### ISSUE TITLE
Slow backend performance with large post/postmeta tables

### ISSUE THREAD

**Issue by LordSimal** [woocommerce/woocommerce-paypal-payments#1012]
### Describe the Bug

The check for `site_has_ppec_subscriptions()` executes a query on every backend page which can be rather expensive on larger datasets.

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/9105243/203265041-d554d06c-533f-49e5-a043-0ca57b1cfd60.png">

### To Reproduce

We have 207574 posts and 10562744 post_meta entries. This results in a rather long query execution time as you can see above.

### Expected Behavior

Query not being executed on every backend request. Maybe cache it in a transient and only execute the expensive query every x hours.

OR

Add a checkbox in the settings which skips executing this query in the first place because there are no ppec subscriptions present.

### Actual Behavior

The expensive query is being executed one every backend request.

### Environment

 - WordPress Version 6.0.3
 - WooCommerce Version 7.1.0
 - Plugin Version 2.0.0
 - Browser Chrome 107.0.5304.110

**Comment by InpsydeNiklas** [comment]
Hi @LordSimal, the migration functionality is enabled automatically but can be disabled with a filter: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-paypal-checkout-gateway-migration-layer-ppec-helper 
For any other questions or suggestions, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
