### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WC_Subscriptions_Synchroniser' not found

### ISSUE THREAD

**Issue by jenniNCA** [woocommerce/woocommerce-paypal-payments#1013]
### Describe the Bug

Trying to view a subscription product produces this fatal error:

Fatal error: Uncaught Error: Class 'WC_Subscriptions_Synchroniser' not found 

### To Reproduce

1. Go to manage paypal payment settings
2. Select " Enable the PayPal Gateway"
3. Click on any subscription product on website 
4. Fatal Error

### Screenshots

Fatal error: Uncaught Error: Class 'WC_Subscriptions_Synchroniser' not found
in /home/customer/www/nightingalecakes.co.uk/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/FreeTrialHandlerTrait.php on line 69

Call stack:

    WooCommerce\P\B\A\SmartButton::is_free_trial_product()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php:416
    WooCommerce\P\B\A\SmartButton::render_button_wrapper_registrar()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php:238
    WooCommerce\P\B\A\SmartButton::render_wrapper()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php:57
    WooCommerce\P\B\ButtonModule::WooCommerce\P\B\{closure}()
    wp-includes/class-wp-hook.php:308
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:332
    WP_Hook::do_action()
    wp-includes/plugin.php:565
    do_action_ref_array()
    wp-includes/class-wp.php:797
    WP::main()
    wp-includes/functions.php:1332
    wp()
    wp-blog-header.php:16
    require()
    index.php:17

### Expected Behavior

Subscription product page should display and be able to subscribe

### Actual Behavior

Fatal error as above. If the Paypal Gateway is **not** enabled the product functions normally and can be purchased as normal

### Environment

 - WordPress Version 6.1.1en_GB
 - WooCommerce Version 7.1.0
 - Plugin Version - 2.0.0
 - Browser [e.g. Chrome, Safari] and Version  Chrome / Firefox both behave the same
 - Any other plugins installed Subscriptions for WooCommerce Version 3.2.6 | By [WebToffee](https://www.webtoffee.com/product/woocommerce-subscriptions/)

### Additional Details

Subscription product is not set up to synchronise and does not have a free trial, it is a payment straight away and then recurring payments. I've tried different settings on the subscription plugin but the only way to resolve this is to disable paypal gateway.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @jenniNCA, PayPal Payments supports automatic recurring payments with [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) plugin.
But the WebToffee subscriptions plugin is not supported, and support for it is currently not planned.

If you encounter any problems with the official WooCommerce Subscriptions plugin, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
