### ISSUE TITLE
Paypal the All in one Checkout does not shown all the Buttons in our Checkout site. 

### ISSUE THREAD

**Issue by naturnahmoebel** [woocommerce/woocommerce-paypal-payments#1018]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by naturnahmoebel** [comment]
Hey Guys, 
we need help with the integration of the new version of paypal checkout: After we actived the Plugin and connected to our Business Account. 
There are no buttons 
<img width="1235" alt="Bildschirmfoto 2022-11-23 um 15 55 41" src="https://user-images.githubusercontent.com/118910745/203578107-e67f9b4a-919b-4840-910d-2a5d81e24df3.png">

[https://www.naturnah-moebel.de/kasse/#step-payment](url)

**Comment by naturnahmoebel** [comment]
We have the multistep Template from Germanized Pro Plugin actived on our Shop.

**Comment by InpsydeNiklas** [comment]
Hi @naturnahmoebel, the payment buttons are displayed where the "Place order" button would be. So they appear on the last step of the Checkout when using the multistep Checkout from the Germanized plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need guidance with setting up the new integration. Thanks!
