### ISSUE TITLE
gateway-settings.js:140 failed to load the PayPal JS SDK script Error: Invalid query value for client-id: Aj8.yGaD................. (debug id: f636886487e91)     at paypal-js.js:209:28

### ISSUE THREAD

**Issue by hafiz-azeem-capslock** [woocommerce/woocommerce-paypal-payments#1022]
I am facing this issue , when activate  Paypal

gateway-settings.js:140 failed to load the PayPal JS SDK script Error: Invalid query value for client-id: Aj8.yGaDEEvG5R4uDtSEL7b94tWUAncdkuGA0gB8Fxy58bRHO9OvjxiW (debug id: f636886487e91)
    at paypal-js.js:209:28

**Comment by InpsydeNiklas** [comment]
Hi @hafiz-azeem-capslock, The credentials may be invalid, so I suggest reconnecting your account using the [onboarding wizard](https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account).
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
