### ISSUE TITLE
Bug on trying to validate Paypal Payments

### ISSUE THREAD

**Issue by wptechnology** [woocommerce/woocommerce-paypal-payments#1030]
### Describe the Bug

The return back URL is not the good one

### To Reproduce

We have created the website on a stagging environnement (with a stagging url).
Then we have moved it to the production environnement, using UpDraft Plus, that move everything correctly.
BUT
When we try to validate the Paypal payments, it is validated by Paypal (it seems too) but the returning URL is the one of the stagging environment... So it never validates on the production of course...
Where can we change the returning URL to be the one that we came from ???

Of course we have tried to uninstall the WC Paypal payments plugin & reintall it, still the same.

### Expected Behavior

Returning to the website URL from which we come

### Actual Behavior

It returns to an old stagging environment

### Environment

`
### WordPress Environment ###

WordPress address (URL): ***masked***
Site address (URL): ***masked***
WC Version: 7.1.0
REST API Version: ✔ 7.1.0
WC Blocks Version: ✔ 8.7.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.25
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.5.17-MariaDB-1:10.5.17+maria~deb11-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.1.0
WC Database Prefix: RfvTmeQD
Total Database Size: 74.68MB
Database Data Size: 63.86MB
Database Index Size: 10.82MB
RfvTmeQDwoocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwoocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
RfvTmeQDwoocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDwoocommerce_order_itemmeta: Data: 0.41MB + Index: 0.38MB + Engine InnoDB
RfvTmeQDwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
RfvTmeQDwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwoocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDactionscheduler_actions: Data: 0.34MB + Index: 0.48MB + Engine InnoDB
RfvTmeQDactionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDactionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDactionscheduler_logs: Data: 0.27MB + Index: 0.23MB + Engine InnoDB
RfvTmeQDcky_banners: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcky_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcky_cookie_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDcleantalk_ac_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcleantalk_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcleantalk_sfw: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
RfvTmeQDcleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDcleantalk_ua_bl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDcommentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDcomments: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
RfvTmeQDfusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDfusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDfusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDfusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDhfcm_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDlinks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDlockdowns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDlogin_fails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDlpc_inward_label: Data: 1.52MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDlpc_outward_label: Data: 21.52MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDmypos_pending_payments_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDoptions: Data: 7.45MB + Index: 0.14MB + Engine InnoDB
RfvTmeQDpostmeta: Data: 13.48MB + Index: 6.03MB + Engine InnoDB
RfvTmeQDposts: Data: 12.20MB + Index: 0.25MB + Engine InnoDB
RfvTmeQDsnippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDstrong_views: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDtermmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDterms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDterm_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDterm_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDtrp_gettext_fr_fr: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
RfvTmeQDtrp_original_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDtrp_original_strings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDusermeta: Data: 0.30MB + Index: 0.30MB + Engine InnoDB
RfvTmeQDusers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDviwec_clicked: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
RfvTmeQDwc_order_stats: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDwc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
RfvTmeQDwc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
RfvTmeQDwoobe_history: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
RfvTmeQDwoobe_history_bulk: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
RfvTmeQDwoostify_filter_index: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwoo_shippment_provider: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
RfvTmeQDwpr_rucss_resources: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
RfvTmeQDwpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Post Type Counts ###

aiosrs-schema: 1
apifw_inv_templates: 1
attachment: 198
avada_faq: 19
custom_css: 2
customize_changeset: 5
elementor_library: 5
fusion_element: 2
fusion_form: 1
fusion_tb_section: 1
hf_builder: 1
language_switcher: 2
nav_menu_item: 35
page: 22
post: 9
product: 15
revision: 576
shop_coupon: 12
shop_order: 204
shop_order_refund: 9
sl-insta-account: 2
sl-insta-feed: 1
sl-insta-media: 6
viwec_template: 1
woo_builder: 3
wpcf7_contact_form: 1
wpm-testimonial: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Amount Left for Free Shipping for WooCommerce: by WPFactory – 2.2.2
Colissimo shipping methods for WooCommerce: by Colissimo – 1.7.3
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.6
Email Templates: by wpexpertsio – 1.3.2.1
WebToffee PayPal Express Checkout Payment Gateway for WooCommerce ( Free ): by WebToffee – 1.7.6
Facebook for WooCommerce: by Facebook – 3.0.4
Avada Builder: by ThemeFusion – 3.8.2
Avada Core: by ThemeFusion – 5.8.2
IONOS Performance: by IONOS – 1.2.3
Login LockDown: by WebFactory Ltd – 1.83
PDF Invoices and Packing Slips For WooCommerce: by Acowebs – 1.3.1
Strong Testimonials: by WPChill – 3.0.2
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.35
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.22.23.25

Advanced Shipment Tracking for WooCommerce: by zorem – 3.5.1
BEAR – Bulk Editor and Products Manager Professional for WooCommerce: by realmag777 – 1.1.2
Product Feed PRO for WooCommerce: by AdTribes.io – 12.0.3
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Payments: by Automattic – 5.0.3
WooCommerce PayPal Payments: by WooCommerce – 2.0.0
WooCommerce: by Automattic – 7.1.0
WordPress Importer: by wordpressdotorg – 0.8
WP Mail SMTP: by WPForms – 3.6.1

### Inactive Plugins (2) ###

WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Shipping & Tax: by WooCommerce – 2.0.0

### Must Use Plugins (1) ###

installatron_hide_status_test.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #9 - /boutique/
Cart: #10 - /panier/
Checkout: #11 - /commander/
My account: #12 - /mon-compte/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada for Laya
Version: (update to version 0 is available)
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.8.2
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce PayPal Payments ###

Onboarded: –
Shop country code: FR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2022-11-28 23:02:06 +01:00
Options: ✔
Notes: 109
Onboarding: completed

### WooCommerce Payments ###

Version: 5.0.3
Connected to WPCOM: No
Blog ID: -
Account ID: -

### Action Scheduler ###

Canceled: 6
Oldest: 2022-10-31 17:33:34 +0100
Newest: 2022-11-21 10:47:43 +0100

Complete: 1,119
Oldest: 2022-10-28 17:54:43 +0200
Newest: 2022-11-28 16:02:47 +0100

Pending: 3
Oldest: 2022-11-28 22:17:31 +0100
Newest: 2022-12-02 13:23:37 +0100

### Status report information ###

Generated at: 2022-11-28 16:08:02 +01:00
`

</details>

**Comment by Sirvijver** [comment]
Hello @wptechnology,

Thank you for reaching out to us, we are here to help. What I think you should do is to disconnect your PayPal account from the live site and reconnect it using the onboarding wizard. This will create a new REST API, and this will save the correct return URL. The previous attempt likely has the staging site URL stored. Reinstalling the plugin does not do anything, except renewing the webhooks.
If this does not help you resolve the issue, and you require additional support, please open a support [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We only use GitHub for development activities, and this is why I will close this support request.

Kind regards, 
Joost
