### ISSUE TITLE
Persistent create_order_error => 'Please Enter Address To Continue'

### ISSUE THREAD

**Issue by weronikasiuda** [woocommerce/woocommerce-paypal-payments#1031]
The same issue as https://wordpress.org/support/topic/please-enter-address-to-continue/.

WordPress version: 6.1.1.
WooCommerce version: 7.1.0
plugin version:  2.0.0

Client reports that customers cannot complete orders.

**Comment by clearclicks** [comment]
same issue here with identical setup (WordPress version: 6.1.1., WooCommerce version: 7.1.0, plugin version: 2.0.0)

temporarily, solution described in #issue1025 https://github.com/woocommerce/woocommerce-paypal-payments/issues/1025 fixes it somehow, but I would appreciate a real bugfix.

**Comment by Sirvijver** [comment]
Hello @weronikasiuda and @clearclicks 

We already have this issue open in another GitHub thread, so I will close this one. Please follow the [linked GitHub issue](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1025) if you want to be up-to-date about any changes. If you want to have our support team look into your specific situation, I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
