### ISSUE TITLE
Disfonctionnement Paiement Paypal 

### ISSUE THREAD

**Issue by BonheurTricotin** [woocommerce/woocommerce-paypal-payments#1033]
Le paiement Paypal ne fonctionne plus avec mes clients depuis la semaine dernière. 
Le plug-in semble pourtant bien installé et configurer sur WordPress. 
Pouvez vous m'aider ? 
Merci

**Comment by Sirvijver** [comment]
Hello @BonheurTricotin 

Thanks for reaching out to us. We want to help you, but we only use GitHub for development activities and would like to ask you to open a direct thread with us via[ these instructions](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Please don't forget to add the system report and any known details about the issue that you can share.

I will close this thread and wait for the support request to reach our team.

Kind regards, 
Joost
