### ISSUE TITLE
PayPal api error "429 Too Many Requests"

### ISSUE THREAD

**Issue by NHZEX** [woocommerce/woocommerce-paypal-payments#1034]
### Describe the Bug

Incorrect configuration parameters cause the request to go on indefinitely, resulting in a "429 Too Many Requests" error.

### To Reproduce

Enter invalid configuration parameters.

### Screenshots

![Snipaste](https://user-images.githubusercontent.com/14545600/204454221-b74cc123-6678-44bf-9d0c-546303ef6b26.png)

### Expected Behavior

Notify user of authentication failure, please check input.

### Actual Behavior

No tips. Duplicate requests resulting in denied access.

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.1.0
 - Plugin Version: 2.0.0
 - Browser: Edge 107.0.1418.56

### Additional Details

```
2022-11-29T04:54:35+00:00 WARNING Could not create token.
2022-11-29T04:54:35+00:00 DEBUG POST https://api.sandbox.paypal.com/v1/oauth2/token?grant_type=client_credentials
Response Debug ID: 69900cf9a4eee
Response: Array
(
    [code] => 401
    [message] => Unauthorized
)

Response Body: {"error":"invalid_client","error_description":"Client Authentication failed"}

2022-11-29T04:54:35+00:00 WARNING Could not create token.
2022-11-29T04:54:36+00:00 DEBUG POST https://api.sandbox.paypal.com/v1/oauth2/token?grant_type=client_credentials
Response Debug ID: 69900cdcf95c1
Response: Array
(
    [code] => 429
    [message] => Too Many Requests
)
```

**Comment by femiyb** [comment]
Hello @NHZEX 

Please [reach out to the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for assistance with this issue. Thanks!

regards,
Femi.
