### ISSUE TITLE
WooCommerce PayPal Payments - could not retrieve order

### ISSUE THREAD

**Issue by JustinaZak** [woocommerce/woocommerce-paypal-payments#1036]
### Describe the Bug

 - WordPress Version 7.1.0
 - WooCommerce Version 6.1.1
 - Plugin Version WooCommerce PayPal Payments  2.0
 - Browser [e.g. Chrome, Safari] and Version Edge
 - Any other plugins installed
Astra Pro |   | przez Brainstorm Force – 3.9.3
Premium Starter Templates |   | przez Brainstorm Force – 3.1.18
Better Search Replace |   | przez Delicious Brains – 1.4.1
CartFlows |   | przez CartFlows Inc – 1.11.6
Cookie Notice & Compliance dla RODO / CCPA |   | przez Hu-manity.co – 2.4.2
Monitor Pobierania |   | przez WPChill – 4.7.53
Elementor Pro |   | przez Elementor.com – 3.7.3
Elementor |   | przez Elementor.com – 3.8.1
Elementor Header & Footer Builder |   | przez Brainstorm Force, Nikhil Chavan – 1.6.13
Headers Security Advanced & HSTS WP |   | przez  Andrea Ferro, Augusto Bombana – 5.0.06
Limit Login Attempts Reloaded |   | przez Limit Login Attempts Reloaded – 2.25.9
Loco Translate |   | przez Tim Whitlock – 2.6.3
MailerLite - Signup forms (official) |   | przez MailerLite – 1.6.1
Premium Addons for Elementor |   | przez Leap13 – 4.9.39
Presto Player |   | przez Presto Made, Inc – 1.10.1
WooCommerce Przelewy24 Payment Gateway |   | przez Przelewy24 Sp. z o.o. – 1.0.0
Really Simple SSL |   | przez Wtyczki Really Simple – 6.0.11
W3 Total Cache |   | przez BoldGrid – 2.2.7
WooCommerce Cart Abandonment Recovery |   | przez CartFlows Inc – 1.2.20
Checkout Field Editor for WooCommerce |   | przez ThemeHigh – 1.8.0
WooCommerce Fakturownia by wphocus |   | przez WPhocus – 1.6.8
WooCommerce PayPal Payments |   | przez WooCommerce – 2.0.0
WooCommerce |   | przez Automattic – 7.1.0
WPForms Lite przez WPForms – 1.7.8

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @JustinaZak 
Thank you for reaching out to us. We want to help you, but we use GitHub only for developers activities, so we want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. 
This error is known to us, but we want to ask you to provide the complete system report, so we can take a look at your site and specifics ourselves.

Kind regards, 
Joost
