### ISSUE TITLE
Wrong price when discounted via plugin

### ISSUE THREAD

**Issue by pandiit** [woocommerce/woocommerce-paypal-payments#1039]
### Describe the Bug

Using WooCommerce PayPal Paymants with discount plugin generate wrong price in orders. 

### To Reproduce

1. Enable discount via WooCommerce Dynamic Pricing & Discounts by RightPress
2. Add discounted product to cart
3. Select PayPal payment
4. See error in price (price isn't discounted)

### Quick fix 
Back to using PayPal Standard with API

</details>

**Comment by Sirvijver** [comment]
Hello @pandiit 

The issue you reported here, sound to be a plugin conflict that needs to be reviewed and tested. We do not use GitHub for support requests, so you will need to open a support request via [.org](https://wordpress.org/plugins/woocommerce-paypal-payments/) or via our support desk, following [these instructions](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

I will close this support request here on GitHub.

Kind regards, 
Joost
