### ISSUE TITLE
pay later paypal bug

### ISSUE THREAD

**Issue by finouch** [woocommerce/woocommerce-paypal-payments#1042]
paypal bug pay later in my woocommerce

**Comment by leonardola** [comment]
Hello @finouch could you please explain a little bit more about this bug? 
How do we simulate it? 
What happens? 
What should happen?
What is your environment? Server, browser, OS, etc
Please post your System report here. You can find it on WooCommerce > Status > Get System report.

**Comment by finouch** [comment]
Hello 
Thanks for reaching me, i fixed it it was in pay pal pay later i couldn’t clickon it ´ but it has been fixed 
Thank you so much
