### ISSUE TITLE
County Is an optional field (For UK payments) but required by Paypal?

### ISSUE THREAD

**Issue by jjma** [woocommerce/woocommerce-paypal-payments#1045]
I'm using the Woocommerce One Page checkout plugin with Paypal which works well for US customers however in the UK if a customer doesn't add the County field and clicks on Pay with Paypal the payment fails. 

The error is: Billing State is a required field. --> This is firstly confusing as State is not a field label, County is. Secondly, county is an optional field so it shouldn't fail. If you add the County the payment goes through. 

Occurs in all browsers.

Paypal Payments Version 2.0.0
Woocommerce Version 7.1.0
Wordpress Version 6.1.1

**Comment by Sirvijver** [comment]
Hello @jjma 

Thank you for reaching out to us, we are here to help. We only use GitHub for development requests, and this seems to be a support issue. We would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please include the full system report, so we can try to recreate the issue you are facing. I will close this ticket.

Kind regards, 
Joost
