### ISSUE TITLE
Using existing Woocommerce checkout button

### ISSUE THREAD

**Issue by virajsoni06** [woocommerce/woocommerce-paypal-payments#1049]
Hi, the plugin renders its own Pay buttons which is fine for some users. However there's no config setting I can find which I can modify to use existing checkout button which is shipped with Woocommerce

![image](https://user-images.githubusercontent.com/13236286/204804633-a5093262-38a3-4d61-b41b-37d533b23784.png)
You can notice in the image above, there are separate buttons rendered by PayPal. Is there a way we can use the existing Woocommerce checkout button?

Thanks

**Comment by femiyb** [comment]
Hello @virajsoni06 

The plugin is set up so it replaces the default WooCommerce "Place Order" button to display the PayPal payment buttons. Both the default button and the PayPal buttons should not appear on your site at the same time.

For further assistance, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for guidance. Thanks!

Regards,
Femi.
