### ISSUE TITLE
paypal payment only issues

### ISSUE THREAD

**Issue by BoostedDiamonds** [woocommerce/woocommerce-paypal-payments#1053]
1. go to www.boosteddiamonds.com
2. select an item to purchase and add to cart
3. follow check out procedure and use paypal as payment option
4. "order not retrievable" error upon placing order. 

![316783880_471364305107836_8375938456034998110_n](https://user-images.githubusercontent.com/119539403/204906723-040a33d3-4b72-4177-99b7-34a68eb92b0e.jpg)

### To Reproduce

1. Go to '…'
6. Click on '…'
7. Scroll down to …'
8. See error

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @BoostedDiamonds 

the issue you are encountering is a common issue. The issue occurs mostly when the WooCommerce "Place Order" button is not correctly replaced with our PayPal button. If you use the WooCommerce button, you will get the error "Could not retrieve order".
This issue can occur when a plugin or the theme blocks our AJAX script from replacing the button. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We don't manage support requests via GitHub, so we will close this request. If you require additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
