### ISSUE TITLE
errors in comments in paypal orders

### ISSUE THREAD

**Issue by syntaxmedia** [woocommerce/woocommerce-paypal-payments#1058]
### Describe the Bug

In admin in all orders we can see a lot of these comments:
Couldn’t sync tracking information: [Error] Unknown error while connecting to PayPal. Status code: 0.

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 7.0.0
 - Plugin Version 2.0.0

**Comment by Sirvijver** [comment]
Hello @syntaxmedia 

the issue you are encountering could be related to your account details. You should try disconnecting and onboarding the plugin again (creating a new REST API in the process) using the connect wizard.

If that does not fix the issue, you probably should open a support thread on our support environment. We primarily use GitHub for development, not for support. You can raise a support request following [these instructions](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Kind regards, 
Joost
