### ISSUE TITLE
Payment gateway shows multiple errors after last update and payments not processing

### ISSUE THREAD

**Issue by Morrinaaus** [woocommerce/woocommerce-paypal-payments#1060]
edited post - error is mentioned on this forum and is a conflict between woocommerce paypal payments and wp armours honey pot extended version

[forum post](https://wordpress.org/support/topic/spamming-your-javascript-is-disabled/)

**Comment by Sirvijver** [comment]
Hello @Morrinaaus 

We use GitHub only for developers cases, and this is clearly a case that requires a support thread. I would advise you to open such a support thread on [wp.org](https://wordpress.org/support/plugin/woocommerce-paypal-payments/) or via [these instructions directly with our support team](https://paypal.inpsyde.com/docs/request-support/).

Closing this GH thread for now.

Kind regards, 
Joost
