### ISSUE TITLE
Hosted fields already in progress when trying to pay with onsite card payment

### ISSUE THREAD

**Issue by R-Flo** [woocommerce/woocommerce-paypal-payments#1061]
### To Reproduce

1. Go to 'the checkout page'
2. Fill out the form 
3. Select the payment gateway
4. Fill out the payment form
5. Submit

### Screenshots

![image](https://user-images.githubusercontent.com/2573981/205655092-a00216a7-951a-43b1-bb06-6c3381018766.png)

![image](https://user-images.githubusercontent.com/2573981/205655194-71d6cbd1-71de-4a1c-aabf-5d320c396fd5.png)

### Expected Behavior

It should simply work when i'm paying, opening 3DS window are redirect right awat the the thank you page

### Actual Behavior

I cannot complete the order because of the hosted fields error

### Environment

 - WordPress Version : 6.1.1
 - WooCommerce Version : 7.1.0
 - Plugin Version : 2.0.0
 - Browser [e.g. Chrome, Safari] and Version : Chrome 108.0.5359.71
 - Any other plugins installed : Other payment gateways such as Klarna et stripe

<details><summary>System status</summary>

`
### wp-core ###

version: 6.1.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 5
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/runcloud/webapps/feelnov
wordpress_size: 250,29 Mo (262446774 bytes)
uploads_path: /home/runcloud/webapps/feelnov/wp-content/uploads
uploads_size: 25,26 Mo (26488362 bytes)
themes_path: /home/runcloud/webapps/feelnov/wp-content/themes
themes_size: 5,29 Mo (5546601 bytes)
plugins_path: /home/runcloud/webapps/feelnov/wp-content/plugins
plugins_size: 330,41 Mo (346461303 bytes)
database_size: 153,22 Mo (160661504 bytes)
total_size: 764,47 Mo (801604544 bytes)

### wp-active-theme ###

name: Feelnov (feelnov)
version: 1.0.0
author: Kaffein Agency
author_website: https://kaffein.agency
parent_theme: Twenty Fifteen (twentyfifteen)
theme_features: core-block-patterns, wc-product-gallery-lightbox, wc-product-gallery-slider, woocommerce, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, post-formats, custom-logo, custom-background, editor-style, editor-styles, wp-block-styles, responsive-embeds, editor-color-palette, editor-gradient-presets, customize-selective-refresh-widgets, custom-header, widgets
theme_path: /home/runcloud/webapps/feelnov/wp-content/themes/feelnov
auto_update: Désactivé

### wp-parent-theme ###

name: Twenty Fifteen (twentyfifteen)
version: 3.3
author: L’équipe WordPress
author_website: https://wordpress.org/
theme_path: /home/runcloud/webapps/feelnov/wp-content/themes/twentyfifteen
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.0, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-mu-plugins (7) ###

add_checkout_cgv_checkbox.php: author: (undefined), version: (undefined)
cart_totals.php: author: (undefined), version: (undefined)
disable_payment_gateway_for_countries.php: author: (undefined), version: (undefined)
gateway_icons.php: author: (undefined), version: (undefined)
google_tag_manager.php: author: (undefined), version: (undefined)
product_view_button.php: author: (undefined), version: (undefined)
shortcode_category_page_title.php: author: (undefined), version: (undefined)

### wp-plugins-active (26) ###

Advanced Order Export For WooCommerce: version: 3.3.3, author: AlgolPlus, Mises à jour auto activées
AFL UTM Tracker: version: 2.6.2, author: Appfromlab, Mises à jour auto désactivées
Cookiebot CMP by Usercentrics | The reliable, flexible and easy to use consent solution: version: 4.2.1, author: Usercentrics A/S (latest version: 4.2.2), Mises à jour auto activées
CookieYes | GDPR Cookie Consent: version: 3.0.6, author: CookieYes, Mises à jour auto désactivées
Divi Builder: version: 4.19.2, author: Elegant Themes, Mises à jour auto activées
Favicon by RealFaviconGenerator: version: 1.3.25, author: Philippe Bernard, Mises à jour auto désactivées
FluentSMTP: version: 2.2.2, author: FluentSMTP & WPManageNinja Team, Mises à jour auto activées
Icegram Express - Email Subscribers, Newsletters and Marketing Automation Plugin: version: 5.5.1, author: Icegram, Mises à jour auto activées
Jetpack: version: 11.5.1, author: Automattic, Mises à jour auto activées
Payment Plugins for Stripe WooCommerce: version: 3.3.34, author: Payment Plugins, support@paymentplugins.com, Mises à jour auto activées
RunCloud Hub: version: 1.2.1, author: RunCloud, Mises à jour auto activées
WooCommerce: version: 7.1.0, author: Automattic, Mises à jour auto activées
WooCommerce Multilingual & Multicurrency: version: 5.0.2, author: OnTheGoSystems, Mises à jour auto activées
WooCommerce PayPal Payments: version: 2.0.0, author: WooCommerce, Mises à jour auto activées
WooCommerce Shipping & Tax: version: 2.1.0, author: WooCommerce, Mises à jour auto activées
WooCommerce Stripe Gateway: version: 7.0.1, author: WooCommerce, Mises à jour auto activées
Woo Discount Rules: version: 2.5.2, author: Flycart, Mises à jour auto activées
WP-SCSS: version: 3.0.0, author: Connect Think, Mises à jour auto activées
WP All Import: version: 3.7.1, author: Soflyy, Mises à jour auto activées
WPML All Import: version: 2.3.0, author: OnTheGoSystems, Mises à jour auto activées
WPML CMS Nav: version: 1.5.5, author: OnTheGoSystems, Mises à jour auto activées
WPML Media: version: 2.7.1, author: OnTheGoSystems, Mises à jour auto activées
WPML Multilingual CMS: version: 4.5.14, author: OnTheGoSystems, Mises à jour auto activées
WPML SEO: version: 2.1.0, author: OnTheGoSystems, Mises à jour auto activées
WPML String Translation: version: 3.2.3, author: OnTheGoSystems, Mises à jour auto activées
Yoast SEO: version: 19.11, author: Team Yoast, Mises à jour auto activées

### wp-plugins-inactive (7) ###

Advanced Custom Fields Multilingual: version: 2.0.0-beta1, author: OnTheGoSystems, Mises à jour auto activées
Contact Form 7: version: 5.6.4, author: Takayuki Miyoshi, Mises à jour auto activées
OTGS Installer: version: 3.0.4, author: OnTheGoSystems, Mises à jour auto activées
PDF Invoices & Packing Slips for WooCommerce: version: 3.2.5, author: WP Overnight, Mises à jour auto activées
WooCommerce Payments: version: 5.1.2, author: Automattic, Mises à jour auto activées
Wordfence Security: version: 7.8.0, author: Wordfence, Mises à jour auto activées
WP Rollback: version: 1.7.2, author: GiveWP.com, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Non disponible
imagemagick_version: Non disponible
imagick_version: Non disponible
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 Mo
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-90-generic x86_64
httpd_software: nginx/1.21.4
php_version: 8.0.25 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.5.18-MariaDB-1:10.5.18+maria~ubu2004
client_version: mysqlnd 8.0.24
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/runcloud/webapps/feelnov/wp-content
WP_PLUGIN_DIR: /home/runcloud/webapps/feelnov/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indéfini
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 211180197
ssl_cert: No
time_diff: false
version_option: 11.5.1:1670008966
old_version: 11.5.1:1670008966
public: Public
master_user: Aucun utilisateur principal configuré.
current_user: #1 ContactKaffein
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 11.5.1
jp_plugin_dir: /home/runcloud/webapps/feelnov/wp-content/plugins/jetpack/
plan: free
protect_header: false
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/feelnov.com","siteurl":"https:\/\/feelnov.com","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: {"8":{"name":"test__connection_token_health","label":false,"short_description":"\u00c9chec de la validation du jeton de blog.","long_description":"<p>Une connexion solide garantit la fourniture des services essentiels de Jetpack pour votre site WordPress, comme les statistiques et la s\u00e9curit\u00e9 de site.<\/p><p><span class=\"dashicons fail\"><span class=\"screen-reader-text\">Erreur<\/span><\/span> \u00c9chec de la validation du jeton de blog.<\/p><p><strong>Nous recommandons de reconnecter Jetpack.<\/strong><\/p>","severity":"critical","action":"https:\/\/feelnov.com\/wp-admin\/admin.php?page=jetpack#\/reconnect","action_label":"Reconnecter Jetpack maintenant","show_in_site_health":true,"pass":false,"group":["default"],"type":"direct"}}

`
</details>

**Comment by nicdwilson** [comment]
5770499-zen

Rolling back to v1.9.4 solved this issue

**Comment by Sirvijver** [comment]
Hello @R-Flo 

We have already a [GH issue](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1011) for this case.
Please follow this linked issue, so we can close this duplicate thread.

Kind regards, 
Joost
