### ISSUE TITLE
Recurring payments always failing

### ISSUE THREAD

**Issue by jtomara** [woocommerce/woocommerce-paypal-payments#1062]
### Describe the Bug

This plugin does not properly process any subscriptions whether it be initial or renewals. We've already brought this issue to PayPal and they have adamantly expressed this is not their issue and we are the only ones reporting this issue to them.

### To Reproduce

1. Go to any subscription product and try to checkout with PayPal. Whether it be an initial purchase or a renewal, the transactions always fail and show refunded in Woocommerce. PayPal has insisted this isn't their issue.
2. Click on  https://jailbirds.com/annual-subscriptions/
3. Select any product - add to cart - try to checkout with paypal and you'll see it immediately get put on hole .. then fail.. then refund (but it never does any of that on PayPals side) PayPal does receive the request, but something is wrong with the API so they do not process it.

### Screenshots

https://jtomara.com/james/jb-cancelled.png
https://jtomara.com/james/jb-onhold.png

### Expected Behavior

Payment should process normally

### Actual Behavior

Payment always fails

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.1.0
 - Plugin Version 2.0.0
 - Browser [e.g. Chrome, Safari] and Version - All
 - Any other plugins installed
   A ad-inserter                                  2.7.22
  A akismet                                      5.0.2
  I all-in-one-wp-migration                      7.68
  I all-in-one-wp-migration-s3-extension         3.58
  I all-in-one-wp-migration-unlimited-extension  2.46
  A amp                                          2.3.0
  A automatewoo                                  5.6.0
  I better-search-replace                        1.4.1
  A custom-api-for-wp                            2.5.1
  A ewww-image-optimizer                         6.9.2
  A facebook-for-woocommerce                     3.0.5
  A woocommerce-follow-up-emails                 4.9.33
  I google-analytics-for-wordpress               8.10.1
  A happyforms-upgrade                           1.34.0
  A leadin                                       9.2.12
  A mailchimp-for-woocommerce                    2.7.6
  A google-analytics-premium                     8.7.0
  A printful-shipping-for-woocommerce            2.1.34
  A searchwp                                     4.2.8
  A searchwp-customisations                      1.0.0
  A searchwp-metrics                             1.4.2
  A searchwp-woocommerce                         1.3.10
  A searchwp-xpdf                                1.3.0
  A google-site-kit                              1.88.0
  A string-locator                               2.6.1
  A td-cloud-library                             2.3 | built on 05.10.2022 13:12
  A td-composer                                  3.7 | built on 17.11.2022 13:12
  A td-mobile-plugin                             2.1 | built on 05.10.2022 13:12
  A td-newsletter                                1.7 | built on 05.10.2022 13:12
  A td-subscription                              1.3.3 | built on 05.10.2022 13:12
  A td-woo                                       1.6 | built on 05.10.2022 13:12
  A td-social-counter                            5.1 | built on 28.11.2022 11:24
  A td-standard-pack                             1.5 | built on 05.10.2022 13:12
  A updraftplus                                  1.22.23
  A user-role-editor                             4.63.1
  A woocommerce                                  7.1.0
  A coinpayments-payment-gateway-for-woocommerce 1.0.14
  A woocommerce-payments                         5.1.2
  A woocommerce-paypal-payments                  2.0.0
  A woocommerce-subscription-downloads           1.3.0
  A woocommerce-subscriptions                    4.6.0
  A wordfence                                    7.8.0
  A wp-optimize-premium                          3.2.9
  A insert-headers-and-footers                   2.0.4.4
  A wp-fastest-cache                             1.0.8
  A wp-fastest-cache-premium                     1.6.8
  A wp-file-manager                              7.1.6
  A wp-google-maps                               9.0.13
  A wp-google-maps-pro                           8.1.20
  A wp-mail-smtp                                 3.6.1
  I wp-mail-smtp-pro                             3.5.1
  A amazon-s3-and-cloudfront-pro                 3.0.2
  I amazon-s3-and-cloudfront                     3.0.2
  A wordpress-seo                                19.11

### Additional Details

Woocommerce PayPal plugin logs
https://jtomara.com/james/jb-wc-paypal-logs.txt

<details><summary>System status</summary>

https://jtomara.com/james/wc-system-report.txt

</details>

**Comment by Sirvijver** [comment]
Hello,

Thank you for reaching out to us, we are here to help. We only use GitHub for development case and this seems to be a support request. We will close this request and ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
