### ISSUE TITLE
PayPal Business sign-in issue?

### ISSUE THREAD

**Issue by 844servyou** [woocommerce/woocommerce-paypal-payments#1063]
Hello, we're trying to get help with WooCommerce PayPal Payments. When we sign into our business account, the submission sticks on a blank page. We're new to WooCommerce PayPal Payments. Any help would be greatly appreciated. Thank you!

**Comment by Sirvijver** [comment]
Hello @844servyou 

Our plugin is supported via other site, we advised to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

However, this issue sound more like a PayPal (not a plugin) issue, so you might want to reach out to [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) instead.

I will close this support request and mark it as such.

Kind regards, 
Joost
