### ISSUE TITLE
Infinite loop when connecting with paypal account

### ISSUE THREAD

**Issue by javiersalazar87** [woocommerce/woocommerce-paypal-payments#1067]
Infinite loop when connecting with paypal account

**Comment by Sirvijver** [comment]
Hello @javiersalazar87 

I want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. The GitHub site we only use for development purposes of issue that have been reproduced and require a fix from our developers. We can help you with your support request, but we want to ask you to open a ticket via the linked site above.

Kind regards, 
Joost
