### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by pyramed22** [woocommerce/woocommerce-paypal-payments#1070]
### To Reproduce

When a customer uses PayPal payments, I get an error report
See https://pyramed.org

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.1.1
 - PayPal Plugin Version 2.0.0
 - Brave Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (64-bit)]
 - Any other plugins installed. Yes 20

### Additional Details

<details><summary>System recovered and useable</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
Hello @pyramed22 

Please [reach out to the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for assistance with this issue. Thanks!
