### ISSUE TITLE
Option to vault new payment methods missing on the /your-account/ppcp-paypal-payment-tokens/ page

### ISSUE THREAD

**Issue by isabelhuerta24** [woocommerce/woocommerce-paypal-payments#1073]
It makes a bad user experience that in order to vault a payment method they have to make  a purchase first on the checkput page.

It could be a great feature to have that done on the  /your-account/ppcp-paypal-payment-tokens/ page as well as being able to set a default payment method in order to better manage the payments for better user exprience.

Or is ther any external addon or plugin that can help do that?

**Comment by InpsydeNiklas** [comment]
Thanks for the suggestion.
The custom payment tokens endpoint is currently being migrated to the WooCommerce native endpoint: #1059
The goal is to also provide users the opportunity to save a payment method from the my-account section. 

> It makes a bad user experience that in order to vault a payment method they have to make a purchase first on the checkput page.

Unfortunately, [Vault v2](https://developer.paypal.com/limited-release/vault-payment-methods/vault-sdk) (which the plugin implements) does not support vaulting a payment method without a payment. A workaround for this was only recently implemented, e.g. to make free-trial subscriptions possible, and it may also be reused to save a payment method from the my-account section once the payment token migration has been completed.

Sometime next year, integration will be upgraded to use [Vault v3](https://developer.paypal.com/beta/multiparty/vault/), which provides additional features, such as natively saving a payment method without a purchase, simplifying the entire process.

> Or is ther any external addon or plugin that can help do that?

As of the latest version, the only way for the buyer to save a payment method without completing a real payment is by purchasing a "free subscription" with the WooCommerce Subscriptions plugin. So when setting up a free trial or prorated subscription or a subscription with a 100% coupon, the buyer could save the payment method without moving any funds. 
But they would still have to go through what is essentially the [same checkout procedure](https://woocommerce.com/document/woocommerce-paypal-payments/#free-trials).
Better token management can be expected with the next feature update sometime in January.

If anything remains unclear, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
