### ISSUE TITLE
Something went wrong. Please try again or choose another payment source.

### ISSUE THREAD

**Issue by mashalshaikh95** [woocommerce/woocommerce-paypal-payments#1081]
### To Reproduce

I am facing an error "Something went wrong. Please try again or choose another payment source" when I click on PayPal on woocommerce checkout

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @mashalshaikh95 

Thank you for reaching out to us. We do not support our plugin via GitHub and would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
We try to only use GitHub for development activities, so will close this request here.

The issue you are reporting (Something went wrong. Please try again or choose another payment source) is a common error, and we would need to see your system report, our plugin logs and any screenshot that could help clear up what you are encountering. Please also tell us if you are able to reproduce the issue.

Kind regards, 
Joost
