### ISSUE TITLE
Requiring not required fields

### ISSUE THREAD

**Issue by agnesebm** [woocommerce/woocommerce-paypal-payments#1083]
Plugin is requiring to fill all checkout form fields even some of them have rules applied and are hidden. And "Card billing data handling" is set to "Do not use WC checkout form data". Any other payment methods works fine, so I assume the Checkout form editor plugin is not guilty.

To Reproduce: 
1. go to ziedijelgava.lv store, 
2. choose any product
3. at checkout form choose Piegāde - Saņemt veikalā (Delivery - receive at store), it will hide other delivery fields that are not relevant at this case. 
4. Then choose Paypal as payment method. 
5. Validation message appears to fill all required fields, even these are hidden and not required at this case.

### Expected Behavior

Non of checkout form fields should be passed to the Paypal plugin.

### Environment

 - WordPress Version 5.9.5
 - WooCommerce Version 7.1.1
 - Plugin Version 2.0.1
 - Browser: Microsoft Edge 108.0.1462.46, Chrome 108.0.5359.99
 - Any other plugins installed: Checkout Field Editor for WooCommerce (Pro)

**Comment by Sirvijver** [comment]
Hello @agnesebm 

Thank you for reaching out. However, we do not do plugin support via the GitHub forum and I would need to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

It looks like the process you use to hide the delivery fields, does not do it in a way that our plugin understands the fields are not required. Please open a support thread with us including the system report, so we can take a look at this and possibly recreate the issue for us to understand what is happening and possibly get our developers involved to create a fix for this.

Kind regards, 
Joost
