### ISSUE TITLE
PayPal button markup is always displayed on single product page, regardless of setting

### ISSUE THREAD

**Issue by alexanderaltendorfer** [woocommerce/woocommerce-paypal-payments#1086]
### Describe the Bug

The PayPal checkout button markup is always displayed on the single product page, regardless of the setting of the "Enable buttons on Single Product" checkbox.

The reason for this is a mismatch with the settings key. The checkbox is saved with the key 'button_product_enabled' but in SmartButton.php:409 the key 'button_single_product_enabled' is used. This results in $not_enabled_on_product_page always being false.

### To Reproduce

1. Go to a product page
2. Toggle "Enable buttons on Single Product" checkbox
3. See that the button markup is always displayed, regardless of the setting

### Expected Behavior

The settings checkbox should toggle the button markup output

### Actual Behavior

The settings checkbox does not toggle the button markup output. This can cause issues with custom styles or themes.

### Environment

 - WordPress Version 6.0.3
 - WooCommerce Version 6.6.1
 - Plugin Version 2.0.1

**Comment by Sirvijver** [comment]
Hello @alexanderaltendorfer 

Sorry for the long delay, it seems this thread was lost during the holiday season.

We do no use GitHub for support activities, so we want to advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you need more guidance.

Can you open a support thread with us and provide the system report and logs to this support request, so we can take a closer look?

We will close this GitHub thread and wait for you to open the support thread with us.

Kind regards, 
Joost
