### ISSUE TITLE
No me funciona PayPal Payments

### ISSUE THREAD

**Issue by SmartEstudio** [woocommerce/woocommerce-paypal-payments#1087]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you have any further questions. Thanks!
