### ISSUE TITLE
Could not retrieve order when changing subscription payment method without a payment token (461)

### ISSUE THREAD

**Issue by PedroPessuto** [woocommerce/woocommerce-paypal-payments#1088]
### Describe the Bug

Hello, I'm facing a problem when using "WooCommerce PayPal Payments" plugin in version 2.0.1 with WooCommerce Subscriptions version 4.7.0. Wordpress is at version 6.1.1.

It turns out that when trying to create a subscription/purchase order manually and then trying to add the automatic payment using Paypal, the error appears: "Could not retrieve order". For example: I, as an administrator, create a subscription manually, after that the user, when trying to renew the subscription, must use Paylpal, but when selecting it, the error occurs.

### To Reproduce

1. Create a subscription manually as admin
2. Trying to renew the subscription (created before) as user
3. Select Paypal as payment method 

### Screenshots

![Error](https://user-images.githubusercontent.com/116746646/207968369-3d244c1b-17df-4f06-a320-5fc8c4ef00f3.png)

### Expected Behavior

accept renewal using Paypal

### Actual Behavior

reject renewal using Paypal

###  Environment
WordPress Version : 6.1.1
WooCommerce Subscriptions: 4.7.0
WooCommerce PayPal Payments:  2.0.1

**Comment by PedroPessuto** [comment]
It is also worth mentioning that there is an error when buying a subscription using Paypal, it is only accepting fixed prices.

**Comment by creative-andrew** [comment]
Same error here.

**Comment by InpsydeNiklas** [comment]
Hi @PedroPessuto,
Changing a subscription payment method to PayPal or Advanced Card Processing requires a saved payment method:
![image](https://user-images.githubusercontent.com/70433191/209987493-b1ce5676-0ff4-46b6-9a19-6cd77aa65224.png)
Changing the payment method without a saved payment method (in the Vault) results in this error.
So the buyer must first save the payment method with a purchase before an existing subscription could be switched to it.

The payment token management is currently being reworked, so this error will be resolved in one of the next updates.

**Comment by InpsydeNiklas** [comment]
Closing this as it duplicates  #434
