### ISSUE TITLE
Paypal button not showing

### ISSUE THREAD

**Issue by ilfarhanahmed** [woocommerce/woocommerce-paypal-payments#1090]
### Describe the Bug

Even though the paypal payment option is active within Woocommerce settigns, it is not showing on the checkout page.
Woocommerce is connected perfectly with the Paypal account, stripe and other options are working fine, buy paypal button is not showing up.

Website
https://licenzeillimitate.com/pagamento/

 - WordPress Version: WordPress 6.1.1
 - WooCommerce Version: Version 7.2.0
 - Plugin Version: Version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version: Tried on all the latest browsers including Firefox and Opera.
 - Any other plugins installed: WooCommerce Stripe Gateway, WooCommerce Payments

</details>

**Comment by InpsydeNiklas** [comment]
Looks like this page is using the WooCommerce Checkout Block, which PayPal Payments does not yet support: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-does-paypal-payments-support-blocks
Support for this new Checkout is in development, but for now it only works with the regular shortcode checkout.
If any questions remain, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) to receive further guidance. Thanks!
