### ISSUE TITLE
PayPal button for WooCommerce Wordpress not working

### ISSUE THREAD

**Issue by OxorOnceAgain** [woocommerce/woocommerce-paypal-payments#1092]
### Describe the Bug

A button for PayPal payment for WooCommerce should be showing in the cart section when the PayPal option is selected. Still, it does not show, even changing the layout configuration for the PayPal button within the PayPal Payments plugin for WooCommerce.

The plugin is called "WooCommerce PayPal Payments" and it's running in the 2.0.1 version for the WooCommerce 7.2.1 version.

Simply the button doesn't load once you select the PayPal option.

Already tried uninstalling all other plugins. It did not change anything.

### To Reproduce

1. Go to https://olegisar.org/courses/ and try to buy a course.
2. Click on _Introducción al neuroderecho_ and then _carrito_.
3. Scroll down and try to pay with PayPal.
4. See error.

### Screenshots

![image](https://user-images.githubusercontent.com/120618325/208688606-d71a49ca-e614-43f9-b8d7-7fccfcd40c32.png)

### Expected Behavior

There should appear a button for PayPal payment.

### Actual Behavior

The button loads indefinitely.

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.2.1
 - Plugin Version 2.0.1 
 - Browser Brave and Firefox (same problem)
 - Plugins installed:

![image](https://user-images.githubusercontent.com/120618325/208691623-5fe2bf8f-9974-447c-8383-3843971d6d31.png)

### Additional Details

WooCommerce working with Tutor LMS 2.1.3.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @OxorOnceAgain,
 `ARS` is not a supported PayPal currency: https://developer.paypal.com/api/rest/reference/currency-codes/
The integration currently expects a valid currency to be configured and only displays a more obvious error for certain currencies.

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly is you need more assistance with the setup. Thanks!

**Comment by OxorOnceAgain** [comment]
Thank you! This did it. :)
