### ISSUE TITLE
reCaptcha for WooCommerce support (1138)

### ISSUE THREAD

**Issue by mynumberis2000** [woocommerce/woocommerce-paypal-payments#1093]
Am using reCaptcha for WooCommerce (2.38), and tried switching from PayPal Checkout Gateway (2.1.3) to PayPal Payments (2.0.1). Payments does not require the completion of the Captcha field, while Checkout Gateway does (preferred).

I don't know if this is an issue with reCaptcha instead, but posting here first.

WooCommerce version 7.1.1, WordPress 6.1.1

Thanks!
Eric

**Comment by InpsydeNiklas** [comment]
Currently, the reCaptcha plugin is not supported for the "early wc validation".
But the team is looking into whether it would be possible to add compatibility.
