### ISSUE TITLE
your photo upload

### ISSUE THREAD

**Issue by matrimonygreat** [woocommerce/woocommerce-paypal-payments#1094]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @matrimonygreat,
I'm not sure this is the right place for your request. PayPal Payments doesn't interact with photo uploads in any case.
If you have any questions regarding PayPal Payments, I suggest [getting in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) to receive further guidance. Thanks!
