### ISSUE TITLE
Dont Connect with Paypal

### ISSUE THREAD

**Issue by gaitanayantal** [woocommerce/woocommerce-paypal-payments#1099]
1 - Plugin installed!
2 - Activated 
3 - Connect with Paypal ( in the setup welcome page of the pluguin)
4 - Login to PayPal Account
3 -  Accepted connection with plugin
4 - OK Connection
5 - Return to woocommerce
6- The page appear and blink .....
Returm tu point 3.....

Https://www.gaitanayantal.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-connection&ppcp-onboarding-error=1)

**Comment by gaitanayantal** [comment]
<img width="1440" alt="Screenshot 2022-12-23 at 14 40 17" src="https://user-images.githubusercontent.com/121313482/209393161-8992d9f4-ca08-4b5e-ad36-946fab1b383c.png">

Return URL:[ ](ttps://www.gaitanayantal.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-connection&ppcp-onboarding-error=1)

**Comment by InpsydeNiklas** [comment]
If the automatic connection process fails for some reason, you could still connect manually [as described here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input). But the [onboarding wizard](https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account) is the recommended approach, so please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you still need assistance with the setup. Thanks!
