### ISSUE TITLE
only paypal and credit card at checkout

### ISSUE THREAD

**Issue by flinke-flasche** [woocommerce/woocommerce-paypal-payments#1100]
from one second to the next most of the paying options at my checkout disappeared.
i only see paypal and credit card.
I this a paypal problem?
i didn’t change something.

**Comment by InpsydeNiklas** [comment]
I assume this relates to [this request](https://wordpress.org/support/topic/only-paypal-and-credit-card-at-checkout/). 
We try to maintain GitHub for development and bug reports only and no support, I'll close this issue.
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you have any further questions. Thanks!
