### ISSUE TITLE
Problema con pay later messaging

### ISSUE THREAD

**Issue by MarcoGallo755** [woocommerce/woocommerce-paypal-payments#1103]
[PayPal Pay Later messaging](https://woocommerce.com/document/woocommerce-paypal-payments/#pay-later-messaging) non funziona, nonostante sia abilitato non viene mostrato il messaggio sulla pagina prodotto

**Comment by Sirvijver** [comment]
Hello @MarcoGallo755 

when the PayPal account was used with a "website payment standard" integration in the last **10 days** (some form of legacy PayPal integration), then the Pay Later messaging is not displayed.

It could take some time before it starts showing again. If not, you could reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review your account for this matter.

We only use GitHub for development activities, so if you require additional support, I advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Closing this thread now.
Kind regards, 
Joost
