### ISSUE TITLE
Woocommerce Paypal Payments

### ISSUE THREAD

**Issue by YannB54** [woocommerce/woocommerce-paypal-payments#1107]
### Describe the Bug

 - WordPress Version 6.1.1
 - WooCommerce 7.2.2
 - Woocommerce Paypal Payments 2.0.1
 - Version Mozilla = 108.0.1 
 - Version Chrome = 105.0.5195.127
 - IOS Apple = 16.3

### Additional Details

<details><summary>System status</summary>

  ```
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @YannB54 

We did not see any problem description in this thread, so we will close. If you have a support request, we would want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We only use GitHub for development activities, so would not provide extensive support via this platform for encountered issues. I will close this thread now.

Kind regards, 
Joost
