### ISSUE TITLE
Paypal token message will not go away 

### ISSUE THREAD

**Issue by congruitymel** [woocommerce/woocommerce-paypal-payments#1110]
Paypal authentication and token message will not go away. Tested PayPal transactions on my website and can place order and receive funds. 

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @congruitymel 

We would like to see what you are seeing, and would like to ask you to send some screenshots on this matter (+system report). However, we do not provide plugin support via GitHub and I would need to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) and open a ticket with them.

Kind regards, 
Joost
