### ISSUE TITLE
unable to process paypal payments

### ISSUE THREAD

**Issue by sylviahubbard1** [woocommerce/woocommerce-paypal-payments#1111]
### Describe the Bug

going through the paypal payments on my site sylviahubbard.com and cannot process paypal or venmo payments. keep getting error of something went wrong please choose another payment source. I'm able to process google payments though so the button is set up as right as possible
### To Reproduce

1. Go to '[…](https://sylviahubbard.com/product/sweetjustice/)' 
2. Click on 'paypal or veno'

### Screenshots
https://sylviahubbard.com/wp-content/uploads/2023/01/319758005_539176084927123_8943666819022581677_n.png

### Expected Behavior

when they click on paypal or venmo i expect them to go sign into their account and process the transaction 
### Actual Behavior
it gives them an error on the page as noted above 

### Environment

 - WordPress Version WordPress 6.1.1 running [Karuna](https://sylviahubbard.com/wp-admin/themes.php) theme.
 - WooCommerce Version Version 7.2.2 
 - Plugin Version Version 2.0.1 
 - Browser Chrome, Version 108.0.5359.125 (Official Build) (64-bit)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @sylviahubbard1 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered occurs sometimes when the PayPal has been limited and under review by PayPal. You might be able to get this resolved by contacting [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and asking them to review the account for this issue.

If this does not resolve the issue, please contact our support team as mentioned above.

Kind regards, 
Joost
