### ISSUE TITLE
Error de conexión

### ISSUE THREAD

**Issue by salamacasta** [woocommerce/woocommerce-paypal-payments#1112]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @salamacasta 

Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you require our support. You have not provided any details of the issue you are facing, and we try to avoid providing support via GitHub. I will mark this thread as resolved.

Kind regards, 
Joost
