### ISSUE TITLE
PayPal and Payment Buttons Missing on Checkout!

### ISSUE THREAD

**Issue by lightofminewebdesign** [woocommerce/woocommerce-paypal-payments#1113]
Hello, I am having an issue I've read a lot about. I am using the WooCommerce PayPal Payments plugin and the payment buttons are missing from the checkout page and if people select the place order button, they get the "Could not retrieve order." error, because the button is not replaced by the payment buttons. I am using the WordPress Version 6.1.1, Astra Theme Version 3.9.4, the WooCommerce Version 7.2.2, Elementor Pro Version 3.9.2, and the checkout page is created using ShopLentor Version 2.5.3. 

The page I am having issues with is https://thebodyshackmakesscents.com/checkout/

I have tried switching to the Storefront theme which did nothing. I tried disabling all plugins except for WooCommerce and the PayPal Payments plugins, and it did nothing. I have tried adding the following shortcodes:

First I tried:
<?php

add_filter('woocommerce_paypal_payments_single_product_renderer_hook', function() {
    return 'woocommerce_after_add_to_cart_form';
});

add_filter('woocommerce_paypal_payments_checkout_button_renderer_hook', function() {
    return 'woocommerce_review_order_after_submit';
});

then I tried:

add_filter('woocommerce_paypal_payments_checkout_button_renderer_hook', function() {
    return 'woocommerce_review_order_after_submit';
});

then I tried:

add_shortcode( 'do_hook', function( $atts = array(), $content = null, $tag = ''){
 if ( isset( $atts['hook'] ) ) {
  do_action( $hook );
 }
 return;
});

finally I tried:

[do_hook hook="woocommerce_before_main_content"]

and none of these worked... I added the shortcodes using the Elementor widget on the checkout page.

None of these steps fixed the issue. **I did notice that the buttons appear on mobile devices, but not on a laptop and I don't have a tablet to check with.**

Please help me!!!!! My client is launching their website Saturday night.

**Comment by Sirvijver** [comment]
Hello @lightofminewebdesign 

I see that the place order button is not getting replaced by our plugin. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We do actually not provide support via our GitHub page and only use it for development activities. For this reason, I will close this thread and ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you require more guidance.

Kind regards, 
Joost
