### ISSUE TITLE
Car Processing is not working on instant checkout

### ISSUE THREAD

**Issue by kundanver** [woocommerce/woocommerce-paypal-payments#1114]
Hello

I am using "Instantio Pro" plugin and card processing was showing on the SIDE CART.
But suddenly what happened it is not showing on the SIDE CARD. yes but it is showing on the checkout page.

SITE URL
https://myhypereffects.com/iamthematrix/

**Comment by Sirvijver** [comment]
Hello @kundanver 

The advanced card processing payment method should only be visible in the checkout page, so this seems to be working correctly. I am not sure what you mean by the "side cart", but the product page and cart page should only show the PayPal and Pay Later payment option (if selected to do so).
We do not support Instantio Pro, so if you have encountered a conflict with our and this plugin, please open a support request to have this further investigate. We use GitHub only for development activities, so if additional support is needed, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. This thread will be closed now.

Kind regards, 
Joost

**Comment by kundanver** [comment]
Okay, Thank you for your reply
