### ISSUE TITLE
Paypal popup close instantly when click

### ISSUE THREAD

**Issue by Nikonco** [woocommerce/woocommerce-paypal-payments#1115]
### Describe the Bug

When I click on the checkout button, the pop up close instantly.

### To Reproduce

Add product to basket : https://utopia56.org/adhesion/
On checkout page, click on PayPal.

(works well on our staging environment, but really don't understand why as it suppose to be an exact copy).

### Screenshots
<img width="1157" alt="Capture d’écran 2023-01-09 à 18 48 50" src="https://user-images.githubusercontent.com/3864199/211375145-f6742ec8-041c-4aea-8ced-790adc05e6ff.png">

**Comment by Sirvijver** [comment]
Hello @Nikonco 

We do no use GitHub for support activities, so if you need additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error I saw on your site was "Something went wrong. Please try again or choose another payment source.". This can occur when your PayPal account is limited and under review. During this time, the account can't be used, and that message will show up. Please get in touch with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to get this sorted.

If they can find any problem; You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

This thread will be closed now.
Kind regards, 
Joost
