### ISSUE TITLE
unable to add paypal automatically

### ISSUE THREAD

**Issue by razr1911** [woocommerce/woocommerce-paypal-payments#1116]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @razr1911 

There is not enough information here to help you. We use GitHub only for development activities, so if you require our support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

I will close this thread.
Kind regards, 
Joost
