### ISSUE TITLE
Paypal "Pay in 4" tagline amount is not updated on cart page if items are added or removed from cart or postage options are changed.

### ISSUE THREAD

**Issue by lordmuz** [woocommerce/woocommerce-paypal-payments#1117]
### Describe the Bug

When viewing the Woocommerce cart page, if a quantity is changed, or an item is removed, OR if a postage option is changed (ie from regular post to express post), the originally calculated "pay in 4" text remains, and does not change, even though the total amount payable has changed.

### To Reproduce

1. Add two items from a woocommerce shop to the cart.
2. Click on "cart" to view the cart.
3. Note the text displayed on the tag line "Pay in 4 interest-free payments of $x.xx Learn more"
4. Change a cart item quantity, or delete a cart item, and then press "Update Cart" to get a new total.
5. Note that the tag line "Pay in 4 interest-free payments of $x.xx Learn more" does not change to reflect the new amount.

### Screenshots

![image](https://user-images.githubusercontent.com/122365885/211550382-fc4345e0-aaae-4717-a0fb-aefc2acde0be.png)

Delete item "PinkFresh Studio Hot Foil Plates Nested Rectangles" from cart

![image](https://user-images.githubusercontent.com/122365885/211550722-ace7974f-682b-4c66-bcac-4a381aab4edf.png)

The "paypal pay in 4 tagline" remains the same - 18.72 is not one quarter of 34.90.  The tagline should be updated to $8.73

![image](https://user-images.githubusercontent.com/122365885/211551043-cc3cf603-3bc4-4efe-9c24-ec8dd3b405bf.png)

### Expected Behavior

The paypal amount for "pay in 4" should be updated when the total cart amount changes.  Whether that is via an AJAX call or otherwise.  The "pay in 4" amount does not change, and remains the same.

If you press F5 or REFRESH the cart page, only then will the pay in 4 amount change to the correct value.

### Actual Behavior

If the cart is modified, or a different postage selection is made, the "Pay in 4" amount remains the same.  This is not correct behavior.

### Environment

 - WordPress Version:  6.1.1
 - WooCommerce Version:  7.2.2
 - Plugin Version:    2.0.1
 - Browser [e.g. Chrome, Safari] and Version:  Chrome 108.0.5359.125 (Official Build) (64-bit)

**Comment by Sirvijver** [comment]
Hello @lordmuz 

The issue you reported is known to us and was already reported some time ago [here](https://github.com/woocommerce/woocommerce-paypal-payments/issues/803). I think it's best you track that thread, and we close this one, so we don't have any duplicate items on GitHub.

Kind regards, 
Joost
