### ISSUE TITLE
Unable to create order, issue NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE

### ISSUE THREAD

**Issue by giselew** [woocommerce/woocommerce-paypal-payments#1120]
### Describe the Bug

Î'm selling subscriptions for webhosting plans on my site. On Woo-checkout page, after clicking PROCEED TO PAYPAY I receive an error message
It's:
Unable to create order{"name":"UNPROCESSABLE_ENTITY","details":[{"issue":"NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE","description":"The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source."}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"cfda7919a155","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE","rel":"information_link","method":"GET"}]}

### To Reproduce

1. First make a user on https://w23.toctoc.ch/shop/register/. Login and go to https://w23.toctoc.ch/product/website-standard/
2. Add a desired domainname and click add to card, then proceed to check out
3. Fill in form fields, when complete at the bottom click on PROCEED TO PAYPAL

### Expected Behavior

Paypal login shoud come

### Actual Behavior

the error message arrives

### Environment

All versions are up to date

### Additional Details

Paypal account looks ok, it's a business account active since longtime
Now my products are subscriptions ... To me it looks like the plugin doesn't handle subscription requirements imposed by Paypal

**Comment by Sirvijver** [comment]
Hello @giselew 

you have reached out to oper GitHub forum with a support request. We utilize GitHub mainly for development activities so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have engaged us for, seems to be an issue that is related to your PayPal account and I would advise to get in touch with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) in order to review your account and see if they can correct this issue.

If they cannot help you, please reach out to our support team as advised above.

Kind regards, 
Joost

**Comment by giselew** [comment]
Hello Joost,

 

Many thinks for your reply. I also think I need to check with PayPal Technical Support. I gave a try with totally normal product (no subscriptions) – I receive same error back … well.

 

Have a great week, kind regards

 

Gisèle

 

Von: Joost van de Vijver ***@***.*** 
Gesendet: Montag, 16. Januar 2023 12:54
An: woocommerce/woocommerce-paypal-payments ***@***.***>
Cc: Gisèle Wendl ***@***.***>; Mention ***@***.***>
Betreff: Re: [woocommerce/woocommerce-paypal-payments] Unable to create order, issue NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE (Issue #1120)

 

Hello @giselew <https://github.com/giselew> 

you have reached out to oper GitHub forum with a support request. We utilize GitHub mainly for development activities so I would like to ask you to reach out to the support team <https://woocommerce.com/document/woocommerce-paypal-payments/#get-help>  directly for more guidance.

The issue you have engaged us for, seems to be an issue that is related to your PayPal account and I would advise to get in touch with PayPal Merchant Technical Support <https://www.paypal-techsupport.com/s/contactsupport>  in order to review your account and see if they can correct this issue.

If they cannot help you, please reach out to our support team as advised above.

Kind regards,
Joost
