### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by qbanchin** [woocommerce/woocommerce-paypal-payments#1124]
### Describe the Bug

Payment provider declined the payment, please use a different payment method. OrderEndpoint.php:339 Order status changed from Pending payment to Failed.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.3.0
 - Paypal Payment Plugin Version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @qbanchin 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you reported seems to be a payment decline from PayPal or the involved bank, so there is not much you can do from the Plugin perspective. The plugin only displays the notice that they receive from PayPal/the bank and cannot adjust anything on this.

Kind regards, 
Joost
