### ISSUE TITLE
Cannot deactivate once activated! Help me deactivate from WooCommerce, please!

### ISSUE THREAD

**Issue by CarlosFarnesi** [woocommerce/woocommerce-paypal-payments#1126]
Cannot deactivate once activated! Help me deactivate from WooCommerce, please!

**Comment by Sirvijver** [comment]
Hello @CarlosFarnesi 

This platform is intended mainly for development. If support requests that are opened here, they should be given a hint of what could cause the issue and advised to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You can deactivate our plugin by renaming the plugin folder on your ftp if nothing else works for you.
Please provide more details to your support request if/when you open one.

Kind regards, 
Joost
