### ISSUE TITLE
Activation Problem

### ISSUE THREAD

**Issue by winnersingh** [woocommerce/woocommerce-paypal-payments#1127]
### To Reproduce

1. Go to 'Acivate paypal'
2. Click on 'Enter login detail in the POP box,'
3. Scroll down to …'Pop says paypal activated'
4. See error but when refresh the wocommerce payal section, its still says 'activate paypal'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @winnersingh 

I am not sure what error you are seeing and what the impact is of this issue, so it is hard to give you any advice on this matter. 
You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)


We only perform development activities on GitHub, so I will close this support request. If you require additional support, I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.

Kind regards, 
Joost
