### ISSUE TITLE
When both plugins WooCommerce Paypal Payment and WooCommerce Zahlungen are activated there is an error during checkout

### ISSUE THREAD

**Issue by chrizmc** [woocommerce/woocommerce-paypal-payments#1134]
Hi, I followed your proposal to deactivate all plugins based on my error description here: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1109#issuecomment-1381782528

I found out that there is a conflict between WooCommerce Paypal Payment and WooCommerce Zahlungen. Can you help me?

**Comment by Sirvijver** [comment]
Hello @chrizmc

We do no use GitHub for support activities, so we want to advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you need more guidance.

You can still link the GitHub case there.
Kind regards, 
Joost
