### ISSUE TITLE
Unable to setup paypal with woocommerce

### ISSUE THREAD

**Issue by bantorocom** [woocommerce/woocommerce-paypal-payments#1140]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @bantorocom 

We do not provide plugin support via the GitHub forum, and can only advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
When/if you do, please add the system report and logs (if available) for us to help you out better.

This thread will be closed.

Kind regards, 
Joost
