### ISSUE TITLE
Broken link in home page

### ISSUE THREAD

**Issue by dsgjohnnie** [woocommerce/woocommerce-paypal-payments#1141]
### Describe the Bug

My site scanner has been reporting a broken link for the past several days to the following PayPal URL associated with the Payments Plugin.  The link is on line 3242 of https://www.discountkeystore.com/ and it returns a 400 error.  Screenshot is attached with the error and debug ID.

https://www.paypal.com/sdk/js?client-id=AaDdDrejtoFcnMeZqmrEZ_Nkd1zBsaei62ROKvV0oP4vsICsWkbzoYPWD6jIn_NDw1GW_AdceO9yO5oU&amp;currency=USD&amp;integration-date=2022-04-13&amp;components=buttons,funding-eligibility,messages&amp;vault=false&amp;commit=false&amp;intent=capture&amp;disable-funding=card&amp;enable-funding=venmo,paylater" data-partner-attribution-id="Woo_PPCP" data-uid-auto="uid_trrxeslflrzlugmeykpbbrgqhlcybt"

### To Reproduce

Go to the link above which is in my site code from the plugin

### Screenshots

![Screenshot 2023-01-30 073413](https://user-images.githubusercontent.com/114694374/215481125-64ef501f-109a-473e-85a0-550e0d12ab3a.jpg)
![Screenshot 2023-01-30 073445](https://user-images.githubusercontent.com/114694374/215481151-b001b59e-868b-4029-b511-f92b67819a36.jpg)

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version  7.3.0
 - Plugin Version  2.0.1
 - Browser [e.g. Chrome, Safari] and Version - Observed error via app.powermapper.com and confirmed on Chrome Version 109.0.5414.120 (Official Build) (64-bit)
 - Any other plugins installed
Back In Stock Notifier for WooCommerce \| WooCommerce Waitlist Pro | Version 3.2 by codewoogeek \| Auto-updates enabled
Bing Webmaster Url Submission | Version 1.0.13 by Bing Webmaster \| Auto-updates enabled
Duplicate Page | Version 4.5 by mndpsingh287 \| Auto-updates enabled
Elementor | Version 3.10.1 by Elementor.com (Latest version: 3.10.2) \| Auto-updates disabled
Email Verification for WooCommerce | Version 2.5.0 by WPFactory \| Auto-updates enabled
Envato Market | Version 2.0.8 by Envato \| Auto-updates enabled
Integration for WooCommerce and QuickBooks Pro | Version 1.2.3 by CRM Perks \| Auto-updates enabled
Jetpack | Version 11.7.1 by Automattic \| Auto-updates enabled
MailerLite - Signup forms (official) | Version 1.6.1 by MailerLite \| Auto-updates enabled
Payment Plugins for Stripe WooCommerce | Version 3.3.36 by Payment Plugins, support@paymentplugins.com \| Auto-updates disabled
Product Feed PRO for WooCommerce | Version 12.1.9 by AdTribes.io \| Auto-updates enabled
Profile Builder | Version 3.8.8 by Cozmoslabs \| Auto-updates enabled
Redirection | Version 5.3.9 by John Godley \| Auto-updates enabled
Serial Numbers for WooCommerce | Version 1.4.5 by PluginEver \| Auto-updates enabled
Site Kit by Google | Version 1.92.0 by Google \| Auto-updates enabled
Trustpilot-reviews | Version 2.5.914 by Trustpilot \| Auto-updates enabled
UpdraftPlus - Backup/Restore | Version 1.22.24 by UpdraftPlus.Com, DavidAnderson \| Auto-updates enabled
WooCommerce | Version 7.3.0 by Automattic \| Auto-updates disabled
WooCommerce Amazon Pay | Version 2.4.0 by WooCommerce \| Auto-updates enabled
WooCommerce Cart Abandonment Recovery | Version 1.2.21 by CartFlows Inc \| Auto-updates enabled
WooCommerce Google Analytics Integration | Version 1.5.19 by WooCommerce \| Auto-updates enabled
WooCommerce PayPal Payments | Version 2.0.1 by WooCommerce \| Auto-updates disabled
WooCommerce Serial Numbers Pro | Version 1.1.8 by pluginever \| Auto-updates disabled
WP Cerber Security, Anti-spam & Malware Scan | Version 9.4 by Cerber Tech Inc. \| Auto-updates enabled
WP Crontrol | Version 1.15.1 by John Blackbourn & crontributors \| Auto-updates enabled
WP Mail SMTP Pro | Version 3.7.0 by WPForms \| Auto-updates enabled
WP Rocket | Version 3.12.4 by WP Media \| Auto-updates disabled
WP Rollback | Version 1.7.3 by GiveWP.com \| Auto-updates enabled
WPScan | Version 1.15.6 by WPScan Team \| Auto-updates enabled
WP Sitemap Page | Version 1.9.2 by Tony Archambeau \| Auto-updates enabled
XStore Core | Version 5.0.2 by 8theme \| Auto-updates enabled
Yoast SEO | Version 20.0 by Team Yoast \| Auto-updates enabled

### Additional Details

<details><summary>System status</summary>

  
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @dsgjohnnie, it looks like the URLs you provided have been encoded incorrectly,
The "amp;" parameters in the URL you mentioned are HTML entities for the ampersand symbol ("&"). It seems that the URL may have been encoded improperly at some point, which caused the HTML entities to be included in the URL. 
The URL in the screenshot includes excess space symbols in the URL, which should not be there.
But I'm not sure if this originates in the PayPal Payments plugin itself, as the script appears to be loading correctly on your site.

If this alert is causing any issues on your site, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
