### ISSUE TITLE
PayLater doesn't work

### ISSUE THREAD

**Issue by logogrammagit** [woocommerce/woocommerce-paypal-payments#1148]
### Describe the Bug

Hello,
we have installed your plugin and linked the account but the Paylater does not work. We contacted PayPal support directly who tell us the following: After checking recent transactions on his account, I see that he is processing transactions using the REST API method, but most of the transactions were not recorded on his account. 
I also see that it is triggering the "Get method" call - https://developer.paypal.com/docs/api/orders/v2/#orders_get, but not the payment confirmation call - https://developer.paypal.com/docs/api/orders/v2/#orders_confirm on the payer's side. Once the payer confirms the payment and the transaction is authorized, he can collect the payment by activating - https://developer.paypal.com/docs/api/orders/v2/#orders_capture. Please check its integration and proceed with the integration of the website.

I have attached to the ticket the screenshots with the configuration of your plugin. Can you tell us what the problem is? Waiting for your kind reply, thank you

### To Reproduce

Make a paylater order on https://www.elmaxweb.it

### Screenshots
<img width="558" alt="settings-connection1" src="https://user-images.githubusercontent.com/123968106/215725825-a64991cf-4def-418b-9b25-27dfccb36a17.png">
<img width="685" alt="settings-connection2" src="https://user-images.githubusercontent.com/123968106/215725830-48fb104a-a51c-4b37-9f0a-28dee3d9ff49.png">
<img width="754" alt="settings-standard1" src="https://user-images.githubusercontent.com/123968106/215725831-0c94a6ac-b6c3-4472-8993-03472c81c139.png">
<img width="1168" alt="settings-standard2" src="https://user-images.githubusercontent.com/123968106/215725834-8d1dad66-8a5d-4d64-a644-f3d2fc6039ff.png">
<img width="713" alt="settings-paylater1" src="https://user-images.githubusercontent.com/123968106/215725839-7fc4eaaf-1093-4aff-b455-3c54120a5195.png">

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.1.0
 - Plugin Version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version Chrome 109.0.5414.120
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @logogrammagit 

Sorry for the long delay in this response. We do actually not provide plugin support via GitHub and don't put priority on the response to these threads. I will ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

It does sound there might be an issue with the payment handling, but it could be that this is caused on the PayPal server when it is not able to vault the payment method. We will need to see the order notes of example situations, and it would also be good to get the logs that are related to this matter. For now, I will close this thread and wait for you to open a support thread with our team.

Kind regards, 
Joost
