### ISSUE TITLE
WooCommerce PayPal Payments (versie 2.0.2) critical error

### ISSUE THREAD

**Issue by JeanPaulos** [woocommerce/woocommerce-paypal-payments#1152]
Foutdetails
===========
Een fout van het type E_ERROR werd veroorzaakt op regelnummer 103 van het bestand /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/extensions.php. Foutmelding: Uncaught Error: Failed opening required '/home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/connection-tab-settings.php' (include_path='.:/usr/local/php80/pear') in /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/extensions.php:103
Stack trace:
#0 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule->WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#1 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(144): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#2 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(74): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeExtension(Object(Closure), Array)
#3 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(293): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#4 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#5 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#6 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#7 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get('wcgateway.setti...')
#8 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}()
#9 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator(Object(Closure))
#10 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(62): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached('wcgateway.setti...', Object(Closure))
#11 /home/customer/www/bedrukt.nl/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php(405): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('wcgateway.setti...')
#12 /home/customer/www/bedrukt.nl/public_html/wp-includes/class-wp-hook.php(308): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}('

**Comment by InpsydeNiklas** [comment]
Hi @JeanPaulos 
Errors like this usually occur if something went wrong during the update, like some files potentially not being updated. I suggest downloading the latest version again [from here ](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.0.2/woocommerce-paypal-payments.zip) and then installing it manually from your WordPress admin or via FTP. If any problem persist, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
