### ISSUE TITLE
Learnpress Fallo

### ISSUE THREAD

**Issue by agusgonzalezs** [woocommerce/woocommerce-paypal-payments#1158]
La última actualización produce un fallo con el plugin de Learnpress, en especifico un error critico de wordpress.

**Comment by Sirvijver** [comment]
Hello @agusgonzalezs 

thank you for reaching out to us. We would like to take a look into this issue, but we need you to provide more details about the error, logs and would also want to review your system report. We only use GitHub for development activities, so would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly to open a support request and provide these additional details for us to take a look at.

I will close this thread.

Kind regards, 
Joost
