### ISSUE TITLE
Paypal Payments Activate Link

### ISSUE THREAD

**Issue by SpencerMichelsCom** [woocommerce/woocommerce-paypal-payments#1164]
The link when activating paypal account no longer goes to the bizsignup/ partner Url, instead goes to paypal homepage

1. Go to 'Woocommerce Payment Settings '
2. Click on 'Payments'
3. Scroll down to 'Paypal'
4. Click 'Finish Setup'
5. Check both boxes
6. Select 'Standard Card Processing'
7. Scroll to buttons
8. Click 'Activate Paypal'
9. Issue occurs on pop-up.

Link should direct to Page with accepting partnership with Paypal, then business sign-in.

Link instead just redirects to Paypal homepage.

 - WordPress Version 
 - WooCommerce Version 7.1.0
 - WooCommerce PayPal Payments Version 2.0.2
 - Chrome Version 108.0.5359.124

Link was going to proper URL this morning, but servers had an outage, once back online the URL was broken

**Comment by Sirvijver** [comment]
Hello @SpencerMichelsCom 

I just tested this situation and in my testing environment, the situation is still as normal: it links to the business sign-in popup:
![image](https://user-images.githubusercontent.com/78153894/217240419-11b6f474-95af-4fa3-aed1-be24d7b16c32.png)

Please try to see if any aspect of your site is affecting this redirection. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
. 
We do not provide plugin support via GitHub (only development activities are done her), so I will close this thread and ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
