### ISSUE TITLE
Order payement status

### ISSUE THREAD

**Issue by CPPRESSE** [woocommerce/woocommerce-paypal-payments#1171]
### Describe the Bug

All Paypal order stay in "pending paiement", even on paypal it say "finnished"

even there is no problem on log file

Even the webhook working normaly

### Expected Behavior

update order status after payement finnished

### Actual Behavior

No update of oder status

### Environment

 - WordPress Version : 6.1.1
 - WooCommerce Version : 7.3.0
 - Plugin Version : 2.0.2

### Additional Details

2023-01-17T17:51:00+00:00 DEBUG POST https://api.paypal.com/v1/notifications/verify-webhook-signature
Request Body: {"transmission_id":"606d77f0-968f-11ed-a7af-915d6ac354aa","transmission_time":"2023-01-17T17:50:06Z","cert_url":"https:\/\/api.paypal.com\/v1\/notifications\/certs\/CERT-360caa42-fca2a594-38317689","auth_algo":"SHA256withRSA","transmission_sig":"jTBS12b9oPj7Lm5D+hPcr4+OTGGMK4zGK+iFs2qKXM\/mvrulg4wyYUxtHb0a4lsIgu8qRcTTVXBU28+o35ifGPLnvrhH1QybGz+uZBKfDLWdeAXMhMuQeDscLXrQV8MkKD9ulkm\/s3GO86aQ9+jaO6XkPqIjoergvPpJYJog4H\/I2h5MV7Y1JbWnVK18Cz+wgA8BuFyyQ4PFeMRY\/MwiSEvE3XlWZEvYWzcarf62cs+LLiYjO9pfQS\/\/MGkKIDn2dI6Ubv5X51+YzX4+rHAWzGSlYg0D0mdjTvKJGDj++4+AurA4YLxMtgmIm5vN8Dmqo2f+xKWVUCa\/tzUtpwp9ZA==","webhook_id":"5MF86992KA3684330","webhook_event":{"id":"WH-3F478161D14326433-36X661342G189033J","event_version":"1.0","create_time":"2023-01-17T17:50:00.687Z","resource_type":"capture","resource_version":"2.0","event_type":"PAYMENT.CAPTURE.COMPLETED","summary":"Payment completed for EUR 34.5 EUR","resource":{"id":"8NM57039UW353373C","amount":{"currency_code":"EUR","value":"34.50"},"final_capture":true,"seller_protection":{"status":"ELIGIBLE","dispute_categories":["ITEM_NOT_RECEIVED","UNAUTHORIZED_TRANSACTION"]},"seller_receivable_breakdown":{"gross_amount":{"currency_code":"EUR","value":"34.50"},"paypal_fee":{"currency_code":"EUR","value":"1.35"},"net_amount":{"currency_code":"EUR","value":"33.15"}},"invoice_id":"SB-58280","custom_id":"58280","status":"COMPLETED","supplementary_data":{"related_ids":{"order_id":"1XA69379JL6166436"}},"create_time":"2023-01-17T17:49:37Z","update_time":"2023-01-17T17:49:37Z","links":[{"href":"https:\/\/api.paypal.com\/v2\/payments\/captures\/8NM57039UW353373C","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v2\/payments\/captures\/8NM57039UW353373C\/refund","rel":"refund","method":"POST"},{"href":"https:\/\/api.paypal.com\/v2\/checkout\/orders\/1XA69379JL6166436","rel":"up","method":"GET"}]},"links":[{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-3F478161D14326433-36X661342G189033J","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-3F478161D14326433-36X661342G189033J\/resend","rel":"resend","method":"POST"}]}}
Response Debug ID: ee90ffd631a16
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-01-17T17:51:00+00:00 INFO Webhook has been handled by PAYMENT.CAPTURE.COMPLETED
2023-01-17T17:51:00+00:00 DEBUG POST https://api.paypal.com/v1/notifications/verify-webhook-signature
Request Body: {"transmission_id":"606d77f0-968f-11ed-a7af-915d6ac354aa","transmission_time":"2023-01-17T17:50:06Z","cert_url":"https:\/\/api.paypal.com\/v1\/notifications\/certs\/CERT-360caa42-fca2a594-38317689","auth_algo":"SHA256withRSA","transmission_sig":"jTBS12b9oPj7Lm5D+hPcr4+OTGGMK4zGK+iFs2qKXM\/mvrulg4wyYUxtHb0a4lsIgu8qRcTTVXBU28+o35ifGPLnvrhH1QybGz+uZBKfDLWdeAXMhMuQeDscLXrQV8MkKD9ulkm\/s3GO86aQ9+jaO6XkPqIjoergvPpJYJog4H\/I2h5MV7Y1JbWnVK18Cz+wgA8BuFyyQ4PFeMRY\/MwiSEvE3XlWZEvYWzcarf62cs+LLiYjO9pfQS\/\/MGkKIDn2dI6Ubv5X51+YzX4+rHAWzGSlYg0D0mdjTvKJGDj++4+AurA4YLxMtgmIm5vN8Dmqo2f+xKWVUCa\/tzUtpwp9ZA==","webhook_id":"5MF86992KA3684330","webhook_event":{"id":"WH-3F478161D14326433-36X661342G189033J","event_version":"1.0","create_time":"2023-01-17T17:50:00.687Z","resource_type":"capture","resource_version":"2.0","event_type":"PAYMENT.CAPTURE.COMPLETED","summary":"Payment completed for EUR 34.5 EUR","resource":{"id":"8NM57039UW353373C","amount":{"currency_code":"EUR","value":"34.50"},"final_capture":true,"seller_protection":{"status":"ELIGIBLE","dispute_categories":["ITEM_NOT_RECEIVED","UNAUTHORIZED_TRANSACTION"]},"seller_receivable_breakdown":{"gross_amount":{"currency_code":"EUR","value":"34.50"},"paypal_fee":{"currency_code":"EUR","value":"1.35"},"net_amount":{"currency_code":"EUR","value":"33.15"}},"invoice_id":"SB-58280","custom_id":"58280","status":"COMPLETED","supplementary_data":{"related_ids":{"order_id":"1XA69379JL6166436"}},"create_time":"2023-01-17T17:49:37Z","update_time":"2023-01-17T17:49:37Z","links":[{"href":"https:\/\/api.paypal.com\/v2\/payments\/captures\/8NM57039UW353373C","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v2\/payments\/captures\/8NM57039UW353373C\/refund","rel":"refund","method":"POST"},{"href":"https:\/\/api.paypal.com\/v2\/checkout\/orders\/1XA69379JL6166436","rel":"up","method":"GET"}]},"links":[{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-3F478161D14326433-36X661342G189033J","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-3F478161D14326433-36X661342G189033J\/resend","rel":"resend","method":"POST"}]}}
Response Debug ID: 5e4217d422f60
Response: Array
(
    [code] => 200
    [message] => OK
)
<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @CPPRESSE 
The webhooks could be [resubscribed from the connections tab](https://woocommerce.com/document/woocommerce-paypal-payments/#webhook-status). If you still encounter webhook-related problems after resubscribing, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
