### ISSUE TITLE
Woocomerce Product pictures  and SALE sign overlay website footer

### ISSUE THREAD

**Issue by chekorbla** [woocommerce/woocommerce-paypal-payments#1173]
Issue: 

When product image and product gallery images are uploaded, the product image overlay website footer when scrolling (When product gallery images are removed) the product image does not overlay footer.

Similar, when a SALE price is entered, the SALE badge on the product overlay website footer when scrolling 

Same for the QUICK VIEW display ----overlay footer when scrolling

Footer is fixed to the bottom of the website using the following CSS (Using OceanWP theme:

 .site-footer{
     position:fixed;
     bottom:0px;
     left:0px;
     right:0px;
     width:100%;
    }

Any advice how to resolve this issues? See pictures attached. Thank you.
![Images layover footer](https://user-images.githubusercontent.com/103399770/217668968-375e5cba-2cab-429f-a0c1-5f0f7427ef31.jpg)
![Overlay footer](https://user-images.githubusercontent.com/103399770/217668976-6080ac7d-7233-4ef3-b2ac-4ac179abfeeb.jpg)
![Overlay](https://user-images.githubusercontent.com/103399770/217668980-36f7084e-c8bb-4120-93ba-3ec4f30de6bf.jpg)
![Image overlay](https://user-images.githubusercontent.com/103399770/217669886-ee70e535-ea76-40af-94f4-5d58846a202c.jpg)

**Comment by InpsydeNiklas** [comment]
Hi @chekorbla, I understand you are encountering a problem, and it appears to be related to your theme and not to PayPal Payments. To resolve this issue, I recommend reaching out to the developer of your theme for assistance. Or if you think there is a relation to PayPal Payments, then please consider [reaching out to the plugin support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
