### ISSUE TITLE
Smart Button of WooCommerce PayPal Payments hidden on Desktop

### ISSUE THREAD

**Issue by meto20** [woocommerce/woocommerce-paypal-payments#1174]
After installing and connect this plugin with PP, I've noticed that the smart buttons appears only in cart page and checkout page. It doesn't appear on the product page or mini cart page. 

Kindly help to solve this issue.

**Comment by InpsydeNiklas** [comment]
Hi @meto20, this could potentially happen with certain page builders. But please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance. Thanks!
