### ISSUE TITLE
PayPal large button on product is appearing in a section over the actual product, see screenshot here: https://prnt.sc/vGZOH8vKwmVI

### ISSUE THREAD

**Issue by RetroWill** [woocommerce/woocommerce-paypal-payments#1176]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by RetroWill** [comment]
Using Divi theme builder.

**Comment by InpsydeNiklas** [comment]
Hi @RetroWill, This filter must be added to your themes `functions.php` file and should fix the button placement for Divi Theme Builder product pages: 
```php
add_filter('woocommerce_paypal_payments_single_product_renderer_hook', function() {
    return 'woocommerce_after_add_to_cart_form';
});
```
If any questions remain, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly to receive more guidance. Thanks!

**Comment by RetroWill** [comment]
Sorts the button appearing over the product area in the builder but it appears now for a split second in the correct place and then vanishes.
