### ISSUE TITLE
Can't login in the pay pal account

### ISSUE THREAD

**Issue by Thesuitss** [woocommerce/woocommerce-paypal-payments#1178]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Thesuitss 

When the onboarding wizard fails for some reason, you could also [manually connect your API credentials](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input). But if you need assistance with the plugin setup, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), so the team can provide more guidance. Thanks!

Kind regards,
Niklas
