### ISSUE TITLE
paypal connection issue keeps saying "sorry nonce did not verify" after clicking on yellow paypal button 

### ISSUE THREAD

**Issue by xmod5184** [woocommerce/woocommerce-paypal-payments#1181]
![image](https://user-images.githubusercontent.com/125149941/218273473-84772c0c-6509-4ae5-8987-92bb1dd34e35.png)

**Comment by InpsydeNiklas** [comment]
Hi @xmod5184,

This error does not look like it's coming from PayPal Payments.
Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your system report, so the team can look into this further with you. Thanks!

Kind regards,
Niklas
