### ISSUE TITLE
get_cart was called incorrectly. Get cart should not be called before the wp_loaded action due to Paypal plugin

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#1183]
### On Stripe account webhook logs when the webhook call 500 (Internal Server Error) is generated, this error is due to the WooCommerce PayPal Payments plugin, we have checked with a deactivated plugin then the Stripe webhook warning has been removed.

get_cart was called incorrectly. Get cart should not be called before the wp_loaded action. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule->WooCommerce\PayPalCommerce\WcGateway\{closure}, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory, WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule->WooCommerce\PayPalCommerce\WcGateway\{closure}, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get, WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory, WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}, WC_Payment_Gateways->get_available_payment_gateways, WC_Gateway_COD->is_available, apply_filters('woocommerce_cart_needs_shipping'), WP_Hook->apply_filters, override_cart_needs_shipping, WC_Cart->get_cart, wc_doing_it_wrong. This message was added in version 2.3.

**Comment by InpsydeNiklas** [comment]
@kiran-pr This issue has been resolved in this PR: #1172
For any additional questions or guidance, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
