### ISSUE TITLE
waiting for www.paypal.com slow down website

### ISSUE THREAD

**Issue by TedRocLA** [woocommerce/woocommerce-paypal-payments#1184]
. When I load the page, it takes a long time to fully load, and I can see that the browser says “waiting for paypal.”

According to GTmetrix, this may be the culprit:
https://www.paypal.com/sdk/js?client-id=...&merchant-id=...&intent=capture&locale=en_US&components=buttons,funding-eligibility,messages&commit=false&currency=USD

When I view source, I can see that there are numerous mentions of PayPal there, including a link to a CSS file and some JavaScript.

I don’t need these things on my home page or the blog single post pages, so I’d like to know if there is a way to remove them. I only want the payment-related CSS and JS to be showing up on the shop-related pages.

**Comment by InpsydeNiklas** [comment]
Hi @TedRocLA 
If you don't want the PayPal scripts to be loaded on your home page, I suggest disabling the Mini Cart button: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-scripts-on-every-page
For any questions regarding the plugin setup, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly to receive more guidance. Thanks!

Kind regards,
Niklas

**Comment by TedRocLA** [comment]
Hi Niklas,

thank you, that seems to work

 

regards from Ted

LivingApartment

M 04 25251304

W  <http://www.livingapartment.com.au/> www.LivingApartment.com
