### ISSUE TITLE
Issue with editing WooCommerce subscriptions that use PayPal as payment method

### ISSUE THREAD

**Issue by kmaric69** [woocommerce/woocommerce-paypal-payments#1194]
### Describe the Bug

I got a question regarding the WooCommerce Subscriptions plugin and WooCommerce PayPal Payments plugin.

I noticed when I have the PayPal Sandbox activated that you have a bunch of features enabled like manually editing the subscription, editing the date, and applying coupons (which makes sense in sandbox mode).

But when you disable sandbox mode, you lose a lot of these features.

**My question is:** Is it possible to enable these features also in production mode (let’s call it like this - sandbox deactivated) and if yes is this something that needs to be set up on the PayPal business account or somewhere else?

The reason I need this is that I’m building a refer a friend system that would automatically apply coupons to new subscribers, but our subscription model is based on a free trial period.

Which means that once the user subscribers he starts his free trial and becomes and active subscriber and the coupon should be applied after he is already subscribed (coupon will take effect on his automatic renewal after the trial ends). But the WooCommerce PayPal Payments plugin is blocking this option to apply a coupon.

### To Reproduce

1. Install and activate WooCommerce Subscriptions and WooCommerce PayPal Payments plugin.
2. Setup WooCommerce PayPal Payments and enable Vaulting
3. Setup WooCommerce Subscriptions plugin (create a subscription-based product and add a free trial option)
4. Make a test purchase using PayPal in sandbox mode and try to edit the subscription (apply coupon or change the date for the subscription)
5. Make a test purchase with PayPal sandbox mode disabled and try to edit the subscription (apply coupon or change the date for the subscription)

### Screenshots
Sandbox activated - Feature list
<img width="163" alt="Screenshot 2023-02-13 at 12 49 10" src="https://user-images.githubusercontent.com/11028407/219091961-66d59d22-4824-4ff1-bf90-8009d2bc5ff8.png">
Sandbox deactivated - Feature list
<img width="174" alt="Screenshot 2023-02-13 at 12 49 45" src="https://user-images.githubusercontent.com/11028407/219091969-8ed252aa-9949-4b48-94ea-dfb4011540d2.png">
Sandbox activated - Able to edit subscription
<img width="1014" alt="Screenshot 2023-02-13 at 12 50 06" src="https://user-images.githubusercontent.com/11028407/219091973-0bb6ca8d-9f4f-4d5f-8d79-68146256c81d.png">
Sandbox deactivated - Unable to edit subscription
<img width="1011" alt="Screenshot 2023-02-13 at 12 52 49" src="https://user-images.githubusercontent.com/11028407/219091980-a29397c3-3310-436a-9e95-9f6310c020e4.png">

### Expected Behavior
You should be able to update the subscription with sandbox mode disabled (apply coupons or change date for the subscription).

### Actual Behavior
You are not able to apply coupons to existing subscriptions that used PayPal as payment method.

### Environment

- WordPress Version 6.1.1
- WooCommerce Version 7.3.0
- WooCommerce PayPal Payments Version 2.0.2
- WooCommerce Subscriptions 4.6.0

**Comment by Sirvijver** [comment]
Hello @kmaric69 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing does indeed seem to be account related, so I would advise reaching out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) first and ask them to check your account related to these shortcomings in live mode.

If that does not work, please reach out to our support team via the provided link. We will mark this thread as closed.

Kind regards, 
Joost
