### ISSUE TITLE
After Update 2.0.2 - Pay upon Invoice not working

### ISSUE THREAD

**Issue by TimoNuesslein** [woocommerce/woocommerce-paypal-payments#1202]
After the update to 2.0.2 the purchase on account does not work anymore. 

Status: 422
Issue: DEVICE_DATA_NOT_AVAILABLE
Description: The requested action could not be performed, semantically incorrect, or failed business validation.

DEVICE_DATA_NOT_AVAILABLE Device Data is not available for processing this order. The PayPal-Client-Metadata-Id header value sent during `Create Order` api call is either missing or incorrect or there was an error in collecting required data. Please verify if appropriate value for PayPal-Client-Metadata-Id header is being sent during ‘Create Order’ api call. Please note this error only applies to payment_source.pay_upon_invoice at the moment.

**Comment by Sirvijver** [comment]
Hello @TimoNuesslein

the team has addressed this in issue https://github.com/woocommerce/woocommerce-paypal-payments/pull/1177.
You can try out a test version with this change from [this download link](https://drive.google.com/uc?export=download&id=1VjO-dYb2t6pcWdNF0dnb0pKlJEwLBPBE).

We appreciate your feedback on how this version works for you.

Kind regards, 
Joost

**Comment by InpsydeNiklas** [comment]
This issue was resolved in the last update [2.0.3.](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.3)

> Fix - DEVICE_DATA_NOT_AVAILABLE error message when FraudNet is enabled https://github.com/woocommerce/woocommerce-paypal-payments/pull/1177

If any issues remain, please [contact the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
