### ISSUE TITLE
Conflict between PayPal Payments 2.0.2 and Invoice Payment Option 1.0.4

### ISSUE THREAD

**Issue by lynnjat7** [woocommerce/woocommerce-paypal-payments#1208]
### Describe the Bug

It's not clear where this issue lies, so I'm raising it here as a PayPal Payments problem for tracking purposes, but will also highlight this issue to the developers of Invoice Payment Option (Addify).

The issue is that with the latest version of both plugins installed:
--> PayPal Payments 2.0.2
--> Invoice Payment Option 1.0.4

... access to the Product Data area on a product, to edit any details about a product, is blocked.

What you will see is that the data area just shows a spinner, and never fully loads the Product editor, so the product cannot be edited.

This was originally reported by a customer as hanging on variable products, when attempting to access the "Variations" tab.

But on my test site, I also saw it on Simple products when attempting to access any other tabs, such as Inventory or Shipping.

The problem can be seen both on existing products and when attempting to create a new product.

### To Reproduce

1. Install version 2.0.2 of PayPal Payments and configure and activate as a payment gateway
2. Install version 1.0.4 of Invoice Payment Option and activate
3. Attempt to edit any existing product, and access other tabs in the Product Data area.

### Screenshots

A simple product, hanging:
![VS6tue.png](https://user-images.githubusercontent.com/109691691/220708125-e19171f8-502e-454c-aa4d-7d479fe63388.png)

A variable product, hanging:
![zYBca5.png](https://user-images.githubusercontent.com/109691691/220708460-27a523dc-6f89-475a-9cc4-253cc513fd38.png)

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.4
 - Plugin Version: 2.0.2 of PayPal Payments; 1.0.4 of Invoice Payment Option
 - Browser [e.g. Chrome, Safari] and Version: tested in Chrome
 - Any other plugins installed: customer did a full conflict test to identify this issue; tested on my test site with Storefront, Woo, these two plugins, plus Jetpack, Code Snippets, Square, and Subscriptions.

### Additional Details

Customer ticket: 5982720-zd-woothemes

**Comment by lynnjat7** [comment]
Update: Tested with a downgrade to PayPal Payments 2.0.1 and it resolves this issue, so can be used as a workaround. 

It's definitely something changed in PayPal Payments 2.0.2 that causes the issue, but I think it is likely up to Invoice Payment Option to work around the new version to resolve this conflict.

**Comment by InpsydeNiklas** [comment]
Thanks for bringing this up @lynnjat7. It appears this behavior may be related to #1195 and should be fixed with the next update.
Could you please give it a try with [this version](https://drive.google.com/uc?export=download&id=1-AZQSMQgxE7ZqPuTBVKQO139y3kd8Act)?
Thanks!

**Comment by lynnjat7** [comment]
@InpsydeNiklas It works! Thank you! The customer has downgraded to 2.0.1 and is fine for now - I'll let them know they should be able to upgrade when the next version comes out with confidence.

**Comment by InpsydeNiklas** [comment]
Thanks for the feedback, it is much appreciated.
We just published a new pre-release version for testing with the fix: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.3-rc2
This next update is currently expected to be officially released in the first week of March, but it depends on the testing results.
