### ISSUE TITLE
Hosted Fields Payment is Already In Progress on Invoiced Orders

### ISSUE THREAD

**Issue by Happbee** [woocommerce/woocommerce-paypal-payments#1219]
### Describe the Bug
Invoiced customers are receiving an error and unable to check out. Only applies to orders that are emailed an invoice for an order that was created on the woocommerce platform. Payments are not progressing through the system when using the advanced card processing. 
Does not seem to affect customers that create their own cart and checkout. 

### To Reproduce

Create an invoice using add order in woocommerce. 
Email invoice/details to customer
Customer opens email, uses provided link to cart page
Customers submit payment, are given the processing notice, processing notice goes away, customer believes it did not process, tries to resubmit, gets Hosted Fields Payment is already in progress.
We never receive payment, order does not go through.

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

https://snipboard.io/AjtxTZ.jpg

### Expected Behavior

Customer enters credit card number, card is processed, order is placed

### Actual Behavior

Customer enters card number, progresses, receives error notice

### Environment

 - WordPress Version: WP Version: 6.1.1
 - WooCommerce Version : WC Version: 7.4.0
 - Plugin Version WooCommerce PayPal Payments |   | by WooCommerce – 2.0.2
 - Browser [e.g. Chrome, Safari] and Version Firefox Version 110
 - Any other plugins installed
 - 

All in One SEO |   | by All in One SEO Team – 4.3.1.1
Blocksy Companion |   | by CreativeThemes – 1.8.76
Total Upkeep Premium |   | by BoldGrid – 1.5.9
Total Upkeep |   | by BoldGrid – 1.15.5
BoldGrid Easy SEO |   | by BoldGrid – 1.6.11
BoldGrid Gallery |   | by BoldGrid.com – 1.5.1
BoldGrid Inspirations |   | by BoldGrid – 2.7.4
Bulk Media Register |   | by Katsushi Kawamori – 1.26
Customizer Export/Import |   | by The Beaver Builder Team – 0.9.5
DreamHost Panel Login |   | by DreamHost, danielbachhuber – 1.0.0
Jetpack |   | by Automattic – 11.8.4
Login No Captcha reCAPTCHA (Google) |   | by Robert Peake and Contributors – 1.7.1
Media Cleaner |   | by Jordy Meow – 6.5.9
Post and Page Builder Premium |   | by BoldGrid – 1.0.6
Post and Page Builder |   | by BoldGrid – 1.22.2
Smart Slider 3 |   | by Nextend – 3.5.1.13
WooCommerce Composite Products |   | by WooCommerce – 8.7.1
WooCommerce Stripe Gateway |   | by WooCommerce – 7.1.0
WooCommerce Payments |   | by Automattic – 5.5.0
WooCommerce PayPal Payments |   | by WooCommerce – 2.0.2
WooCommerce Product Bundles |   | by WooCommerce – 6.18.1
WooCommerce Shipping & Tax |   | by WooCommerce – 2.2.3
WooCommerce |   | by Automattic – 7.4.0
WordPress Importer |   | by wordpressdotorg – 0.8
WP Extended Search |   | by 5um17 – 2.1.2
WP Mail Logging |   | by SendLayer – 1.10.5
WP Mail SMTP |   | by WPForms – 3.7.0
WPForms Lite |   | by WPForms – 1.8.0.1
WPS Cleaner |   | by WPServeur, NicolasKulka, wpformation – 1.6.8
YITH WooCommerce Wishlist |   | by YITH – 3.18.0
PayPal Zettle POS |   | by PayPal – 1.5.4

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Happbee 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I believe this issue has already been identified and was fixed in our upcoming release. You can test the [beta release here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.3-rc2) or wait for the official release that should become available today/this week.

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost

**Comment by Happbee** [comment]
I reached the GitHub platform when I clicked the get support link on the
description for the plug in. You may wish to change that link to the actual
support team to prevent future confusion.
