### ISSUE TITLE
Could not retrieve order. This browser may not be supported. Please try again with a different browser.

### ISSUE THREAD

**Issue by ahmadmalik092** [woocommerce/woocommerce-paypal-payments#1225]
### Describe the Bug

Could not retrieve order. This browser may not be supported. Please try again with a different browser

### To Reproduce

When I click on place order button, I get the following error. 
"Could not retrieve order. This browser may not be supported. Please try again with a different browser"

### Screenshots
[InkedFireShot Capture 119 - Store Checkout 04 - Harmless Cigarette™ - harmlesscigarette com_LI](https://user-images.githubusercontent.com/4756343/222657739-3ecdee4d-9f58-4fc9-8d5d-0cf210977e17.jpg)

### Expected Behavior

Click the button should proceed to charge PayPal payment and place an order

### Actual Behavior

showing an error "Could not retrieve order. This browser may not be supported. Please try again with a different browser"

### Environment

 - WordPress Version - 6.0.2
 - WooCommerce Version - 7.4.1
 - Plugin Version - 2.0.2
 - Browser - Google Chrome 110.0.5481.178
 - Elementor Pro - 3.10.2
 - Cartflows - 1.11.9

**Comment by movingelectrons** [comment]
also having this problem

**Comment by geokongr** [comment]
I'm also having this problem with a connected PayPal account. I currently use the latest version of WooCommerce PayPal Payments (2.0.2), WordPress (6.1.1) and WooCommerce (7.4.1). I'm also using the latest version of Chrome 110.0.5481.178 (Official Build) (64-bit).

**Comment by kitsunemax** [comment]
Same error happening here ... please order with paypal (credit card pay), get the same error as above, the order with status [failed] in woocommerce, with order notes aded by the system saying:
> Could not retrieve order. This browser may not be supported. Please try again with a different browser. PayPalGateway.php:472 Order status changed from Pending payment to Failed.
___

When I process to refund (the held transaction via paypal) in the order processing screen (in firefox 10.0 (64-bit)), I then get an error message/alert:
>An error occurred while attempting to create the refund using the payment gateway API.
___

WordPress Version - 6.1.1
WooCommerce Version - 7.4.1
WooCommerce PayPal Payments - 2.0.2
Browser - Google Chrome Version 110.0.5481.100 (Official Build) (x86_64)
Elementor Pro - 3.11.4

**Comment by ahmadmalik092** [comment]
> ### Describe the Bug
> Could not retrieve order. This browser may not be supported. Please try again with a different browser
> 
> ### To Reproduce
> When I click on place order button, I get the following error. "Could not retrieve order. This browser may not be supported. Please try again with a different browser"
> 
> ### Screenshots
> [InkedFireShot Capture 119 - Store Checkout 04 - Harmless Cigarette™ - harmlesscigarette com_LI](https://user-images.githubusercontent.com/4756343/222657739-3ecdee4d-9f58-4fc9-8d5d-0cf210977e17.jpg)
> 
> ### Expected Behavior
> Click the button should proceed to charge PayPal payment and place an order
> 
> ### Actual Behavior
> showing an error "Could not retrieve order. This browser may not be supported. Please try again with a different browser"
> 
> ### Environment
> * WordPress Version - 6.0.2
> * WooCommerce Version - 7.4.1
> * Plugin Version - 2.0.2
> * Browser - Google Chrome 110.0.5481.178
> * Elementor Pro - 3.10.2
> * Cartflows - 1.11.9

I found an error in /modules/ppcp-button/assets/js/button.js 
There was an extra bracket at the end of the code, I removed it and it is now working fine. please check if you guys are also getting js errors in the console.

**Comment by goatcloud** [comment]
Ditto. All software current.

**Comment by kitsunemax** [comment]
> I found an error in /modules/ppcp-button/assets/js/button.js
> There was an extra bracket at the end of the code, I removed it and it is now working fine. please check if you guys are also getting js errors in the console.

Hey there @ahmadmalik092  .... thkns for the fix suggestion.
Wonder if you'd be able to post the code at the end of the file you updated, so can remove the same as what you did, and test the fix  (or if you have submitted a pull request with the fix?)

Thanks, Max

**Comment by ahmadmalik092** [comment]
> > I found an error in /modules/ppcp-button/assets/js/button.js
> > There was an extra bracket at the end of the code, I removed it and it is now working fine. please check if you guys are also getting js errors in the console.
> 
> Hey there @ahmadmalik092 .... thkns for the fix suggestion. Wonder if you'd be able to post the code at the end of the file you updated, so can remove the same as what you did, and test the fix (or if you have submitted a pull request with the fix?)
> 
> Thanks, Max

Hi Max, 
It was my client's website, I don't have access to it now. But while working on it, I found later that it was not a bug in woocommerce-paypal-payments plugin, It was a javascript conflict with better-search-replace plugin. Better-search-replace plugin added its own javascript code at the end of  /modules/ppcp-button/assets/js/button.js and in that code, there was an extra bracket at the end. 

I think if you have js errors on your checkout page, it could prevent woocommerce-paypal-payments js from running. resolving js errors will fix the problem.  

another point to note is, the installed plugin version was 2.0.2

**Comment by thisissandip** [comment]
6030183-zen

**Comment by Sirvijver** [comment]
Hello all, 

@ahmadmalik092 is correct, this issue is most likely caused by a JavaScript issue that causes the WooCommerce button (Place Order) to not be replaced by the generic PayPal button. In some websites and/or web browsers our JavaScript is getting blocked, and the wrong button is being used to create the order, which results in the error you have encountered.

Without using the generic PayPal button to place the order, the payment cannot succeed, so this is a critical issue that needs to be resolved. We advise doing [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to find out what is causing this problem for your site and or review the JavaScript settings of your (or the customers) browser.

This support request was opened on the GitHub forum. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you require additional support. I will mark this thread as closed.

Kind regards, 
Joost

**Comment by anhnnp** [comment]
Hi @Sirvijver can you help me my issue look like the same: 
Could not retrieve order. This browser may not be supported. Please try again with a different browser

I use the voucher I get the above error,
but if i just pay without coupon then success

```
Environment
WordPress Version - 6.2
WooCommerce Version - 6.1.2
WooCommerce PayPal Payments - Plugin Version - 2.0.3
Browser - Google Chrome 108.0.5359.124
```

![error](https://user-images.githubusercontent.com/10054554/229275189-802bc4d0-9339-4347-bc01-bc3abc2794a5.png)
![image](https://user-images.githubusercontent.com/10054554/229275202-cfd1eb6f-bfbb-499c-894d-1c60768661a9.png)
![image](https://user-images.githubusercontent.com/10054554/229275242-56dc19b0-3903-4474-a850-0c64f3eee9d8.png)
![image](https://user-images.githubusercontent.com/10054554/229275287-75fba48f-2799-4da0-af1a-810296d7ba4c.png)

**Comment by renata-franco** [comment]
Hello, I have this case here: 6221690-zd-woothemes

**Comment by TillettDev** [comment]
Hello, also having this issue for a very small number of orders.

"Could not retrieve order. This browser may not be supported. Please try again with a different browser. PayPalGateway.php:472 Order status changed from Pending payment to Failed."

Tried disabling PayPal Pay Later and that reduced it dramatically. However, I had another come through. Any Ideas?

**Comment by hubbybubby23** [comment]
I had the exact same issue. Make sure Woocommerce > settings > payments > paypal > standard payments

Make sure that "Require Instant Payment" is ticked on.

After I turned it on the buttons appeared correctly and the payments went through.

Hope this helps

**Comment by abdullah815** [comment]
> > I found an error in /modules/ppcp-button/assets/js/button.js
> > There was an extra bracket at the end of the code, I removed it and it is now working fine. please check if you guys are also getting js errors in the console.
> 
> Hey there @ahmadmalik092 .... thkns for the fix suggestion. Wonder if you'd be able to post the code at the end of the file you updated, so can remove the same as what you did, and test the fix (or if you have submitted a pull request with the fix?)
> 
> Thanks, Max

I done all things but all in vain

**Comment by behindthescenes2023** [comment]
> I had the exact same issue. Make sure Woocommerce > settings > payments > paypal > standard payments
> 
> Make sure that "Require Instant Payment" is ticked on.
> 
> After I turned it on the buttons appeared correctly and the payments went through.
> 
> Hope this helps

Worked Perfectly!!!!!  Thank you!!
