### ISSUE TITLE
PayPal Smart Payment Buttons not showing 

### ISSUE THREAD

**Issue by tmmngoma** [woocommerce/woocommerce-paypal-payments#1227]
### To Reproduce

1. Go to WooCommerce > Settings > Payments
2. Ensure you are connected to PayPal
3. Enable PayPal features for your store

### Screenshots
<img width="670" alt="1" src="https://user-images.githubusercontent.com/15251242/222673627-f330274e-9b1d-4758-91f5-27a7be411801.png">
<img width="1064" alt="2" src="https://user-images.githubusercontent.com/15251242/222673464-c5260dea-45e8-4b30-a46c-42013fcf7b7c.png">
<img width="1081" alt="3" src="https://user-images.githubusercontent.com/15251242/222673489-ce71fb99-db30-446b-b6e4-d6a54aa7bfe6.png">

### Expected Behavior

Show PayPal Smart Payment Buttons and do payments

### Actual Behavior

Radio button "PayPal"

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.0
 - Plugin 2.0.2
 - Browser Chrome
 - PayPal

  ```

</details>

**Comment by InpsydeNiklas** [comment]
The buttons not displaying in the preview on the settings pages for certain countries was resolved in https://github.com/woocommerce/woocommerce-paypal-payments/pull/1186 for the next update, which can be tested from here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.3-rc2
If you need further assistance, please [get in touch with he support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
