### ISSUE TITLE
Paypal plugin no longer working

### ISSUE THREAD

**Issue by Arthur-Fohrer** [woocommerce/woocommerce-paypal-payments#1228]
Hello,

Originally, there was a problem with webhooks. I disconnected the account and tried to connect it again. 

Now, I cannot connect the paypal account anymore.

Arthur

**Comment by InpsydeNiklas** [comment]
If the onboarding wizard failed too often, PayPal may temporarily limit the API. But please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your system report and PayPal Payments log files for more guidance. Thanks!
