### ISSUE TITLE
Error received 

### ISSUE THREAD

**Issue by uniquegroupltd** [woocommerce/woocommerce-paypal-payments#1230]
Hello, our server receive the following error:

get_cart was called incorrectly. \xe4\xb8\x8d\xe6\x87\x89\xe8\xa9\xb2\xe5\x9c\xa8 wp_loaded \xe5\x8b\x95\xe4\xbd\x9c\xe4\xb9\x8b\xe5\x89\x8d\xe5\x8f\x96\xe5\xbe\x97\xe8\xb3\xbc\xe7\x89\xa9\xe8\xbb\x8a Backtrace: require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce\\PayPalCommerce\\WcGateway\\WCGatewayModule->WooCommerce\\PayPalCommerce\\WcGateway\\{closure}, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\CachingContainer->get, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\CachingContainer->getCached, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\CachingContainer->invokeGenerator, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\CachingContainer->WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\{closure}, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\CompositeContainer->get, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\DelegatingContainer->get, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\DelegatingContainer->invokeFactory, WooCommerce\\PayPalCommerce\\WcGateway\\WCGatewayModule->WooCommerce\\PayPalCommerce\\WcGateway\\{closure}, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\DelegatingContainer->get, WooCommerce\\PayPalCommerce\\Vendor\\Dhii\\Container\\DelegatingContainer->invokeFactory, WooCommerce\\PayPalCommerce\\WcGateway\\WCGatewayModule::WooCommerce\\PayPalCommerce\\WcGateway\\{closure}, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, Woo_Wallet_Frontend->woocommerce_available_payment_gateways, is_wallet_rechargeable_cart, WC_Cart->get_cart, wc_doing_it_wrong. This message was added in version 2.3.

**Comment by InpsydeNiklas** [comment]
This compatibility issues with third-party plugins was resolved for the next update, which can be tested from here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.3-rc2
