### ISSUE TITLE
Upload button is disabled

### ISSUE THREAD

**Issue by LE0616** [woocommerce/woocommerce-paypal-payments#1231]
### To Reproduce

1. Go to 'Active PayPal'
2. Proceed with setup until asked for owner IDs 
3. See error

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
PayPal Payments does not control the PayPal popup window. If you can't progress in the popup for technical reasons, please get in touch with the [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport), or the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) to clarify requirements for your PayPal account.

If you can't complete the onboarding wizard for some reason, you could still manually connect your API credentials as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input
But for any issues regarding the plugin setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
