### ISSUE TITLE
Woocommerece order status did not change when payment is made through Paypal

### ISSUE THREAD

**Issue by Ashbal-P** [woocommerce/woocommerce-paypal-payments#1232]
Fehler bei Statusübergang. Couldn’t find matching email in sites’ users and guests.

Order status works fine on cash option but when customer opt for paypal payment method the order get completed but admin and user dont receive email and woocommerece order note said the line"Fehler bei Statusübergang. Couldn’t find matching email in sites’ users and guests." we have to manually send the email to customer and have to resend new order notification. we are using paypal payments by woocommerece plugin.

### To Reproduce

To reproduce error choose paypal method and book.

### Screenshots

![image](https://user-images.githubusercontent.com/127184082/223350944-4bc48a22-f51f-43bc-9545-3af04434e4ea.png)

### Expected Behavior

On order completion new order notification should be send to admin and order completion mail to customer

### Actual Behavior

Mails are not initiated when payment is made through paypal

### Environment

 - WordPress Version:6.1.1
 - WooCommerce Version:7.4.1
 - Plugin Version:2.0.2
 - Browser Chrome ver:110.0.5481.178 (Official Build) (64-bit)
 - Chauffeur Booking System:6.7
 - Kadence Woocommerece email Designer:1.5.7

### Additional Details

`
### WordPress Environment ###

WordPress address (URL):
Site address (URL):
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 392 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.7.41-log
Max Upload Size: 92 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wpi0_
Total Database Size: 201.88MB
Database Data Size: 161.33MB
Database Index Size: 40.55MB

### Post Type Counts ###

attachment: 1579
chbs_booking: 951
chbs_booking_extra: 3
chbs_booking_form: 1
chbs_email_account: 1
chbs_geofence: 204
chbs_location: 1
chbs_price_rule: 295
chbs_route: 6
chbs_tax_rate: 4
chbs_vehicle: 3
chbs_vehicle_attr: 9
cookielawinfo: 6
custom_css: 1
elementor_font: 1
elementor_icons: 1
elementor_library: 26
elementor_snippet: 2
elementor-hf: 1
is_search_form: 1
language_switcher: 4
nav_menu_item: 4
page: 1325
post: 5607
revision: 187
shop_order: 851
shop_order_refund: 31
shopmagic_automation: 1
wp_global_styles: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

All-in-One WP Migration: by ServMask – 7.71
Chauffeur Booking System for WordPress: by QuanticaLabs – 6.7
Elementor Pro: by Elementor.com – 3.6.5
Elementor: by Elementor.com – 3.11.2
Instant Indexing: by Rank Math – 1.1.16
G Meta Keywords: by Sinan Yorulmaz – 1.4
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.7
Really Simple SSL: by Really Simple Plugins – 6.2.0
Slider Revolution: by ThemePunch – 6.6.11
ShopMagic für WooCommerce: by WP Desk – 3.0.8
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.4.9

WooCommerce PayPal Payments: by WooCommerce – 2.0.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.4.0
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.19.6
WooCommerce: by Automattic – 7.4.1
Wordfence Security: by Wordfence – 7.9.1
Yoast SEO Premium: by Team Yoast – 20.0
Yoast SEO: by Team Yoast – 20.2.1
Asset CleanUp: Page Speed Booster: by Gabe Livan – 1.3.9.1
WP Mail Logging: by SendLayer – 1.10.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.12

Sequential Order Numbers for WooCommerce: by WebToffee – 1.5.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #10486 - /privacy-policy/

### Theme ###

Name: Astra
Version: 4.0.2
Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: 
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-02-24 14:55:09 +00:00
Options: ✔
Notes: 84
Onboarding: completed

### Action Scheduler ###

Complete: 41
Oldest: 2023-02-04 14:07:02 +0000
Newest: 2023-03-07 07:14:48 +0000

Failed: 6
Oldest: 2023-01-06 11:25:57 +0000
Newest: 2023-03-07 07:09:09 +0000

Pending: 1
Oldest: 2023-03-07 19:17:38 +0000
Newest: 2023-03-07 19:17:38 +0000

### Status report information ###

Generated at: 2023-03-07 08:22:24 +01:00
`
 

</details>

**Comment by InpsydeNiklas** [comment]
This error is not coming from PayPal Payments but from a third-party plugin. PayPal Payments also is not responsible for sending email notifications as this is done by WooCommerce.
If you encounter problems with the PayPal Payments plugin, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
