### ISSUE TITLE
iDeal Payment method have never worked

### ISSUE THREAD

**Issue by erick3000** [woocommerce/woocommerce-paypal-payments#1233]
Hello

Customers paying with iDeal get charged, yet no error is given to the customer, no invoice from paypal, no invoice from woocommerce, nothing. Just a charge on their account which does eventually clears out.

This is unrelated to woocommerce version or wordpress as the issue has been the same for several years. Have you guys even tested iDeal before getting it to production?

Never had an issue with stripe and iDeal so definitely a PayPal issue with this plug in.

Netherland citizens do prefer to pay with iDeal so hopefully you can find what the issue is. i which i could help but since there is no trace other than customers complaining of a charge with no invoice, error, or obsoletely anything.

**Comment by lemonbyte** [comment]
This problem occurs only with mobile payment through the banking app. 

When using the e.g. QR, the problem is not there.

**Comment by lemonbyte** [comment]
The webhook is not called or not called in a correct way when using banking app with ideal payments

**Comment by lemonbyte** [comment]
Same -> iDeal issue via mobile phone #1179

**Comment by erick3000** [comment]
So, no solution then? how about killing it by default? 99% of purchase are done on mobile now a days.

Not trying to be an azz but imagine how customers feel, like they are getting ripped off or scammed....

**Comment by wakdev** [comment]
We have the same problem on Prestashop... Did you find a solution?

**Comment by erick3000** [comment]
> We have the same problem on Prestashop... Did you find a solution?

They haven't fixed it in years, don't expect much.
