### ISSUE TITLE
How to modify the content submitted by the paypal button

### ISSUE THREAD

**Issue by springAndSpring** [woocommerce/woocommerce-paypal-payments#1244]
![image](https://user-images.githubusercontent.com/66676765/224891963-ea02ec5a-5079-429b-a139-34592cc74d20.png)
Sorry to bother my friend, I have a problem using this plug-in. When I click this button to pay, I want to see what data I submitted, but I can't find the code. Can you tell me

**Comment by InpsydeNiklas** [comment]
Hi @tutouchengxuyuan 
The submitted data is stored in the logs when Logging is enabled in the Connection tab.
The plugin provides filters to modify the order creation and patch data sent to PayPal: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#modify-the-order-creation-request-body-data
But if you need more guidance, I suggest to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
