### ISSUE TITLE
Users not able to pay and order keeps in the pending or cancelled 

### ISSUE THREAD

**Issue by asharma16891** [woocommerce/woocommerce-paypal-payments#1252]
### Describe the Bug

Using the Paypal payment method user is not able to pay and the order keep going into the pending status and then the status is changed to Cancelled. 
I even disable Hold on by removing the number and this is before -  https://prnt.sc/FX0dTdHUaOQ_ 

Now as well the issue exist as now today the order status is on Pending Status

### Screenshots

https://prnt.sc/q0XI8YX2xTcK - When Hold on the feature set to 60 mins
https://prnt.sc/JDtg0wQaPa7C - After disabling the Hold on option

### Environment

`
### WordPress Environment ###

WordPress address (URL): http://www.patienthandling.com.au
Site address (URL): https://www.patienthandling.com.au
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.7.39-google-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 599.31MB
Database Data Size: 335.42MB
Database Index Size: 263.89MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 19.55MB + Index: 16.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.02MB + Index: 9.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 2.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 10.52MB + Index: 10.06MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 2.52MB + Index: 0.42MB + Engine InnoDB
wp_gf_entry_meta: Data: 6.52MB + Index: 11.41MB + Engine InnoDB
wp_gf_entry_notes: Data: 2.52MB + Index: 0.41MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.25MB + Index: 0.20MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_lecm_rewrite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 6.19MB + Index: 3.20MB + Engine InnoDB
wp_postmeta: Data: 124.67MB + Index: 82.91MB + Engine InnoDB
wp_posts: Data: 20.48MB + Index: 7.80MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 1.42MB + Index: 0.28MB + Engine InnoDB
wp_terms: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_term_relationships: Data: 1.48MB + Index: 0.44MB + Engine InnoDB
wp_term_taxonomy: Data: 0.34MB + Index: 0.16MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 14.52MB + Index: 12.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 1.77MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.52MB + Index: 2.66MB + Engine InnoDB
wp_wc_order_stats: Data: 2.52MB + Index: 3.36MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.06MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.28MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_woo_ua_auction_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_csv_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_publisher: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_table_design: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfb_total_averages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 10.52MB + Index: 25.64MB + Engine InnoDB
wp_wps_index: Data: 62.59MB + Index: 61.64MB + Engine InnoDB
wp_wps_key: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
wp_wps_object_type: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_wps_uri: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_wps_user_agent: Data: 0.31MB + Index: 0.11MB + Engine InnoDB
wp_yith_ywrac_email_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 6.33MB + Index: 2.38MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.33MB + Index: 0.42MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.23MB + Index: 0.16MB + Engine InnoDB

### Post Type Counts ###

acf-field: 204
acf-field-group: 33
addify_quote: 7
addify_rfq: 2
attachment: 6243
imgt_log: 500
nav_menu_item: 129
oembed_cache: 22
option-tree: 1
page: 44
post: 7
postman_sent_mail: 72
product: 498
product_variation: 852
resources: 87
revision: 775
shop_order: 19294
shop_order_refund: 431
shop_quote: 110
wp_global_styles: 1
wpcf7_contact_form: 1
ywrac_cart: 9
ywrac_email: 2
ywraq-pdf-template: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Gravity Forms: by Gravity Forms – 2.7.2
Advanced Custom Fields PRO: by WP Engine – 6.0.7
Akismet Anti-Spam: by Automattic – 5.0.2
Facebook for WooCommerce: by Facebook – 3.0.14
Gravity Forms Mailchimp Add-On: by Gravity Forms – 5.2.0
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 10.0.25
W3 Total Cache: by BoldGrid – 2.3.0
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.3
Stock Manager for WooCommerce: by StoreApps – 2.10.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.29
WooCommerce: by Automattic – 7.4.1 (update to version 7.5.0 is available)
Wordfence Security: by Wordfence – 7.9.1
Yoast SEO: by Team Yoast – 20.3
WP Crontrol: by John Blackbourn & crontributors – 1.15.1
WP Mail SMTP: by WPForms – 3.7.0
WPS Hide Login & Checkout: by WPServeur
NicolasKulka
wpformation – 1.9.8

YITH WooCommerce Recover Abandoned Cart Premium: by YITH – 2.20.0
YITH WooCommerce Request A Quote Premium: by YITH – 4.9.0
Zip - WooCommerce: by Zip – 2.3.16

### Inactive Plugins (4) ###

Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.4.0
GTM4WP: by Thomas Geiger – 1.16.2
Imagify | Tools: by WP Media –
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #20 - /shop/
Cart: #21 - /cart/
Checkout: #22 - /checkout/
My account: #23 - /my-account/
Terms and conditions: #91 - /terms-conditions/

### Theme ###

Name: Patient Handling
Version: 1.0
Author URL: http://believintech.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: patient-handling/woocommerce/archive-product.php
patient-handling/woocommerce/cart/cart-shipping.php
patient-handling/woocommerce/cart/cart.php version 7.0.1 is out of date. The core version is 7.4.0
patient-handling/woocommerce/checkout/form-checkout.php
patient-handling/woocommerce/checkout/review-order.php
patient-handling/woocommerce/checkout/thankyou.php
patient-handling/woocommerce/content-single-product.php
patient-handling/woocommerce/emails/admin-new-order.php
patient-handling/woocommerce/emails/customer-completed-order.php
patient-handling/woocommerce/emails/customer-processing-order.php
patient-handling/woocommerce/emails/plain/customer-completed-order.php
patient-handling/woocommerce/order/order-details.php
patient-handling/woocommerce/single-product/add-to-cart/external.php
patient-handling/woocommerce/single-product/add-to-cart/grouped.php
patient-handling/woocommerce/single-product/add-to-cart/simple.php
patient-handling/woocommerce/single-product/add-to-cart/variable.php
patient-handling/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
patient-handling/woocommerce/single-product/add-to-cart/variation.php
patient-handling/woocommerce/single-product/meta.php
patient-handling/woocommerce/single-product/product-image.php
patient-handling/woocommerce/single-product/product-thumbnails.php
patient-handling/woocommerce/single-product/related.php
patient-handling/woocommerce/single-product/review-meta.php
patient-handling/woocommerce/single-product/short-description.php
patient-handling/woocommerce/single-product/tabs/description.php
patient-handling/woocommerce/single-product/tabs/tabs.php
patient-handling/woocommerce/single-product/title.php
patient-handling/woocommerce/single-product-reviews.php
patient-handling/woocommerce/single-product.php
patient-handling/taxonomy-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AU
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-14 23:39:39 +11:00
Options: ✔
Notes: 113
Onboarding: completed

### Action Scheduler ###

Complete: 3,023
Oldest: 2023-02-13 09:35:42 +1100
Newest: 2023-03-15 01:21:05 +1100

Failed: 4
Oldest: 2022-12-23 21:38:01 +1100
Newest: 2023-03-14 21:54:04 +1100

Pending: 2
Oldest: 2023-03-15 16:50:05 +1100
Newest: 2023-03-15 23:28:41 +1100

### Status report information ###

Generated at: 2023-03-15 01:45:59 +11:00
`

**Comment by asharma16891** [comment]
While looking more into the log file I noticed for all the users who couldn't;t able to pay even though they got charged the log file doesn't trigger PAYMENT.CAPTURE.COMPLETED event/webhooks

I believe this might be the reason for this but waiting for the solid fix

**Comment by youmaz1** [comment]
did you solve the issue, I have the same problem

**Comment by asharma16891** [comment]
> did you solve the issue, I have the same problem

No, it is still open but now it's happening with one user per day after I update this setting - https://prnt.sc/FX0dTdHUaOQ_ 

Now, this is also happening with the Stripe Payment method..... 

Not sure what is happening...

**Comment by ichiba-n** [comment]
hi. Have you solved the issue yet? I'm having the same problem

**Comment by Sirvijver** [comment]
Hello all,

The GitHub forum is only used for development activities, not for support requests. In order to get continued support, I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. After this response, this support request will be closed.

The issue does sound like you might have an issue with the webhooks. The first thing to do is to check the webhook status by using the webhooks tools that you can find in the setting page in the bottom of the "Connection" tab. Here you will find the "Simulate" and "Resubscribe" button that will give you the status of the webhooks. If you require additional support, please show us what the outcome is when you use these buttons and what webhook URLs are shown on this page.

Kind regards, 
Joost
