### ISSUE TITLE
Uncaught ReferenceError: paypal is not defined

### ISSUE THREAD

**Issue by TonystarAGB** [woocommerce/woocommerce-paypal-payments#1258]
### Describe the Bug

Uncaught SyntaxError: Unexpected token '<' (at undefined:1:1)
Renderer.js:68 Uncaught ReferenceError: paypal is not defined
    at e.value (Renderer.js:68:151)
    at e.value (Renderer.js:22:18)
    at e.value (CheckoutBootstap.js:67:23)
    at e.value (CheckoutBootstap.js:21:14)
    at button.js:154:26
    at HTMLScriptElement.<anonymous> (button.js:247:13)

But disabled your plugin not show error and all right

### To Reproduce

1. Go to www.sanitarbaby.com
2. Add to cart a product
3. Navigate page cart and checkout
4. Open console browser adn see errot

### Screenshots

![image](https://user-images.githubusercontent.com/44058398/225681617-59dde0d6-aa3f-4769-b35e-4f6a99098e0b.png)

### Environment

 WordPress address (URL): https://www.sanitarbaby.com
Site address (URL): https://www.sanitarbaby.com
WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 8000
cURL Version: 7.84.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-cll-lve
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.1
WC Database Prefix: wpzy_
Dimensione totale database: 248.14MB
Dimensione dati database: 206.08MB
Dimensione indice database: 42.06MB
wpzy_woocommerce_sessions: Dati: 11.32MB + indice: 0.43MB + motore MyISAM
wpzy_woocommerce_api_keys: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_woocommerce_attribute_taxonomies: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_downloadable_product_permissions: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_order_items: Dati: 0.07MB + indice: 0.03MB + motore MyISAM
wpzy_woocommerce_order_itemmeta: Dati: 0.55MB + indice: 0.32MB + motore MyISAM
wpzy_woocommerce_tax_rates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_tax_rate_locations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_shipping_zones: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_shipping_zone_locations: Dati: 1.00MB + indice: 0.96MB + motore MyISAM
wpzy_woocommerce_shipping_zone_methods: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_payment_tokens: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_payment_tokenmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_woocommerce_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_actionscheduler_actions: Dati: 5.87MB + indice: 2.45MB + motore MyISAM
wpzy_actionscheduler_claims: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_actionscheduler_groups: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_actionscheduler_logs: Dati: 4.85MB + indice: 3.29MB + motore MyISAM
wpzy_berocket_termmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_braapf_product_stock_status_parent: Dati: 0.11MB + indice: 0.19MB + motore MyISAM
wpzy_braapf_product_variation_attributes: Dati: 0.02MB + indice: 0.04MB + motore MyISAM
wpzy_braapf_term_taxonomy_hierarchical: Dati: 0.01MB + indice: 0.03MB + motore MyISAM
wpzy_braapf_variable_attributes: Dati: 0.02MB + indice: 0.04MB + motore MyISAM
wpzy_brb_business: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_brb_review: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_chaty_contact_form_leads: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_commentmeta: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpzy_comments: Dati: 0.27MB + indice: 0.09MB + motore MyISAM
wpzy_e_events: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_e_notes: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_e_notes_users_relations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_e_submissions: Dati: 0.00MB + indice: 0.03MB + motore MyISAM
wpzy_e_submissions_actions_log: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_e_submissions_values: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_gla_attribute_mapping_rules: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_gla_budget_recommendations: Dati: 0.11MB + indice: 0.12MB + motore MyISAM
wpzy_gla_merchant_issues: Dati: 3.96MB + indice: 0.17MB + motore MyISAM
wpzy_gla_shipping_rates: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_gla_shipping_times: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_imagify_files: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_imagify_folders: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_links: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_mailchimp_carts: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_mailchimp_jobs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_mailerlite_checkouts: Dati: 0.06MB + indice: 0.00MB + motore MyISAM
wpzy_ml_data: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_options: Dati: 6.50MB + indice: 0.21MB + motore MyISAM
wpzy_postmeta: Dati: 158.69MB + indice: 29.08MB + motore InnoDB
wpzy_posts: Dati: 9.19MB + indice: 1.68MB + motore MyISAM
wpzy_rank_math_404_logs: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_rank_math_analytics_objects: Dati: 0.09MB + indice: 0.07MB + motore MyISAM
wpzy_rank_math_internal_links: Dati: 0.09MB + indice: 0.02MB + motore MyISAM
wpzy_rank_math_internal_meta: Dati: 0.01MB + indice: 0.01MB + motore MyISAM
wpzy_rank_math_redirections: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpzy_rank_math_redirections_cache: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_revslider_css: Dati: 0.09MB + indice: 0.01MB + motore MyISAM
wpzy_revslider_css_bkp: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_layer_animations: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_layer_animations_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_navigations: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_navigations_bkp: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_sliders: Dati: 0.06MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_sliders_bkp: Dati: 0.06MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_slides: Dati: 0.19MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_slides_bkp: Dati: 0.22MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_static_slides: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_revslider_static_slides_bkp: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_rsgiftvoucher: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_rspointexpiry: Dati: 0.04MB + indice: 0.01MB + motore MyISAM
wpzy_rsrecordpoints: Dati: 0.05MB + indice: 0.01MB + motore MyISAM
wpzy_rs_expiredpoints_email: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_rs_templates_email: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_snp_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_snp_stats: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_sumo_reward_encashing_submitted_data: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_sumo_reward_send_point_submitted_data: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_termmeta: Dati: 0.41MB + indice: 0.23MB + motore MyISAM
wpzy_terms: Dati: 0.03MB + indice: 0.05MB + motore MyISAM
wpzy_term_relationships: Dati: 0.22MB + indice: 0.44MB + motore MyISAM
wpzy_term_taxonomy: Dati: 0.11MB + indice: 0.04MB + motore MyISAM
wpzy_tm_taskmeta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_tm_tasks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_usermeta: Dati: 0.64MB + indice: 0.34MB + motore MyISAM
wpzy_users: Dati: 0.03MB + indice: 0.05MB + motore MyISAM
wpzy_wc_admin_notes: Dati: 0.04MB + indice: 0.00MB + motore MyISAM
wpzy_wc_admin_note_actions: Dati: 0.02MB + indice: 0.01MB + motore MyISAM
wpzy_wc_category_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_wc_customer_lookup: Dati: 0.04MB + indice: 0.03MB + motore MyISAM
wpzy_wc_download_log: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_wc_order_coupon_lookup: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_wc_order_product_lookup: Dati: 0.06MB + indice: 0.06MB + motore MyISAM
wpzy_wc_order_stats: Dati: 0.02MB + indice: 0.02MB + motore MyISAM
wpzy_wc_order_tax_lookup: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.03MB + motore MyISAM
wpzy_wc_product_download_directories: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_wc_product_meta_lookup: Dati: 0.53MB + indice: 0.95MB + motore MyISAM
wpzy_wc_rate_limits: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_wc_reserved_stock: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_wc_tax_rate_classes: Dati: 0.00MB + indice: 0.01MB + motore MyISAM
wpzy_wc_webhooks: Dati: 0.00MB + indice: 0.00MB + motore MyISAM
wpzy_wpr_rocket_cache: Dati: 0.27MB + indice: 0.37MB + motore MyISAM
wpzy_wpr_rucss_used_css: Dati: 0.00MB + indice: 0.02MB + motore MyISAM
wpzy_yith_wapo_addons: Dati: 0.07MB + indice: 0.00MB + motore MyISAM
wpzy_yith_wapo_blocks: Dati: 0.01MB + indice: 0.00MB + motore MyISAM
wpzy_yith_wccl_meta: Dati: 0.00MB + indice: 0.00MB + motore MyISAM

### Post Type Counts ###

acf-field: 2
acf-field-group: 2
attachment: 10803
brand: 1
brb_collection: 3
br_filters_group: 4
br_labels: 1
br_notice: 4
br_product_filter: 8
bwp_footer: 5
bwp_megamenu: 14
custom_css: 2
elementor_library: 34
elementor_snippet: 2
elementskit_content: 26
gift_card: 3
grw_feed: 1
nav_menu_item: 53
oembed_cache: 5
page: 41
post: 8
product: 2232
product_variation: 3889
rank_math_locations: 2
revision: 82
seedprod: 1
shopengine-template: 2
shop_coupon: 32
shop_order: 277
shop_order_refund: 5
srp_birthday: 50
srp_promotional: 1
sumomasterlog: 107
sumomembershipplans: 1
sumosubscriptions: 8
sumosubs_cron_events: 8
wcpa_pt_forms: 1
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

WooCommerce Advanced Product Labels: by BeRocket – 1.2.4.1
Bopo - WooCommerce Product Bundle Builder Premium: by VillaTheme – 1.0.5.1
Brands for WooCommerce: by BeRocket – 3.7.0.6
bunny.net: by bunny.net – 1.0.8
Business Reviews Bundle: by RichPlugins  – 1.9.11
Chaty: by Premio – 3.0.7
Cloudflare: by Cloudflare
Inc. – 4.11.0

GTM4WP: by Thomas Geiger – 1.16.2
Easy Table of Contents: by Magazine3 – 2.0.45.2
Elementor Pro: by Elementor.com – 3.11.6
Elementor: by Elementor.com – 3.11.5
ElementsKit Lite: by Wpmet – 2.8.5
ElementsKit Pro: by Wpmet – 3.2.0
Facebook for WooCommerce: by Facebook – 3.0.15
Google Listings and Ads: by WooCommerce – 2.4.1
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1
Make, formerly Integromat Connector: by Celonis s.r.o. – 1.5.4
Klarna On-Site Messaging for WooCommerce: by krokedil
klarna – 1.10.0

Klarna Order Management for WooCommerce: by klarna
krokedil – 1.7.1

Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 3.0.5

One User Avatar: by One Designs – 2.3.9
Perfmatters: by forgemedia – 2.0.7
Product XML Feeds for WooCommerce: by WPWhale – 2.7.2
SUMO Reward Points: by Fantastic Plugins – 28.2
Rank Math SEO: by Rank Math – 1.0.110.1
ShopEngine Pro: by Wpmet – 2.2.1
ShopEngine: by Wpmet – 4.1.0
Soisy Pagamento Rateale: by Soisy – 6.0.1
SUMO Subscriptions: by Fantastic Plugins – 14.4.1
Use Memcached: by Palasthotel  (in person: Edward Bock) – 1.0.4
CTX Feed: by WebAppick – 5.3.1
MailerLite - WooCommerce integration: by MailerLite – 1.8.4
Pacchetti di prodotti WPC per WooCommerce: by WPClever – 7.0.7
WPC Smart Wishlist for WooCommerce: by WPClever – 4.6.2
WooCommerce AJAX Products Filter: by BeRocket – 3.1.3.3
WooCommerce Stripe Gateway: by WooCommerce – 7.2.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.3
WooCommerce Product Variations Swatches Premium: by VillaTheme – 1.0.13
WooCommerce: by Automattic – 7.5.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.13

WP Rocket: by WP Media – 3.12.6.1
Wp Social: by Wpmet – 2.2.2
YITH WooCommerce Gift Cards: by YITH – 2.19.0
YITH WooCommerce Product Add-ons & Extra Options: by YITH – 2.19.0

### Inactive Plugins (3) ###

Loco Translate: by Tim Whitlock – 2.6.4
Query Monitor: by John Blackbourn – 3.11.2
SUMO Discounts: by Fantastic Plugins – 5.9.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Perfmatters MU: by forgemedia – 2.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bopobb (bopobb)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
woosb (woosb)
woosg (woosg)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /negozio/
Carrello: #7 - /carrello/
Pagamento: #8 - /pagamento/
Il mio account: #39862 - /account-utente/
Termini e condizioni: #23076 - /termini-e-condizioni/

### Theme ###

Name: Hello Elementor Child
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.6.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Klarna Payments Request Log ###

2022-12-08 13:02:27: KP Create Session
Response code: 
Response message: {"errors":{"http_request_failed":["cURL error 28: Failed to connect to api.klarna.com port 443: Connection timed out"]},"error_data":[]}
Correlation ID:

2022-12-08 13:02:17: KP Create Session
Response code: 
Response message: {"errors":{"http_request_failed":["cURL error 28: Failed to connect to api.klarna.com port 443: Connection timed out"]},"error_data":[]}
Correlation ID:

2022-04-01 16:46:18: KP test credentials
Response code: 401
Response message: 
Correlation ID:

2022-03-28 14:08:45: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"2f283ff1-b4e0-47da-96be-0bc18b7f189b\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:08:45: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"079ffbf9-e9aa-4595-b872-fe4bce825db7\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:08:41: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"f19b647f-6428-4365-a63b-a37e8a361f1f\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:08:41: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"2c0ccdf8-d046-42d7-b2a6-17e57dc9ee25\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:08:40: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"26d758c0-d383-4fb1-8193-7a1b6ada75d7\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:08:40: KP Create Session
Response code: 403
Response message: {"headers":[],"body":"{\n  \"error_code\" : \"INVALID_OPERATION\",\n  \"error_messages\" : [ \"\" ],\n  \"correlation_id\" : \"c604038e-096e-4ac3-8522-c3e800485383\"\n}","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
Correlation ID:

2022-03-28 14:06:25: KP test credentials
Response code: 403
Response message: {"error_code":"INVALID_OPERATION","error_messages":[""],"correlation_id":"f8c9ab0f-8185-4e10-b33e-cae48f0c05b6"}
Correlation ID: f8c9ab0f-8185-4e10-b33e-cae48f0c05b6

2022-03-28 11:28:12: KP test credentials
Response code: 403
Response message: {"error_code":"INVALID_OPERATION","error_messages":[""],"correlation_id":"006cc5ae-acd8-4b15-a91d-c0acc5a9a9f7"}
Correlation ID: 006cc5ae-acd8-4b15-a91d-c0acc5a9a9f7

### Klarna Countries ###

Production Countries: IT
Test Countries: No countries selected

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-16 21:33:55 +01:00
Options: ✔
Notes: 107
Onboarding: completed

### Action Scheduler ###

Complete: 18.908
Oldest: 2023-02-13 16:18:49 +0000
Newest: 2023-03-16 15:54:02 +0000

Failed: 2.053
Oldest: 2022-01-16 05:28:49 +0000
Newest: 2023-03-15 11:45:58 +0000

Pending: 4
Oldest: 2023-03-17 03:00:00 +0000
Newest: 2023-03-17 04:21:19 +0000

### Status report information ###

Generated at: 2023-03-16 17:08:19 +01:00

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by TonystarAGB** [comment]
if I try to pay despite the error, it returns me this string:
Could not retrieve order. This browser may not be supported. Please try again with a different browser.

![image](https://user-images.githubusercontent.com/44058398/225690665-97afb735-9117-40e0-981a-cf46bca0c7da.png)

**Comment by TonystarAGB** [comment]
I resolved this bug, conflict with bunny cdn plugin and now show button in checkout and cart. But now only in checkout page i see this error:

![image](https://user-images.githubusercontent.com/44058398/225716804-daea8b63-77cb-43cf-a083-a9e7886a6756.png)

**Comment by Sirvijver** [comment]
Hello,

We have seen this error (Unexpected token '<', ") before with other merchants. There is an issue with your site and the only way you can find out what is causing this is by doing conflict testing. However, in order to perform these tests, you will need to find out how you can reproduce this error. Have you tried recreating the order that your customer was making when he encountered this issue?

Once you can reproduce the issue, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

This staging site plugin only works for single sites, not multisite. If you can't get this to work, you might want to reach out to your hosting partner and ask if they have any solutions for this or (last option) to test on your live site (be sure to have a backup of your site!!!).

This is a support request, and we only do development activities via GitHub, so I will have to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need additional support. We will mark this thread as resolved. I would be good to reach out to us with this new error you got after testing, but it depends on the fact if this is an affecting issue, because I am expecting this is an error that does not affect the functioning of our plugin. Please reach out if it does.

Kind regards,
Joost
