### ISSUE TITLE
WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by TheOnvipeBand** [woocommerce/woocommerce-paypal-payments#1261]
### Describe the Bug

EMAIL From: CleanTalk [mailto:welcome@cleantalk.org] 
Sent: 17. marts 2023 02:20
To: CleanTalk@tryware.dk
Subject: Malware Issues on astroguide.info Mar 17 2023 02:20:02

Malware Issues
Time	Mar 17 2023 02:20:02
Hostname	astroguide.info
Plugin	wordpress-security-2.105
Scanned files	1140
Result	WARNING

These files may not contain malicious code but they use very dangerous PHP functions and constructions! PHP developers don't recommend to use such code. Besides, it looks very suspicious.

### To Reproduce

1. Go to 'Please, check scan results in your WP dashboard:
http://astroguide.info/wp-admin/options-general.php?page=spbc '
2. Click on 'Settings/Security by CleanTalk/Malware Scanner - Perform Scan'
3. Scroll down to Critical 8'

Failed files: 8
Path	Modify time	MD5 Hash	Plugin
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php	Mar 14 2023 11:59:49	e3ee50bde318003ab1dd07a668605a8a	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/CompatModule.php	Mar 14 2023 11:59:49	026f65f0a40dca54e79bb99198785735	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php	Mar 14 2023 11:59:49	9502d1c14e13ccb088ce62c610c424d4	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/Fields/connection-tab-fields.php	Mar 14 2023 11:59:49	24cd51a11216ad0588f9db31794e489d	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/Fields/pay-later-tab-fields.php	Mar 14 2023 11:59:49	a0f29542cc3c26cc94792bc9f3c14f2e	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/Fields/paypal-smart-button-fields.php	Mar 14 2023 11:59:49	8369b933febf7284ce38c2bd73398362	-
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php	Mar 14 2023 11:59:49	6cb653b46dcaf5d76d14f793134dbaca	-
/wp-content/plugins/woocommerce-paypal-payments/uninstall.php	Mar 14 2023 11:59:50	a37546d3f10743377d3868c95535240c

### Screenshots

![image](https://user-images.githubusercontent.com/128118956/225819939-88a1d65a-42a9-4e40-8620-377a6853b876.png)
![image](https://user-images.githubusercontent.com/128118956/225820110-f950c2d4-9702-4abf-9220-26fe152f41bb.png)

All 8 shows identical warnings: Detected Heuristic: assert (Using the function in production is not recommended)

![image](https://user-images.githubusercontent.com/128118956/225820206-b368556d-1ae3-4b5e-877e-1e9bb1a6050b.png)
![image](https://user-images.githubusercontent.com/128118956/225820291-9d9d89cf-c171-4176-9561-98185a06bf13.png)

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.5.0
 - Plugin Version WooCommerce Paypal Payments 2.0.3 THIS IS THE PLUGIN THAT CREATES THE CLEANTALK WARNING
 - Browser [e.g. Chrome, Safari] and Version Mozilla Firefox 109.0.1 64-bit
 - Any other plugins installed
  
![image](https://user-images.githubusercontent.com/128118956/225819518-d530e73f-bc6e-4ac5-87a9-5ac4412cafc2.png)
![image](https://user-images.githubusercontent.com/128118956/225819700-6315ab95-8f0f-4e4e-98d8-955ed87ce30e.png)
![image](https://user-images.githubusercontent.com/128118956/225819769-7c97d99b-3786-481c-90b8-294731220edb.png)

### Additional Details

I want WooCommerce to solve this issue, maybe contacting https://cleantalk.org about WHY they produce this Warning cause I am using their https://wordpress.org/support/plugin/security-malware-firewall plugin

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by TheOnvipeBand** [comment]
After sending the issue to welcome@cleantalk.org I have now been told, that "The files are safe. Not recommended functions were used, but nothing critical."

--------


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:\Users\Jmalm\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:\Users\Jmalm\AppData\Local\Temp\msohtmlclip1\01\clip_editdata.mso">

<link rel=themeData
href="file:///C:\Users\Jmalm\AppData\Local\Temp\msohtmlclip1\01\clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:\Users\Jmalm\AppData\Local\Temp\msohtmlclip1\01\clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DA link=blue vlink="#954F72" style='tab-interval:65.2pt'>


<p class=MsoNormal><b><span lang=EN-US style='font-size:11.0pt;font-family:
"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:
EN-US'>From:</span></b><span lang=EN-US style='font-size:11.0pt;font-family:
"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman";mso-ansi-language:
EN-US'> Serge B [mailto:serge.b@cleantalk.org] <br>
<b>Sent:</b> 17. marts 2023 10:15<br>
<b>To:</b> jmalmgren@tryware.dk<br>
<b>Cc:</b> CleanTalk@tryware.dk<br>
<b>Subject:</b> Re: Malware Issues on astroguide.info Mar 17 2023 02:20:02<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>The files are
safe. Not recommended functions were used, but nothing critical.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-family:"Arial",sans-serif'>Best regards<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



  |   | Serge   Technical Support Engineer       CleanTalk Inc., Carson City, NV,   89701   CleanTalk.org
-- | -- | --
  |   |  
  |   | Our services: WordPress Security Service \| SSL Certificate \| CleanTalk   Database of spam IP/emails \| CleanTalk Anti-Spam




</body>

</html>
From: Serge B [mailto:serge.b@cleantalk.org] 
Sent: 17. marts 2023 10:15
To: jmalmgren@tryware.dk
Cc: CleanTalk@tryware.dk
Subject: Re: Malware Issues on astroguide.info Mar 17 2023 02:20:02

The files are safe. Not recommended functions were used, but nothing critical.

Best regards

 
	Serge
Technical Support Engineer

CleanTalk Inc., Carson City, NV, 89701
[CleanTalk.org](http://www.cleantalk.org/)

		
 
	Our services: [WordPress Security Service](https://cleantalk.org/wordpress-security-malware-firewall) | [SSL Certificate](https://cleantalk.org/ssl-certificates/cheap-positivessl-certificate) | [CleanTalk Database of spam IP/emails](https://cleantalk.org/blacklists) | [CleanTalk Anti-Spam](https://cleantalk.org/about)

**Comment by Sirvijver** [comment]
Hello @TheOnvipeBand 

This seems to be a support request that you handled yourself. I will close this thread and because we only handle development cases on GitHub, I would like to advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you require more guidance.

Kind regards, 
Joost
