### ISSUE TITLE
Pago no recibido

### ISSUE THREAD

**Issue by Svitbytka** [woocommerce/woocommerce-paypal-payments#1265]
![WhatsApp Image 2023-03-18 at 4 05 38 PM](https://user-images.githubusercontent.com/94603191/226117001-4519928a-f679-44f0-aced-b259fdd0205a.jpeg)

Buenos días, hoy una clienta hizo pago desde la web pero pulsando boton de PayPal. No se porque pero no tengo información sobre el pedido, tampoco tengo ingreso en Paypal. 
¿Qué podría pasar?

**Comment by InpsydeNiklas** [comment]
Hi @Svitbytka 
The WooCommerce order is created once the buyer confirmed the payment in the PayPal popup window.
If no WooCommerce order was created, then PayPal also would not capture any payment. If the buyer somehow managed to authorize a payment, they should usually be automatically refunded if the amount was not captured within three hours.

But we would be happy to investigate this behavior further. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
