### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by springAndSpring** [woocommerce/woocommerce-paypal-payments#1266]
I saw what I wanted to see on the wiki, but I don't know where this piece of code should be added. Could someone please tell me, thank you very much
![1679183834553](https://user-images.githubusercontent.com/66676765/226146156-d7aa1058-2e83-491b-951c-2e69ec43b554.jpg)

**Comment by InpsydeNiklas** [comment]
Hi @tutouchengxuyuan 
This filter either must be placed in the `functions.php` file of your active theme, ideally a child theme. If you don't have a child theme and insert it into your main theme, then any theme update would overwrite the change. 
Alternatively, it could also be added with a plugin, [e.g. as a code snippet](https://wordpress.org/plugins/code-snippets/).

But if you need more detailed instructions, [ please reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
