### ISSUE TITLE
Paypal paypment

### ISSUE THREAD

**Issue by Niko0187** [woocommerce/woocommerce-paypal-payments#1268]
### Describe the Bug

 Paypal payment not works

### To Reproduce

![image](https://user-images.githubusercontent.com/128357549/226276192-992aa170-973a-4ae7-af65-29785dd14248.png)

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version --- LAST VERSION
 - WooCommerce Version  LAST VERSION
 - Plugin Version   
 - Browser [e.g. Chrome, Safari] and Version  ALL  Browser 
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Niko0187 

Could you please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly? An error like this could occur for various reasons, and we would need some more details about your site to better judge it.
Thanks!
