### ISSUE TITLE
PAYPAL WOOCOMMERCE

### ISSUE THREAD

**Issue by GREG074** [woocommerce/woocommerce-paypal-payments#1270]
### Describe the Bug

I've a got a shop with woocommerce and people could not pay with paypal, it always search and turn around on the cart. 

### To Reproduce

1. Go to the page order https://wfwesternshop.fr/commander/
2. Click on '…' choose paypal
3. Scroll down to the end of the page

### Screenshots
<img width="1141" alt="Capture d’écran 2023-03-20 à 12 51 14" src="https://user-images.githubusercontent.com/128379350/226331500-5782e22c-2745-4b5d-b1ab-db07093351d0.png">

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @GREG074 

Behavior like this could occur for various reasons.
But the buttons appear to be loading as expected for me:
![image](https://user-images.githubusercontent.com/70433191/227589464-60b02c02-747f-4c19-87e9-337f0b63ed92.png)

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you still need more assistance. Thanks!
