### ISSUE TITLE
Placement bug

### ISSUE THREAD

**Issue by Aftab3321** [woocommerce/woocommerce-paypal-payments#1271]
### Describe the Bug

This is placing the pay with paypal button below my header of the page which is not a correct position of it it should be placed above add to card as my other payment methods are showing up

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![image](https://user-images.githubusercontent.com/122532834/226553142-ac89c2f4-6333-48fc-b111-f602033673b9.png)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Aftab3321 
This behavior usually occurs when using the Divi Theme Builder. I suggest either taking a look at [the documentation here](https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-smart-buttons-not-loading) or giving it a try with [this plugin version](https://drive.google.com/uc?export=download&id=1Xty5ZMg-sK40AZDBmyWHt5xkZH3JpiDz) to see if the behavior persists. If you try the plugin version, please let us know how this works for you.

But if you need more assistance, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
