### ISSUE TITLE
remove PayPal payment pop-up, it is possible ?

### ISSUE THREAD

**Issue by Dje78250** [woocommerce/woocommerce-paypal-payments#1272]
Hello, we are having a problem implementing our site on ios and Android with the wpmobile plugin, the payment pop-up may be the cause, is it possible to remove this pop-up option? THANKS

**Comment by InpsydeNiklas** [comment]
Hi @Dje78250 
PayPal Payments implements the PayPal smart buttons which trigger the payment flow via the popup window.
We haven't performed any tests with the wpmobile plugin and this is not something we support at this time.
But if you need a simpler PayPal integration that only forwards the buyer to the PayPal website in the same window/tab, I suggest giving it a try with [PayPal Standard](https://developer.woocommerce.com/2021/07/12/developer-advisory-paypal-standard-will-be-hidden-on-new-installs/).
Please be aware though that the PayPal Standard integration is no longer supported.

If you require more assistance regarding PayPal Payments, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
