### ISSUE TITLE
Cannot delete Webhooks of cloned, but already deleted, instances

### ISSUE THREAD

**Issue by zubasoft** [woocommerce/woocommerce-paypal-payments#1278]
### Describe the Bug

Too many Webhooks are automatically created, when the site is cloned (e.g. with WordPress Toolkit). A manual resubscribe does not help to get rid of the deleted, cloned instances. Webhook simulation fails in this case.

### To Reproduce

Clone the site inside the webroot (as WordPress Toolkit do) and use it and a new Webhook is created somehow.

### Screenshots

Only the last entry is the correct one:
![image](https://user-images.githubusercontent.com/49788594/227559077-a24bf9fb-6d84-44af-b42b-4edde07de37e.png)

### Expected Behavior

It should be checked if the webhooks are still available with "Resubscribe" and all other should be deleted. Maybe you can also add an automatic check inside the WordPress cron that checks periodically if the webhooks are still available and delete them if not.

### Actual Behavior

Webhook simulation fails. I think it tries the wrong URLs (they aren't there anymore).

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version 7.5.1
 - Plugin Version 2.0.3
 - Browser Does not matter
 - A lot other plugins are installed, but I don't think they are the reason for this problem. If necessary I will share them.

**Comment by InpsydeNiklas** [comment]
Hi @zubasoft, the additional subscriptions not being cleared upon resubscribing should be resolved with the next update, for which a pre-release version is available here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.4-rc1
Alternatively, disconnecting and reconnecting the PayPal account will create a new REST app with dedicated webhooks.
Please keep in mind that the webhook subscription is stored in the REST app, and as long as you are using the same REST app across multiple site instances, your webhooks may not work as expected.

In any case, please let us know how it works for you with the pre-release version.  Thanks!

**Comment by zubasoft** [comment]
Thank you for the quick reply. That worked for me!
