### ISSUE TITLE
hello, suddenly the PayPal "Pay in 3 Installments" buttons do not show up in my site.  What could it be?  Thanks

### ISSUE THREAD

**Issue by giuscavo** [woocommerce/woocommerce-paypal-payments#1279]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @giuscavo 
This button could potentially not show up for various reasons despite being enabled. To rule out an account-related issue, it is often useful to first connect a [PayPal Sandbox account](https://woocommerce.com/document/woocommerce-paypal-payments/#testing-in-sandbox) to see if the behavior persists. Beyond this, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by giuscavo** [comment]
thank you
