### ISSUE TITLE
FATAL ERROR: Service not found for key "session.handler"

### ISSUE THREAD

**Issue by tex0gen** [woocommerce/woocommerce-paypal-payments#128]
### Describe the bug

Upon activation of the plugin, the site error 500s with the following error:
`Fatal error: Uncaught Dhii\Container\Exception\NotFoundException: Service not found for key "session.handler" in /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/DelegatingContainer.php:46 Stack trace: #0 /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/extensions.php(64): Dhii\Container\DelegatingContainer->get() #1 /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/DelegatingContainer.php(142): WooCommerce\PayPalCommerce\WcGateway\WcGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}() #2 /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/DelegatingContainer.php(74): Dhii\Container\DelegatingContainer->_invokeExtension() #3 /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/services.php(49): Dhii\Container\DelegatingContainer->get() #4 /home/bownetcms/public_html/ in /home/bownetcms/public_html/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/CachingContainer.php on line 52
`
### To reproduce

1. Install plugin
2. Activate

**Environment (please complete the following information):**
 - WordPress Version: **5.6.2**
 - WooCommerce Version: **5.0.0**
 - WooCommerce PayPal Payments Plugin Version: **1.1.0**
 - Browser [e.g. chrome, safari] and Version **ALL**
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>
`
### WordPress Environment ###

WordPress address (URL): https://bownetcms.co.uk
Site address (URL): https://bownetcms.co.uk
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.1
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.3
PHP Post Max Size: 30 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 8.0.23-0ubuntu0.20.04.1
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 220.85MB
Database Data Size: 174.08MB
Database Index Size: 46.77MB
wp_woocommerce_sessions: Data: 25.04MB + Index: 0.38MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_ajaxsearchpro: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_ajaxsearchpro_priorities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ajaxsearchpro_statistics: Data: 0.45MB + Index: 0.13MB + Engine MyISAM
wp_asp_index: Data: 12.34MB + Index: 9.35MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 1.20MB + Engine InnoDB
wp_cp_feeds: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_layerslider: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.44MB + Index: 0.42MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Engine MyISAM
wp_pmxe_posts: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_pmxe_templates: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_posts: Data: 0.10MB + Index: 0.03MB + Engine MyISAM
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_popover_ip_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 22.56MB + Index: 21.06MB + Engine InnoDB
wp_posts: Data: 13.52MB + Index: 2.48MB + Engine InnoDB
wp_prli_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_prli_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_prli_link_metas: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_prli_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_relationships: Data: 0.31MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.25MB + Index: 0.63MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 69.59MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.38MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_extra_flat_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpb2d_processed_dbtables: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_access_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_consents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_delete_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgdprc_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_msgs: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 1.36MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.07MB + Engine MyISAM

### Post Type Counts ###

attachment: 2445
avia_framework_post: 7
customize_changeset: 2
inc_popup: 1
nav_menu_item: 152
oembed_cache: 5
page: 28
popup_theme: 6
post: 3
product: 1039
product_variation: 1688
revision: 1338
shop_coupon: 24
shop_order: 1910
shop_order_refund: 17

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (24) ###

ManageWP - Worker: by GoDaddy – 4.9.8
WooCommerce Subcategories widget: by Pavel Burov (Dark Delphin) – 1.4.1
Ajax Search Pro: by Ernest Marcinko – 4.11.4
Classic Editor: by WordPress Contributors – 1.6
Custom Permalinks: by Sami Ahmed Siddiqui – 1.7.1
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Duplicate Page: by mndpsingh287 – 4.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.6
WooCommerce Product Filter: by Mihajlovic Nenad – 6.4.1
Pretty Links: by Pretty Links – 3.2.1
Social Icon Widget: by Mostafiz Shamim – 1.0.2
WP woocommerce featured product by category: by WP Online Support – 1.1
WooCommerce Table Rate Shipping by Mangohour: by mangohour – 1.2.1
Trustpilot-reviews: by Trustpilot – 2.5.808
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.0.2

WooCommerce Admin: by WooCommerce – 2.0.1
WooCommerce Cart Based Shipping: by Bolder Elements – 3.1
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3
Woocommerce Dropdown Cart: by Phuc Pham – 2.1.1
WooCommerce: by Automattic – 5.0.0
Wordfence Security: by Wordfence – 7.4.14
Yoast SEO: by Team Yoast – 15.9
WP GDPR Compliance: by Van Ons – 1.5.6
WP Sync DB: by Sean Lang – 1.5

### Inactive Plugins (25) ###

3CX Live Chat: by 3CX – 9.3.0
Analytify - Google Analytics Dashboard: by Analytify – 3.1.6
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.3.6.1
Excel-Like Product Manager for WooCommerce and WP E-commerce: by Holest Engineering – 2.1.18
GDPR Cookie Consent: by WebToffee – 2.0.0
PayPal for WooCommerce: by Angell EYE – 1.4.16
Product CSV Import Export (BASIC): by WebToffee – 1.8.9
Product Sales Report for WooCommerce: by Aspen Grove Studios – 1.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.4
Simple Image Sizes: by Rahe – 3.2.1
SiteGround Migrator: by SiteGround – 1.0.26
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.21.24

W3 Total Cache: by BoldGrid – 2.1.1
WooCommerce - Store Exporter: by Visser Labs – 2.7
WooCommerce Helper: by WooCommerce – 1.7.1 – Network enabled
WooCommerce PayPal Payments: by WooCommerce – 1.1.0
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.17
WooCommerce Product CSV Import Suite: by Mike Jolley / WooThemes – 1.9.15
WooCommerce Product Feed for Google, Awin, Shareasale, Bing and More: by ExportFeed.com – 3.3.0.1
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP All Export Pro: by Soflyy – 1.5.2
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.9
WP All Import Pro: by Soflyy – 4.5.1
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WP Live Chat Support Pro: by WP Live Chat – 7.0.06

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by ManageWP –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #10 - /products/
Basket: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: #2417 - /terms-and-conditions/

### Theme ###

Name: Enfold Child
Version: (update to version 0 is available)
Author URL: 
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.1.2
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: enfold-child/woocommerce/emails/customer-completed-order.php version 2.5.0 is out of date. The core version is 3.7.0
enfold-child/woocommerce/emails/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.7.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 339
Oldest: 2021-01-24 12:43:07 +0000
Newest: 2021-02-24 00:07:55 +0000

`

</details>

**Comment by Dinamiko** [comment]
Hello @tex0gen,

Sorry for the delay in the response, does this problem still persist? if so please let us know here, thanks.

**Comment by tex0gen** [comment]
@Dinamiko Nope, issue is confirmed fixed this end. Thank you!
