### ISSUE TITLE
PayPal Buttons not showing in the Orders Page

### ISSUE THREAD

**Issue by imwebvizion** [woocommerce/woocommerce-paypal-payments#1280]
### Describe the Bug

We are using a partial payment plugin which allows customers to pay deposits. There is no issue on the checkout page and customers are able to pay using PayPal.

However, when they go back to their order and try to pay after clicking the PayPal radio button, the main PayPal button does not appear. Please see my screenshot.
![image](https://user-images.githubusercontent.com/128875776/227682640-41dfefe1-a456-404d-81e8-22450740be7b.png)

Same issue when I use the Standard card button.
![image](https://user-images.githubusercontent.com/128875776/227682681-d6e67984-f0f3-47eb-9109-489556c16263.png)

I think it has something to do with the Smart Button Locations since there's no option to display the buttons on the Order's page.
![image](https://user-images.githubusercontent.com/128875776/227682735-becef512-3c56-488d-b6e4-4d555afda578.png)

Hope you can help. Thank you!

**Comment by InpsydeNiklas** [comment]
Hi @imwebvizion 
The `Checkout` location covers the regular checkout and the `pay for order` endpoint. So enabling it there is good enough.
Can you please check if this behavior also persists for you when you manually create a WooCommerce order?
If so, I suggest enabling the Storefront theme and disabling all other plugins to see if the behavior persists, as this is appears to be a theme or plugin conflict.

Beyond this, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by imwebvizion** [comment]
Tyche SoftwaresHello Niklas,

You're right!

It's the Payment Gateway Based Fees and Discounts for WooCommerce by Tyche
Softwares that's causing the issue. Thanks!


--

Best Regards,


Cj Sarreal

Co-Founder, Webvizion


***@***.***  |  +63 999 224 2117

https://thewebvizion.com/ |  Metro Manila, Philippines
