### ISSUE TITLE
WooCommerce PayPal Payments and Defender Recaptcha Compatibility Issue. (1570)

### ISSUE THREAD

**Issue by devsatwik** [woocommerce/woocommerce-paypal-payments#1282]
### Describe the Bug

I have identified a compatibility issue between the WooCommerce PayPal Payments plugin and the Defender plugin. Specifically, when the Recaptcha feature on the Defender plugin is enabled and customers attempt to pay using PayPal, the Recaptcha fails.

After further investigation, I have discovered that the WooCommerce PayPal Payments plugin is sending the same captcha to Google for verification twice, which violates security measures that require each captcha to be used only once. Consequently, Defender users who have Recaptcha on Checkout enabled are unable to process orders correctly due to this issue.

I hope this information provides clarity on the problem and helps in resolving the compatibility issue.

### To Reproduce

1. Install Defender Plugin
2. Goto WP-admin > Defender> Tools > Google Recapcha
3. Setup Recaptcha v2/v3 with the API keys
4. Enable Recaptcha on checkout as shown here https://monosnap.com/direct/4NAIYcQy2enRdSElAbWGQTxQqQv9Ph 
5. Save the settings > Try paying through Paypal on the checkout

### Expected Behavior

The Recaptcha should not fail at checkout and the payment should proceed

### Actual Behavior

The Recaptcha fails on checkout when the user tries to pay 

### Environment

WordPress 6.1.1
Defender Pro Version: 3.9.0
WooCommerce PayPal Payments 2.0.2
Chrome Browser
Woocommerce 7.5.1

**Comment by InpsydeNiklas** [comment]
Thanks for the issue report, but we can only suggest a potential workaround by [disabling the early wc validation and enabling the basic validation](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#checkout-form-field-validation-before-creating-the-paypal-order) instead. 
The Defender plugin must address this behavior's core cause, as the same issue occurs without PayPal Payments when the form validation fails on the first attempt:
https://user-images.githubusercontent.com/70433191/236323596-782a75ac-218b-4d43-b8f7-c1fe49079955.mp4

Other plugins, such as the [reCaptcha for WooCommerce](https://woocommerce.com/products/recaptcha-for-woocommerce/) plugin, solve this problem by saving a transient for several minutes after a successful check. So I suggest contacting the Defender plugin developers or testing it with alternative reCaptcha solutions.
