### ISSUE TITLE
PayPal Window 

### ISSUE THREAD

**Issue by wazhoare** [woocommerce/woocommerce-paypal-payments#1289]
### Describe the Bug
Click on Paypal button and payment window/modal/popup appears and disappears in a blink of an eye. Followed by the following message:Something went wrong. Please try again or select another payment method. Both Apple Pay and credit card work fine

### To Reproduce
Place item, go to account checkout page and, complete name and address fields, selct agree to terms and click "PaPal" btn 

1. Go to 'checkout'
2. Click on 'paypal'
3. Scroll down to …'
Something went wrong. Please try again or select another payment method

### Screenshots

https://user-images.githubusercontent.com/129443357/228955559-0fdd5a29-dcce-49b4-9331-885e6e9bc1bb.mov

### Expected Behavior

Payment 
### Actual Behavior

Crashing 
### Environment

 Current version: 6.2 - WordPress Version
 Version 7.5.1 - WooCommerce Version
Version 2.0.3 - Plugin Version
 All up to date and happens in both - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

`
### WordPress Environment ###

WordPress address (URL): https://tankslapped.com
Site address (URL): https://tankslapped.com
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.28
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 8.0.1
OpenSSL/1.1.1t

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wpug_
Total Database Size: 79.11MB
Database Data Size: 69.03MB
Database Index Size: 10.08MB
wpug_woocommerce_sessions: Data: 3.68MB + Index: 0.15MB + Engine MyISAM
wpug_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpug_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.08MB + Engine MyISAM
wpug_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_actionscheduler_actions: Data: 0.88MB + Index: 0.36MB + Engine MyISAM
wpug_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_actionscheduler_logs: Data: 0.59MB + Index: 0.46MB + Engine MyISAM
wpug_adtribes_my_conversions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_ac_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_connection_reports: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_no_cookie_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_sfw: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_sfw_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_spamscan_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_cleantalk_ua_bl: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_comments: Data: 0.14MB + Index: 0.06MB + Engine MyISAM
wpug_e_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_bans: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpug_itsec_dashboard_events: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wpug_itsec_distributed_storage: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_lockouts: Data: 0.15MB + Index: 0.04MB + Engine MyISAM
wpug_itsec_logs: Data: 44.79MB + Index: 3.38MB + Engine MyISAM
wpug_itsec_mutexes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_opaque_tokens: Data: 0.21MB + Index: 0.25MB + Engine MyISAM
wpug_itsec_temp: Data: 0.26MB + Index: 0.22MB + Engine MyISAM
wpug_itsec_user_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_webauthn_credentials: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_itsec_webauthn_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_options: Data: 8.43MB + Index: 0.36MB + Engine MyISAM
wpug_postmeta: Data: 6.99MB + Index: 3.63MB + Engine MyISAM
wpug_posts: Data: 1.22MB + Index: 0.11MB + Engine MyISAM
wpug_rank_math_404_logs: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_rank_math_analytics_gsc: Data: 0.46MB + Index: 0.34MB + Engine MyISAM
wpug_rank_math_analytics_inspections: Data: 0.25MB + Index: 0.03MB + Engine MyISAM
wpug_rank_math_analytics_keyword_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpug_rank_math_internal_links: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wpug_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_css: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wpug_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_slides: Data: 0.13MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_static_slides: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpug_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_termmeta: Data: 0.08MB + Index: 0.07MB + Engine MyISAM
wpug_terms: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpug_term_relationships: Data: 0.04MB + Index: 0.07MB + Engine MyISAM
wpug_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpug_usermeta: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
wpug_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wpug_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpug_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_customer_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpug_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_order_product_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpug_wc_order_stats: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wpug_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_product_attributes_lookup: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wpug_wc_product_download_directories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wpug_wc_rate_limits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpug_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpug_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpug_wpr_rocket_cache: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wpug_wpr_rucss_used_css: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 360
custom_css: 1
elementor_library: 12
itsec-dash-card: 9
itsec-dashboard: 1
mc4wp-form: 1
nav_menu_item: 20
page: 23
post: 4
product: 101
product_variation: 472
rey-global-sections: 7
shop_coupon: 6
shop_order: 107
shop_order_refund: 10
size-chart: 10
wpcf7_contact_form: 4
wpcode: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Classic Editor: by WordPress Contributors – 1.6.3
Anti-Spam by CleanTalk: by СleanTalk  – 6.7
Contact Form 7: by Takayuki Miyoshi – 5.7.5.1
Elementor: by Elementor.com – 3.12.0
Enable Media Replace: by ShortPixel – 4.1.0
Facebook for WooCommerce: by Facebook – 3.0.16
Site Kit by Google: by Google – 1.96.0
WPCode Lite: by WPCode – 2.0.9
iThemes Security Pro: by iThemes – 7.3.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.10
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.2
One Click Demo Import: by OCDI – 3.1.2
Slider Revolution Before/After Add-On: by ThemePunch – 3.1.0
Slider Revolution: by ThemePunch – 6.6.12
Rey Core: by ReyTheme – 2.5.2
Rey Module - Preloaders Pack: by ReyTheme – 1.1.1
Rank Math SEO PRO: by Rank Math – 3.0.32.1
Rank Math SEO: by Rank Math – 1.0.110.2
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.5.0
Product Size Charts Plugin for WooCommerce: by theDotstore – 2.4.2
Product Feed ELITE for WooCommerce: by AdTribes.io – 3.6.8
WooCommerce Payments: by Automattic – 5.6.2
WooCommerce PayPal Payments: by WooCommerce – 2.0.3
WooCommerce Shipment Tracking: by WooCommerce – 1.8.0
WooCommerce: by Automattic – 7.5.1
WP Mail SMTP: by WPForms – 3.7.0
WP Rocket: by WP Media – 3.12.6.1

### Inactive Plugins (2) ###

bunny.net: by bunny.net – 1.0.8
Product Feed PRO for WooCommerce: by AdTribes.io – 12.4.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #44 - /shop/
Basket: #45 - /cart/
Checkout: #46 - /checkout/
My account: #47 - /my-account/
Terms and conditions: #177 - /terms-conditions/

### Theme ###

Name: Rey Child
Version: 1.0.0
Author URL: https://twitter.com/mariushoria
Child Theme: ✔
Parent Theme Name: Rey
Parent Theme Version: 2.5.2
Parent Theme Author URL: https://twitter.com/mariushoria
WooCommerce Support: ✔

### Templates ###

Overrides: /home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/cart/mini-cart.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/loop-orderby.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/loop-pagination-load-more.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/loop-price.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/loop-result-count.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-simple-add-to-cart-button.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-variation-add-to-cart-button.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-variation-data.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-meta.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-product-image.php
/home/whandcoc/public_html/wp-content/plugins/rey-core/template-parts/woocommerce/single-blocks.php

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://tankslapped.com
Subscriptions-core Library Version: 5.5.0
Subscription Statuses: –
WooCommerce Account Connected: ❌ No

### Store Setup ###

Country / State: United Kingdom (UK)

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
gateway_scheduled_payments

PayPal: refunds

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-31 10:45:27 +00:00
Options: ✔
Notes: 106
Onboarding: completed

### WooCommerce Payments ###

Version: 5.6.2
Connected to WPCOM: Yes
Blog ID: 205510937
Account ID: acct_1KpvYb2HC1sXC7sW

### Action Scheduler ###

Complete: 3,175
Oldest: 2023-02-27 21:20:15 +0000
Newest: 2023-03-30 20:45:18 +0000

Failed: 14
Oldest: 2022-09-16 09:12:39 +0000
Newest: 2023-03-30 19:23:19 +0000

Pending: 4
Oldest: 2023-03-30 21:27:07 +0000
Newest: 2023-04-04 03:05:08 +0000

### Status report information ###

Generated at: 2023-03-30 20:56:09 +00:00
`

**Comment by Sirvijver** [comment]
Hello @wazhoare 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I did take a look at your site (https://tankslapped.com/) and saw an issue when I tried the express checkout option on the product page. I would expect the error you saw in the checkout is related to the same error:
`Expected currency from order api call to be GBP, got EUR. Please ensure you are passing currency=EUR to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/`

I would expect that you have a currency switcher active on your site, and this problem is most likely caused by PayPal receiving a different currency than it is expecting. Please do some tests with this plugin (or other plugins) deactivated and see if you can still recreate the problem (you can see the error in the web browser console > f12).

If you require our continued support, please open a support via the link provide above.

Kind regards, 
Joost
