### ISSUE TITLE
PayPal button doesn't fit the whole "Width" on Ipad Pro 12.9 Portrait mode in the checkout

### ISSUE THREAD

**Issue by Bebuk85** [woocommerce/woocommerce-paypal-payments#1291]
The checkout on Ipad Pro 12.9 in portrait looks a little bit odd, the variables are all together and not in list and the PayPal button doesn't fit the whole "width" (I tried with a real iPad on Safari and Chrome Canary on PC with Devtools and same issue)

Please find the detailed description here: https://www.loom.com/share/b62c797a89ae4d77a09f0725cf34d634

Product test: https://fvpwpc0mh1.onrocket.site/charter/60ft-reel-machine/ ---- Checkout: https://fvpwpc0mh1.onrocket.site/checkout/

![CHECKOUT ON VERTICAL IPAD PRO 12 9](https://user-images.githubusercontent.com/72046610/229270698-9a197915-21af-4691-9037-84958a293bfc.jpeg)

**Comment by Sirvijver** [comment]
Hello @Bebuk85 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

For this request, I can guide you to this gist that could possibly help you correct the size of the PayPal button:
https://gist.github.com/Sirvijver/15b34321375994a37bfb346a7c1418e2

Any other adjustment should probably be made via standard CSS actions or via the WooCommerce Visual Hook guide: https://www.businessbloomer.com/woocommerce-visual-hook-guide-checkout-page/

I will mark this thread as resolved. Please reach out to our support team as described above if you need additional support.

Kind regards, 
Joost

**Comment by Bebuk85** [comment]
Support Resquest?

It's a general trouble not only me, it should be 100% width by default.

**Comment by InpsydeNiklas** [comment]
The div containing the buttons scales dynamically with the page width:
![image](https://user-images.githubusercontent.com/70433191/229863022-f260f5dc-6bb6-4e51-b24b-522db99c331c.png)
The smart buttons also render dynamically according to the size of the div, but the buttons are only available in widths between 200px and 750px. Your site layout changes below 1024 pixels, so there is a certain region where the buttons would be aligned on the left.

While it is not possible to make the buttons wider, you could e.g. center them with CSS like this:
```
#ppc-button-ppcp-gateway {
	display: flex;
	justify-content: center;
}
```

In any case, there is not much the plugin could do in this regard, as it doesn't actively set the button size.
If any questions remain, I suggest getting in touch with the support from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
