### ISSUE TITLE
Coupon'Allowed Email' Validation doesn't Ajax update after error notice (1572)

### ISSUE THREAD

**Issue by brendanofarrell** [woocommerce/woocommerce-paypal-payments#1292]
Looks like a bug in the custom checkout validation the plugin performs. The coupon is still displayed after the error.

Sorry, it seems the coupon "xyz" is not yours - it has now been removed from your order.

The coupon is indeed removed from the backend, but the checkout page isn’t updated accordingly. If you reload the page or trigger an AJAX reload by changing a billing field, you’ll notice that the coupon is no longer applied.

This is confusing for customers, as the discounted amount is still be displayed in the PayPal popup window when they click the PayPal button a second time without reloading the page.

To recreate
- set up a coupon, with email allowed
- as guest user - navigate to checkout - use different email, than allowed
- attempt PayPal checkout
- 'coupon 'xyz' is not yours' error will show
- checkout doesn't update with AJAX; coupon remains
- proceed through PayPal checkout shows as if the coupon has not been removed
- customer gets charged full price

**Comment by InpsydeNiklas** [comment]
Hi @brendanofarrell
Thanks for reporting the issue!
Please try [this test version](https://drive.google.com/uc?export=download&id=1__PKkHE3Br8Mm1BRUqJZQugvkuCOyNB_) and let us know if it resolves the issue for you. Your feedback is much appreciated.
If all goes as expected, this will be included in the next update later this month.
Thanks!

**Comment by brendanofarrell** [comment]
Hi Niklas,

That’s brilliant! And works perfectly.

Very appreciated.

Brendan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
