### ISSUE TITLE
Plugin paypal payments does not work

### ISSUE THREAD

**Issue by Biggossa** [woocommerce/woocommerce-paypal-payments#1297]
### Describe the Bug

After installing the plugin when I go to the "connect your account" link, there is a quick refresh but the page does not change

### To Reproduce

1. go to woocommerce settings
2. go to payments
3. click on paypal
4. click on "connect your account"
5. the page make a quick refresh (seems he's traying to charge something that for a millisecond appears but after nothing happens and the page come back exactly the same. no possibility to put  nothing

### Screenshots
no way to create a screenshot of a so fast refresh...

### Environment

 - WordPress Version Welcome to WordPress 6.2
 - WooCommerce Version Version 7.5.1
 - Plugin Version Version 2.0.4
 - Browser [e.g. Chrome, Safari] and Version  chrome Versione 112.0.5615.49 (Build ufficiale)
 - Any other plugins installed - Elementor and Paypal standard (from the beginning... )

### Additional Details

How to remove the old paypal option?

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Biggossa 
If the integrated onboarding wizard fails for some reason (e.g. closing the popup window too quickly), you could still try to manually connect your credentials as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input

But please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report to get more help with the setup. Thanks!

**Comment by Biggossa** [comment]
I’ll try, but the problem is the conflict between the old PayPal button integrated in woo commerce and the new one. I had to uninstall the new one otherwise he didn’t worked at all.

Thanks for your time.

Paolo Vallerga
