### ISSUE TITLE
Could not retrieve order. OrderEndpoint.php:543 Order status changed from Pending payment to Failed.

### ISSUE THREAD

**Issue by myrandomtips** [woocommerce/woocommerce-paypal-payments#1298]
### Describe the Bug

Customer order failed

Could not retrieve order. OrderEndpoint.php:543 Order status changed from Pending payment to Failed.

**Comment by InpsydeNiklas** [comment]
Hi @myrandomtips 
This error can have various causes as described here: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors#could-not-retrieve-order

I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance as the team is happy to look into this for you. Thanks!
