### ISSUE TITLE
Subscription payment failed. The payment method was not saved at PayPal. 

### ISSUE THREAD

**Issue by Sayaka29** [woocommerce/woocommerce-paypal-payments#1299]
@niklasinpsyde 
### I have a problem with WooCommerce PayPal Payments. Version 2.0.4

WordPress Version 6.2
I have a subscription plugin: Subscriptions for WooCommerce. Version 3.2.7 
Whenever a customer tries to purchase a subscription product, the status goes from processing, pending, on hold and then failed and the subscription is canceled. 

The message in the order tab reads like this:
Subscription payment failed. The payment method was not saved at PayPal. Order status changed from On hold to Failed.

Can any suggest a solution to this problem?

**Comment by InpsydeNiklas** [comment]
Hi @Sayaka29 

To use Vaulting, your PayPal merchant account must be enabled for Reference Transactions. See more details here:
https://woocommerce.com/document/woocommerce-paypal-payments/#subscriptions-faq
Unfortunately, this requirement currently is not mentioned directly in the plugin, but the next update will improve the Vaulting setting to make this more clear.

Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance on how to set up PayPal Payments for subscriptions. Thanks!
