### ISSUE TITLE
Settings page is a bit cluttered

### ISSUE THREAD

**Issue by websupporter** [woocommerce/woocommerce-paypal-payments#13]
Extracted from #4.

Right now, if I want to disable buttons on the mini-cart, for example, it is a bit of a pain sifting through all of the different buttons and messaging sections to find what I am looking for. It might be better to have all button settings together, all messaging settings together, or even separate these into different tabs to reduce the number of settings on a single page.

**Comment by InpsydeNiklas** [comment]
Settings page has been improved and split up in different tabs, among others in #801, #961, & #1065.
