### ISSUE TITLE
Hola, he actualizado plugin WooCommerce PayPal  y todos los datos pero me sigue saliendo que mi tienda no está actualizada. Me podéis ayudar, por favor?

### ISSUE THREAD

**Issue by Svitbytka** [woocommerce/woocommerce-paypal-payments#1301]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Svitbytka 
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need help with setting up the PayPal Payments plugin. The team is happy to help from the provided link, as GitHub is only used for issue tracking.
Thanks!
