### ISSUE TITLE
Unable to translate "Save your Credit Card" in checkout page

### ISSUE THREAD

**Issue by nicksimoneau** [woocommerce/woocommerce-paypal-payments#1302]
### Describe the Bug

I'm unable to find where I can translate the string .

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Buzut** [comment]
This string is supposed to be translated by the plugin's language pack. So unless the plugin is available in the website's language, it is currently not translated.

This should be translatable by the user in my opinion and registered to be compatible with WPML string translation. WPML string translation icl_register_string or similar function allows the administrator to define translations for various languages.

**Comment by InpsydeNiklas** [comment]
@nicksimoneau This string can be translated with the [WordPress translation files](https://translate.wordpress.org/projects/wp-plugins/woocommerce-paypal-payments/stable/en-gb/default/?filters%5Bterm%5D=Save+your+Credit+Card&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). The [official plugin translations](https://translate.wordpress.org/projects/wp-plugins/woocommerce-paypal-payments/) are mostly not quite complete yet, but the team is working on improved translation coverage.
This string is translated correctly for me in any case, e.g. when using German or Spanish languages.

If you encounter any problems with the plugin setup, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

@Buzut For now, PayPal Payments does not have any dedicated compatibility with multilingual plugins but I'm also not aware of too many issue reports in this regard.

**Comment by nicksimoneau** [comment]
OH I just get why I didn't have the translation since my WordPress language is set to (French Canadian) instead of (French France) and the French Canadian translation didn't exist in the plugin !

**Comment by Buzut** [comment]
Hi @InpsydeNiklas 
So there are two different ways things can be done:
- either everything is translated into translation files and (when available) the i18n plugins handle that completely transparently using the appropriate .MO file
- strings are saved in the database (like the Payment method title that the user can edit in the back office [Woocommerce > Settings > Payment > Advanced Card Processing], as shown in this screenshot https://snipboard.io/7JcRYF.jpg) and then unless you use a function to make this translatable, it won't work with i18n plugins. 

The de facto standard function for that is [`icl_register_string`](https://polylang.pro/doc/wpml-api/) as all plugins support WPLM's API.

Maybe I should open a ticket specifically for the Payment method title then?
