### ISSUE TITLE
Use WooCommerce payment method tokens api (591)

### ISSUE THREAD

**Issue by Buzut** [woocommerce/woocommerce-paypal-payments#1303]
WC has a « saved card » feature that allows user to add new cards, see their cards (or payment means), set a default one and delete them in their user account.

PayPal currently doesn’t support it and shows the saved cards on checkout only without the possibility to remove them.

Screenshots

https://snipboard.io/KLG0lp.jpg
https://snipboard.io/4Y2Vhs.jpg
https://snipboard.io/uFvy1Z.jpg

**Comment by InpsydeNiklas** [comment]
Hi @Buzut 
Payment methods that were saved in the Vault can be viewed and deleted on the shop website in the `My Account  > PayPal payments` section while Vaulting is enabled.
This section may not appear on your custom my-account page layout but is accessible under this URL: `example.com/my-account/ppcp-paypal-payment-tokens/`
Changing your theme or disabling all other plugins should result in the menu point appearing.
For better compatibility, the team is already working on migrating to the WooCommerce native payment token API in #1059. This needs a bit more time but should be included in one of the next couples of updates.

That being said, if you encounter any problems with the plugin setup, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by Buzut** [comment]
Hi @InpsydeNiklas, 

Thank you for you answer. I now have it appearing, it's a bit puzzling as it's not under the same wording nor the same place as usual in the menu.
Will wait for the new implementation then. :)
