### ISSUE TITLE
Could not retrieve order. This browser may not be supported. Please try again with a different browser.

### ISSUE THREAD

**Issue by d3xy** [woocommerce/woocommerce-paypal-payments#1304]
### Describe the Bug

Following error is provided when user tries to checkout using paypal
"Could not retrieve order. This browser may not be supported. Please try again with a different browser."

### To Reproduce

1. Open cart
2. Attempt to checkout using paypal
3.  Be presented with error

### Screenshots
https://i.imgur.com/rvnrsqr.png

### Expected Behavior

Checkout using paypal or atleast open paypal's login page

### Actual Behavior

Presents error

### Environment

 - WordPress Version: 6.2
 - WooCommerce Version: 7.5.1
 - Browser [e.g. Chrome, Safari] and Version = Chrome latest and Edge latest aswell as Opera GX latest

<details><summary>System status</summary>

</details>

**Comment by Sirvijver** [comment]
Hi @d3xy 

This error can have various causes as described here: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors#could-not-retrieve-order

I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance, as the team is happy to look into this for you. Thanks!
