### ISSUE TITLE
Paypal sdk console error

### ISSUE THREAD

**Issue by CosmikCarrot** [woocommerce/woocommerce-paypal-payments#1305]
### Describe the Bug

Console error. See - https://www.screencast.com/t/shPMlEzkA1FV

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

See - https://www.screencast.com/t/shPMlEzkA1FV

### Environment

 - WordPress Version 6.2
 - WooCommerce Version 7.5.1
 - Plugin Version 2.0.4
 - Browser [e.g. Chrome, Safari] and Version - Chrome
 - Any other plugins installed - Yes 57.

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @CosmikCarrot 
Please check the source code of your page where the smart button is loaded and search for items with the id `paypal`. Remove any item with this id, e.g. an anchor or a div that displays a PayPal icon.
This error means there is already an item with the id `paypal` on your site which would prevent the PayPal SDK from initializing.

For more guidance, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by CosmikCarrot** [comment]
Thanks @InpsydeNiklas 

It appears to have magically disappeared, so I think that might have been a caching issue, even though it was on incognito.

Case closed.
