### ISSUE TITLE
external resources are loaded before customer chooses paypal

### ISSUE THREAD

**Issue by qyanu** [woocommerce/woocommerce-paypal-payments#1306]
### Describe the Bug

When the WooCommerce PayPal Payments plugin is used, external resources
are loaded from www.paypal.com/sdk/js endpoints from the checkout page
**before** the customer has made the clear selection of using the PayPal
payment option (as opposed to some other payment option).

There is an ongoing lawsuite in Austria that seems to me related to
the legality of the behaviour above.
Citing to the european union's GDPR law, the lawsuite seems to claim
that loading external resources is prohibited unless it is directly
related to a user's explicit choice.
As far as i understood it, both sides of the lawsuite seem to agree on
this claim but differ on whether actual damages need to be
proven or if the loading itself is sufficient to constitute an
infringement.
However, no court has rendered any judgements yet as far as i know.

And ... i am not a lawyer nor in any other way more proficient in legal
issues than the average joe.

### To Reproduce

1. Have Wordpress + WooCommerce + WooCommerce PayPal Payments;
2. Have two payment options, for example "Bank Transfer" and "PayPal"
   activated;
3. Put some item in the shopping cart;
4. Go to the checkout page;

Notice that some external resources (e.g. from www.paypal.com/sdk/js)
are loaded **before** the user has made any choice (click) regarding
the payment options.

### Expected Behavior

The external resources are only loaded after the user has somehow
clicked on the choice of paypal (default option would not count as
choice before some related click is made).

### Environment

 - WordPress Version ... 6.2
 - WooCommerce Version ... 7.5.1
 - Plugin Version ... 2.0.4
 - Browser and Version ... Firefox 102.9.0esr

**Comment by Sirvijver** [comment]
Hello @qyanu 

We are a payment plugin developer and are also not aware of the exact law requirements worldwide for the usage of our plugin. I think this matter probably need to be directed to [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) that can better answer such situation.

If you have technical questions concerning or running into issues with our plugin, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance, as the team is happy to look into this for you. Thanks!
