### ISSUE TITLE
PayPal Advanced Credit Card Processing Option Disappeared For No Reason. Please help! 

### ISSUE THREAD

**Issue by butthead101** [woocommerce/woocommerce-paypal-payments#1308]
Hello,

For some reason the Paypal advanced card processing plugin is no longer showing on the checkout page. I haven't changed any settings.

Please kindly advise asap as we are potentially losing business!

Please see below.
![Uploading SyrHkymqWh7xrdcd.png…]()

**Comment by InpsydeNiklas** [comment]
Hi @butthead101, The image did not attach. In any case, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
