### ISSUE TITLE
kwd currency not work 

### ISSUE THREAD

**Issue by arabfono** [woocommerce/woocommerce-paypal-payments#1310]
not work with currency KWD!

please fix it
please fix itplease fix itplease fix itplease fix itplease fix it
 
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
@arabfono PayPal does not support this currency. That's not something we can fix.
You must use a [PayPal-supported currency](https://developer.paypal.com/api/rest/reference/currency-codes/) to use the PayPal Payments plugin.
For more details on the best currency to use, I suggest getting in touch with the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/). Thanks!
