### ISSUE TITLE
como puedo corregir este error?:                          CURRENCY_NOT_SUPPORTED Currency code is not currently supported. Please refer https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for list of supported currency codes.

### ISSUE THREAD

**Issue by automatismosglobal** [woocommerce/woocommerce-paypal-payments#1311]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
@automatismosglobal PayPal does not support this currency. You must use a [PayPal-supported currency](https://developer.paypal.com/api/rest/reference/currency-codes/) to use the PayPal Payments plugin.
For more details, please see [the documentation here](https://woocommerce.com/document/woocommerce-paypal-payments/#faq-which-currencies-are-supported) or get [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
