### ISSUE TITLE
Not Showing Up On My Cart and Checkout Pages

### ISSUE THREAD

**Issue by petvideoverify** [woocommerce/woocommerce-paypal-payments#1312]
### Describe the Bug
Paypal and Venmo are not showing up on Product, My Cart, and Checkout pages when I access them through a Desktop.  They show up when accessing them through a smartphone

![image](https://user-images.githubusercontent.com/96212315/232349824-76165f12-3048-43e1-b265-59ab1336ca31.png)

![image](https://user-images.githubusercontent.com/96212315/232349843-71aeaab0-c756-482c-9a9c-28257028b694.png)

![image](https://user-images.githubusercontent.com/96212315/232349857-13935571-2fe2-4ee9-8159-73bcd2eeaed9.png)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @petvideoverify
PayPal Payments does not yet support the new Block Cart & Checkout pages. Experimental support for this will be added over the course of the next updates, but for now, it requires the regular WooCommerce shortcode Cart and Checkout pages: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-does-paypal-payments-support-blocks 
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
