### ISSUE TITLE
Calculation ignores customer tax exemption status

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-paypal-payments#1336]
### Describe the Bug

If `WC_Customer::set_is_vat_exempt(true)` has been called (e.g. by a plugin that checks a customer VAT number), then the plugin still adds tax. There's nothing in the code that checks the customer exemption status. This results in the WooCommerce checkout total being what is expected..... but when you get to PayPal, suddenly tax is back.

**Comment by InpsydeNiklas** [comment]
Hi @DavidAnderson684, can you provide a specific example? I can't reproduce this behavior. 
E.g. when setting tax exemption status for logged in users from UK, it works as expected:
```php
function my_custom_set_customer_vat_exempt( $cart ) {
    if ( is_admin() && ! defined( 'DOING_AJAX' ) ) {
        return;
    }
    if ( ! is_user_logged_in() ) {
        return;
    }
    $customer = WC()->customer;
    if ( $customer && 'GB' === $customer->get_billing_country() ) {
        $customer->set_is_vat_exempt( true );
    }
	else {
		$customer->set_is_vat_exempt( false );
	}
}
add_action( 'woocommerce_before_calculate_totals', 'my_custom_set_customer_vat_exempt', 10 );
```
No taxes are displayed in the PayPal popup when selecting UK, and they are displayed when using any other country.
In any case, the amount captured will be taken from the WC order. So even in cases where the order total in the PayPal popup window may not be accurate, the actual amount captured should be correct.

But please provide more details steps to reproduce the reported behavior. Thanks!

**Comment by DavidAnderson684** [comment]
I confess, I haven't myself set up a site.... I've just had three users of my VAT plugin who all report the same thing when using your payment gateway (and on no other payment gateway that they've tried).

If you want to replicate it more closely, then the hooks during which potentially the `set_is_vat_exempt()` call is made can be either `woocommerce_checkout_update_order_review` or `woocommerce_checkout_process`.

**Comment by InpsydeNiklas** [comment]
No matter which hook we used, the amount displayed in PayPal matched the amount displayed on the checkout page. But in any case, regardless of which amount is shown in the PayPal popup, the final capture amount will be taken from the WooCommerce order.
So, a buyer may see a higher value in the popup than what they are being charged, depending on when eventual discounts are applied. The hook `woocommerce_checkout_process` generally occurs too late to be considered within the PayPal popup window. 
If this issue report comes up again, I recommend referring affected users directly [to our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) so we can provide more guidance. Thanks!

**Comment by DavidAnderson684** [comment]
The cause of this was eventually tracked down. The real cause was related to the context in which the taxation country for line items was being calculated. The PayPal plugin sends an AJAX request on the checkout to the back-end, `?wc-ajax=ppc-create-order`, and the back-end sends an API request to PayPal to create an order. But during this AJAX request, no flags are set inside WooCommerce (e.g. `WOOCOMMERCE_CHECKOUT` or `is_checkout()`) to indicate a check-out context. As such, the VAT plugin, when asked for the VAT country, includes signals which aren't relevant on the checkout. (On the checkout, the only country that matters is the order's taxation country; other things like visitor IP address which matter on ordinary product pages when first seeing the page, shouldn't be consulted).

We've now fixed this in the VAT plugin by adding special detection for the PayPal plugin's AJAX request.
