### ISSUE TITLE
Paypal Payment widget failed to initialize due to an error

### ISSUE THREAD

**Issue by Wingkodeco** [woocommerce/woocommerce-paypal-payments#1341]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Wingkodeco 

This platform is intended mainly for development. For plugin support requests, we would advise you to [reach out to the support team](https://paypal.inpsyde.com/docs/request-support/) directly for more guidance. If you do, please add more details about the issue you are encountering and include the system report.

For now, I will mark this request as there is not enough information to respond to.

Kind regards, 
Joost
