### ISSUE TITLE
For old/existing reference transaction agreements: "ERROR Failed to create payment token. Already vaulted." => "This PayPal account is already saved on this site. Please check that you are logged in correctly."

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-paypal-payments#1342]
### Describe the Bug

Trying to buy a WooCommerce Subscription. Monthly payment at beginning of each month, so checkout total is zero.

### What happens

After purchasing I can log in to PayPal with my account. Then I get the following error:

> This PayPal account is already saved on this site. Please check that you are logged in correctly.

Looking at the logs I see:

```
2023-04-23T10:36:06+00:00 DEBUG POST https://api.paypal.com/v2/vault/approval-tokens/YYYYYY/confirm-payment-token
Response Debug ID: 3691f017f14dd
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-04-23T10:36:06+00:00 ERROR Failed to create payment token. Already vaulted.
2023-04-23T10:36:07+00:00 DEBUG GET https://api.paypal.com/v2/vault/payment-tokens/?customer_id=XXXXX
Response Debug ID: 3361619efd40b
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-04-23T10:36:09+00:00 DEBUG POST https://api.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"XXXXX"}
Response Debug ID: bef4ab438fbcd
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-04-23T10:36:10+00:00 DEBUG GET https://api.paypal.com/v2/vault/payment-tokens/?customer_id=XXXXX
Response Debug ID: 7e9ef76f2aa5d
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-04-23T10:36:38+00:00 DEBUG POST https://api.paypal.com/v1/notifications/verify-webhook-signature
Request Body: {"transmission_id":"JJJJJJJJJJJJ-e1c2-11ed-9206-ZZZZZ","transmission_time":"2023-04-23T10:36:10Z","cert_url":"https:\/\/api.paypal.com\/v1\/notifications\/certs\/CERT-360caa42-KKKKKKK-CCCCCCC","auth_algo":"SHA256withRSA","transmission_sig":"DDDDDDDDDD+55bf0a1hPEj+MCgcnrYTRwue00qpKeECh2bfjQ0hoDObBn7CVmZAnXGYS\/LLLLLLLLLLLLL\/ZvYfWlRzIMA+3\/FFFFFFFFFFF\/pbQnM0cJiHya36in5I2hiZwmWdUwJhlrpPT\/5yITp5Rg2vYeJ7KdcaSiTa+ROsXNEhxznUjQ3R36hWy3xmpRH1GStQ==","webhook_id":"EEEEEEEEEEE","webhook_event":{"id":"WH-50769749FT4948424-GGGGGGGGGGGGGG","event_version":"1.0","create_time":"2023-04-23T10:36:06.097Z","resource_type":"payment_token","resource_version":"2.0","event_type":"VAULT.PAYMENT-TOKEN.CREATED","summary":"A payment token has been created.","resource":{"time_created":"2023-04-23T03:36:06.097Z","links":[{"href":"https:\/\/api.paypal.com\/v2\/vault\/payment-tokens\/IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","rel":"self","method":"GET","encType":"application\/json"},{"href":"https:\/\/api.paypal.com\/v2\/vault\/payment-tokens\/IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","rel":"delete","method":"DELETE","encType":"application\/json"},{"href":"https:\/\/api.paypal.com\/v2\/vault\/approval-tokens\/YYYYYY","rel":"approval_token","method":"GET","encType":"application\/json"}],"source":{"paypal":{"payer":{"email_address":"AAAAAAAA@mail.org","payer_id":"HHHHHHHHHHHHHHHHHHH"}}},"id":"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","customer_id":"BBBB","status":"CREATED"},"links":[{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-50769749FT4948424-GGGGGGGGGGGGGG","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-50769749FT4948424-GGGGGGGGGGGGGG\/resend","rel":"resend","method":"POST"}]}}
Response Debug ID: e6a6cc0a50936
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-04-23T10:36:38+00:00 INFO Der Webhook wurde von VAULT.PAYMENT-TOKEN.CREATED behandelt.
2023-04-23T10:36:39+00:00 DEBUG POST https://api.paypal.com/v1/notifications/verify-webhook-signature
Request Body: {"transmission_id":"JJJJJJJJJJJJ-e1c2-11ed-9206-ZZZZZ","transmission_time":"2023-04-23T10:36:10Z","cert_url":"https:\/\/api.paypal.com\/v1\/notifications\/certs\/CERT-360caa42-KKKKKKK-CCCCCCC","auth_algo":"SHA256withRSA","transmission_sig":"DDDDDDDDDD+55bf0a1hPEj+MCgcnrYTRwue00qpKeECh2bfjQ0hoDObBn7CVmZAnXGYS\/LLLLLLLLLLLLL\/ZvYfWlRzIMA+3\/FFFFFFFFFFF\/pbQnM0cJiHya36in5I2hiZwmWdUwJhlrpPT\/5yITp5Rg2vYeJ7KdcaSiTa+ROsXNEhxznUjQ3R36hWy3xmpRH1GStQ==","webhook_id":"EEEEEEEEEEE","webhook_event":{"id":"WH-50769749FT4948424-GGGGGGGGGGGGGG","event_version":"1.0","create_time":"2023-04-23T10:36:06.097Z","resource_type":"payment_token","resource_version":"2.0","event_type":"VAULT.PAYMENT-TOKEN.CREATED","summary":"A payment token has been created.","resource":{"time_created":"2023-04-23T03:36:06.097Z","links":[{"href":"https:\/\/api.paypal.com\/v2\/vault\/payment-tokens\/IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","rel":"self","method":"GET","encType":"application\/json"},{"href":"https:\/\/api.paypal.com\/v2\/vault\/payment-tokens\/IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","rel":"delete","method":"DELETE","encType":"application\/json"},{"href":"https:\/\/api.paypal.com\/v2\/vault\/approval-tokens\/YYYYYY","rel":"approval_token","method":"GET","encType":"application\/json"}],"source":{"paypal":{"payer":{"email_address":"AAAAAAAA@mail.org","payer_id":"HHHHHHHHHHHHHHHHHHH"}}},"id":"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII","customer_id":"BBBB","status":"CREATED"},"links":[{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-50769749FT4948424-GGGGGGGGGGGGGG","rel":"self","method":"GET"},{"href":"https:\/\/api.paypal.com\/v1\/notifications\/webhooks-events\/WH-50769749FT4948424-GGGGGGGGGGGGGG\/resend","rel":"resend","method":"POST"}]}}
Response Debug ID: 9d8ebf6c14b32
Response: Array
(
    [code] => 200
    [message] => OK
)


```

FWIW, the user account tab on `/my-account/ppcp-paypal-payment-tokens/` says 
> No payments available yet. 

This is done on a live server. Asking a friend with another PayPal account who has never used our site, he is able to complete a subscription.

### Environment

All version up to date:

 - WordPress Version 6.2
 - WooCommerce Version 7.6.0
 - Plugin Version 2.0.4 
 - Browser [e.g. Chrome, Safari] and Version: Firefox

 - Any other plugins installed:

[Polylang Pro](https://polylang.pro/) 	  	von WP SYNTEX – 3.3.3
[Akismet Anti-Spam: Spam Protection](https://akismet.com/) 	  	von Automattic - Anti Spam Team – 5.1
[Classic Editor](https://de.wordpress.org/plugins/classic-editor/) 	  	von WordPress-Mitwirkende – 1.6.3
[WooCommerce Clone Orders](https://woocommerce.com/products/clone-orders) 	  	von Vibe Agency – 1.5.7
[DHL Shipping Germany for WooCommerce](https://github.com/shadimanna/dhl-logistic-services-for-woocommerce) 	  	von DHL – 3.3.0
[Kadence Related Content](https://www.kadencewp.com/) 	  	von Kadence WP – 1.0.10
[Kadence Shop Kit](https://www.kadencewp.com/product/kadence-woo-extras/) 	  	von Kadence WP – 2.0.17
[MC4WP: Mailchimp for WordPress](https://mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page) 	  	von ibericode – 4.9.3
[One Stop Shop für WooCommerce](https://github.com/vendidero/one-stop-shop-woocommerce) 	  	von vendidero – 1.3.7
[Polylang comments merging](https://polylang.pro/) 	  	von Frédéric Demarle – 0.3-dev
[Polylang for WooCommerce](https://polylang.pro/) 	  	von WP SYNTEX – 1.7.2
[Lazy Load - Optimize Images](https://de.wordpress.org/plugins/rocket-lazy-load/) 	  	von WP Rocket – 2.3.6
[ShortPixel Image Optimizer](https://shortpixel.com/) 	  	von ShortPixel - Convert WebP/AVIF & Optimize Images – 5.2.1
[Proxy Cache Purge](https://github.com/ipstenu/varnish-http-purge/) 	  	von Mika Epstein – 5.1.3
[WooCommerce Stripe-Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) 	  	von WooCommerce – 7.3.0
[Germanized für WooCommerce](https://www.vendidero.de/woocommerce-germanized) 	  	von vendidero – 3.12.1
Advanced Order Export For WooCommerce (Pro) 	  	von AlgolPlus – 3.4.1
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) 	  	von WooCommerce – 2.0.4
[PDF Invoices & Packing Slips for WooCommerce](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-bundle/) 	  	von WP Overnight – 3.5.2
[PDF Invoices & Packing Slips for WooCommerce - Professional](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-professional/) 	  	von WP Overnight – 2.14.1
[WooCommerce Subscriptions](https://www.woocommerce.com/products/woocommerce-subscriptions/) 	  	von [WooCommerce](https://woocommerce.com/) – 5.0.1
WooCommerce 	  	von Automattic – 7.6.0
[WP Mail SMTP](https://wpmailsmtp.com/) 	  	von WPForms – 3.7.0
[WP Overnight Sidekick](https://wpovernight.com/) 	  	von WP Overnight – 2.5.1
[wpSEO](https://www.wpseo.de/) 	  	von Kai Spriestersbach – 4.7.3
[XML Sitemap & Google News](https://status301.net/wordpress-plugins/xml-sitemap-feed/) 	  	von RavanH – 5.3.3

### Additional Details

I search the issue tracker here for other bugs with this error message, but those are much older and slightly different.

**Comment by gerdneuman** [comment]
> FWIW, the user account tab on /my-account/ppcp-paypal-payment-tokens/ says
> 
>     No payments available yet.


And FWIW, if I go to https://www.paypal.com/myaccount/autopay/ with the failing user, then the payment source for our WooCommerce website is listed there as active (start date was 29.11.2016)

**Comment by gerdneuman** [comment]
Problem is reproducible for other users :-( 

We just received an email from a customer who cannot complete a subscription purchase. 

Looking into the issue: This user has already had a subscription previously, and hence, probably an existing Reference Transaction "agreement" (not sure what the right term is here) with us.

So whenever, is already an existing **old** vault / reference transaction agreement at PayPal the whole process of buying a subscription fails.

I can send you the WooCommerce PayPal by mail log if you need it. Do not want to post it here publically.

**Comment by gerdneuman** [comment]
I have to correct myself: The other customer with the same error has **not** had a previous subscription with us – but instead she had just previous normal orders (no subscription products) with us, which she paid with PayPal.

**Comment by Sirvijver** [comment]
Hello @gerdneuman 

I see you already opened a support request with our support team (# 158769) via the WooCommerce support desk. 
The response on this support thread was the following:

> The error message you received indicates that the PayPal account is already saved in the vault but under a different customer id (WordPress user). As per the WooCommerce documentation on PayPal payments (https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting-vaulting), the same PayPal buyer account cannot be saved across multiple different WordPress users.
> 
> In order to assist you better, we kindly request you confirm whether the PayPal account was already saved for a different WordPress user. If not, please provide us with the steps to reproduce the error so we can further investigate the issue.
> 
> Also, this error typically occurs when attempting to pay for a free trial subscription or with a 100% coupon for a subscription while the PayPal buyer was already vaulted.

Because we only perform development activities on this platform. Please continue working with our support team, but we will close this thread as such.

Kind regards, 
Joost

**Comment by gerdneuman** [comment]
Hi @Sirvijver , thanks for clarifying. I will try to verify with the customer if she had paid with her PayPal account for another shop account before.

Regarding:
> I see you already opened a support request with our support team (# 158769) via the WooCommerce support desk.

Nope, I had not opened such a support request # 158769 
I guess you are confusing names here maybe.

(I had opened a support request, but on a complelely different thing)

**Comment by Sirvijver** [comment]
Hello @gerdneuman 

I found the support thread via the URL of the site, so it could also be a colleague of yours opening the support request for it. However, it does not matter much anyway. Please open the support thread if you require additional support.

Kind regards, 
Joost

**Comment by gerdneuman** [comment]
Hi @Sirvijver, I do not a colleague in this project :upside_down_face: How can I open the support thread? Being logged in at woocommerce.com and clicking on the `Support` tab (leads to https://woocommerce.com/my-account/create-a-ticket/) I can only submit _new_ support tickets anyway. 

FWIW, I got feedback from the customer now. She says that she might have possibly ordered before - buying a normal non-subscription product - with PayPal while being a "guest" customer, that is not having a shop account with us yet at this time.

The red warning section at https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting-vaulting says:
> A PayPal buyer account can only be saved in the Vault of the PayPal merchant account for one customer id (unique per WordPress user), not across multiple sites or customer ids.

This says nothing about the use case when a customer used PayPal as a guest before (and buying a subscription later as a then created customer). How about that? Can you clarify that it also does not work for this use case?
