### ISSUE TITLE
PayPal Pay Later Tab or configurations options no showing

### ISSUE THREAD

**Issue by eddr** [woocommerce/woocommerce-paypal-payments#1343]
### Describe the Bug

- PayPal Pay Later Tab or configurations options no showing. We want to disable it but have no such option on the PayPal Payment settings and neither in a different tab or a different gateway
- Smart buttons are enabled, Payments are working for quite some time now

### To Reproduce

1. Go to PP settings
2. https://yoursite.xxx/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway
3. Try to locate Pay Later settings

### Screenshots

![image](https://user-images.githubusercontent.com/373980/234201684-9db2aa8a-5dac-46fe-8106-76b7f51baa0d.png)

### Expected Behavior

Pay Later configurations tab / section that allow you to disable or enable it, like in the docs:
https://woocommerce.com/document/woocommerce-paypal-payments/#pay-later-tab

### Actual Behavior

No such configuration

### Environment

 - WordPress Version : 6.2
 - WooCommerce Version: 7.6
 - Plugin Version: 2.0.4
 - Browser [e.g. Chrome, Safari] and Version: Firefox
 - Any other plugins installed : should I list all of them?

### Additional Details

- EDIT:
seems to be related to this code on SectionsRenderer.php file:

if ( ! $this->messages_apply->for_country() ) {
    unset( $sections[ Settings::PAY_LATER_TAB_ID ] );
}

- Our store sells all over the world, including US 

- We noticed only recently that customers started to use the Pay Later option. 
Looking at the system status under the plugin's status, we noticed "Shop country code: IL"

<details><summary>System status</summary>

  `
### WordPress Environment ###

WordPress address (URL): https://ayalabar.com
Site address (URL): https://ayalabar.com
WC Version: 7.6.0
REST API Version: ✔ 7.6.0
WC Blocks Version: ✔ 9.8.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 7.4.28
PHP Post Max Size: 64 MB
PHP Time Limit: 3600
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.6.0

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Query Monitor: by John Blackbourn – 3.12.1
ATUM Multi-Inventory: by Stock Management Labs™ – 1.8.0.1
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.9.29.1
Classic Editor: by WordPress Contributors – 1.6.3
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.4.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
DynamicConditions: by RTO GmbH – 1.6.0
Elementor ActiveTrail Action: by Earlybirds – 0.1
Elementor Pro: by Elementor.com – 3.12.3
Elementor: by Elementor.com – 3.12.2
Email Log: by Sudar – 2.4.8
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.10
Klaviyo: by Klaviyo
Inc. – 3.0.12

Loco Translate: by Tim Whitlock – 2.6.4
MainWP Child: by MainWP – 4.4.1
PayPlus Payment Gateway: by PayPlus LTD – 6.2.8
PixelYourSite: by PixelYourSite – 9.3.6
Premium Addons for Elementor: by Leap13 – 4.9.53
Qama Priority Sync: by Liel Tzur – 5.5.3
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 5.3.3
PixelYourSite Performance Optimizer: by SecretChord – 0.85
ATUM extender plugin: by SecretChord – 0.1
WooCommerce Email Tests: by SecretChord – 0.1
Simple Custom CSS: by John Regan – 4.0.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.23.3

Accessibility by UserWay: by UserWay.org – 2.5.0
W3 Total Cache: by BoldGrid – 2.3.1
Order Tags: by 99w – 2.1.0
Webis Multilingual for WooCommerce: by  – 2.0.4
Ajax add to cart for WooCommerce: by QuadLayers – 2.0.2
Woocommerce Custom Product Addons: by Acowebs – 4.2.3
Woo Discount Rules PRO 2.0: by Flycart – 2.5.4
Woo Discount Rules: by Flycart – 2.5.4
Premmerce Permalink Manager for WooCommerce: by Premmerce – 2.3.8
Product Filter by WBW: by WBW – 2.3.3
WPC Smart Wishlist for WooCommerce: by WPClever – 4.6.5
FOX - Currency Switcher Professional for WooCommerce: by realmag777 – 2.4.0
WooCommerce PayPal Payments: by WooCommerce – 2.0.4
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.2
WooCommerce PDF Invoices & Packing Slips + mPDF: by WP Overnight – 2.4.0
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.14.1
WooCommerce Smart Coupons: by StoreApps – 7.7.0
WooCommerce: by Automattic – 7.6.0
WBW Product Filter PRO: by WBW – 2.3.3
Wordfence Security: by Wordfence – 7.9.2
Yoast SEO: by Team Yoast – 20.5
WP Crontrol: by John Blackbourn & crontributors – 1.15.2
WP Mail SMTP: by WPForms – 3.7.0

### Inactive Plugins (2) ###

Freesoul Deactivate Plugins: by Jose Mortellaro – 1.9.5.5
Transients Manager: by WPBeginner – 2.0.3

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IL
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: block-editor-feature-enabled
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-04-25 12:42:29 +03:00
Options: ✔
Notes: 110
Onboarding: skipped

### Status report information ###

Generated at: 2023-04-25 10:17:34 +03:00
`
</details>

**Comment by Sirvijver** [comment]
Hello @eddr 

The Pay Later feature is only available for a small amount of countries and is not displayed for other countries.
You can find the details and allowed countries for this feature in this [link](https://developer.paypal.com/docs/checkout/pay-later/au/). You can verify this, by using a sandbox account from countries that are allowed to utilize this feature.

If you have more questions, please reach out to us via [our support environment](https://paypal.inpsyde.com/docs/request-support/), since we only use GitHub for development activities. This is also the reason why we will close this thread.

Kind regards, 
Joost

**Comment by eddr** [comment]
Thanks, but the problem is that I can't turn it off. Not the other way around

**Comment by Sirvijver** [comment]
Hello @eddr 

In order to fix this, you should change your WooCommerce general location setting to US, so the PayPal tab will become visible again. Now you can deactivate the Pay Later option in this tab to resolve the issue and after doing this you should change the location setting back to Israel.

Please let us know if you got this resolved.

Kind regards, 
Joost
