### ISSUE TITLE
Loading Paypal scripts on every page

### ISSUE THREAD

**Issue by bnrbranding** [woocommerce/woocommerce-paypal-payments#1344]
### Describe the Bug

Every page on the site is loading the Paypal scripts, these should only load on product pages and in checkout

### To Reproduce

Enable Paypal payments on your site

### Expected Behavior

Paypal scripts should only load on product pages or in checkout

### Actual Behavior

Scripts are loading on every page

### Environment

 - WordPress Version - 6.2
 - WooCommerce Version - 7.6.0
 - Plugin Version - 2.0.4
 - Browser [e.g. Chrome, Safari] and Version - Chrome
 - Any other plugins installed - many other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @bnrbranding 
The scripts are only loaded on pages where the PayPal buttons or messaging is enabled.
I suggest disabling the Mini Cart button location: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-scripts-on-every-page
For more guidance, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by NickSick** [comment]
I have paypal buttons activated only on the checkout page, but still i have the same problem. Every page, every product page, every blog item, all the same, waiting for paypal.

Edit: i checked again, script is not loading on blog posts.

**Comment by Sirvijver** [comment]
Hello @bnrbranding 

We still advise you to open a support ticket with us, but there is one thing you might want to try:
Go to the settings page under the "standard payments" tab and find the fields for "Hide Funding Source(s)" and remove & add (or vise versa) the "Credit & debit cards" option from the field.

I encountered an instance where this helped resolve a similar issue.  Please try and if it doesn't work, please follow Niklas his instructions to engage our support team where we will continue helping you.

Kind regards, 
Joost

**Comment by bnrbranding** [comment]
Thanks, you can close this ticket.

Brent Friar
BNRBranding.com
(704) 584-9090
*Data driven digital marketing for small businesses*
