### ISSUE TITLE
paypal payment in 3 installments has been deconfigured on my website and does not appear even though it is activated

### ISSUE THREAD

**Issue by eliacastrillo** [woocommerce/woocommerce-paypal-payments#1353]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by eliacastrillo** [comment]
paypal payment in 3 installments has been deconfigured on my website and does not appear even though it is activated

**Comment by InpsydeNiklas** [comment]
Hi @eliacastrillo 
I suggest contacting the support team from here to clarify any questions you may have: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
