### ISSUE TITLE
woocommerce can not integrate PAYPAL

### ISSUE THREAD

**Issue by JasonL2023** [woocommerce/woocommerce-paypal-payments#1355]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @JasonL2023 
I suggest contacting the support team from here to clarify any questions you may have: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
