### ISSUE TITLE
All in one Checkout PayPay for Woocommerce

### ISSUE THREAD

**Issue by SteamDreamOfficial** [woocommerce/woocommerce-paypal-payments#1356]
### Describe the Bug

Hello, 

I have a big problem with the All in One Checkout for Woocommerce. 

I do not know what to do, because PayPal always automatically sets the test mode although I have entered the live API in the plugin. Also not all payment options are displayed that are set. After several phone calls with PayPal, I was told by the technical department that everything is in order from PayPal and also no errors are displayed at PayPal. Therefore, I am looking for contact with Woocommerce, because I have a Woocommerce store with the plugin All in One Checkout PayPal for Woocommerce. Everyday I have checkout problems because no one can pay through this plugin. 

So I need an advice from you to fix the issue as soon as possible. 

Please let me know what exactly you need so I can provide it. 
I am at your disposal for any queries. 

Best regards 
Dirk Wichmann 
STEAM DREAM 

Translated with www.DeepL.com/Translator (free version)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @SteamDreamOfficial 

This seems to be related to a plugin conflict with a 3rd party plugin (All in One Checkout for WooCommerce) that currently is in Beta testing. We could try to help out with this request, but the chance that such an issue will be quickly resolved from our side is small. These type of cases usually get a lower priority and can take much time before they are resolved.

If you want us to take a look at this plugin and any conflict it might have with our PayPal Payments plugin, please open a support request with our support team via [this link](https://paypal.inpsyde.com/docs/request-support/).
We don't provide support via GitHub, so we will mark this thread as resolved. If we end up needing to develop a solution for this issue, we will reopen this case and continue from there.

Kind regards, 
Joost
