### ISSUE TITLE
is_internal_meta_key was called incorrectly. 

### ISSUE THREAD

**Issue by uniquegroupltd** [woocommerce/woocommerce-paypal-payments#1361]
Hello, our server receive a lot of following errors:

is_internal_meta_key was called incorrectly. \xe4\xb8\x80\xe8\x88\xac\xe6\x96\xb0\xe5\xa2\x9e/\xe6\x9b\xb4\xe6\x96\xb0/\xe5\x8f\x96\xe5\xbe\x97\xe4\xb8\xad\xe7\xb9\xbc\xe6\x96\xb9\xe6\xb3\x95\xe4\xb8\x8d\xe6\x87\x89\xe8\xa9\xb2\xe7\x94\xa8\xe6\x96\xbc\xe5\x85\xa7\xe9\x83\xa8\xe4\xb8\xad\xe7\xb9\xbc\xe8\xb3\x87\xe6\x96\x99\xef\xbc\x8c\xe5\x8c\x85\xe6\x8b\xac\xe3\x80\x8c_shipping_phone\xe3\x80\x8d\xe3\x80\x82\xe4\xbd\xbf\xe7\x94\xa8 getter \xe5\x92\x8c setter\xe3\x80\x82 Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Gateway\\CreditCardGateway->process_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->process, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_new_order_status, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Processing_Order->trigger, WC_Email->get_content, WC_Email_Customer_Processing_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-processing-order.php'), do_action('woocommerce_email_customer_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->email_addresses, wc_get_template, include('/plugins/woocommerce/templates/emails/email-addresses.php'), WC_Order->get_formatted_shipping_address, apply_filters('woocommerce_order_formatted_shipping_address'), WP_Hook->apply_filters, Flexible_Checkout_Fields_Disaplay_Options->woocommerce_order_formatted_shipping_address, Flexible_Checkout_Fields_Disaplay_Options->woocommerce_order_formatted_address, wpdesk_get_order_meta, WC_Data->get_meta, WC_Data->is_internal_meta_key, wc_doing_it_wrong. This message was added in version 3.2.0.

Shall we know what it is and can we fix ?

Thanks & Regards,
Andrew

**Comment by InpsydeNiklas** [comment]
Hi @uniquegroupltd 
This looks like a potential compatibility issue with the Flexible Checkout Fields plugin. It's possible this plugin may need some tweaks to not negatively impact the PayPal Payments settings pages.
For more guidance, I suggest contacting the support team directly: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
