### ISSUE TITLE
Payment Optiong is not showing 

### ISSUE THREAD

**Issue by NexLinkns** [woocommerce/woocommerce-paypal-payments#1364]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @NexLinkns 
If you need help setting up PayPal Payments, I suggest contacting the support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Please include more details about your problem and a copy of your WooCommerce system report. 
Thanks!
