### ISSUE TITLE
The PayPal payment button does not appear

### ISSUE THREAD

**Issue by MakeIT-DigitalAgency** [woocommerce/woocommerce-paypal-payments#1369]
![WhatsApp Image 2023-05-07 at 17 57 07](https://github.com/woocommerce/woocommerce-paypal-payments/assets/85159486/5c73d75b-c18c-4285-9eac-76aa1aa440e3)
![WhatsApp Image 2023-05-12 at 12 58 56](https://github.com/woocommerce/woocommerce-paypal-payments/assets/85159486/4d765400-40ca-47da-be8c-de618661fd74)
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @MakeIT-DigitalAgency 
This most likely is a compatibility issue with your theme. Can you please check if the behavior persists with a default theme like [Storefront](https://wordpress.org/themes/storefront/)?
If this resolves the issue, I suggest installing [this small plugin](https://drive.google.com/uc?export=download&id=1fArJDYadZ1vyRZUTr3LtfiYXZz3zAGX1) to see if it results in the button loading on the Checkout page.

For any questions about the setup, please consider reaching out to the support team directly [from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).
Thanks!
