### ISSUE TITLE
Credit Cards Processing fails with e-cards

### ISSUE THREAD

**Issue by Buzut** [woocommerce/woocommerce-paypal-payments#1371]
Several of our customers repeatedly face payment failures when trying to pay with their e-cards. After they resorted back to their normal credit card, it worked like it should.

`Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be
performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYMENT_DENIED
CreditCardGateway.php:406 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business
validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYMENT_DENIED OrderEndpoint.php:327État de la commande modifié de Attente paiement à Échouée.`

**Comment by InpsydeNiklas** [comment]
Hi @Buzut 
This error is not a technical issue but the result when PayPal rejects a payment.
The team is working on improved error messages, but there is nothing the plugin could do about PayPal rejecting the payment.
For more information, I suggest contacting the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/).
