### ISSUE TITLE
Payment upon Invoice orders marked as paid, but empty payment instructions are sent

### ISSUE THREAD

**Issue by jankohoener** [woocommerce/woocommerce-paypal-payments#1373]
### Describe the Bug

Some orders on our site made via Pay upon Invoice in Germany (Per Rechnung zahlen) have been marked as paid, however there's no link as usual to Paypal, there are no Ratepay payment instructions and also the Paypal Transaction Fee is not calculated. Furthermore, in one case, the order confirmation e-mail to the customer contained empty payment instructions

> Bitte überweisen Sie den Betrag in Höhe von xxx € bis zum 06-06-2023 auf das unten angegebene Konto. Wichtig: Bitte geben Sie unbedingt als Verwendungszweck an, sonst kann die Zahlung nicht zugeordnet werden.
> 
 >   Empfänger:
 >   IBAN:
 >   BIC:
 >   Name der Bank:
 >   Verwendungszweck:

### To Reproduce
It happened only for some cases of paying upon invoice on the checkout page. So I don't know if it can easily be reproduced.
As some of the data are confidential customer data I don't wish to include that publicly. Is there a way to proceed confidentially?

### Expected Behavior

I would have expected the order to either complete as usual with the link, the payment instructions and the transaction fee calculated or to have failed, as it did in some cases on our site already.

### Actual Behavior

The order is marked as paid, however it seems that it actually isn't and that the customer doesn't receive payment instructions.

### Environment

 - WordPress Version 6.2
 - WooCommerce Version 7.7.0
 - Plugin Version 2.0.4
 - Any other plugins installed: numerous plugins would prefer to share them confidentially

**Comment by InpsydeNiklas** [comment]
Hi @jankohoener 
This behavior could occur when you manually change the order status before the webhook with the payment instruction arrives: https://woocommerce.com/document/woocommerce-paypal-payments/#PUI-email-notification
As long the webhook did not arrive, the Pay upon Invoice orders will not contain any details, including the transaction id and payment instructions.
I suggest resubscribing the webhooks as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#webhook-status
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
