### ISSUE TITLE
We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again.

### ISSUE THREAD

**Issue by AmYre** [woocommerce/woocommerce-paypal-payments#1378]
### Describe the Bug

I had the plugin for many months now. Yesterday one of my online buyers said to me that they try to buy on my website having this message : "Something went wrong. Please try again or choose another payment source". I get on my dashboard, deleted paypal account, and start to reconnect my account. But now when try to reconnect my paypal account to the WooCommerce PayPal Payments plugin, i have this message : "We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again. ". When i try again, it says the same thing. Any help ?

**Comment by InpsydeNiklas** [comment]
Hi @AmYre 
You could try it again, but before clicking the "Back to WooCommerce" button in the PayPal popup, wait about 5-10 seconds. The onboarding process could potentially be interrupted when this button is clicked too quickly.
If it still doesn't work, you may want to consider manually connecting your API credentials: https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input

If you encounter any problems with the plugin setup, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by AmYre** [comment]
Hi Niklas, thank you it worked !

I have another question, I do not know if it is the right place to do it.
But i will try. If i had to unconnect my paypal account and encountered the
problem you help me fixed it is because one of my clients had a issue with
the payment process, it did not pass. The client still have the
problem even after resetting paypal. There is the object error the console
throwed at her :

Object { err: "e.address is undefined\nt@
***@***.***://savonsdesaison.fr/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/assets/js/button.js?ver=2.0.4:2:94806\nZr/
</</<@
***@***.******@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:75486\nZr/
</<@
https://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:136739\nXr/
<@
***@***.******@***.******@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:143455\nco/
</</<@
***@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:77328\nco/
</</<@
https://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:149338\nco/
</<@
***@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:130141\nWr/
<@
https://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:138519\nWr/
<@
***@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:138531\nno/u
<@
***@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:143220\nco/
</</<@
***@***.***://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:77328\nco/
</</<@
https://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:149338\nco/
</<@
https://www.paypal.com/sdk/js?client-id=AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9&currency=EUR&integration-date=2023-03-20&components=buttons,funding-eligibility,messages&vault=false&commit=true&intent=capture&disable-funding=card,credit,paylater&enable-funding=venmo:3:149593\n",
timestamp: "1684156264643", referer: "www.paypal.com", sdkCorrelationID:
"0b9361b4a4986", sessionID: "uid_8f1d9eeb7f_mtm6mta6mtg", clientID:
"AeL8xhkne0XtmX-skQHgAhs3n8JAaJ1YJ0J7nftX9vXG0tCZpQ6u2Mx2X-JXguSSeCAjzMNQzjJRQXl9",
env: "production", buttonSessionID: "uid_2bf4898ebe_mtm6mta6mtg",
buttonCorrelationID: "f721295032654", time: "1684156264643", … }

Any help ?

Le lun. 15 mai 2023 à 17:14, Niklas Gutberlet ***@***.***> a
écrit :
