### ISSUE TITLE
Unable to connect paypal block checkout

### ISSUE THREAD

**Issue by captaincourageous** [woocommerce/woocommerce-paypal-payments#1385]
Added `add_filter( 'woocommerce_paypal_payments_blocks_enabled' , '__return_true' ); ` to `functions.php` - this did not change anything.

And then tried the paypal blocks plugin - WooCommerce PayPal Payments - Enable Block Buttons. 

"WooCommerce Blocks" plugin is active. 
Woocommerce is v7.6.1

Woocommerce block checkout page still shows  "Incompatible with block-based checkout" in the CC section.

"Smart Button Location" in Paypal Payments Plugin -> Standard Payments does not show the 'Block' options as shown here:
https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews

**Comment by InpsydeNiklas** [comment]
Hi @captaincourageous 
Thanks for testing.
It looks like option 1 may only work when adding the filter to a plugin like "Code Snippets" and not when adding the filter to directly your theme.
But options 2 and 3 should work in any case: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews#enabling-express-block-features

But if you need any guidance with the testing setup, I recommend contacting the support team directly from here:
https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!

**Comment by captaincourageous** [comment]
Congratulations. It appears to work. I have not made a payment myself since I am the account owner, but buttons all appear as expected and click thru functionality is as expected. Thank you for all your hard work.

**Comment by InpsydeNiklas** [comment]
@captaincourageous Thanks for the feedback! 
The entire payment process can also be tested without moving any real funds by connecting a [PayPal sandbox account](https://woocommerce.com/document/woocommerce-paypal-payments/#testing-in-sandbox) as the plugin can have one live account and one sandbox account connected.
In any case, the upcoming update early next week will include this feature preview. The following update in late June/early July should remove the feature flag to make this functionality available to everyone by default without needing the code snippet.
If any questions arise, I suggest [contacting the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thank you!
