### ISSUE TITLE
Create Order error

### ISSUE THREAD

**Issue by ernieshigh** [woocommerce/woocommerce-paypal-payments#139]
On clicking "PayPal" button to submit order  get Woocommerce Error message:
"Something went wrong. Please try again or choose another payment source."

Expecting to be directed to PayPal login page to submit payment,

Attached screenshot of error

[image005](https://user-images.githubusercontent.com/8550439/112708391-bb41a680-8eec-11eb-99b0-4f8110a5872a.jpg)

Tried different theme, disable plugins. Contacted PayPal support to verify connection, correct API keys etc. They say it is a Woocommerce issue

**Comment by InpsydeNiklas** [comment]
Hi @ernieshigh,

Could you please open a support ticket as described here?:
https://paypal.inpsyde.com/docs/how-to-request-support-via-widget-on-the-website/
Please include your WooCommerce system report and a link to this issue.
Thanks!

Kind regards,
Niklas
