### ISSUE TITLE
WooCommerce PayPal Payments error

### ISSUE THREAD

**Issue by magasati** [woocommerce/woocommerce-paypal-payments#1401]
### Describe the Bug

I've been useing WooCommerce PaypalPayment plugin with my wordpress site. It was working fine untill the last week. There was no changes in the site but payments canot be succeded and my clients ge the following error messages:
"We’re sorry, but we are unable to add this card. Try again later or add a different card"
I updtaed woocommerce, woocommerce database and the plugin itself but the issue still remains

### To Reproduce

1. Go to 'https://kendermanufaktura.com/termek/fizetes-proba/'
2. Click on 'Kosárba teszem' (Add to cart)
3. Click on  'Kosár' (Cart)
4. Click on 'Tovább a pénztárhoz' (Proceed to chevkout)
5. Select radiobutton 'Bankkártya / Paypal' (Credit card / Paypal)
6. Add credit card details for trial purchase for 100 HUF = 
![paypal-error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/134312568/8bafea23-f3b2-4bb7-8a24-f4fe09b752ab)
0.267 EUR
7. See error

### Screenshots

paypal-error.jpg shows the error message after adding credit card details and cliking on pay button.

### Environment

 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.7.0
 - Plugin Version: 2.0.4
 - Browser [e.g. Chrome, Safari] and Version: Chrome
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @magasati ,

Thank you for reaching out to us, however, the GitHub site is not the correct site for support request. I will provide you a response on this matter, but will have to ask you to [reach out to our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), in case you need additional support.

The card payment method you are using is the Standard Card Processing option, this payment method is triggered by our plugin, but actually come from the WooCommerce plugin and is managed completely by the PayPal Server. Our plugin does not have any control over its function. For this reason, you will need to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review these payment attempts to find out what is causing these failures. 

Our plugin won't show any logs of this payment method, neither does it have any settings that could affect it, so there is very little we can do to help for this payment method. The only solution we can offer for this is to switch over to our Advanced Card Processing payment method. Unfortunately, this payment method is only available in [certain countries](https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/).

I hope MTS can help you out to resolve this issue.

Kind regards, 
Joost
