### ISSUE TITLE
paypal is not working after updation

### ISSUE THREAD

**Issue by aliminhas978** [woocommerce/woocommerce-paypal-payments#1405]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @aliminhas978 

With the details you have provided, we are not able to give any support. We need to know what you are seeing, what errors you get and what logs are generated. We simply need to know what is happening after the update. Also: from what to what did you update?

We do actually not use GitHub for providing plugin support, so I would ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for support on this matter. This thread will be closed.

Kind regards, 
Joost
