### ISSUE TITLE
Pay in 3 quits without errors

### ISSUE THREAD

**Issue by badpenguin** [woocommerce/woocommerce-paypal-payments#1414]
I've this bug since many months regarding plugin and WP/WC updates.

It does not happen every time.

After the user complete the transaction using the "pay in 3" popup 
this popup close and nothing more happen:
- no order is create in woocommerce
- no error logs
- even enabling paypal logs in wp-content/wc-logs there are no message
- no paypal transaction in our merchant account

On the user side the paypal transaction exists but after 48 hours is refunded automatically by paypal.

It seem more a problem on paypal side rather then the plugin
but it wish at least know witch is the problem to communicate with the customsers;
expecially why the user does not receive any UX or email feedback from paypal.

Its happening randomly since many months but i've all upgraded now:
 - WordPress 6.2.2
 - WooCommerce 7.7.2
 - Plugin Version 2.0.5
 - Browser: any
 - Any other plugins installed:
 - PDF Invoices & Packing Slips for WooCommerce 3.5.4
 - WooCommerce Stripe Gateway 7.4.1

**Comment by Sirvijver** [comment]
Hello @badpenguin ,

Thank you for reaching out to us, however, the GitHub interface is only used by us for doing development and not support activities. If my response below does not help, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you report, could be an issue where our plugin does not receive the webhooks for a successful payment, so you might want to look and test the webhooks. You can find the 2 webhook tools (buttons: "Simulate" and "Resubscribe" in our settings page, under the tab "Connection".

At the moment when the pop-up for Pay Later pops up, the process is actually taken over by PayPal. So it might also be better to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and provide them the account(s) and time (+date & timezone) to see if they can find any issue from their end. Please also check the plugin logs to see if you are not able to find any entries of these payment attempts, so you could include some Debug ID's if available.

If this does not help you, and you need our continued support, please open a thread with our support team as instructed above. For now, we will close this thread.

Kind regards, 
Joost
