### ISSUE TITLE
Paypal

### ISSUE THREAD

**Issue by illuminationslight** [woocommerce/woocommerce-paypal-payments#1419]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @illuminationslight 
It's not quite clear which problem you encounter, but if you need help setting up the [PayPal Payments plugin](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
