### ISSUE TITLE
The Paypal Advanced Credit Card Option got turned off by itself

### ISSUE THREAD

**Issue by dcuff** [woocommerce/woocommerce-paypal-payments#1423]
The option of visitors to pay with Credit Card was disabled.
I had to manually turn it back on.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @dcuff 
Usually, the plugin settings should not change without your input. 
There is a potential issue that could lead to the Advanced Card Processing gateway not showing after a plugin update. But to learn more about this please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
