### ISSUE TITLE
The card button is not displayed on the checkout page

### ISSUE THREAD

**Issue by renninho11** [woocommerce/woocommerce-paypal-payments#1425]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @renninho11 
The Standard Card Button not appearing on the Checkout page could have multiple causes, such as a horizontal button layout, or when it is disabled via the `Hide Funding Source(s)` setting.
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need further guidance. Thanks!
