### ISSUE TITLE
Trying to activate PayPal and it kicks me to my staging site.

### ISSUE THREAD

**Issue by congruitymel** [woocommerce/woocommerce-paypal-payments#1428]
### To Reproduce

1. Login to my WP Admin for my live site 
2. Go to Woocommerce
3. Click on "PayPal Payments is almost ready. To get started, connect your account"
4. Click Activate PayPal (enable PayPal Payments is selected, Securely accept all major credit cards is not selected)
5. Pop up window appears to login to PayPal 
6. Enter my credentials 
7. Agree and Connect
8. The same popup window says Thanks for Signing Up with a button to "Go back to WooCommerce"
9. Directs me to my staging site and requires me to login to Wordpress 

### Screenshots
<img width="459" alt="Screenshot 2023-06-12 at 11 44 50 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/122054321/95d061ba-5e18-4488-9889-6ba438382412">
<img width="454" alt="Screenshot 2023-06-12 at 11 44 42 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/122054321/eaa13bf2-5bab-4c8e-b735-81f5815e429a">
![Screenshot 2023-06-12 at 11 53 23 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/122054321/832049ac-72ca-4ff6-adc1-c81dae356d41)

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.7.2
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed: Woocommerce Payments 6.0.0, Woocommerce PayPal payments 2.0.5

**Comment by InpsydeNiklas** [comment]
Hi @congruitymel, 

Thanks for reaching out and sorry for the inconvenience.

There could be a caching issue causing this behaviour. 'Transients' is a type of cache that WordPress uses to store temporary data, like the signup URL. Clearing your transients should help. They are stored in your website's database, in the `wp_options` table. You can search for and delete the transients related to the PayPal connection process by searching for values **LIKE** `%ppcp-paypal-signup%`.

Alternatively, you can manually adjust the return URL:

- Right-click the "Go back to WooCommerce" button on the last step of the onboarding wizard and select 'Copy Link Address'.

- Paste the URL in a new browser tab. But before you hit enter, replace the part of the URL that points to your staging site with your live site's URL. When you then go to this URL, the plugin should connect to your live site.

If the above solutions don't work, you can [manually connect](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input) your API credentials in the PayPal Payments plugin settings.

Please don't hesitate to [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need further guidance.
Thanks!
