### ISSUE TITLE
PayPal Button not showing on my checkout page

### ISSUE THREAD

**Issue by mayazankoul** [woocommerce/woocommerce-paypal-payments#1429]
### Describe the Bug

The default PayPal  "Place Order" button isn't showing when I select "PayPal/Credit Card" as payment option on my website.

### To Reproduce

1. Go to 'www.lilatv.com/shop'
2. Select any item to buy
3. Go to cart
4. Go to Checkout page
5. Select "PayPal/Credit Card" as payment method
6. No place order button appears!

### Expected Behavior

We should see the default PayPal checkout button

### Actual Behavior

No buttons at all are appearing.

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.7.2
 - Plugin Version 2.0.5
 - Browser both Chrome and Safari
 - Any other plugins installed, yes but I tried turning them all off and using StoreFront as a theme, and the button didnt appear. Instead, there was like a loading button the whole time.

**Comment by InpsydeNiklas** [comment]
Hi @mayazankoul 
As far as I can tell, the PayPal buttons are loading and working correctly on your Checkout page:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/cda5a4a3-c051-48a3-9df6-e9ef2889d6b8)
Please note that the PayPal buttons are replacing the regular "Place order" button on the Checkout page: https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-on-checkout-page

If you need help with the plugin setup, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
