### ISSUE TITLE
Advanced Card Processing gateway becomes invisible post-plugin update unless admin pages are accessed once (1759)

### ISSUE THREAD

**Issue by InpsydeNiklas** [woocommerce/woocommerce-paypal-payments#1432]
### Describe the Bug

Post the update to version 2.0.4, a new issue has emerged resulting in the Advanced Card Processing gateway not loading after updating the plugin. The problem persists upon upgrading or downgrading to 2.0.4, and also affects subsequent versions (2.0.5, 2.1.0).

In order to mitigate this problem temporarily, one must visit any section within the PayPal Payments settings or the Payments tab under the WooCommerce settings. It's noteworthy that no changes need to be saved.

### To Reproduce

- Install version 2.0.3
- Enable ACDC gateway
- Visit the Checkout page
- Observe that the ACDC gateway is visible
- Update to any newer version (2.0.4, 2.0.5, 2.1.0)
- **Do not** navigate to the PayPal Payments settings page or the WooCommerce>Settings>Payments tab
- Reload the Checkout page
- Observe that the ACDC gateway is not visible
- Navigate to/reload the WooCommerce>Settings>Payments tab or any PayPal Payments settings tab (no need to save anything)
- Reload the Checkout page again
- Observe that the ACDC gateway is now visible

### Expected Behavior

Post plugin update, the Advanced Card Processing gateway should remain visible on the Checkout page without necessitating a visit to the WooCommerce>Settings>Payments tab or any PayPal Payments settings tab.

### Actual Behavior

Presently, the Advanced Card Processing gateway disappears from the Checkout page post-update unless certain admin pages are accessed at least once.

### Environment

- WordPress Version: Unspecified
- WooCommerce Version: Unspecified
- Plugin Version: From 2.0.4 onwards

**Comment by sx23296** [comment]
I can confirm the problem. The card payment is no longer displayed.

**Comment by spigotdesign** [comment]
Also confirming the problem and the 'solution'.

**Comment by TorlockC** [comment]
Copying from the WP plugin directory for visibility:

Hi @InpsydeNiklas, the workaround here is only staying in place temporarily on our website before card payments drop off again every few hours.

For reference, we use an autoscaling WP implementation which likely explains why this keeps happening when different servers are spun up to replace old ones. I’ve also reverted back to 2.0.3 but still the issue persists regardless.

Is it possible to let me know if there has been any progress in better understanding the cause or working toward a fix?

**Comment by generalwax** [comment]
I had been dealing with this using the solution provided until now.  With update to 2.9.4, the Advanced Card Processing is gone altogether.  All I have in the settings now is Standard Card Button.

**Comment by generalwax** [comment]
This may be a compatibility issue with the latest release of WooCommerce.
