### ISSUE TITLE
Checkout Buttons Disappears On Checkout Page After Page Loaded

### ISSUE THREAD

**Issue by Kenny728** [woocommerce/woocommerce-paypal-payments#1436]
### Describe the Bug

As the title described, when I go to the checkout page, I can see the Paypal check out button appears and loading (not clickable yet) and after a short time of loading, the Paypal checkout button disappears (both pay via credit card & pay via Paypal)

### To Reproduce

I have to restore the plugin version back to 2.0.5 to make sure it runs properly, so I choose not to provide my website link. If you need it, we can have a private chat, and I will upgrade the plugin to reproduce this issue for a short time.

### Expected Behavior

checkout button appears and is ready to redirect users to checkout

### Actual Behavior

The button is gone after the checkout page is loaded, and it is visible (not clickable) for a short time while loading

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.7.2 & 7.8.0
 - Plugin Version 2.0.5 & 2.1.0
 - Browser [e.g. Chrome, Safari] and Version Edge Version 113.0.1774.57 (Official Build) (64-bit)
 - Any other plugins installed: Elementor 3.13.4/Pro 3.2.1; ShopEngine 4.2.0/Pro 2.2.1

### Additional Details

The website has 8 plugins that need to upgrade today, so I run several backup restores to rule out the effect of the upgrade of other plugins. The last two plugins that may affect the checkout button could be the WooCommerce plugin and the WooCommercce Paypal Payment plugin. They both release updates these days, and I am not sure which plugin upgrade caused this.

* This issue only appears on the checkout page. The Paypal button runs well on other pages

**Comment by haritslamis71** [comment]
Hi, would you mind letting me know how to downgrade to previous version of "Woo Paypal Payment" please, I could not find the option to do so on their web and I am not familiar with Github. Thanks

**Comment by Kenny728** [comment]
@haritslamis71 
> I guess it's not just me having this issue. Here's the link: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.0.5

**Comment by haritslamis71** [comment]
Great, thank you @Kenny728.

**Comment by Sirvijver** [comment]
Hello @Kenny728 and @haritslamis71 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We just released version 2.1.0, so maybe you should try that version and see if it resolves this issue. Otherwise, please open a support thread via the link provided above. Since we don't do plugin support via GitHub, I will close this thread.

Kind regards, 
Joost

**Comment by Kenny728** [comment]
> Hello @Kenny728 and @haritslamis71
> 
> You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
> 
> We just released version 2.1.0, so maybe you should try that version and see if it resolves this issue. Otherwise, please open a support thread via the link provided above. Since we don't do plugin support via GitHub, I will close this thread.
> 
> Kind regards, Joost

Hi @Sirvijver, I think this is a bug worth noticing, so I am reporting it here. This issue appears on 2.1.0, not on 2.0.5
