### ISSUE TITLE
Vault Option Not Showing Once Activated (Can't Disable Vaulting)

### ISSUE THREAD

**Issue by LemonadeStandWeb** [woocommerce/woocommerce-paypal-payments#1438]
### Describe the Bug

I activated Vaulting to enable Subscriptions, but ended up deciding to go with a separate payment gateway for Subscriptions. When I returned to PayPal WooCommerce to disable Vaulting so that PayPal wouldn't show up as a payment option for Subscription products, the option no longer exists.

In screenshots it appears it was located under the "Standard Payments" tab, however I no long have the option.

The box I originally ticked was titled: "

### To Reproduce

With PayPal Enabled and Connected, go to PayPal Checkout Settings and tick the box for "Vaulting". IT says "Enable saved cards and subscription features on your store. To use vaulting features you must enable vaulting on your account."

Once complete, navigate away and come back.

No other payment method adjustments were made since then although I did add one additional payment method today which should not overlap with PayPal Payments in any way.

### Screenshots

![chrome_RPw5vQ03fg](https://github.com/woocommerce/woocommerce-paypal-payments/assets/134979133/d3674d16-ff97-4383-bde8-ab4be6340f17)

![WooCommerce settings ‹ Ready Room Coffee — WordPress](https://github.com/woocommerce/woocommerce-paypal-payments/assets/134979133/96247df7-ca8f-4b4e-8a84-befa657aacde)

### Expected Behavior

Should still have the Vaulting box for me to untick so that I can disable PayPal as a payment method for Subscription products.

### Actual Behavior

Does not allow me to disable Vaulting so that PayPal still appears to allow purchase on Subscription products, even though I'm still awaiting approval on Vaulting and cannot actually save payments.

### Environment

 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.8.0
 - Plugin Version: 2.1.0
 - Browser: Chrome

### Additional Details

Nothing has changed since the Vaulting box was originally ticked to enable PayPal payments on Subscription products.

</details>

**Comment by InpsydeNiklas** [comment]
Hi @LemonadeStandWeb 

Following update 2.1.0, the Vaulting feature on the Standard Payments tab is automatically hidden and disabled if the connected PayPal account does not have [Vault approval (Reference Transactions)](https://woocommerce.com/document/woocommerce-paypal-payments/#get-vaulting-approval). However, if the Vaulting setting was enabled before the update, then the plugin will still continue to declare subscription compatibility to not abruptly invalidate existing setups.
This is an in-between step for additional changes in the following update. [Here](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews) you can read more about the next update, which includes a feature to process [PayPal Subscriptions](https://developer.paypal.com/docs/subscriptions/) via PayPal Payments. 

There are multiple ways to get Vaulting disabled for your case where it is enabled, but the checkbox is hidden:

- clear the plugin settings from the Connection tab & reconnect the PayPal account
- downgrade to 2.0.5, disable Vaulting, update again to 2.1.0
- change the value in the `woocommerce-ppcp-settings` option in the database directly 

The team is still working on updating the documentation with the latest changes.
I hope this helps!
If any questions remain, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
