### ISSUE TITLE
fatal error since new update

### ISSUE THREAD

**Issue by mttindustries** [woocommerce/woocommerce-paypal-payments#1439]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

getting this error in the error log. 
[15-Jun-2023 08:14:58 UTC] PHP Fatal error:  Uncaught TypeError: Return value of WooCommerce\PayPalCommerce\Button\Assets\SmartButton::intent() must be of the type string, null returned in /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php:1434
Stack trace:
#0 /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(986): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->intent()
#1 /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(803): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->url_params()
#2 /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(600): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->script_data()
#3 /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(71): WooCommerce\PayPalCommerce\But in /home/slotmein/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php on line 1434

this was working all before before updating it yesterday to version 2 

when clicking on cart the whole site throws and error message

**Comment by Sirvijver** [comment]
Hello @mttindustries 

Thank you for reaching out to us and informing us about this situation. We have created a bug for our developers to look into this situation and hope to fix this soon. Please give us some time, so our developers can investigate, and we will update you once we have any news on this matter.

It could be good to temporary switch back to the previous version, so that it does not affect your website. Be aware that this is the only report we received so far.

Kind regards, 
Joost

**Comment by sx23296** [comment]
Same problem here...

I switched back to the previous version and waiting for the next update.

**Comment by mttindustries** [comment]
I found just disabling the smart button feature solves the issue. So at the moment the site is just using the vanilla check boxes for payment methods until this issue gets fixed

Sorry didn't mean to close the issue that was an accident

**Comment by mttindustries** [comment]
I found just disabling and resetting the smart button locations seemed to solved it. Maybe it needed to be reassigned for a woo-commerce database update

**Comment by Motobugs** [comment]
> I found just disabling and resetting the smart button locations seemed to solved it. Maybe it needed to be reassigned for a woo-commerce database update

me too....now it seems to work!
