### ISSUE TITLE
PayPal buttons missing from WooCommerce Checkout page

### ISSUE THREAD

**Issue by mvdbergh** [woocommerce/woocommerce-paypal-payments#1442]
We can't complete the order on checkout, as there are no PayPal buttons visible.

We have enabled the WooCommerce Plugin, Price based on Counrtry, Paystack, Payfast and Paypal Payments.

### To Reproduce

1. Go to https://wwisacademy.com/
2. Click on a ticket to Get Tickets
3. Scroll down to bottom and add tickets
4. Add to cart
5. Checkout
6. And try select paypal

### Screenshots

<img width="599" alt="Screenshot 2023-06-16 at 16 14 42" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/29274600/c6d4708c-997a-4b1e-8322-0107e8a32c36">

 - WordPress Version: Latest
 - WooCommerce Version: Latest
 - Plugin Version: Latest
 - Browser Chrome
 - Any other plugins installed -  WooCommerce Plugin, Price based on Counrtry, Paystack, Payfast and Paypal Payments.

### Additional Details

**Comment by mvdbergh** [comment]
I think this is related to Sandbox vs Live - I'm regenerating API Creds.

**Comment by InpsydeNiklas** [comment]
Hi @mvdbergh 
From the screenshot, it looks like South African Rand (ZAR) is the configured currency. PayPal doesn't support this currency: https://developer.paypal.com/docs/api/reference/currency-codes/
For certain unsupported currencies, the PayPal buttons may not load at all, while with other currencies, an error may be thrown when the button is clicked. ZAR belongs to the currencies where no buttons are loading at all.
The team is currently working on adding a warning on the settings page when your store currency is not supported by PayPal in #1433 
This should help clarify the situation with unsupported configurations.

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need any additional assistance with the plugin setup. Thanks!
