### ISSUE TITLE
Payments not Completing

### ISSUE THREAD

**Issue by SonyaS3** [woocommerce/woocommerce-paypal-payments#1449]
Customers have reported to me that they go through our checkout, click through to pay with paypal, login to paypal and click to submit the payment and see a screen on paypal's site saying thank-you, but they do not get redirected back to our site, the payment doesn't go through (on both their paypal account and ours) and the order never comes through our site.

**Comment by Sirvijver** [comment]
Hello @SonyaS3 

Thank you for reaching out to us, we would like to help you, but the GitHub forum is only used for development activities, and this seems to be a support request. In any case, if we want to help you, we will need more details about the situation.

I would advise [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) and provide them:
- The system report.
- The logs (if available, if not, please activate the logging function in the plugin settings).
- Screenshots of the order overview (we want to look at the order notes).

One thing you can do now, is to check the webhooks; if these don't function correctly, it can cause the "payment successful" webhook to not arrive at WooCommerce. You can find 2 buttons that help you with this, in the settings pages under the tab "Connection". You can use the "Simulate" and "Resubscribe" button to test and possibly fix the webhooks. Please also add to the newly opened support ticket, that this was done and what response the buttons gave you.

For now, I will close this ticket and wait for you to open this support ticket.

Kind regards, 
Joost
