### ISSUE TITLE
"Something went wrong error" after last update! please Urgent!

### ISSUE THREAD

**Issue by Motobugs** [woocommerce/woocommerce-paypal-payments#1451]
Using elementor + xstore theme in a woocommerce site I have a big problem on the checkout procedure.
Selecting credit card or paypal or paylater methods, system do not connect to the external paypal access page for customers and a red issue comes out on my site's frontend speaking : "something went wrong please try another payment source" and again, another error that occurs is regarding a "0" value using the credit card method (maybe when a customer insert the card number on the relative field.
Please solve this bug asap because I can't take payments on this site and it is a mess.
Let me know, thanks a lot

 - WordPress Version 6.2.2
 - WooCommerce Version 7.8.0
 - Plugin Version 2.1.0
 - Browser Edge, and Firefox and Chrome
 - Xstore theme 5.1.7
 - Elementor 3.14
 - WProcket 3.13.4

**Comment by InpsydeNiklas** [comment]
Hi @Motobugs 

An error like this can have various causes, and we would need to know more details about your site, like a copy of your system report, to judge it. 
If you encounter any problems after an update to the latest version 2.1.0, I suggest rolling back to the previous version 2.0.5 to see if the problem persists.

But please [contact the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
