### ISSUE TITLE
Incompatibility with WooCommerce One Page Checkout (or similar use cases) in Version 2.1.0 (1816)

### ISSUE THREAD

**Issue by InpsydeNiklas** [woocommerce/woocommerce-paypal-payments#1454]
### Describe the Bug

We have encountered an issue related to the WooCommerce One Page Checkout plugin compatibility (added in #356) with the update 2.1.0. 
The problems observed include (but may not be limited to):

- The "Place Order" button, as well as the smart buttons, are being displayed in the PayPal gateway on the one-page checkout pages.
- The Advanced Card Processing (ACDC) gateway fails to load on the one-page checkout pages.

Similar issues may occur when using version 2.1.0 with other third-party plugins that implement the checkout gateways on non-checkout pages (e.g. single product page).

### To Reproduce

1. Install PayPal Payments 2.1.0
2. Enable the Advanced Card Processing feature.
3. Install the [WooCommerce One Page Checkout plugin](https://woocommerce.com/products/woocommerce-one-page-checkout/).
4. Create a new product and enable the "One Page Checkout" attribute (found next to the virtual/downloadable options).
5. Visit the product page that you just created.

Observed Behavior:
### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/f28a269a-f5ec-44a0-8618-a7259dcb290b)

### Expected Behavior

- The "Place Order" button should not load for the PayPal gateway on this page.
- If enabled, the Advanced Card Processing gateway should appear on the page.

### Actual Behavior

1. Both PayPal smart buttons and the "Place Order" button appear on the page in the PayPal gateway.
2. The Advanced Card Processing gateway does not load at all.

### Environment

 - WordPress Version: n/a
 - WooCommerce Version: n/a
 - Plugin Version: 2.1.0
 - Any other plugins installed: [WooCommerce One Page Checkout](https://woocommerce.com/products/woocommerce-one-page-checkout/)

**Comment by surflibre** [comment]
Hi,

My installed modules:   WooCommerce Bookings + WooCommerce One Page Checkout 2.4.0

Since version 2.1.0 the Paypal button no longer appears, only the order button by default, and when you validate with this button, an error message is displayed:
"Could not retrieve order."
The module works up to 2.0.5.

Is there a fix in progress?

Regards,

**Comment by magicoli** [comment]
This is not specific to WooCommerce One Page Checkout.

I experience the same issue with Paypal Payment 
- when adding [woocommerce_cart] and [woocommerce_checkout] on the same page
- with WooCommerce One Page Checkout
- with a couple of other One Page checkout plugins
