### ISSUE TITLE
Advanced card processing didn't work properly. Some days later it automatically disabled but it is showing enable 

### ISSUE THREAD

**Issue by Shahadot69** [woocommerce/woocommerce-paypal-payments#1455]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Shahadot69 

thank you for reaching out to us. You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The problem description is not complete, so please provide more details of the issue and the system report when you open a new support thread. The issue might be related to this thread: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1432

We will close this thread for now and wait for the support ticket you can open with us if you require additional support from us.

Kind regards, 
Joost
