### ISSUE TITLE
PayPal Smart Buttons don't show up when default currency is South African Rand

### ISSUE THREAD

**Issue by Ute11** [woocommerce/woocommerce-paypal-payments#1458]
### Describe the Bug

The PayPal Smart buttons don't show on the checkout page where it is enabled. I've consistently reproduced the issue when changing the default currency from USD/Euro where it works, to ZAR/South African Rand, where even the preview does not work. 

### To Reproduce

When I have the WooCommerce default currency set to ZAR (South African Rands) the smart buttons don't show - not even the preview. If I set it to Euro or USD, I can see the Smart Buttons.

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/137315529/8991f3bf-d590-46af-9c02-6f7a8bac7645)

### Expected Behavior

I assume PayPal works for all currencies, including ZAR?

### Actual Behavior

No smart buttons show on the checkout page

### Environment

All plugins and WordPress are the latest versions as of 21 June 2023
 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser Brave and Version
 - Any other plugins installed - 
 - Related plugins: I had CURCY - Multi Currency for WooCommerce and WooCommerce Payfast Gateway installed, but both are currently uninstalled as I was troubleshooting this issue. No other payment gateway plugin is active at the moment. 

### Additional Details

I noticed many issues have been raised regarding the smart button not showing, but no one mentioned the default currency issue. 
When I disable the smart buttons, I get an error message as per this screenshot
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/137315529/340810e9-8721-4f46-a4c7-17bdb4c81777)

<details><summary>System status</summary>

  ```
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Ute11 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Unfortunately, PayPal does not work with all currencies. If you look in the console (f12) and follow the error that is shown there, you will see this error:
`throw new Error("SDK Validation error: 'Invalid query value for currency: ZAR'" );`

[Here you can find a list of the currencies PayPal works with](https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/) and if you want to reach out to PayPal to find a solution for this, I would advise you to get in contact with [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) to find a solution.

Kind regards, 
Joost
