### ISSUE TITLE
Paypal fast payment allows you to add a product without selecting variables or options

### ISSUE THREAD

**Issue by Entregafas** [woocommerce/woocommerce-paypal-payments#1460]
### To Reproduce

1. Go to '[…](https://www.replacementlenses.net/product/compatible-ray-ban-4171-erika-replacement-lenses/)'
2. Click on 'Clear the size selection and pay by fast paypal' or o Do not select anything and pay by PayPal

**Comment by InpsydeNiklas** [comment]
Hi @Entregafas 
Normally, this behavior occurs in Chrome, but not in Firefox. 
But on your site, there may be a compatibility problem with the variation swatches.
In any case, the team is looking into improving the smart button behavior when no valid product variation was selected.

Can you please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your system report so this can be investigated deeper? Thanks!

**Comment by Entregafas** [comment]
Hi!

Thank you!

Yes

`
### WordPress Environment ###

WordPress address (URL): https://www.cristalesrepuesto.com
Site address (URL): https://www.cristalesrepuesto.com
WC Version: 7.8.0
REST API Version: ✔ 7.8.0
WC Blocks Version: ✔ 10.2.3
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 30000
cURL Version: 7.85.0
OpenSSL/3.0.8

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.0
WC Database Prefix: uyrawcTp
Tamaño total de la base de datos: 2733.12MB
Tamaño de los datos de la base de datos: 2112.35MB
Tamaño del índice de la base de datos: 620.77MB
uyrawcTpwoocommerce_sessions: Datos: 6.32MB + Índice: 0.14MB + Motor MyISAM
uyrawcTpwoocommerce_api_keys: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
uyrawcTpwoocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoocommerce_order_items: Datos: 10.43MB + Índice: 3.57MB + Motor MyISAM
uyrawcTpwoocommerce_order_itemmeta: Datos: 129.63MB + Índice: 38.38MB + Motor MyISAM
uyrawcTpwoocommerce_tax_rates: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
uyrawcTpwoocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoocommerce_shipping_zone_locations: Datos: 0.01MB + Índice: 0.01MB + Motor MyISAM
uyrawcTpwoocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoocommerce_payment_tokens: Datos: 0.06MB + Índice: 0.03MB + Motor MyISAM
uyrawcTpwoocommerce_payment_tokenmeta: Datos: 0.17MB + Índice: 0.14MB + Motor MyISAM
uyrawcTpwoocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpactionscheduler_actions: Datos: 35.93MB + Índice: 16.19MB + Motor MyISAM
uyrawcTpactionscheduler_claims: Datos: 0.08MB + Índice: 0.15MB + Motor MyISAM
uyrawcTpactionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
uyrawcTpactionscheduler_logs: Datos: 30.67MB + Índice: 23.71MB + Motor MyISAM
uyrawcTpcommentmeta: Datos: 0.74MB + Índice: 0.57MB + Motor MyISAM
uyrawcTpcomments: Datos: 47.46MB + Índice: 17.39MB + Motor MyISAM
uyrawcTpdgwt_wcas_index: Datos: 11.52MB + Índice: 0.47MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_de: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_en: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_es: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_fr: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_it: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_cache_pt_pt: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_de: Datos: 14.52MB + Índice: 20.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_en: Datos: 13.52MB + Índice: 19.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_es: Datos: 16.52MB + Índice: 20.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_fr: Datos: 13.52MB + Índice: 19.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_it: Datos: 13.52MB + Índice: 19.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_doclist_pt_pt: Datos: 13.52MB + Índice: 18.03MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_de: Datos: 0.42MB + Índice: 0.36MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_en: Datos: 0.42MB + Índice: 0.34MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_es: Datos: 0.41MB + Índice: 0.36MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_fr: Datos: 0.44MB + Índice: 0.36MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_it: Datos: 0.41MB + Índice: 0.36MB + Motor InnoDB
uyrawcTpdgwt_wcas_invindex_wordlist_pt_pt: Datos: 0.39MB + Índice: 0.36MB + Motor InnoDB
uyrawcTpdgwt_wcas_var_index: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
uyrawcTpicl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpicl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpicl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpicl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpicl_languages_translations: Datos: 0.19MB + Índice: 0.09MB + Motor InnoDB
uyrawcTpicl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpicl_mo_files_domains: Datos: 0.20MB + Índice: 0.06MB + Motor InnoDB
uyrawcTpicl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_strings: Datos: 11.82MB + Índice: 3.79MB + Motor MyISAM
uyrawcTpicl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_string_packages: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_string_pages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpicl_string_positions: Datos: 0.16MB + Índice: 0.05MB + Motor InnoDB
uyrawcTpicl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpicl_string_translations: Datos: 8.52MB + Índice: 4.03MB + Motor InnoDB
uyrawcTpicl_string_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpicl_translate: Datos: 198.78MB + Índice: 14.59MB + Motor MyISAM
uyrawcTpicl_translate_job: Datos: 2.52MB + Índice: 0.42MB + Motor InnoDB
uyrawcTpicl_translations: Datos: 11.52MB + Índice: 16.99MB + Motor MyISAM
uyrawcTpicl_translation_batches: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_translation_downloads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpicl_translation_status: Datos: 238.67MB + Índice: 3.71MB + Motor MyISAM
uyrawcTpimagify_files: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
uyrawcTpimagify_folders: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpimgoptimizations: Datos: 107.61MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpimgoptimizeractions: Datos: 11.52MB + Índice: 0.00MB + Motor InnoDB
uyrawcTplinks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpoptions: Datos: 54.11MB + Índice: 13.08MB + Motor InnoDB
uyrawcTppostmeta: Datos: 743.24MB + Índice: 216.22MB + Motor MyISAM
uyrawcTpposts: Datos: 189.28MB + Índice: 19.21MB + Motor MyISAM
uyrawcTprank_math_404_logs: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTprank_math_analytics_ga: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTprank_math_analytics_gsc: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTprank_math_analytics_inspections: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
uyrawcTprank_math_analytics_keyword_manager: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTprank_math_analytics_objects: Datos: 6.05MB + Índice: 1.78MB + Motor MyISAM
uyrawcTprank_math_internal_links: Datos: 1.13MB + Índice: 0.67MB + Motor MyISAM
uyrawcTprank_math_internal_meta: Datos: 0.32MB + Índice: 0.23MB + Motor MyISAM
uyrawcTprank_math_redirections: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTprank_math_redirections_cache: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpsbi_feeds: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpsbi_feed_caches: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpsbi_instagram_feeds_posts: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpsbi_instagram_feed_locator: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpsbi_instagram_posts: Datos: 0.50MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpsbi_sources: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTptermmeta: Datos: 2.79MB + Índice: 1.08MB + Motor MyISAM
uyrawcTpterms: Datos: 0.72MB + Índice: 0.97MB + Motor MyISAM
uyrawcTpterm_relationships: Datos: 6.53MB + Índice: 12.21MB + Motor MyISAM
uyrawcTpterm_taxonomy: Datos: 0.90MB + Índice: 0.73MB + Motor MyISAM
uyrawcTptm_taskmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTptm_tasks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpusermeta: Datos: 49.90MB + Índice: 25.48MB + Motor MyISAM
uyrawcTpusers: Datos: 3.05MB + Índice: 3.06MB + Motor MyISAM
uyrawcTpwc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpwc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpwc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpwc_customer_lookup: Datos: 4.27MB + Índice: 3.72MB + Motor MyISAM
uyrawcTpwc_download_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpwc_order_product_lookup: Datos: 5.32MB + Índice: 4.19MB + Motor MyISAM
uyrawcTpwc_order_stats: Datos: 3.91MB + Índice: 2.18MB + Motor MyISAM
uyrawcTpwc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpwc_product_attributes_lookup: Datos: 15.56MB + Índice: 12.55MB + Motor InnoDB
uyrawcTpwc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpwc_product_meta_lookup: Datos: 6.92MB + Índice: 7.86MB + Motor MyISAM
uyrawcTpwc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
uyrawcTpwc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
uyrawcTpwc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
uyrawcTpwoobe_history: Datos: 20.52MB + Índice: 0.61MB + Motor InnoDB
uyrawcTpwoobe_history_bulk: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
uyrawcTpwoocommerce_exported_csv_items: Datos: 23.18MB + Índice: 0.35MB + Motor MyISAM
uyrawcTpwoo_sales_country_region: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpwoo_shippment_provider: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpwpfm_backup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
uyrawcTpwpr_rocket_cache: Datos: 7.50MB + Índice: 10.44MB + Motor InnoDB
uyrawcTpwpr_rucss_used_css: Datos: 13.47MB + Índice: 21.33MB + Motor InnoDB

### Post Type Counts ###

aoc_popup: 1
attachment: 106370
ct_ugdpr_service: 1
custom_css: 4
customize_changeset: 1
is_search_form: 1
mc4wp-form: 1
nav_menu_item: 676
oembed_cache: 83
order_status: 30
page: 100
polylang_mo: 2
popup: 8
popup_theme: 8
portfolio_project: 8
post: 323
product: 15604
product_variation: 80430
revision: 62
shop_coupon: 14
shop_order: 49790
shop_order_refund: 674
snp_mail_log: 10917
snp_popups: 1
tm_global_cp: 7
vpc-config: 1
wapf_product: 235
wc_custom_statuses: 2
wc_order_email: 7
wc_order_status: 23
woo_mb_template: 20
wp_block: 3
wp_global_styles: 1
wpcode: 2
yaymail_template: 162

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

WPML Multilingual CMS: por OnTheGoSystems – 4.6.4
WPML SEO: por OnTheGoSystems – 2.1.0
PW Advanced WooCommerce Order Status & Actions Manager: por Proword – 2.2
Advanced Product Fields Pro for WooCommerce: por StudioWombat – 2.7.1
FiboSearch - AJAX Search for WooCommerce (Pro): por Equipo de FiboSearch – 1.24.0
Custom Order Status Manager for WooCommerce: por Bright Plugins – 1.0
GTM4WP: por Thomas Geiger – 1.16.2
Envato Market: por Envato – 2.0.8
Flexible Shipping: por WP Desk – 3.16.5
Homepage Control: por WooThemes – 2.0.3
Imagify: por Imagify – Optimize Images & Convert WebP – 2.1.1
WPCode Lite: por WPCode – 2.0.12
Smash Balloon Instagram Feed: por Smash Balloon – 6.1.4
KP Fastest Tidio Chat: por Kreativo Pro – 1.0.4
Product Variations Swatches for WooCommerce: por VillaTheme – 1.0.10
Rank Math SEO PRO: por Rank Math – 3.0.35
Rank Math SEO: por Rank Math – 1.0.117.1
Shortcode in Menus: por Gagan Deep Singh – 3.5.1
Storefront Blog Customiser: por WooCommerce – 1.3.0
Storefront Designer: por WooThemes – 1.8.4
Storefront Powerpack: por WooCommerce – 1.6.2
Tidio Chat: por Tidio Ltd. – 6.0.8
Trustpilot-reviews: por Trustpilot – 2.5.914
Video PopUp: por Alobaidi – 1.1.3
Advanced Order Export For WooCommerce: por AlgolPlus – 3.4.0
WooCommerce Redsys Gateway Light: por José Conti – 5.2.1
ASM Envíos para WooCommerce: por ASM – 1.9.14
ASM Valora para WooCommerce: por ASM – 1.9.14
BEAR - Bulk Editor and Products Manager: por realmag777 – 2.0.8.1
WOOCS - WooCommerce Currency Switcher: por realmag777 – 2.3.9.4
WooCommerce Stripe Gateway: por WooCommerce – 7.4.1
WooCommerce Multilingual & Multicurrency: por OnTheGoSystems – 5.2.0
WooCommerce PayPal Payments: por WooCommerce – 2.1.0
WooCommerce Shipping Tracking: por Lagudi Domenico – 35.8
WooCommerce: por Automattic – 7.8.0
WP Rocket: por WP Media – 3.14
WPML Media: por OnTheGoSystems – 2.7.3
WPML String Translation: por OnTheGoSystems – 3.2.6

### Inactive Plugins (3) ###

Cloudflare: por Cloudflare
Inc. – 4.12.0

WP Rollback: por GiveWP.com – 1.7.3
Yoast Duplicate Post: por Enrico Battocchi & Team Yoast – 4.5

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

WC Custom Email Templates: por Sunny – 1.0.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: braintree-variable-subscription (braintree-variable-subscription)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock-en)
outofstock (outofstock)
outofstock (outofstock-pt-pt)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5-pt-pt)
rated-5 (rated-5)
rated-5 (rated-5-en)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Base de la tienda: #4373 - /tienda/
Carrito: #4367 - /cart/
Finalizar compra: #4365 - /checkout/
Mi cuenta: #4371 - /mi-cuenta/
Términos y condiciones: #2470 - /term-conditions/

### Theme ###

Name: Storefront Child
Version: 1.1.20
Author URL: https://github.com/wpwebguru
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 4.3.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: La  version 3.4.0 de storefront-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php está obsoleta. La versión del núcleo es la 7.0.1
La  version 3.5.1 de storefront-child/woocommerce/single-product/product-image.php está obsoleta. La versión del núcleo es la 7.8.0

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: ES
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-06-22 11:00:55 +02:00
Options: ✔
Notes: 18
Onboarding: completed

### Action Scheduler ###

Complete: 49.920
Oldest: 2023-05-22 12:47:14 +0200
Newest: 2023-06-22 12:46:38 +0200

Failed: 5.881
Oldest: 2022-09-24 12:11:24 +0200
Newest: 2023-05-24 23:13:09 +0200

Pending: 4
Oldest: 2023-06-22 12:46:59 +0200
Newest: 2023-07-09 02:05:52 +0200


### Status report information ###

Generated at: 2023-06-22 12:46:54 +02:00
`

**Comment by InpsydeNiklas** [comment]
@Entregafas Can you please check if the behavior persists for you when you disable the plugin `Product Variations Swatches for WooCommerce: por VillaTheme` and try it with the Firefox browser? This plugin may impact the behavior.
In a standard setup without this plugin, we can reproduce the PayPal button not disappearing when clearing the variation selection, but only with the Chrome browser.
If the behavior changes with this plugin disabled, please send the support team a message with a copy of the plugin from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!

**Comment by InpsydeNiklas** [comment]
This should no longer be a problem in the latest version 2.2.0. Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) If any troubles persist. Thanks!
