### ISSUE TITLE
Advanced Card Processing w/ Checkout Blocks support

### ISSUE THREAD

**Issue by ethanclevenger91** [woocommerce/woocommerce-paypal-payments#1462]
#211 was closed, but I think this gives the wrong idea around compatibility between this plugin and the WooCommerce block-driven checkout experience.

You can, as of 2.1.0, add PayPal buttons in the block checkout. You _cannot_ take cards directly on your site (Advanced Card Processing), which was my primary want from this ticket. I've always found that sending folks to a third-party site for payment feels cheap.

Opening this ticket as a place to centralize updates from the dev team around this feature, and so that folks looking for more information on this issue get some kind of explicit information about the current status of that feature rather than sifting through the somewhat misleading information provided when #211 was closed.

**Comment by raifd** [comment]
@ethanclevenger91 Not sure if related but here is a weird behavior I came across. Unless all options are selected on the **Smart Button Locations**, PayPal will not display in the checkout block and we see an error saying that it is not compatible with the block: https://d.pr/i/55gdiV

Is this something you are aware of? Worth a new issue maybe?
Thank you!

**Comment by InpsydeNiklas** [comment]
@raifd Currently, the PayPal express buttons and checkout gateway with "Proceed to PayPal" button will only appear on the **Checkout block** when specifically the "Express Checkout" location is enabled:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/c98dbce6-4329-408d-a0cf-a2f1a63dc243)
If this location was not added, the PayPal gateway will not declare itself to be compatible with the Checkout block. This may change in the future, but it is unrelated to the missing Advanced Card Processing integration mentioned in this issue.

As a brief status update, the Advanced Card Processing integration for the Checkout block is being developed. We hope to be able to release it sometime in Q2, if all goes well.

**Comment by raifd** [comment]
Thank you for the additional details and the clarification @InpsydeNiklas

**Comment by InpsydeNiklas** [comment]
Hi @ethanclevenger91, FYI Advanced Card Processing support for the Checkout block was added for the upcoming [2.8.0 update](https://github.com/woocommerce/woocommerce-paypal-payments/releases).
