### ISSUE TITLE
Fatal Error | Admin side order list not displaying (1675)

### ISSUE THREAD

**Issue by vkharche** [woocommerce/woocommerce-paypal-payments#1466]
### Describe the Bug
Fatal error: Uncaught Error: WooCommerce\PayPalCommerce\WcGateway\Admin\OrderTablePaymentStatusColumn::render(): Argument #1 ($column) must be of type string, int given, called in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php on line 618
in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Admin/OrderTablePaymentStatusColumn.php on line 74

Call stack:

WooCommerce\P\W\A\OrderTablePaymentStatusColumn::render()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php:618
WooCommerce\P\W\WCGatewayModule::WooCommerce\P\W\{closure}()
wp-includes/class-wp-hook.php:308
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:332
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-admin/includes/class-wp-posts-list-table.php:1363
WP_Posts_List_Table::column_default()
wp-admin/includes/class-wp-list-table.php:1532
WP_List_Table::single_row_columns()
wp-admin/includes/class-wp-posts-list-table.php:1397
WP_Posts_List_Table::single_row()
wp-admin/includes/class-wp-posts-list-table.php:807
WP_Posts_List_Table::_display_rows()
wp-admin/includes/class-wp-posts-list-table.php:783
WP_Posts_List_Table::display_rows()
wp-admin/includes/class-wp-list-table.php:1444
WP_List_Table::display_rows_or_placeholder()
wp-admin/includes/class-wp-list-table.php:1371
WP_List_Table::display()
wp-admin/edit.php:487

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version - 6.2.2
 - WooCommerce Version - 7.7.2
 - Plugin Version - 2.1.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @vkharche 

This issue is already known with us and is being worked via the linked PR. Please review this and see if that helps you. You could try to adjust the code that was change in that PR to verify the fix at this moment. Please use the linked PR if you have any feedback for us, or open a new support thread if you require further assistance via [this link](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). We will close this thread.

Kind regards, 
Joost
