### ISSUE TITLE
Release 1.3.0 - Vaulting issues

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#147]
1. If vaulting is disabled for PayPal Checkout but enabled for DCC, the scripts are loaded with `vault=true`. I'm not sure if there's something we can technically do about the checkout page given the script is only loaded once despite both gateways being shown, but that's not true for the single product page or the cart page where DCC isn't shown.

   I understand this could add unnecessary complexity to the code, but we should definitely do something to handle conflicting settings (vaulting on for a gateway, disabled for the other). I wouldn't oppose making it clear on the settings page that vaulting settings affect both gateways (and forcefully set the relevant options), unless you have a better idea @Dinamiko.
   
   @mattallan: thoughts?
2. Similar to the above, on the Checkout page, if "Allow Registered Buyers to Save Credit Card" (DCC) is enabled but "Allow Registered Buyers to Save PayPal Account" (PayPal Checkout) is unchecked, `data-client-token` is still set on the `<script>` tag. This means the PayPal account gets vaulted, despite the option value.

   Again, if conflicting settings are not possible, we should clearly indicate that somehow.
3. `vault=true` in the SDK args seems to be required for vaulting PayPal accounts. Vaulting of cards in DCC does work even when `vault=false` in the SDK args. Because of this, I believe both vaulting settings (at least for PayPal Checkout) should be connected i.e. you shouldn't be able to check off "Allow Registered Buyers to Save PayPal Account" unless "Enable Vaulting for PayPal Accounts" is also checked off.
4. The gateways report Subscriptions support if vaulting is enabled but the check doesn't consider whether the gateway is disabled or not. For instance, if vaulting is enabled for DCC but DCC is disabled, PayPal will still report it supports subscriptions even if PayPal Checkout's vaulting settings are all turned off.
   This is particularly problematic on the frontend because it allows subscription products to be added to the cart and even go as far as the Checkout page just to find no way to really pay (no buttons are loaded) and the "Sign Up Now" button doesn't work.
5. Also, that vaulting is enabled is not the only requisite to be able to pay for a subscription on the frontend. For instance, if saving of accounts/cards is not enabled, `vault=true` itself doesn't guarantee that the user has a token we can use and so you'd end up paying for a subscription that can't be renewed automatically.
6. Because of all of the above, I'm wondering whether the vaulting + saving should be just one setting: for PayPal accounts saving requires `vault=true` anyway and `vault=true` with no tokens and no way to save one doesn't really imply Subscriptions support. I understand keeping the settings separate gives more flexibility, but at the same time makes things more complicated. @Dinamiko: Do you think there's a valid use case for `vault=true` with no way to actually save cards or accounts? @mattallan: thoughts?
4. Given the vaulting features can only be added to a merchant's account via onboarding, all vaulting-related options in the plugin should remain turned off (and `disabled`) until the merchant has the relevant scopes in their access token (`https://uri.paypal.com/services/vault/payment-tokens/readwrite` for instance). Until that happens, we should point merchants to the onboarding via a note around the settings or something.

**Comment by Dinamiko** [comment]
Hi @jorgeatorres,

We have consolidated all Vaulting settings in one single one that is shared between both gateways, that would fix the incompatibility problems. The setting is disabled by default.

Regarding point 4, I´ve added a check for payment gateway enabled, it should now not display Subscription support when gateways are not enabled.

**Comment by jorgeatorres** [comment]
@Dinamiko: Thanks for all your hard work on this! Did you include something for 7? I can't find anything in the code.

**Comment by jorgeatorres** [comment]
> Regarding point 4, I´ve added a check for payment gateway enabled, it should now not display Subscription support when gateways are not enabled.

Thanks. Works great now. ~Related to this, do you know why is it that we _require_ PayPal Checkout to be enabled to use DCC? Was that a requirement at some point? Unless I'm missing something it should be possible to use DCC without PayPal Checkout. Not a blocker for this release, of course. Please let me know whether I should open an issue about this.~ (I received confirmation this is a requirement from PayPal)

- - -

I can confirm everything in this issue has been addressed, with the sole exception of (7). The idea behind (7) was that we don't allow merchants to enable vaulting (and with it, Subscriptions support) unless they really can use vaulting features with their account. I see you've added a message to the checkbox, but that doesn't really prevent them from checking it off.

Whether vaulting features are available can be guessed from the `scope` when obtaining an access token (/v1/oauth2/token). Example:

> {
>   "scope": "https://uri.paypal.com/services/invoicing https://uri.paypal.com/services/vault/payment-tokens/read https://uri.paypal.com/services/disputes/read-buyer https://uri.paypal.com/services/payments/realtimepayment https://uri.paypal.com/services/disputes/update-seller https://uri.paypal.com/services/payments/payment/authcapture openid https://uri.paypal.com/services/disputes/read-seller Braintree:Vault https://uri.paypal.com/services/payments/refund https://api.paypal.com/v1/vault/credit-card https://api.paypal.com/v1/payments/.* https://uri.paypal.com/services/reporting/search/read https://uri.paypal.com/services/payments/initiatepayment https://uri.paypal.com/payments/payouts **https://uri.paypal.com/services/vault/payment-tokens/readwrite** https://api.paypal.com/v1/vault/credit-card/.* https://uri.paypal.com/services/subscriptions https://uri.paypal.com/services/applications/webhooks",
>   "access_token": "...",
>   "token_type": "Bearer",
>   ...
> }

If the vaulting features are not available, the Vaulting checkbox should probably remain entirely disabled. Would it be too difficult to add that check before the release?

**Comment by Dinamiko** [comment]
Hi @jorgeatorres, 

We´ve took a look but we´ll need time to properly implement and test it, is not possible to include it in this release.

**Comment by jorgeatorres** [comment]
@Dinamiko: I've moved (7) above to its own separate issue (#151). I'm going to close this one now. Thanks!
