### ISSUE TITLE
can't find the fill the token open in paypal wordpress dashboard 

### ISSUE THREAD

**Issue by Rishabh1831** [woocommerce/woocommerce-paypal-payments#1475]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi there, 
We notice that you've run into an issue, though from the title, we aren't fully certain about the specifics of the problem. To ensure you receive the most accurate and helpful guidance, we encourage you to reach out directly to our expert support team. Please use this [link](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) to get in touch.

Rest assured, our team is happy to assist you through any difficulties you may be encountering. We look forward to hearing from you. Thank you!
