### ISSUE TITLE
Paypal buttons disappear when the standard basket button is activated

### ISSUE THREAD

**Issue by laeti-uxui** [woocommerce/woocommerce-paypal-payments#1479]
### To Reproduce

1. Go to 'Woocommerce'
2. Click on 'Payments then on All Payment methods'
3. Scroll down to Paypal and activate it with Standard cart button'
4. Go to the checkout page
5. See error

### Screenshots

https://we.tl/t-bnDifDJXvC

### Expected Behavior

Normally, the PayPal buttons should appear when you click on PayPal, as well as the fields for entering your credit card when you click on credit card and, finally, the button for finalising your order.
 
### Actual Behavior

When the page reloads, the buttons appear and disappear just as quickly.

### Environment

 - WordPress Version : 6.2.2
 - WooCommerce Version : Version 7.8.1
 - Plugin Version : WooCommerce Payments | Version 6.1.1 / WooCommerce PayPal Payments | Version 2.1.0 / 
 - Browser [e.g. Chrome, Safari] and Version : Chrome 114.0.5735.198
 - Any other plugins installed :  Elementor | Version 3.14.1 / Elementor Addon Elements | Version 1.12.3 / Elementor Pro | Version 3.14.1 / Cart Notices for WooCommerce | Version 3.5.7.7

### Additional Details

<details><summary>System status</summary>

`
### wp-core ###

version: 6.2.2
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2326
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/drbm4231/public_html
wordpress_size: 20,40 Go (21903227647 bytes)
uploads_path: /home/drbm4231/public_html/wp-content/uploads
uploads_size: 3,91 Go (4193870530 bytes)
themes_path: /home/drbm4231/public_html/wp-content/themes
themes_size: 21,69 Mo (22740896 bytes)
plugins_path: /home/drbm4231/public_html/wp-content/plugins
plugins_size: 325,00 Mo (340790173 bytes)
database_size: 219,24 Mo (229885046 bytes)
total_size: 24,86 Go (26690514292 bytes)

### wp-active-theme ###

name: Atelier (atelier)
version: 2.9.2
author: Swift Ideas
author_website: http://www.swiftideas.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, structured-post-formats, post-formats, automatic-feed-links, title-tag, custom-logo, custom-background, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, swiftframework, widgets, menus, editor-style
theme_path: /home/drbm4231/public_html/wp-content/themes/atelier
auto_update: Désactivé

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.1, author: L’équipe WordPress, Mises à jour auto désactivées

### wp-mu-plugins (1) ###

ManageWP - Worker Loader: author: GoDaddy, version: (undefined)

### wp-plugins-active (42) ###

Advanced Order Export For WooCommerce (Pro): version: 3.4.1, author: AlgolPlus, Mises à jour auto désactivées
Akismet Anti-Spam: Spam Protection: version: 5.2, author: Automattic - Anti Spam Team, Mises à jour auto désactivées
All In One WP Security: version: 5.1.9, author: All In One WP Security & Firewall Team, Mises à jour auto désactivées
Breadcrumb NavXT: version: 7.2.0, author: John Havlik, Mises à jour auto désactivées
Cart Notices for WooCommerce: version: 3.5.7.7, author: BeRocket, Mises à jour auto désactivées
Classic Editor: version: 1.6.3, author: WordPress Contributors, Mises à jour auto désactivées
Contact Form 7: version: 5.7.7, author: Takayuki Miyoshi, Mises à jour auto désactivées
CookieYes | GDPR Cookie Consent: version: 3.1.1, author: CookieYes, Mises à jour auto désactivées
Elementor: version: 3.14.1, author: Elementor.com, Mises à jour auto désactivées
Elementor Addon Elements: version: 1.12.3, author: WPVibes, Mises à jour auto désactivées
Elementor Header & Footer Builder: version: 1.6.14, author: Brainstorm Force, Nikhil Chavan, Mises à jour auto désactivées
Elementor Pro: version: 3.14.1, author: Elementor.com, Mises à jour auto désactivées
Envato Market: version: 2.0.8, author: Envato, Mises à jour auto désactivées
Essential Addons for Elementor: version: 5.8.0, author: WPDeveloper, Mises à jour auto désactivées
Facebook for WooCommerce: version: 3.0.26, author: Facebook, Mises à jour auto désactivées
Gift Up!: version: 2.19.2, author: Gift Up!, Mises à jour auto désactivées
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: version: 10.1.24, author: HubSpot, Mises à jour auto désactivées
Jetpack: version: 12.2.1, author: Automattic, Mises à jour auto désactivées
Klaviyo: version: 3.1.0, author: Klaviyo, Inc., Mises à jour auto désactivées
Livemesh Addons for Elementor: version: 7.8, author: Livemesh, Mises à jour auto désactivées
Loco Translate: version: 2.6.4, author: Tim Whitlock, Mises à jour auto désactivées
ManageWP - Worker: version: 4.9.17, author: GoDaddy, Mises à jour auto désactivées
Media Library Folders Reset: version: 8.0.7, author: Max Foundry, Mises à jour auto désactivées
Meta Box: version: 5.7.3, author: MetaBox.io, Mises à jour auto désactivées
Meta pixel for WordPress: version: 3.0.12, author: Facebook, Mises à jour auto désactivées
oAuth Twitter Feed for Developers: version: 2.3.0, author: Liam Gladdy (Storm Consultancy), Mises à jour auto désactivées
One Click Demo Import: version: 3.1.2, author: OCDI, Mises à jour auto désactivées
PDF Invoices & Packing Slips for WooCommerce: version: 3.5.6, author: WP Overnight, Mises à jour auto désactivées
Product Feed PRO for WooCommerce: version: 12.7.8, author: AdTribes.io, Mises à jour auto désactivées
Redux Framework: version: 4.4.1, author: Team Redux (latest version: 4.4.3), Mises à jour auto désactivées
Table Rate Shipping for WooCommerce: version: 2.28, author: JEM Plugins, Mises à jour auto désactivées
UpdraftPlus - Backup/Restore: version: 1.23.6, author: UpdraftPlus.Com, DavidAnderson, Mises à jour auto désactivées
WooCommerce: version: 7.8.1, author: Automattic, Mises à jour auto désactivées
WooCommerce Advanced Free Shipping: version: 1.1.5, author: Jeroen Sormani, Mises à jour auto désactivées
WooCommerce Payments: version: 6.1.1, author: Automattic, Mises à jour auto désactivées
WooCommerce PayPal Payments: version: 2.1.0, author: WooCommerce, Mises à jour auto désactivées
WooCommerce Quickview: version: 3.4.5, author: Iconic, Mises à jour auto désactivées
WooCommerce Shipping & Tax: version: 2.2.5, author: WooCommerce, Mises à jour auto désactivées
WooCommerce Smart Coupons: version: 8.1.0, author: StoreApps, Mises à jour auto désactivées
YITH WooCommerce Coupon Email System Premium: version: 1.28.0, author: YITH, Mises à jour auto désactivées
YITH WooCommerce Wishlist: version: 3.22.0, author: YITH, Mises à jour auto désactivées
Yoast Duplicate Post: version: 4.5, author: Enrico Battocchi & Team Yoast, Mises à jour auto désactivées

### wp-plugins-inactive (8) ###

Colissimo shipping methods for WooCommerce: version: 1.8.1, author: Colissimo, Mises à jour auto activées
GTM4WP: version: 1.16.2, author: Thomas Geiger, Mises à jour auto désactivées
Media Library Folders: version: 8.0.7, author: Max Foundry, Mises à jour auto désactivées
NavMenu Addon For Elementor: version: 1.1.6, author: ThemeIsle, Mises à jour auto désactivées
Really Simple SSL: version: 7.0.5, author: Really Simple Plugins, Mises à jour auto désactivées
WooCommerce Colissimo Shipping Rates: version: 1.1.9, author: WooCommerce (latest version: 1.2.0), Mises à jour auto désactivées
WooCommerce Dynamic Pricing & Discounts: version: 2.3.9, author: RightPress, Mises à jour auto désactivées
WooCommerce PayPal Checkout Gateway: version: 2.1.3, author: WooCommerce, Mises à jour auto désactivées

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Non disponible
imagemagick_version: Non disponible
imagick_version: Non disponible
file_uploads: File uploads is turned off
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 Mo
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64 x86_64
httpd_software: Apache
php_version: 7.4.33 64bit
php_sapi: litespeed
max_input_variables: 2000000
time_limit: 360
memory_limit: 4096M
max_input_time: 360
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 8.1.2 OpenSSL/1.1.1u
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.6.14-MariaDB
client_version: mysqlnd 7.4.33
max_allowed_packet: 268435456
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/drbm4231/public_html/wp-content
WP_PLUGIN_DIR: /home/drbm4231/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 4096M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Indéfini
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
0: Writable

### redux-framework ###

version: 4.4.1
installation: plugin
data directory: /home/drbm4231/public_html/wp-content/plugins/redux-framework/redux-core/
browser: 
	Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
	Browser: Chrome
	Version: 114.0.0.0
	Platform: Apple

### redux-instance-sf_atelier_options ###

opt_name: sf_atelier_options
global_variable: sf_atelier_options
dev_mode: false
ajax_save: true
page_slug: _atelier_options
page_permissions: manage_options
menu_type: menu
page_parent: themes.php
compiler: true
output: true
output_tag: true
templates_path: undefined
extensions: 
	Accordion: 1.0.1
	Custom Fonts: 2.0.0
	Customizer: 4.0.0
	Datetime: 2.0.0
	Google Maps: 2.0.0
	Import Export: 4.0.0
	Js Button: 2.0.0
	Metaboxes: 4.0.0
	Multi Media: 4.4.1
	Options Object: 4.0.0
	Repeater: 4.3.7
	Search: 3.4.5
	Shortcodes: 4.3.5
	Social Profiles: 4.3.17
	Users: 4.4.1
	Widget Areas: 1.0.0

### jetpack ###

site_id: 171887171
ssl_cert: No
time_diff: undefined
version_option: 12.2.1:1688049556
old_version: 12.1.1:1685614024
public: Public
master_user: #4 atelier-admin
is_offline_mode: off
is_offline_mode_constant: off
current_user: #4 atelier-admin
tokens_set: Blog User
blog_token: Y3WqplmcjJOmNCew&DsNr(vPp(7OYY(@
user_token: bAwy3*ve3AkXz7oVeEAQ#6uh1v3zjbtF
version: 12.2.1
jp_plugin_dir: /home/drbm4231/public_html/wp-content/plugins/jetpack/
plan: free
protect_header: false
full_sync: {"started":"Mon, 21 Mar 2022 11:49:27 +0000","finished":"Mon, 21 Mar 2022 11:49:32 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"4"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[4],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/latelierdimages.fr","siteurl":"https:\/\/latelierdimages.fr","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

`

</details>

**Comment by laeti-uxui** [comment]
Same problem for other people here : https://wordpress.org/support/topic/paypal-checkout-buttons-missing/

**Comment by Sirvijver** [comment]
Hello @laeti-uxui 

Thank you for reaching out to us, we are here to help.
This issue is not related to the .org link you shared with us; that one is very old and related to an older plugin.

The Elementor Po compatibility we added in 2.1.0 seems to be causing more problems than it helped resolve. Specifically, the filter to change the Checkout render hook results in the PayPal buttons not rendering at all for certain themes. We have created a package that should resolve this issue for you, you can download it here: https://drive.google.com/uc?export=download&id=1bJXF41hA_HQAMgR-KqVmR3iUfQT2ao_7

If you have any more questions regarding this, please [open a support request here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), because we do not intend to use GitHub as a support platform. I will close this thread now.

Kind regards, 
Joost
