### ISSUE TITLE
Missing Payer Info for Guest Checkouts (137)

### ISSUE THREAD

**Issue by Rigby90** [woocommerce/woocommerce-paypal-payments#148]
We've encountered an issue where no payer information is sent across to PayPal for guest checkouts using DCC, even though the fields are filled in during checkout and stored against the WC Order itself.

After looking into the code I believe it's due to the payerData function below returning null, which is expected as there's no logged-in customer.

https://github.com/woocommerce/woocommerce-paypal-payments/blob/a1b41b9bbb1fbc524f8b7a08e8838842471ad44a/modules/ppcp-button/src/Assets/class-smartbutton.php#L633-L640

However, the null payer is then passed onto the below JS function which in turn does a null check and returns null, rather than falling back to utilising the user filled in fields.

https://github.com/woocommerce/woocommerce-paypal-payments/blob/a1b41b9bbb1fbc524f8b7a08e8838842471ad44a/modules/ppcp-button/resources/js/modules/Helper/PayerData.js#L3-L5

As a quick test, I removed the null check within PayerData.js and performed another guest checkout, the expected data is then sent across to PayPal using all the fields that were filled in during checkout exist within PayPal, rather than showing empty and the record showing against a random DCC generated email address.

Happy to assist with submitting a PR to resolve this, would just need some understanding on why it was implemented in this way as it looks like it was done to fall back on existing customer records in the event that the fields don't exist within the checkout?

**Comment by InpsydeNiklas** [comment]
This was fixed a while back already.
