### ISSUE TITLE
api.paypal.com does not work on Hetzner Cloud

### ISSUE THREAD

**Issue by xardit** [woocommerce/woocommerce-paypal-payments#1480]
### Describe the Bug

PayPal API url `api.paypal.com` from this wordpress extension does not work when I try to setup paypal on a Hetzner Cloud ubuntu server.

### To Reproduce

1. Try to activate PayPal or try manual setup with API keys for any sandbox or live account.
2. Site gets stuck on saving process and crashes with a 502 error
3. After it gets back online an error persists that it could not get the authenticated token.
4. The paypal settings page if it is opened it crashes the site again.

### Expected Behavior

Connect to the merchant account successfully 

### Actual Behavior

Site gets stuck on setup process and crashes with a 502 error. Sometimes when it comes back online on dashboard you get a `Could not get Token` message from the Woocommerce Paypal Plugin

### Environment

 - WordPress 6.2.2
 - WooCommerce 7.8.0
 - Plugin 2.1.0
 - Browser: Tried on Chrome + Safari + Edge + Firefox + Brave

### Discovery

* On the server I run ping with error: no ICMP response, just blank, not even timeout.
```
root@website:~# ping api.paypal.com
PING api.glb.paypal.com (173.0.84.66) 56(84) bytes of data.
^C
--- api.glb.paypal.com ping statistics ---
32 packets transmitted, 0 received, 100% packet loss, time 31729ms
```

* Testing it locally with success
```
C:\Users\Admin>ping api.paypal.com

Pinging api.glb.paypal.com [173.0.84.66] with 32 bytes of data:
Reply from 173.0.84.66: bytes=32 time=39ms TTL=50
Reply from 173.0.84.66: bytes=32 time=43ms TTL=50

Ping statistics for 173.0.84.66:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 39ms, Maximum = 43ms, Average = 41ms
```

* Testing locally API authentication with client id and secret using Postman with a successfully generated token. I tried both `api.paypal.com` and `api-m.paypal.com` with success.

* Conclusion is the hetzner network has some firewall filter or blackhole on the `api.paypal.com`

Note: I do not have any filters or firewalls, my setup is default.

### Temporary solution

As it appears the api url `api-m.paypal.com` is not filtered on hetzner network so we just need to change default `api.paypal.com` to `api-m.paypal.com`

Edit file `/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php` on line 24-25 and replace with those lines
```
define( 'PAYPAL_API_URL', 'https://api-m.paypal.com' );
define( 'PAYPAL_SANDBOX_API_URL', 'https://api-m.sandbox.paypal.com' );
```

After that you can connect your account successfully,

**This is very inconvenient and confusing because you can not see the error anywhere on any log on wordpress or php-fpm/nginx logs. The only error you see is the standard Wordpress Woocommerce Paypal error `Could not get Token`**

## Other steps I took

Reported this thread to hetzner team to investigate this issue.

**Comment by InpsydeNiklas** [comment]
Hi @a3diti 

We certainly do not recommend changing the PayPal API URL. But this sounds more like a hosting-related issue rather than a plugin issue, as you could reproduce the issue outside of the plugin.
We don't have a Hetzner Cloud environment available for testing, but we're not seeing any general issues with the PayPal API connection on the plugin level. So this is something for the Hetzner support to investigate for your case.

If any problems persist after consulting with the Hetzner support team, please please consider [reaching out to the PayPal Payments support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by bylmzio** [comment]
i reached out to paypal, because of the same issue i had.
The wrote me following:

```
The URL to the API service is either:

    Sandbox. https://api-m.sandbox.paypal.com/
    Live. https://api-m.paypal.com/

Please try modifying the endpoint URL of the requests and try again. We don't see this IP being blocked from our logs and I raised a request internally to check if there are any blocks.
```

After Modifying it, it worked very well.

**Comment by bylmzio** [comment]
i dont know, why paypal support tells me the correct URL is `https://api-m.paypal.com/` but it is not inside the list here
`https://www.paypal.com/us/cshelp/article/what-are-the-ip-addresses-for-paypal-servers-ts1056`

**Comment by InpsydeNiklas** [comment]
After consulting PayPal, it appears the `api-m` endpoint utilizes a more robust CDN and is the recommended endpoint for all REST API calls for a while already. So PayPal Payments will likely switch to this new endpoint in the next update. Thanks for the feedback!
