### ISSUE TITLE
Cannot do Payments by Paypal on web

### ISSUE THREAD

**Issue by TherPH55** [woocommerce/woocommerce-paypal-payments#1486]
### Describe the Bug

Some people tried to buy my courses by PayPal and could not do: tecnical error.

### To Reproduce

1. Add a product 
2. Fullfill the info required
3. Click on PayPal
4. Cannot proceed: "en estos

### ScreenshotsWe're having tecnical issues at this moment. Try it later"

![error paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/137761322/21cfb634-e3d6-4df9-9090-7630cd04fa7e)

### Expected Behavior: Alow my clients to buy

On 02/07/2023 I received last payment by paypal. Others failed

 - WordPress Version 6.2.2
 - WooCommerce Version Versión 7.8.2
 - Plugin Version Versión 2.1.0
 - Browser [e.g. Chrome, Safari] and Version Chrome, Safari, alll
 - Any other plugins installed WooCommerce Stripe Gateway

**Comment by Sirvijver** [comment]
Hello @TherPH55 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You have not provided enough details for us to give any response. The only thing that could have caused this (according to the details you have provided) is an outage on the PayPal server (not a plugin issue). These type of outages should be visible on this website: https://www.paypal-status.com/product/sandbox

If you believe this is a plugin issue, please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards, 
Joost
