### ISSUE TITLE
Woocommerce Paypal Plugin - Order Failed

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#1500]
when trying to place an order on my website, i get an email saying that the order failed.
I am using WooCommerce Version 7.8.2
I am using paypal plugin for woocommerce version 2.1.0

any ideas ?
kevin rea
lancaster, calif.

**Comment by Sirvijver** [comment]
Hello @kevinsrea 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We have no information to base our response on. We would need to know what you see in the logs (you need to activate logging in the plugin settings) and also the order notes will give us valuable information of what occurred with the transaction. It could be that there is a plugin conflict, and you can perform [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to verify this, but I can't really base my response on anything with the information you have provided.

I would advise you to open a new support thread via the link provided above with the request details, so our support team can take a closer look. This thread will be closed as explained above.

Kind regards, 
Joost
