### ISSUE TITLE
Paypal Payments serializing formData of array inputs (1873)

### ISSUE THREAD

**Issue by Josh-Millard** [woocommerce/woocommerce-paypal-payments#1501]
### Describe the Bug

My scenerio is I have a website that sells tickets through Woocommerce. On the Woocoommerce checkout page if the user is purchasing 3 tickets then 3 input boxes are generated such as:

```
<input type="text" name="ticket[name][]">
<input type="text" name="ticket[name][]">
<input type="text" name="ticket[name][]">
```

I have setup an action(_woocommerce_after_checkout_validation_) within Woocommerce to ensure that the name fields are required during checkout.

When I test the checkout process with just a standard Cash on Delivery method everything works as expected. 

When I try checking out with Woocommerce Paypal Payments my woocommerce_after_checkout_validation action is throwing an error.

This is my custom validation action:

```
function btd_custom_checkout_field_validation( $data, $errors ) {

    $ticket_names = ( isset( $_POST['ticket']['name'] ) ) ? $_POST['ticket']['name'] : false;

    if( $ticket_names ) {

        foreach( $ticket_names as $name ) {

            if( $name == "" ) {

                $errors->add( 'error', 'Please ensure all names are entered that will be attending the event. #1' );

                return;

            }

        }

    } else {

        $errors->add( 'error', 'Please ensure all names are entered that will be attending the event #2' );

    }

}
add_action( 'woocommerce_after_checkout_validation', 'btd_custom_checkout_field_validation', 10, 2 );
```

When I click the Paypal Button on checkout it throws the error 'Please ensure all names are entered that will be attending the event #2'.

This is because when wc-ajax=ppc-create-order is fired it seems that my input fields in HTML("ticket[name][]") is being serialized and not being taken into account that it is in array.

### Screenshots

<img width="1728" alt="nwe" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/84436732/de62e3e1-5637-4283-bffd-4a305599550b">

<img width="225" alt="Screenshot 2023-07-10 at 09 45 07" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/84436732/bd339bb6-413a-4234-a830-cd7b356e4c74">

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.8.2
 - WooCommerce Paypal Payments 2.1.0
 - Firefox

**Comment by InpsydeNiklas** [comment]
Hi @Josh-Millard 
If your Checkout page doesn't depend on a server-side validation before the PayPal popup opens, you could try it with the basic validation enabled instead of the early wc validation ([wiki link](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#checkout-form-field-validation-before-creating-the-paypal-order)):

```
add_filter( 'woocommerce_paypal_payments_early_wc_checkout_validation_enabled', '__return_false' );

add_filter( 'woocommerce_paypal_payments_basic_checkout_validation_enabled', '__return_true' );
```
This only checks via JavaScript if all required fields are populated before submission.

**Comment by Josh-Millard** [comment]
Thank you for this.

I cant see this in the documentation, I had no clue this even existed?

**Comment by InpsydeNiklas** [comment]
It's briefly mentioned in the plugin documentation, but developer-level information is primarily available here in the [GitHub wiki](https://github.com/woocommerce/woocommerce-paypal-payments/wiki). The plugin documentation is currently undergoing a rework to improve the structure.

In any case, the team will investigate the issue you reported, but we must ask for your understanding that it may take some time before the resources are available. So while it is not ideal, I hope the basic validation could be a viable workaround for you.

**Comment by Josh-Millard** [comment]
I didnt look at the wiki on here in all fairness, thank you for your reply.

**Comment by Josh-Millard** [comment]
I didnt look at the wiki on here in all fairness, thank you for your reply.
