### ISSUE TITLE
button check out

### ISSUE THREAD

**Issue by MIKEN320** [woocommerce/woocommerce-paypal-payments#1503]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @MIKEN320 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not really provide any details about the issue, so I can only advise you to open the support thread via the link provided above, and we can take a look and try to help you fix whatever issue you are facing.

Kind regards, 
Joost
