### ISSUE TITLE
remove paypal smart button woocommerce and show paypal iframe modal on place order button

### ISSUE THREAD

**Issue by tejas-elsner** [woocommerce/woocommerce-paypal-payments#1512]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Expected Behavior

I want to render paypal window on click of place order button
### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hello @tejas-elsner 
>I want to render paypal window on click of place order button

I'm afraid that's not possible as PayPal Payments is designed to replace the "Place order" button on the WooCommerce Checkout page.
If you don't want to present the PayPal smart buttons directly on your Checkout page, you could only create some workaround with custom code. For instance, something like [this oversimplified example](https://gist.github.com/InpsydeNiklas/bdbead04345aad83eb22e7b5e1f7919e) of creating a gateway that redirects the buyer to the Pay for order page to pay via PayPal after clicking the "Place order" button on the Checkout page.
But please keep in mind PayPal prefers to display the smart buttons directly on your Checkout page as the PayPal buttons are something users recognize and trust.

But for any questions regarding possible customizations, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
