### ISSUE TITLE
[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation.

### ISSUE THREAD

**Issue by thecowmilk** [woocommerce/woocommerce-paypal-payments#1516]
### Describe the Bug

After the plugin installation and setup with a business account, after every checkout I have an error from the Paypal plugin which is
```
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-COMPLIANCE_VIOLATION 
```

### To Reproduce

Install the plugin and set it up
Try to buy a product and insert your credit card information.
Click the pay button and wait for the error. 

### Expected Behavior

The payment should go through without any errors.

### Actual Behavior

```
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-COMPLIANCE_VIOLATION 
```

### Environment

 - WordPress Version: 6.2
 - WooCommerce Version: 7.9.0
 - Plugin Version: 2.2.0
 - Browser [e.g. Chrome, Safari] and Version: Mozilla and Chrome
 - Any other plugins installed: Yes but not related to payments.

**Comment by InpsydeNiklas** [comment]
Hi @thecowmilk, this is an issue with your PayPal account and not with the plugin. I suggest contacting [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) to clarify. 
If you need additional help setting up PayPal Payments, please [reach out to the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for more guidance. Thanks!
