### ISSUE TITLE
All PP payments stuck on pending payment since update

### ISSUE THREAD

**Issue by neotrope** [woocommerce/woocommerce-paypal-payments#1520]
### Describe the Bug

As of the version Version 2.2.0

all paypal payment stuck on pending payment and don't go to processing.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @neotrope 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities. I see you have opened [a .org thread](https://wordpress.org/support/topic/v2-2-0-all-pp-payments-stuck-on-pending-payment/) as well, so I will continue working with you via that engagement and see if we can find a solution for this. This GH thread will be closed now.

Kind regards, 
Joost
