### ISSUE TITLE
PayPal does not work

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#1524]
### Describe the Bug

I have a critical issue, PayPal buttons do not show at all in the store, even though I have it configured properly. When I save PayPal settings in the plugin, the buttons show for some time (and work) and then disappear again. On the cart screen there is never ending loader. It can all be seen on this loom: https://www.loom.com/share/a64ef921db354341a90ba7c62712b613?sid=97156d1e-91e1-4ee7-84e7-cc6ef1960aff

### To Reproduce

1. Go to any product page 
2. add to cart
3. got to checkout and choose the PayPal payment

### Expected Behavior

The buttons must show and work, as you can see they should be seen in 4 places , they do not appear anywhere 

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

Attached system report 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
[SystemStatusReport_behemoth-store.com_2023-07-19T21-29-32.txt](https://github.com/woocommerce/woocommerce-paypal-payments/files/12100289/SystemStatusReport_behemoth-store.com_2023-07-19T21-29-32.txt)

**Comment by Sirvijver** [comment]
Hello @behemothwebstore 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We have seen this issue before and will use this thread for any development activities when we have identified the issue for it. However, I would recommend you to open another thread with us (as advised above), so you can work with our support team to identify the cause of this issue. The system report did not reach us, so please add that with this engagement as well.

We just release version 2.2.0, so it might be related to this update. Did you already try to roll back to [version 2.1.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.1.0/woocommerce-paypal-payments.zip)? That could be a quick fix, until we find out what is causing this situation.

Pending your response (via the support interface).

Kind regards, 
Joost

**Comment by InpsydeNiklas** [comment]
Hi @behemothwebstore 
The PayPal script isn't loading because of your cookie consent plugin. I think you should contact the plugin author, as PayPal Payments appears to work as expected on your site.
For any further questions regarding PayPal Payments, please [contact the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
