### ISSUE TITLE
Automatic Refunds button not showing on refund 

### ISSUE THREAD

**Issue by Hitanmaster** [woocommerce/woocommerce-paypal-payments#1526]
### To Reproduce

1. Go to 'woocommerce'
2. Click on 'orders'
3. select the order 
4. Scroll down to refund
5. there is only manual login buttion

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/103843176/8807aa14-354b-4d56-8c76-a072aa7ecd7b)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Hitanmaster 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

From the details that we have received, there is not so much we can tell about this situation. Are you sure this was paid via PayPal? It would be good to see the entire order and get more details on it.
We have not seen this issue recently, so we would have to take a closer look if we are to give you a proper response. If you require our support, please open a support thread via the link provided above.

Kind regards, 
Joost
