### ISSUE TITLE
Creating a refund overwrites transaction_id

### ISSUE THREAD

**Issue by mathe42** [woocommerce/woocommerce-paypal-payments#1527]
### Describe the Bug

When a order is refunded the transaction_id of the order is overwritten. Therefore there is no way to get the transaction_id of the sale for a refunded order (over the REST-API). 

This is needed generate booking data for tax reasons.

### To Reproduce

1. Create a Order and pay with paypal
2. Refund that order
3. Check transaction_id in order data

### Screenshots

N/A

### Expected Behavior

A way to get the transaction_id from the sale after the refund is created.

### Actual Behavior

No way to get the transaction_id from the sale after the refund is created.

### Environment

 - WordPress Version: any
 - WooCommerce Version: any
 - Plugin Version: current
 - Browser [e.g. Chrome, Safari] and Version: any
 - Any other plugins installed: not relevant

### Additional Details

We have seen this behaviour with a lot of woocomerce shops. Our company generates booking data for tax consultants and we need this to match the payment (here paypal) to the sale / refund.

**Comment by Sirvijver** [comment]
Hello @mathe42 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have tested a refund and see that the Transaction ID that you find in the top of the order overview is not changed. Only when you go into the PayPal transaction overview and go into the details of the refund, you can find the transaction ID of the refund. So in my test, there was no indication that the transaction ID was replaced; instead we see that another Transaction ID is generated by PayPal for the refund.

If you see any issue with this, please raise a support request for us to take a closer look at this, but this seems to be working as intended at the moment.

Kind regards, 
Joost
