### ISSUE TITLE
Paypal payment on woocommerce

### ISSUE THREAD

**Issue by santepied** [woocommerce/woocommerce-paypal-payments#1531]
### Describe the Bug

I am an e-commerce on woocommerce. I put a payment solution for my customers. Since yesterday the solution does not work anymore. It shows an error message and my clients have the same. I can't find the solution.
The order is getting failed and I have lost 10 groins since yesterday. Thank you for your help

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

 ![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/140241762/5629c041-ba1a-4c61-96f7-c1015e955dbe)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @santepied 
This looks like an error in the PayPal system and not with the PayPal Payments plugin directly.
In any case, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance as GitHub is not the right place for this. Thanks!
