### ISSUE TITLE
Paypal Button is hidden on the checkout page.

### ISSUE THREAD

**Issue by myithubau** [woocommerce/woocommerce-paypal-payments#1532]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

![Screenshot 2023-07-24 134548](https://github.com/woocommerce/woocommerce-paypal-payments/assets/140366449/7d85d07a-cc3a-4b45-9af0-6e4c935071b0)

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by myithubau** [comment]
Please rectify issue in order to start using your Paypal plugin.

**Comment by InpsydeNiklas** [comment]
Hi @myithubau 
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need any assistance. Thanks!
