### ISSUE TITLE
No order details or delivery informations in WC after order payed with Paypal

### ISSUE THREAD

**Issue by RomainLaf** [woocommerce/woocommerce-paypal-payments#1534]
### Describe the Bug

It's the second time this bug appeared. A customer pay for an order and then I have no informations at all in WC admin order detail page. So I don't even know where to deliver the order. 

Paypal have all the informations about the customer's details, but WC don't. Here's a screenshot for WC Order detail page : https://share.cleanshot.com/FrJDqd9j  

### To Reproduce

I don't know how to reproduce this issue because it should be impossible to click on any payement gateway button on checkout page without filling delivery fields. So I don't know how the issue appear. Does the user have fill all the delivery fields informations, then clicked on Paypal button, then all the fields emptied ? 

### Screenshots

https://share.cleanshot.com/FrJDqd9j  

### Expected Behavior

Customer add product to cart, fill the checkout fields (delivery details), then click on paypal button, pay and the the order is recieved in backend WC Order detail page and I have all the informations about the customer.

### Environment

 - WordPress Version : 6.2.2
 - WooCommerce Version : 7.9.0
 - Paypal Gateway : 2.2.0
 - Stipe Gateway : 7.4.1

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://iconicfootballshop.com
Site address (URL): https://iconicfootballshop.com
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 360
PHP Max Input Vars: 250000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.14-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: ifs_
Total Database Size: 286.98MB
Database Data Size: 244.52MB
Database Index Size: 42.46MB
ifs_woocommerce_sessions: Data: 63.18MB + Index: 2.66MB + Engine MyISAM
ifs_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB + Engine MyISAM
ifs_woocommerce_order_itemmeta: Data: 0.54MB + Index: 0.38MB + Engine MyISAM
ifs_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_actionscheduler_actions: Data: 0.69MB + Index: 0.43MB + Engine MyISAM
ifs_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_actionscheduler_logs: Data: 2.34MB + Index: 1.63MB + Engine MyISAM
ifs_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_cmplz_cookies: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ifs_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_comments: Data: 0.29MB + Index: 0.13MB + Engine MyISAM
ifs_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
ifs_gla_merchant_issues: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
ifs_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ifs_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ifs_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ifs_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_forms: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_mapping_to_external_entities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_newsletters: Data: 0.13MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_newsletter_links: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_newsletter_templates: Data: 3.05MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_scheduled_tasks: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_segments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_sending_queues: Data: 0.34MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_settings: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_bounces: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_subscribers: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
ifs_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_user_agents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_options: Data: 9.05MB + Index: 0.30MB + Engine MyISAM
ifs_postmeta: Data: 60.27MB + Index: 8.76MB + Engine MyISAM
ifs_posts: Data: 10.82MB + Index: 1.53MB + Engine MyISAM
ifs_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_post_smtp_logs: Data: 8.02MB + Index: 0.00MB + Engine InnoDB
ifs_relevanssi: Data: 2.57MB + Index: 2.71MB + Engine MyISAM
ifs_relevanssi_log: Data: 0.73MB + Index: 0.34MB + Engine MyISAM
ifs_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_css: Data: 0.13MB + Index: 0.01MB + Engine MyISAM
ifs_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_layer_animations: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_sliders: Data: 1.73MB + Index: 0.01MB + Engine MyISAM
ifs_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_slides: Data: 16.57MB + Index: 0.01MB + Engine MyISAM
ifs_revslider_slides_bkp: Data: 0.11MB + Index: 0.00MB + Engine MyISAM
ifs_revslider_static_slides: Data: 1.14MB + Index: 0.01MB + Engine MyISAM
ifs_revslider_static_slides_bkp: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
ifs_termmeta: Data: 0.45MB + Index: 0.11MB + Engine MyISAM
ifs_terms: Data: 0.02MB + Index: 0.06MB + Engine MyISAM
ifs_term_relationships: Data: 0.35MB + Index: 0.67MB + Engine MyISAM
ifs_term_taxonomy: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
ifs_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ifs_usermeta: Data: 0.98MB + Index: 0.42MB + Engine MyISAM
ifs_users: Data: 0.07MB + Index: 0.05MB + Engine MyISAM
ifs_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wcpdf_invoice_number_2022: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wc_admin_notes: Data: 0.07MB + Index: 0.00MB + Engine MyISAM
ifs_wc_admin_note_actions: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
ifs_wc_category_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ifs_wc_customer_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
ifs_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_wc_order_product_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
ifs_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
ifs_wc_order_tax_lookup: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
ifs_wc_product_attributes_lookup: Data: 0.45MB + Index: 0.50MB + Engine InnoDB
ifs_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_wc_product_meta_lookup: Data: 0.08MB + Index: 0.12MB + Engine MyISAM
ifs_wc_rate_limits: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ifs_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ifs_wfconfig: Data: 2.33MB + Index: 0.00MB + Engine InnoDB
ifs_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wffilemods: Data: 18.55MB + Index: 0.00MB + Engine InnoDB
ifs_wfhits: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
ifs_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ifs_wfknownfilelist: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
ifs_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wflogins: Data: 0.45MB + Index: 0.14MB + Engine InnoDB
ifs_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
ifs_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ifs_wfreversecache: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
ifs_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ifs_wfstatus: Data: 0.33MB + Index: 0.17MB + Engine InnoDB
ifs_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_woodmart_wishlists: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
ifs_woodmart_wishlist_products: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
ifs_wpforms_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ifs_wpr_rocket_cache: Data: 0.20MB + Index: 0.30MB + Engine InnoDB
ifs_wpr_rucss_used_css: Data: 1.28MB + Index: 0.58MB + Engine InnoDB
ifs_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ifs_wsal_metadata: Data: 18.02MB + Index: 16.38MB + Engine InnoDB
ifs_wsal_occurrences: Data: 6.02MB + Index: 2.88MB + Engine InnoDB
ifs_wt_iew_action_history: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
ifs_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ifs_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 10189
cms_block: 2
flamingo_contact: 452
flamingo_inbound: 4910
gift_card: 4
mailpoet_page: 1
nav_menu_item: 133
page: 23
post: 4
product: 1013
revision: 25
shop_coupon: 6
shop_order: 395
shop_order_refund: 1
um_directory: 1
um_form: 3
woodmart_size_guide: 1
wp_global_styles: 1
wpcf7_contact_form: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Ban Hammer: by Mika Epstein – 3.1.2
bpost shipping: by bpost – 2.3.34
Classic Widgets: by Contributeurs et contributrices WordPress – 0.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.2
Honeypot pour Contact Form 7: by Nocean – 2.1.1
Contact Form 7: by Takayuki Miyoshi – 5.7.7
Drag and Drop Multiple File Upload - Contact Form 7: by Glen Don L. Mongaya – 1.3.6.9
Duplicate Page: by mndpsingh287 – 4.5.2
GTM4WP: by Thomas Geiger – 1.16.2
Facebook for WooCommerce: by Facebook – 3.0.29
Flamingo: by Takayuki Miyoshi – 2.4
Google Listings and Ads: by WooCommerce – 2.4.10
Hide admin menu: by Bhavin Thummar & Maulik Patel (BM Studio) – 1.1.1
Imagify | Remove Thumbnail Sizes: by WP Media –
Jetpack: by Automattic – 12.3
Éditeur de page: by Michael M - WPBakery.com – 6.11.0
Loco Translate: by Tim Whitlock – 2.6.4
Post SMTP: by Post SMTP – 2.5.9
Relevanssi: by Mikko Saari – 4.20.0
Slider Revolution Mousetrap Add-On: by ThemePunch – 3.0.4
Slider Revolution Particles Effect: by ThemePunch – 3.2.6
Slider Revolution Transitionpack Add-On: by ThemePunch – 1.0.3
Slider Revolution: by ThemePunch – 6.6.7
Safe SVG: by 10up – 2.1.1
Advanced Editor Tools: by Automattic – 5.9.0
Trustpilot-reviews: by Trustpilot – 2.5.914
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.7.26

Aelia Foundation Classes for WooCommerce: by Aelia – 2.4.8.230524
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
Extra Product Sorting Options for WooCommerce: by SkyVerge – 2.9.1
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
WooCommerce PayPal Payments: by WooCommerce – 2.2.0
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.6
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.14.3
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.20.2
Aelia Tax Display by Country for WooCommerce: by Aelia – 1.20.2.230718
WooCommerce: by Automattic – 7.9.0
Woodmart Core: by  – 1.0.39
Wordfence Security: by Wordfence – 7.10.2
WP Activity Log for WooCommerce: by WP White Security – 1.5.2
WP Rocket: by WP Media – 3.14
WP Activity Log: by WP White Security – 4.5.3
YITH WooCommerce EU VAT, OSS & IOSS Premium: by YITH – 2.19.0
YITH WooCommerce Gift Cards Premium: by YITH – 4.0.1

### Inactive Plugins (2) ###

CMP - Coming Soon & Maintenance Plugin: by NiteoThemes – 4.1.9
Imagify: by Imagify – Optimize Images & Convert WebP – 2.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #8 - /boutique/
Cart: #9 - /panier/
Checkout: #10 - /commander/
My account: #11 - /mon-compte/
Terms and conditions: #662 - /conditions-generales-de-vente/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.2.4
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php version 7.4.0 is out of date. The core version is 7.9.0
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php version 5.2.0 is out of date. The core version is 7.9.0
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php version 7.4.0 is out of date. The core version is 7.8.0
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php version 2.0.0 is out of date. The core version is 7.8.0
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php version 3.5.1 is out of date. The core version is 7.8.0
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: BE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Tracking enabled: ✔

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-24 15:51:31 +02:00
Options: ✔
Notes: 170
Onboarding: completed

### Action Scheduler ###

Complete: 2,332
Oldest: 2023-06-23 13:22:53 +0200
Newest: 2023-07-24 12:51:52 +0200

Failed: 16
Oldest: 2023-01-11 08:26:11 +0100
Newest: 2023-06-01 06:26:57 +0200

Pending: 98
Oldest: 2023-07-24 12:45:51 +0200
Newest: 2024-01-01 00:00:01 +0100

### Status report information ###

Generated at: 2023-07-24 12:52:15 +02:00
`

</details>

**Comment by PascalMalinguePerso** [comment]
Hi.
We have exactly the the same behaviour and error on our website :
www.123cerises.com
WordPress Version : 6.2.2
WooCommerce Version : 7.9.0
Paypal Gateway : 2.2.0

**Comment by riccardodicurti** [comment]
There is the same bug  [ here ](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522) with a suggestion on how to fix it.

link: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522

I think this can be closed as a duplicate.

**Comment by InpsydeNiklas** [comment]
Hi there, 
this issue indeed duplicates #1522, so I will close it.
I suggest following the advice mentioned [in this comment](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522#issuecomment-1653158776) and [contacting the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
