### ISSUE TITLE
The new version of WooCommerce PayPal Payments (2.2.0) erase the client information of the website

### ISSUE THREAD

**Issue by PascalMalinguePerso** [woocommerce/woocommerce-paypal-payments#1535]
### Describe the Bug
Hi,
I installed the new version of WooCommerce PayPal Payments.
I realised that once a payment is made with PayPal, then the transaction is accepted, the all the contact / shipping information of the order is erased.

I receive a new order in my WooCommerce Backoffice but without any client / shipping information.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by EstenzE** [comment]
I have this same issue.  Orders are placed and paypal is successfully charged, but shipping information is not showing up in woocommerce orders.  Also, shipping charges are not being applied as well.  This has been happening since the latest WooCommerce update.

**Comment by marc-intuix** [comment]
Same issue here. Please fix this on next update. I have plugin version 2.2.0 and Woocommerce version 7.8.2.

Thanks

**Comment by riccardodicurti** [comment]
I also have the same problem with the following plugin versions: 

WooCommerce PayPal Payments 2.2.0 
WooCommerce 7.9.0

Someone in the WordPress plugin repository forum wrote that he solved it by removing a previously added custom checkbox to the checkout: 

```
add_action( 'woocommerce_review_order_before_submit',  function() {
    woocommerce_form_field( 'privacy_policy', array(
        'type'          => 'checkbox',
        'class'         => array('form-row privacy'),
        'label_class'   => array('woocommerce-form__label woocommerce-form__label-for-checkbox checkbox'),
        'input_class'   => array('woocommerce-form__input woocommerce-form__input-checkbox input-checkbox'),
        'required'      => true,
        'label'         => ''
    ));
}, 20 );
```

**Comment by riccardodicurti** [comment]
There is the same bug  [ here ](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522) with a suggestion on how to fix it.

link: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522

I think this can be closed as a duplicate.

**Comment by InpsydeNiklas** [comment]
Hi there, 
this issue indeed duplicates #1522, so I will close it.
I suggest following the advice mentioned [in this comment](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522#issuecomment-1653158776) and [contacting the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
