### ISSUE TITLE
Payments Being Declined

### ISSUE THREAD

**Issue by TDA-Holdings** [woocommerce/woocommerce-paypal-payments#1537]
### Describe the Bug

When customers choose PayPal Advanced Card Payment method, credit cards are declined by issuer. However, when using Stripe payment gateway, payments are processed without issue.

### To Reproduce

1. Add product to cart
2. Go to checkout
3. Enter card details
4. Click Pay Now

### Expected Behavior

We expect valid credit card payments to be accepted.

### Actual Behavior

Credit cards are declined by issuer.

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.9.0
 - Plugin Version - WooCommerce PayPal Payments 2.2.0
 - Browser [e.g. Chrome, Safari] and Version - Unknown customer browser. We use Safari 16.5.2
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @TDA-Holdings 
I don't see what this has to do with the PayPal Payments plugin.
If you need support, please [contact the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
