### ISSUE TITLE
Chowdhury

### ISSUE THREAD

**Issue by SUJIT-G** [woocommerce/woocommerce-paypal-payments#1538]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @SUJIT-G 
This issue doesn't contain any information about the issue you may encounter. In any case, GitHub is not the right place for support questions.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with more information about your issue to receive guidance. Thanks!
