### ISSUE TITLE
Some users on Safari are not seeing the paypal buttons so can't complete a sale

### ISSUE THREAD

**Issue by PurpleWebCreative** [woocommerce/woocommerce-paypal-payments#1539]
We are experiencing some users on Safari on mobile who are not seeing the paypal button as an option on the gateway. This is resulting in the not being able to complete a purchase

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @PurpleWebCreative 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
