### ISSUE TITLE
double paiement paypal

### ISSUE THREAD

**Issue by horusboutique** [woocommerce/woocommerce-paypal-payments#1541]
lors de la  saisir  de leur  commande , certaines clientes  vont trop vite  et  ne saisissent pas leur point  mondial relay , elles paient puis  revienennt en arriere pour saisir le point de livraison , puis  sont  redirigées vers le paiement une seconde fois . 

ce qui  crée deux commandes  deux paiements 

le plugin ne  bloque pas  la  validation de paiment 

besoin aide svp merci

**Comment by SydeKrystian** [comment]
Hello @horusboutique 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522
You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here.](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6)

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here.](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
