### ISSUE TITLE
UNPROCESSABLE_ENTITY and order not processed but payment recieved in practice

### ISSUE THREAD

**Issue by eddr** [woocommerce/woocommerce-paypal-payments#1544]
Hi

System:
WP 6.2.2
WC 7.9
PP plugin: 2.2

---

Description: 
- Some customers try to pay via PP without success. 
- There is "UNPROCESSABLE_ENTITY" comment in the order edit page, no "failed" status
- Order status / stocks do not change
- Payment is received in PayPal in practice
- After some time, the order is automatically cancelled by WC

Expected behaviour :
If order fails, payment should not be recieved
If payment is recieved, order status should change..

More Info:
It seems that two orders are created in some cases - one without customer information but with payment information, and another with customer information but no payment info.. 

We can provide logs
Please advise
Thanks

**Comment by riccardodicurti** [comment]
There is the same bug  [ here ](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522) with a suggestion on how to fix it.

link: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522

I think this can be closed as a duplicate.

**Comment by InpsydeNiklas** [comment]
Hi @eddr 
this indeed sounds to be related to the bug reported in #1522.
So I will close this as a duplicate.
For any further questions, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
