### ISSUE TITLE
woocommerce_checkout_process hook does not fired after clicking on Paypal button

### ISSUE THREAD

**Issue by Estalhun** [woocommerce/woocommerce-paypal-payments#1545]
### Describe the Bug

I use a code to validate the address, phone and email fields because some of the customers provide false or at least inaccurate information.

```
add_action('woocommerce_checkout_process', 'my_custom_checkout_field_process');
function my_custom_checkout_field_process() {
            $billing_email = $_POST['billing_email'];
            if( is_email($billing_email) !== false ) {
            	$wrong_email_domains = array('fremail.hu', 'gamil.com', 'gmail.ro', 'gmail.sk', 'gmail.pl', );
                if ( in_array( preg_replace( '/^[^@]+@/', '', $billing_email ), $wrong_email_domains ) ) {
                    $myerr = true;
                    if( function_exists('my_log') ) { my_log( 'Email address: ' . $_POST['billing_email'] ); } 
                    wc_add_notice( __('A megadott email cím helytelen:') . ' <span data-no-translation style="color:red; font-weight:bold;">' . $billing_email  .
                              '</span>', 'error' );
                }
            } 
            //there are the rest of the code
}
```

### To Reproduce

1. Put my code into the functions.php
2. Use test@gamil.com as email address in the checkout
3. Fill every necessary field.
4. You should see the error message as seen on the screenshot.

### Screenshots

[Link](https://drive.google.com/drive/folders/1-_XTkAMHqHee9Lw0oNDvASIn83-xdKsx?usp=drive_link)

### Expected Behavior

woocommerce_checkout_process hook should fired after clicking on Paypal button

### Actual Behavior

woocommerce_checkout_process hook does not fired after clicking on Paypal button

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.8.2
 - Plugin Version 2.2.0
 - Browser [e.g. Chrome, Safari] and Version: Does not matter
 - Any other plugins installed:

Action Scheduler: by Automattic – 3.6.1
Ivory Search: by Ivory Search – 5.5.2
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout: by PI Websolution – 2.1.69
Advanced Google reCAPTCHA: by WP Concern – 1.0.15
All In One WP Security: by All In One WP Security & Firewall Team – 5.2.1
Application Passwords: by George Stephanis – 0.1.3
Astra Pro: by Brainstorm Force – 4.1.6
Astra Widgets: by Brainstorm Force – 1.2.12
Better Plugin Compatibility Control: by Oliver Schlöbe – 6.0.1
Blackhole for Bad Bots: by Jeff Starr – 3.6
Booster Plus for WooCommerce: by Pluggabl LLC – 7.0.0
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Come Back!: by Sanjeev Aryal – 1.3.4
Currency Exchange for WooCommerce: by BeRocket – 3.5.8
Customiser Search: by Brainstorm Force – 1.1.6
Delete Expired Transients: by WebAware – 2.0.7
Disable Cart Fragments: by Optimocha – 2.3
Disable Feeds: by Samir Shah
BBpress support by Matthew Sigley – 1.4.4

Display Order Details for WooCommerce: by Pinal Shah – 1.0
Display Posts: by Bill Erickson – 3.0.2
Download Plugins and Themes from Dashboard: by WPFactory – 1.8.3
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
Easy WP SMTP: by Easy WP SMTP – 2.1.2
Elementor Pro: by Elementor.com – 3.14.1
Elementor: by Elementor.com – 3.14.1
Email Address Encoder: by Till Krüss – 1.0.22
Faster Updates: by WP Core Contributors – 0.3.2
Faster YouTube Embed: by HasThemes – 1.0.6
GDPR Cookie Compliance: by Moove Agency – 4.12.4
Health Check & Troubleshooting: by The WordPress.org community – 1.6.0
HelloPack: by HelloWP Ltd – 1.2.21
Hungarian Pickup Points & Shipping Labels for WooCommerce: by Viszt Péter – 2.6.1
Image Regenerate & Select Crop: by Iulia Cazan – 7.2.2
Integration for Szamlazz.hu & WooCommerce: by Viszt Péter – 5.7.6.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.11
LH Add Media from URL: by Peter Shaw – 1.22
List category posts: by Fernando Briano – 0.88.1
LiteSpeed Cache: by LiteSpeed Technologies – 5.5.1
Loco Translate: by Tim Whitlock – 2.6.4
Loginizer: by Softaculous – 1.8.1
Media Sync: by Erol Živina – 1.3.1
Menu Duplicator: by Jeremy Ross – 0.6
Meta Box: by MetaBox.io – 5.7.4
My Custom Functions: by Space X-Chimp – 4.51
MailerLite - Signup forms (official): by MailerLite – 1.6.8
Pages with category and tag: by YAHMAN – 0.9.0
WooCommerce Partial COD - Payment Gateway Restrictions & Fees: by zendcrew – 1.2.1
Peter's Post Notes: by Peter Keung – 1.6.5
Phoenix Media Rename: by crossi72 – 3.11.0
PixelYourSite: by PixelYourSite – 9.4.0.1
Plugin Notes Plus: by Jamie Bergen – 1.2.6
PowerPack Lite for Elementor: by IdeaBox Creations – 2.7.8
Print-O-Matic: by twinpictures – 2.1.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Related Posts for WordPress: by Never5 – 2.1.4
Rollback Update Failure: by WP Core Contributors – 5.3.3
Sidebar Manager: by Brainstorm Force – 1.1.8
OTP SimplePay Gateway for WooCommerce: by Cone Development – 2.5.7
Slide Anything - Responsive Content / HTML Slider and Carousel: by  – 2.4.9
Tag Groups: by TaxoPress – 2.0.3
Transients Manager: by WPBeginner – 2.0.3
TranslatePress - Business: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu – 1.3.0

TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.5.7

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.7.26

User Role Editor: by Vladimir Garagulya – 4.63.3
Visibility Logic for Elementor: by StaxWP – 2.3.5.1
Pont shipping for Woocommerce: by szathmari.hu – 7.4
Webshippy Order Sync: by Webshippy Ltd. – 1.7.3
Conditional Display for Mobile by WonderPlugin: by Magic Hills Pty Ltd – 1.2
WooCommerce Cancel Abandoned Order: by studio RVOLA – 2.0.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.9.0
Combo Offers WooCommerce: by QuanticEdge – 2.10
Woo Discount Rules PRO 2.0: by Flycart – 2.6.1
Woo Discount Rules: by Flycart – 2.6.1
MailerLite - WooCommerce integration: by MailerLite – 1.8.7
CartBounty Pro - Save and recover abandoned carts for WooCommerce: by Streamline.lv – 9.11
Booster for WooCommerce: by Pluggabl LLC – 6.0.6
WooCommerce PayPal Payments: by WooCommerce – 2.2.0
WooCommerce Matomo Analytics: by InnoCraft – 1.0.20
WooCommerce: by Automattic – 7.8.2 (update to version 7.9.0 is available)
Woocommerce Wintax Integration: by Novitax Kft. – 1.0.2
WP BrowserUpdate: by Marco Steinbrecher – 4.6.2
WP Crontrol: by John Blackbourn & contributors – 1.15.3
WP IE Buster: by Qrac – 1.4.1
WP Last Modified Info: by Sayan Datta – 1.8.8
WP Mail Logging: by WP Mail Logging Team – 1.12.0
LightStart - Maintenance Mode, Coming Soon and Landing Page Builder: by Themeisle – 2.6.8
WP-Matomo Integration: by André Bräkling – 1.0.28
SEOPress PRO: by The SEO Guys at SEOPress – 6.8
SEOPress: by The SEO Guys at SEOPress – 6.8.0.1
Refer a Friend for WooCommerce PREMIUM: by WPGens – 2.4.0

### Dropin Plugins (2) ###

maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Must Use Plugins (3) ###

aios-firewall-loader.php: by  –
Elementor Safe Mode: by Elementor.com – 1.0.0
Health Check Troubleshooting Mode: by  – 1.8.1

### Additional Details
none

**Comment by InpsydeNiklas** [comment]
Hi @Estalhun 
This is expected behavior as the hook `woocommerce_checkout_process` is called only after creating the PayPal order, so it would not be taken into account when clicking the PayPal button.

Instead, you could try it with the hook `woocommerce_after_checkout_validation` because [validate_checkout](https://github.com/woocommerce/woocommerce/blob/1e94d3fc180783fd17ae096e84b87dda21dfc5e4/plugins/woocommerce/includes/class-wc-checkout.php#L849) is called before opening the popup window.

Alternatively, you can try additionally enabling the [basic validation as mentioned here](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#checkout-form-field-validation-before-creating-the-paypal-order). This doesn't perform a server-side validation, but it would additionally check that all required form fields are populated before opening the PayPal popup window.

For any additional questions, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by pablo-sg-pacheco** [comment]
Hi,

The `woocommerce_after_checkout_validation` works fine for the paypal button on checkout page, but apparently it doesn't get triggered from smart buttons displayed on cart and product pages. Can you please look into it?

**Comment by InpsydeNiklas** [comment]
@pablo-sg-pacheco The hook `woocommerce_after_checkout_validation` fires on the checkout page after WooCommerce validated all checkout form fields. There are no form fields to validate on the single product or cart pages, hence this hook does not trigger.
On the single product page e.g. for variable products, the PayPal buttons will be greyed out as long as there is no valid product selection.

**Comment by pablo-sg-pacheco** [comment]
Thanks for the info.

So if the PayPal button can be greyed out, maybe I could use that as a form of validation. Is there some hook I could use to make it greyed out?

**Comment by InpsydeNiklas** [comment]
Examples on how to disable (grey out) the buttons can be found [in the wiki](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#programmatically-disable-the-paypal-smart-buttons-grey-outvisible-but-unclickable).  Beyond this, the buttons can also be [conditionally hidden](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-smart-buttons-on-the-single-product-page-for-specific-products) on the single product page. The buttons on the cart/checkout pages can be removed by unsetting the `ppcp-gateway`. 
I hope this helps! 
For any other questions on how to best configure PayPal Payments for your needs, I recommend [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.
