### ISSUE TITLE
Empty response from js

### ISSUE THREAD

**Issue by AltRob** [woocommerce/woocommerce-paypal-payments#1546]
### Describe the Bug

Getting an empty response from: https://www.paypal.com/sdk/js?client-id=CLIENTID
Website taking over 10 mins to load.
Only seems to happen in Safari.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @AltRob 
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need assistance as GitHub is not the right place for support. Thanks!
