### ISSUE TITLE
Impossible to Refund a Guest Checkout order

### ISSUE THREAD

**Issue by MikeLikesThat** [woocommerce/woocommerce-paypal-payments#1547]
### Describe the Bug

Impossible to Refund an order through Woocommerce that was made through Guest Checkout via PayPal.

### To Reproduce

1. Go to order made via "x debit card" that also has a PayPal fee
2. Click on Refund
3. The standard blue button that should state "Refund $0.00 via PayPal" or "Refund $0.00 manually" are missing.

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/81569362/43024fa3-af7a-430c-b926-057d0e07fe06)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/81569362/c7d8b596-cd9a-41f8-84c9-5d1c415d6961)

### Expected Behavior

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/81569362/c32c8aaa-f89e-4e19-9f7c-3d8739d1d7e6)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/81569362/183e417d-e602-4218-8d11-17ef70fc6990)

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.9.0
 - Plugin Version 6.2.0
 - All Browsers
 
 ### Additional Details

All screenshots are from the same site at the time of writing this report. It is possible to refund orders via all other payment methods on the site except for orders paid via x card with a PayPal fee which I can only assume is your Pay by Card as a Guest Checkout feature.

**Comment by SydeKrystian** [comment]
Hello @MikeLikesThat 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
