### ISSUE TITLE
3D Secure

### ISSUE THREAD

**Issue by kaoopro** [woocommerce/woocommerce-paypal-payments#1548]
Always trigger 3D Secure auto bypass for Advanced Card Processing. pls fix it.
Version 2.2.0
WordPress Current version: 6.2.2

**Comment by InpsydeNiklas** [comment]
Hi @kaoopro 
It is not fully clear to us what "Always trigger 3D Secure auto bypass for Advanced Card Processing" is supposed to mean, but the 3D Secure contingency can be configured from the [Advanced Card Processing settings tab](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing). 
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need any additional assistance. 
Thanks!

**Comment by kaoopro** [comment]
> Hi @kaoopro
> It is not fully clear to us what "Always trigger 3D Secure auto bypass for Advanced Card Processing" is supposed to mean, but the 3D Secure contingency can be configured from the [Advanced Card Processing settings tab](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing).
> Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need any additional assistance.
> Thanks!

hi. it will open popup to ask buyer verify payment using 3D. but it will pass this verify. buyer don't have to verify 3D secure to bank card
