### ISSUE TITLE
problem with paypal

### ISSUE THREAD

**Issue by tiendaYTSmed** [woocommerce/woocommerce-paypal-payments#1549]
good morning

The orders that are made by paypal through the ytsmed.com website are generating an error, the clients inform me that the purchase confirmation email does not arrive, and we receive the purchase email with the customer data and empty shipping, the paypal purchase is made and we receive the payment to our account, please I need to solve this since the clients get confused and some of them place the order twice, it has happened to me that the second order does arrive the data.

With the other payment platforms, this problem has never happened to me.

And neither with Paypal until last week we updated the plugins I don't know if that would have something to do

![Captura Paypal 1](https://github.com/woocommerce/woocommerce-paypal-payments/assets/140694417/a054a2ab-e4d9-404e-9771-db581cca7176)
![Captura de Paypal 2](https://github.com/woocommerce/woocommerce-paypal-payments/assets/140694417/204057ee-15e9-49b0-b707-88cebb7509a8)

**Comment by InpsydeNiklas** [comment]
Hi @tiendaYTSmed  
this issue duplicates #1522, so I will close it.
I suggest following the advice mentioned [in this comment](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522#issuecomment-1653158776) and [contacting the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
