### ISSUE TITLE
Woocommerce - contact information missing

### ISSUE THREAD

**Issue by watels** [woocommerce/woocommerce-paypal-payments#1551]
### Describe the Bug

On woocommerce, sometimes when my customer make a transaction, the contact informations are empty. Whereas it is mandatory fields. 
Sometimes it works well, but most of the time it doesn't.

Here is a screenshot : https://ibb.co/KXqNqDG

I have the paypal log. But I am not sure to be able to share it here as it contains private informations.

Woocommerce version : 7.9.0

**Comment by InpsydeNiklas** [comment]
Hi @watels 
This issue duplicates #1522, so I will close it.
Please check the information in this comment for a potential workaround: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522#issuecomment-1653158776
For any further questions or more guidance, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.
Thanks!
