### ISSUE TITLE
WooCommerce PayPal Payments issue

### ISSUE THREAD

**Issue by Morgan67000** [woocommerce/woocommerce-paypal-payments#1552]
Hi everyone !

I do have an unexpected error with wordpress/woocommerce/paypal

Everything worked fine at first (set 3 weeks ago), but today I saw the following error and I can't manage to solve it

### Describe the Bug

Authentication with PayPal failed: Could not create token.

Please verify your API Credentials and try again to connect your PayPal business account. Visit the [plugin documentation](https://docs.woocommerce.com/document/woocommerce-paypal-payments/) for more information about the setup.

here is the log :

CRITICAL Uncaught WCPay\Exceptions\API_Exception: Erreur : Accounts do not currently support `card_payments` without `transfers`. Please visit https://stripe.com/docs/connect/account-capabilities#card-payments for more details. 

### To Reproduce

WooCommerce PayPal Payments

### Actual Behavior

The token won't generate

### Environment

WooCommerce PayPal Payments version 2.2.0
PHP Version 8.2
Woocommerce version 7.9
WordPress 6.2.2

**Comment by SydeKrystian** [comment]
Hello @Morgan67000 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
