### ISSUE TITLE
Bug on the paypal version 2.1.1

### ISSUE THREAD

**Issue by dadds69** [woocommerce/woocommerce-paypal-payments#1557]
### Describe the Bug

Guest orders paid via paypal are placed on the site while guest orders are deactivated. In addition, there is no customer information, neither name nor address. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.9.0
 - Plugin Version 2.1.1
 - Browser [e.g. Chrome, Safari] and Version Edge
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @dadds69 

I noticed that one of the problems you're experiencing has been reported before in this issue, https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. 
You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
