### ISSUE TITLE
We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again.

### ISSUE THREAD

**Issue by guillaume62** [woocommerce/woocommerce-paypal-payments#1558]
### Describe the Bug

I can't connect my Business account Paypal

### To Reproduce

1. Go to 'WooPayment'
2. Click on 'Setting'
3. Activate (Paypal)
4. ID and Password are correct
5. See error

### Environment

It's a new installation of Wordpress WooPayments and WooCommerce

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @guillaume62 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
