### ISSUE TITLE
Problem with Paypal on Woocommerce : Authentication with PayPal failed: Could not create token.

### ISSUE THREAD

**Issue by backtothefootball** [woocommerce/woocommerce-paypal-payments#1559]
Hello,
I'm using Paypal on Woocommerce since 2 years. Everything was fine before. 
Woocommerce version : 6.2.2
Paypal plugin version : 2.2.0

I have an issue with the Paypal plugin since a few days. In back office, it says : _Authentication with PayPal failed: Could not create token._
In front office, clients can't pay with paypal anymore, it says : _Could not create token._

I have tried to reconnect my account, it had failed everytime. 
I have then tried to reconnect manually, with my API codes. I can see i'm connected with this method but I still got the issue _Authentication with PayPal failed: Could not create token._
I have switched from 2.2.0 version to the 2.1.0 version and the problem seems to be resolved... 

What can I do to resolve it ?

Thank you

**Comment by guillaume62** [comment]
Hello @backtothefootball 
Same issue for me.
I hope they help us

**Comment by SydeKrystian** [comment]
Hello @backtothefootball 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
