### ISSUE TITLE
No connection to Paypal in Woocommerce

### ISSUE THREAD

**Issue by RRoseEd** [woocommerce/woocommerce-paypal-payments#1560]
Hi, 
Our Wordpress website can't manage to accept Paypal payments anymore, with a "Could not create token" message when ordering.
This is most probably due to a failed API Credential link to Paypal. We tried to disconnect and reconnect this link (both automatically and manually with Merchant IDs and Live Client ID), but in he Wordpress manager, we still get the "failed API credential" error message. 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/58868251/d8354e16-f256-40f8-9e69-c27a821e041d)
Many thanks for your help

**Comment by guillaume62** [comment]
Hello 
Same issue for me

**Comment by SydeKrystian** [comment]
Hello @RRoseEd 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Regards,

Krystian
