### ISSUE TITLE
FraudID feature running despite being disable, causing mySQL performance issues

### ISSUE THREAD

**Issue by tomwc4** [woocommerce/woocommerce-paypal-payments#1564]
**Description**
We recently had issues with multiple WooCommerce clients having performance issues, so bad enough to result in customers getting constant 503s from the server. I had originally chalked it up to bots, but after looking deeper, it seems like the WooCommerce PayPal Payments plugin is flooding the mySQL database `wp_woocommerce_sessions` table with serialized records for `"ppcp_fraudnet_session_id"`. Multiple records are generated for each cart session, and has been causing poor performance on each site we have this plugin installed on.

The catch is - neither of these sites have PayPal FraudNet enabled in the config, and one of these sites wasn't even using the PayPal payment gateway (the plugin was installed, but the gateway was not configured).

**To Reproduce**

- Have WooCommerce PayPal Payments plugin active
- Observe session records in `wp_woocommerce_sessions` , search terms for `"ppcp_fraudnet_session_id"`
- Delete all session records, they will re-post within seconds

Record data looks like:

`a:16:{s:24:"ppcp_fraudnet_session_id";s:32:"73ae78a5bbed7b713af601197f44d470";s:4:"cart";s:9808:"a:5:{s:32:"60624252672d0b7800df4d8d40d9045d";a:13:{s:14:"composite_data";a:7:{i:1678864724;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:12:"Lower Risers";s:12:"composite_id";i:2702;}i:1678864725;a:12:{s:10:"product_id";i:568;s:8:"quantity";i:1;s:10:"attributes";a:1:{s:18:"attribute_pa_color";s:6:"orange";}s:12:"variation_id";i:573;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:2:"no";s:6:"static";s:3:"yes";s:5:"title";s:11:"Hand Guards";s:12:"composite_id";i:2702;s:4:"type";s:8:"variable";}i:1678864726;a:10:{s:10:"product_id";i:172;s:8:"quantity";i:2;s:12:"quantity_min";i:1;s:12:"quantity_max";i:2;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:7:"Mirrors";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}i:1678864728;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Display Mount";s:12:"composite_id";i:2702;}i:1678864727;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:4:"Dash";s:12:"composite_id";i:2702;}i:1678864729;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Switch Mounts";s:12:"composite_id";i:2702;}i:1683698196;a:10:{s:10:"product_id";i:2059;s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:9:"Anti Vibe";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}}s:18:"composite_children";a:3:{i:0;s:32:"344512d71bf719df56d3964df6a3281a";i:1;s:32:"191bcd5716e88964c797286f875fefa1";i:2;s:32:"73df6fa9723cf2f8fc6ca3c6567cef1e";}s:3:"key";s:32:"60624252672d0b7800df4d8d40d9045d";s:10:"product_id";i:2702;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:1;s:9:"data_hash";s:32:"bb53e75c6d7a35cfd7ed7b53e573840c";s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:0;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:0;s:8:"line_tax";d:0;}s:32:"344512d71bf719df56d3964df6a3281a";a:13:{s:16:"composite_parent";s:32:"60624252672d0b7800df4d8d40d9045d";s:14:"composite_data";a:7:{i:1678864724;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:12:"Lower Risers";s:12:"composite_id";i:2702;}i:1678864725;a:12:{s:10:"product_id";i:568;s:8:"quantity";i:1;s:10:"attributes";a:1:{s:18:"attribute_pa_color";s:6:"orange";}s:12:"variation_id";i:573;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:2:"no";s:6:"static";s:3:"yes";s:5:"title";s:11:"Hand Guards";s:12:"composite_id";i:2702;s:4:"type";s:8:"variable";}i:1678864726;a:10:{s:10:"product_id";i:172;s:8:"quantity";i:2;s:12:"quantity_min";i:1;s:12:"quantity_max";i:2;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:7:"Mirrors";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}i:1678864728;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Display Mount";s:12:"composite_id";i:2702;}i:1678864727;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:4:"Dash";s:12:"composite_id";i:2702;}i:1678864729;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Switch Mounts";s:12:"composite_id";i:2702;}i:1683698196;a:10:{s:10:"product_id";i:2059;s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:9:"Anti Vibe";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}}s:14:"composite_item";i:1678864725;s:3:"key";s:32:"344512d71bf719df56d3964df6a3281a";s:10:"product_id";i:568;s:12:"variation_id";i:573;s:9:"variation";a:1:{s:18:"attribute_pa_color";s:6:"orange";}s:8:"quantity";i:1;s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:175;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:175;s:8:"line_tax";d:0;}s:32:"191bcd5716e88964c797286f875fefa1";a:13:{s:16:"composite_parent";s:32:"60624252672d0b7800df4d8d40d9045d";s:14:"composite_data";a:7:{i:1678864724;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:12:"Lower Risers";s:12:"composite_id";i:2702;}i:1678864725;a:12:{s:10:"product_id";i:568;s:8:"quantity";i:1;s:10:"attributes";a:1:{s:18:"attribute_pa_color";s:6:"orange";}s:12:"variation_id";i:573;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:2:"no";s:6:"static";s:3:"yes";s:5:"title";s:11:"Hand Guards";s:12:"composite_id";i:2702;s:4:"type";s:8:"variable";}i:1678864726;a:10:{s:10:"product_id";i:172;s:8:"quantity";i:2;s:12:"quantity_min";i:1;s:12:"quantity_max";i:2;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:7:"Mirrors";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}i:1678864728;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Display Mount";s:12:"composite_id";i:2702;}i:1678864727;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:4:"Dash";s:12:"composite_id";i:2702;}i:1678864729;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Switch Mounts";s:12:"composite_id";i:2702;}i:1683698196;a:10:{s:10:"product_id";i:2059;s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:9:"Anti Vibe";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}}s:14:"composite_item";i:1678864726;s:3:"key";s:32:"191bcd5716e88964c797286f875fefa1";s:10:"product_id";i:172;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:2;s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:81;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:81;s:8:"line_tax";d:0;}s:32:"73df6fa9723cf2f8fc6ca3c6567cef1e";a:13:{s:16:"composite_parent";s:32:"60624252672d0b7800df4d8d40d9045d";s:14:"composite_data";a:7:{i:1678864724;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:12:"Lower Risers";s:12:"composite_id";i:2702;}i:1678864725;a:12:{s:10:"product_id";i:568;s:8:"quantity";i:1;s:10:"attributes";a:1:{s:18:"attribute_pa_color";s:6:"orange";}s:12:"variation_id";i:573;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";s:0:"";s:8:"optional";s:2:"no";s:6:"static";s:3:"yes";s:5:"title";s:11:"Hand Guards";s:12:"composite_id";i:2702;s:4:"type";s:8:"variable";}i:1678864726;a:10:{s:10:"product_id";i:172;s:8:"quantity";i:2;s:12:"quantity_min";i:1;s:12:"quantity_max";i:2;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:7:"Mirrors";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}i:1678864728;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Display Mount";s:12:"composite_id";i:2702;}i:1678864727;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:4:"Dash";s:12:"composite_id";i:2702;}i:1678864729;a:9:{s:10:"product_id";s:0:"";s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:13:"Switch Mounts";s:12:"composite_id";i:2702;}i:1683698196;a:10:{s:10:"product_id";i:2059;s:8:"quantity";i:1;s:12:"quantity_min";i:1;s:12:"quantity_max";i:1;s:8:"discount";d:10;s:8:"optional";s:3:"yes";s:6:"static";s:2:"no";s:5:"title";s:9:"Anti Vibe";s:12:"composite_id";i:2702;s:4:"type";s:6:"simple";}}s:14:"composite_item";i:1683698196;s:3:"key";s:32:"73df6fa9723cf2f8fc6ca3c6567cef1e";s:10:"product_id";i:2059;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:1;s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:71.099999999999994315658113919198513031005859375;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:71.099999999999994315658113919198513031005859375;s:8:"line_tax";d:0;}s:32:"177540c7bcb8db31697b601642eac8d4";a:11:{s:3:"key";s:32:"177540c7bcb8db31697b601642eac8d4";s:10:"product_id";i:3053;s:12:"variation_id";i:0;s:9:"variation";a:0:{}s:8:"quantity";i:1;s:9:"data_hash";s:32:"b5c1d5ca8bae6d4896cf1807cdf763f0";s:13:"line_tax_data";a:2:{s:8:"subtotal";a:0:{}s:5:"total";a:0:{}}s:13:"line_subtotal";d:50;s:17:"line_subtotal_tax";d:0;s:10:"line_total";d:50;s:8:"line_tax";d:0;}}";s:11:"cart_totals";s:401:"a:15:{s:8:"subtotal";s:5:"377.1";s:12:"subtotal_tax";d:0;s:14:"shipping_total";s:2:"15";s:12:"shipping_tax";d:0;s:14:"shipping_taxes";a:0:{}s:14:"discount_total";d:0;s:12:"discount_tax";d:0;s:19:"cart_contents_total";s:5:"377.1";s:17:"cart_contents_tax";i:0;s:19:"cart_contents_taxes";a:0:{}s:9:"fee_total";s:1:"0";s:7:"fee_tax";d:0;s:9:"fee_taxes";a:0:{}s:5:"total";s:6:"392.10";s:9:"total_tax";d:0;}";s:15:"applied_coupons";s:6:"a:0:{}";s:22:"coupon_discount_totals";s:6:"a:0:{}";s:26:"coupon_discount_tax_totals";s:6:"a:0:{}";s:21:"removed_cart_contents";s:6:"a:0:{}";s:16:"wca_session_data";s:120:"a:1:{i:0;a:3:{s:5:"event";s:32:"woocommerceanalytics_add_to_cart";s:10:"product_id";s:4:"3053";s:8:"quantity";s:1:"1";}}";s:22:"shipping_for_package_0";s:522:"a:2:{s:12:"package_hash";s:40:"wc_ship_340f9403a3651a8f74aa9fd42ac0e61a";s:5:"rates";a:1:{s:11:"flat_rate:1";O:16:"WC_Shipping_Rate":2:{s:7:"*data";a:6:{s:2:"id";s:11:"flat_rate:1";s:9:"method_id";s:9:"flat_rate";s:11:"instance_id";i:1;s:5:"label";s:13:"USA flat rate";s:4:"cost";s:5:"15.00";s:5:"taxes";a:0:{}}s:12:"*meta_data";a:1:{s:5:"Items";s:159:"Ultimate Hand Guard KTM 2015+ (125-690cc) - Orange &times; 1, HDB Hand Guard Mirror &times; 2, Anti Vibe Threaded Inserts &times; 1, Mask Turn Signal &times; 1";}}}}";s:25:"previous_shipping_methods";s:39:"a:1:{i:0;a:1:{i:0;s:11:"flat_rate:1";}}";s:23:"chosen_shipping_methods";s:29:"a:1:{i:0;s:11:"flat_rate:1";}";s:22:"shipping_method_counts";s:14:"a:1:{i:0;i:1;}";s:9:"ppcp_fees";s:6:"a:0:{}";s:45:"facebook_for_woocommerce_add_to_cart_event_id";s:36:"02c5e29c-659d-4a60-a83d-169a6e10653f";s:10:"wc_notices";N;s:8:"customer";s:720:"a:27:{s:2:"id";s:1:"0";s:13:"date_modified";s:0:"";s:8:"postcode";s:0:"";s:4:"city";s:0:"";s:9:"address_1";s:0:"";s:7:"address";s:0:"";s:9:"address_2";s:0:"";s:5:"state";s:2:"CO";s:7:"country";s:2:"US";s:17:"shipping_postcode";s:0:"";s:13:"shipping_city";s:0:"";s:18:"shipping_address_1";s:0:"";s:16:"shipping_address";s:0:"";s:18:"shipping_address_2";s:0:"";s:14:"shipping_state";s:2:"CO";s:16:"shipping_country";s:2:"US";s:13:"is_vat_exempt";s:0:"";s:19:"calculated_shipping";s:0:"";s:10:"first_name";s:0:"";s:9:"last_name";s:0:"";s:7:"company";s:0:"";s:5:"phone";s:0:"";s:5:"email";s:0:"";s:19:"shipping_first_name";s:0:"";s:18:"shipping_last_name";s:0:"";s:16:"shipping_company";s:0:"";s:14:"shipping_phone";s:0:"";}";}`

This entry came out especially long because the client has a lot of variable products with multiple options.

Some sites generated as many as a dozen of these entries per cart session that are updated and refreshed, causing our mySQL minutes to gradually increase into performance issues.

**Screenshots**

(Plugin w/o FraudNet enabled)
![2023-07-31 08_53_45-WooCommerce settings ‹ HDB Offroad — WordPress](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1915245/471355e9-a1e0-4316-8425-3989f9c92bec)

(Resulting Records)
![2023-07-31 08_54_12-mysql8-admin server324 com _ localhost _ hdboffroad_2023 _ hdb_woocommerce_sessi](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1915245/a73437fc-d890-4de4-af78-c4b6f6772896)

(Performance indicators - starting around the time we updated the plugin)
![2023-07-31 11_20_27-hdboffroad com __ Control Panel __ Resources](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1915245/4f542846-50e9-4d0e-9498-5a3c4b83836f)

**Expected Behavior**

The FraudNet records shouldn't be created if the FraudNet mode isn't enabled in the plugin settings.

**Actual Behavior**
 FraudNet records are created for each session. It also appears to create those records even if the PayPal payment gateway isn't enabled in WooCommerce payment settings.

**Environment**

WordPress Version 6.2.2
WooCommerce Version 7.9.0
Plugin Version 2.2.0 
Browser [e.g. Chrome, Safari] and Version: same behaviour on all browsers
Plugins installed: Multiple other payment plugins, but disabling the plugin stops the records from generating

**Comment by Whynotdiex** [comment]
Im experiencing the same issue, but everytime Fraudnet makes a record about the session ID, it also wipes the cart to 0 for none signed in users

**Comment by tomwc4** [comment]
I ended up removing the plugin for the 2 clients that could. For the other one, spambots in conjunction with this issue caused the site to crash, so I ended upgrading their service to a higher tier for a deeper layer of security and object caching and so far that's done the trick.

**Comment by InpsydeNiklas** [comment]
Hi there, thanks for the issue report. This does appear to be more of a support-related problem instead of a bug in the plugin and I'd like to clarify eventual misconceptions:

>  it seems like the WooCommerce PayPal Payments plugin is flooding the mySQL database wp_woocommerce_sessions table with serialized records

The `wp_woocommerce_sessions` table stores user session data for WooCommerce. Entries are created when a visitor starts a session on the site, typically by adding an item to the cart. This allows WooCommerce to track cart contents and other session-specific data even for users who aren't logged in.
The FraudNet feature in the Connection tab isn't related to these database entries. PayPal Payments generally does not create any entries in this table. But when a website visitor has a product in the cart while the PayPal buttons are active, WooCommerce may store specific PayPal data in the session data it would be storing regardless.
This happens independently of whether FraudNet is enabled, and disabling PayPal Payments plugin should also have no big impact on whether these session entries are created or not.

If any questions or issues remain when using the latest PayPal Payments version, I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by sun** [comment]
@InpsydeNiklas Sorry, but that is not correct.  The FraudNet integration of the PayPal Payments plugin is starting a session before an anonymous site visitor interacts with the shop (at all).

In a standard configuration of HTTP caches such as Varnish, if the backend sets a cookie, then the response cannot be cached, because the cache needs to assume that it contains content that is specific to the current user.

But the page response is not user-specific, there are no items in the cart, and therefore the PayPal Payments plugin should not start a session.

That is why the current behavior of the plugin causes a major performance regression for all websites using the plugin.

In fact, [PayPal's FraudNet integration manual](https://developer.paypal.com/docs/checkout/apm/pay-upon-invoice/fraudnet/) states that the script is only supposed to be loaded on the checkout page.

As @tomwc4 mentioned, when inspecting the content of these sessions in the database, you can see that they are empty.

<details>
<summary>Example session content (unserialized)</summary>

```
array(8) {
  ["ppcp_fraudnet_session_id"]=>
  string(32) "8aa4637dcab3b78cd7f848851a2eexxx"
  ["cart"]=>
  array(0) {
  }
  ["cart_totals"]=>
  array(15) {
    ["subtotal"]=>
    int(0)
    ["subtotal_tax"]=>
    int(0)
    ["shipping_total"]=>
    int(0)
    ["shipping_tax"]=>
    int(0)
    ["shipping_taxes"]=>
    array(0) {
    }
    ["discount_total"]=>
    int(0)
    ["discount_tax"]=>
    int(0)
    ["cart_contents_total"]=>
    int(0)
    ["cart_contents_tax"]=>
    int(0)
    ["cart_contents_taxes"]=>
    array(0) {
    }
    ["fee_total"]=>
    int(0)
    ["fee_tax"]=>
    int(0)
    ["fee_taxes"]=>
    array(0) {
    }
    ["total"]=>
    int(0)
    ["total_tax"]=>
    int(0)
  }
  ["applied_coupons"]=>
  array(0) {
  }
  ["coupon_discount_totals"]=>
  array(0) {
  }
  ["coupon_discount_tax_totals"]=>
  array(0) {
  }
  ["removed_cart_contents"]=>
  array(0) {
  }
  ["customer"]=>
  array(28) {
    ["id"]=>
    string(1) "0"
    ["date_modified"]=>
    string(0) ""
    ["first_name"]=>
    string(0) ""
    ["last_name"]=>
    string(0) ""
    ["company"]=>
    string(0) ""
    ["phone"]=>
    string(0) ""
    ["email"]=>
    string(0) ""
    ["address"]=>
    string(0) ""
    ["address_1"]=>
    string(0) ""
    ["address_2"]=>
    string(0) ""
    ["city"]=>
    string(0) ""
    ["state"]=>
    string(2) "AG"
    ["postcode"]=>
    string(0) ""
    ["country"]=>
    string(2) "CH"
    ["shipping_first_name"]=>
    string(0) ""
    ["shipping_last_name"]=>
    string(0) ""
    ["shipping_company"]=>
    string(0) ""
    ["shipping_phone"]=>
    string(0) ""
    ["shipping_address"]=>
    string(0) ""
    ["shipping_address_1"]=>
    string(0) ""
    ["shipping_address_2"]=>
    string(0) ""
    ["shipping_city"]=>
    string(0) ""
    ["shipping_state"]=>
    string(2) "AG"
    ["shipping_postcode"]=>
    string(0) ""
    ["shipping_country"]=>
    string(2) "CH"
    ["is_vat_exempt"]=>
    string(0) ""
    ["calculated_shipping"]=>
    string(0) ""
    ["meta_data"]=>
    string(2) "[]"
  }
}
```
</details>
