### ISSUE TITLE
paypal payment without customer information

### ISSUE THREAD

**Issue by ateacme** [woocommerce/woocommerce-paypal-payments#1566]
### Describe the Bug

Hi, in last few days on website labartdog.com we have had two orders from different new customers not logged that have chosen to pay with paypal from the product page and have not entered any data useful for shipping. So we needed to contact them through the email address received from paypal and ask them name, surname, adress, phone.... in this way they have not even accepted the conditions of sale of our site... how it can be possible? can you pleas double check and fix this problem as soon as possibile?

### To Reproduce

1. Go to a prduct, for example https://labartdog.com/prodotto/biopar-camouflage/
2. Click on the size (120)
3. Scroll down to Paypal
4. See error -> paypal login without enter our data on mya website

### Expected Behavior

I knew that users, after accessing paypal, still needed to enter data on my site to complete the purchase but obviously this is not the case, or these data are not saved

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 7.9.0
 - Plugin Version 2.2.0
 - Browser [e.g. Chrome, Safari] and Version all the browsers
 - Any other plugins installed:
 <html><body>

Advanced Dynamic Pricing for WooCommerce |   | by AlgolPlus – 4.4.3
-- | -- | --
AfterShip Tracking - All-In-One WooCommerce Order Tracking (Free plan available) |   | by AfterShip – 1.17.0
iThemes Security |   | by iThemes – 8.1.7
Chaty |   | by Premio – 3.1.2
Classic Widgets |   | by WordPress Contributors – 0.3
Claue Addons |   | by JanStudio – 1.2.7
Customer Reviews for WooCommerce |   | by CusRev – 5.31.3
Yoast Duplicate Post |   | by Enrico Battocchi & Team Yoast – 4.5
Embed Google Fonts |   | by Adrian Mörchen + Contributors – 3.1.0
GDPR Cookie Compliance |   | by Moove Agency – 4.12.4
GTranslate |   | by Translate AI Multilingual Solutions – 3.0.3
Smash Balloon Instagram Feed |   | by Smash Balloon – 6.1.6
WPBakery Page Builder |   | by Michael M - WPBakery.com – 6.13.0
PixelYourSite |   | by PixelYourSite – 9.4.0.1
Redirection |   | by John Godley – 5.3.10
Slider Revolution |   | by ThemePunch – 6.6.14
SiteGround Optimizer |   | by SiteGround – 7.3.4
Woocommerce Product Image Color Picker |   | by MWA – 1.3.3
WooCommerce Advanced Shipping |   | by Jeroen Sormani – 1.1.2
WooCommerce B2B |   | by Code4Life – 3.2.5
WooCommerce PayPal Payments |   | by WooCommerce – 2.2.0
WooCommerce PDF Invoices Italian Add-on |   | by laboratorio d'Avanguardia – 0.7.2
PPOM for WooCommerce |   | by Themeisle – 32.0.8
WooCommerce |   | by Automattic – 7.9.0
Yoast SEO |   | by Team Yoast – 20.12
WPA WooCommerce Product Bundle |   | by WPAddon – 1.2.6
WooCommerce Variation Swatch |   | by WPAddon – 1.1.7
WPForms Lite |   | by WPForms – 1.8.2.3
YITH WooCommerce Ajax Product Filter |   | by YITH – 4.24.1
YITH WooCommerce Wishlist |   | by YITH – 3.23.0

</body>
</html>Advanced Dynamic Pricing for WooCommerce 	  	by AlgolPlus – 4.4.3
[AfterShip Tracking - All-In-One WooCommerce Order Tracking (Free plan available)](http://aftership.com/) 	  	by AfterShip – 1.17.0
[iThemes Security](https://ithemes.com/security) 	  	by iThemes – 8.1.7
Chaty 	  	by Premio – 3.1.2
[Classic Widgets](https://wordpress.org/plugins/classic-widgets/) 	  	by WordPress Contributors – 0.3
[Claue Addons](http://www.janstudio.net/) 	  	by JanStudio – 1.2.7
[Customer Reviews for WooCommerce](https://wordpress.org/plugins/customer-reviews-woocommerce/) 	  	by CusRev – 5.31.3
[Yoast Duplicate Post](https://yoast.com/wordpress/plugins/duplicate-post/) 	  	by Enrico Battocchi & Team Yoast – 4.5
[Embed Google Fonts](https://github.com/moewe-io/embed-google-fonts) 	  	by Adrian Mörchen + Contributors – 3.1.0
[GDPR Cookie Compliance](https://wordpress.org/plugins/gdpr-cookie-compliance/) 	  	by Moove Agency – 4.12.4
[GTranslate](https://gtranslate.io/?xyz=998) 	  	by Translate AI Multilingual Solutions – 3.0.3
[Smash Balloon Instagram Feed](https://smashballoon.com/instagram-feed) 	  	by Smash Balloon – 6.1.6
[WPBakery Page Builder](http://wpbakery.com/) 	  	by Michael M - WPBakery.com – 6.13.0
[PixelYourSite](http://www.pixelyoursite.com/) 	  	by PixelYourSite – 9.4.0.1
[Redirection](https://redirection.me/) 	  	by John Godley – 5.3.10
[Slider Revolution](https://www.sliderrevolution.com/) 	  	by ThemePunch – 6.6.14
[SiteGround Optimizer](https://it.siteground.com/) 	  	by SiteGround – 7.3.4
[Woocommerce Product Image Color Picker](https://www.milanoweb.agency/) 	  	by MWA – 1.3.3
[WooCommerce Advanced Shipping](https://jeroensormani.com/woocommerce-advanced-shipping/) 	  	by Jeroen Sormani – 1.1.2
[WooCommerce B2B](https://woocommerce-b2b.com/) 	  	by Code4Life – 3.2.5
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) 	  	by WooCommerce – 2.2.0
[WooCommerce PDF Invoices Italian Add-on](https://ldav.it/plugin/woocommerce-pdf-invoices-italian-add-on/) 	  	by laboratorio d'Avanguardia – 0.7.2
[PPOM for WooCommerce](https://themeisle.com/plugins/ppom-pro/) 	  	by Themeisle – 32.0.8
[WooCommerce](https://woocommerce.com/) 	  	by Automattic – 7.9.0
[Yoast SEO](https://yoa.st/1uj) 	  	by Team Yoast – 20.12
[WPA WooCommerce Product Bundle](http://wpaddon.net/wc-product-bundle) 	  	by WPAddon – 1.2.6
[WooCommerce Variation Swatch](http://wpaddon.net/wc-variation-swatch) 	  	by WPAddon – 1.1.7
[WPForms Lite](https://wpforms.com/) 	  	by WPForms – 1.8.2.3
[YITH WooCommerce Ajax Product Filter](https://wordpress.org/plugins/yith-woocommerce-ajax-navigation/) 	  	by YITH – 4.24.1
[YITH WooCommerce Wishlist](https://yithemes.com/themes/plugins/yith-woocommerce-wishlist/) 	  	by YITH – 3.23.0

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @ateacme 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. 
You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
