### ISSUE TITLE
Bug in version 2.2.0: Some of the orders return without customer information.

### ISSUE THREAD

**Issue by samisraeli** [woocommerce/woocommerce-paypal-payments#1567]
### Describe the Bug
Since we updated the plugin to version 2.2.0 we are facing problem with the plugin.
Some of the orders return without customer information.

Log:
2023-07-30T09:16:33+00:00 INFO WC order YYYYYY has been processed after approval in PayPal.
2023-07-30T09:16:33+00:00 INFO Webhook has been handled by CHECKOUT.ORDER.APPROVED
2023-07-30T09:16:40+00:00 DEBUG  https://api.paypal.com/v2/checkout/orders/XXXXXX
Response Debug ID: 1e0b8b7d5e897
Response: Array
(
    [code] => 200
    [message] => OK
)
I changed the data with YYYYYY and XXXXXXX.
Sam

**Comment by SydeKrystian** [comment]
Hello @samisraeli 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian

**Comment by samisraeli** [comment]
Thank you, I'll try your fix.
Sam
