### ISSUE TITLE
Orders are being placed with an empty name and address

### ISSUE THREAD

**Issue by dhwrd** [woocommerce/woocommerce-paypal-payments#1570]

**Comment by SydeKrystian** [comment]
Hello @danh-dev 

I noticed that the problem you're experiencing has been reported before in this issue #1522. You can follow the progress of the fix on that thread. 

We have developed a fix package that should address the current issue. You can download this package from [here](https://drive.google.com/uc?export=download&id=1DkB2KNllIiunvf73PEeTiX5wxD2vl8d6).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
