### ISSUE TITLE
PayPal authorizes order but order in WooCommerce is missing all customer data

### ISSUE THREAD

**Issue by kelly-thorn** [woocommerce/woocommerce-paypal-payments#1572]
### To Reproduce

Unfortunately I do not know how to reproduce the error but I will at least describe what I do know.

Since applying update 2.2.0 we have had at least one order everyday where the order is approved by PayPal, however, the order that ends up in WooCommerce does not contain the users email, billing, and shipping addresses. Despite this we have had successful PayPal transactions that did include all of the previously mentioned items as well so I am not sure how to reproduce this.

For reference we are using the WooCommerce Blockbase theme version 3.1.12

### Environment

 - WordPress Version 6.2.1
 - WooCommerce Version 7.9.0
 - Plugin Version 2.2.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed
 - 
Redirection for Contact Form 7 by Qube One – 2.9.2
weLaunch Framework by weLaunch.io – 1.0.19
Accordion Blocks by Phil Buchanan – 1.5.0
Additional Order Filters for WooCommerce by Anton Bond – 1.10
Address Autocomplete by HighAddons – 1.0.7
Advanced Custom Fields PRO by WP Engine – 6.1.7
Afterpay Gateway for WooCommerce by Afterpay – 3.5.4
Ajax Search Pro by Ernest Marcinko – 4.26.2
Akismet Anti-Spam: Spam Protection by Automattic - Anti Spam Team – 5.2
Checkout Rate Limiter by BrianHenryIE – 1.3.1
Carousel Slider Block for Gutenberg by – 1.0.8
Contact Form 7 by Takayuki Miyoshi – 5.7.7
DCJ Block Customizations by Dotcomjungle, Inc. – 1.0.0
Dcj Blog Product Highlight by The WordPress Contributors – 0.1.0
Dotcomjungle ERP Integration by Dotcomjungle, Inc. – 1.0.22
DCJ Pro Deals by Dotcomjungle, Inc. – 1.0.0
Dcj Product Cat Heading by The WordPress Contributors – 0.1.0
Dotcomjungle Product Purchase Restrictions by Dotcomjungle, Inc. – 1.0.0
Dcj Product Specs by The WordPress Contributors – 0.1.0
DCJ Quest by Dotcomjungle, Inc. – 1.0.0
Duplicate Page by mndpsingh287 – 4.5.2
Facebook for WooCommerce by Facebook – 3.0.27
FG Magento to WooCommerce Premium by Frédéric GILLES – 2.64.4
Guest Order Tracking for WooCommerce by Algoritmika Ltd – 2.1.2
Header and Footer Scripts by Digital Liberation – 2.2.1
Smash Balloon Instagram Feed by Smash Balloon – 6.1.5
iThemes Security Pro by iThemes – 7.3.1
Klaviyo by Klaviyo, Inc. – 3.2.1
HubSpot All-In-One Marketing - Forms, Popups, Live Chat by HubSpot – 10.1.24
Listo by Takayuki Miyoshi – 1.6
MWB HubSpot for WooCommerce by MakeWebBetter – 1.4.8
Meta Box by MetaBox.io – 5.7.3
Nextend Social Login by Nextendweb – 3.1.9
Meta pixel for WordPress by Facebook – 3.0.12
Password Protect WordPress Lite by BWPS – 1.8.8
Pixel Manager for WooCommerce (Premium) by SweetCode – 1.32.5
Quick Alt Editor by Arsmoon – 1.0.2
reCaptcha for WooCommerce by I Thirteen Web Solution – 2.45
Refersion for WooCommerce by Refersion, Inc. – 4.9.2
Relevanssi by Mikko Saari – 4.20.0
Responsive Block Control by Sascha Paukner – 1.2.7
Route App by Route – 2.2.4
Sharpens Display by The WordPress Contributors – 0.1.0
SpinupWP by SpinupWP – 1.5.1
Stackable - Gutenberg Blocks (Premium) by Gambit Technologies, Inc – 3.9.1
Sucuri Security - Auditing, Malware Scanner and Hardening by Sucuri Inc. – 1.8.39
SVG Support by Benbodhi – 2.5.5
UberMenu 3 - The Ultimate WordPress Mega Menu by Chris Mavricos, SevenSpark – 3.7.7
WooCommerce Blocks by Automattic – 10.4.2
Variation Swatches for WooCommerce by Emran Ahmed – 2.0.24
WooCommerce Extended Coupon Features PRO by Soft79 – 3.1.4.1
Avalara AvaTax by Avalara – 2.5.0
WooCommerce Back In Stock Notifications by WooCommerce – 1.6.3
WooCommerce Buying Guide by weLaunch – 1.2.3
WooCommerce Stripe Gateway by WooCommerce – 7.4.1
WooCommerce Gift Cards by WooCommerce – 1.16.3
WooCommerce Google Analytics Integration by WooCommerce – 1.8.3
WooCommerce PayPal Payments by WooCommerce – 2.2.0
PDF Invoices & Packing Slips for WooCommerce by WP Overnight – 3.5.6
WooCommerce Google Product Feed by Ademti Software Ltd. – 10.10.4
WooCommerce Products Compare by Themesquad – 1.2.0
WooCommerce Sequential Order Numbers Pro by SkyVerge – 1.20.1
WooCommerce Shipment Tracking by WooCommerce – 2.3.1
WooCommerce Table Rate Shipping by WooCommerce – 3.1.1
WooCommerce WishLists by Element Stark – 2.2.10
WooCommerce by Automattic – 7.9.0
WooSidebars by WooCommerce – 1.4.6
Hustle by WPMU DEV – 7.8.0
Yoast SEO Premium by Team Yoast – 20.9
Yoast SEO by Team Yoast – 20.10
WP Mail SMTP by WP Mail SMTP – 3.8.2
WP Product Feed Manager by Michel Jongbloed – 1.49.1
WP Rocket by WP Media – 3.14.2.1
Yoast SEO: WooCommerce by Team Yoast – 15.7
Smart Coupons For WooCommerce Coupons by WebToffee – 1.4.8
Zendesk Chat Widget by Zendesk – 1.4.18

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by erick3000** [comment]
Does the payment happen to be from Netherlands and using IDeal?

**Comment by kelly-thorn** [comment]
Not that I'm aware of.


*Kelly ThornDotcomjungle Inc.*

Ashland, Oregon 97520
541.690.4020 <5416904020>
www.dotcomjungle.com
***@***.***

**Comment by SydeKrystian** [comment]
Hello @kelly-thorn 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://f005.backblazeb2.com/file/Inpsyde/ShareX/2023/08/PCP-1896-woocommerce-paypal-payments%20%286%29.zip).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
