### ISSUE TITLE
Error with the paypal plugin WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by AaronMorganmedia** [woocommerce/woocommerce-paypal-payments#1573]
Today I updated the Paypal Plugin WooCommerce PayPal Payments in a customer web but after updating I just keep getting the same message in the plugin 

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/141408961/1d51e206-a4a3-4295-bafc-6e9e2043b3f9)

The main problem is that when I go to the product page and try to pay with th3 option of " 3 month" I get stuck in the loading screen.

Pls some help would be aprreciate in order to solve this problem

**Comment by SydeKrystian** [comment]
Hello @AaronMorganmedia 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
