### ISSUE TITLE
Payment successful but Return back to checkout page internal server error

### ISSUE THREAD

**Issue by guan7008** [woocommerce/woocommerce-paypal-payments#1574]
### To Reproduce

1. Go To Checkout
2. Click on PayPal
3. Paid successfully in PayPal
4. WooCommerce show Internal Server Error

### Screenshots

![WhatsApp Image 2023-08-04 at 17 11 47](https://github.com/woocommerce/woocommerce-paypal-payments/assets/47512585/59b2f8e2-cc7c-43b9-9175-8684d904e4f5)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @guan7008 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
