### ISSUE TITLE
Paypal orders going ON HOLD status

### ISSUE THREAD

**Issue by sileska** [woocommerce/woocommerce-paypal-payments#1576]
I am using WC paypal pluging in my WP site
I have other websites and the plugin works fine
on this site, when customer pays, the order goes into ON HOLD status
I have checked with paypal and they dont see any issues on my account
i get these messages

Awaiting payment. Order status changed from Pending payment to On hold.

PayPal order payment is set to PENDING status, details: The captured payment is pending manual review.

**Comment by SydeKrystian** [comment]
Hello @sileska 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
