### ISSUE TITLE
Duplicated Order

### ISSUE THREAD

**Issue by agentstorepro** [woocommerce/woocommerce-paypal-payments#1577]
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED CardButtonGateway.php:310 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED OrderEndpoint.php:577 Order status changed from Pending payment to Failed.

Wordpress: 6.2.2
Woocommerce: 7.9.0

**Comment by dakman** [comment]
yes also having the same issue...  two orders appear and let me guess ... one is blank and one is filled in?? going to attempt replicating this in the sandbox

**Comment by dakman** [comment]
yes also having the same issue...  two orders appear one is blank and one is filled in

**Comment by SydeKrystian** [comment]
Hello @agentstorepro 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://f005.backblazeb2.com/file/Inpsyde/ShareX/2023/08/PCP-1896-woocommerce-paypal-payments%20%286%29.zip).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian
