### ISSUE TITLE
Empty Shipping / Invoice address

### ISSUE THREAD

**Issue by web4studio** [woocommerce/woocommerce-paypal-payments#1579]
Hi

We got four orders payed successful with paypal, but at the backend inside the order the address information is missing.
Pls take a look at my screenshots.

Woo + WP + PayPal Plugin are at the lasted version.

Any idea?
Many thx
Nadine

<img width="1293" alt="Bildschirmfoto 2023-08-07 um 12 48 27" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/69577864/20347fa4-bdc7-4de1-a101-a6e9b7cb1225">
<img width="1282" alt="Bildschirmfoto 2023-08-07 um 12 48 16" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/69577864/39ab35e0-5658-43ec-ac36-67f7234fdc42">
<img width="2549" alt="Bildschirmfoto 2023-08-07 um 12 52 20 Kopie" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/69577864/aa58b6fc-6d64-4e1d-a6c4-a7b6689db4a8">

**Comment by SydeKrystian** [comment]
Hello @web4studio 

I noticed that the problem you're experiencing has been reported before in this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/1522. You can follow the progress of the fix on that thread.

We have developed a fix package that should address the current issue. You can download this package from [here](https://f005.backblazeb2.com/file/Inpsyde/ShareX/2023/08/PCP-1896-woocommerce-paypal-payments%20%286%29.zip).

After downloading the package, install it in your WordPress environment. This should overwrite the current problematic version and mitigate the issue. Alternatively, you can revert to the previous version of the plugin until a more permanent fix is implemented. You can download the previous version from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

Remember to test after installation to ensure the problem has been resolved. Should the problem persist or if you encounter any other issues, please don't hesitate to reach out to us by [support request.](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help)

Kind Regards,

Krystian

**Comment by web4studio** [comment]
Hey there

SOLVED!
Many thx for the patch. This was 100% the solution.

Nadine
