### ISSUE TITLE
ACDC Expiry Placeholder and Label mismatch

### ISSUE THREAD

**Issue by Chaithi** [woocommerce/woocommerce-paypal-payments#158]
### Describe the bug
In checkout page, when using ACDC, the Expiry date is format 'MM/YY', but the placeholder is listed as 'MM/YYYY' causing confusion.

**Comment by InpsydeNiklas** [comment]
Hi Rob,
There are some UI improvements planned for the next release and this is among them.
We will get back to you with more details.
Kind regards,
Niklas

**Comment by Chaithi** [comment]
Change [line 90](https://github.com/woocommerce/woocommerce-paypal-payments/blob/e2cf37297ae10d0329f99a2b3ef55a8e1112c5ce/modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js#L90) to 
`placeholder: this.defaultConfig.hosted_fields.labels.mm_yy,`

Change [line 670](https://github.com/woocommerce/woocommerce-paypal-payments/blob/e13dfad27c862c64d6d85ce86d03b51c7e72465f/modules/ppcp-button/src/Assets/class-smartbutton.php#L670) to 
`'mm_yy'            => __( 'MM/YY', 'woocommerce-paypal-payments' ),`
