### ISSUE TITLE
Single Product Purchase Missing Extra Information (881)

### ISSUE THREAD

**Issue by delboy1966** [woocommerce/woocommerce-paypal-payments#1581]
Some of our products have extra options for the buyer to fill in, via a text box, this uses the "Extra Option Product" plugin.

It seems that if the buyer is just purchasing that one item and on the item page selects "PayPal" button, even though they have filled in the extra options box, the details are not carried across to the checkout. They are however if they continue as normal and go to the checkout without logging into PayPal first from the products page.

 - WordPress Version 6.2.2
 - WooCommerce Version 7.9.0
 - WooCommerce PayPal Payments 2.2.0

**Comment by InpsydeNiklas** [comment]
Hi @delboy1966 
Various plugins add "extra options" to your products, and supporting all of them on the single product page is not trivial.
But there are open issues here on GitHub regarding support for the official [Product Add-Ons](https://woocommerce.com/products/product-add-ons/?aff=10486&cid=1131038) plugin in #492. And the support for additional third-party plugins such as the "Extra Option Product" plugin may be handled in #732.

So when in doubt, I suggest commenting with a link to the plugin you are using in the #732 issue, or better, [contacting the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for more guidance. Thanks!
