### ISSUE TITLE
TeraWallet does not show up on cart or checkout page

### ISSUE THREAD

**Issue by motherjai69** [woocommerce/woocommerce-paypal-payments#1582]
### Describe the Bug
The TeraWallet connection for woocommerce is set up as it is supposed to be to work properly, everything is checked on and the option to use the balance in the wallet is not available in the shopping cart or checkout page.

How do I get the wallet to be an option for payment in the shopping cart and checkout page?

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @motherjai69 
TeraWallet is not a feature provided by the WooCommerce PayPal Payments plugin. So your request seems to be related to a third-party plugin. Have you tried reaching out to the TeraWallet support team?
If you need any assistance with the PayPal Payments setup and configuration, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

**Comment by motherjai69** [comment]
It is woocommerce shopping cart that lists the woowallet (terawallet) as an option but then does not display it in the customer side. So yes it is a woocommerce problem. Quit trying to push the blame elsewhere. Jennifer Lawson On Aug 9, 2023 1:19 AM, Niklas Gutberlet ***@***.***> wrote:
Hi @motherjai69
TeraWallet is not a feature provided by the WooCommerce PayPal Payments plugin. So your request seems to be related to a third-party plugin. Have you tried reaching out to the TeraWallet support team?
If you need any assistance with the PayPal Payments setup and configuration, please consider reaching out to the support team directly for more guidance. Thanks!

**Comment by InpsydeNiklas** [comment]
@motherjai69 WooCommerce, PayPal Payments, and TeraWallet are three separate pieces of software that are developed and supported by different teams. If you encounter any problems with the TeraWallet extension, I suggest contacting the TeraWallet support for more guidance: https://standalonetech.com/forum/terawallet/

The [PayPal Payments support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) can only help you with questions or issues relating to the [PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) plugin.
In any case, this GitHub repository is not the right place for support questions. Please use the support links provided above if you need any more guidance. Thank you!
