### ISSUE TITLE
Advanced Card Processing is not showing up

### ISSUE THREAD

**Issue by Aurarum** [woocommerce/woocommerce-paypal-payments#1584]
All features are enabled.
Advanced Card Processing is not showing up as a payment method.
Latest 2.2.0 plugin version

**Comment by InpsydeNiklas** [comment]
Hi @Aurarum 
Your issue may be something for the support team to investigate, as GitHub is meant as a place for confirmed bugs. To help you better, we would need more details about your site, such as a copy of your WooCommerce system report. For the best possible guidance, I suggest [reaching out to the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  Thanks!
