### ISSUE TITLE
ppcp-order-tracking -> MetaBoxRenderer HPOS compatibility issues (1934)

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-paypal-payments#1587]
The following potential issue was found when auditing PayPal Payments for HPOS compatibility.
Reported by Masum from Alpha. 

Potential Impact: Metabox might not be rendering in new edit-order pages when COT is data source ([ref](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions))

1. https://github.com/woocommerce/woocommerce-paypal-payments/blob/f25f5eefa899015ae461c7d65842893ed2bd978a/modules/ppcp-order-tracking/src/MetaBoxRenderer.php#L76

2. https://github.com/woocommerce/woocommerce-paypal-payments/blob/f25f5eefa899015ae461c7d65842893ed2bd978a/modules/ppcp-order-tracking/src/MetaBoxRenderer.php#L125

HPOS expected to roll out in a couple of months, thus assigning a `Priority: High` label to this issue.

I didn't see these in the other issue for HPOS compatibility https://github.com/woocommerce/woocommerce-paypal-payments/issues/1555 .

**Comment by Dinamiko** [comment]
Fixed in #1561.
