### ISSUE TITLE
WooCommerce PayPal Payments causes Analytics page to render empty

### ISSUE THREAD

**Issue by jordanmaurice** [woocommerce/woocommerce-paypal-payments#1590]
### Describe the Bug

When WooCommerce PayPal Payments v.2.2.0 is installed, the Analytics Page is empty. 

### To Reproduce

1. Install WooCommerce PayPal payments 2.0.4 or later
2. Click on Analytics
3. Observe empty grey page in lieu of analytics data

Console shows the following javascript errors, resulting from:
/wp-content/plugins/woocommerce/assets/client/admin/currency/index.js?ver=8.0.1

Uncaught TypeError: Cannot read properties of undefined (reading 'getSetting')
    at index.js?ver=8.0.1:1:4434
    at index.js?ver=8.0.1:1:4643
index.js?ver=8.0.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'CurrencyFactory')
    at index.js?ver=8.0.1:2:638484
    at index.js?ver=8.0.1:2:767026
    at index.js?ver=8.0.1:2:767069
index.js?ver=8.0.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'CurrencyContext')
    at 95817 (index.js?ver=8.0.1:2:287207)
    at i (index.js?ver=8.0.1:2:472913)
    at index.js?ver=8.0.1:2:486407
    at index.js?ver=8.0.1:2:583071
    at index.js?ver=8.0.1:2:583107

### Screenshots

N/A Empty screen

### Expected Behavior

Analytics data/graphs should render

### Actual Behavior

Empty screen is shown

### Environment

 - WordPress Version 6.2.2
 - WooCommerce Version 8.0.1
 - Plugin Version 2.2.0, confirmed happening as old as 2.0.4
 - Browser [e.g. Chrome, Safari] and Version - Happens in Chrome/Firefox, I'm sure others.
 - Any other plugins installed - Tested with all other plugins disabled, only happens with paypal payments activated

**Comment by InpsydeNiklas** [comment]
Hi @jordanmaurice 
I cannot reproduce the reported behavior, and the Analytics page is showing on my end with PayPal Payments enabled. Can you please check if the behavior persists after disabling/re-enabling WooCommerce and installing the latest [PayPal Payments pre-release version 2.2.1-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.2.1-rc1)?

The console error is generated from the core WooCommerce plugin, so maybe the [WooCommerce support team](https://wordpress.org/support/plugin/woocommerce/) can provide additional guidance.

**Comment by InpsydeNiklas** [comment]
As we haven't heard back from you and are unable to reproduce the reported issue, we'll close this GitHub issue for now.
We kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need any additional assistance.
Thank you for your understanding!
