### ISSUE TITLE
There are no payment methods available in our woocommerce store

### ISSUE THREAD

**Issue by eelnivek** [woocommerce/woocommerce-paypal-payments#1591]
<html>
<body>

  |  
-- | --
API Credentials
Status: Connected

</body>
</html>

**Comment by Sirvijver** [comment]
Hello @eelnivek 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Normally I would try to give you a quick support response on your issue, but we have not received any details on your site, so we can't investigate anything on the issue or see if we can see any errors. When you engage us via the support interface, please add the system report, logs and any screenshots, errors or other details that you could share with us.

I will close this thread and wait for you to open a new one with our support team.

Kind regards, 
Joost
