### ISSUE TITLE
Woocommerce order coming through with no details after using PayPal Blocks v2.2.0

### ISSUE THREAD

**Issue by Jeff-Coons** [woocommerce/woocommerce-paypal-payments#1593]
### Describe the Bug

When a user uses the PayPal block, the order comes through with no data (name, email, address, phone, etc.). However, we are getting a PayPal transaction ID that shows all the details missing from the order.

### To Reproduce

I haven't been able to reproduce the issue. We've seen users that have paid via PayPal (normal & pay later) without issue. However, some orders seem to be coming in blank.

From one customer who sent over the steps taken when the bug occured:
1) Loaded up my cart
2) Clicked View Cart
4) Choose to do a normal checkout with credit card (i.e. not Paypal, GPay, etc)
5) At this point - changed my mind and decided to click "pay with PayPal" instead of entering my shipping/billing information
6) PayPal login/pop up opened - I logged in and selected my paypal information and confirmed
7) Once this happened, the pop up closed and I was back on your site with shipping address filled in but billing address blank and payment information showing "Payed with Paypal", the order details were still in the side bar on the right
8) The order didn't look fully placed to me so I just filled in the same address for billing (my normal home address) and clicked place order
9) On Place Order click, I got an error that said "Your Cart is Empty"
10) Clicked on View Cart and indeed, the cart was now empty
11) Went over to paypal and saw that the money was debited from my account and that the order was placed

### Screenshots
![Order_Showing_Blank_Data](https://github.com/woocommerce/woocommerce-paypal-payments/assets/7240384/c6b79a5e-ed34-4019-bbf6-de0d78ba8e3e)

### Expected Behavior

For user data to come through after placing an order.

### Actual Behavior

User data missing completely after order is placed. Issue is inconsistent and user data is available via PayPal (by using transaction id)

### Environment

 - WordPress Version: 6.3
 - WooCommerce Version: 8.0.1
 - Plugin Version: 2.2.9
 - Any other plugins installed: WooCommerce Blocks (10.8.2)

### Additional Details

I haven't seen, nor have we received, any errors in the logs. There was nothing to indicate that an order had failed or that there was an issue. It was only noticed as we began trying to fulfill the order and realized that there was no information. Since the first instance, we've seen 4 out of 30 PayPal specific orders come through with no information.

**Comment by PaulProe** [comment]
Same issue on my site. Seems to have occurred within the last 7 days. Not consistent, out of 9 orders processed thru PayPal, 5 have come back without customer information. To salvage order, customer data must be manually entered from PayPal Account

**Comment by nick-stulane** [comment]
Same issue here it seems to be on some orders using PayPal. 

We also have shipping information missing so they are able to checkout with free postage. we had an order from Switzerland come in and they checked out but we only ship to the UK and we do not even have shipping methods set up for out of the UK.

we also have a click-and-collect plugin and they were able to select this shipping method and then skip the selection of the day/time which is not possible normally.

As a test, I have disabled the large yellow PayPal/Pay Later buttons on the cart and checkout.

**Comment by Sirvijver** [comment]
Hello @Jeff-Coons, @PaulProe and @nick-stulane,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This is, however, a known issue, and we have shared most details on this matter via the wp.org forum via this thread:
https://wordpress.org/support/topic/details-being-deleted-no-customer-information-on-order/

The fix is already available in our current release candidate here, or you could revert to the previous [release 2.1.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.1.0)

For now, I will close this thread.

Kind regards, 
Joost

**Comment by Jeff-Coons** [comment]
Hey Joost,

Thank you for sending over this information! I spent quite a lot of time googling and hadn't come across any information regarding this, hence why I opened up an issue here.

Much appreciated and thanks again!
