### ISSUE TITLE
Inconsistent error

### ISSUE THREAD

**Issue by okancolakup** [woocommerce/woocommerce-paypal-payments#1596]
[11-Aug-2023 05:45:58 UTC] PHP Fatal error:  Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\PayPalApiException: [Error] Unknown error while connecting to PayPal. Status code: 0. in ...wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/PartnerReferrals.php:101

I sometimes get this error randomly briefly. The issue is not consistent and it goes away on its own. I've seen it in the error log of my website.

**Comment by okancolakup** [comment]
WordPress version 6.3
Active theme: Geeks Child (version 1.2.14)
Current plugin: WooCommerce PayPal Payments (version 2.2.0)
PHP version 8.1.21

(happened for another website with different theme as well)

**Comment by Sirvijver** [comment]
Hello @okancolakup 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We see this error mostly when the API credentials are invalid. In particular, when the merchant ID is wrong.
We recommend disconnecting and reconnecting your PayPal account to fix the credentials: https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account
The preferred way of connecting your account is via the connect wizard (blue button "Activate PayPal").

Please raise the advised support request if this does not resolve the issue for you. We will close this thread.
When/if you do, please also share the system report with us and some more complete logs.

Kind regards, 
Joost
