### ISSUE TITLE
now checkout and card page showig

### ISSUE THREAD

**Issue by dayankennedy** [woocommerce/woocommerce-paypal-payments#1598]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @dayankennedy 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

When you open this support thread, please provide at minimum the system report, so we can review and verify the issue. Also, the problem description you provided here is not clear, and we need more details on the issue you are facing! We will close this thread and wait for you to open a support request.

Kind regards, 
Joost
