### ISSUE TITLE
After selecting the Credit Card/Debit button, the other methods disappear and don't return on failure

### ISSUE THREAD

**Issue by websupporter** [woocommerce/woocommerce-paypal-payments#16]
Extracted from #4.

On failure, it would be nice to not have to try again and be able to select a different payment method. Right now, after selecting the Credit Card/Debit button, the other methods disappear and don't return on failure.

**Comment by jorgeatorres** [comment]
I believe the "X" in the Debit/Credit button is enough for this issue to be considered solved.
