### ISSUE TITLE
PayPal payment does not load and direct to Thank you page

### ISSUE THREAD

**Issue by hazalsema** [woocommerce/woocommerce-paypal-payments#1603]
### Describe the Bug

On my Woocommerce shop, PayPal payments do not load. After waiting long time, altough it shows an error on the payment, I see purchase in my orders without redirecting to Thank you page. Therefore I do not also recieve any e-mail for purchase. I see purchases only in my orders and PayPal account. 

### To Reproduce

1. Buy purchase on the check-out
2. Click on Paypal
3. Give PayPal infos to purchase
4. Wait to load that puchase will completed
5. See error that purchase failed

### Environment

 - WordPress Version: Version 6.2.2
 - WooCommerce Version: Version 8.0.2
 - Paypal Payments: Version 2.2.0
 - Browser Chrome, Safari

**Comment by SydeKrystian** [comment]
Hello @hazalsema 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
