### ISSUE TITLE
Mobile not showing Venmo

### ISSUE THREAD

**Issue by dougie-wougie** [woocommerce/woocommerce-paypal-payments#1604]
The plugin works on the web version find. On the mobile, the Venmo button is missing. I have woo commerce and using WP with Divi framework

<img width="793" alt="CleanShot 2023-08-16 at 13 39 11@2x" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/58369176/3da6c8f5-3888-4187-be87-4d5ddeffeb18">

![IMG_6786](https://github.com/woocommerce/woocommerce-paypal-payments/assets/58369176/c1050481-38e5-4dab-876e-83767b43a609)

**Comment by dougie-wougie** [comment]
This might be helpful. [aascv.org/shop](https://aascv.org/shop/)

**Comment by SydeKrystian** [comment]
Hello @dougie-wougie 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please open a support issue via the link provided above and provide us with more details, such as the system report and the plugin logs.

Kind regards,

Krystian
