### ISSUE TITLE
No me deja pagar por paypal

### ISSUE THREAD

**Issue by destellos1** [woocommerce/woocommerce-paypal-payments#1609]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hola, 

Has contactado al foro abierto de GitHub con una solicitud de soporte. Utilizamos GitHub principalmente para actividades de desarrollo, por lo que me gustaría pedirte que te pongas en contacto con el equipo de soporte directamente para obtener más orientación. Puedes hacerlo a través de este enlace: [enlace de ayuda](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Por favor, añade el informe del sistema, los registros y cualquier detalle que pueda ayudarnos a resolver este problema cuando crees un ticket de soporte. Cerraremos este hilo ahora.

Saludos cordiales,
Joost
