### ISSUE TITLE
Authentication with PayPal failed: Could not create token.

### ISSUE THREAD

**Issue by Arthur-Fohrer** [woocommerce/woocommerce-paypal-payments#1615]
### Describe the Bug

I cannot connect my paypal account. 

Since 2 days, the plugin is displaying me an error. 

### Screenshots

<img width="1213" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/127095907/f1098335-3c18-440f-9834-31629a86c7fd">

### Environment

 - WordPress Version: last version
 - WooCommerce Version: last version
 - Plugin Version: last version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @Arthur-Fohrer 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

I would suggest trying to onboard your account with [manual credential input.](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input)

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,

Krystian
