### ISSUE TITLE
Unable to display credit card payment menu

### ISSUE THREAD

**Issue by bksy0909** [woocommerce/woocommerce-paypal-payments#1616]
### Describe the Bug

I can't find the place to configure credit card payment. The backend shows that credit card payment is already displayed, but the website just can't display it

### To Reproduce

I can't find the place to configure credit card payment. The backend shows that credit card payment is already displayed, but the website just can't display it

### Screenshots
Stable occurrence of problems

1）Background settings
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48849993/82236466-9425-4745-bee3-4fbf891e0b73)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48849993/ec950214-1c9b-42d3-add8-8b4a603a8907)

2）Screenshot of website front-end payment，only paypal menu ，no credit card payment menu
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48849993/26e035aa-a9d5-4eb8-bb76-3249d4dcff59)

### Environment

 - WordPress Version
    6.3
 - WooCommerce Version
    8.0.1
 - Plugin Version
 2.2.0 
 - Browser [e.g. Chrome, Safari] and Version
 Chrome 116.0.5845.97
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @bksy0909 
It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For any questions regarding the plugin setup, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

The behavior you report is correct as the Standard Card Button is only available on the Checkout page: https://woocommerce.com/document/woocommerce-paypal-payments/#APMs-on-non-checkout-pages
Card payments are still possible by clicking the PayPal button e.g. when configuring the `Landing page` with `Billing`. This may require guest payments to be enabled in your PayPal merchant account, though.

We'll be closing this GitHub issue for now but the [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) is ready to assist you with any remaining questions. Thank you for your understanding!
