### ISSUE TITLE
Some Paypal Payment orders don't show customer details in woocommerce

### ISSUE THREAD

**Issue by bardepot** [woocommerce/woocommerce-paypal-payments#1619]
### Describe the Bug

Customer placed an order. In the woocommerce order data, there is no customer data available. Only shows IP Address and the Billing/shipping details is empty as well as the email address. 

### To Reproduce
Not sure on reproduction as some Paypal payment orders don't have problems.

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Expected Behavior

All customer data provided to be present in woocommerce order details

### Actual Behavior

Some Paypal payment orders do not have customer data

### Environment

 - WordPress Version 6.3
 - WooCommerce Version 8.0.2
 - Plugin Version 2.2.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @bardepot 
Apologies for the trouble! Please update PayPal Payments to the latest version 2.2.1 as this includes a fix for the reported issue.
If any questions remain after the update or if you need additional clarification, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

We'll close this GitHub issue for now. However, our support team is happy to assist you with your concerns. Thank you for your understanding!
