### ISSUE TITLE
Paypal Payments are not delivered to shop operator

### ISSUE THREAD

**Issue by innsitSoftware** [woocommerce/woocommerce-paypal-payments#1626]
Products can be ordered an payed via Paypal, but the money will not be transmitted to the shop operator Paypal Account.
On the Payment methods of the buyer the money will be debited.

**Comment by SydeKrystian** [comment]
Hello @innsitSoftware 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous. 

Lastly, could we request a full screenshot of the failed order page? We're particularly interested in seeing the order note, similar to the screenshot below:  

![](https://f005.backblazeb2.com/file/Inpsyde/ShareX/2023/08/uIAeoAWeNd.png)


We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
