### ISSUE TITLE
Something went wrong. Please try again or choose another payment source

### ISSUE THREAD

**Issue by TGY2023** [woocommerce/woocommerce-paypal-payments#1627]
When someone tries to purchase via Paypal in the checkout page, it starts to load the paypal popup, but then goes straight back to the checkout page with the error "Something went wrong. Please try again or choose another payment source".

This is mainly happening on mobile, I cant recreate it on desktop.

 - WordPress Version 6.3
 - WooCommerce Version 8.0.2
 - Plugin Version Version 2.2.1
 - Browser [e.g. Chrome, Safari] and Version Mobile
 - Any other plugins installed - Yes - multiple

**Comment by SydeKrystian** [comment]
Hello @TGY2023 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
