### ISSUE TITLE
Header Overflow Error

### ISSUE THREAD

**Issue by Petbeginners** [woocommerce/woocommerce-paypal-payments#1629]
### Describe the Bug

Steps to reproduce:

1) Use Google Chrome on merchant website
2) Go to PayPal express checkout
3) Click on PayPal express button to sign in
4) Sign in to Paypal
5) The screen just goes blank with a “Header Overflow” at the top

There are two versions of this issue:
– you are not logged into your pp account, it will ask again and again for your mailadress
– you are logged into your pp account, you’ll get a message “header overflow”
Testet with Chrome, FF, Safari, Opera, Chromium, cleared cache, no restrictions like ad-block or pop-up block

Reported also here: https://wordpress.org/support/topic/header-overflow-error/

### Expected Behavior

On clinking the PayPal express checkout button, it should allow the user to login but the plugin is throwing a header overflow error

 - WordPress Version - latest version 
 - WooCommerce Version - latest version
 - Plugin Version - latest version
 - Browser - Google Chrome
 

### Additional Details

i contacted Woocommerce PayPal Support and they were able to reproduce the issue. The engineers were not able to login as well to make payment. They have referred me to open a ticket here.

**Comment by Tjrvn** [comment]
Concerns this error:
https://github.com/woocommerce/woocommerce-paypal-payments/issues/1620

Solution for me was to use an alternative plugin.

**Comment by Petbeginners** [comment]
Hello, I disabled the Woocommerce PayPal plugin and installed an alternative PayPal plugin (https://wordpress.org/plugins/pymntpl-paypal-woocommerce/) and the checkout issue goes away when using PayPal express. There is no more "header overflow" messages. 

I can confirm that this is a bug with the plugin and something with this plugin that is causing the header overflow error.

**Comment by SydeKrystian** [comment]
Hello @Petbeginners 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.

Please clear the cache of your website as well as clean cookies from your browser. This is a common issue that users often face right after updating the plugin or going through the onboarding process again. If after trying the above solution, the issue remains unresolved, please let us know

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
