### ISSUE TITLE
No se conecta con el servidor de compras

### ISSUE THREAD

**Issue by Franciscovalino** [woocommerce/woocommerce-paypal-payments#1630]
### Describe the Bug

Pulsa el botos de G-PAY
### To Reproduce

DA vueltas como pansando
Se para y desaparece
Y pasado un rato(tarda bastante) da error :  El pago no se ha completado// Es ha producido un error al procesar el pedido.Vuelva a intentarlo

**Comment by SydeKrystian** [comment]
Hello @Franciscovalino 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
