### ISSUE TITLE
System error with paypal

### ISSUE THREAD

**Issue by crossworkx** [woocommerce/woocommerce-paypal-payments#1631]
<img width="1000" alt="Bildschirmfoto 2023-08-27 um 20 12 54" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/143349469/9d369df4-376d-4a68-9b4d-750aa69436a2">

Hello!
May you can help me to find out, whats wrong and how i can fix the problem with paypal payments. 
Since 3 Days it is not possible to pay with paypal and the attached file is displayed.
How can i fix that, do you have any ideas on how I can proceed to identify the error?
Many Thanks inadvance.

**Comment by SydeKrystian** [comment]
Hello @crossworkx 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Given the nature of your problem, I recommend reaching out directly to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport)

Whatever happens on the PayPal server side is usually PayPal's fault. We've been made aware that there have been some outages on their end in recent days

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
