### ISSUE TITLE
Security Header Not Valid

### ISSUE THREAD

**Issue by rie76** [woocommerce/woocommerce-paypal-payments#1632]
### To Reproduce

1. Go to '[www.](https://thrivewithlawrence.com/packages/)'
2. Click on 'package'
3. Create account and click paypal button

### Screenshots
<img width="1283" alt="Screenshot 2023-08-28 at 12 06 07 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/133986728/4b3835c6-6fff-4b80-af15-1d4c0b262fa5">

### Environment

 - WordPress Version 6.3
 - WooCommerce Version Version 8.0.2
 - Plugin Version-Version 8.0.2
 - Browser [e.g. Chrome, Safari] and Version Chrome -Version 116.0.5845.110 (Official Build) (arm64)
 - Any other plugins installed
 All In One WP Security, All-in-One Security and Firewall Premium, Classic Editor, Elementor, Essential Addons for Elementor, Facebook Chat Plugin - Live Chat Plugin for WordPress, Fluent Forms, LiteSpeed Cache, MailerLite - Signup forms (official), Paid Memberships Pro, Royal Elementor Addons, ShopLentor – WooCommerce Builder for Elementor & Gutenberg, Smash Balloon Instagram Feed, Under Construction, WooCommerce, WooCommerce PayPal Payments

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by rie76** [comment]
* Hitting the paypal button should redirect the user to the paypal login page but this error shows up instead.

**Comment by SydeKrystian** [comment]
Hello @rie76 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
