### ISSUE TITLE
fehler

### ISSUE THREAD

**Issue by phantasiali** [woocommerce/woocommerce-paypal-payments#1637]
### Describe the Bug

There is a mistake between paypal and CTX Feed. If I want to work with the CTX feed I get the message that see you on screenshot.
Wordpress send me a mail with "fehler-details". I hope that you can help me.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![2023-08-25 (1)](https://github.com/woocommerce/woocommerce-paypal-payments/assets/53369949/1eaf21ac-4b5f-42df-8e3d-c941d7f4c664)

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 230 der Datei /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php verursacht. Fehlermeldung: Uncaught TypeError: WooCommerce\PayPalCommerce\Subscription\SubscriptionModule::WooCommerce\PayPalCommerce\Subscription\{closure}(): Argument #2 ($post) must be of type WP_Post, array given, called in /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/class-wp-hook.php on line 310 and defined in /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:230
Stack trace:
#0 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}()
#1 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-content/plugins/webappick-product-feed-for-woocommerce/includes/helper.php(917): do_action()
#4 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-content/plugins/webappick-product-feed-for-woocommerce/admin/partials/woo-feed-edit-template.php(33): woo_feed_register_and_do_woo_feed_meta_boxes()
#5 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-content/plugins/webappick-product-feed-for-woocommerce/woo-feed.php(637): require('...')
#6 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/class-wp-hook.php(310): woo_feed_manage_feed()
#7 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#8 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-includes/plugin.php(517): WP_Hook->do_action()
#9 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-admin/admin.php(259): do_action()
#10 /mnt/web017/c1/10/512148410/htdocs/STRATO-apps/wordpress_02/app/wp-admin/index.php(10): require_once('...')
#11 {main}
  thrown

### Environment

 - WordPress Version **6.3**
 - WooCommerce Version **8.0.2**
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version **microsoft edge**
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hallo @phantasiali,

Sie haben sich an das offizielle GitHub-Forum mit einer Support-Anfrage gewandt. Wir nutzen GitHub hauptsächlich für Entwicklungsaktivitäten. Daher möchte ich Sie bitten, sich direkt an das [Support-Team zu wenden](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), um weitere Anleitung zu erhalten.

Wir sind über dieses Problem informiert und haben einen Fehlerbericht erstellt. Wir haben unsere Entwickler gebeten, sich mit Priorität darum zu kümmern. Falls Sie über Änderungen in der Situation informiert werden möchten, schauen Sie bitte in unseren GitHub-Fehlerbericht zu diesem Fall: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1628

Wir haben gerade eine Lösung für dieses Problem von unseren Entwicklern erhalten und ein Paket für Sie erstellt, das Sie hier herunterladen können:
https://drive.google.com/uc?export=download&id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP

Wir planen, dies so bald wie möglich als Version 2.2.2 zu veröffentlichen, jedoch befinden wir uns noch in Diskussion darüber. Bis dahin sollten Sie in der Lage sein, dieses Paket als vorübergehende Lösung zu verwenden, bis wir eine neue Version veröffentlichen.

Wir werden diesen Support-Thread schließen und empfehlen Ihnen, wie oben beschrieben ein Support-Ticket bei uns zu eröffnen, falls dies noch notwendig ist.

Mit freundlichen Grüßen,
Joost

====original english message====

Hello @phantasiali ,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We are aware of this issue and have opened a bug for and asked our developers to look into this with priority.
If you want to see if there are any changes in the situation, please check our GitHub issue for this case here: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1628

We just got a fix for this issue from our developers and created a package for you that you can download here:
https://drive.google.com/uc?export=download&id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP

We think we will try to release this as soon as possible as version 2.2.2, but we are still discussion this. For now, you should be able to use this package as a temporary fix until we do a next release.

We will close this support thread and advise you to open a support ticket with us as described above if this is still needed.

Kind regards,
Joost

**Comment by phantasiali** [comment]
Hello Joost,

 

thank you for the quikly help. But it does´t work. The problem is the same.

Is it possible to help me once moore? Thank´s a lot

 

Herzliche Grüße von Maria-Theresia Wolff

 



Maria-Theresia Wolff

Kalmüntener Str. 104 a

51467 Bergisch Gladbach

02202-2498280

 <https://www.phantasiali.de/> https://www.phantasiali.de/

 

Von: Joost van de Vijver ***@***.***> 
Gesendet: Montag, 28. August 2023 14:53
An: woocommerce/woocommerce-paypal-payments ***@***.***>
Cc: phantasiali ***@***.***>; Mention ***@***.***>
Betreff: Re: [woocommerce/woocommerce-paypal-payments] fehler (Issue #1637)

 

Hallo @phantasiali <https://github.com/phantasiali> ,

Sie haben sich an das offizielle GitHub-Forum mit einer Support-Anfrage gewandt. Wir nutzen GitHub hauptsächlich für Entwicklungsaktivitäten. Daher möchte ich Sie bitten, sich direkt an das Support-Team zu wenden <https://woocommerce.com/document/woocommerce-paypal-payments/#get-help> , um weitere Anleitung zu erhalten.

Wir sind über dieses Problem informiert und haben einen Fehlerbericht erstellt. Wir haben unsere Entwickler gebeten, sich mit Priorität darum zu kümmern. Falls Sie über Änderungen in der Situation informiert werden möchten, schauen Sie bitte in unseren GitHub-Fehlerbericht zu diesem Fall: #1628 <https://github.com/woocommerce/woocommerce-paypal-payments/issues/1628> 

Wir haben gerade eine Lösung für dieses Problem von unseren Entwicklern erhalten und ein Paket für Sie erstellt, das Sie hier herunterladen können:
https://drive.google.com/uc?export=download <https://drive.google.com/uc?export=download&id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP> &id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP

Wir planen, dies so bald wie möglich als Version 2.2.2 zu veröffentlichen, jedoch befinden wir uns noch in Diskussion darüber. Bis dahin sollten Sie in der Lage sein, dieses Paket als vorübergehende Lösung zu verwenden, bis wir eine neue Version veröffentlichen.

Wir werden diesen Support-Thread schließen und empfehlen Ihnen, wie oben beschrieben ein Support-Ticket bei uns zu eröffnen, falls dies noch notwendig ist.

Mit freundlichen Grüßen,
Joost

====original english message====

Hello @phantasiali <https://github.com/phantasiali>  ,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to reach out to the support team <https://woocommerce.com/document/woocommerce-paypal-payments/#get-help>  directly for more guidance.

We are aware of this issue and have opened a bug for and asked our developers to look into this with priority.
If you want to see if there are any changes in the situation, please check our GitHub issue for this case here: #1628 <https://github.com/woocommerce/woocommerce-paypal-payments/issues/1628> 

We just got a fix for this issue from our developers and created a package for you that you can download here:
https://drive.google.com/uc?export=download <https://drive.google.com/uc?export=download&id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP> &id=16GC-69a1JmA65HH0GIj4xOAQNL313hDP

We think we will try to release this as soon as possible as version 2.2.2, but we are still discussion this. For now, you should be able to use this package as a temporary fix until we do a next release.

We will close this support thread and advise you to open a support ticket with us as described above if this is still needed.

Kind regards,
Joost
