### ISSUE TITLE
WooCommerce PayPal Payments creating orders without customer details or shipping address

### ISSUE THREAD

**Issue by astimary** [woocommerce/woocommerce-paypal-payments#1638]
WooCommerce PayPal Payments plugin creating orders without any customer details including name, shipping and billing address.
I have to directly login to PayPal, search through and match the PayPal payment token to the correct order to find the payment details just so I can send customers their orders.

Screenshot of an order placed today and paid for with PayPal.

This has been ongoing for over a month now and it's getting old. I always keep all plugins up to date.

Please help me :(

![Screenshot 2023-08-29 151455](https://github.com/woocommerce/woocommerce-paypal-payments/assets/141553951/5a16a7a9-38ef-43f4-bf4d-fd015cc501b0)

**Comment by Sirvijver** [comment]
Hello @astimary 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you reported should have been resolved with our latest release (2.2.1). Please open a new support thread, as described above, if you still encounter this or any other issue. We will close this thread.

Kind regards, 
Joost
