### ISSUE TITLE
Payment method dropdown option label on edit order screen for ppcp-gateway option displaying wrong name (1965)

### ISSUE THREAD

**Issue by tankianann** [woocommerce/woocommerce-paypal-payments#1639]
When editing the order details->billing details->payment method in the wp dashboard, the label for the "ppcp-gateway" option is always labelled the currently active gateway, and not "PayPal".

Screenshot here: https://www.dropbox.com/scl/fi/1iig4004xy0uvtqzwcx75/ppcp-gateway-bug.jpg?rlkey=nzn3v161kgue8nyigowom7vki&dl=0

**Comment by InpsydeNiklas** [comment]
Hi @tankianann, thank you for reporting this issue. The behavior was addressed in #1661 and will be included in the next update. So I'll close this issue.
