### ISSUE TITLE
Advanced card processing not verifying address

### ISSUE THREAD

**Issue by imran-shc** [woocommerce/woocommerce-paypal-payments#1643]
Hi there.

All settings are ok but Paypal advanced card processing is not verifying 
Address Match: N
Postal Match: N
And sometimes failed to process card payments.
Please help to resolve this problem we have live site.

Thanks in advance.

**Comment by Sirvijver** [comment]
Hello @imran-shc 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have checked the address and postal code verification, and it is actually behaving as I would expect.
Postal codes are being checked/verified on the expected format for the country that was selected. The address is only checked if it is filled in (this is the same as the default WooCommerce verification).
Card payment can fail on many different causes, but this is not something I can respond to without see what errors were shown or what the logs say about these situations.

I would advise you to open a support thread as advised above and provide more details on how the order fail for every individual case you mentioned. Please also provide the system report, logs and possibly screenshot of the errors, so we can have a complete overview of the situation.
For now, I will close this thread, as we don't handle support cases on GitHub.

Kind regards, 
Joost
