### ISSUE TITLE
URGENT custody option PayPal

### ISSUE THREAD

**Issue by Trunkz8** [woocommerce/woocommerce-paypal-payments#1647]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Trunkz8** [comment]
Buenas,

Querría saber cómo desactivar la custodia de PayPal, ya que quiero poner pago a plazos para mis productos, desde los ajustes propios de woocommerce no me sale la opción.

**Comment by Trunkz8** [comment]
Hello,

I would like to know how to deactivate the PayPal custody, because I want to put payment in instalments for my products, from the woocommerce settings I don't get the option.

**Comment by SydeKrystian** [comment]
Hello @Trunkz8 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
