### ISSUE TITLE
Duplicate Orders with same PaypalID

### ISSUE THREAD

**Issue by nuil** [woocommerce/woocommerce-paypal-payments#1651]
### Describe the Bug

Customer orders on our Webshop and pays with Paypal. 
The Paypal Webhook triggers, the original order is marked as paid, but a new order is created and stored with the same transaction id.

### To Reproduce

Happens very rarely. Not been able to reproduce.

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/2334194/9695dc34-81d5-480a-a2f3-7f54a703a208)

### Expected Behavior

Order is marked as paid.

### Actual Behavior

No additional order is created.

### Environment

 - WordPress Version: 6.3.1
 - WooCommerce Version:  8.0.1
 - Plugin Version: 2.1

### Additional Details

We already upgraded to 2.2.2

**Comment by InpsydeNiklas** [comment]
Hi @nuil 
Thanks for getting in touch. Under certain conditions, a bug in version 2.2.0 could potentially lead to the creation of a second WooCommerce order following the arrival of a webhook. However, this issue has been resolved in later versions, and we're not aware of any other reports regarding duplicate orders with the latest plugin update 2.2.2.
If any issues persist for you using the latest plugin version, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for additional guidance.
We will close this GitHub issue for now. However, our support team is available to assist you with any concerns that may arise. Thank you for your understanding!
