### ISSUE TITLE
`$_POST` uses the wrong key to hold the shipping method (1969)

### ISSUE THREAD

**Issue by Rahmon** [woocommerce/woocommerce-paypal-payments#1652]
### Describe the Bug

When a user selects PayPal as a payment, WooCommerce PayPal Payments makes a request with the form data and tries to validate the fields. The form data is held by the form key in the request but before validating the fields, WooCommerce PayPal Payments adds the form fields to the `$_POST`.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/6010232/5729e403-3bd1-4e8c-b6e0-11e4b05bf33a)

Notice that the key `shipping_method[0]` should be `shipping_method: [local_pickup:18]`. When the WooCommerce PayPal Payments adds the form fields to the `$_POST` this field is added that way.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/6010232/d4e4e173-0064-4ebb-a36f-aeec374166e9)

That said, if a plugin relies on the key `shipping_method` to retrieve the data, it will fail.

### To Reproduce

One of the ways to observe this bug is by testing it with and without WooCommerce PayPal Payments enabled.

1. Add the code snippet below:

```php
add_filter(
	'woocommerce_checkout_posted_data',
	function( $data ) {
		
		$expected_key = ! empty( $_POST['shipping_method'] );
		$wrong_key    = ! empty( $_POST['shipping_method[0]'] );
		
		return $data;
	},
	10,
	1
);
```

2. Add a product to the cart and proceed to the checkout page

WooCommerce PayPal Payments **disabled**

1. Select a payment method and place the order
2. Result:
   - $expected_key: true
   - $wrong_key: false

WooCommerce PayPal Payments **enabled**

1. Select PayPal as the payment method and click on the PayPal button
2. Result:
   - $expected_key: false
   - $wrong_key: true

### Expected Behavior

The key `shipping_method` in the `$_POST` variable.

### Actual Behavior

The `$_POST` variable doesn't have the `shipping_method` key but `shipping_method[0]`.

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version 8.0.3
 - Plugin Version 2.2.2
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

Workaround to fix this issue:

```php
add_filter(
	'woocommerce_checkout_posted_data',
	function( $data ) {

		if ( empty( $data['payment_method'] ) || 'ppcp-gateway' !== $data['payment_method'] ) {
			return $data;
		}

		if ( ! empty( $data['shipping_method'][0] )  ) {
			return $data;
		}

		if ( empty( $_POST['shipping_method[0]'] ) ) {
			return $data;
		}

		$data['shipping_method'] = array( $_POST['shipping_method[0]'] );
		
		return $data;
	},
	10,
	1
);
```

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Rahmon 
Thanks for the detailed feedback. This will be looked into.
One alternative workaround, albeit one with more drawbacks, may be to disable the early validation:
`add_filter( 'woocommerce_paypal_payments_early_wc_checkout_validation_enabled', '__return_false' );`
And optionally enable the basic validation:
`add_filter( 'woocommerce_paypal_payments_basic_checkout_validation_enabled', '__return_true' );`
Before opening the PayPal popup window, this would validate the required checkout form fields only in the browser and not on the server.
