### ISSUE TITLE
PayPal Payment Loading in Checkout Page (Woo-commerce)

### ISSUE THREAD

**Issue by 543S** [woocommerce/woocommerce-paypal-payments#1657]
### To Reproduce

1. Go to 'Cart Page'
2. Click on 'Pay with PayPal Method'
3. Loading Without a Result

### Environment

 - WordPress Version ==> 6.3.1
 - WooCommerce Version ==> 8.0.3
 - Plugin Version ==> ASTRA
 - Browser [e.g. Chrome, Safari] and Version ==> Safari & Chrome
 - Any other plugins installed ==> Stripe, Spam Plugins

</details>
![paypal bug](https://github.com/woocommerce/woocommerce-paypal-payments/assets/63461408/c5775934-779b-485f-b06d-d4d53069812c)

**Comment by Sirvijver** [comment]
Hello @543S 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

For the issue you reported, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. 
Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you, please open a support thread via the link above, and we will continue helping you out there. This thread will be closed.

Kind regards, 
Joost
