### ISSUE TITLE
Add Remove settings at Uninstall

### ISSUE THREAD

**Issue by Bebuk85** [woocommerce/woocommerce-paypal-payments#1658]
Would be good to have this option when someone deletes your plugin.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/72046610/18ddf582-9f8b-4358-9a3d-75939e2bb555)

Thanks.

**Comment by InpsydeNiklas** [comment]
Hi @Bebuk85 
Thanks for your suggestion. This functionality is already available at the bottom of the Connection tab: 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/0e289a01-fd6a-4c2a-b939-e4b3a69a29e2)
More details in the docs here: https://woocommerce.com/document/woocommerce-paypal-payments/#reset-settings
So, I will go ahead and close this issue. For any other questions or suggestions, our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) is ready to help you. Thanks!
