### ISSUE TITLE
Paypal button not present

### ISSUE THREAD

**Issue by Baikal55** [woocommerce/woocommerce-paypal-payments#1662]
### To Reproduce

1. Go to https://shop.yukasz.com/payment
2. Click on 'Paypal checkbox'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version '6.3.1'
 - Plugin Version 'Woocommerce 8.0.3' , Woocommerce Payments 6.4.0' , Woocommerce Paypal Payments 2.2.2'
 - Browser [e.g. Chrome, Safari] and Version 'Chrome Version 116.0.5845.141 (Build officiel) (64 bits)'
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Baikal55 
Was this Checkout page built using Elementor? It looks like the JavaScript execution on this page doesn't work as e.g. also the card fields don't disappear when selecting another gateway. Certain problems could arise as the Elementor plugin is not fully supported by PayPal Payments.
Can you please check if the behavior persists when you create a regular Checkout page with the `[woocommerce_checkout]` shortcode? For additional guidance, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.
We will close this GitHub issue for now. However, our support team is available to assist you with any concerns that may arise. Thank you for your understanding!
