### ISSUE TITLE
Advanced Card Payments doesn't work if 1st in tree

### ISSUE THREAD

**Issue by gunship800** [woocommerce/woocommerce-paypal-payments#1665]
### Describe the Bug

When advanced card payments is placed first, the field cannot be used or edited.  When moved anywhere else it works as it should.  This has been an issue for as long as I can remember.

### To Reproduce

Advanced card payments is placed as first option

 - WordPress Version 6.3.1
 - WooCommerce 8.0.3
 - woocommerce paypal 2.2.2
 - Affects any browsers or mobile

![p](https://github.com/woocommerce/woocommerce-paypal-payments/assets/118882234/51043f99-dce0-4fb7-b74b-33287988994a)

**Comment by InpsydeNiklas** [comment]
Hi @gunship800 
The Advanced Card Processing card field styling is primarily determined by the theme. Changing the theme e.g. to [Storefront](https://wordpress.org/themes/storefront/) should resolve this behavior. We are not aware of any other reports like this, but it should be possible to fix the fields with some [custom CSS](https://woocommerce.com/document/woocommerce-paypal-payments/#customizing-hosted-fields).
Your theme developer would be the best contact for this, but you can also contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for additional guidance.
We will close this GitHub issue for now. However, our support team is available to assist you with any concerns that may arise. Thank you for your understanding!
