### ISSUE TITLE
word press

### ISSUE THREAD

**Issue by mohammedas22** [woocommerce/woocommerce-paypal-payments#1670]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @mohammedas22 

You did not provide any request or suggestion, so I will close this thread.

You have reached out to open GitHub forum. We utilize GitHub mainly for development activities, so if you require support from our team, I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
