### ISSUE TITLE
Paypal Button not visible in Checkout

### ISSUE THREAD

**Issue by thewrites-xyz** [woocommerce/woocommerce-paypal-payments#1671]
### Describe the Bug

I have your Woocommerce Checkout and it's not showing as a button on my checkout page. Everything is configured and live.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/133000538/6292c178-1b78-4b33-af72-6fc9b1ffbaaf)

### Environment

 - WordPress Version | 6.3.1
 - WooCommerce Version | 8.0.3
 - Plugin Version | 2.2.2
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by thewrites-xyz** [comment]
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/133000538/b6ec6006-c702-402a-8c0b-2d1f060156a6)

**Comment by InpsydeNiklas** [comment]
Hi @thewrites-xyz 
On the new [Block Checkout](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-2), PayPal Payments supports only the express button locations at this time. So you could select the `Block Express Checkout` button location to see these buttons:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/c70eba90-a3ac-4f13-a13e-d434442b8834)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/ddc7b7a6-2257-4f89-b187-dbd8ab20a64c)

But there is no regular payment gateway available yet. This requires the `[woocommerce_chekcout]` shortcode for now.
You can read more about the Block support here: https://woocommerce.com/document/woocommerce-paypal-payments/#woocommerce-blocks
For additional guidance, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.
We will close this GitHub issue for now. However, our support team is available to assist you with any remaining questions. Thank you for your understanding!

**Comment by thewrites-xyz** [comment]
Hi,

Thank you for your reply. I've added the Block Buttons and still, I'm not seeing any buttona in the checkout page.

thewrites.xyz

Regards,

**Comment by thewrites-xyz** [comment]
Button is now appearing, tho when I click Credit Card, it's disabled. I
can't edit the fields.

[image: image.png]
