### ISSUE TITLE
woocommerce PayPal No response to fast payment.It can only be used in the shopping cart interface

### ISSUE THREAD

**Issue by Darrenrixing** [woocommerce/woocommerce-paypal-payments#1673]
### To Reproduce

1. Go to 'product page'
2. Click on 'paypal'
3. no effect,"Something went wrong. Please try again or choose another payment source." is displayed, or the PayPal payment interface does not move

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/144256075/5eadd6d7-84ce-48a0-8090-6941a32c6720)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/144256075/1311d5fb-dd50-463c-ae9b-00d0867c67c9)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Darrenrixing** [comment]
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/144256075/20bd068f-f325-418f-bc18-a273a146b891)
There was no reaction in the jump PayPal payment world

**Comment by InpsydeNiklas** [comment]
Hi @Darrenrixing 
This issue appears to be the same as #1664. I suggest testing it with the version mentioned in this comment: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1664#issuecomment-1706188571
If the issue persists for you with the mentioned test version or if any other questions remain, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.
We will close this GitHub issue for now. However, our support team is available to assist you with any remaining questions. Thank you for your understanding!
