### ISSUE TITLE
paypal doesnt work,loading the whole time

### ISSUE THREAD

**Issue by Content2122** [woocommerce/woocommerce-paypal-payments#1679]
### Describe the Bug

Hi everyone, i'm working on strato wordpress, and currently im facing a problem with paypal, im trying to buy the (x) product from my website but at the end when i try to pay with paypal it keeps loading and nothing happens i cannot even click on the button to buy the product it keeps loading the whole time.
thanks for your time.
### To Reproduce

1. Go to 'https://verlosung.info/produkt/apple-watch-se-eticket/'
2. Click on 'Participate Now for 7.99,'
3. Scroll down to 'weiter zur kasse'

### Screensh
![Screenshot 2023-09-08 10 14 36 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/105956646/215affb3-2f39-4be1-882c-4bfc38cabf1e)
![Screenshot 2023-09-08 10 13 53 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/105956646/c7ccc976-4bb5-4b33-a81a-3369a11cc607)
![Screenshot 2023-09-08 10 13 06 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/105956646/0e8631e0-472d-4d58-a261-07b1df2ef1b3)
ots
/
/

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

```[tasklist]
### Tasks
```

**Comment by InpsydeNiklas** [comment]
Hi @Content2122 
When I checked your site yesterday or the day before, the PayPal buttons were loading correctly on your Checkout page. By now, the seems to be no purchasable product anymore, though. So we will close this issue, but if any questions remain, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thank you!
