### ISSUE TITLE
Incompatibility with a woocommerce quotation plugin

### ISSUE THREAD

**Issue by welem** [woocommerce/woocommerce-paypal-payments#1681]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by welem** [comment]
Hello,

I've installed from a long time a plugin that enable quote request (https://woocommercequoteplugin.com/) on my wocommerce shop (https://welem.com/enr/shop/).
When the paypal plugin is active, if I click on the 'add to quote' button, the Ajax request crashes because there is an error which is generated in the apiModule of the paypal plugin.
Paypal is useless when you click on the "add to quote" button, because it is a quote request, there is no price and the object handled is not a 'WC_Cart' but a 'WC_Quotation_Quote' from my quote plugin.
For more details, see this logs extract just above:

[10-Sep-2023 15:46:07 UTC] PHP Fatal error:  Uncaught TypeError: WooCommerce\PayPalCommerce\ApiClient\ApiModule::WooCommerce\PayPalCommerce\ApiClient\{closure}(): Argument #1 ($cart) must be of type WC_Cart, WC_Quotation_Quote given, called in /home/welem/www/enr/wp-includes/class-wp-hook.php on line 310 and defined in /home/welem/www/enr/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/ApiModule.php:38
Stack trace:
#0 /home/welem/www/enr/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\ApiClient\ApiModule->WooCommerce\PayPalCommerce\ApiClient\{closure}(Object(WC_Quotation_Quote))
#1 /home/welem/www/enr/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#2 /home/welem/www/enr/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/welem/www/enr/wp-content/plugins/woocommerce-quotation/classes/class.quote.php(1233): do_action('woocommerce_aft...', Object(WC_Quotation_Quote))
#4 /home/welem/www/enr/wp-includes/class-wp-hook.php(308): WC_Quotation_Quote->calculate_totals()
#5 /home/welem/www/enr/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#6 /home/welem/www/enr/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/welem/www/enr/wp-content/plugins/woocommerce-quotation/classes/class.quote.php(230): do_action('woocommerce_add...', '70821a40b06f875...', '5298', 1, false, Array, Array)
#8 /home/welem/www/enr/wp-content/plugins/woocommerce-quotation/functions/adq-quote-ajax.php(139): WC_Quotation_Quote->add_to_quote('5298', 1)
#9 /home/welem/www/enr/wp-includes/class-wp-hook.php(310): adq_ajax_add_to_quote('')
#10 /home/welem/www/enr/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#11 /home/welem/www/enr/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /home/welem/www/enr/wp-admin/admin-ajax.php(188): do_action('wp_ajax_add_to_...')
#13 {main}
  thrown in /home/welem/www/enr/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/ApiModule.php on line 38


For information, temporarily, I made a working patch ('LVA' tags) in the woocommerce-paypal-payments/modules/ppcp-api-client/src/ApiModule.php file like this:
<<<< 
	public function run( ContainerInterface $c ): void {
		/* LVA+ */
		if ($cart instanceof WC_Cart) {
		/* LVA- */
		add_action(
			'woocommerce_after_calculate_totals',
			function ( \WC_Cart $cart ) {
				$fees = $cart->fees_api()->get_fees();
				WC()->session->set( 'ppcp_fees', $fees );
			}
		);
		/* LVA+ */
		}
		/* LVA- */
	}
[debug.log](https://github.com/woocommerce/woocommerce-paypal-payments/files/12569436/debug.log)

**Comment by InpsydeNiklas** [comment]
Hi @welem 
While the quotation plugin may work by itself in isolation, it would be up to the developer of this plugin to ensure that it is compatible with PayPal Payments. Compatibility does not always mean that plugins have to directly interact but simply coexist in the same space.
PayPal Payments throws the error, but it does so because the other plugin is altering the cart object without returning the proper data. This is not recommended practice and can easily result in other plugins not working as expected or cause other issues. But there isn't much we can do about this problem, as it must be resolved by improving the core logic of the quotation plugin. 
So the primary suggestion is to contact the quotation plugin developer. We will close this issue, but if any questions remain, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thank you!
