### ISSUE TITLE
Paypal Button/checkout not working on product page 

### ISSUE THREAD

**Issue by hamadgill** [woocommerce/woocommerce-paypal-payments#1682]
[###](url) Describe the Bug

PayPal functions are not working on the single product page woocommerce , but work correctly on all other locations (cart, checkout, mini cart). All other locations will load PayPal within the popup but on the single product page it will not load and is in a constant loop, was working in version 2.2.0 but has not been working since version 2.2.1
### To Reproduce

Click on any product in woocommerce , Once on the single product page, click the Paypal button 

### Screenshots

[[]](https://snipboard.io/KUjdtJ.jpg)(url) - how it loads on other locations correctly 

[[]](https://snipboard.io/OMwB7b.jpg)(url) - how it loads on single product page and not working

### Expected Behavior

Suppose to load PayPal checkout/login
### Actual Behavior

PayPal popup is in a constant loop, not loading, but loads correctly on all other PayPal button locations (cart, mini cart, checkout)

### Environment

 - WordPress Version - 6.3.1
 - WooCommerce Version - 8.0.3
 - Plugin Version - 2.2.2
 - Browser [e.g. Chrome, Safari] and Version - tested on multiple devices and browsers, Chrome desktop, Android and ios
 - Any other plugins installed - woo commerce payments, after pay woo commerce 

### Additional Details

working until version 2.2.0 not working since 2.2.1

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @hamadgill 
Thanks for reporting the issue. This is issue duplicates #1664 and will be resolved in the next update, so I will close it already. In the meantime, please check out the [test package provided in the comments on the other issue](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1664#issuecomment-1706188571) for a potential workaround other than downgrading.
Thank you!
