### ISSUE TITLE
Paypal Button Error

### ISSUE THREAD

**Issue by Handycraftindia** [woocommerce/woocommerce-paypal-payments#1684]
Attention: Your current WooCommerce store currency (INR) is not supported by PayPal. Please update your store currency to one that is supported by PayPal to ensure smooth transactions. Visit the [PayPal currency support page](https://developer.paypal.com/api/rest/reference/currency-codes/) for more information on supported currencies.

**Comment by Sirvijver** [comment]
Hello @Handycraftindia 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide a problem description or question, only the error that indicates a requirement of the plugin. If needed, please open a new support request via the link provided above and provide your question there, so we can help you out. For now, we will close this GitHub thread.

Kind regards, 
Joost
