### ISSUE TITLE
The customers can't pay with AMEX using Advanced Card Processing

### ISSUE THREAD

**Issue by azanoni** [woocommerce/woocommerce-paypal-payments#1685]
### Describe the Bug

In the checkout page we have two options, PayPal button or Debit & Credit Cards box, in the last one when we use AMEX credit cards we cannot finished the order because we always received this error:

**_Payment provider declined the payment, please use a different payment method. OrderEndpoint.php:365 Order status changed from Pending payment to Failed._**

### To Reproduce

1. Go to Checkout Page
2. Click on Debit & Credit Cards radio button
3. Fill the box with an American Express credit Card
4. Check the checkbox "I have read and agree to the website...." and Press "Place Order"
5. See error

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/21685626/13a97e18-713a-45c8-841e-be2f6def292e)

### Expected Behavior

Finished the order without any issue

### Actual Behavior

We cannot complete the order 

### Environment

 - WordPress 6.1.3
 - WooCommerce 7.8.0
 - Plugin Version: 2.1.0
 - Browser: All of Them
 - Any other plugins installed

### Additional Details

<details><summary>Example Error LOG</summary>

  ```

2023-09-10T23:48:15+00:00 DEBUG  https://api.paypal.com/v2/checkout/orders/xxxxx
Response Debug ID: f0ae3417dcbc0
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-09-10T23:48:17+00:00 DEBUG POST https://api.paypal.com/v2/checkout/orders/xxxxx/capture
Response Debug ID: 0bee731e92f6c
Response: Array
(
    [code] => 201
    [message] => Created
)


2023-09-10T23:48:17+00:00 ERROR Payment failed: Payment provider declined the payment, please use a different payment method. OrderEndpoint.php:365
2023-09-10T23:56:04+00:00 DEBUG POST https://api.paypal.com/v1/identity/generate-token
Response Debug ID: be889129e917e
Response: Array
(
    [code] => 200
    [message] => OK
)


2023-09-10T23:56:48+00:00 DEBUG POST https://api.paypal.com/v1/identity/generate-token
Response Debug ID: 3506810d8e144
Response: Array
(
    [code] => 200
    [message] => OK
)
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @azanoni 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

Another approach would be to contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) directly, as they are best suited to help with rejected payments related to PayPal services.

We'll be closing this GitHub issue for now. However, once you reach out to our support team or the PayPal Merchant Technical Support, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
