### ISSUE TITLE
PayPal Payment button not showing on live site

### ISSUE THREAD

**Issue by jasworn** [woocommerce/woocommerce-paypal-payments#1687]
Describe the Bug

The payment button at the bottom of the checkout page is not showing when the WooCommerce PayPal Payment gateway plugin is enabled, a 'Place Order' button shows when the plugin is deactivated.

Environment

WordPress 6.3.1
WooCommerce Version 8.0.3
Plugin Version 2.2.2
Chrome browser 116.0.5845.180, Firefox 117.0 (64-bit)
Plugins installed - Contact Form 7, Deposits for WooCommerce, Flamingo, Limit Login Attempts, Payment Gateway Fees, Smash Balloon Instagram Feed, Woo Checkout Editor, WooCommerce Bookings, WooCommerce PDF Product Vouchers, WP Mail SMTP, Yoast SEO.

**Comment by SydeKrystian** [comment]
Hello @jasworn 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
