### ISSUE TITLE
Customer which is not registered after paying with PayPal

### ISSUE THREAD

**Issue by amandinebta** [woocommerce/woocommerce-paypal-payments#1695]
Customer not registered

Hi, recently some clients which order on my Wordpress website were not able to be registered when buying. But the order is passed. For the first two orders, I didn't receive the payment for the shipment which was written on the order but has not been take in count by PayPal. Also the customer wasn't able to register or even choose the place where she would receive her order. 

Last problem I got was today, the person was not able to register but this time the shipment cost was sent to me. But still, the client was not registered and I had no informations about anything. Which is a real problem, and happening only with PayPal. Could you please do something really quick about that before I had any problematic issues with some customers ? Or I will have to take down the PayPal plug-in. Also, some other people had this problem before and wrote it on different website when you look for this problem. 

Thank you.

**Comment by Sirvijver** [comment]
Hello @amandinebta 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any details for me to investigate, so there is not much I can do at this support request at the moment. When you open a support thread (as instructed above), please provide the system report and logs related to this issue. If you don't have logs available, please activate "logging" in the plugin settings, so we will have them available if this issue occurs again.

I am not aware of any known issue, but it would be good that you add the link to this other website where other merchants reached out to us. This way, we can take a look and see if this is related to any known issue.#1694 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. 

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

I will close this GitHub thread. Please open a support thread if you require our continued support.

Kind regards, 
Joost
