### ISSUE TITLE
URGET - Paypal Stopped processing orders

### ISSUE THREAD

**Issue by nerodesign** [woocommerce/woocommerce-paypal-payments#1696]
### Describe the Bug

Paypal pyments have stopped being processed.

Receiving an error when someone goes to checkout , see below (screenshot atatched also).

"Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID PayPalGateway.php:604 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID OrderEndpoint.php:332 Order status changed from Pending payment to Failed."

Have checked PAYPAL in WOOCMMERCE SETTINGS and have authentication error all of a sudden. Tried to reconnect manully and still same error. (see screenshot).
Also getting a webhook connection error. (see screenshot).

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version. 8.1
 - Plugin Version 2.2.2
 - Browser [e.g. Chrome, Safari] and Version. All 
 - Any other plugins installed - none recently

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
`
### wp-core ###

version: 6.3.1
site_language: en_US
user_language: en_US
timezone: Australia/Perth
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 919
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/wplive/web/wp-live
wordpress_size: 1.08 GB (1158246780 bytes)
uploads_path: /home/wplive/web/wp-live/wp-content/uploads
uploads_size: 677.22 MB (710114954 bytes)
themes_path: /home/wplive/web/wp-live/wp-content/themes
themes_size: 37.08 MB (38881313 bytes)
plugins_path: /home/wplive/web/wp-live/wp-content/plugins
plugins_size: 190.74 MB (200003578 bytes)
database_size: 512.38 MB (537265441 bytes)
total_size: 2.46 GB (2644512066 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: Floret Child (bodega-child)
version: 1.0.0
author: Anonymous
author_website: (undefined)
parent_theme: Bodega (bodega)
theme_features: core-block-patterns, title-tag, woocommerce, widgets-block-editor, post-thumbnails, bodega_qode_sidebar, automatic-feed-links, post-formats, menus, widgets
theme_path: /home/wplive/web/wp-live/wp-content/themes/bodega-child
auto_update: Disabled

### wp-parent-theme ###

name: Bodega (bodega)
version: 3.4
author: Select Themes
author_website: http://demo.qodeinteractive.com
theme_path: /home/wplive/web/wp-live/wp-content/themes/bodega
auto_update: Disabled

### wp-mu-plugins (5) ###

Asset CleanUp Pro: Plugin Filtering: version: 1.0, author: Gabriel Livan
Health Check Troubleshooting Mode: author: (undefined), version: 1.7.2
htpm-mu-plugin.php: author: (undefined), version: (undefined)
Nero Site: author: (undefined), version: 1.9.51
WP Umbrella: version: 1.0.0, author: WP Umbrella

### wp-plugins-active (34) ###

Bodega Core: version: 1.2, author: Select Themes, Auto-updates disabled
Checkout Field Editor and Manager for WooCommerce: version: 2.2.15, author: Acowebs, Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates enabled
Classic Widgets: version: 0.3, author: WordPress Contributors, Auto-updates enabled
Convertful - Your Ultimate On-Site Conversion Tool: author: (undefined), version: 2.5, Auto-updates enabled
Envato Market: version: 2.0.10, author: Envato, Auto-updates enabled
Finteza Analytics: version: 1.3, author: finteza, Auto-updates enabled
Growmatik - Marketing Automation and Personalization: version: 2.8.3, author: Artbees, Auto-updates enabled
GTM4WP: version: 1.18.1, author: Thomas Geiger, Auto-updates disabled
Kadence WooCommerce Email Designer: version: 1.5.11, author: Kadence WP, Auto-updates enabled
MailPoet: version: 4.27.0, author: MailPoet, Auto-updates enabled
MailPoet Premium: version: 4.27.0, author: MailPoet, Auto-updates enabled
ManageWP - Worker: version: 4.9.17, author: GoDaddy, Auto-updates enabled
Master Slider Pro: version: 3.6.5, author: averta, Auto-updates enabled
Metricool: version: 1.19, author: Metricool, Auto-updates enabled
Plerdy: version: 1.2, author: Plerdy, Auto-updates enabled
Plugin Toggle: version: 1.3.1, author: Cedaro, Auto-updates enabled
Product Add-Ons for WooCommerce: version: 2.1.38, author: BizSwoop a CPF Concepts, LLC Brand, Auto-updates enabled
Product Feed Manager for WooCommerce: version: 7.3.11, author: RexTheme, Auto-updates enabled
RabbitLoader: version: 2.19.9, author: RabbitLoader, Auto-updates enabled
Really Simple SSL: version: 7.0.9, author: Really Simple Plugins, Auto-updates enabled
Redirection: version: 5.3.10, author: John Godley, Auto-updates enabled
Simple History: version: 4.5.0, author: Pär Thernström, Auto-updates disabled
Squirrly SEO (Newton): version: 12.3.10, author: Squirrly, Auto-updates enabled
Squirrly SEO - Advanced Pack: version: 2.2.5, author: Squirrly, Auto-updates disabled
ThoughtMetric for WooCommerce: version: 1.19.0, author: ThoughtMetric, Auto-updates disabled
Tracking Code Manager: version: 2.0.16, author: Data443, Auto-updates enabled
Ultimate Row Background - Visual composer Add On: version: 2.0, author: POSIMYTH Themes, Auto-updates disabled
WooCommerce: version: 8.1.0, author: Automattic, Auto-updates enabled
WooCommerce PayPal Payments: version: 2.2.2, author: WooCommerce, Auto-updates enabled
WooCommerce Table Rate Shipping: version: 4.2, author: Bolder Elements, Auto-updates enabled
WPBakery Page Builder: version: 6.9.0, author: Michael M - WPBakery.com (latest version: 7.0), Auto-updates enabled
WP Umbrella: version: 2.11.3, author: WP Umbrella - Backup & Manage WordPress, Auto-updates disabled
YellowPencil Pro: version: 7.6.0, author: WaspThemes, Auto-updates enabled

### wp-plugins-inactive (1) ###

Weberlo for UTM and Ad Tracking: version: 0.0.6, author: Weberlo, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.15.0-1041-gcp x86_64
httpd_software: nginx/1.21.6
php_version: 8.0.21 64bit
php_sapi: fpm-fcgi
max_input_variables: 10000
time_limit: 300
memory_limit: 256M
max_input_time: 300
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
current: 2023-09-15T03:20:44+00:00
utc-time: Friday, 15-Sep-23 03:20:44 UTC
server-time: 2023-09-15T11:20:42+08:00

### wp-database ###

extension: mysqli
server_version: 5.7.33
client_version: mysqlnd 8.0.21
max_allowed_packet: 1073741824
max_connections: 5000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/wplive/web/wp-live/wp-content
WP_PLUGIN_DIR: /home/wplive/web/wp-live/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`
</details>
![Screenshot 2023-09-15 at 10 44 15 am](https://github.com/woocommerce/woocommerce-paypal-payments/assets/49036845/a3907ee4-3bb1-4dba-9178-68c167797961)
![Screenshot 2023-09-15 at 10 42 57 am](https://github.com/woocommerce/woocommerce-paypal-payments/assets/49036845/3a332d8a-52fd-4760-b3d8-080890383408)
![Screenshot 2023-09-15 at 10 42 01 am](https://github.com/woocommerce/woocommerce-paypal-payments/assets/49036845/ae0c7c43-2739-4e5f-9f4b-fa806ebf36da)
![Screenshot 2023-09-15 at 10 42 06 am](https://github.com/woocommerce/woocommerce-paypal-payments/assets/49036845/c44eace8-7b90-47d8-82c5-29a942b80230)

**Comment by Sirvijver** [comment]
Hello @nerodesign 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error DUPLICATE_INVOICE_ID error is a security feature from PayPal which aims to prevent accidental double-payments.

PayPal Payments automatically sets an "invoice prefix" and then sends the WooCommerce order numbers in the pattern "invoice prefix+ordernumber" to PayPal. So when your prefix is set to "cfbdg-" and your order number is "123", PayPal Payments sends the invoice ID "cfbdg-123" to PayPal.

Under certain circumstances, for example when you restore a backup from your website, it is possible that the most recent WooCommerce orders do not exist anymore after the restore.
So as soon as WooCommerce attempts to create a new order with the number 123 and the same invoice prefix, PayPal would throw this error to prevent accidental double payments because there is already a payment at PayPal with the same invoice ID.
This feature can be disabled, though we usually recommend keeping it enabled. To disable it, follow these steps:

1. Log in to your Business PayPal account (https://www.paypal.com/businessmanage/preferences/payments)
2. Go to the Payments Preferences section
3. Under the "Block accidental payments:" section, select the option "No, allow multiple payments per invoice ID"

With this feature disabled, PayPal would no longer complain when you submit an invoice number that already exists in the system.

But instead of disabling this feature, it would be better to figure out the true cause for this error. A buyer during the normal checkout process should normally not encounter this error. 

If you require additional support, please open a support request as mentioned above. We will close this thread for now.

Kind regards, 
Joost
