### ISSUE TITLE
Avoid running the query to check if the  PPEC deactivation note should be marked as actioned.

### ISSUE THREAD

**Issue by prettyboymp** [woocommerce/woocommerce-paypal-payments#1701]
### Describe the Bug

The query to check if there is a PPEC deactivation note within `WooCommerce\PayPalCommerce\Compat\PPEC\DeactivateNote` runs on every request.  While it's a relatively fast query, this still adds unneeded overload.  Ideally, this should at least be wrapped in an `is_admin()` check.

### To Reproduce

1.  Use something like debug_bar() to watch queries when browsing a site.
2. Note that the query to check for the `ppcp-disable-ppxo-note` note is run on every page.

Adding a call to `if( is_admin() )` around the below action should be enough to fix it.
https://github.com/woocommerce/woocommerce-paypal-payments/blob/d3a02e79c52c71bac04375ba1d93ec9858f70e3e/modules/ppcp-compat/src/CompatModule.php#L92-L99

**Comment by InpsydeNiklas** [comment]
merged in #2719
