### ISSUE TITLE
Connecting to account fails and timesout

### ISSUE THREAD

**Issue by bylmzio** [woocommerce/woocommerce-paypal-payments#1708]
### Describe the Bug

After connecting the paypal plugins with account it fails. And when entering data manually  the endpoint `POST https://api.paypal.com/v1/oauth2/token?grant_type=client_credentials` times out.

Error:
`cURL error 28: Connection timeout after 10001 ms`
` WooCommerce\P\A\A\PayPalBearer->request()`
it tries to reconnect 45 times and slows everything in backend down.

### Screenshots

![Bildschirmfoto 2023-09-19 um 14 32 30](https://github.com/woocommerce/woocommerce-paypal-payments/assets/7440674/53dac721-28c5-404a-94da-551bca5f21ff)

### Environment
 - WordPress Version 6.3.1
 - WooCommerce Version  8.1.1
 - Plugin Version  2.2.2
 - Browser: Firefox, Chrome latest
 - Any other plugins installed yes

**Comment by Sirvijver** [comment]
Hello @bylmzio 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are reporting seems to be a mix of incorrect account details being used (can be corrected by onboarding the plugin again using the wizard) and hosting related issues. Please take a look [here](https://www.wpbeginner.com/wp-tutorials/how-to-fix-curl-error-28-connection-timed-out-after-x-milliseconds/) for the cURL error 28 situation and see if you can get this resolved following those instructions.

We will close this thread, please open a support thread as advised above, if you need additional support.

Kind regards, 
Joost
