### ISSUE TITLE
detail in woocommerce order edit page is gone using 2.3.0-rc1 (2037)

### ISSUE THREAD

**Issue by helpme2k2** [woocommerce/woocommerce-paypal-payments#1709]
### Describe the Bug
detail in woocommerce order edit page is gone using 2.3.0-rc1

### To Reproduce

Replace v2.2.0 or 2.2.1 or 2.2.2 with 2.3.0.rc1, 
click Woocommerce > Orders > any old order that was created with older plugin from the list

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/10323059/ea5aeae7-647f-4e40-b7a1-d5a3f7e17daa)

### Expected Behavior
The order detail returned as soon as plugin 2.3.0.rc1 is deactivated, or replaced with 2.2.2 or 2.2.1 or 2.2.0

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version 8.1.1
 - Plugin Version 2.3.0-rc1
 - Browser [e.g. Chrome, Safari] and Version firefox 117.0.1 , Chrome 116.0.5845.188  , Win 11 22h2
 - Any other plugins installed

### Additional Details

Wordpress actually send an email to admin email, tell me error was caught when I visit the order edit page:

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.2.2
Active theme: Jevelin Child (version )
Current plugin: WooCommerce PayPal Payments (version 2.3.0-rc1) PHP version 7.4.32

Error Details
=============
An error of type E_ERROR was caused in line 436 of the file /home/XXXXXXXXX/domains/XXXXXXXXX.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php. Error message: Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Missing required information: Tracking Number ,Carrier Name Other in /home/XXXXXXXXX/domains/XXXXXXXXX/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php:436
Stack trace:
#0 /home/XXXXXXXXX/domains/XXXXXXXXX.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php(398): WooCommerce\PayPalCommerce\OrderTracking\Endpoint\OrderTrackingEndpoint->validate_tracking_info(Array)
#1 /home/XXXXXXXXX/domains/XXXXXXXXX.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php(355): WooCommerce\PayPalCommerce\OrderTracking\Endpoint\OrderTrackingEndpoint->create_shipment(11578, Array)
#2 /home/XXXXXXXXX/domains/XXXXXXXXX.com/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/MetaBoxRenderer.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @helpme2k2, thanks for trying out the 2.3.0 pre-release version. This update includes major changes to the shipment tracking integration but we're unable to reproduce the reported error at this time.
Can you confirm this is an old PayPal Payments order? I assume this problem does not appear for non-PayPal orders?
One way to circumvent the error could be to disable the tracking integration:
`add_filter('woocommerce_paypal_payments_shipment_tracking_enabled', '__return_false');`
Beyond this, it would be good for us to understand if you can reproduce the problem with only WooCommerce and PayPal Payments active as the error could be the result of a third-party plugin conflict.

However, disabling tracking of course is not a real solution, especially if you want to take advantage of the functionality.
So a few more details about your site, such as which shipment tracking plugin you are using, or better a complete copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) would help us a lot in better understanding your site setup.
If you prefer to share sensitive details privately, you can reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this GitHub issue. Thank you!

**Comment by helpme2k2** [comment]
> Hi @helpme2k2, thanks for trying out the 2.3.0 pre-release version. This update includes major changes to the shipment tracking integration but we're unable to reproduce the reported error at this time. Can you confirm this is an old PayPal Payments order? I assume this problem does not appear for non-PayPal orders? One way to circumvent the error could be to disable the tracking integration: `add_filter('woocommerce_paypal_payments_shipment_tracking_enabled', '__return_false');` Beyond this, it would be good for us to understand if you can reproduce the problem with only WooCommerce and PayPal Payments active as the error could be the result of a third-party plugin conflict.
> 
> However, disabling tracking of course is not a real solution, especially if you want to take advantage of the functionality. So a few more details about your site, such as which shipment tracking plugin you are using, or better a complete copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) would help us a lot in better understanding your site setup. If you prefer to share sensitive details privately, you can reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this GitHub issue. Thank you!

I confirm the problem is happening to old PayPal Payments order. Cause our store doesn't use other payment gateway. I will be contacting the support team.

**Comment by InpsydeNiklas** [comment]
Hi @helpme2k2, we haven't been able to reproduce the error that resulted in the missing order details yet. 

There is a new release candidate [2.3.0-rc2 version](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.3.0-rc2), but this version does not contain any changes compared to rc1 that would lead me to believe that this error is fixed for you. In that case, the filter mentioned above that disables tracking functionality may be the best workaround to prevent the error.
While our developers are still investigating the error, it would help us the most if you could give it a try in a [staging environment](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Advanced-Troubleshooting#test-on-staging) to find out if this could potentially be a conflict with another plugin.
Also, do these orders contain PayPal tracking data? Or does this problem happen with every PayPal order regardless of whether they include PayPal tracking data? I would suggest that you pass your findings directly to our support team as you're already in touch.
In the meantime, I'll leave this issue open until our investigation concludes and we can better judge the cause of the reported behavior. Thank you!

**Comment by HelpAdude** [comment]
def on advanced paypal  r.block is not  a function and "Hosted Fields payment is already in progress" in some cases

**Comment by helpme2k2** [comment]
thank you for the update on rc2. I have tried the plugin and as you have suggested, it doesn't fix the situation. The filter, add_filter('woocommerce_paypal_payments_shipment_tracking_enabled', '__return_false'); indeed fixed the problem.
I have been trying to deactive all the plugins one by one and only left the essential one active. But he issue still there when rc1/2 is activated. It looks like the issue is not caused by an active plugin but rather the orders that was created by the plugin(s).
I am actually openned a ticket with at the Woocommerce website and talking to the Krystian from Inpsyde SupportTeam, WooCommerce PayPal Payments via email. Since my website contains customers' information, I will not continue the conversation here but communicate to the team through email. 
Thank you very much for your help.
Elton
    On Friday, September 22, 2023 at 01:11:55 PM EDT, Niklas Gutberlet ***@***.***> wrote:  
 
 


Hi @helpme2k2, we haven't been able to reproduce the error that resulted in the missing order details yet.

There is a new release candidate 2.3.0-rc2 version, but this version does not contain any changes compared to rc1 that would lead me to believe that this error is fixed for you. In that case, the filter mentioned above that disables tracking functionality may be the best workaround to prevent the error.
While our developers are still investigating the error, it would help us the most if you could give it a try in a staging environment to find out if this could potentially be a conflict with another plugin.
Also, do these orders contain PayPal tracking data? Or does this problem happen with every PayPal order regardless of whether they include PayPal tracking data? I would suggest that you pass your findings directly to our support team as you're already in touch.
In the meantime, I'll leave this issue open until our investigation concludes and we can better judge the cause of the reported behavior. Thank you!
