### ISSUE TITLE
Cart Items removed after adding items to cart

### ISSUE THREAD

**Issue by zachnoel** [woocommerce/woocommerce-paypal-payments#1710]
### Describe the Bug

When adding items to cart and then viewing the cart only the newly added items are in there.

### To Reproduce

1. Go to woocommerce store
2. Add items to cart
3. view cart
4. go back to store
5. add new items to cart
6. view cart
7. only the new items are visiable in the cart. The previously added items are gone

### Expected Behavior

It is expected to have all items that were added to show up in the cart as they are being added from the store.

### Actual Behavior

Only the most recent item is added to the cart

### Environment

 - WordPress Version - 6.3.1
 - WooCommerce Version - 8.1.1
 - Plugin Version - 2.2.2
 - Browser [e.g. Chrome, Safari] and Version - Chrome
 - Any other plugins installed - Disabled all but woocommerce

**Comment by InpsydeNiklas** [comment]
Hi @zachnoel, thanks for reporting the issue. Could you please give it a try with the current [2.3.0 pre-release version from here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.3.0-rc1) and let us know if this resolves the issue for you? Thanks!

**Comment by zachnoel** [comment]
@InpsydeNiklas I have tried to install the 2.3.0 pre release version and it seemed to clear up the cart resetting but that version was throwing some sytax error on the checkout form and was preventing users to continue through checkout. I have reverted back to 2.2.2 version for now and trying to find where that cart is getting reset but don't have many options right now. Is there any other options?


![paypal error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4705798/1e837c24-6921-4708-bf80-e22cacdd0d5e)

**Comment by InpsydeNiklas** [comment]
Hi @zachnoel, thanks for giving it a try!
In the 2.3.0 pre-release version, the plugin sends additional information to PayPal, such as the `item_url` and `image_url`. According to your screenshot, it seems the `image_url` may contain additional parameters that a third-party plugin may have added. More details, such as a complete copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/) would help us a lot in better understanding your site setup and what could potentially cause the error.
If you prefer to share sensitive details privately, you can reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this GitHub issue. Thank you!

In the meantime, another way to temporarily work around the cart issue could be enabling this setting in WooCommerce to redirect the buyer to the cart after adding a product:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/3d1b40e6-973a-4a5f-abdc-25451392e826)

**Comment by zachnoel** [comment]
@InpsydeNiklas I appreciate your feedback. I tried the workaround above first to redirect to cart page after cart add but it was still clearing the cart as before. I then retried the latest 2.3.0 pre-release version again and found that my jetpack plugin was doing some image optimizations which seemed to be the reason for the image_url error. After disabling just the image optimizations in jetpack it did end up working as expected. I now have my application operational again. Thank you once again and I will be watching out for any other issues out of the 2.3.0 version until it is released. Again thank you for your responses!

**Comment by Sirvijver** [comment]
Hello @zachnoel 

Thanks for letting us know you got this working to your liking. Please [open a support request](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you encounter any more issues with our plugin.

Kind regards, 
Joost
