### ISSUE TITLE
WooCommerce PayPal Payments PHP8 compatibility issues

### ISSUE THREAD

**Issue by PierreWS** [woocommerce/woocommerce-paypal-payments#1723]
### To Reproduce

I did a live test with PHP8 and I had Critical errors when cron jobs from the server were executed... Please check if those issues can affect those errors or any other errors with PHP8, Thanks 

### Screenshots

NA

### Expected Behavior

NA

### Actual Behavior Error report from PHP Compatibility Checker

WooCommerce PayPal Payments
PHP 8.0 incompatibilities:

FILE: vendor/dhii/human-readable-interface/src/CaptionAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/DescriptionAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/LabelAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/MessageAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/TitleAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/CaptionAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/DescriptionAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/LabelAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/MessageAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/TitleAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Environment

WordPress version: |   | 6.3.1
-- | -- | --
WooCommerce version: |   | 8.1.1
Server info: |   | Apache
PHP version: |   | 8.0.30
PHP post max size: |   | 512 MB
PHP time limit: |   | 3000
PHP max input vars: |   | 30000
cURL version: |   | 8.3.0, OpenSSL/1.1.1w
SUHOSIN installed: |   | –
MySQL version: |   | 5.7.43
Max upload size: |   | 512 MB
  |   |  
Active plugins (36) |   |  
Polylang |   | by WP SYNTEX – 3.4.5
Akismet Anti-spam: Spam Protection |   | by Automattic - Anti-spam Team – 5.3
Code Snippets |   | by Code Snippets Pro – 3.5.0
Yoast Duplicate Post |   | by Enrico Battocchi & Team Yoast – 4.5
EWWW Image Optimizer |   | by Exactly WWW – 7.2.1
reCaptcha by BestWebSoft |   | by BestWebSoft – 1.73
Jetpack |   | by Automattic – 12.6
Loginizer |   | by Softaculous – 1.8.1
Max Mega Menu - Pro Addon |   | by megamenu.com – 2.2.9.1
Max Mega Menu |   | by megamenu.com – 3.2.3
Popup Maker |   | by Popup Maker – 1.18.2
reCaptcha for WooCommerce |   | by I Thirteen Web Solution – 2.47
Plugin for Google Reviews |   | by RichPlugins – 2.8
Checkout Field Editor for WooCommerce |   | by ThemeHigh – 1.9.1
Product Feed ELITE for WooCommerce |   | by AdTribes.io – 3.3.4
WooCommerce Conditional Shipping and   Payments |   | by WooCommerce – 1.15.3
WooCommerce Conversion Tracking |   | by weDevs – 2.0.11
WooCommerce Customer/Order/Coupon Export |   | by SkyVerge – 5.5.0
Customizer for WooCommerce |   | by SkyVerge – 2.8.0
WooCommerce Stripe Gateway |   | by WooCommerce – 7.6.0
WooCommerce Google Analytics Integration |   | by WooCommerce – 1.8.5
Booster for WooCommerce |   | by Pluggabl LLC – 7.1.1
WooCommerce MSRP Pricing |   | by Ademti Software Ltd. – 3.4.21
WooCommerce PayPal Payments |   | by WooCommerce – 2.2.2
WooCommerce Print Invoices/Packing Lists |   | by SkyVerge – 3.13.1
WooCommerce Product Enquiry Form |   | by WooCommerce – 1.2.24
WooCommerce Product Search |   | by itthinx – 4.16.0
WooCommerce Table Rate Shipping |   | by WooCommerce – 3.1.4
WooCommerce |   | by Automattic – 8.1.1
Yoast SEO |   | by Team Yoast – 21.2
WP Fastest Cache |   | by Emre Vona – 1.1.9
WP-Lister Pro for eBay |   | by WP Lab – 3.5.1
WP Mail SMTP Pro |   | by WP Mail SMTP – 3.9.0
YITH RAQ fix fo wc conditional shipping |   | by YITH – 1.0.0
YITH WooCommerce Product Add-ons &   Extra Options Premium |   | by YITH – 4.4.0
YITH Request a Quote for WooCommerce   Premium |   | by YITH – 4.17.0

Inactive plugins (7) |   |  
Mailchimp for WooCommerce |   | by Mailchimp – 3.2
Popups for Divi |   | by divimode.com – 3.0.5
Product Import Export for WooCommerce |   | by WebToffee – 2.3.4
Term Management Tools |   | by theMikeD, scribu – 2.0.1
WooCommerce Sequential Order Numbers Pro |   | by SkyVerge – 1.19.0 (update to version 1.20.3 is available)
WP Crontrol |   | by John Blackbourn & crontributors – 1.15.3
WP Missed Schedule (The Original) |   | by sLaNGjIs Team – 2014.1231.2017.12

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @PierreWS 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you described here, is most likely not an issue with our plugin. We have tested our plugin fully with this PHP version and did not encounter this described situation. I would expect there might be a conflict present with another plugin. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If this does not help you further, please open a support request as explained above.

Kind regards, 
Joost
