### ISSUE TITLE
Conflict with WooCommerce Produce Bundles Plugin adding Products to Cart

### ISSUE THREAD

**Issue by bmzero** [woocommerce/woocommerce-paypal-payments#1724]
### Describe the Bug

With version 2.2.2 installed, guest users cannot add bundled products to the shopping cart.

### To Reproduce

Using WP Safe Mode, I was able to deactivate all plugins and narrow down the problem. With only WooCommerce, WooCommerce Product Bundles, WooCommerce PayPal Payments, and WP Safe Mode enabled (on Twenty Twenty theme), the issue persists.

Attempt to add a bundled product to the shopping cart. The mini-cart opens up, the product appears to be added, but sometimes immediately disappears. Sometimes it appears to stay in the cart, but clicking the View Cart button reveals an empty cart.

Disabling WooCommerce PayPal Payments resolves the issue.

### Screenshots

Here's a video submitted by a customer of ours - https://www.dropbox.com/scl/fi/vqx76mu4j3uam0y1n33t0/AAL-broken-website.mov

Here's the screenshot of the console errors.

![2023-09-22_17-06-00](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1192516/0ee300de-fb79-4806-a45e-0fe9e3cf32cc)

### Expected Behavior

It is expected that the products are added to the cart and remain in the cart.

### Actual Behavior

Products immediately disappear from the cart.

### Environment

 - WordPress Version - 6.3.1
 - WooCommerce Version - 8.1.1
 - Plugin Version - 2.2.2
 - Browser [e.g. Chrome, Safari] and Version - Chrome 117.0.5938.92 
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

### WordPress Environment ###

WordPress address (URL): https://americanadventurelab.com
Site address (URL): https://americanadventurelab.com
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.28
PHP Post Max Size: 8 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 8.0.25
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Total Database Size: 6173.95MB
Database Data Size: 5828.39MB
Database Index Size: 345.56MB
wp_woocommerce_sessions: Data: 59.14MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 6.52MB + Index: 2.50MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 86.61MB + Index: 47.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_acfw_store_credits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 4.02MB + Index: 9.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.02MB + Index: 3.03MB + Engine InnoDB
wp_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.50MB + Index: 0.48MB + Engine InnoDB
wp_comments: Data: 48.58MB + Index: 28.56MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ee_product_feed: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_call: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_products_sync_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_tiktok_catalog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ff_scheduled_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_entry_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_analytics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submission_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_fluentform_submissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 6.16MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 1.50MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_customer_pairs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_log: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_payment_id_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_paymentmethod_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_product_pairs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_customers: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_qbo_items: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_history: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_real_time_sync_queue: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_sessions: Data: 0.47MB + Index: 0.25MB + Engine MyISAM
wp_mw_wc_qbo_sync_shipping_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_tax_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mw_wc_qbo_sync_variation_pairs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mw_wc_qbo_sync_wq_cf_map: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2529.11MB + Index: 8.08MB + Engine InnoDB
wp_postmeta: Data: 157.69MB + Index: 128.27MB + Engine InnoDB
wp_posts: Data: 36.20MB + Index: 8.70MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.33MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_short_link_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_short_link_replacements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_short_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_relationships: Data: 0.34MB + Index: 0.20MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 24.41MB + Index: 14.89MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.64MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.50MB + Index: 1.83MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 2.45MB + Index: 2.14MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 6.48MB + Index: 5.84MB + Engine InnoDB
wp_wc_order_stats: Data: 5.52MB + Index: 4.48MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.28MB + Index: 0.27MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.22MB + Index: 0.33MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 2735.28MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 29.58MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 2.02MB + Index: 0.23MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 0.45MB + Index: 0.14MB + Engine InnoDB
wp_wfNotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfSecurityEvents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfStatus: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfWafFailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.34MB + Index: 0.33MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 9.52MB + Index: 34.64MB + Engine InnoDB
wp_wps_index: Data: 21.05MB + Index: 28.05MB + Engine InnoDB
wp_wps_key: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wp_wps_object_term: Data: 1.06MB + Index: 2.31MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_wps_uri: Data: 3.52MB + Index: 2.52MB + Engine InnoDB
wp_wps_user_agent: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_yikes_easy_mc_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 1.03MB + Index: 0.09MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 1.03MB + Index: 3.22MB + Engine InnoDB
wp_yoast_indexable: Data: 7.08MB + Index: 2.16MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.03MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.33MB + Index: 0.45MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_bans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_elements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_logs: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_other_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_polls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_skins: Data: 0.28MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_subelements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoppoll_votes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3521
blocks: 9
custom_css: 1
customize_changeset: 1
featured_item: 8
jetpack_migration: 2
jp_img_sitemap: 8
jp_img_sitemap_index: 4
jp_sitemap: 4
jp_sitemap_master: 4
mc4wp-form: 1
modula-gallery: 2
nav_menu_item: 36
oembed_cache: 31
page: 57
post: 38
product: 376
product_variation: 957
revision: 3023
seedprod: 3
shop_coupon: 3375
shop_order: 23140
shop_order_refund: 2144
sidebar: 1
ux_template: 6
wc_order_email: 6
wc_order_status: 19
wp_global_styles: 1
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (55) ###

WooCommerce Orders and Products Export - MR: by Sergey Gudymenko – 3.11.6
Additional Order Filters for WooCommerce: by Anton Bond – 1.10
Antispam Bee: by pluginkollektiv – 2.11.5
Cart Upsell for WooCommerce: by SKROTRON – 1.0.8
Contact Form 7: by Takayuki Miyoshi – 5.8
Conversios.io - All-in-one Google Analytics, Pixels and Product Feed Manager for WooCommerce: by Conversios – 6.6.1
Facebook for WooCommerce: by Facebook – 3.0.33
Hide Categories and Products for Woocommerce: by N.O.U.S. Open Useful and Simple – 1.2.9
VerifyPass: by VerifyPass – 4.0.2
Jetpack: by Automattic – 12.6.1
Kaya QR Code Generator: by Kaya Studio – 1.5.3
LiveChat WooCommerce: by LiveChat – 2.2.14
Mailchimp for WooCommerce: by Mailchimp – 3.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.7
WooCommerce Sync for QuickBooks Online - by MyWorks Software: by MyWorks Software – 2.8.1
Order Export & Order Import for WooCommerce: by WebToffee – 2.3.9
Product Import Export for WooCommerce: by WebToffee – 2.3.4
Redirection: by John Godley – 5.3.10
Slugs Manager: by WPFactory – 2.6.3
WooCommerce Split Orders: by Vibe Agency – 1.6.8
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.39
User Role Editor: by Vladimir Garagulya – 4.64
User Switching: by John Blackbourn & contributors – 1.7.0
W3 Total Cache: by BoldGrid – 2.4.1
InXpress Shipping Extension: by InXpress – 3.0.5
WooCommerce Extra Fees Plugin: by theDotstore – 3.9.4
WooCommerce Brands: by WooCommerce – 1.6.58
WooCommerce - FarApp: by FarApp – 1.3.4
WooCommerce Order Status Manager: by SkyVerge – 1.15.2
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.13.1
WooCommerce Product Add-ons: by WooCommerce – 6.4.7
WooCommerce Product Bundles: by WooCommerce – 6.22.3
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.61
WooCommerce Product Search: by itthinx – 4.16.0
WooCommerce Shipping & Tax: by WooCommerce – 2.3.5
WooCommerce Shipment Tracking: by WooCommerce – 2.4.0
WooCommerce Shipping Per Product v2: by WooCommerce – 2.5.3
WooCommerce UPS Shipping: by WooCommerce – 3.5.7
WooCommerce USPS Shipping: by WooCommerce – 4.7.4
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.9
WooCommerce Smart Coupons: by StoreApps – 8.6.0
WooCommerce Smart Orders Page: by FEST Agency – 1.4.4
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.8
WooCommerce: by Automattic – 8.1.1
WooSidebars: by WooCommerce – 1.4.6
Wordfence Security: by Wordfence – 7.10.3
Yoast SEO: by Team Yoast – 21.2
WP Extra File Types: by Davide Airaghi – 0.5.2
WP Mail SMTP: by WP Mail SMTP – 3.9.0
WP Safe Mode: by Marcus Sykes – 1.3
Yoast SEO: WooCommerce: by Team Yoast – 15.6
Product Import Export for WooCommerce Add-on: by WebToffee – 1.1.5
Import Export for WooCommerce Wrapper: by WebToffee – 1.2.4
Easy Forms for Mailchimp: by YIKES
Inc. – 6.8.9

### Inactive Plugins (3) ###

Advanced Coupons for WooCommerce Free: by Rymera Web Co – 4.5.7
WooCommerce PayPal Payments: by WooCommerce – 2.2.0 (update to version 2.2.2 is available)
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

WP Safe Mode Bootstrap File: by WP Safe Mode – 1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #62 - /shop/
Cart: #61 - /cart/
Checkout: #60 - /checkout/
My account: #59 - /my-account/
Terms and conditions: #28416 - /returns/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.17.7
Parent Theme Author URL: https://uxthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/order-received.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 6.22.3
Loopback Test: ✔
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-23 19:33:18 -05:00
Options: ✔
Notes: 192
Onboarding: completed

### Action Scheduler ###

Canceled: 7
Oldest: 2023-08-28 22:10:12 +0000
Newest: 2023-09-21 16:06:45 +0000

Complete: 8,876
Oldest: 2023-08-23 02:16:02 +0000
Newest: 2023-09-23 01:26:21 +0000

Failed: 790
Oldest: 2022-11-09 10:08:40 +0000
Newest: 2023-09-22 23:08:13 +0000

Pending: 3
Oldest: 2023-09-23 06:42:45 +0000
Newest: 2023-09-23 15:29:22 +0000

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: 
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: no
Combine emails: no
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: yes
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2023-09-22 20:53:31 -05:00
`

</details>

**Comment by Sirvijver** [comment]
Hello @bmzero 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are reporting is a known issue and will be resolved in the next release. You can already use the beta version for our next release [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.3.0-rc2/woocommerce-paypal-payments.zip), but we are still testing this package. The official release should take place next week.
Details on this issue can be found [here](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1645).

If you require more assistance, please open a support request as explained above. This thread will be closed.

Kind regards, 
Joost

**Comment by Coldkennels** [comment]
Hey @Sirvijver, I've been struggling with the same issue @bmzero mentioned in the original post for a while now - at least a couple of months - and have finally tracked it down to the Woocommerce Paypal Payments plugin after finding this post. Somehow, this bug has obviously worked its way back into the plugin.
