### ISSUE TITLE
hola no me llegan los pagos por tarjeta a mi cuenta 

### ISSUE THREAD

**Issue by gamatecnologica** [woocommerce/woocommerce-paypal-payments#1726]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by gamatecnologica** [comment]
hola no esta llegando el importe de mis ventas por tarjeta mediante paypal a mi cuenta, cual es la solucion?

**Comment by Sirvijver** [comment]
Hola @gamatecnologica,

Te has comunicado para abrir un foro en GitHub con una solicitud de soporte. Utilizamos GitHub principalmente para actividades de desarrollo, por lo que me gustaría pedirte que te pongas en contacto directamente con el equipo de soporte para obtener más orientación. Puedes hacerlo aquí: [Contactar con el equipo de soporte](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Actualmente, no tenemos ningún error abierto que coincida con la descripción de tu problema. Es posible que simplemente estés teniendo un problema de configuración, pero solo podremos verificarlo si obtenemos más detalles de tu parte. Si deseas que investiguemos más a fondo esto, por favor, abre un contacto privado como se indicó anteriormente, e incluye el informe del sistema, los registros y las notas de pedido para ver qué está sucediendo con estos pedidos.

En primer lugar, te sugeriría que [te pongas en contacto con el Soporte Técnico para Comerciantes de PayPal](https://www.paypal-techsupport.com/s/contactsupport) para que revisen y comenten sobre los ID de transacción relacionados con estos pedidos. Luego, si todavía necesitas nuestro apoyo, abre un hilo privado con nosotros.

Cerraremos este hilo ya que no proporcionamos soporte a través de GitHub.

Saludos cordiales,
Joost

===original English message===

Hello @gamatecnologica 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We do currently not have any bug open that matches your trouble description. It could be that you are simply having a configuration issue, but we can only verify that if we get more details from you. If you want us to look further into this, please open a private engagement as informed above, including the system report, logs and order notes, to see what is happening on with these orders.
Firstly, I would ask [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to review and comment on the transaction ID's that are related to these orders and after that open a private thread with us, if our support is still needed.

We will close this thread as we do not provide support via GitHub.

Kind regards, 
Joost
