### ISSUE TITLE
v 2.3.0 – Fatal Error when saving WooCommerce variations (2079)

### ISSUE THREAD

**Issue by MicPass** [woocommerce/woocommerce-paypal-payments#1730]
New version 2.3.0 causes fatal error when saving variations, here Woocommerce log:

2023-09-26T08:53:13+00:00 CRITICAL Uncaught Error: Class “WC_Subscriptions_Product” not found in /var/www/vhosts/…/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:545
Stack trace:
#0 /var/www/vhosts/…/wp-includes/class-wp-hook.php(312): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}() 
#1 /var/www/vhosts/…/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /var/www/vhosts/…/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/vhosts/…/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(568): do_action()
#4 /var/www/vhosts/…/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2425): WC_Meta_Box_Product_Data::save_variations()
#5 /var/www/vhosts/…/wp-includes/class-wp-hook.php(310): WC_AJAX::save_variations()
#6 /var/www/vhosts/…/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#7 /var/www/vhosts/…/wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/vhosts/…/wp-admin/admin-ajax.php(188): do_action() #9 {main} thrown in /var/www/vhosts/…/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php alla riga 545

**Comment by InpsydeNiklas** [comment]
Hi @MicPass, thanks for reporting the issue and apologies for the error.
Could you please give it a try with [this version](https://drive.google.com/uc?export=download&id=1GpwvhJOQRvq_7nEWEJNozN_HcIwL7vJT) and let us know if this resolves the error for you? Thank you!

**Comment by MicPass** [comment]
Thank you but I still experience problems, latest log:

2023-09-26T10:20:27+00:00 CRITICAL Uncaught Error: Class "WC_Subscriptions_Product" not found in /var/www/vhosts/.../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:556
Stack trace:
#0 /var/www/vhosts/.../wp-includes/class-wp-hook.php(312): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}()
#1 /var/www/vhosts/.../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /var/www/vhosts/.../wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/vhosts/.../wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(568): do_action()
#4 /var/www/vhosts/.../wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2425): WC_Meta_Box_Product_Data::save_variations()
#5 /var/www/vhosts/.../wp-includes/class-wp-hook.php(310): WC_AJAX::save_variations()
#6 /var/www/vhosts/.../wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#7 /var/www/vhosts/.../wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/vhosts/.../wp-admin/admin-ajax.php(188): do_action()
#9 {main}
  thrown in /var/www/vhosts/.../wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php alla riga 556

<img width="1557" alt="Schermata 2023-09-26 alle 12 21 11" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/123643076/1f7f888b-ed61-4e5f-b50e-606120a1a965">

**Comment by InpsydeNiklas** [comment]
Hi @MicPass thank you for the feedback. We created a [new version](https://drive.google.com/uc?export=download&id=1GpwvhJOQRvq_7nEWEJNozN_HcIwL7vJT) (same download link) that should resolve this issue for variable products as well. Please give it a try and let us know if this fully resolves the problem for you now. Thanks again!

**Comment by MicPass** [comment]
Great, it seems to be working. Thank you!

**Comment by InpsydeNiklas** [comment]
@MicPass Thank you for the feedback! The team is looking to release soon a [2.3.1 update](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.3.1-rc1) with the fix for this issue.

**Comment by MicPass** [comment]
Great, thank you!
