### ISSUE TITLE
Mini-Cart Bug cause of wrong DOM-Structure in v2.3.1 (2094)

### ISSUE THREAD

**Issue by webandhost** [woocommerce/woocommerce-paypal-payments#1735]
### Describe the Bug

The newest version generates a broken header, when adding paypal to minicart. 
There is a closing div at the and, which closes a parent element:

<p class="woocommerce-mini-cart__buttons buttons"><span id="ppc-button-minicart"></span></div>

### To Reproduce

Install WooCommerce PayPal Payments (v2.3.1) and activate the minicart checkout
You have to add an article to you cart to see the bug

### Expected Behavior

Right DOM-Structure

### Actual Behavior

Wrong DOM-Structure

### Environment

 - WordPress v6.3.1
 - WooCommerce v8.1.1 
 - WooCommerce PayPal Payments v2.3.1
 - Firefox v116.0.3

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @webandhost, thank you for reporting this issue. 
This problem should be resolved in [this version](https://drive.google.com/uc?export=download&id=1IroCb-i-s9lcndSJ44TtKOEN11gaETB6). Please let us know how this works for you. Thank you!

**Comment by webandhost** [comment]
Hello @InpsydeNiklas thanks for your reply.
The site doesn't run with this version and gives an error, which file needs to be replaced?
Probably it would be best if I just replace the changed file(s)?

**Comment by InpsydeNiklas** [comment]
The linked package is a complete plugin and compared to the regular version 2.3.1, it only changes one line of code in the file `modules/ppcp-button/src/Assets/SmartButton.php`, as can be seen in this PR: https://github.com/woocommerce/woocommerce-paypal-payments/pull/1736/files
So when you have e.g. FTP access, you could also manually change the `echo '</div>';` on line 485 to `echo '</p>';` on your existing plugin installation. 
I hope this helps! If you need additional guidance, I recommend [contacting our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly.

**Comment by webandhost** [comment]
Thanks again @InpsydeNiklas
I  changed line 485 in modules/ppcp-button/src/Assets/SmartButton.php
Now everything works as usual again!
