### ISSUE TITLE
Problems with only Mastercard credit cards

### ISSUE THREAD

**Issue by stemazzara** [woocommerce/woocommerce-paypal-payments#1744]
### Describe the Bug

Hello, i have some troubles on my website https://pgpharma.it/. Payment made with Mastercard Credit card don't work, while those ones made with a Visa credit card correctly work. Can you tell me what the problem could be and how to solve it?

Thank you very much, bye

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @stemazzara,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you report could be related to [the Advanced credit and debit country and currency availability](https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/). Please check the link and open a new support thread, as advised above, if you still need our support.

Kind regards, 
Joost
