### ISSUE TITLE
Paypal Button is not Showing 

### ISSUE THREAD

**Issue by usajacketsstore** [woocommerce/woocommerce-paypal-payments#1752]

**Comment by Sirvijver** [comment]
Hello @usajacketsstore 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are describing sounds like an issue with your theme or something blocking the button (the JavaScript it is using). You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If this does not help, please open a private engagement with us as described above.

Kind regards, 
Joost
