### ISSUE TITLE
unable to save subscription with Paypal enabled

### ISSUE THREAD

**Issue by hyperterry** [woocommerce/woocommerce-paypal-payments#1756]
### Describe the Bug

With Subscriptions version 3.1.6 (yes it's old) and Woocommerce Paypal version 2.3.1 I cannot save a Subscription in wp-admin backend.
I have Paypal's Subscriptions settings Disabled, error still happens.

`Fatal error: Uncaught Error: Call to undefined method WP_Post::get_meta() in example/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:596 Stack trace: #0 example/public/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}(39091, Object(WP_Post)) #1 example/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #2 example/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 example/public/wp-content/plugins/woocommerce-subscriptions_3_1_6/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php(417): do_action('woocommerce_pro...', 39091, Object(WP_Post)) #4 example/public/wp-includes/class-wp-hook.php(310): WCS_Meta_Box_Subs in example/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php on line 596`

### To Reproduce

1. Go to '/wp-admin/post.php?post=39091&action=edit'
2. Click on Update'
3. See error

### Expected Behavior

Should not be calling subscriptions code when Paypal subscriptions are not enabled and using an old version of Subscriptions plugin.

### Actual Behavior

With the Paypal plugin enabled, this error shows no matter what settings of Paypal plugin.

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version 8.1.1
 - Plugin Version WooCommerce PayPal Payments 2.3.1
 - Plugin Version WooCommerce Subscriptions 3.1.6
 
### Additional Details

Reverting Paypal payments to version 2.2.1 fixes the issue.

**Comment by InpsydeNiklas** [comment]
Hi @hyperterry this issue was likely fixed in #1748. Can you give it a try [with this version](https://drive.google.com/uc?export=download&id=1JtG0TfSYRKTrdCohFlYfZOPNCp5VWyKX) and let us know if this resolves the error for you? Thank you!

**Comment by hyperterry** [comment]
> Hi @hyperterry this issue was likely fixed in #1748. Can you give it a try [with this version](https://drive.google.com/uc?export=download&id=1JtG0TfSYRKTrdCohFlYfZOPNCp5VWyKX) and let us know if this resolves the error for you? Thank you!

Yep seems to be working now thanks.

**Comment by InpsydeNiklas** [comment]
Thanks for the feedback! The change was included in versions 2.4.0 and newer.
