### ISSUE TITLE
Failed to load webhooks

### ISSUE THREAD

**Issue by dunght5185** [woocommerce/woocommerce-paypal-payments#1758]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @dunght5185 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide us many details so this will be a fairly general response. 
Have you already tested the webhooks in the plugin settings tab "Connection"? There you will find the button "Simulate" and "Resubscribe" that can help you test and resolve this issue. If that does not help you fix it, you might want to try deactivating all other plugins and temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

If that does not help you identify the cause of this issue, please open a private thread as described above.

Kind regards, 
Joost
