### ISSUE TITLE
New Order confirmation email is not received in orders with variable products when transaction is via Paypal and error is logged. 

### ISSUE THREAD

**Issue by exonianp** [woocommerce/woocommerce-paypal-payments#1764]
### Describe the Bug

When the user opts to pay with Paypal we do not receive a notication about their order (nor the customer). 

This error is also logged. 

[Sat Oct 14 15:20:36.671553 2023] [proxy_fcgi:error] [pid 9707:tid 140367282288384] [client 62.74.46.173:0] AH01071: Got error 'PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_COD->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_New_Order->trigger, WC_Email->get_content, WC_Email_New_Order->get_content_html, wc_get_template_html, wc_get_template,...; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_COD->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_New_Order->trigger, WC_Email->get_content, WC_Email_New_Order->get_content_html, wc_get_template_html, wc_get_template,...; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_COD->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Processing_Order->trigger, WC_Email->get_content, WC_Email_Customer_Processing_Order->get_content_html, wc_get...; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_COD->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Processing_Order->trigger, WC_Email->get_content, WC_Email_Customer_Processing_Order->get_content_html, wc_get...', referer: https://beautyhouse.gr/checkout/

[Sat Oct 14 15:31:05.508571 2023] [proxy_fcgi:error] [pid 9707:tid 140368356030208] [client 45.139.215.230:0] AH01071: Got error 'PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Gateway\\PayPalGateway->process_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->process, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_new_order_status, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, ...; PHP message: The WC_Product::get_variation_description function is deprecated since version 3.0. Replace with WC_Product::get_description().; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Gateway\\PayPalGateway->process_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->process, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_new_order_status, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, ...; PHP message: The WC_Product::get_variation_description function is deprecated since version 3.0. Replace with WC_Product::get_description().; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Gateway\\PayPalGateway->process_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->process, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_new_order_status, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, ...; PHP message: The WC_Product::get_variation_description function is deprecated since version 3.0. Replace with WC_Product::get_description().; PHP message: id was called incorrectly. \xce\x9f\xce\xb9 \xce\xb9\xce\xb4\xce\xb9\xcf\x8c\xcf\x84\xce\xb7\xcf\x84\xce\xb5\xcf\x82 \xcf\x80\xcf\x81\xce\xbf\xcf\x8a\xcf\x8c\xce\xbd\xcf\x84\xce\xbf\xcf\x82 \xce\xb4\xce\xb5 \xce\xb8\xce\xb1 \xce\xad\xcf\x80\xcf\x81\xce\xb5\xcf\x80\xce\xb5 \xce\xbd\xce\xb1 \xcf\x80\xcf\x81\xce\xbf\xcf\x83\xcf\x80\xce\xb5\xce\xbb\xce\xb1\xcf\x8d\xce\xbd\xce\xbf\xce\xbd\xcf\x84\xce\xb1\xce\xb9 \xce\xb1\xcf\x80\xce\xb5\xcf\x85\xce\xb8\xce\xb5\xce\xaf\xce\xb1\xcf\x82. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Gateway\\PayPalGateway->process_payment, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->process, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_new_order_status, WooCommerce\\PayPalCommerce\\WcGateway\\Processor\\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, ...; PHP message: The WC_Product::get_variation_description function is deprecated since version 3.0. Replace with WC_Product::get_description().', referer: https://beautyhouse.gr/checkout/

### To Reproduce

It happens with all sales.

You have to have variable products  in your cart and attempt to pay via paypal. 

### Expected Behavior

To receive the emails and have no errors logged

### Actual Behavior
As above

### Environment

 - WordPress Version 6.3.2
 - WooCommerce Version 8.2
 - Plugin Version 2.3.1 
 - Browser [e.g. Chrome, Safari] and Version: any
 - Any other plugins installed (irrelevant. It is product type specific - as stated in the error)

DB: MariaDB 10.6

**Important: php version is 8.2** 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @exonianp 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
