### ISSUE TITLE
When this plugin is active, can't edit Thrive Themes Woo templates and Woo-related pages are foormatted incorrectly.

### ISSUE THREAD

**Issue by dsvidan2010** [woocommerce/woocommerce-paypal-payments#1765]
### Describe the Bug

When you visit my shop, visit a product, then add something to cart, immediately there is a very large white space above the product listing.  Sometimes, after adding to cart, you need to click a related product on the same page, jump from the menu to the shop page, and then back to a different product.

When you scroll down, various formatting issues are present.  Mismatching fonts, hidden headers are exposed, etc.  Everything seems misaligned.

Whenever I disable the Paypal Payments plugin, all seems to work.  (Aside from a caching issue where the quantity in cart on a product page does not match what is shown in the mini cart on the shop page.  I believe this to be unrelated for now).

### To Reproduce

1. Go to 'https://todaysboxingmedia.com/shop'
2. Click on a product for example: "Green Belt Boxing Training Bag".
3. Verify the mini cart shows an item in cart.
4. The page may immediately show a large white space below the header now with improperly formatted body of product page below it.
5. move from product to product and you can see now all products are formatted incorrectly.  On the back end, product templates are NOT modifiable now when this is occuring.

### Screenshots

Here, the front end shows large white spaces on product page:

<img width="1731" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/147902938/c232b020-4aec-4f77-be17-17b3b16afaee">

<img width="1731" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/147902938/c9368ade-b9ef-4836-861b-d30d88ba6e65">

On the back end, can't edit Woocommerce templates.  Nothing can be clicked on once the template is open until Paypal Payments is deactivated.:

### Expected Behavior

I should be able to edit Woocommerce templates and see products, shop, checkout page without large white space and incorrect formatting.

### Actual Behavior

All formatting when Paypal Payments is active is incorrect and large white space shows on all Woocommerce pages except the cart page.  On back end, unable to edit or click on any elements of the Woo template in Thrive Theme Builder until Paypal Payments is deactivated.

### Environment

Site/Plugin info:

Site address (URL): |   | https://todaysboxingmedia.com
WooCommerce version: |   | 8.2.0
WordPress version: |   | 6.3.2
Browsers: Multiple, Safari, chrome
Theme installed: Thrive Themes (Thrive architect)
WooCommerce Payments |   | by Automattic – 6.6.0
WooCommerce PayPal Payments |   | by WooCommerce – 2.3.1
Thrive Automator |   | by <a href="https://thrivethemes.com">Thrive Themes</a> – 1.16
Thrive Leads |   | by <a href="https://thrivethemes.com">Thrive Themes</a> – 3.23
Thrive Ovation |   | by <a href="https://thrivethemes.com">Thrive Themes</a> – 3.23
Thrive Product Manager |   | by Thrive Themes – 1.15
Thrive Ultimatum |   | by <a href="https://thrivethemes.com">Thrive Themes</a> – 3.23
Thrive Architect |   | by <a href="http://www.thrivethemes.com">Thrive Themes</a> – 3.25

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->


  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @dsvidan2010 
This sounds like it could be related to https://github.com/woocommerce/woocommerce-paypal-payments/issues/1735.
[This version](https://drive.google.com/uc?export=download&id=1IroCb-i-s9lcndSJ44TtKOEN11gaETB6) should resolve the issue for you. Alternatively, disabling the Mini Cart button may also prevent the behavior. 
In any case, this behavior will be resolved in the next plugin update.
I recommend [contacting the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you require additional guidance. Thank you!

**Comment by dsvidan2010** [comment]
Niklas,Thank you.  I’ll try this out.  Haven't really installed a plugin this way before.Are there alternative ways to roll back without installing a package downloaded outside of Wordpress?I have no issue doing it this way, just curious.Also, the link for “contacting the support team directly” takes me to Woocommerce.com.Should I not be opening tickets with the plugin forum on wordpress.org?Thanks!DuckySent from my iPhone On Oct 16, 2023, at 5:44 AM, Niklas Gutberlet ***@***.***> wrote:﻿
Hi @dsvidan2010
This sounds like it could be related to #1735.
This version should resolve the issue for you. Alternatively, disabling the Mini Cart button may also prevent the behavior.
In any case, this behavior will be resolved in the next plugin update.
I recommend contacting the support team directly if you require additional guidance. Thank you!
