### ISSUE TITLE
unable to capture the payment method to WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by justcalljarold** [woocommerce/woocommerce-paypal-payments#1768]
### Describe the Bug

Error Details
=============
Error message: Uncaught Error: Call to undefined method WP_Post::get_meta() in /[url]/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:596]([url]/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:596)
Stack trace:
#0 /[url]/public_html/wp-includes/class-wp-hook.php(310)]([url]/public_html/wp-includes/class-wp-hook.php(310)): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}(4303, Object(WP_Post))
#1 /[url]/public_html/wp-includes/class-wp-hook.php(334)]([url]/public_html/wp-includes/class-wp-hook.php(334)): WP_Hook->apply_filters('', Array)
#2 /[url]/public_html/wp-includes/plugin.php(517)]([url]/public_html/wp-includes/plugin.php(517)): WP_Hook->do_action(Array)
#3 /[url]/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php(417)]([url]/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php(417)): do_action('woocommerce_pro...', 4303, Object(WP_Post))
#4 /[url]/public_html/wp-includes/class-wp-hook.php(310)]([url]/public_html/wp-includes/class-wp-hook.php(310)): WCS_Meta_Box_Subscription_Dat

### To Reproduce

1. Go to 'Subscriptions[any]'
2. Click on 'Update'

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/148115004/273d8fc0-4130-4b67-9199-e9809116b85f)

### Expected Behavior

should not be having this error

### Actual Behavior

update changes made from WP-Admin and capture payment method on user side

### Environment

 - WordPress Version (6.3.2)
 - WooCommerce Version (8.2.0)
 - WooCommerce PayPal Payments (2.3.1)
 - WooCommerce Subscriptions (4.1.0)

### Additional Details

Enabled Vaulting on WooCommerce PayPal Payments (don't know if this helps but looking on the docs this should be enable so the payment method could be captured and reuse for automatic renewals)

**Comment by InpsydeNiklas** [comment]
Hi @justcalljarold 
This issue was resolved in the latest pre-release version which can be downloaded from here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.0-rc1
This update should be released within the next week or two, so I recommend giving it a try and letting us know if this resolves the error for you.
If any problems remain after applying either option, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
