### ISSUE TITLE
Updated First Name and Last name on Checkout page NOT being passed to Paypal

### ISSUE THREAD

**Issue by chicagowebmanagement** [woocommerce/woocommerce-paypal-payments#1769]
### Describe the Bug
Updated First Name and Last name on Checkout page NOT being passed to Paypal
However they ARE captured and retained in WooCommerce Order Details.

User logs in as FIRSTNAME with FIRSTNAME and LASTNAME
On checkout page, they change it to NEWFIRST and NEWLAST
Place order, and woocommerce captures NEWFIRST and NEWLAST for order details
However; Paypal credit processing shows FIRSTNAME and LASTNAME instead of the revised values.

### To Reproduce

1. LOGIN to ecommerce site as a buyer (any level, including admin)
2. Add items to cart and proceed to /checkout page
3. While at /checkout page, CHANGE the first and last name of buyer
4. Submit Credit card info and 'complete sale'
5. WooCommerce captures REVISED first and last names for the order.
6.  PayPal shows ORIGINAL first and last names for order; **this creates conflict when comparing buyer names.**

### Expected Behavior

Buyer's name (at moment of sale capture) should be passed to WooCommerce AND Paypal.

### Actual Behavior

IF user changes first and last names on /checkout page in woocommerce, Paypal fails to receive the updated information; only WooCommerce captures this updated information.

### Environment

`
### Describe the Bug
Updated First Name and Last name on Checkout page NOT being passed to Paypal
However they ARE captured and retained in WooCommerce Order Details.

User logs in as FIRSTNAME with FIRSTNAME and LASTNAME
On checkout page, they change it to NEWFIRST and NEWLAST
Place order, and woocommerce captures NEWFIRST and NEWLAST for order details
However; Paypal credit processing shows FIRSTNAME and LASTNAME instead of the revised values.

### To Reproduce

1. LOGIN to ecommerce site as a buyer (any level, including admin)
2. Add items to cart and proceed to /checkout page
3. While at /checkout page, CHANGE the first and last name of buyer
4. Submit Credit card info and 'complete sale'
5. WooCommerce captures REVISED first and last names for the order.
6.  PayPal shows ORIGINAL first and last names for order; **this creates conflict when comparing buyer names.**

### Expected Behavior

Buyer's name (at moment of sale capture) should be passed to WooCommerce AND Paypal.

### Actual Behavior

IF user changes first and last names on /checkout page in woocommerce, Paypal fails to receive the updated information; only WooCommerce captures this updated information.

### Environment

`
### WordPress Environment ###

WordPress address (URL): https://www.xxxxxxxxxxxx
Site address (URL): https://wwwxxxxxxxxxxxxx
WC Version: 8.1.1
REST API Version: ✔ 8.1.1
WC Blocks Version: ✔ 10.9.3
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: ❌ 6.3.1 - There is a newer version of WordPress available (6.3.2)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 100 MB
PHP Time Limit: 43300
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.34-26
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.1
WC Database Prefix: wp_
Total Database Size: 4185.47MB
Database Data Size: 3422.13MB
Database Index Size: 763.34MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 5.52MB + Index: 5.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 162.64MB + Index: 31.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fullfilled_by_amazon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
getcharacterdata: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oc_mysigns: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
oc_myweight: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ups_export_someurlsomesite: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
ups_shipping: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
vvv: Data: 0.00MB + Index: 0.00MB + Engine
wp_actionscheduler_actions: Data: 1.02MB + Index: 0.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.02MB + Index: 0.33MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ak_params: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ak_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ak_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ak_storage: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ak_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_akeeba_common: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_st: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 111.63MB + Index: 111.30MB + Engine InnoDB
wp_commentmeta: Data: 0.20MB + Index: 0.22MB + Engine InnoDB
wp_comments: Data: 23.56MB + Index: 20.09MB + Engine InnoDB
wp_duplicator_packages: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_easywpsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_easywpsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_edit_signs: Data: 19.55MB + Index: 1.52MB + Engine InnoDB
wp_email_log: Data: 19.52MB + Index: 0.00MB + Engine InnoDB
wp_fm_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 21.55MB + Index: 4.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 47.58MB + Index: 72.78MB + Engine InnoDB
wp_gf_entry_notes: Data: 8.52MB + Index: 3.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ocstores: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 31.33MB + Index: 3.70MB + Engine InnoDB
wp_postmeta: Data: 255.81MB + Index: 183.55MB + Engine InnoDB
wp_posts: Data: 29.56MB + Index: 13.58MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.52MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_rg_lead_detail: Data: 2.52MB + Index: 7.06MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_robogallery_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_session_signs: Data: 584.00MB + Index: 221.22MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_snippets: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_spu_hits_logs: Data: 13.52MB + Index: 9.55MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_usermeta: Data: 19.55MB + Index: 19.06MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.33MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 1.52MB + Index: 0.70MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 2.52MB + Index: 3.84MB + Engine InnoDB
wp_wc_order_stats: Data: 1.52MB + Index: 1.02MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.34MB + Index: 0.61MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpeditor_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpjf3_mr_access_keys: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpjf3_mr_unrestricted_ips: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppcp_group_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppcp_private_page: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppopups_hits: Data: 11.52MB + Index: 15.55MB + Engine InnoDB
wp_wpr_rucss_resources: Data: 1998.58MB + Index: 10.08MB + Engine InnoDB
wp_wpr_rucss_used_css: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_indexable: Data: 16.55MB + Index: 6.97MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 1.52MB + Index: 3.48MB + Engine InnoDB
wp_yoast_seo_links: Data: 2.52MB + Index: 2.00MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.44MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 6
acf-field: 58
acf-field-group: 13
attachment: 10094
blog: 24
custom_css: 1
deprecated_log: 14
e-landing-page: 1
elementor_library: 327
faq-posts: 43
flamingo_contact: 4646
flamingo_inbound: 9405
gallery: 1
herovideos: 1
nav_menu_item: 99
news_posts: 3
oembed_cache: 1
page: 321
post: 10
product: 3190
pys_event: 3
revision: 5
robo_gallery_table: 3
sb_gallery: 31
shop_coupon: 1024
shop_order: 23678
shop_order_refund: 598
slider: 3
slides: 1
spt: 1
spucpt: 3
store_page: 2427
testimonials: 11
wp-types-group: 15
wppopups: 5
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (65) ###

Gravity Forms: by Gravity Forms – 2.7.15
weLaunch Framework: by weLaunch.io – 1.0.19
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.1.0
Advanced Custom Fields: by WP Engine – 6.2.1
Advanced Post Types Order: by Nsp Code – 2.4.0.6
All-in-One WP Migration: by ServMask – 7.79
WP Engine Smart Plugin Manager: by WP Engine – 5.17.30
Code Snippets: by Code Snippets Pro – 3.5.0
Custom Field Template: by Hiroaki Miyashita – 2.6
Custom Permalinks: by Sami Ahmed Siddiqui – 2.5.2
GTM4WP: by Thomas Geiger – 1.18.1
Easy WP SMTP: by Easy WP SMTP – 2.1.2
Elementor Pro: by Elementor.com – 3.16.2
Elementor: by Elementor.com – 3.16.5
Email Log: by Sudar – 2.4.8
Error Log Monitor: by Janis Elsts – 1.7.7
File Manager Advanced: by modalweb – 5.1.2
Gravity Forms Event Tracking: by Ronald Huereca – 2.4.14
Gravity PDF: by Blue Liquid Designs – 6.7.1
Gravity Forms Survey Add-On: by Gravity Forms – 3.8
Intuitive Custom Post Order: by hijiri – 3.1.4.1
mobble: by Scott Evans – 1.6
PayPal for WooCommerce: by Angell EYE – 1.5.4
Post Type Switcher: by Triple J Software
Inc. – 3.2.1

Quick Page/Post Redirect Plugin: by anadnet – 5.2.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Robo Gallery: by RoboSoft – 3.2.16
Schema Creator by Raven: by Raven Internet Marketing Tools – 1.1.1
Simple Page Ordering: by 10up – 2.6.0
Simple Page Tester Premium: by Simple Page Tester – 1.4.2
Simple Page Tester: by Simple Page Tester – 1.4.5
Sitejabber: by Michael Lai – 1.0
someurlsomesite Braintree Payment Gateway: by someurlsomesite – 1.1
someurlsomesite Customer Order xls Export: by Edson Valdez – 1.0
The Permalinker: by  – 1.8.1
Advanced Editor Tools: by Automattic – 5.9.2
Toolset Types: by OnTheGoSystems – 2.3.5
Ultimate Noindex Nofollow Tool II: by Kilian Evang – 1.3.4
Use Administrator Password: by David Anderson – 1.3.1
User Role Editor: by Vladimir Garagulya – 4.64
User Switching: by John Blackbourn & contributors – 1.7.0
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.10
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.6
Product Feed PRO for WooCommerce: by AdTribes.io – 13.0.5
WooCommerce Custom Status: by Garman Technical Services – 1.0
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.0
WooCommerce Name Your Price: by Kathy Darling – 2.11.4
WooCommerce PayPal Payments: by WooCommerce – 2.3.1
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.0
WooCommerce Role Based Methods: by WPBackOffice – 2.4.1
WooCommerce Shipping & Tax: by WooCommerce – 2.3.6
WooCommerce UPS Shipping: by WooCommerce – 3.2.18
WooCommerce USPS Shipping: by WooCommerce – 4.4.35
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.16.3
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.21
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.27
WooCommerce Wholesale Prices: by Rymera Web Co – 2.1.9
WooCommerce: by Automattic – 8.1.1 (update to version 8.2.0 is available)
WordPress Country Selector: by weLaunch – 1.6.7
Yoast SEO Premium: by Team Yoast – 21.3
Yoast SEO: by Team Yoast – 21.3
WP Crontrol: by John Blackbourn & crontributors – 1.15.3
WP Editor: by Benjamin Rojas – 1.2.7
WP Private Content Plus: by Rakhitha Nimesh – 3.6
WP Popups: by timersys – 2.1.5.1

### Inactive Plugins (1) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (6) ###

Elementor Safe Mode: by Elementor.com – 1.0.0
Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.1.4
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.0
WP Engine System: by WP Engine – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7442 - /shop/
Cart: #5264 - /cart/
Checkout: #5323 - /checkout/
My account: #101963 - /my-account/
Terms and conditions: #9648 - /terms-conditions/

### Theme ###

Name: nothingtoknow
Version: 2.22.20140828.1213
Author URL: http://noone-youknow.net
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: someurlsomesite/woocommerce/cart/cart-empty.php
someurlsomesite/woocommerce/cart/cart-shipping.php
someurlsomesite/woocommerce/cart/cart-totals.php
someurlsomesite/woocommerce/cart/cart.php version 7.8.0 is out of date. The core version is 7.9.0
someurlsomesite/woocommerce/checkout/form-billing.php
someurlsomesite/woocommerce/checkout/form-checkout.php
someurlsomesite/woocommerce/checkout/form-coupon.php
someurlsomesite/woocommerce/checkout/payment.php version 7.8.0 is out of date. The core version is 8.1.0
someurlsomesite/woocommerce/checkout/review-order.php
someurlsomesite/woocommerce/checkout/thankyou.php version 3.7.0 is out of date. The core version is 8.1.0
someurlsomesite/woocommerce/content-product.php
someurlsomesite/woocommerce/content-single-product.php
someurlsomesite/woocommerce/emails/admin-new-order.php
someurlsomesite/woocommerce/emails/customer-completed-order.php
someurlsomesite/woocommerce/emails/customer-invoice.php
someurlsomesite/woocommerce/emails/email-order-items.php
someurlsomesite/woocommerce/emails/email-styles.php
someurlsomesite/woocommerce/global/quantity-input.php
someurlsomesite/woocommerce/loop/add-to-cart.php
someurlsomesite/woocommerce/loop/loop-start.php
someurlsomesite/woocommerce/loop/price.php
someurlsomesite/woocommerce/myaccount/dashboard.php
someurlsomesite/woocommerce/myaccount/form-edit-account.php
someurlsomesite/woocommerce/myaccount/form-edit-address.php
someurlsomesite/woocommerce/myaccount/form-login.php
someurlsomesite/woocommerce/myaccount/my-account.php
someurlsomesite/woocommerce/myaccount/my-address.php
someurlsomesite/woocommerce/myaccount/my-orders.php
someurlsomesite/woocommerce/myaccount/navigation.php
someurlsomesite/woocommerce/myaccount/orders.php
someurlsomesite/woocommerce/notices/error.php
someurlsomesite/woocommerce/notices/success.php
someurlsomesite/woocommerce/order/order-details-item.php
someurlsomesite/woocommerce/order/order-details.php
someurlsomesite/woocommerce/single-product/product-image.php
someurlsomesite/woocommerce/single-product/related.php
someurlsomesite/woocommerce/single-product/tabs/tabs.php
someurlsomesite/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-17 03:09:05 -05:00
Options: ✔
Notes: 156
Onboarding: completed

### Action Scheduler ###

Complete: 1,536
Oldest: 2023-09-15 22:22:12 -0500
Newest: 2023-10-16 11:53:36 -0500

Pending: 1
Oldest: 2023-10-17 04:06:09 -0500
Newest: 2023-10-17 04:06:09 -0500

### Status report information ###

Generated at: 2023-10-16 12:36:12 -05:00
`

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @chicagowebmanagement 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have recreated the same situation, where I used an existing WP customer and changed the FIRSTNAME and LASTNAME to NEWFIRSTNAME & NEWLASTNAME. However, for me this did not show up on the PayPal transaction details. For me the adjusted names showed up as expected.

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not show what is causing this issue, please open a private engagement with us as explaineb above.

Kind regards, 
Joost
