### ISSUE TITLE
 Plugin causes issues with items disappearing from cart

### ISSUE THREAD

**Issue by premkumarbsetec** [woocommerce/woocommerce-paypal-payments#1772]
Plugin causes issues with items disappearing from cart

### To Reproduce

When adding products to the basket (single units of different products) we are able to add 2 or 3 products, upon adding another product the cart will empty and just retain the 1 most recently added product. This happens on a mix of mobile and desktop browsers but can replicated consistently in Chrome, Incognito window

**Comment by InpsydeNiklas** [comment]
Hi @premkumarbsetec 
Can you please give it a try with the latest pre-release version from here and let us know if this resolves the issue for you?: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.0-rc1
If any problems remain after applying either option, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!

**Comment by rseher** [comment]
I have the same problem on my site.  If I disable The woo commerce paypal plugin the problem goes away.
![Screenshot 2023-10-18 at 2 46 43 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/148397190/1fb46bc1-1492-490a-a532-ccdaff4972fd)

Looks like we are done using paypal on our website until this gets fixed.  I am also using elementor pro on the site.

Thank you,

Roger

**Comment by Sirvijver** [comment]
Hello all,

this issue has been resolved with our upcoming release 2.4.0. You can already test this fix by using our beta release that you can download from [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.0-rc1).

We already have had some confirmations on the fix, so I will close this thread. If you still have issues, please open a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
