### ISSUE TITLE
Credit cart payment with not showing at checkout

### ISSUE THREAD

**Issue by validator16** [woocommerce/woocommerce-paypal-payments#1774]
### Describe the Bug

Since I updated the plugin, in the checkout the advanced card processing option appears with CSS display: none 
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/66414194/1a76c4d0-454a-4f09-b6b6-ef004e3abbc8)

### Expected Behavior

Card payment should be shown as a normal payment method, and not hidden.

### Actual Behavior

When you go to finalize the order at checkout the option to pay by credit card from the paypal plugin is not displayed. The integration is done correctly, we have been receiving payments since July, and suddenly I updated the plugin to the latest version and it shows as display none.
### Environment

 - WordPress Version: 6.3.2
 - WooCommerce Version: 8.2.1
 - Plugin Version: 2.3.1

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @validator16 
Saving any PayPal Payments settings page should make the Advanced Card Processing gateway reappear.
This behavior was resolved in the new pre-release version which can be downloaded from here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.0-rc1
If any problems remain after applying either option, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
