### ISSUE TITLE
the woocomerce paypal integration plugin pushes my buddyboss theme page 'body' to the centre of the page. please help - how can i fix this?

### ISSUE THREAD

**Issue by buddybuser** [woocommerce/woocommerce-paypal-payments#1776]
### Describe the Bug

the woocomerce paypal integration plugin pushes my buddyboss theme page 'body' to the centre of the page. please help 

### To Reproduce

I unactivated all my plugins and this plugin is clearly messing with all my Buddyboos theme pages

### Screenshots

<img width="1990" alt="Screen Shot 2023-10-17 at 21 38 07" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/148282695/41f5632f-cffa-4a50-8ee9-29549db7156c">

### Environment

 - WordPress Version - latest
 - WooCommerce Version - latest
 - Plugin Version -latest
 - Browser [e.g. Chrome, Safari] and Version -  firefox
 - Any other plugins installed - loads but I tested them all and it seems to only be this effecting the template files

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @buddybuser 
This behavior can be resolved by either installing the new pre-release version from here: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.0-rc1
Alternatively by disabling the Mini Cart button until the next update was officially released.
If any problems remain after applying either option, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
