### ISSUE TITLE
No Paypal Logo in the Checkout

### ISSUE THREAD

**Issue by admin100903** [woocommerce/woocommerce-paypal-payments#1777]
### Describe the Bug
we dont have the paypal logo in the checkout

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
here you can see we dont have a paypal logo in our checkout what we need please https://prnt.sc/dfukKAMNDIPq

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version 8.2.1
 - Plugin Version 2.3.1
 - Browser [e.g. Chrome, Safari] and Version: all browser
 - Any other plugins installed: for sure i have more plugins but all wordpress standard coded

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
`
### WordPress Environment ###

WordPress address (URL): https://wayofmusic.de
Site address (URL): https://wayofmusic.de
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: ❌ 6.3.1 - Es ist eine neuere Version von WordPress verfügbar (6.3.2)
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Wir empfehlen das PHP Speicher-Limit (memory_limit) auf mindestens 64 MB zu setzen. Siehe: PHP Speicher-Limit erhöhen
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-1:10.6.15+maria~deb11-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() ist fehlgeschlagen. Kontaktieren Sie Ihren Webhosting-Anbieter.

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: e42g_
Datenbank-Gesamtgröße: 476.63MB
Datenbank-Datengröße: 387.82MB
Datenbank-Indexgröße: 88.81MB
e42g_woocommerce_sessions: Daten: 9.02MB + Index: 0.14MB + Engine InnoDB
e42g_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
e42g_woocommerce_order_items: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB
e42g_woocommerce_order_itemmeta: Daten: 0.34MB + Index: 0.33MB + Engine InnoDB
e42g_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
e42g_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_actionscheduler_actions: Daten: 9.02MB + Index: 10.58MB + Engine InnoDB
e42g_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_actionscheduler_logs: Daten: 7.02MB + Index: 6.03MB + Engine InnoDB
e42g_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_comments: Daten: 0.25MB + Index: 0.31MB + Engine InnoDB
e42g_e_events: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_e_submissions: Daten: 0.02MB + Index: 0.27MB + Engine InnoDB
e42g_e_submissions_actions_log: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
e42g_e_submissions_values: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_gla_attribute_mapping_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_gla_budget_recommendations: Daten: 0.22MB + Index: 0.14MB + Engine InnoDB
e42g_gla_merchant_issues: Daten: 2.02MB + Index: 0.00MB + Engine InnoDB
e42g_gla_shipping_rates: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_gla_shipping_times: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_jetpack_sync_queue: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
e42g_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_automations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_automation_runs: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
e42g_mailpoet_automation_run_logs: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_mailpoet_automation_run_subjects: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_automation_triggers: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_automation_versions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_newsletters: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_newsletter_templates: Daten: 3.28MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_scheduled_tasks: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
e42g_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
e42g_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_subscribers: Daten: 0.02MB + Index: 0.23MB + Engine InnoDB
e42g_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_subscriber_tag: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_mailpoet_tags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_options: Daten: 20.05MB + Index: 4.03MB + Engine InnoDB
e42g_pmxi_files: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_hash: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_history: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_images: Daten: 0.50MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_imports: Daten: 0.27MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_posts: Daten: 1.36MB + Index: 0.00MB + Engine InnoDB
e42g_pmxi_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_postmeta: Daten: 169.13MB + Index: 32.16MB + Engine InnoDB
e42g_posts: Daten: 106.05MB + Index: 6.27MB + Engine InnoDB
e42g_rank_math_internal_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_asset_seo_redirect: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_blocker_thumbnails: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_consent: Daten: 5.52MB + Index: 2.09MB + Engine InnoDB
e42g_rcb_revision: Daten: 0.23MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_revision_independent: Daten: 0.14MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_scan: Daten: 24.05MB + Index: 13.11MB + Engine InnoDB
e42g_rcb_scan_markup: Daten: 0.20MB + Index: 0.06MB + Engine InnoDB
e42g_rcb_stats: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_stats_buttons_clicked: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_stats_custom_bypass: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_tcf_features: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_tcf_purposes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_tcf_special_features: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_tcf_special_purposes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_tcf_stacks: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_rcb_tcf_vendors: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_rcb_template: Daten: 11.42MB + Index: 0.08MB + Engine InnoDB
e42g_rcb_template_translation: Daten: 0.23MB + Index: 0.05MB + Engine InnoDB
e42g_real_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_revslider_css: Daten: 0.13MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_css_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_revslider_layer_animations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_revslider_navigations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_revslider_navigations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_revslider_sliders: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_sliders_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_slides: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_slides_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_static_slides: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_revslider_static_slides_bkp: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_snippets: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_termmeta: Daten: 0.20MB + Index: 0.22MB + Engine InnoDB
e42g_terms: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
e42g_term_relationships: Daten: 2.27MB + Index: 1.31MB + Engine InnoDB
e42g_term_taxonomy: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
e42g_usermeta: Daten: 0.44MB + Index: 0.25MB + Engine InnoDB
e42g_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_wcrp_rental_products_rentals: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_wcrp_rental_products_rentals_archive: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_wc_admin_notes: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
e42g_wc_admin_note_actions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
e42g_wc_category_lookup: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
e42g_wc_customer_lookup: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
e42g_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wc_orders: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
e42g_wc_orders_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wc_order_addresses: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
e42g_wc_order_bundle_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
e42g_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wc_order_operational_data: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wc_order_product_lookup: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
e42g_wc_order_stats: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
e42g_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wc_product_attributes_lookup: Daten: 1.33MB + Index: 1.34MB + Engine InnoDB
e42g_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_wc_product_meta_lookup: Daten: 0.31MB + Index: 0.52MB + Engine InnoDB
e42g_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woobe_history: Daten: 0.47MB + Index: 0.44MB + Engine InnoDB
e42g_woobe_history_bulk: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_bundled_itemmeta: Daten: 1.39MB + Index: 2.95MB + Engine InnoDB
e42g_woocommerce_bundled_items: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
e42g_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
e42g_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woodmart_wishlists: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_woodmart_wishlist_products: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woot_tables: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_woot_tables_columns: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_woot_tables_meta: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_woot_vocabulary: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
e42g_wpforms_payments: Daten: 0.02MB + Index: 0.14MB + Engine InnoDB
e42g_wpforms_payment_meta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
e42g_wpforms_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
e42g_yoast_indexable: Daten: 5.05MB + Index: 0.95MB + Engine InnoDB
e42g_yoast_indexable_hierarchy: Daten: 1.25MB + Index: 0.56MB + Engine InnoDB
e42g_yoast_migrations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
e42g_yoast_primary_term: Daten: 0.11MB + Index: 0.11MB + Engine InnoDB
e42g_yoast_seo_links: Daten: 1.05MB + Index: 0.50MB + Engine InnoDB

### Post Type Counts ###

attachment: 11558
cms_block: 8
customize_changeset: 46
elementor_library: 2
feedback: 1
mailpoet_page: 1
nav_menu_item: 62
oembed_cache: 3
page: 30
post: 6
product: 2720
rcb-banner-link: 2
rcb-cookie: 5
revision: 4087
shop_coupon: 1
shop_order: 178
shop_order_refund: 2
shop_subscription: 1
woodmart_layout: 13
woodmart_slide: 9
woodmart_woo_fbt: 421
wp_block: 2
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Code Snippets: von Code Snippets Pro – 3.5.0
EAN for WooCommerce: von WPFactory – 4.8.0
Error Log Viewer by BestWebSoft: von BestWebSoft – 1.1.2
Site Kit by Google: von Google – 1.111.0
Jetpack: von Automattic – 12.7
MC4WP: Mailchimp for WordPress: von ibericode – 4.9.9
Real Cookie Banner: von devowl.io – 3.13.1
Safe SVG: von 10up – 2.2.0
SMTP Mailer: von naa986 – 1.1.9
Trusted Shops Easy Integration for WooCommerce: von vendidero – 1.0.8
Way of Music: von Paul Treubrodt – 0.0.1
easyCredit-Ratenkauf für WooCommerce: von NETZKOLLEKTIV – 2.1.4
CTX Feed: von WebAppick – 6.1.4
BEAR – Bulk Editor and Products Manager Professional for WooCommerce: von realmag777 – 2.1.4
Payment Plugins for Stripe WooCommerce: von Payment Plugins
support@paymentplugins.com – 3.3.51

WooCommerce PayPal Payments: von WooCommerce – 2.3.1
WooCommerce Product Bundles: von WooCommerce – 6.22.4
WooCommerce: von Automattic – 8.2.1
Yoast SEO: von Team Yoast – 21.4
WP All Import Pro: von Soflyy – 4.8.2-beta-1.7
WP All Import - WooCommerce Import Add-On Pro: von Soflyy – 4.0.0
WPForms Lite: von WPForms – 1.8.4

### Inactive Plugins (4) ###

Contact Form 7: von Takayuki Miyoshi – 5.8.1
MailPoet: von MailPoet – 4.32.0
TikTok: von TikTok – 1.2.0
WooCommerce Stripe Gateway: von WooCommerce – 7.6.1

### Must Use Plugins (2) ###

IONOS Marketplace: von IONOS – 1.1.5
WordPress automation by Installatron: von  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
demo (demo)
external (external)
grouped (grouped)
rental (rental)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #9610 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Ihr Konto: #9 - /kundenkonto/
Allgemeine Geschäftsbedingungen: #19599 - /agb/

### Theme ###

Name: wayofmusic
Version: (Update auf Version 0 ist verfügbar)
Author URL: 
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: wayofmusic/woocommerce/archive-product.php Version - ist veraltet. Die Hauptversion ist 3.4.0
wayofmusic/woocommerce/cart/cart-totals.php
wayofmusic/woocommerce/cart/cart.php
wayofmusic/woocommerce/checkout/review-order.php
wayofmusic/woocommerce/content-product.php
wayofmusic/woocommerce/emails/email-addresses.php
wayofmusic/woocommerce/emails/email-order-details.php
wayofmusic/woocommerce/loop/add-to-cart.php
wayofmusic/woocommerce/loop/loop-end.php
wayofmusic/woocommerce/loop/loop-start.php

Outdated Templates: ❌
					
					
						Erfahren Sie
wie Sie aktualisieren können

### Product Bundles ###

Database Version: 6.22.4
Loopback Test: ✔
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-18 11:16:50 +02:00
Options: ✔
Notes: 100
Onboarding: completed

### Action Scheduler ###

Abgeschlossen: 11.785
Oldest: 2023-09-17 07:17:03 +0000
Newest: 2023-10-18 06:51:15 +0000

Fehlgeschlagen: 8.083
Oldest: 2023-06-24 14:07:20 +0000
Newest: 2023-10-18 07:05:28 +0000

Ausstehend: 9
Oldest: 2023-10-18 07:07:28 +0000
Newest: 2023-10-24 08:17:49 +0000

### Status report information ###

Generated at: 2023-10-18 09:05:38 +02:00
`

</details>

**Comment by Sirvijver** [comment]
Hello @admin100903 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This is a known situation, and we have a snippet available for you to get this icon added to your checkout option for PayPal:
https://gist.github.com/Sirvijver/8fa5d567951ee8ed6bf6d98fa251b0d1
You can easily add/test this by using a snipped plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/).

If you require additional support, please open a support ticket with our team as explained above.

Kind regards, 
Joost
