### ISSUE TITLE
Impossible to select variant options if Paypal express is enable on single product page

### ISSUE THREAD

**Issue by sergiopatti** [woocommerce/woocommerce-paypal-payments#1784]
### Describe the Bug

Impossible to select variant options if Paypal express is enable on single product page because the site opens a popup with text: "please select some product options before adding this product to your cart"

### To Reproduce

1. Go to single product page
2. Click on Select an option
4. See error popup

### Screenshots
https://pasteboard.co/sIFUaBmnwbRy.png

### Expected Behavior

I want to select all options without problems and after click on paypal button

### Actual Behavior

Impossible to select variant options if Paypal express is enable on single product page

### WordPress Environment ###

WordPress address (URL): https://www.magifitalia.com
Site address (URL): https://www.magifitalia.com
WC Version: 8.2.1
REST API Version: ✔ 8.2.1
WC Blocks Version: ✔ 11.1.2
Action Scheduler Version: ✔ 3.6.3
Log Directory Writable: ✔
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.2.1
WC Database Prefix: mit_
Dimensione totale database: 23.86MB
Dimensione dati database: 18.18MB
Dimensione indice database: 5.68MB
mit_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
mit_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
mit_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_actionscheduler_actions: Dati: 1.52MB + indice: 0.56MB + motore InnoDB
mit_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_actionscheduler_logs: Dati: 1.48MB + indice: 0.36MB + motore InnoDB
mit_cky_banners: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
mit_cky_cookies: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_cky_cookie_categories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
mit_gla_attribute_mapping_rules: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_gla_budget_recommendations: Dati: 0.22MB + indice: 0.14MB + motore InnoDB
mit_gla_merchant_issues: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_gla_shipping_rates: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_gla_shipping_times: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_automations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_automation_runs: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_automation_run_logs: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_automation_run_subjects: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_automation_triggers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_automation_versions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_custom_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_dynamic_segment_filters: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_feature_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_forms: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_log: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_newsletters: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_newsletter_links: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_mailpoet_newsletter_option: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_newsletter_option_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_newsletter_posts: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_newsletter_segment: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_newsletter_templates: Dati: 2.52MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_scheduled_tasks: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_scheduled_task_subscribers: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_segments: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_sending_queues: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_settings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_statistics_bounces: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_mailpoet_statistics_clicks: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_mailpoet_statistics_forms: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_statistics_newsletters: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_statistics_opens: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
mit_mailpoet_statistics_unsubscribes: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_mailpoet_statistics_woocommerce_purchases: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
mit_mailpoet_stats_notifications: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_subscribers: Dati: 0.02MB + indice: 0.16MB + motore InnoDB
mit_mailpoet_subscriber_custom_field: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_subscriber_ips: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_subscriber_segment: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_subscriber_tag: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_mailpoet_tags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_user_agents: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_mailpoet_user_flags: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_options: Dati: 3.20MB + indice: 0.09MB + motore InnoDB
mit_postmeta: Dati: 1.25MB + indice: 0.47MB + motore InnoDB
mit_posts: Dati: 2.20MB + indice: 0.13MB + motore InnoDB
mit_revslider_css: Dati: 0.13MB + indice: 0.02MB + motore InnoDB
mit_revslider_css_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_revslider_layer_animations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_revslider_layer_animations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_revslider_navigations: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_revslider_navigations_bkp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_revslider_sliders: Dati: 0.09MB + indice: 0.02MB + motore InnoDB
mit_revslider_sliders_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_revslider_slides: Dati: 1.22MB + indice: 0.02MB + motore InnoDB
mit_revslider_slides_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_revslider_static_slides: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_revslider_static_slides_bkp: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_trp_gettext_it_it: Dati: 1.52MB + indice: 0.48MB + motore InnoDB
mit_trp_gettext_original_meta: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_trp_gettext_original_strings: Dati: 0.39MB + indice: 0.27MB + motore InnoDB
mit_trp_original_meta: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_trp_original_strings: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_usermeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
mit_wc_admin_note_actions: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
mit_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_orders: Dati: 0.02MB + indice: 0.13MB + motore InnoDB
mit_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
mit_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
mit_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_wc_product_meta_lookup: Dati: 0.05MB + indice: 0.09MB + motore InnoDB
mit_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
mit_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_yith_wcwl: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_yith_wcwl_lists: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_yoast_indexable: Dati: 0.06MB + indice: 0.09MB + motore InnoDB
mit_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
mit_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
mit_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
mit_yoast_seo_links: Dati: 0.06MB + indice: 0.03MB + motore InnoDB
mit_yolo_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

attachment: 278
language_switcher: 2
mailpoet_page: 1
nav_menu_item: 24
page: 19
post: 1
product: 27
product_variation: 91
revision: 128
wpcf7_contact_form: 3
yolo_footer: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-spam: Spam Protection: by Automattic - Squadra antispam – 5.3
Contact Form 7: by Takayuki Miyoshi – 5.8.1
CookieYes | GDPR Cookie Consent: by CookieYes – 3.1.6
Cresta Help Chat: by CrestaProject - Rizzo Andrea – 1.3.1
WPBakery Page Builder: by Michael M - WPBakery.com – 7.0
Maintenance: by WebFactory Ltd – 4.08
Slider Revolution: by ThemePunch – 6.6.12
TranslatePress - Multilingue: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 2.6.4

UpdraftPlus - Backup/Ripristino: by UpdraftPlus.Com
DavidAnderson – 1.23.10

User Role Editor: by Vladimir Garagulya – 4.64
WooCommerce Payments: by Automattic – 6.6.0
WooCommerce PayPal Payments: by WooCommerce – 2.3.1
WooCommerce: by Automattic – 8.2.1
Yoast SEO: by Team Yoast – 21.4
Yolo Sofani Framework: by YoloTheme – 1.7.2
You Save for Woocommerce: by 10Horizons Plugins – 0.5.3

### Inactive Plugins (1) ###

YITH WooCommerce Wishlist: by YITH – 3.26.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #11 - /shop/
Carrello: #12 - /carrello/
Pagamento: #13 - /pagamento/
Il mio account: #14 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Yolo Sofani
Version: 1.7.2
Author URL: http://yolotheme.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: yolo-sofani/woocommerce/archive-product.php
yolo-sofani/woocommerce/cart/cross-sells.php
yolo-sofani/woocommerce/cart/mini-cart.php
yolo-sofani/woocommerce/checkout/form-coupon.php
yolo-sofani/woocommerce/checkout/form-login.php
yolo-sofani/woocommerce/checkout/form-shipping.php
yolo-sofani/woocommerce/content-product.php
yolo-sofani/woocommerce/content-single-product.php
yolo-sofani/woocommerce/global/quantity-input.php
yolo-sofani/woocommerce/loop/add-to-cart.php
yolo-sofani/woocommerce/loop/loop-end.php
yolo-sofani/woocommerce/loop/loop-start.php
yolo-sofani/woocommerce/loop/no-products-found.php
yolo-sofani/woocommerce/loop/pagination.php
yolo-sofani/woocommerce/loop/rating.php
yolo-sofani/woocommerce/loop/sale-flash.php
yolo-sofani/woocommerce/myaccount/form-login.php
yolo-sofani/woocommerce/product-searchform.php
yolo-sofani/woocommerce/single-product/add-to-cart/simple.php
yolo-sofani/woocommerce/single-product/add-to-cart/variable.php
yolo-sofani/woocommerce/single-product/meta.php
yolo-sofani/woocommerce/single-product/product-image.php
yolo-sofani/woocommerce/single-product/rating.php
yolo-sofani/woocommerce/single-product/related.php
yolo-sofani/woocommerce/single-product/review.php
yolo-sofani/woocommerce/single-product/sale-flash.php
yolo-sofani/woocommerce/single-product/short-description.php
yolo-sofani/woocommerce/single-product/tabs/tabs.php
yolo-sofani/woocommerce/single-product/title.php
yolo-sofani/woocommerce/single-product/up-sells.php
yolo-sofani/woocommerce/single-product.php
yolo-sofani/woocommerce/content-product_cat.php

### WooPayments ###

Version: 6.6.0
Connected to WPCOM: Sì
WPCOM Blog ID: 219498588
Account ID: acct_1NQR6zC4xiqcGxOz
Payment Gateway: ❌ Needs setup
Test Mode: Disabilitato
UPE: Disabilitato
WooPay: Disabilitato
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Abilitato (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Abilitato
Public Key Encryption: Disabilitato
Auth and Capture: Abilitato
Documents: Disabilitato
Logging: Disabilitato

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-10-20 09:42:50 +02:00
Options: ✔
Notes: 111
Onboarding: completed

### Action Scheduler ###

Completato: 250
Oldest: 2023-09-19 06:35:28 +0200
Newest: 2023-10-19 15:33:47 +0200

Operazione non riuscita: 1.841
Oldest: 2023-05-27 11:43:54 +0200
Newest: 2023-06-28 11:15:24 +0200

In attesa: 1
Oldest: 2023-10-20 12:07:39 +0200
Newest: 2023-10-20 12:07:39 +0200

### Status report information ###

Generated at: 2023-10-19 16:25:11 +02:00
`

**Comment by SydeKrystian** [comment]
Hello @sergiopatti 

I am not able to diagnose this error on your site because it looks like it is in maintenance mode. 

GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
