### ISSUE TITLE
After paypal payment, not redirect to the order confirmation page

### ISSUE THREAD

**Issue by balrambochliya25** [woocommerce/woocommerce-paypal-payments#1790]
### Describe the Bug
 
After a successful payment, paypal not redirect to the order confirmation page. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @balrambochliya25 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There is much information missing for us to provide a good response to this, but I will try to give you some ideas on how to proceed on this.
The confirmation page should be loaded when the payment_succeeded webhooks are received, so it could be that the webhooks are not received. You can test and correct the webhooks by using the webhook tools (buttons "Simulate" & "Resubscribe) that you can find in the bottom of the tab "Connection" in the settings page of our plugin.

It could also be that another plugin is causing a conflict with our plugin and causing this effect. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you find the cause or resolve the issue, please open a support thread as advised above.

Kind regards, 
Joost
