### ISSUE TITLE
The button for direct card payments only has a single language "Chinese"

### ISSUE THREAD

**Issue by Boyex21** [woocommerce/woocommerce-paypal-payments#1791]
### Describe the Bug
The button for direct card payments only has a single language "Chinese"

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48374028/2e3e2486-5483-466c-b048-65c88d7cdd79)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48374028/5f54236c-66eb-4348-a38e-2de60ab3cbea)

**Comment by Sirvijver** [comment]
Hello @Boyex21 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The language of the PayPal buttons is not regulated by the plugin, but by the PayPal server. The process goes as followed: the plugin gathers details of the end customer (IP, OS, language settings, web browser, etc.) and sends it to the PayPal server. These details are analyzed by PayPal, and then it decides what they believe the end customer should see and send the buttons they want to display to the WooCommerce site. Our plugin only receives these elements and displays what it is being given.
The buttons are reviewed per case and should only rely on the end customer's situation. The only options available are the ones that you can find in the settings page, but for this "Standard Card Processing" payment option, there are no settings to adjust them (there are some for the PayPal and Advanced Card Processing option).

There is not much we can do for this, but if you have any additional questions, please raise a support request with us as explained above.

Kind regards, 
Joost
