### ISSUE TITLE
Required fields are not validated before payment starts

### ISSUE THREAD

**Issue by francoisreme** [woocommerce/woocommerce-paypal-payments#1792]
### Describe the Bug

On the checkout page, I can click the "PLACE ORDER" button that initiate de payment without validating every element of the checkout form.

### Screenshots

![capture](https://github.com/woocommerce/woocommerce-paypal-payments/assets/3638209/dfa9cb2e-d098-472a-8c06-195d39561801)

### Expected Behavior

I expect a correct form validation before payment.

### Actual Behavior

Now the payment seems to start, but we never move to the order confirmation and the payment does not work.

### Environment

- WordPress 6.3.2
- Woocommerce Version 8.2.1
- Paypal Payments 2.3.1

**Comment by SydeKrystian** [comment]
Hello @francoisreme 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
