### ISSUE TITLE
"Plan name" not saved using Woocommerce Subscription with WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by ant0nioli** [woocommerce/woocommerce-paypal-payments#1801]
Hi, I'm following [this guide](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews#how-to-test-paypal-subscriptions-with-paypal-payments) to use Paypal Subscription without Vault, because the account I'm using in this setup in not Reference Transactions enabled:

It should work, because the documentation states:

> As an alternative to Vaulting, [PayPal Subscriptions](https://www.paypal.com/webapps/mpp/subscription-payments) can be used to enable PayPal renewals without requiring a business account or [Vaulting approval (Reference Transactions)](https://woocommerce.com/document/woocommerce-paypal-payments/#get-vaulting-approval).

The problem is:

If I enable this option as stated into the documentation

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1677823/a6fc1171-5984-4c18-a320-7a86105d62df)

And in a Simple Subscription Product I

- check the "Connect Product to Paypal Subscriptions Plan" checkbox
- add a name for the plan
- and save

The plan name does not appear to be stored in Woocommerce and/or in Paypal Subscription panel in paypal.com

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1677823/846bd9ef-0a2f-45bc-91a0-7b44ada78086)

The Woocommerce's Product field remain empty after the page reload after the Product's creation/update.

I'm troubleshooting with this setup:

|   | version |
| - | - |
| Wordpress | 6.3.2 |
| Woocommerce | 8.2.1 |
| WooCommerce PayPal Payments | 2.3.1 |
| WooCommerce PayPal Payments - Enable PayPal Subscriptions | 1.0.0 |

Anyone who could help?

**Comment by Sirvijver** [comment]
Hello @ant0nioli 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The field "Plan Name" is a field that is only seen in the product page and can be whatever you want to make it. When the subscription is sold, PayPal will create a subscription reference that you will see in the order.

I would guess that you probably forgot to set a price for the product and that this is causing an issue.
The Plan name field must be populated with whatever you want the subscription plan at PayPal to be called.
PayPal Subscriptions consist of two things:
- a plan
- a product
In WooCommerce both are one thing but in PayPal we have to create two. The PayPal product will have the same name as the WooCommerce product and the plan name can be specified.

The subscription product must have a price, this looks to me the only place where this can cause any issue. Please take a look [here](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-subscriptions) for further details on this new feature.

If you require any further support, please open a support request as described above.

Kind regards, 
Joost
