### ISSUE TITLE
paypal dont work in woocomerce

### ISSUE THREAD

**Issue by migueadrenalina** [woocommerce/woocommerce-paypal-payments#1806]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @migueadrenalina 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any error, logs or even the system report, so we can't really tell you anything at this moment. We suggest you create the support request, and we will try to help you via that engagement. We will close this thread for now.

Kind regards, 
Joost
