### ISSUE TITLE
 save button on settings on paypal woocomerce

### ISSUE THREAD

**Issue by SuzannahLeighDesign** [woocommerce/woocommerce-paypal-payments#1817]
### Describe the Bug

There isnt a save button under the pay pal options in WooCommerce settings where is=t should be at the bottom left. Is there another way to save?

**Comment by InpsydeNiklas** [comment]
Hi @SuzannahLeighDesign, after your account was connected, the "Save changes" button should be displayed on the bottom left of the settings pages as usual:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/db3c11c0-54a1-44a5-8209-6ddd719461ca)
You can find more setup instructions in the [onboarding guide here](https://woo.com/document/woocommerce-paypal-payments/#connect-paypal-account) or [troubleshooting tips here](https://woo.com/document/woocommerce-paypal-payments/#troubleshooting). 
If you need additional assistance, please get in touch with the support team directly from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!

**Comment by SuzannahLeighDesign** [comment]
Hello thanks for your email

It isn’t showing on both my sites I am working on, see screen grab below:

Best regards,

Suzannah Leigh

Graphic Designer

 <https://suzannahleighdesign.com/> 
Suzannah Leigh Design Ltd
+44 (0)7747 123 342 |  ***@***.***> ***@***.*** |  <http://www.suzannahleighdesign.com/> suzannahleighdesign.com
 <https://www.instagram.com/suzannahleighdesign/>

**Comment by SuzannahLeighDesign** [comment]
Hello would it help if I created a temporary login in so you can go in yourself and see what the issue is?
Best regards,
Suzannah Leigh

**Comment by InpsydeNiklas** [comment]
Hi Suzannah, for detailed assistance, we kindly ask that you reach out directly to our support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Our support team is available to assist you with your concerns because we cannot help with support questions here on GitHub. Thank you for your understanding!
