### ISSUE TITLE
CRITICAL Uncaught Error in Woocommerce

### ISSUE THREAD

**Issue by ATJohn316** [woocommerce/woocommerce-paypal-payments#1819]
When viewing Woo store, everything seems normal except when viewing product categories; the view becomes narrowed and there is a "critical error" message for all products:

CRITICAL Uncaught Error: Class 'WooCommerce\PayPalCommerce\ApiClient\Entity\Token' not found in /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Authentication/PayPalBearer.php:105
Stack trace:
#0 /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/TrackingAvailabilityTrait.php(28): WooCommerce\PayPalCommerce\ApiClient\Authentication\PayPalBearer->bearer()
#1 /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/Assets/CompatAssets.php(87): WooCommerce\PayPalCommerce\Compat\Assets\CompatAssets->is_tracking_enabled()
#2 /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Compat\Assets\CompatAssets->register()
#3 /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 in /home/650490.cloudwaysapps.com/tjragtvzue/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Authentication/PayPalBearer.php on line 105

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @ATJohn316 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you described here seems to be a plugin conflict, so initially we would advise you to do conflict testing to see if you can isolate the cause of this problem. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If this does not help you forward, please open a support thread as advised above.

Kind regards, 
Joost
