### ISSUE TITLE
Impossible to add CB details on Firefox

### ISSUE THREAD

**Issue by Rit92** [woocommerce/woocommerce-paypal-payments#1820]
### Describe the Bug

Impossible enter numbers 

### To Reproduce

1. Go to (https://noil-motors.com/boutique/)
2. Click on any product to add the cart and try to pay.
3. choose CB
4. See error --> You can't enter your cb details

### Expected Behavior

able to enter my CB details to pay

### Actual Behavior

I can't put my CB details, so i can't pay

### Environment

 - WordPress Version 6.3.2
 - WooCommerce Version 8.2.1
 - Plugin Version 2.4.0
 - Browser : Firefox
 - Any other plugins installed : Version 3.0.4 | with [Fluid Checkout](https://fluidcheckout.com/)

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Rit92 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
