### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by abdul-musabbir** [woocommerce/woocommerce-paypal-payments#1833]
![Screenshot 2023-11-10 020448](https://github.com/woocommerce/woocommerce-paypal-payments/assets/126709118/a000cbf2-4ae8-4cf2-96a8-5010d7cea727)

why showing this message into top header also in pages?

**Comment by InpsydeNiklas** [comment]
Hello @abdul-musabbir, your screenshot does not depict an error message, but the Pay Later messaging: https://woo.com/document/woocommerce-paypal-payments/#pay-later-messaging-config
When setting up a new store from a supported region, the messaging will automatically appear in the following locations:

- Single Product
- Cart
- Checkout
- Shop (includes Search & Product Categories pages)
- Home
 
These messages can be disabled from the Pay Later tab in the PayPal Payments settings.
If you need any guidance with the plugin setup, we kindly ask you to contact our [support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
