### ISSUE TITLE
can not connect paypal

### ISSUE THREAD

**Issue by yuxinhe88** [woocommerce/woocommerce-paypal-payments#1853]
### To Reproduce

1. Go to 'woocommerce payments'
2. Click on 'Activate paypal'
3. Activate the window to open in a new tab of the browser instead of popping up in the current tab
4. After logging in to PayPal, the account is still not connected.  Some stores cannot display the preview of the PayPal button style after connecting.  There are two main issues: one is that the account cannot be connected, and the other is that some can connect but cannot display the button.
### Environment

 - WordPress Version   There are several versions, but currently I am using is 6.4.1
 - WooCommerce Version  8.3.0
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @yuxinhe88 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You mentioned 'woocommerce payments', which is actually another plugin than the plugin this GitHub page is for. If you are trying to onboard our PayPal Payments plugin with your PayPal account, we would advise you to try this again, but while disabling all other plugins (except WooCommerce and PayPal Payments) and activating the [Default storefront theme](https://wordpress.org/themes/storefront/). 
If that does not show any improvements, you might want to try onboarding the plugin with a [sandbox account](https://developer.paypal.com/). If that does work, you might have an issue with your account, and you should ask [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to review your account.

If none of this helped you, please open a support ticket via the link provided above, so our support team can take another look. We will now close this GitHub thread.

Kind regards, 
Joost
