### ISSUE TITLE
Credit card icons are added in an inconsistent way that doesn't leverage the WooCommerce gateway abstraction

### ISSUE THREAD

**Issue by clifgriffin** [woocommerce/woocommerce-paypal-payments#186]
### Describe the bug
`\WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway` is using `get_title()` to display the credit card icons instead of using `get_icon()` from `WC_Payment_Gateway`, which it extends. 

This means that the icons are not available in any other context than the `update_order_review` AJAX call. 

I think all gateways with icons should implement `get_icon()` for this functionality for consistency and maximum extensibility.

**Comment by InpsydeNiklas** [comment]
Hi @clifgriffin,
Thanks for the input, we appreciate your feedback.  I informed our developers about it.
For one of the next updates, we are working on some further improvements for the icons and will take this into consideration. 
Kind regards,
Niklas
