### ISSUE TITLE
PayPal Tracking Info does not sync

### ISSUE THREAD

**Issue by peterpenguw** [woocommerce/woocommerce-paypal-payments#1862]
### Describe the Bug

PayPal Tracking Info does not show in PayPal as before.

As of Oct 2023, this plugin is no longer updating PayPal with such tracking # and thus our income is frozen in paypal.

### To Reproduce

1. Go to Lashgod.ca
2. Click on Checkout with PayPal
3. No tracking info in PayPal transaction

### Screenshots
screenshot of NO TRACKING info in PayPal screen
![no tracking info](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4958704/d081c8d3-0b0f-414a-9f3c-878a79078378)

screenshot of YES BUT WE DID PROVIDE TRACKING numerous times.
![tracking info provided](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4958704/93a41565-c6d2-4b02-9ffa-c13f5be4ae4f)

**This is a repeating and constant error that never corrects itself.**

### Expected Behavior

**As per plugin advertisement:**
[Package Tracking](https://woo.com/document/woocommerce-paypal-payments/#package-tracking)
Elevate Your Post-Purchase Experience (US Merchants/Buyers)

Tailored specifically for the US market, the latest WooCommerce PayPal Payments version offers an improved post-purchase experience for US merchants and buyers. Benefit from shorter hold times, Seller Protection eligibility, and other improvements to the existing package tracking system to facilitate smoother transactions and better buyer-seller relations.
Automated Order and Shipment Synchronization

Streamline the process of sharing product details and shipping information between WooCommerce and PayPal for a smoother post-purchase experience. PayPal automates the synchronization of package tracking data, reducing manual work associated with payment holds, disputes, chargebacks, and customer support.

### Actual Behavior

**Reality:**
no "tracking" info field is provided in WooCommerce orders to fill.  Our shipping vendor UPS sends tracking # via WooCommerce notes and it used to work.

### Environment

`
### WordPress Environment ###

WordPress address (URL): https://lashgod.ca
Site address (URL): https://lashgod.ca
WC Version: 8.2.2
REST API Version: ✔ 8.2.2
WC Blocks Version: ✔ 11.1.3
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 6.2.3 - There is a newer version of WordPress available (6.4.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.0.28
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.5-MariaDB-1:10.11.5+maria~ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.2.1
WC Database Prefix: wp_
Total Database Size: 2281.40MB
Database Data Size: 1899.34MB
Database Index Size: 382.06MB
wp_woocommerce_sessions: Data: 53.08MB + Index: 3.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 11.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 70.61MB + Index: 58.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 18.06MB + Index: 15.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 7.02MB + Index: 8.03MB + Engine InnoDB
wp_aryo_activity_log: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
wp_chaty_contact_form_leads: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_chaty_widget_analysis: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_comments: Data: 25.56MB + Index: 16.09MB + Engine InnoDB
wp_ddp_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_products_sync_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_call: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ee_product_sync_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_eum_logs: Data: 13.52MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 2.52MB + Index: 2.41MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.30MB + Index: 0.42MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.36MB + Index: 0.22MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hfcm_scripts: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_hustle_entries_meta: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hustle_modules_meta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_hustle_tracking: Data: 1.52MB + Index: 1.11MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_options: Data: 31.14MB + Index: 3.03MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 360.63MB + Index: 199.30MB + Engine InnoDB
wp_posts: Data: 95.14MB + Index: 14.70MB + Engine InnoDB
wp_post_views: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
wp_po_plugins: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.28MB + Index: 0.09MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 2.20MB + Index: 0.33MB + Engine InnoDB
wp_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 1.36MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_usermeta: Data: 20.55MB + Index: 18.06MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 3.44MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 4.52MB + Index: 4.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.34MB + Index: 0.38MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 13.52MB + Index: 13.06MB + Engine InnoDB
wp_wc_order_stats: Data: 4.52MB + Index: 4.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 1.30MB + Index: 2.66MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.44MB + Index: 1.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woodmart_wishlists: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 1144.58MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 6375
cms_block: 25
custom_css: 5
customize_changeset: 4
cwginstocknotifier: 1741
elementor_library: 7
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 8
et_template: 11
et_theme_builder: 1
gift_card: 75
gp_elements: 2
mc4wp-form: 1
metform-entry: 1
metform-form: 2
nav_menu_item: 252
oembed_cache: 3
page: 49
portfolio: 9
post: 36
product: 1383
product_variation: 3375
revision: 3371
shop_coupon: 4200
shop_order: 48767
shop_order_refund: 43
woodmart_sidebar: 1
woodmart_size_guide: 1
woodmart_slide: 3
wp_global_styles: 3
wp_show_posts: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Admin CSS MU: by Arun Basil Lal – 2.10
Admin Menu Editor: by Janis Elsts – 1.12
Afterpay Gateway for WooCommerce: by Afterpay – 3.7.1
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.26.1
Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Activity Log: by Activity Log Team – 2.9.0
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 5.0.1
Chaty Pro: by Premio – 3.1.6
Classic Editor: by WordPress Contributors – 1.6.3
Disable Admin Notices Individually: by Creative Motion  – 1.3.3
Disable Cart Fragments: by Optimocha – 2.3
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.5
Easy SVG Support: by Benjamin Zekavica – 3.5
Elementor Pro: by Elementor.com – 3.17.1
Elementor: by Elementor.com – 3.17.3
Facebook for WooCommerce: by Facebook – 3.1.4
FileBird Lite: by Ninja Team – 5.5.5
Flexible Checkout Fields PRO: by WP Desk – 3.5.11
Flexible Checkout Fields: by WP Desk – 3.5.18
Forget About Shortcode Buttons: by Designs & Code – 2.1.3
GTM Kit: by TLA Media – 1.16.2
Header Footer Code Manager: by 99robots – 1.1.36
Heartbeat Control by WP Rocket: by WP Rocket – 2.0.1
Imsanity: by Exactly WWW – 2.8.3
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.12
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.10
PixelYourSite: by PixelYourSite – 9.4.7.1
PNG to JPG: by KubiQ – 4.3
Post Views Counter: by dFactory – 1.4.3
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: by Retainful – 2.6.25
Rank Math SEO: by Rank Math – 1.0.206
Sezzle WooCommerce Payment: by Sezzle – 5.0.5
Easy Updates Manager: by Easy Updates Manager Team – 9.0.17
Storemapper for WordPress: by Storemapper – 1.0.0
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.4.7
CTX Feed Pro: by WebAppick Author – 6.6.21
Advanced Order Export For WooCommerce: by AlgolPlus – 3.4.3
WooCommerce Order Navigation: by woosmartcod.com – 1.1
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.52

Variation Swatches for WooCommerce: by Emran Ahmed – 2.0.29
WooCommerce Bulk Variations: by Barn2 Plugins – 2.1.5
BLAZING Email Transfer Payment Gateway: by Massoud Shakeri
BlazingSpider – 2.6.0

WooCommerce Google Analytics Integration: by WooCommerce – 1.8.9
WooCommerce PayPal Payments: by WooCommerce – 2.4.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.7.2
WooCommerce: by Automattic – 8.2.2
Woodmart Core: by  – 1.0.39
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Sitemap Page: by Tony Archambeau – 1.9.2
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.9.9

YITH WooCommerce Gift Cards: by YITH – 4.6.0

### Inactive Plugins (8) ###

Acowebs Woocommerce Dynamic Pricing: by Acowebs – 4.5.1
CAPTCHA 4WP (Premium): by Melapress – 7.3.1
Checkout Field Editor and Manager for WooCommerce: by Acowebs – 2.2.16
Hide featured image on all single page/post: by TylerTork – 1.0
Payment Plugins for PayPal WooCommerce: by Payment Plugins
support@paymentplugins.com – 1.0.40

Redirect 404 Error Page to Homepage: by ProThoughts – 1.1
Redirection: by John Godley – 5.3.10
WP Show Posts: by Tom Usborne – 1.1.4

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 3.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #47 - /shop/
Cart: #390 - /shopping-cart/
Checkout: #394 - /checkout/
My account: #395 - /my-account/
Terms and conditions: #42505 - /shipping-returns-refunds-policy/

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 7.3.3
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/checkout/thankyou.php
woodmart/woocommerce/content-product-cat.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-attributes.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/description.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product-reviews.php
woodmart/woocommerce/single-product.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-23 22:31:30 +00:00
Options: ✔
Notes: 55
Onboarding: completed

### Action Scheduler ###

Complete: 24,840
Oldest: 2023-10-23 19:45:39 +0000
Newest: 2023-11-23 19:44:31 +0000

Failed: 17
Oldest: 2022-09-29 23:45:15 +0000
Newest: 2023-11-23 19:33:57 +0000

Pending: 5
Oldest: 2023-11-23 19:47:22 +0000
Newest: 2023-11-27 06:48:39 +0000

### Status report information ###

Generated at: 2023-11-23 19:45:29 +00:00
`

### Additional Details

can contact me at   Peter@Nordic99.com

<details><summary>System status</summary>

  ```

  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @peterpenguw, I'm not seeing any [supported package tracking extension](https://woo.com/document/woocommerce-paypal-payments/#package-tracking-compatibility) in your provided system report. How the tracking data is saved in your WooCommerce orders is not clear. Can you give more details on how you receive this data?
PayPal Payments can only automatically send the tracking data to PayPal when using a supported package tracking extension.
If you're not using a supported extension, you can [manually submit the package tracking data to PayPal with the PayPal Package Tracking metabox](https://woo.com/document/woocommerce-paypal-payments/#how-to-use-package-tracking-features) in your WooCommerce orders.

**Comment by Sirvijver** [comment]
Hello @peterpenguw 

Since you reached out to open GitHub forum with a support request, we would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you require more guidance. We will close this support request for now.

Kind regards, 
Joost
