### ISSUE TITLE
PayPal Payments plugin not displaying credit card option button

### ISSUE THREAD

**Issue by robo26** [woocommerce/woocommerce-paypal-payments#1863]
### Describe the Bug

The credit card button fails to display and when checking the backend the PayPal plugin responds with a 504 timeout error, this happens intermittently on trojan-battery.co.uk. I have checked for server issues and have checked all file permissions are correct.

### To Reproduce

Add an item to the cart, and click to proceed to checkout, at the bottom you will only see the PayPal option button rather than both the PayPal and Credit Card option buttons.

### Expected Behavior

I would expect to be able to choose the credit card option button and when I click it the fields to enter credit card details would slide down to display.

### Actual Behavior

The credit card option button does not always display.

### Environment

 - WordPress Version: 6.41
 - WooCommerce Version: 8.31
 - WooCommerce Payments Plugin Version: 2.41
 - Browser [e.g. Chrome, Safari] and Version: Brave, Edge, Opera and Chome all to latest versions
 - Any other plugins installed: I disabled all but the WooCommerce and WooCommerce Payments plugins to test and it made no difference, I also set the theme to the 2024 WordPress theme to test.

### Additional Details

 Attached is the error log
[trojan-paypal-token-error.txt](https://github.com/woocommerce/woocommerce-paypal-payments/files/13458776/trojan-paypal-token-error.txt)

</details>

**Comment by InpsydeNiklas** [comment]
Hi @robo26, from the provided log, it looks like PayPal blocked your account for about an hour for too many API requests. It's not clear what caused the requests for PayPal to block you though, so you may want to additionally reach out to the [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) with your log file to understand why PayPal temporarily blocked your account.
Right now, the PayPal and Advanced Card Processing options appear as expected on your site.
That being said, the plugin settings pages currently may be slower than usual when the PayPal account was blocked which in some cases could result in a 504 timeout. This timeout normally should only affects the Connection tab in the PayPal Payments settings pages though.

**Comment by robo26** [comment]
That's great thank you, I will get onto PayPal with the information you provided. Much appreciated
Best Regards Jon

**Comment by InpsydeNiklas** [comment]
If this intermittent connection problem persists for you or the PayPal MTS can tell you what kind of API request caused the temporary blockage, I recommend also contacting our PayPal Payments plugin support team for additional guidance: https://woo.com/document/woocommerce-paypal-payments/#get-help
We use GitHub primarily for the plugin development, so I will close this issue for now. But if you need further support, please don't hesitate to contact the team using the link above. Thank you!

**Comment by robo26** [comment]
Thanks again, Niklas I appreciate your supportBest RegardsJonJonathan RobertsCEO, Esthetig LtdPhone: 01492 580572 Mobile: ***@***.***: www.esthetig.comOur other websitesWeb Design: www.madebyewd.comWeb Hosting: www.gbhosting.co.ukComputer Repair: www.nwpcr.co.ukIMPORTANT The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.This email is governed by our email policy. You can view this policy at https://esthetig.com/terms-conditions/. Together will all of our policies. All work carried out is subject to these policies. Please read the relevant policies.Esthetig Ltd, Registered in England and Wales. Registration Number 06112562, Registered Office Bethel 26 Tan-y-Fron Deganwy Conwy LL31 9YN.On 24 Nov 2023 18:00, Niklas Gutberlet ***@***.***> wrote:
If this intermittent connection problem persists for you or the PayPal MTS can tell you what kind of API request caused the temporary blockage, I recommend also contacting our PayPal Payments plugin support team for additional guidance: https://woo.com/document/woocommerce-paypal-payments/#get-help
We use GitHub primarily for the plugin development, so I will close this issue for now. But if you need further support, please don't hesitate to contact the team using the link above. Thank you!
