### ISSUE TITLE
Warning: Undefined property: WooCommerce::$payment_gateways (2368)

### ISSUE THREAD

**Issue by PhilDuValais** [woocommerce/woocommerce-paypal-payments#1866]
### Describe the Bug
Warning: Undefined property: WooCommerce::$payment_gateways in ...
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Checkout/DisableGateways.php on line 118

### To Reproduce

Just activate these version of WooCommerce and the error occurs, as soon as the WooCommerce PayPal Payments plugin is enabled as follow:
Standard Paiements -> Enabled

DISABLING THIS OPTION, no error is diaplayed (but the paypal gateway is off).

### Actual Behavior

Warning: Undefined property: WooCommerce::$payment_gateways in ...
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Checkout/DisableGateways.php on line 118

### Environment

 - WordPress Version 6.4.1
 - WooCommerce Version 8.3.1
 - Plugin Version WooCommerce PayPal Payments 2.4.1
 - Firefox 120, Chrome 119, Safari 17.1
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by hanneskannes1988** [comment]
Any update on this issue?

**Comment by PhilDuValais** [comment]
Hello,

still the same problem on all our websites with your updated plugin.
WooCommerce Multilingual & Multicurrency 5.3.2

Warning: Undefined property: WooCommerce::$payment_gateways in /home/clients/18a3e26666cfbf23e8732e4990151eba/sites/aveni.shop/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Checkout/DisableGateways.php on line 118

WordPress 6.4.1
WooCommerce 8.3.1
WooCommerce PayPal Payments 2.4.3

We only can use your Plugin WooCommerce Multilingual & Multicurrency 5.2.1 that is running without problem

Regards
Phil

**Comment by hanneskannes1988** [comment]
> Hello, still the same problem on all our websites with your updated plugin. WooCommerce Multilingual & Multicurrency 5.3.2 Warning: Undefined property: WooCommerce::$payment_gateways in /home/clients/18a3e26666cfbf23e8732e4990151eba/sites/aveni.shop/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Checkout/DisableGateways.php on line 118 WordPress 6.4.1 WooCommerce 8.3.1 WooCommerce PayPal Payments 2.4.3 We only can use your Plugin WooCommerce Multilingual & Multicurrency 5.2.1 that is running without problem Regards Phil

Thanks for your reply!
I  didn't know that this error was related to WCML but I just downgraded my WCML veriosn to 5.2.1 and can also say, that the error has gone.
Did you already reported this bug to WPML?

Kind regards

**Comment by PhilDuValais** [comment]
Hello,

Currently I’ve not found where to report this bug to WPML.

Regards
Phil

**Comment by hanneskannes1988** [comment]
Hi Phil,

I've contacted WPML and they already know about this issue. It should be resolved in the next update. Till then, you can find a workaround here: https://wpml.org/errata/woocommerce-payment-details-are-displayed-twice-on-the-order-confirmation-page-e-mail/

Regards

**Comment by PhilDuValais** [comment]
Hi,

Thanks a lot for your answer.

Regards
Phil

**Comment by InpsydeNiklas** [comment]
Thanks for sharing the details. As this seemingly will be addressed in a future WooCommerce Multilingual & Multicurrency plugin update without the need for any changes on the PayPal Payments side, I will close this issue.
If anything remains unclear, I recommend contacting our [support team directly from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
