### ISSUE TITLE
Check out error

### ISSUE THREAD

**Issue by nguyen083** [woocommerce/woocommerce-paypal-payments#1867]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @nguyen083 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any details on the error you encountered on the checkout, so please add the exact error and the system report to the support thread we advised you to open with us. I will mark this thread as resolved.

Kind regards, 
Joost
