### ISSUE TITLE
PayPal Button "Jetzt bezahlen" not visible

### ISSUE THREAD

**Issue by lokacoding** [woocommerce/woocommerce-paypal-payments#1869]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/119011988/6ecf3ca3-6df1-4378-b2db-85a2f431e119)

### Expected Behavior

"Jetzt Bezahlen" (Pay) Button should be there to finish order..

### Actual Behavior
"Jetzt Bezahlen" (Pay) Button is missing. Only in Paypal. PayOne Plugin (other payment method) works.

### Environment

 - WordPress Version 6.4.1
 - WooCommerce Version Testesd with 7.5.1 and updated to 8.3.1 (on both now working)
 - Plugin Version 2.4.1
 - Browser [e.g. Chrome, Safari] and Version Chrome All known Browsers (no Browser Issue)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

`
### WordPress Environment ###

WordPress address (URL): ##I could not share it.
Site address (URL): ##I could not share it.
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: ZX8IgXTz_
Datenbank-Gesamtgröße: 240.84MB
Datenbank-Datengröße: 121.05MB
Datenbank-Indexgröße: 119.79MB
ZX8IgXTz_woocommerce_sessions: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
ZX8IgXTz_woocommerce_order_items: Daten: 0.47MB + Index: 0.17MB + Engine InnoDB
ZX8IgXTz_woocommerce_order_itemmeta: Daten: 6.52MB + Index: 5.97MB + Engine InnoDB
ZX8IgXTz_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
ZX8IgXTz_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_actionscheduler_actions: Daten: 1.02MB + Index: 0.11MB + Engine InnoDB
ZX8IgXTz_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_actionscheduler_logs: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_cmplz_cookiebanners: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_cmplz_cookies: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_cmplz_services: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_comments: Daten: 2.52MB + Index: 1.45MB + Engine InnoDB
ZX8IgXTz_fooevents_check_in: Daten: 0.50MB + Index: 0.22MB + Engine InnoDB
ZX8IgXTz_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_loka_analyse_jahr: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_loka_analyse_kennzahlen: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_loka_analyse_monat: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_loka_analyse_topartikel: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_loka_buchungstage: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_loka_ticketsettings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_loka_timeslots: Daten: 1.50MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_access: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_01: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_02: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_03: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_04: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_05: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_06: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_07: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_08: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_09: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_10: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_11: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2023_12: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_blob_2024_01: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_invalidations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2022_10: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2022_11: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2022_12: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_01: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_02: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_03: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_04: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_05: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_06: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_07: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_08: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_09: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_10: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_11: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2023_12: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_archive_numeric_2024_01: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_brute_force_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_changes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_custom_dimensions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_goal: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_locks: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_logger_message: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_log_action: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_log_conversion: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_log_conversion_item: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_log_link_visit_action: Daten: 0.36MB + Index: 0.25MB + Engine InnoDB
ZX8IgXTz_matomo_log_profiling: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_log_visit: Daten: 0.30MB + Index: 0.19MB + Engine InnoDB
ZX8IgXTz_matomo_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_plugin_setting: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_privacy_logdata_anonymizations: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_report: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_report_subscriptions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_segment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_sequence: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_session: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_site: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_site_setting: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_site_url: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_container: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_container_release: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_container_version: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_tag: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_trigger: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_tagmanager_variable: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_tracking_failure: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_twofactor_recovery_code: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_user: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_matomo_user_dashboard: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_user_language: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_matomo_user_token_auth: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_options: Daten: 3.03MB + Index: 0.17MB + Engine InnoDB
ZX8IgXTz_payone_api_log: Daten: 1.52MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_payone_transaction_log: Daten: 1.52MB + Index: 0.06MB + Engine InnoDB
ZX8IgXTz_pmxe_exports: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_pmxe_google_cats: Daten: 0.39MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_pmxe_posts: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_pmxe_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_postmeta: Daten: 50.25MB + Index: 31.63MB + Engine InnoDB
ZX8IgXTz_posts: Daten: 12.42MB + Index: 3.67MB + Engine InnoDB
ZX8IgXTz_snippets: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_statistics_exclusions: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_statistics_historical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
ZX8IgXTz_statistics_pages: Daten: 3.52MB + Index: 16.31MB + Engine InnoDB
ZX8IgXTz_statistics_search: Daten: 3.52MB + Index: 4.55MB + Engine InnoDB
ZX8IgXTz_statistics_useronline: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_statistics_visit: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_statistics_visitor: Daten: 17.55MB + Index: 41.19MB + Engine InnoDB
ZX8IgXTz_statistics_visitor_relationships: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_storeabill_documentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
ZX8IgXTz_storeabill_document_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
ZX8IgXTz_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_usermeta: Daten: 2.36MB + Index: 3.03MB + Engine InnoDB
ZX8IgXTz_users: Daten: 0.16MB + Index: 0.14MB + Engine InnoDB
ZX8IgXTz_wcpdf_credit_note_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wcpdf_invoice_number: Daten: 0.09MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wcpdf_invoice_number_2022: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wcpdf_packing_slip_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wc_customer_lookup: Daten: 0.27MB + Index: 0.22MB + Engine InnoDB
ZX8IgXTz_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_wc_order_product_lookup: Daten: 0.48MB + Index: 0.47MB + Engine InnoDB
ZX8IgXTz_wc_order_stats: Daten: 0.44MB + Index: 0.33MB + Engine InnoDB
ZX8IgXTz_wc_order_tax_lookup: Daten: 0.22MB + Index: 0.20MB + Engine InnoDB
ZX8IgXTz_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
ZX8IgXTz_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_wdr_order_discounts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wdr_order_item_discounts: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
ZX8IgXTz_wdr_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipmentmeta: Daten: 3.52MB + Index: 3.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipments: Daten: 0.47MB + Index: 0.23MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipment_itemmeta: Daten: 2.52MB + Index: 3.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipment_items: Daten: 0.34MB + Index: 0.41MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
ZX8IgXTz_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
ZX8IgXTz_wow_coder: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wpforms_tasks_meta: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wpmailsmtp_debug_events: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
ZX8IgXTz_wt_sc_coupon_lookup: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 166
blocks: 5
custom_css: 1
document_template: 5
event_magic_tickets: 8278
nav_menu_item: 15
page: 31
post: 2
product: 11
revision: 859
shop_coupon: 498
shop_order: 2924
shop_order_refund: 49
user_request: 1
ux_template: 2
wbcr-snippets: 11
wp_global_styles: 1
wp_navigation: 1
wpcf7_contact_form: 2
wpdesk-coupons: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

AJAX - In den Warenkorb + X in 1 Produkte: von Marius Schulte – 1.0.0
BackWPup: von WP MEDIA SAS – 4.0.2
PAYONE Payment for WooCommerce: von PAYONE GmbH – 2.6.0
Complianz | GDPR/CCPA Cookie Consent: von Really Simple Plugins – 6.5.5
Contact Form 7: von Takayuki Miyoshi – 5.8.3
Date Picker Events: von Marius Schulte – 1.0.1
Flexible PDF Gutscheine für WooCommerce: von WP Desk – 1.9.0
FooEvents for WooCommerce: von FooEvents – 1.18.6
FooEvents Express Check-in: von FooEvents – 1.7.3
FooEvents Multi-Day: von FooEvents – 1.6.8
FooEvents PDF Tickets: von FooEvents – 1.9.22
Woody code snippets (PHP snippets | Insert PHP): von Creative Motion
Will Bontrager Software
LLC  – 2.4.10

Custom Login Page Customizer: von Hardeep Asrani – 2.3.1
Loka Shops Dashboard: von Marius Schulte – 1.0.2
Members: von MemberPress – 3.2.8
Premmerce User Roles: von Premmerce – 1.0.13
Woo Discount Rules: von Flycart – 2.6.2
Germanized für WooCommerce Pro: von vendidero – 3.7.3
Germanized für WooCommerce: von vendidero – 3.14.1
WooCommerce PayPal Payments: von WooCommerce – 2.4.1
PDF Invoices & Packing Slips for WooCommerce: von WP Overnight – 3.7.2
PDF Invoices & Packing Slips for WooCommerce - Professional: von WP Overnight – 2.15.1
WooCommerce Produkt-Add-ons: von WooCommerce – 4.1.0
WooCommerce Smart Gutscheine: von StoreApps – 4.33.1
WooCommerce: von Automattic – 8.3.1
WP Coder: von WPCoder – 3.2
WP Mail SMTP: von WP Mail SMTP – 3.10.0
Connect Matomo: von André Bräkling – 1.0.30
WP Statistics: von VeronaLabs – 14.2
WP Super Cache: von Automattic – 1.11.0
WPS Hide Login: von WPServeur
NicolasKulka
wpformation – 1.9.9

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #24 - /shop/
Warenkorb: #25 - /warenkorb/
Kasse: #26 - /kasse/
Mein Konto: #27 - /mein-konto/
Allgemeine Geschäftsbedingungen: #120 - /agb/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.18.1
Parent Theme Author URL: https://uxthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome-child/woocommerce/cart/cart.php
flatsome/woocommerce/cart/mini-cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/order-received.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-11-27 13:32:41 +01:00
Options: ✔
Notes: 27
Onboarding: skipped

### Action Scheduler ###

Abgeschlossen: 245
Oldest: 2023-10-27 17:18:46 +0200
Newest: 2023-11-27 12:58:28 +0100

Fehlgeschlagen: 1
Oldest: 2022-10-31 18:18:51 +0100
Newest: 2022-10-31 18:18:51 +0100

Ausstehend: 9
Oldest: 2023-11-27 13:32:22 +0100
Newest: 2023-12-31 23:00:01 +0100

### Status report information ###

Generated at: 2023-11-27 13:02:07 +01:00
`

</details>

**Comment by Sirvijver** [comment]
Hello @lokacoding 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are experiencing is usually caused by another plugin or the theme, blocking our plugin to run the JavaScript that replaces the WooCommerce "Place Order" button with our generic "PayPal" button. Most of the time you can find out what is causing this issue, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

Our upcoming release (2.4.2) will have a feature included that should avoid this issue from occurring and default to the WC button if this situation occurs. The beta release for this will become hopefully available today [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases).

If you have more questions, please open a support thread as advised above.

Kind regards, 
Joost
