### ISSUE TITLE
Failed payment with box now plugin

### ISSUE THREAD

**Issue by alprio** [woocommerce/woocommerce-paypal-payments#1878]
### Describe the Bug
Hello , 
I have a plugin, box now. it is a delivery service in greece. At checkout you have to pick a locker to send the item.
On standard checkout , with another payment method (viva wallet) if someone forgets to pick a locker and tries to place an order a message appears,  please pick a locker.
On the other hand, paypal plugin doesn't check this parameter and opens the popup window to continue the transaction. If you continue , at the final step , when you press the button to pay, the transaction will fail and it will display a message please pick a locker. 

### To Reproduce

1. Go to checkout page select box now as shipping method , add all your info , check the box for privacy policy and the test with viva wallet and after that with paypal.
2. Click on '…'
3. Scroll down to …'

### Expected Behavior

check locker before paypal popup

### Actual Behavior

checks locker after failed payment

### Environment

 - WordPress Version 6.4.1
 - WooCommerce Version 8.3.1
 - Plugin Version 2.4.1
 - Browser [e.g. Chrome, Safari] and Version chrome , safari latest
 - Any other plugins installed box now

### Additional Details

to test it , it doesn't need any api or something for box now.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @alprio 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
