### ISSUE TITLE
FATAL Error from Shipstation Connection

### ISSUE THREAD

**Issue by kawhatley** [woocommerce/woocommerce-paypal-payments#1884]
"PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WooCommerce\PayPalCommerce\OrderTracking\Integration\ShipStationIntegration::WooCommerce\PayPalCommerce\OrderTracking\Integration\{closure}(),

**Comment by Sirvijver** [comment]
Hello @kawhatley,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We are aware of an issue with the 2.4.1 release, but this should be resolved with our [last release, version 2.4.2](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.2). Please update the plugin and verify if this is the case. If you are still encountering problems with that version, please open a support request as described above.

Kind regards, 
Joost
