### ISSUE TITLE
Double Slash in button.js URL

### ISSUE THREAD

**Issue by adi88nugroho** [woocommerce/woocommerce-paypal-payments#189]
### Describe the bug
Double slash in button.js URL

### To reproduce
1. Open yourdomain.com/my-account/
2. Open Developer Tools/Inspect
3. Search //assets/js/button.js

**Screenshots**
![woocommerce-paypal-payments](https://user-images.githubusercontent.com/5824107/124339500-16182780-dbd9-11eb-86c2-42287007a8cd.JPG)

### Expected behavior
It should display a single slash on the URL

**Environment (please complete the following information):**
 - WordPress 5.7.2 Version
 - WooCommerce 5.4.1 Version
 - WooCommerce PayPal Payments Plugin 1.3.2 Version
 - Browser Chrome 91 Version
 - Any other plugins installed:  RankMathSEO, WP Rocket, Elementor

**Comment by AlexP11223** [comment]
Fixed in #439
