### ISSUE TITLE
Advanced Credit Card - in mobile view

### ISSUE THREAD

**Issue by squeakita** [woocommerce/woocommerce-paypal-payments#1891]
### Describe the Bug
On a mobile device when I click the Credit Card option the fields are too wide for the screen. 
I can no longer see the option buttons to change to PayPal if wanted.

### To Reproduce

1. Go to the checkout page
2. Click on Credit Card radio option
3. You will see the credit card fields appear
4. I can no longer scroll to the left to change payment types if wanted. 
5. The fields are to wide

### Screenshots
![Capture](https://github.com/woocommerce/woocommerce-paypal-payments/assets/17814439/ec717783-ada1-4c6a-89ad-ea3115d90bb4)

### Expected Behavior
I expect to be able to change back to PayPal if wanted.
I expect to see all of the fields easily.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>
`
### WordPress Environment ###

WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 6.3.2 - There is a newer version of WordPress available (6.4.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.25
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 8.4.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 8.0.33-25
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: wp_zj9cna6s1s_
Total Database Size: 74.85MB
Database Data Size: 65.36MB
Database Index Size: 9.49MB
wp_zj9cna6s1s_woocommerce_sessions: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_avatax_tax_codes: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_actionscheduler_actions: Data: 3.03MB + Index: 1.84MB + Engine InnoDB
wp_zj9cna6s1s_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_actionscheduler_logs: Data: 0.52MB + Index: 0.31MB + Engine InnoDB
wp_zj9cna6s1s_check_email_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_zj9cna6s1s_db7_forms: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_grp_google_place: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_grp_google_review: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_grp_google_stats: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_feature_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_mapping_to_external_entities: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletter_templates: Data: 1.04MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_scheduled_tasks: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_segments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_sending_queues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_settings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_statistics_woocommerce_purchases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_options: Data: 4.44MB + Index: 1.09MB + Engine InnoDB
wp_zj9cna6s1s_postmeta: Data: 6.52MB + Index: 3.03MB + Engine InnoDB
wp_zj9cna6s1s_posts: Data: 2.52MB + Index: 0.28MB + Engine InnoDB
wp_zj9cna6s1s_redirection_404: Data: 0.25MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_zj9cna6s1s_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_slp_extendo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_store_locator: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_tm_taskmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_wc_admin_note_actions: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_wc_admin_notes: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_zj9cna6s1s_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_zj9cna6s1s_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zj9cna6s1s_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_wfconfig: Data: 1.33MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wffilemods: Data: 21.55MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfhits: Data: 0.23MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wfissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_wfknownfilelist: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wflogins: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_zj9cna6s1s_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfnotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_zj9cna6s1s_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_wfstatus: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_zj9cna6s1s_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_woof_query_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wpaas_activity_log: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_wpforms_payment_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_wpforms_payments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_zj9cna6s1s_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_campaign: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_custom_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wysija_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_url_mail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_user: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_wysija_user_field: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_user_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_wysija_user_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zj9cna6s1s_yoast_indexable: Data: 0.28MB + Index: 0.13MB + Engine InnoDB
wp_zj9cna6s1s_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zj9cna6s1s_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_zj9cna6s1s_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_zj9cna6s1s_yoast_seo_links: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_zj9cna6s1s_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

acf-field: 55
acf-field-group: 5
attachment: 614
awl_filter_gallery: 1
custom_css: 2
custom-css-js: 2
gg_galleries: 1
mailpoet_page: 1
mc4wp-form: 1
nav_menu_item: 36
page: 18
post: 2
product: 262
revision: 707
seedprod: 2
shop_coupon: 1
shop_order: 51
shop_order_refund: 14
wpcf7_contact_form: 2
wpforms: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 3.1

Advanced Custom Fields: Gallery Field: by Elliot Condon – 2.1.0
Advanced Custom Fields: Options Page: by Elliot Condon – 2.1.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.1.0
Advanced Custom Fields: by WP Engine – 6.2.4
All-in-One WP Migration Unlimited Extension: by ServMask – 2.54
All-in-One WP Migration: by ServMask – 7.79
Breadcrumb NavXT: by John Havlik – 7.2.0
Popups - Submission Messages For Contact Form 7: by Code Work Web – 1.0.8
Check & Log Email: by WPOmnia – 1.0.8
Classic Editor: by WordPress Contributors – 1.6.3
CoBlocks: by GoDaddy – 3.1.5
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.15.3
Contact Form 7: by Takayuki Miyoshi – 5.8.4
Contact Form CFDB7: by Arshid – 1.2.6.7
Simple Custom CSS and JS: by SilkyPress.com – 3.45
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
GTM4WP: by Thomas Geiger – 1.18.1
Envato Market: by Envato – 2.0.10
Head, Footer and Post Injections: by Stefano Lissa – 3.2.7
Jetpack: by Automattic – 12.9
Salient WPBakery Page Builder: by Michael M - WPBakery.com | Modified by ThemeNectar – 7.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.10
Media File Renamer: Rename Files (Manual, Auto, AI): by Jordy Meow – 5.7.7
My Custom Functions: by Space X-Chimp – 4.51
Pinterest for WooCommerce: by WooCommerce – 1.3.15
Redirection: by John Godley – 5.3.10
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
reSmush.it Image Optimizer: by reSmush.it – 0.4.13
Responsive Lightbox & Gallery: by dFactory – 2.4.6
Salient Core: by ThemeNectar – 2.0.5
Salient Demo Importer: by ThemeNectar – 1.6.1
Salient Portfolio: by ThemeNectar – 1.7.5
Salient Shortcodes: by ThemeNectar – 1.5.3
Salient Social: by ThemeNectar – 1.2.4
Salient Widgets: by ThemeNectar – 1.2
Simple CSS: by Tom Usborne – 1.1.1
Avalara AvaTax: by Avalara – 2.6.1
WooCommerce PayPal Payments: by WooCommerce – 2.4.2
Products Filter for WooCommerce: by realmag777 – 2.2.9.4
WooCommerce Shipping & Tax: by WooCommerce – 2.4.2
WooCommerce: by Automattic – 8.3.1
Wordfence Security: by Wordfence – 7.11.0
Yoast SEO Premium: by Team Yoast – 21.6
Yoast SEO: by Team Yoast – 21.6
WPForms Lite: by WPForms – 1.8.5.2
MailPoet 2: by MailPoet – 2.22

### Inactive Plugins (3) ###

Gravity Forms: by Gravity Forms – 2.7.8
Plugin for Google Reviews: by RichPlugins <support@richplugins.com> – 3.1
WP Mail SMTP: by WP Mail SMTP – 3.10.0

### Dropin Plugins (2) ###

db-error.php: db-error.php
object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Object Cache Pro (MU): by Rhubarb Group – 1.18.2
System Plugin: by  – 4.103.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #9 - /shop-all/
Cart: #11 - /cart/
Checkout: #13 - /checkout/
My account: #15 - /my-account/
Terms and conditions: #335 - /store-policy/

### Theme ###

Name: Salient Child Theme
Version: 1.0
Author URL: https://themeforest.net/user/themenectar
Child Theme: ✔
Parent Theme Name: Salient
Parent Theme Version: 16.1.2
Parent Theme Author URL: https://themeforest.net/user/themenectar
WooCommerce Support: ✔

### Templates ###

Overrides: salient/woocommerce/cart/mini-cart.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/checkout/terms.php
salient/woocommerce/content-product.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/loop/loop-start.php
salient/woocommerce/myaccount/form-login.php
salient/woocommerce/single-product/product-image.php
salient/woocommerce/single-product/rating.php
salient/woocommerce/single-product/tabs/description.php
salient/woocommerce/single-product/tabs/tabs.php
salient/woocommerce/single-product/title.php
salient/woocommerce/single-product-reviews.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-06 11:52:44 +00:00
Options: ✔
Notes: 106
Onboarding: completed

### Action Scheduler ###

Complete: 4,637
Oldest: 2023-11-05 00:56:14 +0000
Newest: 2023-12-06 00:49:41 +0000

Failed: 23
Oldest: 2023-06-26 14:00:15 +0000
Newest: 2023-12-05 18:02:05 +0000

Pending: 8
Oldest: 2023-12-06 00:53:57 +0000
Newest: 2023-12-12 04:59:21 +0000

### Status report information ###

Generated at: 2023-12-06 00:50:04 +00:00
`
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @squeakita, the default hosted fields appearance is controlled by your theme. You can [style the fields with CSS](https://woo.com/document/woocommerce-paypal-payments/#customizing-hosted-fields) like this:
```
#ppcp-credit-card-gateway-card-number, #ppcp-credit-card-gateway-card-expiry, #ppcp-credit-card-gateway-card-cvc {
  width: 50% !important;
} 
```
But for advice regarding styling changes, I recommend contacting your theme developer. The next PayPal Payments update introduces new card fields which should resolve theme-related issues like this. These [new card fields can be tested in the latest live version](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews/#how-to-test-hosted-card-fields) but they are not ready for production sites as they are not yet fully integrated.
