### ISSUE TITLE
PayPal Won't Connect to WooCommerce

### ISSUE THREAD

**Issue by nerdy1texan** [woocommerce/woocommerce-paypal-payments#1893]
I downloaded the plugin but when I click 'click to connect PayPal account', it won't open the PayPal sign in window and would simply refresh the page.

### To Reproduce

1 Go to 'WooCommerce' on left tab and click 'Settings'
2 Under settings, click on 'Payments' tab then scroll down until you see 'PayPal'. Click on it. 
3 When first time using PayPal plugin, you should be seeing the 'Connect Paypal' link as the attached picture. 

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/112106845/d887c525-d3fd-459f-bd2e-0a100d2a28cf)
![PayPal Bug](https://github.com/woocommerce/woocommerce-paypal-payments/assets/112106845/6b5f8ff0-f6be-4d06-9eb3-d4b2212616ce)

**Comment by InpsydeNiklas** [comment]
Hi @nerdy1texan, the notice only links to the onboarding page from your screenshot. To connect your account, click `Activate PayPal`. You can find the full setup instructions here: https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account
The text in this notice will be updated to better reflect what it does.

If you need additional assistance with setting up the integration, I recommend contacting the support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thank you!
