### ISSUE TITLE
WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by Pranshusingh24** [woocommerce/woocommerce-paypal-payments#1895]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Pranshusingh24 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any error, message or any details, so we will close this thread. 

Kind regards, 
Joost

**Comment by Pranshusingh24** [comment]
Ok I will provide message about it.
