### ISSUE TITLE
PayPal has discontinued the Giropay service

### ISSUE THREAD

**Issue by horgai-IT** [woocommerce/woocommerce-paypal-payments#1905]
Hello, 

I use the WooCommerce PayPal plugin on various pages. It allows payment via Giropay. However, PayPal discontinued the service in September 2023. When customers select this payment option, an error occurs and customers cannot select any other payment option via PayPal (e.g. instant payment, SEPA or PayPal itself). 

Can you please adjust this.

 - WordPress Version 6.4.2
 - WooCommerce Version 8.4.0
 - Plugin Version 2.4.2
 - Browser [e.g. Chrome, Safari] and Version: Edge 120.0.2210.61 
 - Any other plugins installed: yes many

Thank you for your help
Daniel Hoffmann

**Comment by Sirvijver** [comment]
Hello @horgai-IT,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

As far as I know, the Giropay Alternative Payment Method is still active, but I will check with PayPal and see if anything changed on their side and get it adjusted if needed. A solution for your situation is fairly simple: you can go to our plugin's settings page and deactivate any Alternative Payment Method you want to by adding it to the field for "Disable Alternative Payment Methods". Once you have added "Giropay" there, it should not show up for any customer on your checkout page.

Thank you for reporting this to us, I'll make sure this is handled. If you have any further questions, please open a support request as described above.

Kind regards, 
Joost
