### ISSUE TITLE
Dans validation de la commande on ne voie plus Paypal

### ISSUE THREAD

**Issue by BlogsSavoir** [woocommerce/woocommerce-paypal-payments#1909]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by BlogsSavoir** [comment]
depuis nouvelle page validation de la commande on ne voi plus payement par paypal

**Comment by InpsydeNiklas** [comment]
Hi @BlogsSavoir, please contact the support team from here if you need assistance setting up PayPal Payments: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
