### ISSUE TITLE
Card payments unavailable

### ISSUE THREAD

**Issue by alstr** [woocommerce/woocommerce-paypal-payments#191]
I have installed the extension and successfully linked sandbox and live credentials. The store is located in the UK, as is the PayPal account. When I go the "PayPal Card Processing" section of Payment settings, it says:

> "Credit Card processing for your account has not yet been activated by PayPal. If your account is new, this can take some days. Otherwise, please get in contact with PayPal."

I do not understand this message as the account is not new and there is nothing wrong with the PayPal account. I have never had issues coding my own checkout with card payments before, so this seems a problem with the plugin. I don't believe contacting PayPal will be of any use as they will not help with a third party plugin issue.

It occurs with both sandbox and live credentials. No conflicting plugins are enabled.

I have seen a similar issue reported recently on your forum but it was closed without resolution: https://wordpress.org/support/topic/missing-credit-card-option/

PS: this is my first time using WooCommerce and the myriad similar PayPal plugins are confusing and not clearly explained in the documentation. I tried to report on the forum but no account activation email has come through. :cry:

**Screenshots**

![Screenshot 2021-07-08 at 14 41 54](https://user-images.githubusercontent.com/11612438/124932271-d7300a80-dffa-11eb-95a5-b00e3799b8c4.png)

 - WordPress Version 5.7.2
 - WooCommerce Version 5.4.1
 - WooCommerce PayPal Payments Plugin Version 1.3.2

**Comment by InpsydeNiklas** [comment]
Hi @alstr,

Thanks for your message.
To activate the PayPal Card Processing, your PayPal account needs to have completed the business registration and also accept the terms of the card processing.
When you first connect a newly created sandbox merchant account, then this prompt should pop up:
![image](https://user-images.githubusercontent.com/70433191/124942170-b02e0480-e00b-11eb-8828-21ca64bbb366.png)
When asked for details such as a phone number or email address, you can provide the information from your sandbox account or fake data.
If you don't see this prompt for your sandbox or live account, then please open a support ticket with us as described here so we can look into this further for you:
https://paypal.inpsyde.com/docs/how-to-request-support-via-widget-on-the-website/
Thanks!

Kind regards,
Niklas

**Comment by alstr** [comment]
I used the manual setup as that is what I am accustomed to; is there a way to do this manually? I don't remember coming across this when doing other manual integrations for different store platforms.

**Comment by InpsydeNiklas** [comment]
Most of the older PayPal integrations used exclusively Client IDs and secret API keys to connect an account.
PayPal Payments is the latest official PayPal plugin and aims to simplify the user experience as well as the plugin landscape.
I suggest using the integrated onboarding via the `Connect to PayPal` button as described in the plugin documentation here to connect your account:
https://docs.woocommerce.com/document/woocommerce-paypal-payments/#section-4
If your account did not yet accept the terms for the PayPal Card Processing, then I don't think it will be available when you manually connect the account.

**Comment by alstr** [comment]
Yes, I'm using PayPal Payments but there was still an option to manually input credentials, which I did do.

I will attempt to connect an alternative way, but I think some clarification around having to connect via the button (if so) would improve things.

**Comment by alstr** [comment]
Okay, the prompt did appear when I clicked the button and went through the process. It produced an error at the end for reasons unknown, but that looks like a PayPal issue.

When looking at my PayPal developer applications now, I've got two WooCommerce live apps and no sandbox apps, but both sandbox and live are set up. There should be one instance of each I would have thought...?

Manual setup is much more intuitive. I would definitely prefer to go down that route in future.

Edit:

Sandbox has card payments enabled now but not live.

<img width="1201" alt="Screenshot 2021-07-09 at 13 18 55" src="https://user-images.githubusercontent.com/11612438/125076902-651dfb00-e0b8-11eb-8444-62ad0e4e08b2.png">

**Comment by Dinamiko** [comment]
Hello @alstr,

Sorry for the delay in the response, does this problem still persist? if so please let us know here the steps to reproduce it, thanks.

**Comment by InpsydeNiklas** [comment]
The documentation and entire onboarding screen have been revamped recently to make it more clear that additional vetting is required for advanced card payments. For any other questions, please consider reaching out to the support as mentioned here: https://github.com/woocommerce/woocommerce-paypal-payments/issues/191#issuecomment-876506601
