### ISSUE TITLE
Sub Menu hidden when side setting menu displayed in admin settings

### ISSUE THREAD

**Issue by arandocoder** [woocommerce/woocommerce-paypal-payments#1911]
### Describe the Bug

In Wordpress Admin > Woocomerce > Settings > Payments > PayPal -Pay Via Paypal - Manage

When the new Settings menu is installed the Sub menu is not displayed.
These items do not appear to have been be moved to the left menu either.

The sub menu should display the options: Conenction, Standard Payments, Pay Later, Advanced Card Processing

### To Reproduce
This happened on client site and cant reproduce

The Problem:
![Woocomerce PayPal Payments - admin settings - missing sub menu](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153187566/0f82f90e-f53d-4700-8100-3e3d09c40ad9)

What it should Look Like:
![Woocomerce PayPal Payments - admin settings - missing sub menu- fix applied](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153187566/8f3980f0-f781-48f6-8c1f-16ec8e19c39a)

### Environment

 - WordPress Version 6.3.2
 - WooCommerce Version 8.2.2
 - Plugin Version 2.4.2 
 - Browser [e.g. Chrome, Safari] and Version - same in all browsers - firefox 120.0.1 used above
 - Any other plugins installed - yes!

### Additional Details

When the new side menu is activated the Top settings menu is hidden and moved to the side menu.
The Settings sub menu is also hidden as it has been given the same CSS classes as the Top setting menu, but is not moved to the side menu. 
![Woocomerce PayPal Payments - admin settings - missing sub menu - css cause](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153187566/b39fac9c-35ca-45af-98e0-df1bee911dcc)

Renaming the sub menu allows the Top menu to be hidden and the Sub menu to be displayed:

So we could continue working I renamed the sub menu as follows: class="nav-tab-wrapper woo-nav-tab-wrapper-wpp"

in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/SettingsRenderer.php
Line 126:
From:
```$html = '<nav class="nav-tab-wrapper `woo-nav-tab-wrapper">';```
To:
```$html = '<nav class="nav-tab-wrapper woo-nav-tab-wrapper-wpp">';```

![Woocomerce PayPal Payments - admin settings - missing sub menu - css fix applied](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153187566/3a8cfc17-32d3-4efc-bfe2-f43b8d008d62)

This of course be an issue with the Admin Setting upgrade and the sub menu was not migrated to the side menu. 
I have not looked further into this as I needed a quick solution.

**Comment by InpsydeNiklas** [comment]
Hi @arandocoder, thanks for the issue report. 
The recommended solution would be to disable the _new WooCommerce navigation experience_ from `WooCommerce > Settings > Advanced > Features`:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/0b955fb8-f534-43a7-813c-082893573ff4)
This new navigation experience is not supported at this time and may result in the plugin settings not working as expected. Better support for this will be looked into once WooCommerce resumes development of this feature.
For now, I will close this issue as it duplicates #1027
