### ISSUE TITLE
Advanced Card Processing card 

### ISSUE THREAD

**Issue by maksdts** [woocommerce/woocommerce-paypal-payments#1916]
Debit / Credit Card option of advanced card processing sometimes don't show up. 

We have disabled elementor and switched to Hello Elementor.

 - WordPress Version: **6.4.2**
 - WooCommerce Version: **8.4.0**
 - Plugin Version: **2.4.2**
 - Browser [e.g. Chrome, Safari] and Version: **120.0.6099.110 (Official Build) (64-bit)**
 - Any other plugins installed: We have disabled other plugin but issue still persist

Logs:
2023-12-19T02:33:18+00:00 DEBUG POST https://api-m.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"bfffcc-d2ba9c9ff0856"}
Response Debug ID: 2e6a57552e318
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-12-19T02:33:22+00:00 DEBUG POST https://api-m.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"bfffcc-d2ba9c9ff0856"}
Response Debug ID: e45a05df2ab8d
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-12-19T02:33:38+00:00 DEBUG POST https://api-m.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"bfffcc-bb78127ef0856"}
Response Debug ID: edd51b4165582
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-12-19T02:33:43+00:00 DEBUG POST https://api-m.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"bfffcc-bb78127ef0856"}
Response Debug ID: 18c6aa150c5a8
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-12-19T02:44:36+00:00 DEBUG GET https://api-m.paypal.com/v1/notifications/webhooks
Response Debug ID: 45558e602c1e6
Response: Array
(
    [code] => 200
    [message] => OK
)

2023-12-19T02:44:36+00:00 DEBUG DELETE https://api-m.paypal.com/v1/notifications/webhooks/99T91900D2960431M
Response Debug ID: 833bd83a40116
Response: Array
(
    [code] => 204
    [message] => No Content
)

2023-12-19T02:44:36+00:00 INFO Webhooks deleted.

_______________________________________________________________
#8 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(127): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('button.endpoint...')
#9 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}('')
#10 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#11 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /www/tipmprelive_950/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action('wc_ajax_ppc-sim...')
#13 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WC_AJAX::do_wc_ajax('')
#14 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(false, Array)
#15 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /www/tipmprelive_950/public/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /www/tipmprelive_950/public/wp-blog-header.php(19): require_once('/www/tipmpreliv...')
#18 /www/tipmprelive_950/public/index.php(17): require('/www/tipmpreliv...')
#19 {main}
  thrown in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php on line 48

2023-12-15T23:21:50+00:00 CRITICAL Uncaught TypeError: WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint::__construct(): Argument #1 ($smart_button) must be of type WooCommerce\PayPalCommerce\Button\Assets\SmartButton, WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton given, called in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/services.php on line 172 and defined in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php:48
Stack trace:
#0 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/services.php(172): WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint->__construct(Object(WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton), Object(WC_Cart), Object(WooCommerce\PayPalCommerce\Button\Endpoint\RequestData), Object(WooCommerce\PayPalCommerce\Button\Helper\CartProductsHelper), Object(WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger))
#1 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#2 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#3 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('button.endpoint...')
#4 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get('button.endpoint...')
#5 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}()
#6 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator(Object(Closure))
#7 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(62): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached('button.endpoint...', Object(Closure))
#8 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(127): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('button.endpoint...')
#9 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}('')
#10 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#11 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /www/tipmprelive_950/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action('wc_ajax_ppc-sim...')
#13 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WC_AJAX::do_wc_ajax('')
#14 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(false, Array)
#15 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /www/tipmprelive_950/public/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /www/tipmprelive_950/public/wp-blog-header.php(19): require_once('/www/tipmpreliv...')
#18 /www/tipmprelive_950/public/index.php(17): require('/www/tipmpreliv...')
#19 {main}
  thrown in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php on line 48

2023-12-15T23:21:55+00:00 CRITICAL Uncaught TypeError: WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint::__construct(): Argument #1 ($smart_button) must be of type WooCommerce\PayPalCommerce\Button\Assets\SmartButton, WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton given, called in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/services.php on line 172 and defined in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php:48
Stack trace:
#0 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/services.php(172): WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint->__construct(Object(WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton), Object(WC_Cart), Object(WooCommerce\PayPalCommerce\Button\Endpoint\RequestData), Object(WooCommerce\PayPalCommerce\Button\Helper\CartProductsHelper), Object(WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger))
#1 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#2 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#3 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('button.endpoint...')
#4 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get('button.endpoint...')
#5 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}()
#6 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator(Object(Closure))
#7 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(62): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached('button.endpoint...', Object(Closure))
#8 /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(127): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('button.endpoint...')
#9 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}('')
#10 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#11 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#12 /www/tipmprelive_950/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action('wc_ajax_ppc-sim...')
#13 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(310): WC_AJAX::do_wc_ajax('')
#14 /www/tipmprelive_950/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(false, Array)
#15 /www/tipmprelive_950/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /www/tipmprelive_950/public/wp-includes/template-loader.php(13): do_action('template_redire...')
#17 /www/tipmprelive_950/public/wp-blog-header.php(19): require_once('/www/tipmpreliv...')
#18 /www/tipmprelive_950/public/index.php(17): require('/www/tipmpreliv...')
#19 {main}
  thrown in /www/tipmprelive_950/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/SimulateCartEndpoint.php on line 48

**Comment by maksdts** [comment]
![woocommerce-paypal-payments](https://github.com/woocommerce/woocommerce-paypal-payments/assets/134866351/49709643-9e9e-412f-9a91-e011517c0f35)

**Comment by Sirvijver** [comment]
Hello @maksdts 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error, you have shown above, sounds like there is a plugin conflict occurring. When you say that is "sometimes" occurs, can you tell me if you can reproduce this situation yourself? That would be the first step to take. I would create a [staging site](https://wordpress.org/plugins/wp-staging/) to see if that is possible, and then perform [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) when you are able to do that.

If this doesn't improve the situation, I would advise you to reach out to our support team as advised above, since this is a support request. This thread will be closed.

Kind regards, 
Joost

**Comment by SydeKrystian** [comment]
Hello @maksdts 

Since we don't have any records of contacting us through the helpdesk, I provide a potential solution here on GH. We have created a fixing package that can help alleviate the problem encountered. You can download it at the following link: [PCP-2520-woocommerce-paypal-payments.zip](https://f005.backblazeb2.com/file/Inpsyde/upload/2024/01/PCP-2520-woocommerce-paypal-payments.zip). We recommend you install this update and see if it resolves the issues you’re encountering.

Please do not hesitate to inform us if the issue persists after installation, or if you have any other queries.

Kind Regards,

Krystian

**Comment by maksdts** [comment]
Hi  @InpsydeKrystian 

I have installed the package you have provided and it is working  as intended. We have switched back to this plugin.
Thank you so much for fixing this for us!

So much appreciated!

**Comment by SydeKrystian** [comment]
Hello @maksdts 

I'd like to inform you that the issue you experienced won't be resolved in the upcoming update scheduled for January 22nd, version 2.5.0. However, we have prioritized this issue, and it will be addressed in the following update, version 2.5.1, slated for release on February 5th.

In light of this, my recommendation would be to refrain from updating the plugin until version 2.5.1 is available. In any case I linked PR to this issue. 

Kind regards,
Krystian

**Comment by finleydesign** [comment]
We've been experiencing the same issue for a few weeks, now, have updated to 2.5.1 today and still got failed order attempts, paypal simulation fails to load, customer reporting constant spinning wheel

**Comment by Sirvijver** [comment]
Hello @finleydesign 

Because our last release (2.5.0) had a big issue, we had to release an older version (2.4.3) again as 2.5.1, in order to minimize damage to the merchants that are using it (check the [release list](https://github.com/woocommerce/woocommerce-paypal-payments/releases) for details). 
This caused the release number you were told about, not to be correct any longer. The one that now is the one that should include a fix for you, is release 2.5.3 (because 2.5.2 will be the same release as 2.5.0, but with this big issue resolved).

I hope this makes sense. Please have a look at the release list if you need more details on the releases.

Kind regards, 
Joost

**Comment by finleydesign** [comment]
I'm still  a bit lost to which one should be on, I've downloaded what I thought was the right one, but still getting these type of errors

2024-01-27T00:19:48+00:00 ERROR Cart simulation failed: Could not validate nonce.
2024-01-27T13:17:11+00:00 ERROR Cart simulation failed: Could not validate nonce.
2024-01-27T14:25:05+00:00 DEBUG POST https://api-m.paypal.com/v1/oauth2/token?grant_type=client_credentials
Response Debug ID: 041cdc9a320ea
Response: Array
(
    [code] => 200
    [message] => OK
)
