### ISSUE TITLE
WooCommerce PayPal Payments Error

### ISSUE THREAD

**Issue by alihusnainsansi3** [woocommerce/woocommerce-paypal-payments#1918]
### Describe the Bug

Error Details
=============
An error of type E_ERROR was caused in line 48 of the file /home/madkinbeauty/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/Handler/PaymentCaptureRefunded.php. Error message: Uncaught ArgumentCountError: Too few arguments to function WooCommerce\PayPalCommerce\Webhooks\Handler\PaymentCaptureRefunded::__construct(), 1 passed in /home/madkinbeauty/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/services.php on line 94 and exactly 2 expected in /home/madkinbeauty/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/Handler/PaymentCaptureRefunded.php:48
Stack trace:
#0 /home/madkinbeauty/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/services.php(94): WooCommerce\PayPalCommerce\Webhooks\Handler\PaymentCaptureRefunded->__construct(Object(WooCommerce\WooCommerce\Logging\Logger\NullLogger))
#1 /home/madkinbeauty/public_html/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\Webhooks\WebhookModule->WooCommerce\PayPalCommerce\Webhooks\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingCon

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Actual Behavior

I got this email 
[
WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WooCommerce PayPal Payments.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires. ]

### Environment

 WordPress version 6.4.2
Active theme: Risen Legacy Theme for Divi (version 1.0)
Current plugin: WooCommerce PayPal Payments (version 2.2.2)
PHP version 7.4.33

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

```[tasklist]
### Tasks
```

**Comment by SydeKrystian** [comment]
Case already handled by support.
