### ISSUE TITLE
Kirim

### ISSUE THREAD

**Issue by fathur251994** [woocommerce/woocommerce-paypal-payments#1919]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @fathur251994, if you need assistance with setting up PayPal Payments, please contact the support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
