### ISSUE TITLE
Using old shortcode cause error when editing page

### ISSUE THREAD

**Issue by Tropicalista** [woocommerce/woocommerce-paypal-payments#1921]
### Describe the Bug

If I use old shortcode I got this error:

`
[21-Dec-2023 06:42:56 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_total() on null in /home/u521952913/domains/archimediabellearti.it/public_html/new/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php:841
Stack trace:
#0 /home/u521952913/domains/archimediabellearti.it/public_html/new/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(1111): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->message_values()
#1 /home/u521952913/domains/archimediabellearti.it/public_html/new/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/src/PayPalPaymentMethod.php(212): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->script_data()
#2 /home/u521952913/domains/archimediabellearti.it/public_html/new/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/PaymentMethodRegistry.php(62): WooCommerce\PayPalCommerce\Blocks\PayPalPaymentMethod->get_payment_method_data()
#3 /home/u521952913/domains/archimediabellearti.it/public_ in /home/u521952913/domains/archimediabellearti.it/public_html/new/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php on line 841
`

### To Reproduce

1. Go to 'checkout' page 
2. Add old shortcode block
3. Save
4. Refresh the page or try to edit the checkout page

**Comment by InpsydeNiklas** [comment]
Hi @Tropicalista, I'm unable to reproduce this error as it is most likely caused by a third-party plugin. Please contact the support team from here if you need assistance with PayPal Payments: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
