### ISSUE TITLE
A bunch of errors in Console panel in Chrome

### ISSUE THREAD

**Issue by yaro97** [woocommerce/woocommerce-paypal-payments#1923]
### Describe the Bug

My website is mostly set up, but when I check the Console panel in Chrome, I see a bunch of errors, as shown in the screenshot. After some debugging, I realized it's an issue with the WooCommerce PayPal Payments plugin

### To Reproduce

1. Open website;
2. Go to 'Console panel'  in Chrome;
3. See error

### Screenshots

[Error.png](https://s2.loli.net/2023/12/22/xArniGlYvUh4sy6.png)

### Environment

 - WordPress Version: 6.4.2
 - WooCommerce Version: 8.3.1
 - Chrome Version:  120.0.6099.129 (Official Build) (64-bit)

**Comment by InpsydeNiklas** [comment]
PayPal does not appear to load the Pay Later messaging for the connected account. When connecting a sandbox account, this console warning likely goes away.
So you can either disable the Pay Later messaging in the "Pay Later" tab of the plugin settings or contact the [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to clarify why the messaging would not be delivered for your connected account.

If you need any assistance with setting up the plugin, I recommend contacting the support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help 
I will close this issue as it is not a problem with the PayPal Payments plugin.
