### ISSUE TITLE
Paypal not showing pay by credit/debit card

### ISSUE THREAD

**Issue by Robo1974** [woocommerce/woocommerce-paypal-payments#1929]
### Describe the Bug

i have installed the WooCommerce PayPal Payments plugin and the problem I am having is that the option to pay by credit card will not appear/show as an option in the checkout. URL is https://ugoonline.co.uk/

### To Reproduce

1. add products to the basket
2. view basket
3. go to checkout
4. you will see the option to pay by payal and you will NOT see the option to pay by card

![Screenshot 2023-12-25 at 08 00 44](https://github.com/woocommerce/woocommerce-paypal-payments/assets/154792392/ff01ee35-45b2-4c09-9a7d-94969b440b90)

### Expected Behavior

when the user gets to checkout, the user should get the option to pay by card but this option will not show

### Actual Behavior

the card payment option will not show at checkout

### Environment

 - WordPress Version 6.4.2
 - WooCommerce Version 8.4.0
 - Plugin Version 8.4.0
 - Browser [e.g. Chrome, Safari] and Version checked on all
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
To provide credit card options via PayPal Payments, you would need to use the shortcode Checkout as card options are not yet supported on the new Block Checkout: https://woo.com/document/woocommerce-paypal-payments/#woocommerce-blocks
Please contact the support from here for any questions about the plugin setup: https://woo.com/document/woocommerce-paypal-payments/#get-help
