### ISSUE TITLE
[Tablets Orders] Consider collapsing the drawer when clicked outsed and when expanded

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-paypal-payments#1930]

**Comment by InpsydeNiklas** [comment]
Hi @kidinov, can you elaborate on what this has to do with the PayPal Payments integration? I'm not seeing the relationship here. Thanks!

**Comment by kidinov** [comment]
@InpsydeNiklas Picked the wrong repo, sorry
