### ISSUE TITLE
cannot check out if the user is logged in or if order has a user assigned to it 

### ISSUE THREAD

**Issue by ProPixelMedia** [woocommerce/woocommerce-paypal-payments#1931]
if a pending order has a Customer ID assigned to it (like if the user is logged in), and if the customer tries to pay 
then it won't let them use a credit card to pay.  Paypal is the only option to pay. What could cause this?  how can I fix this?

configuration:
Woocommerce

happens in all browsers, cleared cache, etc.

**Comment by InpsydeNiklas** [comment]
Hello @ProPixelMedia, if you need assistance setting up PayPal Payments, please contact the support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
