### ISSUE TITLE
übersetzung und Versandeinstellungen

### ISSUE THREAD

**Issue by amafino** [woocommerce/woocommerce-paypal-payments#1932]
### Describe the Bug
Die deutschen Übersetzungen sind miserabel und die Versandeinstellungen sind nun in englisch überschrieben worden; diese waren vorher in deutsch.
Insgesamt scheint das Plugin also sehr fehlerhaft zu sein

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version 6.4.2
 - WooCommerce Version 8.4.0
 - Plugin Version 2.4.2
 - Browser [e.g. Chrome, Safari] and Version chrome
 - Any other plugins installed

### Additional Details

`
### WordPress Environment ###

WordPress address (URL): https://amafino.de
Site address (URL): https://amafino.de
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.2.13
PHP Post Max Size: 200 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.5.21-MariaDB-0+deb11u1
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: kbhxl_
Datenbank-Gesamtgröße: 82.33MB
Datenbank-Datengröße: 41.29MB
Datenbank-Indexgröße: 41.04MB
kbhxl_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbhxl_woocommerce_order_items: Daten: 0.31MB + Index: 0.11MB + Engine InnoDB
kbhxl_woocommerce_order_itemmeta: Daten: 3.52MB + Index: 5.03MB + Engine InnoDB
kbhxl_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbhxl_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_actionscheduler_actions: Daten: 0.06MB + Index: 0.13MB + Engine InnoDB
kbhxl_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_actionscheduler_logs: Daten: 1.52MB + Index: 0.44MB + Engine InnoDB
kbhxl_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_comments: Daten: 1.52MB + Index: 0.86MB + Engine InnoDB
kbhxl_css_js_manager: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_duplicator_packages: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_ebay_accounts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_auctions: Daten: 3.52MB + Index: 0.22MB + Engine InnoDB
kbhxl_ebay_categories: Daten: 3.52MB + Index: 3.28MB + Engine InnoDB
kbhxl_ebay_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbhxl_ebay_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_orders: Daten: 0.09MB + Index: 0.03MB + Engine InnoDB
kbhxl_ebay_payment: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_profiles: Daten: 0.22MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_shipping: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_sites: Daten: 0.03MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_stocks_log: Daten: 0.11MB + Index: 0.00MB + Engine InnoDB
kbhxl_ebay_store_categories: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_ebay_transactions: Daten: 0.09MB + Index: 0.05MB + Engine InnoDB
kbhxl_feedmanager_channel: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_feedmanager_country: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_feedmanager_feed_status: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
kbhxl_feedmanager_field_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_feedmanager_product_feed: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_feedmanager_product_feedmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
kbhxl_feedmanager_source: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
kbhxl_gla_shipping_rates: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_gpf_feeds: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
kbhxl_import_postID: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_options: Daten: 3.42MB + Index: 0.22MB + Engine InnoDB
kbhxl_pmxe_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_postmeta: Daten: 11.52MB + Index: 17.06MB + Engine InnoDB
kbhxl_posts: Daten: 1.52MB + Index: 0.55MB + Engine InnoDB
kbhxl_po_plugins: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbhxl_rank_math_404_logs: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_rank_math_analytics_gsc: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbhxl_rank_math_analytics_inspections: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
kbhxl_rank_math_analytics_objects: Daten: 0.09MB + Index: 0.02MB + Engine InnoDB
kbhxl_rank_math_internal_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_rank_math_redirections: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_rank_math_redirections_cache: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_termmeta: Daten: 0.42MB + Index: 0.44MB + Engine InnoDB
kbhxl_terms: Daten: 0.09MB + Index: 0.09MB + Engine InnoDB
kbhxl_term_relationships: Daten: 0.19MB + Index: 0.14MB + Engine InnoDB
kbhxl_term_taxonomy: Daten: 0.16MB + Index: 0.11MB + Engine InnoDB
kbhxl_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_tm_tasks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_usermeta: Daten: 5.52MB + Index: 9.03MB + Engine InnoDB
kbhxl_users: Daten: 0.20MB + Index: 0.17MB + Engine InnoDB
kbhxl_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_wc_customer_lookup: Daten: 0.13MB + Index: 0.09MB + Engine InnoDB
kbhxl_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_wc_order_product_lookup: Daten: 0.23MB + Index: 0.30MB + Engine InnoDB
kbhxl_wc_order_stats: Daten: 0.17MB + Index: 0.19MB + Engine InnoDB
kbhxl_wc_order_tax_lookup: Daten: 0.11MB + Index: 0.11MB + Engine InnoDB
kbhxl_wc_product_attributes_lookup: Daten: 0.13MB + Index: 0.14MB + Engine InnoDB
kbhxl_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wc_product_meta_lookup: Daten: 0.11MB + Index: 0.17MB + Engine InnoDB
kbhxl_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wdp_orders: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
kbhxl_wdp_order_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
kbhxl_wdp_rules: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
kbhxl_wdr_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
kbhxl_woocommerce_amazon_buyer_index: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
kbhxl_wpr_rocket_cache: Daten: 0.13MB + Index: 0.19MB + Engine InnoDB
kbhxl_wpr_rucss_used_css: Daten: 0.30MB + Index: 0.36MB + Engine InnoDB

### Post Type Counts ###

attachment: 599
customer_groups: 4
custom_css: 4
nav_menu_item: 88
oembed_cache: 6
page: 19
post: 16
product: 307
product-feed: 1
product_variation: 481
saswp: 1
shop_coupon: 1
shop_order: 1172
shop_order_refund: 34
warmcache: 1
woo_product_tab: 2
wpuf_contact_form: 1
wpuf_input: 3
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Antispam Bee: von pluginkollektiv – 2.11.5
B2B Market: von MarketPress – 2.1.3
OMGF Pro: von Daan from Daan.dev – 3.10.1
OMGF: von Daan von Daan.dev – 5.7.10
Rechtstexte-Schnittstelle der IT-Recht Kanzlei: von IT-Recht Kanzlei – 1.0.8
Loco Translate: von Tim Whitlock – 2.6.6
Rank Math SEO: von Rank Math – 1.0.209
SHOPVOTE: von SHOPVOTE – 2.1.1
SimpleTOC - Inhaltsverzeichnis Block: von Marc Tönsing – 6.0.14
WooCommerce Amazon Pay: von WooCommerce – 2.5.1
German Market: von MarketPress – 3.31
Woocommerce orgaMAX: von Thomas Meichtry – 2.3
WooCommerce PayPal Payments: von WooCommerce – 2.4.2
WooCommerce: von Automattic – 8.4.0
WP Mail Smtp - SMTP7: von Arshid – 1.0.8
WooCommerce Google Feed Manager: von WP Marketing Robot – 3.2.0
WP Rocket: von WP Media – 3.15.6
Custom Product Tabs for WooCommerce: von Code Parrots – 1.8.5

### Inactive Plugins (2) ###

Advanced Database Cleaner PRO: von Younes JFR. – 3.2.3
WP-Lister Lite for eBay: von WP Lab – 3.5.4

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop-Basis: #8 - /
Warenkorb: #9 - /warenkorb/
Kasse: #10 - /kasse/
Mein Konto: #11 - /mein-konto/
Allgemeine Geschäftsbedingungen: #14 - /agb/

### Theme ###

Name: Overlay
Version: 10.5.3
Author URL: https://kairaweb.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-28 16:01:12 +01:00
Options: ✔
Notes: 2
Onboarding: completed

### Action Scheduler ###

Complete: 116
Oldest: 2023-11-27 14:59:10 +0100
Newest: 2023-12-27 17:21:42 +0100

Failed: 9
Oldest: 2023-10-24 05:41:33 +0200
Newest: 2023-12-25 11:10:58 +0100

Pending: 1
Oldest: 2023-12-27 18:06:51 +0100
Newest: 2023-12-27 18:06:51 +0100

### Status report information ###

Generated at: 2023-12-27 17:26:52 +01:00
`

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
The PayPal Payments plugin has nothing to do with your shipping options. 
The wordpress.org community manages the plugin translations. Feel free to contribute your translations for the plugin in your preferred language here: https://translate.wordpress.org/projects/wp-plugins/woocommerce-paypal-payments/

But if you have any questions about the plugin, please contact the support team from here: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!

**Comment by amafino** [comment]
ok, Jetzt ist mir alles klar...

**Comment by InpsydeNiklas** [comment]
Deutschprachigen Support gibt es aktuell nicht, besonders nicht hier auf GitHub da dies die Entwicklungsplatform ist. Support kann von hier angefragt werden: https://woo.com/document/woocommerce-paypal-payments/#get-help
Unser Team wird allerdings auf Englisch antworten. Im Zweifelsfall kannst du auch gerne z.B. auf [Google Translate](https://translate.google.com/?sl=auto&tl=de&text=The%20PayPal%20Payments%20plugin%20has%20nothing%20to%20do%20with%20your%20shipping%20options.%0AThe%20wordpress.org%20community%20manages%20the%20plugin%20translations.%20Feel%20free%20to%20contribute%20your%20translations%20for%20the%20plugin%20in%20your%20preferred%20language%20here%3A%20https%3A%2F%2Ftranslate.wordpress.org%2Fprojects%2Fwp-plugins%2Fwoocommerce-paypal-payments%2F%0A%0ABut%20if%20you%20have%20any%20questions%20about%20the%20plugin%2C%20please%20contact%20the%20support%20team%20from%20here%3A%20https%3A%2F%2Fwoo.com%2Fdocument%2Fwoocommerce-paypal-payments%2F%23get-help%0AThanks!&op=translate) zurückgreifen.
