### ISSUE TITLE
Authorization error with woocommerce paypal payment plugin

### ISSUE THREAD

**Issue by reinsch-it** [woocommerce/woocommerce-paypal-payments#1945]
### To Reproduce

No payment possible

### Screenshots

![PayPal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/155904656/787580cd-3f3d-402b-b180-db7a4ede830d)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @reinsch-it 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The notification you have encountered should not affect the payment that being performed. This notification should purely be a check to verify if the merchant has got Reference Transactions active on their account, but should not affect any payments (unless vaulting is required for subscription renewals).

If you believe this does have a negative effect on your sales or payments, please open a support ticket with our support team as explained above. For now, we will mark this thread as resolved.

Kind regards, 
Joost
