### ISSUE TITLE
when plugin is enabled have some errors

### ISSUE THREAD

**Issue by michalczajka** [woocommerce/woocommerce-paypal-payments#1961]
Warning
: Undefined property: WooCommerce::$payment_gateways in
/Users/michalczajka/Local Sites/senga-dance/app/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Checkout/DisableGateways.php
on line
118

**Comment by Sirvijver** [comment]
Hello @michalczajka 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). 

If this does not identify a cause for this failure, please open a support request as advised above, so our support team can take another look. When/if you do, please be sure to add the system report and more details on the issue you are encountering. We will now close this thread.

Kind regards, 
Joost
