### ISSUE TITLE
Could not validate nonce.

### ISSUE THREAD

**Issue by zerofoxderby** [woocommerce/woocommerce-paypal-payments#1965]
When customer tries to purchase through the express button a code pops up "Could not validate nonce."

We tried reinstalling and reconnecting but it still has that issue. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @zerofoxderby 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Have you already tried to test this situation with a sandbox account? This way, you can see if it might be related to your account; you might not have Reference Transactions activated on your account?
Another option you can try is to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this all shows you no possible cause for this issue, you should probably open a support request as described above. This thread on GH will now be close.

Kind regards, 
Joost
