### ISSUE TITLE
Paypal Buttons not showing in Checkout page payment tabs

### ISSUE THREAD

**Issue by rikrdomat** [woocommerce/woocommerce-paypal-payments#1966]
PayPal payment buttons are not showing on the Checkout page to complete the purchase.

It only shows the paypal button at the top as "Quick Pay" but it doesn't show in the payment options at the bottom where it should, it just shows a message "Pay with PayPal. When you click "Go to PayPal" you will be redirected to PayPal to complete your purchase"

In Woocommerce settings - Payments, I have bank transfer, check, cash on delivery and paypal, they all work fine except Paypal.

Screenshots:
https://snipboard.io/s1XkcG.jpg
https://snipboard.io/2dvOAP.jpg
https://snipboard.io/chtCju.jpg
https://snipboard.io/yGZtjF.jpg
https://snipboard.io/2fNU8y.jpg

WordPress Version: 6.4.2
WooCommerce Version: 8.5.1

**Comment by Sirvijver** [comment]
Hello @rikrdomat 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I believe that the situation you have encountered in your blocks checkout page is the correct current situation. If you want to read more about this situation, you can read [here about the Blocks checkout ](https://woo.com/document/woocommerce-paypal-payments/#woocommerce-blocks). At this moment we are working on getting the standard checkout button added, but for now, the classic checkout page (using the short code [woocommerce_checkout]) is the only way you can get this older option to display the PayPal checkout button.

If you believe there is an issue and need our support team to have a look, I would advise you to open a support ticket with our team as describe above. I will close this GitHub thread now.

Kind regards, 
Joost
