### ISSUE TITLE
PHP Compatibility Checker error 8.0

### ISSUE THREAD

**Issue by Grootyyy** [woocommerce/woocommerce-paypal-payments#1975]
Looking tu update my website to PHP8 and I used the PHP Compatibility Checker and the following errors came out on WooCommerce PayPal Payments plugin. I did a live test with PHP8 and I had Critical errors when cron jobs from the server were executed... 

To Reproduce

I did a live test with PHP8 and I had Critical errors when cron jobs from the server were executed... Please check if those issues can affect those errors or any other errors with PHP8, Thanks. If a patch exists, would it be possible to explain to me how it is possible to modify the lines of code to add a patch which resolves this problem.

PHP 8.0 incompatibilities:

FILE: vendor/dhii/human-readable-interface/src/CaptionAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/DescriptionAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/LabelAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/MessageAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/src/TitleAwareInterface.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/CaptionAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/DescriptionAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/LabelAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/MessageAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: vendor/dhii/human-readable-interface/tests/functional/TitleAwareInterfaceTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERRORS AND 0 WARNINGS AFFECTING 1 LINES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3 | ERROR | 'string' is a reserved keyword as of PHP version 7.0 and should not be used to name a class, interface or trait or as part of a namespace (T_NAMESPACE) 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by InpsydeNiklas** [comment]
Hello @Grootyyy, these are "false positives" and can be safely ignored. PayPal Payments works well with the latest PHP versions. If you have any doubts, I recommend [contacting the support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
