### ISSUE TITLE
Plugin seems to always behave as though vaulting is on, regardless of actual setting

### ISSUE THREAD

**Issue by cmaresh** [woocommerce/woocommerce-paypal-payments#1982]
### Describe the Bug

After update to 2.5.0, I get the following error on the checkout page when clicking the 'Paypal' payment method:

"NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE: The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source."

Vaulting is turned off in our WC settings.

### To Reproduce

1. Create a new user account
2. Add product to cart
3. Go to checkout
4. Fill in all required details
5. Click 'Paypal' payment method

### Screenshots

N/A

### Expected Behavior

Paypal payment window should have opened as usual

### Actual Behavior

The Paypal payment window didn't open, and an error appeared at the top of the checkout page instead.

### Environment

 - WordPress Version - 6.4.2
 - WooCommerce Version - 8.5.1
 - Plugin Version - 2.5.0
 - Browser [e.g. Chrome, Safari] and Version
    Chrome - Version 120.0.6099.225
    Firefox - 121.0.1
 - Any other plugins installed (WooCommerce related, only)
WooCommerce API Product Sync with Multiple Stores - 2.8.0
WooCommerce Gift Cards - 1.15.4
Sequential Order Numbers for WooCommerce 1.10.1
Remarkety - Email Marketing for WooCommerce 1.4.5
Preview E-mails for WooCommerce 2.2.1
Order Export & Order Import for WooCommerce 2.4.7
Flexible Checkout Fields PRO 3.5.6
Customer Reviews for WooCommerce PRO 1.4.3

### Additional Details

The option to pay with credit/debit also disappeared from our payment menu after update. All these problems were resolved when rolling back this plugin to 2.4.3, with no other changes to the site.

**Comment by gunship800** [comment]
Every time I update this plugin I have to manually make sure it works on the front end for customers otherwise I roll it back again.  It happens a lot.  

Something else I found with Paypal/Advanced Card Processing is that you have to drag that option to #1 in tree and back to #2 then re-save again and it will sometimes fix your checkout options.

**Comment by Sirvijver** [comment]
Hello @cmaresh 

The issue you have reported is a known bug with the 2.5.0 release. The team has reverted to the older version and pushed it out at version 2.5.1, so this will not happen any more. We are working on this issue and will provide updates via [this issue](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1981), but close this one as a duplicate.

Sorry for the inconvenience.

Kind regards, 
Joost
