### ISSUE TITLE
different payment options

### ISSUE THREAD

**Issue by Muri840** [woocommerce/woocommerce-paypal-payments#1987]
When I'm at the checkout, different options are usually displayed via PayPal such as PayPal, SEPA, Sofort, debit or credit card, giropay. sometimes some are not displayed. If I activate "pay later" all 5 are displayed again, otherwise 3 times 4. What's wrong?

Version 2.5.1

**Comment by Sirvijver** [comment]
Hello @Muri840,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The Alternative Payment Methods you are asking about, are additional options that are provided by decision of PayPal (server). Our plugin only has got the option to select payment methods you DON'T want to display. This is an option in the plugin setting that is named "Disable Alternative Payment Methods". When you have not entered any payment methods here, only PayPal (server-side) can decide what Alternative Payment Methods are not shown. If you really think there is an issue with this, you might want to talk with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review this situation.

If you think our plugin is at fault here, and you need us to have a closer look, please open a support ticket as described above. We will close this GitHub thread now.

Kind regards, 
Joost
