### ISSUE TITLE
Paypel refund error for Paypal orders without "invoice_id"

### ISSUE THREAD

**Issue by cristianhanna** [woocommerce/woocommerce-paypal-payments#1993]
### Describe the Bug

When creating a Paypal order, the "invoice_id" parameter is optional.

If a refund is made for an order made without "invoice_id" the error appears:
Response Body: {"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema","debug_id":"87106db1860fc","details":[{"issue": "INVALID_STRING_LENGTH","field":"/invoice_id","value":"","description":"The value of a field is either too short or too long.","location":"body"}], "links":[{"href":"https://developer.paypal.com/docs/api/payments/v2/#error-INVALID_STRING_LENGTH","rel":"information_link"}]}

### To Reproduce

1. Create one Paypal order without "invoice_id" using API https://developer.paypal.com/docs/api/orders/v2/
2. Refund the paypal order

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

To fix the bug:
- edit the file /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Entity/RefundCapture.php , public function to_array() : array {
- replace the line: "		$data = array(
			'invoice_id' => $this->invoice_id(),
		);"
with line: "		if ( !empty($this->invoice_id()) ) {
			$data = array(
				'invoice_id' => $this->invoice_id(),
			);
		}"

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
This should be resolved with the changes in #1997, which is included in the 2.5.2 update: https://github.com/woocommerce/woocommerce-paypal-payments/releases
