### ISSUE TITLE
Missing PayPal "Pay Now" button - Standard Payments

### ISSUE THREAD

**Issue by kzSoUlFaThEr** [woocommerce/woocommerce-paypal-payments#1995]
### Describe the Bug

In the payment dialog of Woo Commerce, the normal radio button option for paypal does not show to the button that takes you to paypal. The other 2 options provide the "pay now" button (direct bank transfer and direct debit).

### To Reproduce

1. Go to "Alle Termine" in the main Navigation at the top of the website www.panchooo.de'
2. Click on 'the first event in the list'
3. Scroll down to the order dialog, select 1 ticket and click "Ticket Kaufen" (Buy Ticket). When the page loads click on "Übersicht & Bezahlen" (Overview and pay) and then select the radio button for Paypal.
4. See error: the is no button to continue to paypal to pay. If you choose either of the other 2 options, the blue pay now button appears.
5. If you click on the CART icon at the top of the page it shows you the cart with your selected item and the yellow paypal buzttons and both of these work proerly (they take you to paypal). This is the only way to actually pay with paypal.

### Screenshots
The screenshot shows the missing button
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/40119851/37e9f244-cb53-4356-90a1-aa9c2f83df48)

This screenshot show another pay option providing the required button to actually pay
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/40119851/56988ae2-1fea-4462-a522-c8c4cd2c6e74)

### Expected Behavior

I should have a pay now button when paypal is selected.

### Actual Behavior

When Paypal is selected, no button to pay now appears

### Environment

 - WordPress Version 6.4.2
 - WooCommerce Version 8.5.2
 - Plugin (Woo Commerce PayPal Payments) Version 2.5.1
 - Browser [Chrome] and Version 120.0.6099.225 (Official Build) (64-bit)
 - 
 - Extra Plugins (all are status: Activated):
 - Advanced Dynamic Pricing for WooCommerce (version 4.6.0)
 - Checkout Field Editor for WooCommerce (version 2.0.0)
 - Event Manager and Tickets Selling plugin for WooCommerce - WPEvently (version 4.1.3)
 - Germanized für WooCommerce (version 2.15.5)
 - Germanized für WooCommerce Pro (license has run out and will not update which disables extra (and unused) features not pertaining to any type of payment options) (version 3.2.2)
 - Germanized für WooCommerce: One Stop Shop (version 1.5.1)
 - Vendidero Helper (Vendidero makes the Germanized WooCommerce plugins) (Version 2.2.2)
 - All of these plugins were updated TODAY (26 January 2024)

### Additional Details
Paypal plugin settings screenshot ("erfassen" = Authorize) (Anmeldung = Login)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/40119851/03b6b6a2-ec32-4875-bb7a-fb0c6cbdf175)

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @kzSoUlFaThEr 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have tested your checkout page and see the PayPal button as expected:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/85ca56d4-d914-40ea-861e-c68ab9248547)

Did you already get this issue fixed or are you using another browser/OS? Do you have JavaScript activated on your browser? Also, please try another browser/device and see if the outcome changes. If none of this helped, please open a support request as advised above for further support from our support team.

Kind regards, 
Joost

**Comment by kzSoUlFaThEr** [comment]
No........at the top of your screenshot is the button that is not
working........not the buttons at the bottom

**Comment by kzSoUlFaThEr** [comment]
oh....never mind yes now it works

**Comment by kzSoUlFaThEr** [comment]
the correction was a setting in the plugin to go directly to the cart
page.........with that not set to yes...the problem persist that pay pal
choice shows no purchase buttons
