### ISSUE TITLE
Hola es que cuando le doy a finalizar la compra me aparece un errror de paypal que me dicen lo sentimos, el total permitido de pedido permitido es 1500 al usar este medio de pago

### ISSUE THREAD

**Issue by Luisale7** [woocommerce/woocommerce-paypal-payments#2001]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Luisale7** [comment]
hola 
es que cuando le doy a finalizar la compra por paypal en wordpress me aparece lo sentimos, el total minimo de pedido permitido es 1500 al usar este medio de pago

**Comment by Sirvijver** [comment]
Hello @Luisale7 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This error is most likely coming from the PayPal server and not the plugin. You might want to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and check with them if there is any type of limitation set for your account.

If they can't see any issue there, and you believe this is related to the plugin, please open a support request as advised above. This thread will be closed.

Kind regards, 
Joost
