### ISSUE TITLE
WooCommerence Paypal Setup Page is broken 

### ISSUE THREAD

**Issue by NaWiAu** [woocommerce/woocommerce-paypal-payments#2013]
Hi I am having trouble setting up Paypal fo woocommerence 
![Screenshot 2024-02-02 081049](https://github.com/woocommerce/woocommerce-paypal-payments/assets/158552768/fb7cce3f-e046-465b-9afc-a9459c5c20e3)

The textareas for the settings are only shown for a brief moment while the page is loading but then they dissapear.

**Comment by Sirvijver** [comment]
Hello @NaWiAu 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you reported is not a known issue, and we have no other reports of this. We would expect that a 3rd party plugin or the theme you are using might be causing this issue. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you, please open a support ticket as advised above. This thread will be closed.

Kind regards, 
Joost
