### ISSUE TITLE
Paypal option not available on manually created orders

### ISSUE THREAD

**Issue by dabesa** [woocommerce/woocommerce-paypal-payments#2017]
### Describe the Bug

If an admin creates an order from the WP dashboard, the customer doesn't have option to pay via Paypal.

### To Reproduce

1. Go to Dashboard -> Orders
2. Create a new order, add a product and click Create
3. Go to the payment page for that order (link "Customer payment page")
4. At checkout, the Paypal payment method doesn't appear

### Screenshots

This is a screen recording showing the issue:
https://app.screencastify.com/v3/watch/Mrh34Va1QfIx7vFkSdIu

### Expected Behavior

The Paypal payment method should be available both orders created by backend as well.

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.5.2
 - Plugin Version  2.5.2

**Comment by InpsydeNiklas** [comment]
Hi @dabesa, thanks for the issue report! This was resolved in the recent [2.5.3 ](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.5.3) update.
