### ISSUE TITLE
unable to make payments, token not generated or payment error

### ISSUE THREAD

**Issue by sergy00** [woocommerce/woocommerce-paypal-payments#2025]
![Immagine 2024-02-06 162142](https://github.com/woocommerce/woocommerce-paypal-payments/assets/159769983/5236532e-f5be-4212-86c8-03c387aa1fff)
![Immagine 2024-02-10 142122](https://github.com/woocommerce/woocommerce-paypal-payments/assets/159769983/7b7cf598-6ead-4659-baed-020f3fa7ef30)

### Describe the bug

on my sites it is not possible to make the payment, sometimes it works and sometimes it doesn't

I have already tried deactivating the plugin, reactivating it and resetting it, on PayPal I regenerated the new api, it works at first but after a while it no longer works

### To be reproduced

click on the payment button and errors are generated, both on a single product and on checkout

WooCommerce version: 8.5.2
WooCommerce REST API Package: 8.5.2
WooCommerce Blocks Package: 11.8.
Action Planner Package: 3.7.1
WordPress version: 6.4.3
Chrome
WooCommerce PayPal Payments Version 2.5.3

#log status:

2024-02-06T15:46:48+00:00 CRITICAL Uncaught TypeError: Argument 1 passed to WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint::__construct() must be an instance of WooCommerce\PayPalCommerce\Button\ Assets\SmartButton, provided WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton instance, called in /home/*************************.php at line 172 and defined in /home/****************************************** **.php:48
Stack trace:
#0 /*********************************************** * ******.php(172): WooCommerce\PayPalCommerce\Button\Endpoint\SimulateCartEndpoint->__construct(Object(WooCommerce\PayPalCommerce\Button\Assets\DisabledSmartButton), Object(WC_Cart), Object(WooCommerce\PayPalCommerce\ Button \Endpoint\RequestData), Object(WooCommerce\PayPalCommerce\Button\Helper\CartProductsHelper), Object(WooCommerce\WooCommerce\Logging\Log in /home/***************** *** *********************************************** .php on line 48

**Comment by Sirvijver** [comment]
Hello @sergy00 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue would require more testing to find out what is happening in this situation. We did not get the system report and would also like to look into the full logs for this case. Have you also tried using the plugin in sandbox mode (to rule out an account issue)? Next to plugin, are you also running any custom code on your site?

If you want our support team to have a look at this, please open a private engagement as suggested above.

Kind regards, 
Joost
