### ISSUE TITLE
chackout 

### ISSUE THREAD

**Issue by farouk33-5** [woocommerce/woocommerce-paypal-payments#2032]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @farouk33-5 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any problem description, so if you do have an issue, I would advise you to add the system report, logs and encountered error on a support ticket that should be opened following the instructions provide above. This thread will be closed.

Kind regards, 
Joost
