### ISSUE TITLE
PayPal not working on Website

### ISSUE THREAD

**Issue by CertifiedPrinting** [woocommerce/woocommerce-paypal-payments#2037]
### Paypal not working

 PayPal is suddenly not working on my website

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @CertifiedPrinting 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not add any details or specific questions about the issue you are encountering, so I cannot give you any initial response on that. Please open a support ticket as advised above, so we can help you out further. This GitHub thread will be closed now.

Kind regards, 
Joost
