### ISSUE TITLE
Cannot connect or edit any payment settings, WooPayments, PayPal  nor Stripe.  Instructions not clear!

### ISSUE THREAD

**Issue by doug2son** [woocommerce/woocommerce-paypal-payments#2039]
Cannot connect or edit any payment settings, WooPayments, PayPal  nor Stripe.  Instructions not clear!

1) I have gone through the process of activating PayPal a number of times and On PayPal's side it has gone through but when I come back to the website  www.tryndzi.com it still says ACTIVATE ... 
2)  Also When I try to save Setting (I am logged in as an Admin) is says "Error saving settings"
3) When I try to edit  Payments it says: "Error retrieving disputes."

Clearly something is broke BIG TIME.   All the software is in stalled but it will not let me do any editing. 

### To Reproduce
#1 You cannot reproduce my PayPal as it requires my Login info.
#2  Goto Woocommerce
     Goto Settings
     Goto Payments   will not save  "Error saving settings"
#3 
1. Go to   PAYMENTS in the side bar
2. Click on  EDIT 
3. 
4. See error  Error retrieving disputes.

### Screenshots
https://www.screenpresso.com/=F4Yqb
https://www.screenpresso.com/=enHWb
https://www.screenpresso.com/=IJYAd

### Expected Behavior

should just work
### Actual Behavior

nothing works  can setup up payments

### Environment

 - WordPress Version   6.4.3
 - WooCommerce Version 8.6.0
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version  Chrome / Brave / 
 - Any other plugins installed  
 - Astra Pro
 - Duplicator
 - Elementor
 - Elementor Header & Footer Builder
 - Elementor Pro
 - Pinterest for WooCommerce
 - Printify Shipping Method
 - Rank Math SEO
 - Really Simple SSL
 - Ultimate Addons for Elementor
 - Variation Swatches for WooCommerce
 - WooCommerce
 - WooCommerce Cart Abandonment Recovery
 - WooCommerce PayPal Payments
 - WooCommerce Shipping & Tax
 - WooCommerce Stripe Gateway
 - WooPayments
 - Wordfence Security
 - WP Mail SMTP
 - 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @doug2son 

Please be aware that these issues fall outside our standard support scope, as our primary focus is on supporting the PayPal Payments plugin, while you are facing an issue with Woo Payments. Given the nature of your concerns, I recommend reaching out directly to WooCommerce Support for more tailored assistance. They have the necessary tools and knowledge to address issues related to their payment gateways, notification systems, and overall functionality. You can create a support ticket with them here:

https://woocommerce.com/my-account/create-a-ticket/

Kind Regards,
Krystian
