### ISSUE TITLE
PayPal Pay Later Button Shows but does not give Pay Later option

### ISSUE THREAD

**Issue by vmannusa** [woocommerce/woocommerce-paypal-payments#2044]
### Describe the Bug

With "Pay Later" Enabled, the button does show successfully. However, when you actually click the button and log into Paypal, it gives the same options as if you just clicked "PayPal". It should actually give the option for "Pay Later"

### To Reproduce

1. Go to (https://houstonpikappalumni.com/)
2. Click on 'Frontier Fiesta'
3. Scroll down to 'Pi Kapp Undergrad Package' and click "Add to Cart"
4. Click "Proceed to checkout"
5. Fill out form on left hand side.
6. View payment options on right hand side. Paypal, Venmo, Pay Later, Debit Or Credit Card
7. Click "Pay Later"
8. Log into Paypal
9. View options. Pay in 4 option does not show. Validated that it does show on other websites I.E. Target.com (to rule out issue with my paypal account).

### Screenshots
Pay Later "Enabled" 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/279e7f0c-e3e1-4a80-8bce-3821110ea289)

Pay Later option shows on page

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/431204d6-952c-4100-8ec3-9cd9d81295a1)

### Expected Behavior

Should show up as below like seen on Target.com after logging into Paypal
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/ca48b479-544f-4d40-bcba-016a616e8d42)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/79b8121b-d761-4dec-b4f9-fa45fcb10ef2)

### Actual Behavior

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/431204d6-952c-4100-8ec3-9cd9d81295a1)

Does not show pay in 4 option when clicking "Pay Later"
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/bb6f942c-5dbb-43e6-8a64-4c981b0ac708)

If you just click "Paypal" it show's the same exact screen.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/48462046/08cb60a0-36b1-425c-bbcf-c408fb47755f)

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version Google Chrome
 - Any other plugins installed

### Additional Details

<html>
<body>

ordPress environment
--
WordPress address (URL): |   | https://houstonpikappalumni.com
Site address (URL): |   | https://houstonpikappalumni.com
WooCommerce version: |   | 8.6.1
WooCommerce REST API package: |   | 8.6.1 /home/housmmbv/public_html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package: |   | 11.7.0 /home/housmmbv/public_html/wp-content/plugins/woo-gutenberg-products-block/
Action Scheduler package: |   | 3.7.1 /home/housmmbv/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | /home/housmmbv/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 6.4.3
WordPress multisite: |   |  
WordPress memory limit: |   | 1 GB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</body>
</html>

</details>
ordPress environment
WordPress address (URL):		https://houstonpikappalumni.com
Site address (URL):		https://houstonpikappalumni.com
WooCommerce version:		8.6.1
WooCommerce REST API package:		 8.6.1 /home/housmmbv/public_html/wp-content/plugins/woocommerce/includes
WooCommerce Blocks package:		 11.7.0 /home/housmmbv/public_html/wp-content/plugins/woo-gutenberg-products-block/
Action Scheduler package:		 3.7.1 /home/housmmbv/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable:		 /home/housmmbv/public_html/wp-content/uploads/wc-logs/
WordPress version:		6.4.3
WordPress multisite:		
WordPress memory limit:		1 GB
WordPress debug mode:		–
WordPress cron:		
Language:		en_US
External object cache:		–
Server environment
Server info:		LiteSpeed
PHP version:		7.4.33
PHP post max size:		1 GB
PHP time limit:		1500
PHP max input vars:		2000
cURL version:		7.87.0, OpenSSL/1.1.1w
SUHOSIN installed:		–
MySQL version:		5.5.5-10.6.16-MariaDB-cll-lve-log
Max upload size:		1 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		

Database
 Missing base tables: wpqt_wc_orders, wpqt_wc_orders_meta. Some WooCommerce functionality may not work as expected.
WooCommerce database version:		8.6.1
Database prefix	 	wpqt_
Total Database Size	 	9.18MB
Database Data Size	 	7.56MB
Database Index Size	 	1.62MB
wpqt_woocommerce_sessions	 	Data: 0.19MB + Index: 0.01MB + Engine MyISAM
wpqt_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_attribute_taxonomies	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_order_items	 	Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpqt_woocommerce_order_itemmeta	 	Data: 0.52MB + Index: 0.23MB + Engine MyISAM
wpqt_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_shipping_zones	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_shipping_zone_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_shipping_zone_methods	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_payment_tokens	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_payment_tokenmeta	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_actionscheduler_actions	 	Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wpqt_actionscheduler_claims	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_actionscheduler_groups	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_actionscheduler_logs	 	Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpqt_blogmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_blogs	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_commentmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_comments	 	Data: 0.14MB + Index: 0.06MB + Engine MyISAM
wpqt_gla_attribute_mapping_rules	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_gla_budget_recommendations	 	Data: 0.10MB + Index: 0.10MB + Engine MyISAM
wpqt_gla_merchant_issues	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_gla_shipping_rates	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_gla_shipping_times	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_jetpack_sync_queue	 	Data: 0.42MB + Index: 0.04MB + Engine MyISAM
wpqt_links	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_litespeed_url	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_litespeed_url_file	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_options	 	Data: 2.71MB + Index: 0.11MB + Engine MyISAM
wpqt_postmeta	 	Data: 1.58MB + Index: 0.64MB + Engine MyISAM
wpqt_posts	 	Data: 1.22MB + Index: 0.12MB + Engine MyISAM
wpqt_registration_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_signups	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_site	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_sitemeta	 	Data: 0.37MB + Index: 0.01MB + Engine MyISAM
wpqt_tec_events	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_tec_occurrences	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_termmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_terms	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_term_relationships	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_term_taxonomy	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_usermeta	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpqt_users	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_wc_admin_notes	 	Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_admin_note_actions	 	Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wpqt_wc_category_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_customer_lookup	 	Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpqt_wc_download_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_mnm_child_items	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_order_addresses	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_order_coupon_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_order_operational_data	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_order_product_lookup	 	Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wpqt_wc_order_stats	 	Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wpqt_wc_order_tax_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_product_attributes_lookup	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_product_download_directories	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_wc_product_meta_lookup	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_wc_rate_limits	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_reserved_stock	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqt_wc_tax_rate_classes	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqt_wc_webhooks	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
Post Type Counts
attachment	 	105
custom_css	 	1
customize_changeset	 	1
elementor_library	 	1
feedback	 	201
nav_menu_item	 	8
oembed_cache	 	1
page	 	13
post	 	3
ppdgorder	 	70
ppec-products	 	2
product	 	22
product_variation	 	3
revision	 	220
shop_coupon	 	32
shop_order	 	363
shop_order_refund	 	3
tribe_events	 	1
tribe_venue	 	1
wp_global_styles	 	1
wpplugin_evt_button	 	1
wpsc_cart_orders	 	4
Security
Secure connection (HTTPS):		
Hide errors from visitors	
	
Active plugins (22)
Google Listings and Ads	 	by WooCommerce – 2.5.18
[Jetpack](https://jetpack.com/)	 	by Automattic – 13.1.2
[Product Input Fields for WooCommerce](https://www.tychesoftwares.com/store/premium-plugins/product-input-fields-for-woocommerce/)	 	by Tyche Softwares – 1.8.1
[WooPayments](https://woo.com/payments/)	 	by Automattic – 7.2.0
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	 	by WooCommerce – 2.5.3
[WooCommerce](https://woo.com/)	 	by Automattic – 8.6.1
[WP Simple Shopping cart](https://www.tipsandtricks-hq.com/wordpress-simple-paypal-shopping-cart-plugin-768)	 	by Tips and Tricks HQ, Ruhul Amin, mra13 – 5.0.3
[Options for Twenty Twenty-One](https://webd.uk/product/options-for-twenty-twenty-one-upgrade/)	 	by Webd Ltd – 1.7.3
[UpdraftPlus - Backup/Restore](https://updraftplus.com/)	 	by UpdraftPlus.Com, DavidAnderson – 1.23.16
[Jetpack](https://jetpack.com/)	 	by Automattic – 13.1.2
[WP Express Checkout](https://wp-express-checkout.com/)	 	by Tips and Tricks HQ – 2.3.7
[WPC Grouped Product for WooCommerce](https://wpclever.net/)	 	by WPClever – 4.4.0
[WooCommerce Blocks](https://github.com/woocommerce/woocommerce-gutenberg-products-block)	 	by Automattic – 11.7.0
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	 	by WooCommerce – 2.5.3
[Payment Gateway Plugin for PayPal WooCommerce ( Free )](https://wordpress.org/plugins/express-checkout-paypal-payment-gateway-for-woocommerce/)	 	by WebToffee – 1.8.4
[Flexible Checkout Fields](https://www.wpdesk.net/products/flexible-checkout-fields-pro-woocommerce/)	 	by WP Desk – 4.1.0
[WooPayments](https://woo.com/payments/)	 	by Automattic – 7.2.0
[WooCommerce](https://woo.com/)	 	by Automattic – 8.6.1
Advanced Order Export For WooCommerce	 	by AlgolPlus – 3.4.5
[WooCommerce Mix and Match Products](http://www.woocommerce.com/products/woocommerce-mix-and-match-products/)	 	by Kathy Darling – 2.6.1
[Akismet Anti-spam: Spam Protection](https://akismet.com/)	 	by Automattic - Anti-spam Team – 5.3.1
[Duplicate Page](https://wordpress.org/plugins/duplicate-page/)	 	by mndpsingh287 – 4.5.3
Inactive plugins (3)
[LiteSpeed Cache](https://www.litespeedtech.com/products/cache-plugins/wordpress-acceleration)	 	by LiteSpeed Technologies – 6.1
The Events Calendar	 	by The Events Calendar – 6.3.2
WooCommerce PayPal Checkout Gateway	 	by WooCommerce – 2.1.3
Settings
API enabled:		–
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), mix and match (mix-and-match), simple (simple), subscription (subscription), variable (variable), variable subscription (variable-subscription), woosg (woosg)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to Woo.com:		
Enforce Approved Product Download Directories:		–
HPOS feature screen enabled:		–
HPOS enabled:		–
Order datastore:		WC_Order_Data_Store_CPT
HPOS data sync enabled:		–
WooCommerce pages
Shop base:		 Page not set
[Cart](https://houstonpikappalumni.com/wp-admin/post.php?post=325&action=edit):		#325 - /cart/
[Checkout](https://houstonpikappalumni.com/wp-admin/post.php?post=326&action=edit):		#326 - /checkout-2/
My account:		 Page not set
Terms and conditions:		 Page not set
Theme
Name:		Twenty Twenty-One
Version:		2.1
Author URL:		https://wordpress.org/
Child theme:		 – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: [How to create a child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/)
WooCommerce support:		
Templates
Overrides:	 	–
WooPayments
Version:		7.2.0
Connected to WPCOM:		Yes
WPCOM Blog ID:		195880068
Account ID:		acct_1KLdlJ2EF7HEO0gY
Payment Gateway:		 Needs setup
Test Mode:		Disabled
Enabled APMs:		card
WooPay Express Checkout:		Disabled
WooPay Incompatible Extensions:		No
Apple Pay / Google Pay Express Checkout:		Enabled (product,cart,checkout)
Fraud Protection Level:		basic
Multi-currency:		Enabled
Public Key Encryption:		Disabled
Auth and Capture:		Enabled
Documents:		Disabled
Logging:		Disabled
Mix and Match Products
Version:	 	2.6.1
Database Version:	 	2.6.1
Template Overrides:	 	–
WooCommerce PayPal Payments
Onboarded		
Shop country code		US
WooCommerce currency supported		
Advanced Card Processing available in country		
Pay Later messaging available in country		
Webhook status		–
PayPal Vault enabled		–
ACDC Vault enabled		–
Logging enabled		–
Reference Transactions		–
Used PayPal Checkout plugin		
Subscriptions Mode		Disabled
Admin
Enabled Features:		activity-panels, analytics, product-block-editor, coupons, core-profiler, customer-effort-score-tracks, import-products-task, experimental-fashion-sample-products, shipping-smart-defaults, shipping-setting-tour, homescreen, marketing, mobile-app-banner, navigation, onboarding, onboarding-tasks, product-variation-management, product-virtual-downloadable, product-external-affiliate, product-grouped, product-linked, remote-inbox-notifications, remote-free-extensions, payment-gateway-suggestions, shipping-label-banner, subscriptions, store-alerts, transient-notices, woo-mobile-welcome, wc-pay-promotion, wc-pay-welcome-page
Disabled Features:		customize-store, minified-js, new-product-management-experience, product-pre-publish-modal, settings, async-product-editor-category-field
Daily Cron:		 Next scheduled: 2024-02-21 00:44:23 +00:00
Options:		
Notes:		190
Onboarding:		completed
Action Scheduler
Version:	3.7.1
Data store:	ActionScheduler_DBStore
Action Status	 	Count	Oldest Scheduled Date	Newest Scheduled Date
Complete	 	114	2024-01-21 15:47:10 +0000	2024-02-20 19:09:38 +0000
Failed	 	11	2023-02-23 19:17:41 +0000	2023-07-08 17:31:14 +0000
Pending	 	2	2024-02-21 06:44:11 +0000	2024-02-21 06:44:11 +0000
Status report information
Generated at:	 	2024-02-20 19:09:52 +00:00

**Comment by ghost** [comment]
i have the same problem and the button Paylater not visible (country who accept Paypal later) and i have this bug since decembre 2023.... GooglePay is visible, but not Paylater, all plugin and template are ok, no problems, just this plugin and error, the same bug of this topic : https://wordpress.org/support/topic/paylaterblockmodule-not-found-error/
very bored :/

**Comment by SydeKrystian** [comment]
Hello @vmannusa 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
