### ISSUE TITLE
Payments Page 504 error

### ISSUE THREAD

**Issue by DragonEnergy** [woocommerce/woocommerce-paypal-payments#2046]
### To Reproduce

1. Install plugin and activate
2. Go to WooCommerce > Settings > Payments

 - WordPress Version Current version: 6.4.3
 - WooCommerce Version Version 8.6.1 
 - Plugin Version Version 2.5.3

### Additional Details

When clicked on PAyments page in woocommerce redirect url:
/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-connection

**Comment by SydeKrystian** [comment]
Hello @DragonEnergy 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
