### ISSUE TITLE
WooCommerce PayPal Payments Plugin failure

### ISSUE THREAD

**Issue by rvargasz** [woocommerce/woocommerce-paypal-payments#2047]
### WooCommerce PayPal Payments Plugin

The standard card payment button does not appear on my online store page

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

![Paypal Woocommerce fallo 10](https://github.com/woocommerce/woocommerce-paypal-payments/assets/42255573/a8368798-46ae-4253-a071-4ac8f8b833bb)

![Paypal Woocommerce fallo 2](https://github.com/woocommerce/woocommerce-paypal-payments/assets/42255573/83d696aa-bd0d-406e-b012-ff8850653053)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by rvargasz** [comment]
The standard card payment option was activated and the button does not appear on my online store page

**Comment by SydeKrystian** [comment]
Hello @rvargasz 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Regarding your problem: 

Currently, our plugin does not offer support in block checkout for all plugin features. Specifically, only PayPal Express buttons, Pay Later, Venmo, Apple Pay, & Google Pay buttons can be used on the Block Cart and the Block Express Checkout, as detailed in our documentation [here](https://woo.com/document/woocommerce-paypal-payments/#woocommerce-blocks). To ensure full compatibility with all features of our plugin, I recommend changing your checkout page to the regular/default setting. Here are the steps to do this:

1. Go to the "Edit page".
2. Click on the three horizontal dots in the right corner.
3. Choose "Code editor".
4. Remove any existing code.
5. Enter [woocommerce_checkout]


Should you require any further assistance, or if you have any more questions, please don't hesitate to reach out via support ticket. 

Kind Regards,
Krystian
