### ISSUE TITLE
Random Button on WooCommerce with PayPal Plugin

### ISSUE THREAD

**Issue by Emma-SWL** [woocommerce/woocommerce-paypal-payments#2059]
![Screenshot_20240226-201849](https://github.com/woocommerce/woocommerce-paypal-payments/assets/161380194/528a29fe-1709-4a05-b151-9743c4ee1a06)

 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1
 - Plugin Version 2.5.3
 - Browser Chrome 121.0.6167.180
 - Any other plugins installed I use Payment Plugin for Stripe and their support desk told me the issue was with PayPal plugin

**Comment by Emma-SWL** [comment]
Button disappears when I deactivate the PayPal plugin

**Comment by SydeKrystian** [comment]
Hello @Emma-SWL 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
