### ISSUE TITLE
Does not add cost of Add On products 

### ISSUE THREAD

**Issue by smaniec** [woocommerce/woocommerce-paypal-payments#2061]
I have optional add-ons at checkout (faster shipping for example). The cost of it is reflected in the order details on the right, however when you chose pay pal or a credit card option to checkout, the plug in only grabs the subtotal value (which does not include the selected cost of the add on). It completely ignores the extra costs

**Comment by SydeKrystian** [comment]
Hello @smaniec 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
