### ISSUE TITLE
PAYPAL

### ISSUE THREAD

**Issue by ABOadel2000** [woocommerce/woocommerce-paypal-payments#2063]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @ABOadel2000 

I'm closing this bug request due to a lack of content.

Kind regards,
Krystian
