### ISSUE TITLE
Incorrect Early Initialization of `wptexturize()` (652)

### ISSUE THREAD

**Issue by magnuskl** [woocommerce/woocommerce-paypal-payments#2064]
### Describe the Bug

Within the `plugins_loaded` action, that is, before the `init` hook, `wptexturize()` is indirectly invoked through a call to `get_plugin_data()`, with default `$markup` and `$translate` parameters set to `true`. See [woocommerce-paypal-payments.php#L100](https://github.com/woocommerce/woocommerce-paypal-payments/blob/a06da46e33e7bdaf525cebca5aee7413d67979ca/woocommerce-paypal-payments.php#L100). This early invocation leads to the setting of `wptexturize()`’s static variables, such as `$opening_single_quote` and `$closing_single_quote`, based on the default locale instead of the site’s actual locale, which may cause unexpected behavior in text formatting across the site, particularly in locales that differ from the default.

### To Reproduce

1. Set up a WordPress site with non-English locale.
2. Install and activate WooCommerce and WooCommerce PayPal Payments.
3. Use WP-CLI to run the following command in the terminal: `wp eval "echo wptexturize('This is a \"test\".');"`
4. Observe that the output reflects the default locale’s quotation marks instead of the site’s actual locale’s quotation marks, indicating that `wptexturize()` was initialized prematurely with the default locale settings.

### Screenshots

Not applicable.

### Expected Behavior

`wptexturize()` should respect the site’s actual locale when formatting text, including the correct opening and closing quotation marks.

### Actual Behavior

`wptexturize()` uses the default locale when formatting text, disregarding the site’s actual locale.

### Environment

- WordPress 6.4.3
- WooCommerce 8.6.3
- WooCommerce PayPal Payments 2.5.4
- No other plugins installed.

### Additional Details

The bug seems related to [another bug](https://wordpress.org/support/topic/quotation-marks-modified/) affecting Mollie Payments for WooCommerce.

**Comment by magnuskl** [comment]
There is an offending call to `get_plugin_data()` in [FilePathPluginFactory.php#L68](https://github.com/woocommerce/woocommerce-paypal-payments/blob/a06da46e33e7bdaf525cebca5aee7413d67979ca/src/FilePathPluginFactory.php#L68), too, by the way. A workaround is to set the `$markup` and `$translate` parameters to `false`, preventing the early invocation of `wptexturize()`.

**Comment by InpsydeNiklas** [comment]
Hi @magnuskl, thanks for sharing your findings. This certainly will be helpful for the ongoing investigation into multiple plugins with the reported behavior.

**Comment by InpsydeNiklas** [comment]
@magnuskl From what I can tell, the workaround should not have any negative consequences, so that's what we're going with for PayPal Payments 2.6.1. It will eventually also find its way into a few more plugins. Thanks again for sharing your findings!
Here is a link to the related core issue: https://core.trac.wordpress.org/ticket/49965

**Comment by magnuskl** [comment]
No problem. I am glad that this issue could be resolved.
