### ISSUE TITLE
Replace the middleware URL from `connect.woocommerce.com` to `api.woocommerce.com/integrations` (2721)

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/woocommerce-paypal-payments#2067]
The `connect.woocommerce.com` server is due to be retired. The `api.woocommerce.com`  server now provides the connect service. The base URL will now be `api.woocommerce.com/integrations`. All other endpoints should now be accessible from the base URL.

## Endpoints

- [ ] `/ppc/v2/checkout/orders`
- [ ] `/ppc/v2/checkout/orders/{orderId}`
- [ ] `/ppc/v2/checkout/orders/{orderId}`
- [ ] `/ppc/v2/checkout/orders/{orderId}/capture`
- [ ] `/ppc/v2/checkout/orders/{orderId}/authorize`
- [ ] `/ppc/v2/payments/authorizations/{authorizationId}`
- [ ] `/ppc/v2/payments/authorizations/{authorizationId}/capture`
- [ ] `/ppc/v2/customer/partner-referrals`
- [ ] `/ppcsandbox/v2/checkout/orders`
- [ ] `/ppcsandbox/v2/checkout/orders/{orderId}`
- [ ] `/ppcsandbox/v2/checkout/orders/{orderId}`
- [ ] `/ppcsandbox/v2/checkout/orders/{orderId}/capture`
- [ ] `/ppcsandbox/v2/checkout/orders/{orderId}/authorize`
- [ ] `/ppcsandbox/v2/payments/authorizations/{authorizationId}`
- [ ] `/ppcsandbox/v2/payments/authorizations/{authorizationId}/capture`
- [ ] `/ppcsandbox/v2/customer/partner-referrals`

**Comment by ibndawood** [comment]
Hello @Dinamiko, were you able to test all the endpoints and validate the responses?

**Comment by Dinamiko** [comment]
Hello @ibndawood, the plugin only does 4 calls to `partner-referrals` endpoint using the WooCommerce host to get the signup links, once the merchant is onboarded on PayPal and we have the access token we use the PayPal host for all requests.
```
POST https://api.woocommerce.com/integrations/ppc/v2/customer/partner-referrals
POST https://api.woocommerce.com/integrations/ppc/v2/customer/partner-referrals
POST https://api.woocommerce.com/integrations/ppcsandbox/v2/customer/partner-referrals
POST https://api.woocommerce.com/integrations/ppcsandbox/v2/customer/partner-referrals 
```

We have tested and validated responses for the above 4 requests.

**Comment by ibndawood** [comment]
Thank you, @Dinamiko, for the confirmation. We'll set up rewrites in the `connect.woocommerce` server for the `ppc` endpoints for backward compatibility.

**Comment by ibndawood** [comment]
We've setup rewrites in the `connect.woocommerce.com`. Old plugin pinging the old URL will be served from `api.woocommerce.com`.
