### ISSUE TITLE
Undefined property: stdClass::$authentication_result

### ISSUE THREAD

**Issue by deeminzen** [woocommerce/woocommerce-paypal-payments#2070]
### Describe the Bug

wp-content/debug.log is showing this.
[29-Feb-2024 22:16:09 UTC] PHP Notice:  Undefined property: stdClass::$authentication_result in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Helper/ThreeDSecure.php on line 73

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1
 - Plugin Version. WooCommerce PayPal Payments | Version 2.5.4 by WooCommerce \| Auto-updates enabled
 - Browser [e.g. Chrome, Safari] and Version n/a
 - Any other plugins installed
Admin Menu Editor | Version 1.12.1 by Janis Elsts \| Auto-updates enabled
Advanced Coupons for WooCommerce Free | Version 4.5.9.2 by Rymera Web Co \| Auto-updates disabled
Back In Stock Notifier for WooCommerce \| WooCommerce Waitlist Pro | Version 5.2.2 by codewoogeek \| Auto-updates enabled
CartBounty - Save and recover abandoned carts for WooCommerce | Version 8.0.1 by Streamline.lv \| Auto-updates enabled
Classic Widgets | Version 0.3 by WordPress Contributors \| Auto-updates enabled
Column Shortcodes | Version 1.0.1 by Codepress \| Auto-updates disabled
Contact Form 7 | Version 5.8.7 by Takayuki Miyoshi \| Auto-updates enabled
Customizer For WooCommerce PDF Invoices | Version 1.0.2 by Webtoffee \| Auto-updates disabled
Custom Shipping Methods for WooCommerce Pro | Version 1.8.0 by Imaginate Solutions \| Auto-updates enabled
Custom YITH WooCommerce Product Add-Ons Tab | Version 1.0 by Progressus.io \| Auto-updates enabled
Disable WP Notification | Version 3.2 by Sourabh Agrawal \| Auto-updates enabled
Discount Rules Core | Version 2.6.3 by Flycart \| Auto-updates enabled
FiboSearch - AJAX Search for WooCommerce | Version 1.27.0 by FiboSearch Team \| Auto-updates enabled
Login Security Captcha | Version 1.6.0 by ScriptsTown \| Auto-updates enabled
MailPoet | Version 4.44.1 by MailPoet \| Auto-updates enabled
Members | Version 3.2.9 by MemberPress \| Auto-updates disabled
MetaSlider | Version 3.61.0 by MetaSlider \| Auto-updates enabled
Migrate Guru | Version 5.48 by Migrate Guru \| Auto-updates disabled
Order Export & Order Import for WooCommerce | Version 2.4.9 by WebToffee \| Auto-updates enabled
Phoenix Media Rename | Version 3.11.6 by crossi72 \| Auto-updates enabled
Product Import Export for WooCommerce | Version 2.4.2 by WebToffee \| Auto-updates enabled
Product Slider and Carousel with Category for WooCommerce | Version 2.8.1 by WP OnlineSupport, Essential Plugin \| Auto-updates enabled
Related Products for WooCommerce | Version 1.5.2 by WebToffee \| Auto-updates enabled
Sequential Order Numbers for WooCommerce | Version 1.6.0 by WebToffee \| Auto-updates enabled
Tricker's Shipping & Logistics | Version 1.0.1 by Progressus \| Auto-updates disabled
When Last Login | Version 1.2.2 by Yoohoo Plugins \| Auto-updates enabled
WooCommerce | Version 8.6.1 by Automattic \| Auto-updates enabled
WooCommerce PayPal Payments | Version 2.5.4 by WooCommerce \| Auto-updates enabled
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels | Version 4.4.1 by WebToffee \| Auto-updates disabled
WooCommerce PDF Invoices, Packing Slips and Credit Notes (Pro) | Version 1.1.0 by Webtoffee \| Auto-updates enabled
WooCommerce Wholesale Prices | Version 2.1.12 by Rymera Web Co \| Auto-updates enabled
Woo Discount Rules PRO 2.0 | Version 2.6.2 by Flycart \| Auto-updates enabled
WP HTML Mail - Email Template Designer | Version 3.4.5 by Hannes Etzelstorfer // codemiq \| Auto-updates enabled
WPS Hide Login | Version 1.9.13.2 by WPServeur, NicolasKulka, wpformation \| Auto-updates enabled
YITH Request a Quote for WooCommerce Premium | Version 4.22.0 by YITH \| Auto-updates disabled
YITH WooCommerce Gift Cards Premium | Version 4.10.0 by YITH \| Auto-updates disabled
YITH WooCommerce Product Add-ons & Extra Options Premium | Version 4.10.1 by YITH \| Auto-updates disabled
YITH WooCommerce Product Add-Ons Import/Export | Version 1.0 by Progressus \| Auto-updates disabled
YITH WooCommerce Product Slider Carousel | Version 1.31.0 by YITH \| Auto-updates disabled
Yoast SEO | Version 22.1 by Team Yoast \| Auto-updates enabled

**Comment by InpsydeNiklas** [comment]
Hello @deeminzen, thanks for reporting this warning. It will be resolved in the next update with the fix in the [linked pull request](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2051/files). A pre-release version with this, and additional improvements will be [available for testing from here](https://github.com/woocommerce/woocommerce-paypal-payments/releases) in the next week.
