### ISSUE TITLE
Since 2.5.4 - Many orders do not go through 

### ISSUE THREAD

**Issue by vonzurgathen** [woocommerce/woocommerce-paypal-payments#2075]
Many Orders do not go through

The payment could not be processed. Please try again or contact the shop administrator. [Error] Unknown error connecting to PayPal. Status code: 0. PayPalGateway.php:633 [Error] Unknown error connecting to PayPal. Status code: 0. OrderEndpoint.php:584 Order status changed from payment pending to failed.

We hadnt that problem with 2.5.3 and earlier..

**Comment by SydeKrystian** [comment]
Hello @vonzurgathen 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
