### ISSUE TITLE
Paypal - Credit + Debit Card failure

### ISSUE THREAD

**Issue by adryyhernandez** [woocommerce/woocommerce-paypal-payments#2078]
### Describe the Bug

Receiving error message to try again with a Paypal Account instead of being able to pay within wordpress.

### To Reproduce

1. Go to https://escuela.conayurmexico.com/courses/curso-prueba
2. Fill the information.
3. Select payment method "Credit or Debit Card"
4. After entering card information and selecting Pay $xx.xx, the error is shown.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/29684477/f08053f0-1b37-4be7-9cf7-91b2c543504b)

### Expected Behavior

Process payments within the Wordpress site without opening a Paypal Account.

### Actual Behavior

Receiving error message to try again with a Paypal Account.

### Environment

 - WordPress Version - 6.4.3
 - WooCommerce Version - 8.6.1
 - Plugin Version - 2.5.4
 - Chrome
 - Elementor, Elementor Pro, Learnpress

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @adryyhernandez 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
