### ISSUE TITLE
Paypal showing in italian

### ISSUE THREAD

**Issue by ilariaberenice** [woocommerce/woocommerce-paypal-payments#2082]
### Describe the Bug
Hello, My site is bilingual with wpml, the default language is english, if I activate the paypal option pay later, it shows the message in italian also in the deafault english version of the website, automatically.without me translating any string with wpml.
Sot it shows italian as if it were the default language instead of english
Can you help please?
thanks in advance
Ilaria
<img width="1320" alt="Screenshot 2024-03-06 alle 09 48 03" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/162429251/b5b875e1-793e-44b2-812a-f3e7fbd28a4a">
<img width="1320" alt="Screenshot 2024-03-06 alle 09 48 11" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/162429251/3b15bba9-f1c5-41a2-8c86-9542d9147389">

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @ilariaberenice 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
