### ISSUE TITLE
Ability to access $container

### ISSUE THREAD

**Issue by xlplugins** [woocommerce/woocommerce-paypal-payments#209]
Hi there, 

We are developers of WooFunnels and we are checking plugin feasibility to provide compatibility of our one click upsells with paypal payments. 

In the process we are stuck and not able to find the way to access $container object, we see its the base object use to load any dependency further, So its wont seem possible to write any compat without having access of $container. 

Could you please provide us a way to access this object ? 

Thanks

**Comment by Dinamiko** [comment]
Hello @xlplugins, 

We are working on including a way to access the plugin container from the outside, you can see the work in progress here: https://github.com/woocommerce/woocommerce-paypal-payments/pull/203

In this PR description there is a section explaining how to add modules and accessing the plugin container, will be great if you can give the PR a try to see if it works for you or something is missing, thanks.
