### ISSUE TITLE
[Error] Unknown error while connecting to Paypal. Status code:0

### ISSUE THREAD

**Issue by sreinha** [woocommerce/woocommerce-paypal-payments#2095]
### Describe the Bug

Customers who choose PayPal as payment method often can't proceed to PayPal. The loader is shown at the bottom of the checkout page and the payment button doesn't appear. The error first appeared about two weeks ago. PayPal support said that it must be an issue with the plugin.  

### To Reproduce

1. Put items into the shopping cart
2. Click on 'Go to checkout'
3. Select 'PayPal' as payment method
4. PayPal is chosen as payment method but the payment button doesn't get shown 

### Environment

 - WordPress 6.4.3
 - WooCommerce 8.6.1
 - WooCommerce PayPal Payments 2.5.4
 - Google Chrome 122.0.6261.129, Firefox 123.0.1

### Additional Details

<details><summary>System status</summary>

  
System status is good and does not show any errors.

</details>

**Comment by SydeKrystian** [comment]
Hello @sreinha 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
