### ISSUE TITLE
No aparece pagar con tarjeta

### ISSUE THREAD

**Issue by borroforro** [woocommerce/woocommerce-paypal-payments#2109]
### To Reproduce

1. Go to 'any product'
2. Click on 'on add to cart'
3. Try to 'pay with card'
4. See error 'don't show the button'

**Comment by SydeKrystian** [comment]
Hello @borroforro 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
