### ISSUE TITLE
WooCommerce PayPal Payments doesn't support the new Checkout block

### ISSUE THREAD

**Issue by solstudioim** [woocommerce/woocommerce-paypal-payments#211]
## Describe the bug
I tried to use Checkout Block for my checkout page, but it's not displayed

## To reproduce

1. Download, activate, enable [WooCommerce PayPal Payments](https://wordpress.org/plugins/woocommerce-paypal-payments/)
2. Add to cart a product
3. Checkout and see if WooCommerce PayPal Payments not shown on the checkout page

## Expected behavior
WooCommerce PayPal Payments should be shown and compatible with Checkout Block, as the built-in PayPal Standard is hidden in the latest WooCommerce versions

## Screenshots
<img width="1601" alt="Markup 2021-07-30 at 08 06 04" src="https://user-images.githubusercontent.com/17371139/127584707-35b76e83-311c-43b8-bd7b-522ca0da8e97.png">
<img width="1451" alt="Markup 2021-07-30 at 08 09 50" src="https://user-images.githubusercontent.com/17371139/127584711-8b322072-9200-43b2-81d9-7036cb7e02be.png">

### WordPress (please complete the following information):
* Core version: 5.8
* WooCommerce version: 5.5.2
* WooCommerce Blocks version: 5.5.1
* Site language: English
* WooCommerce PayPal Payments: 1.4.0

### Desktop (please complete the following information):
* OS: Mac
* Browser: Chrome
* Version: 92.0.4515.107

## Additional context
A user on the forum [requested compatibility information between WC Block and WC PayPal Payments](https://wordpress.org/support/topic/compatibility-with-recommended-paypal-plugin-from-woocommerce/?view=all)

**Comment by phillipcornwell** [comment]
another report: 33394334-hc

**Comment by thelogicwizards** [comment]
another report: [4859295-zd](4859295-zd-woothemes)

**Comment by KyleIrving** [comment]
Considering that Woo are advising users not to use PayPal Standard any more and there are no other PayPal add ons that work with WooCommerce Blocks what's the plan here?

**Comment by dweuste** [comment]
> Considering that Woo are advising users not to use PayPal Standard any more and there are no other PayPal add ons that work with WooCommerce Blocks what's the plan here?

This exactly!

**Comment by InpsydeNiklas** [comment]
Support for Cart and Checkout Blocks is planned but it will take longer than originally anticipated. When the new Blocks are no longer a feature plugin and become a core part of WooCommerce, then PayPal Payments will certainly be ready for it. But there is currently no timeframe for support of the Blocks _feature plugin_. It will eventually happen but that's all we can say for the moment.

**Comment by Marc-pi** [comment]
seems the Cart/Checkout blocks will soon to loose their "feature flag" and being activated by default within Woo Plugin !
Any news about the compatibility status https://woocommerce.com/document/cart-checkout-blocks-support-status/ ?

**At minimum, please add a badge/message within the plugin that checks compatibility and warns about incompatibilty.**
i've lost few hours to understand that the Paypal official Woo Plugin is not compatible with new Cart/Checkout blocks.

**Comment by masteradhoc** [comment]
@InpsydeNiklas any update on this? We're using Blocks already on quite some shops that are already live. How come paypal payments plugin still doesnt support the new block experience?

**Comment by Marc-pi** [comment]
FYI the checkout & cart blocks are shipped into WC Core since WC Blocks 8.3 (no more feature flag)
https://github.com/woocommerce/woocommerce-blocks/pull/6805

**Comment by InpsydeNiklas** [comment]
The Blocks integration was moved back a bit as other features had to be prioritized due to deprecation or new product launches at PayPal. It is still on the roadmap for later this year, but there are no new details as there haven't been any major developments yet. 

For now, there's an entry about the incompatibility in the [PayPal Payments FAQ](https://woocommerce.com/document/woocommerce-paypal-payments/#faq-does-paypal-payments-support-blocks), and we will share more details when available.

PayPal Standard is the best option to implement PayPal with the new Blocks Checkout for the time being.
Though the lack of support means you would be on your own if any issues arise.

**Comment by Marc-pi** [comment]
@InpsydeNiklas yes, as asked above
"At minimum, please add a badge/message within the plugin that checks compatibility and warns about incompatibilty."
should not be too hard to set, and would ease onboarding for new incomers :-) (i doubt many read the FAQ when installing the plugin from WP plugin installer, since nothing prevent them to install it even on full FSE theme :-)
WP 6.1 Final is planned for early November, and will pushed further on the FSE i.e on blocks, so should WooCommerce

**Comment by masteradhoc** [comment]
Hey @InpsydeNiklas 
Any update on this?

**Comment by InpsydeNiklas** [comment]
The team is still working on making it happen & the plans did not change. 
We'll try to let you know when there are any noteworthy updates, but that's all I can say for now.

**Comment by csmcneill** [comment]
39117895-hc

**Comment by alexsivro** [comment]
> 39117895-hc

@csmcneill What does this mean?

**Comment by ralucaStan** [comment]
@alexsivro those are some codes for requests we WC Blocks receive on other channels. @csmcneill I think that should have been added on https://github.com/woocommerce/woocommerce-blocks/issues/6816 instead

**Comment by Marc-pi** [comment]
> "At minimum, please add a badge/message within the plugin that checks compatibility and warns about incompatibilty."

done in WC Blocks 9.3 https://github.com/woocommerce/woocommerce-blocks/pull/7412

**Comment by masteradhoc** [comment]
@InpsydeNiklas any news for us?

**Comment by openmindculture** [comment]
Seriously, how can this still be incompatible in 2023? What's the point of the whole blocks / FSE / Gutenberg business, if it just doesn't work with many popular plugins and payment providers? PayPal is one of the most requested payment methods in Germany. Can anybody add support please, before I tell my customers they need to migrate and finally ditch WooCommerce for good?

**Comment by InpsydeNiklas** [comment]
Block support for PayPal Payments is in active development. More details will be shared once the release is getting closer. The first parts of the integration may be available for testing with the next feature update in late February.

It's a work in progress, and the full integration for WooCommerce Blocks also requires some tweaks to how the Blocks work. Some things unfortunately take time to get right, but you can rest assured that support for Blocks is currently the highest priority feature being worked on.

In the meantime, there are more basic integrations like PayPal Standard, or even other third-party PayPal integrations that claim to work with the Blocks checkout.

**Comment by Marc-pi** [comment]
> The first parts of the integration may be available for testing with the next feature update in late February.

Yep, hope you worked on this a little more ;-)
since woo is getting closer to be FSE ready 
keep us informed !!

**Comment by captaincourageous** [comment]
This has been 'top priority' for 2 years. I imagine Paypal is missing out on profits and maybe WooCommerce simply wants the monopoly of Stripe Payments.

I would LOVE to again be able to offer Paypal Payments and Pay Later options.

**Comment by InpsydeNiklas** [comment]
Hello everyone, and thanks for your patience.
As a heads-up, a new pre-release for the next PayPal Payments 2.0.5 update is expected to soon be available [here on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases). Please [check this document](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews) with instructions on how to get early access to the upcoming Block functionality for testing and what features to expect, once the 2.0.5 pre-release update is available to download.
The Blocks integration continues to be refined, so you can expect improvements before this functionality is officially released. [Additional features](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews#what-other-blocks-related-functionality-can-be-expected) will follow in a later update. But if you give it a try, [feedback](https://woocommerce.com/document/woocommerce-paypal-payments/#feedback) about your experience is much appreciated. Thank you!

**Comment by Dinamiko** [comment]
Implemented in #1346.

**Comment by openmindculture** [comment]
Thanks for the work and information! I will try and test it at my customers' shop soon!

**Comment by openmindculture** [comment]
Please reopen the issue, as it does not work!
WordPress: 6.2.2
WooCommerce: 7.7.0
WooCommerce Blocks: 10.2.0
WooCommerce PayPal Payments:

In the block checkout payment block options, there is the following message: Paypal is not compatible with the block checkout.

> Die folgende Erweiterung ist nicht mit dem blockbasierten Checkout kompatibel. [Weitere Informationen(öffnet in neuem Tab)](https://woocommerce.com/document/cart-checkout-blocks-support-status/)
> PayPal

![Screenshot](https://github.com/woocommerce/woocommerce-paypal-payments/assets/6377941/800a0d34-a909-462f-bd44-ef04bfdfa248)

**Comment by kampiamodikuesto** [comment]
i'm on avada and on my istance issue seems exsists. can some one confirm that this issue is fixed in 2025?
