### ISSUE TITLE
paypal pay later

### ISSUE THREAD

**Issue by caredemy** [woocommerce/woocommerce-paypal-payments#2112]
If I deactivate the blank and shop check boxes and save it, it reverts back to it being ticked, so in short I cant deactivate these 2 boxes

![WooCommerce-settings-‹-Caredemy-—-WordPress (1)](https://github.com/woocommerce/woocommerce-paypal-payments/assets/159526307/841ec3ef-bec1-41fc-8cff-ad96ef7b457a)
#![WooCommerce-settings-‹-Caredemy-—-WordPress (1)](https://github.com/woocommerce/woocommerce-paypal-payments/assets/159526307/1a6f91ea-31b7-4325-b7a9-ae9d27ace46c)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hello @caredemy, thanks for reporting this issue! We found that under certain circumstances, you may still see the previous configuration on the Pay Later settings page when saving the settings. But if you reload the page one more time (without saving), it should reflect the changes you made. Can you please let us know if reloading the page updates the values in the configurator for you? Thank you!
Note: What's displayed on the website frontend should be correct after the first save operation already.

**Comment by caredemy** [comment]
We have tried that unfortunately it reverts back and we can not change

Kind Regards

*Glenn*

*Affordable & Compliant Online Care Courses at Caredemy
<https://www.caredemy.co.uk>*

**Comment by caredemy** [comment]
Hi

Do you have an update, currently i cant disable pay later or the buttons,
so I have had to disable Paypal from the store which Is not ideal, the
refresh of page does not resolve.

Kind Regards

*Glenn*

*Affordable & Compliant Online Care Courses at Caredemy
<https://www.caredemy.co.uk>*

**Comment by InpsydeNiklas** [comment]
Hi @caredemy, you should be able to change these settings when disabling the new messaging configurator either with [this code snippet](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-pay-later-messaging-configurator-in-260) or by downgrading to the [previous plugin version 2.5.4](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.5.4).
If you need additional guidance, I recommend that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!

**Comment by samiralibabic** [comment]
I was able to change those settings one by one. If I select multiple checkboxes, it reverts back.
