### ISSUE TITLE
Paypal button is not showing up in wordpress

### ISSUE THREAD

**Issue by mrdelivermymeds** [woocommerce/woocommerce-paypal-payments#2113]
Buttons are enabled in checkout page but it is not showing up in checkout page.

**Comment by Sirvijver** [comment]
Hello @mrdelivermymeds 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any details, so it is hard to provide you with a proper response. If you are using the block checkout page, you might want to read [the documentation here](https://woo.com/document/woocommerce-paypal-payments/#woocommerce-blocks). Also be sure to check that the correct smart buttons are activated in the plugin settings.

If this doesn't help, please open a support thread as advised above.

Kind regards, 
Joost
