### ISSUE TITLE
Remove Pay Later Messaging - Settings not saving

### ISSUE THREAD

**Issue by bleulundi** [woocommerce/woocommerce-paypal-payments#2115]
### Describe the Bug

Hi there, 
I’ve set up the Paypal plugin “WooCommerce PayPal Payments”.
I want want to disable the Pay Later Messaging on the Product and Shop Pages (I only want it to show on Cart and Checkout Page).
However when I untick these options in the Pay Later settings and save, the settings go back to being ticked and still displays on the pages...

Can you help me resolve this ? 

### To Reproduce

1. Go to Woocommerce / Payments / Payment methods / PayPal
2. Click on "Pay Later" tab
3. Scroll down to "Personalize your messages"
4. Untick Product Page and Store
5. Save changes

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/164501301/5f1f0bba-b4e7-4ae0-80e6-3704d8520f48)

### Expected Behavior

I want to remove the "Pay in 4" message from the Shop and Product pages.

### Actual Behavior

After saving changes, the settings do not apply = the message still displays on the Shop and Product pages.

### Environment

 - WordPress Version : 6.4.3
 - WooCommerce Version : 8.7.0
 - Plugin Version :  2.6.0
 - Browser [e.g. Chrome, Safari] and Version : Chrome 122.0.6261.129

**Comment by InpsydeNiklas** [comment]
Hi @bleulundi you should be able to change these settings when disabling the new messaging configurator either with [this code snippet](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-pay-later-messaging-configurator-in-260) or by downgrading to the [previous plugin version 2.5.4](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.5.4).
Can you please additionally reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your WooCommerce status report? Thank you!

**Comment by bleulundi** [comment]
Hi @InpsydeNiklas,
Thank you, disabling the Pay Later messaging Configurator (using the code snippet) worked for me !

**Comment by Cypherous** [comment]
Heya this still isn't fixed and your code snippet doesn't tell me where to actually put it

You guys said this would be fixed in 2.6.2 but its still an issue in 2.7.0, any update on this?

**Comment by soulshakepower** [comment]
Yeah still happening in 2.7.1, and the code snippet creates an fatal error.. please fix this issue! Thanks

**Comment by erdalcicek** [comment]
You can hide the pay later text with the css below.

`.ppcp-messages{
	display:none !important;
}`

**Comment by Cypherous** [comment]
> You can hide the pay later text with the css below.
> 
> `.ppcp-messages{ display:none !important; }`

Right, but that will hide them everywhere, sure its a bandaid fix for the problem but an actual solution would be far better as you might want the messaging to appear in some locations

**Comment by david101design** [comment]
The toggle controls as of 2.8.1 do not work in Firefox, but they do work in Chrome.

**Comment by glennbarrett** [comment]
This is still not working on version 2.9.2

**Comment by maxmichels** [comment]
Can someone re-open this issue? It is still not possible to change the settings where to display the Snippet. Real bummer.

**Comment by Monishamacharla** [comment]
The issue still persists, can someone please check on this?

**Comment by cyberpepe14** [comment]
The issue remains unresolved and it's quite annoying. Could someone please look into it?

**Comment by soulshakepower** [comment]
In my case I managed to save the settings by disabling Siteground's "Speed Optimizer" plugin.
I manage multiple websites hosted on Siteground and that caching plugin somehow prevented me to save the settings.
I reactivated the plugin once the settings where saved and it worked. First time I had such behavior with a caching plugin, as I reported on the plugin's WP.org support section.. If this can help someone here..

**Comment by cyberpepe14** [comment]
> In my case I managed to save the settings by disabling Siteground's "Speed Optimizer" plugin. I manage multiple websites hosted on Siteground and that caching plugin somehow prevented me to save the settings. I reactivated the plugin once the settings where saved and it worked. First time I had such behavior with a caching plugin, as I reported on the plugin's WP.org support section.. If this can help someone here..

Great! It seems the "Redis Object Cache" plugin was the culprit. After disabling it, the "Pay Later" options from PayPal started working correctly. Thanks for the tip, @soulshakepower!

**Comment by PartPurple** [comment]
I'm still experiencing this issue. I'm running plugin version 2.9.6, WooCommerce 9.7.1, WordPress 6.7.2, and no caching plugins to tweak. Anybody have word on a fix? (Hiding them with CSS works for now.)

**Comment by sitoagency** [comment]
Same issue here while using Firefox, in console I read the following error. No issues in Chrome. All systems and softwares up to date.

`TypeError: can't access property "enabled", this.defaultSettings.appswitch is undefined
    shouldEnableAppSwitch Renderer.js:255
    i Renderer.js:181
    renderButtons Renderer.js:231
    render Renderer.js:65
    s gateway-settings.js:162
    h gateway-settings.js:398
    s gateway-settings.js:172
    <anonymous> gateway-settings.js:537
    p gateway-settings.js:273
[gateway-settings.js:168:13](webpack://ppcp-wc-gateway/resources/js/gateway-settings.js)
    s gateway-settings.js:168
    h gateway-settings.js:398
    s gateway-settings.js:172
    <anonima> gateway-settings.js:537
    p gateway-settings.js:273`

**Comment by PatH007** [comment]
I'm still experiencing this issue (version 3.2.1).
I used 
`.ppcp-messages{ display:none !important; }`
And it helped !

**Comment by pixelshrink** [comment]
This is still happening, the CSS does hide the message but please can we fix it so the message isn't displayed.

**Comment by numbersixnz** [comment]
This is still happening with the following configuration:

- Plugin version 3.4.0
- Wordpress 6.9.1
- Woocommerce 10.5.1

All caches are cleared, all Siteground plugins are disabled.

Plugin owner, you really need to sort this out.  Having this persistent bug for this many years is a very poor user experience.
