### ISSUE TITLE
Paypal setup

### ISSUE THREAD

**Issue by hplanger** [woocommerce/woocommerce-paypal-payments#2116]
### To Reproduce

1. Go to payments section 
2. Finish setup PayPal payment
3. Final setup setting show just for one second. Reload and the page on payments section to setup the final paypal payment just show the final setup section for just a monet and is jumping back Activae Paypal, but the activation is  done already.'…'

### Screenshots

Not possible as page is not showing long enough

C

**Comment by Sirvijver** [comment]
Hello @hplanger 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

To give you a quick response here: this is not an issue we are seeing much (or at all) with our last release, so we expect this to be an environment or account issue and I would advise you to do the following:
- You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
- Try onboarding with a sandbox account, if this works, you might want to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to ask them to review your account for any possible issues.

If none of this helps you isolate the cause of this issue, please open a support request and we will try to help you further.

Kind regards, 
Joost
