### ISSUE TITLE
Pay later messaging doesn't work

### ISSUE THREAD

**Issue by AleBTstudio** [woocommerce/woocommerce-paypal-payments#2117]
### Paypal Pay Later messages doesn't appear

In Pay Later Tab when I try to enable messaging I can't see the messages in product page. If I try to change some options how to show the messages, after click to save button all settings don't change.

### the error is in backend of site. In front end pay later messages doesn't appear. url: lolatee.it

1. Go to 'pay later tab'
2. Click on 'customizing banner'
3. try to change some setting
4. click to save and all doesn't change

### Screenshots
<img width="1193" alt="Screenshot 2024-03-24 alle 19 01 17" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/148642506/5ae5f816-97f2-4445-add6-e315ebedb2d1">

### Expected Behavior

I need to show paylater messages with 3 rates

### Actual Behavior

Now nothing appears

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.7.0
 - Plugin Version 2.6.0
 - Browser firefox

### Additional Details
`
### WordPress Environment ###

WordPress address (URL): https://lolatee.it
Site address (URL): https://lolatee.it
WC Version: 8.7.0
REST API Version: ✔ 8.7.0
Action Scheduler Version: ✔ 3.7.2
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.3.3
PHP Post Max Size: 150 MB
PHP Time Limit: 600
PHP Max Input Vars: 12000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.36
Max Upload Size: 150 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.7.0
WC Database Prefix: wp_
Dimensione totale database: 23.78MB
Dimensione dati database: 21.59MB
Dimensione indice database: 2.19MB
wp_woocommerce_sessions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 0.09MB + indice: 0.11MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 0.08MB + indice: 0.03MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_fusion_form_entries: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_fusion_form_fields: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_fusion_form_submissions: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_fusion_forms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_mailchimp_carts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_mailchimp_jobs: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_options: Dati: 14.39MB + indice: 0.13MB + motore InnoDB
wp_post_smtp_logmeta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_post_smtp_logs: Dati: 0.17MB + indice: 0.00MB + motore InnoDB
wp_postmeta: Dati: 0.14MB + indice: 0.14MB + motore InnoDB
wp_posts: Dati: 5.48MB + indice: 0.06MB + motore InnoDB
wp_raneri_danea_scheduled: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_term_relationships: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_termmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_usermeta: Dati: 0.03MB + indice: 0.03MB + motore InnoDB
wp_users: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.05MB + indice: 0.02MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_addresses: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_operational_data: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wc_order_stats: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_orders: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_wc_orders_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yoast_indexable: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_yoast_indexable_hierarchy: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_yoast_migrations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_yoast_primary_term: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_yoast_seo_links: Dati: 0.02MB + indice: 0.03MB + motore InnoDB

### Post Type Counts ###

attachment: 53
customize_changeset: 1
fusion_element: 1
fusion_form: 2
fusion_tb_section: 1
fusion_template: 1
nav_menu_item: 15
page: 11
post: 3
product: 11
product_variation: 48
revision: 130
shop_coupon: 1
shop_order: 3
slide: 1
wp_navigation: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Click to Chat: di HoliThemes – 3.34
Contact Form 7: di Takayuki Miyoshi – 5.9.3
Yoast Duplicate Post: di Enrico Battocchi & Team Yoast – 4.5
Flexible Shipping: di Octolize – 4.24.17
Avada Builder: di ThemeFusion – 3.11.7
Avada Core: di ThemeFusion – 5.11.7
iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more: di iubenda – 3.10.1
Mailchimp for WooCommerce: di Mailchimp – 3.7
Post SMTP: di Post SMTP – 2.8.11
Danea Easyfatt Import/Export: di Riccardo Raneri – 2.31.0
W3 Total Cache: di BoldGrid – 2.7.0
WooCommerce PayPal Payments: di WooCommerce – 2.6.0
WooCommerce: di Automattic – 8.7.0
Yoast SEO: di Team Yoast – 22.3

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

WordPress automation by Installatron: di  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 giorni
Level threshold: –
Log directory size: 27 KB

### WC Pages ###

Shop base: #10 - /negozio/
Carrello: #11 - /carrello/
Pagamento: #12 - /pagamento/
Il mio account: #13 - /mio-account/
Termini e condizioni: #231 - /termini-condizioni/

### Theme ###

Name: Avada
Version: 7.11.7
Author URL: https://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un tema child. Vedi: Come creare un tema child

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-pre-publish-modal
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-03-25 14:14:16 +01:00
Options: ✔
Notes: 73
Onboarding: completed

### Action Scheduler ###

Completato: 236
Oldest: 2024-02-23 16:32:14 +0000
Newest: 2024-03-24 15:56:56 +0000

Operazione non riuscita: 3
Oldest: 2023-10-16 14:16:59 +0000
Newest: 2024-03-23 16:47:53 +0000

In attesa: 1
Oldest: 2024-03-25 15:42:05 +0000
Newest: 2024-03-25 15:42:05 +0000

### Status report information ###

Generated at: 2024-03-24 19:03:13 +01:00
`

**Comment by InpsydeNiklas** [comment]
Hi @AleBTstudio, you should be able to change the Pay Later settings when disabling the new messaging configurator either with [this code snippet](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-pay-later-messaging-configurator-in-260) or by downgrading to the [previous plugin version 2.5.4](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.5.4).

As this appears to be the same issue as reported in #2112, I will close this one. If you need additional guidance or want to try a new plugin version that should resolve the issue, I recommend that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). 
Thank you!
