### ISSUE TITLE
[WPML] Not possible to translate the "Pay via PayPal" text (223)

### ISSUE THREAD

**Issue by diiegopereira** [woocommerce/woocommerce-paypal-payments#2119]
### Describe the Bug
Hi there, this is Diego from the WPML Compatibility team.

We got several tickets in our support forum from clients trying to translate the "Pay via Paypal"string from the plugin, which is not working as expected.

Some examples:
- https://wpml.org/forums/topic/cannot-translate-woocommerce-paypal-payments-title-and-description/
- https://wpml.org/forums/topic/i-want-to-translate-woocommerce-paypal-payments-strings/
- https://wpml.org/forums/topic/pay-via-paypal-not-translate-woocommerce-paypal-payments/

We tried to reproduce in a clean install but it was not possible, so it seems that this issue only happens in specific scenarios.

### Workaround
We created the following errata with the details and a workaround: https://wpml.org/errata/woocommerce-paypal-payments-pay-via-paypal-translation-not-working/

These are the steps:
- Go the "Translate texts in admin screens"page and register/translate the title and description strings from the "admin_texts_woocommerce-ppcp-settings" textdomain
- Open the app/public/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Settings/Settings.php file
- Look for the following snippet, around line 134
```php
foreach ( $defaults as $key => $value ) {
			if ( isset( $this->settings[ $key ] ) ) {
				continue;
			}
			$this->settings[ $key ] = $value;
		}
```
Replace with:
```php
foreach ( $defaults as $key => $value ) {
			if ( isset( $this->settings[ $key ] ) ) {
				// WPML workaround for compsupp-7085
				$this->settings[$key] = apply_filters('wpml_translate_single_string', $this->settings[$key] , 'admin_texts_woocommerce-ppcp-settings', '[woocommerce-ppcp-settings]'.$key);
				continue;
			}
			$this->settings[ $key ] = $value;
		}
```
- Note that we are just applying the wpml_translate_single_string filter there. See https://wpml.org/wpml-hook/wpml_translate_single_string/

### Solution Idea
Maybe it would be possible to add a generic filter there? This way, users could use this filter to translate the string without having to modify the original code. Something like this:
```php
foreach ( $defaults as $key => $value ) {
			if ( isset( $this->settings[ $key ] ) ) {
				// WPML workaround for compsupp-7085
				$this->settings[$key] = apply_filters('woocommerce_paypal_payments_add_to_cart_text', $this->settings[$key]);
				continue;
			}
			$this->settings[ $key ] = $value;
		}
```

This could be useful for other plugins as well.

**Comment by InpsydeNiklas** [comment]
Hi @diiegopereira, thanks for your report. We're tracking this in #1370 as well. 

To clarify why the gateway title/translation is not working: WPML (and specifically the WCML extension) runs through all Payment Gateways setting fields registered via `init_form_fields` - the native WooCommerce `Admin Settings API`, it then targets fields with the following keys: `title`, `description`, and `instructions` for translation (more field keys can be added via the `wcml_gateway_text_keys_to_translate` filter).

At the moment, PayPal Payments is bypassing the `Admin Settings API` for the PayPal and Advanced Card Processing gateways, adding title & description fields in a custom way which is essentially breaking compatibility with any plugins extending the WooCommerce `Admin Settings API` fields.

We don't know when refactoring the settings pages to the `Admin Settings API` will happen as it is a bigger undertaking, but we'll have a look into the option to provide a filter override for translation purposes. Thank you!

**Comment by diiegopereira** [comment]
@InpsydeNiklas thanks for the feedback! I will update our team.

**Comment by InpsydeNiklas** [comment]
Hello @diiegopereira, we are adding a workaround for this in the 2.8.1 update as can be seen in https://github.com/woocommerce/woocommerce-paypal-payments/pull/2308.
Unfortunately, due to the order in which our compatibility module is loaded, we couldn't implement a proper solution without deviating from our standards. So, this approach requires a small `mu-plugin` with a filter to make the title/description fields translatable via WPML. It's better than asking users to change the plugin code directly as this persists through plugin updates, but it would still require users to manually install the `mu-plugin`, so it may not be easy to apply for everyone.
Let us know how this works for you!

We'll keep https://github.com/woocommerce/woocommerce-paypal-payments/issues/1370 open until a proper solution is on the horizon, but I wouldn't expect anything before Q4.
