### ISSUE TITLE
Paypal Incompatibility - new version Checkout block

### ISSUE THREAD

**Issue by RaulMartinezSaveFamily** [woocommerce/woocommerce-paypal-payments#2120]
Hello Woocommerce Paypal payments Team,

We have added the new checkout block for Woocomerce. The block payment options (opciones de pago in spanish) is showing the next following error for Paypal payment.

"Incompatible con el pago basado en bloques" - Incompatible with the payment based in blocks.

![Plataformas de Pago Inconpatibles](https://github.com/woocommerce/woocommerce-paypal-payments/assets/165046760/35bbaffc-e305-4e27-b5a1-75211564b451)

Please, could you help us ? We are using the latest Woocomerce version.

Thanks in advance
Raúl

**Comment by InpsydeNiklas** [comment]
Hello @RaulMartinezSaveFamily, for the PayPal gateway to declare compatibility with the Checkout block, please enable the `Express Checkout` button location in the PayPal Payments settings:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/3ed98698-20e5-4a37-b980-5486e31b6a41)
More details about it can be found here: https://woo.com/document/woocommerce-paypal-payments/#paypal-buttons
If you need additional guidance setting up the PayPal Payments plugin to your needs, I recommend that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).
Thank you!
