### ISSUE TITLE
BUG PAYPAL

### ISSUE THREAD

**Issue by ecomroge** [woocommerce/woocommerce-paypal-payments#2122]
My checkout is not processing any charges, it shows an error with any card with which you try to pay

**Comment by Sirvijver** [comment]
Hello @ecomroge,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Without knowing what the errors are saying or having the logs to look at, there is not much specific advice we can give you. In this case, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). 

If this doesn't help you, please open a support request as advised in the top of my message to receive additional support.

Kind regards, 
Joost
