### ISSUE TITLE
Pay later settings not saving

### ISSUE THREAD

**Issue by MikeHud** [woocommerce/woocommerce-paypal-payments#2123]
### Describe the Bug

The pay later settings do not save! I turn them all off but it switches back. 

Sorry I don't have time to fill in this extensive bug report. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @MikeHud 

If I recall correctly, you mentioned this issue on wp.org, and we advised you to get in touch with us directly for further analysis.

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian
