### ISSUE TITLE
failed payments

### ISSUE THREAD

**Issue by CleanFilter24** [woocommerce/woocommerce-paypal-payments#2126]
Payments with other currencies, especially polish zlots are failing if they made via addition services:
- Credit or debit cards (via PayPal)
- Blik
- Przelewy24

Blik and Przelewy24 has 50% failure ratio,

Errors:

Payer action required, possibly overcharge. Payer needs to perform the following action before proceeding with payment. Status zamówienia zmieniony z Oczekujące na płatność na Nieudane.
 and etc.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @CleanFilter24 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by scottybo** [comment]
@CleanFilter24 did you ever find a solution to this one?

I'm running into this error regularly too.

**Comment by SydeKrystian** [comment]
Hello @scottybo 

We kindly ask that you reach out directly to our [support team](https://paypal.inpsyde.com/docs/request-support/).  We'll try to sort it out.

Kind regards,
Krystian
