### ISSUE TITLE
the checkout page has Chinese words on it instead of English

### ISSUE THREAD

**Issue by thisismia** [woocommerce/woocommerce-paypal-payments#2127]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by thisismia** [comment]
![Uploading 截屏2024-03-28 下午5.34.49.png…]()

**Comment by thisismia** [comment]
here is a screenshot. Does anyone know why this is happening? 
<img width="1304" alt="截屏2024-03-28 下午5 34 49" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/132462385/74dd0958-0261-41a4-8797-7f1354664a91">

**Comment by SydeKrystian** [comment]
Hello @thisismia 

We need to review your system report to properly analyze and address this issue. GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
