### ISSUE TITLE
Woo Subscriptions trial period is not free as we want to be

### ISSUE THREAD

**Issue by melyp** [woocommerce/woocommerce-paypal-payments#2134]
Hello,

We have implemented Woo Subscriptions for few products using PayPal as method of payment.
The products have a free trial period of 14 days but when we connect product to Paypal subscriptions plan it appears a fee for the trial period equal with the value of the subscription, so the trial period is not free as we want.

Every time, we need to log in into Paypal and update each trial period for each product with zero, in order to have the free trial. 

I have attached a picture below.

![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/34377587/df3c1484-5c5f-44c0-aa35-a3f8814a71b0)

Also, we have observed that sometimes the trial period is reset when we edit the product from WordPress Admin.  Is it possible to be this  the cause of reseting? 
The reset happens not for all the products, but only for some of them. 

I also updated the paypal plugin WooCommerce PayPal Payments  to version Version 2.6.0.
WooCommerce version is Version 8.6.1.
WordPress version 6.3.3.

Also, when we connect the product to PayPal subscription plan, the input with the free trial period disappear from WordPress Admin.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/34377587/c46f9f4b-4f95-44be-8bb9-aad148be4ffc)

Is this intended?

Please advice on these topics.

Thank you!
Melania

**Comment by Sirvijver** [comment]
Hello @melyp 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Reading your problem description, I believe there is quite some confusion with the subscriptions setup of our plugin and how it works together with the Woo subscriptions plugin. I would advise you to read [our documentation](https://woo.com/document/woocommerce-paypal-payments/#subscriptions-faq) about this and get more details about the difference between PayPal Vaulting and PayPal Subscriptions, which can have a big impact on the behavior of how the sale and renewals of subscriptions function.

If this document does not help you to clear up the situation and resolve the issue, please open a support request as advised above with our support team.

Kind regards, 
Joost
