### ISSUE TITLE
PayPal Payments

### ISSUE THREAD

**Issue by dizzyobrian** [woocommerce/woocommerce-paypal-payments#2138]
### Describe the Bug
I keep trying to activate my woocommerce and I log into my PayPal (business account) PayPal says congrats you are approved and then woocomerce says no, there is a problem accepting cards; try again.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @dizzyobrian, 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I am not sure what issue you are encountering, but there are 2 things I would advise you to try:
- You may want to disable all other plugins (except WooCommerce and PayPal Payments) and see if another plugin might be affecting the onboarding process negatively.
- Reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review your account to see if there is anything wrong with it. You can also try to onboard the plugin with a sandbox account, this way you can at least verify if the plugin is working correctly. You can create sandbox accounts here: https://developer.paypal.com/

If this does not help you get this issue resolved, please open a support request as advised above.

Kind regards, 
Joost
