### ISSUE TITLE
An error occurred when registering the payment method with the ID "ppcp-gateway": Error: Invalid query value forcurrency: CNY (debug id: 01246142bb264) This error is prompted. How to solve it?

### ISSUE THREAD

**Issue by zhang20245** [woocommerce/woocommerce-paypal-payments#2141]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @zhang20245, PayPal has [restrictions for certain currencies](https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/), such as CNY. But for us to learn more about the problem you are facing and provide proper guidance, please [contact our support team directly from here](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
