### ISSUE TITLE
pay later

### ISSUE THREAD

**Issue by caredemy** [woocommerce/woocommerce-paypal-payments#2145]
we have paypal pay later and subscriptions set up, pay later does not appear as an option for Paypal subscriptions, is this a bug or do we need to select something to make pay later appear for subscriptions , it all works fine for single products

**Comment by InpsydeNiklas** [comment]
Hi @caredemy, PayPal offers Pay Later options only for one-time purchases and not for subscription products: https://developer.paypal.com/docs/checkout/pay-later/us/#link-eligibility
This means Pay Later offers will not be available when using PayPal Vaulting or for PayPal Subscriptions products: https://woo.com/document/woocommerce-paypal-payments/#subscriptions-faq
 If you have any questions about the PayPal integration, please consider [contacting our support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
