### ISSUE TITLE
WooCommerce PayPal Payments - Customer can't make a payment

### ISSUE THREAD

**Issue by LinLTH** [woocommerce/woocommerce-paypal-payments#2150]
### To Reproduce

1. Go to 'https://www.learningtheharp.com/shop/after-the-rain-sheet-music/'
2. Click on 'Add to cart'
3. Click on 'View Cart'
4. Click on 'Proceed to checkout'
5. Select 'PayPal' as payment option
6. There are two buttons (should only be one the paypal one)
7. Click the 'paypal' button
8. See error

### Screenshots

![Screenshot 2024-04-09 at 14 19 59](https://github.com/woocommerce/woocommerce-paypal-payments/assets/166519239/ea64df9b-5053-490a-8088-b0a7955f197b)

### Expected Behavior

I expected the payment to be able to be processed.

### Actual Behavior

No payment is possible, but if I am logged in as an admin on the website then I am able to process the payment correctly (and only the 'paypal' yellow button appears).

### Environment

 - WordPress Version : 6.5
 - WooCommerce Version: 8.7.0
 - Plugin Version: 2.6.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome (but also happening on Safari)
 - Any other plugins installed: too many to list

**Comment by SydeKrystian** [comment]
Hello @LinLTH 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

I haven't been able to reproduce this issue, but analyzing the plugin logs should help us identify the problem. I suggest contacting the support board for further assistance.

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by LinLTH** [comment]
Thank you, I have submitted a support request.
