### ISSUE TITLE
 I can't make payments with the plug in

### ISSUE THREAD

**Issue by deportika** [woocommerce/woocommerce-paypal-payments#2159]
### Describe the Bug

When you try to make the payment by PayPal or debit card and click pay, the system shows the PayPal window but returns to the site page sending the message "There is already an account registered with your email address. Please log in "and from there it doesn't happen.

### To Reproduce

1. Go to https://deportikaonline.com/carrito/
2. Click on boton "Finalizar compra"
3. Select credit or debit card
4. The name, surname and email information are entered (it does not ask for account information)
5. Click on the credit or debit card button
6. show and hide paypal screen
7. error or inconvenience sign

### Screenshots
displays a warning "There is already an account registered with your email address. Please log in." and you can't continue

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/121068660/f55c6700-edcf-4c3a-a0b2-6e355762ce03)

### Expected Behavior

It should ask for the card details and process the payment

### Actual Behavior

It does not ask for card details and does not process the payment.

### Environment

 - WordPress 6.5.2
 - WooCommerce Version Versión 8.7.0
 - WooCommerce PayPal Payments Versión 2.6.1
 - Browser Chrome

**Comment by SydeKrystian** [comment]
Hello @deportika 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
