### ISSUE TITLE
Console Log constantly printing event from parent

### ISSUE THREAD

**Issue by tomektomczuk** [woocommerce/woocommerce-paypal-payments#2162]
<img width="501" alt="Screenshot 2024-04-16 at 17 58 13" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/40096666/ea1dc7a0-afac-476f-97ff-e3d9d0819353">

**Comment by InpsydeNiklas** [comment]
Hi @tomektomczuk, the console logging for Apple Pay currently is only present when WordPress debugging is active. In the next update, these console logs will be disabled even when debugging is active.
In the meantime, you can comment or remove this line to remove the console logs when debugging is active: https://github.com/woocommerce/woocommerce-paypal-payments/blob/7f384e532c4f4e6fb57cf8904896e40c3e0c2cd7/modules/ppcp-applepay/resources/js/ApplepayButton.js#L42
