### ISSUE TITLE
Error: MISSING_SHIPPING_ADDRESS during PayPal payment

### ISSUE THREAD

**Issue by waseeq-siddiqi** [woocommerce/woocommerce-paypal-payments#2164]
Description:
Customers encounter "MISSING_SHIPPING_ADDRESS" error when making PayPal payments with shipping_preference set to SET_PROVIDED_ADDRESS.

Steps to Reproduce:

Checkout with PayPal.
Select SET_PROVIDED_ADDRESS.
Error occurs during payment.
Expected Behavior:
Successful payment without errors related to shipping address.

Actual Behavior:
Error message "MISSING_SHIPPING_ADDRESS" prevents payment completion.

Additional Info:

Occurs consistently.
Website: [[[URL](https://www.raabtasentiments.com/)]]

**Comment by SydeKrystian** [comment]
Hello @waseeq-siddiqi 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
