### ISSUE TITLE
PayPal Pay Later only available in German and does not integrate at all in payment flow

### ISSUE THREAD

**Issue by EasyEl** [woocommerce/woocommerce-paypal-payments#2165]
### Describe the Bug

We sell worldwide but have the option to limit the availability to some european countries. Sadly, for some reason the Pay Later does not integrate well with our standard payments and has an annoying own button management. Even worse, it is only available in German and does not auto-translate to the user browser language.

### To Reproduce

Install the plugin with a German PayPal Business Account

### Expected Behavior

Integrate seamlessly in the normal payment options and give the option to name the payment option. Make sure it is available for all countries in the EU where Pay Later is available.

### Actual Behavior

Custom flow that does not integrate at all in bigger online shops that sell to multiple countries (EUR).

### Environment

 - WordPress Version latest
 - WooCommerce Version latest
 - Plugin Version latest

**Comment by InpsydeNiklas** [comment]
Hi @EasyEl 

> Sadly, for some reason the Pay Later does not integrate well with our standard payments and has an annoying own button management. 

Can you elaborate on what you mean by "_Pay Later does not integrate well with our standard payments and has an annoying own button management_"?
The Pay Later button currently will be presented next to the PayPal button.

> Even worse, it is only available in German and does not auto-translate to the user browser language.

The Pay Later button & messages have a fixed language depending on the connected merchant account. German PayPal merchants will always only show the "Später Bezahlen" button and messaging in German, regardless where the buyer is from or what browser language they configured: https://developer.paypal.com/docs/checkout/pay-later/de/
To learn more about cross-border Pay Later offerings, I suggest contacting the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/).
For any questions relating directly to the PayPal Payments plugin, please [contact our support team from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
