### ISSUE TITLE
"enabling the Checkout location for the PayPal gateway. Enable the Checkout location." Link doesnt work

### ISSUE THREAD

**Issue by AlexisLagos69** [woocommerce/woocommerce-paypal-payments#2167]
After enabling the PayPAl payments for WooCommerce, WooCommerce plugin shows the following message:

Standard Card Button cannot be used without enabling the Checkout location for the PayPal gateway. Enable the Checkout location. When you click in the Enable the Checkout location. link, it does absolutely nothing, only reloads the page. I attach a screenshot.

![WooCommerce PayPall error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/167354952/47e65fd9-535f-4ed9-b311-18af91f4c10b)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/167354952/a775e2a5-7f12-419a-a119-d3c81f16919c)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @AlexisLagos69, the link in the notice only leads you to the Standard Payments tab from where you can enable the `Classic Checkout` location for the smart buttons: https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-buttons The Standard Card Button gateway will not work unless you enable the PayPal button on the Classic Checkout page as well.
The text in this notice will be improved in a future update! For any other questions relating to the PayPal Payments plugin setup, please [contact our support team from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
