### ISSUE TITLE
Error: "Things don't appear to be working at the moment. Please try again later."

### ISSUE THREAD

**Issue by vicross04** [woocommerce/woocommerce-paypal-payments#2169]
### Describe the Bug

When click on pay with "Paypal Standard Card" it redirects but shows the error msg: "Things don't appear to be working at the moment. Please try again later."

### To Reproduce

1. Go to [website](https://dixgamer.com/shop/juegos/ps3/accion-ps3/alien-isolation/)
2. Click on 'Comprar' (purchase)
3. Click on 'Finalizar compra' (go to checkout)
4. Select 'pais' (country) > Argentina

5. Complete with fake data:
Nombre > Victor
Apellido > Vic
Nro de Documento > 12341234
Telefono > 1165652626
Población > BA
Dirección > Pedro 123
Código postal > 1234
Dirección de correo > {your real email}
Confirmar dirección > {your real email}

6. Select "Paypal - Tarjeta"

### Screenshots
<img width="1181" alt="Untitled" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/51501259/8b9e7fa7-9a57-4de1-a517-f27997aa14a6">

### Expected Behavior

It should redirect to paypal to let the customer pay for the order.

### Actual Behavior

It shows an generic error

### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.2
 - Plugin Version 2.6.1
 - Browser Chrome 123.0.6312.124

### Additional Details

- It was working fine until 2 days ago that stopped working.
- Paypal id: D65M49PFNL82A
- The paypal conecction settings were not change at all, seems to be fine.
- The log shows like it is working also, doesnt show any error.
- 
[paypal-2024-04-18.log](https://github.com/woocommerce/woocommerce-paypal-payments/files/15026911/paypal-2024-04-18.log)

**Comment by SydeKrystian** [comment]
Hello @vicross04 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
