### ISSUE TITLE
Mobile Payment Issue: Expiry Date Field Disappearing on PayPal Gateway

### ISSUE THREAD

**Issue by Milamoo** [woocommerce/woocommerce-paypal-payments#2172]
**Describe the Bug**
Users experience issues with the payment gateway on mobile devices where the slash (/) does not appear in the expiry date field during checkout. This might be impacting customer orders. The issue appears specifically when using the PayPal payment option, and it's not consistent across all attempts.

**To Reproduce**
Go to the payment page on the website.
Choose 'Pay by card via PayPal' gateway.
Enter card details and move to the expiry date field.
After entering the expiry date, click on the CVC field.
Observe that the expiry date disappears and is replaced with options for "Clear Autofill Form" and "Manage Addresses."
Screenshots
![expiry](https://github.com/woocommerce/woocommerce-paypal-payments/assets/44054786/92a786d1-c0ae-4d31-befb-327335c52f95)
![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/44054786/56ca780a-470a-4692-9b24-1f553e95d039)

**Expected Behavior**
The expiry date should remain visible and correctly formatted with a slash separating the month and year after it is entered, allowing for seamless completion of the payment form.

**Actual Behavior**
The expiry date either does not display a slash or disappears entirely when the CVC field is clicked, sometimes replaced by a menu with options to clear the form or manage addresses. Users need to refresh the payment page to re-enter information, which may or may not work correctly.

**Environment**
WordPress Version: 6.5.2
WooCommerce Version: 8.8.2
Plugin Version: 2.6.1
Browser: Samsung Internet Browser, Safari on iPad
Any other plugins installed:

1. Advanced Custom Fields PRO
2. Advanced Custom Fields: Font Awesome
3. All-in-One WP Migration
4. All-in-One WP Migration Google Drive Extension
5. Contact Form 7
6. CookieYes | GDPR Cookie Consent
7. Envato Market
8. Fetchify
9. Flexible Checkout Fields
10. Gift Up
11. Honeypot for Contact Form 7
12. Kadence WooCommerce Email Designer
13. LightStart - Maintenance Mode, Coming Soon and Landing Page Builder
14. Mailchimp for WooCommerce
15. Max Mega Menu
16. Modula
17. Ninja Forms
18. Redirection
19. Responsive Menu
20. Schema - All In One Schema Rich Snippets
21. Social Snap Lite
22. TI WooCommerce Wishlist
23. Velvet Blues Update URLs
24. WooCommerce
25. WooCommerce Advanced Product Labels
26. WooCommerce Google Product Feed
27. WooCommerce PayPal Payments
28. WooCommerce Stripe Gateway
29. WOOF - WooCommerce Products Filter
30. Wordfence Security
31. WP Rocket
32. WPCode Lite
33. Yoast SEO

Additional Details
This issue has been noted on both Samsung smartphones and iPads, indicating it may be related to mobile browsers or specific configurations with autofill settings on these devices. A 
![expiry](https://github.com/woocommerce/woocommerce-paypal-payments/assets/44054786/383b104f-c056-4939-a5c9-9d05cf651118)
![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/44054786/9f13139d-5285-4999-abca-1f4b7fc9b7f9)
screenshot is attached for reference.

<details><summary>System status</summary>

**Comment by SydeKrystian** [comment]
Hello @Milamoo 

These fields are created by PayPal, and we simply display them. I've reported this issue and we'll forward the information to PayPal for potential resolution. I'll keep you updated on any developments.

If you still have any questions for us.

Kind regards,
Krystian

**Comment by SydeKrystian** [comment]
Hello @Milamoo 

I’ve noticed that this issue is still open, but it should now be resolved in our plugin. If it persists, please let us know.  

I’ll go ahead and close it for now.  

Kind Regards,  
Krystian
