### ISSUE TITLE
PayPal Advanced Credit Card Gateway Not Showing up in Order-Pay page (Manual Order) 

### ISSUE THREAD

**Issue by jz101** [woocommerce/woocommerce-paypal-payments#2173]
Describe the Bug
If an admin creates an order from the WP dashboard, the customer doesn't have option to pay via credit card. 
Also the standard checkout button 'Proceed to PayPal' should be hidden at order-pay page, show 'smart button' instead. if click on the 'proceed to PayPal' button it show error notice: "Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED"

To Reproduce
Go to Dashboard -> Orders
Create a new order, add a product and click Create
Go to the payment page for that order (link "Customer payment page")
At checkout, the advanced credit card gateway payment method doesn't appear
Screenshots
This is a screen recording showing the issue:
https://ibb.co/9N62Jry

Expected Behavior
The Paypal and Advanced Credit Card payment method should be available both orders created by backend as well.

Environment
WordPress Version 6.2.2
WooCommerce Version 7.4
Plugin Version 2.6.1

**Comment by SydeKrystian** [comment]
Hello @jz101 

You've already raised this issue on our support board and we have responded there. We'll continue our communication through that channel.

I'll mark this issue as closed.

Kind regards,
Krystian
