### ISSUE TITLE
"invalid argument: shipping_address" error with PayPal Express

### ISSUE THREAD

**Issue by harryneufeld** [woocommerce/woocommerce-paypal-payments#2174]
### Describe the Bug

When paying with PayPal express i experience currently the error "invalid argument: shipping_address" after the user is sent back to the shop to verify the buy.

### To Reproduce

Go to Checkout, click on "PayPal" (Express)-Button, on PayPal click on "Validate on Website" (Translated from german).

### Expected Behavior

After validating the Payment in PayPal Process the User should be redirected to the Shop and the shipping Address should be automatically passed from paypal.

### Actual Behavior

Said error appears, address is not shown.

### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.2
 - WooPayments Version 7.5.1
 - WooCommerce PayPal Payments Version 2.6.1
 - Safari, Chrome, Firefox

**Comment by SydeKrystian** [comment]
Hello @harryneufeld 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
