### ISSUE TITLE
Overriding Security Plugin Settings

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#2184]
### Describe the Bug
Our security plugin puts orders on hold for review and Paypal payments is overriding this and pushing everything to processing on payment. This did not happen with previous versions of the plugin.

It is overriding on hold settings.
### To Reproduce

Create an order. It will go from Pending Payment to Processing.
Put order on hold.
Payment will be successfully captured by Paypal.
Order goes from On Hold to Processing and will show transaction ID.

### Screenshots
![paypal](https://github.com/woocommerce/woocommerce-paypal-payments/assets/159199722/ae90a62a-78b7-4ee3-a133-89e768b0d8b9)

### Expected Behavior
Leave it as it is until moved to processing.
### Actual Behavior

Overrides order setting
### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.7.0
 - Plugin Version 2.6.1
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed
Kount Fraud Prevention 1.1.0

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @KatatJackson 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a name of that security plugin.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
