### ISSUE TITLE
Feature: Add ability to utilize the builded Module Container

### ISSUE THREAD

**Issue by brianvarskonst** [woocommerce/woocommerce-paypal-payments#219]
### Describe the Feature
It would be very useful, to implement a filter or action that exposes the builded modules container, like:

```php
apply_filters('woocommerce_paypal_payments_builded_container', $container);
```

If you have security/stability concerns, an only readable Container would make also huge sense, so you can just grab configured components out of the container, so there is no space for changing components that could result in Plugin errors.

**Comment by Dinamiko** [comment]
Hi @brianvarskonst, 

In latest release we have included a way to accessing the plugin container, here is the PR:
https://github.com/woocommerce/woocommerce-paypal-payments/pull/203 

See **Adding modules and accessing the plugin container** section, will be great if you can give it a try to see if it works for you or if something is missing, thanks.
