### ISSUE TITLE
Woocommerce Checkout Failure for Some

### ISSUE THREAD

**Issue by DuckSportsFan** [woocommerce/woocommerce-paypal-payments#2195]
### Describe the Bug

Using the "Debit or Credit Card" radio button option, at the initial Checkout page, some customers are getting a "Failure" error (see photo).

### To Reproduce

1. Go to 'Checkout Page'.
2. Fill out the form.
3. Click on 'Debit & Credit Card' radio button.
4. Enter a valid credit card number.
5. See error in photo, attached.

### Screenshots
![Woocommerce_Error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/7246178/4142522d-eabf-4ed6-b76a-ba6bb92bf7e0)

### Expected Behavior

The card is to be accepted and the transaction approved.

### Actual Behavior

An error and failure message is displayed... See the attached photo.
### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.3
 - Plugin Version 2.7.0
 - Browser [e.g. Chrome, Safari] and Version ...any version.
 - Any other plugins installed: AccessPress Anonymous Post, Copy & Delete Posts, Email Address Encoder, Google Listings and Ads, Include Me, iThemes Security Pro, Jetpack, Mailchimp for WooCommerce, MailPoet, Minutes, Agendas and Newsletters, NinjaFirewall (WP Edition), NinjaScanner, PHP Code For Posts, Pinterest for WooCommerce, Really Simple CAPTCHA, Simple Social Page Widget & Shortcode, Smash Balloon Custom Facebook Feed, Smash Balloon Instagram Feed, Smush Pro, The Events Calendar, The Events Calendar Pro, Under Construction, Widget Importer & Exporter, WooCommerce, WooCommerce Customer/Order/Coupon Export, WooCommerce PayPal Payments, WP All Export Pro, WP Rocket, and WPMU DEV Dashboard.

### Additional Details

This is an intermittent issue...meaning some cards are accepted...and the ones that produce the error produce the same error even immediately and days later.  Interestingly, these failed cards will work when utilizing the "PayPal" payment option as a guest and using the Debit or Credit Card option.

  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @DuckSportsFan 

PAYMENT_DENIED is not a technical issue. It's PayPal's security system blocking the transaction and the reason for it will not be communicated by PayPal. For this error [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) is generally also a better contact than [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) (as the latter deals with technical issues).

Should you require any further assistance or have additional questions we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

Kind regards,
Krystian
