### ISSUE TITLE
Missing paypal payments in woocommerce

### ISSUE THREAD

**Issue by aneesascf** [woocommerce/woocommerce-paypal-payments#2197]
### Describe the Bug

Donors to our website have shared proof that they have made paypal payments, however we do not see these orders or therefore, the receipts, in woocommerce. 

Example: 
transaction date: 
03/12/2022 | 3:46:28 | PST
amount: 100$
to: small change fund. 

These are monthly subscription payments, other months have gone through and shown in orders successfully. There are 6 total for this donor which aren't showing. There are consistently payments from paypal missing in our books. 

### To Reproduce

Can't. You can create a monthly subscription paypal payment but some of them are successful and some aren't - I don't know why some do not show in order data. 

### Expected Behavior

All monthly subscription paypal payments to show in order data and for receipts to be generated. 

### Actual Behavior

We see nothing. no proof of transaction. Donors tell us offline and show us statements as proof. 

### Environment

 - WordPress Version: 6.5.2
 - WooCommerce Version: 8.8.2
 - Plugin Version: woocommerce paypal payments: by WooCommerce – 2.6.1 (update to version 2.7.0 is available)
 - Browser [e.g. Chrome, Safari] and Version: chrome 124.0.6367.80 
 - Any other plugins installed: A
AddToAny Share Buttons, Version 1.8.10
Advanced iFrame custom folder, Version 2024.0
Advanced iFrame Pro, Version 2024.0
Advanced Order Export For WooCommerce, Version 3.5.0
Akismet Anti-spam: Spam Protection, Version 5.3.2 
BackWPup, Version 4.0.4
BetterDocs, Version 3.5.3
Classic Editor, Version 1.6.3
Coinbase Commerce, Version 1.3
Elementor, Version 3.21.1 
Elementor Pro, Version 3.21.0
Give - Annual Receipts, Version 1.1.1
Give - Donation Plugin, Version 3.8.0
Give - Form Field Manager, Version 3.0.4 
Give - PDF Receipts, Version 3.2.0
Give - Peer-to-Peer, Version 2.1.0 
Give - Recurring Donations, Version 2.7.0 
GP Woocommerce Export, Version 1.0.0 
Krowd Themer, Version 1.5.9 
Meta Box, Version 5.9.7
PDF Invoices & Packing Slips for WooCommerce, Version 3.8.0 
PDF Invoices & Packing Slips for WooCommerce - Professional, Version 2.15.8
Restrict User Access, Version 2.6.1
Sequential Order Numbers for WooCommerce, Version 1.6.1
Ultimate Member, Version 2.8.5 
Ultimate Member - reCAPTCHA, Version 2.3.6
Woo Donations, Version 4.3.1
WooCommerce, Version 8.8.2 
WooCommerce Legacy REST API, Version 1.0.1
WooCommerce Order Status Control, Version 1.14.0
WooCommerce PayPal Payments, Version 2.6.1 
WooCommerce Stripe Gateway, Version 8.2.0
Wordfence Security, Version 7.11.5
WP Crowdfunding, Version 2.1.10
WP Crowdfunding Pro, Version 11.2.0 
WP File Manager, Version 7.2.6
WP Mail SMTP Pro, Version 4.0.2 
WP-Optimize - Clean, Compress, Cache, Version 3.3.2
WPCode Lite, Version 2.1.11 
Yoast SEO, Version 22.5

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @aneesascf 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Beyond this, to investigate this issue further, we'd like to examine your plugin log files. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian
