### ISSUE TITLE
Google Pay not rendering & Apple Pay payment fails without any visible errors

### ISSUE THREAD

**Issue by enwikuna** [woocommerce/woocommerce-paypal-payments#2198]
### Describe the Bug

After I got the request approve on PayPal using Google & Apple Pay, I've followed the instructions to set up both payment methods inside the plugin which was successful. First, I was a bit confused that the plugin still shows that the payment methods are unavailable but after synching the API permissions, it worked.

After configuring everything, I've checked both in Safari and Google Chrome. My Chrome profile was logged in and configured to use Google Pay. The same for Apple Pay. Sadly, the Google Pay button is not rendering. Not on Chrome and not on an Android phone.

On Safari (Mac & iPhone), the Apple Pay button appears but is not working. When pressing the button, the buying process fails every time. I've checked the PayPal logs, but I can not find any useful data. 

After that, I've activated logging for the PayPal plugin, but I can also see no errors inside the logs when trying to use Apple Pay.

Please check and fix this ASAP since it's interrupting my business.

### To Reproduce

1. Go to agency.enwikuna.de with a Chrome and Safari browser
2. Add a product to the cart you like
3. Proceed to checkout

### Screenshots

![2](https://github.com/woocommerce/woocommerce-paypal-payments/assets/166232905/97f3bfae-af7c-454d-a93f-e11b7765a025)
![1](https://github.com/woocommerce/woocommerce-paypal-payments/assets/166232905/301ec8e1-b741-427b-b451-f3caa27aa335)

### Expected Behavior

Google Pay renders, and both Apple & Google Pay works.

### Actual Behavior

Google Pay button is not rendering and Apple Pay button is not working.

### Environment

 - WordPress Version: 6.5.2
 - WooCommerce Version: 8.8.3
 - Plugin Version: 2.7.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome (124.0.6367.118) & Safari (17.4.1)
 - Any other plugins installed: Some, but truly not relevant when checking the logs and everything else

**Comment by SydeKrystian** [comment]
Hello @enwikuna 

I see our support team has already handled this on a private board, so I'm closing the issue.

Kind regards,
Krystian

**Comment by codevu** [comment]
I'm also having this issue. Has this been resolved?
