### ISSUE TITLE
Error pay with visa card

### ISSUE THREAD

**Issue by xujiongze** [woocommerce/woocommerce-paypal-payments#2207]
### Describe the Bug

When customer pay with credit card, apper critical error by Wordpress

### To Reproduce

1. Create order
2. Send order notification to customer
3. User click link payment by email
4. Pay with credit card, andd append error

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/31494901/c7ab1b82-6a74-4e66-a8d3-e59441b70415)

### Environment

 - WordPress Version 6.5.2
 - WooCommerce Version 8.8.3
 - Plugin Version 2.7.0 
 - Browser [e.g. Chrome, Safari] and Version  Chrome 124.0.6367.119
 - Any other plugins installed 

### Additional Details

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/31494901/6a0c8627-22d1-43c0-8760-2f6205e2de5c)

**Comment by SydeKrystian** [comment]
Hello @xujiongze 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
