### ISSUE TITLE
applying for the advance payment

### ISSUE THREAD

**Issue by Maosixian** [woocommerce/woocommerce-paypal-payments#2208]
When i was trying to apply for the advance payment, I had to fill in the company owner's ID card of America, but I'm not an American, instead, I'm a Chinese who has an American company, how can I then apply for the advanced payment

**Comment by Sirvijver** [comment]
Hello @Maosixian 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

In order get your request for Advanced Card Processing corrected/progressed, please reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport), they will be able to help you.
More documentation about the account related process for Advanced Card Processing can be found [here](https://woocommerce.com/document/woocommerce-paypal-payments/#sign-up-for-advanced-card-payments).
If you have more questions about the technical working of Advanced Card Processing, please have a look [here](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing).

If you have more technical support questions, please open a support ticket as explained above.

Kind regards, 
Joost
