### ISSUE TITLE
PHP 8.2 Depreciation Error

### ISSUE THREAD

**Issue by calderwood** [woocommerce/woocommerce-paypal-payments#2217]
### Describe the Bug

[Fri May 10 10:18:41.585354 2024] [lsapi:warn] [pid 976007:tid 47237165258496] [remote 69.68.xxx.xx:58904] [host xxx.com] Backend log: PHP Deprecated:  Creation of dynamic property WC_Gateway_PayPal_Pro::$api_password is deprecated in /home/xx/public_html/wp-content/plugins/woocommerce-gateway-paypal-pro/includes/class-wc-gateway-paypal-pro.php on line 94\n, referer: https://xxx.com/wp-content/uploads/fusion-styles/850f2c62149fed4d2af25755eb390cb0.min.css?ver=3.11.7     

### To Reproduce

This is noted in the error logs from PHP 8.2

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @calderwood, the plugin `woocommerce-gateway-paypal-pro` is a different PayPal integration. If you're using an older third-party PayPal integration, I recommend switching to the official [WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) plugin. Documentation can be found here: https://woocommerce.com/document/woocommerce-paypal-payments/
If you need assistance with the setup, you can contact the team from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!

**Comment by calderwood** [comment]
This is the plugin we are using:

WooCommerce PayPal Payments

*	Version: 2.7.0
*	Author:  <https://woocommerce.com/> WooCommerce
*	Last Updated: 2 weeks ago
*	Requires WordPress Version: 5.3 or higher
*	Compatible up to: 6.5.3
*	Requires PHP Version: 7.2 or higher
*	Active Installations: 600,000+

 

Isn’t this your plugin?

**Comment by InpsydeNiklas** [comment]
Yes, `WooCommerce PayPal Payments` is this plugin, but the deprecation notice you mentioned comes from `woocommerce-gateway-paypal-pro`, which is another plugin. The message also implies that this is an outdated PayPal integration that connects to the deprecated PayPal API which `WooCommerce PayPal Payments` does not support: `WC_Gateway_PayPal_Pro::$api_password`
I recommend checking the list of your installed plugins and disabling any PayPal plugin that isn't called exactly "`WooCommerce PayPal Payments`". Hope that helps!

**Comment by calderwood** [comment]
Thanks for that.  Yes I see that we still have the old Woocommerce PP payments activated.  Deleted.
