### ISSUE TITLE
my current WooCommerce store currency (INR) is not supported by PayPal.

### ISSUE THREAD

**Issue by digitex-erp** [woocommerce/woocommerce-paypal-payments#2233]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @digitex-erp 

that is correct, you can find the current supported currencies here: https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/
Also, if you want to contact PayPal regarding this limitation, you might want to contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport). They could maybe help you out with this. We are the plugin developers and have no influence on this matter.

I will close this thread.

Kind regards, 
Joost
