### ISSUE TITLE
Payment Capture Error: Could not retrieve information. Try again later

### ISSUE THREAD

**Issue by outpost5441** [woocommerce/woocommerce-paypal-payments#2241]
**Describe the Bug**

We are running v2.7.0 version of PayPal Payments. We are having a periodic issue on about 30-50% of orders we are trying to capture. The problem occurs with both PayPal and Credit / Debit Card orders. Selecting the "Capture authorized PayPal payment" order actions returns "Could not retrieve information. Try again later." 

This issue occasionally causes the order to report FAILED as well as result an error shown at end. The order gets marked as "Paid" but also marked as "Not captured". 

**To Reproduce**

    Go to an "On Hold" (Not Captured) order.
    From the order actions drop-down select "Capture authorized PayPal payment"
    Click Update
    Error message "Could not retrieve information. Try again later." appears in the upper left.

**Expected Behavior**

The request is made to PayPal to capture the payment and the payment is captured.

**Actual Behavior**

No request is made to PayPal. Payment remains in Pending status in Paypal.
Sometimes changes from On Hold to Failed even though payment was captured.

**Environment**

    WordPress 6.5.3
    WooCommerce 8.8.3
    WooCoomerce PayPal Payments 2.7.0

**Attempted Fixes**

We read a post a year ago with someone with same issue which a suggested fix was to refresh PayPal WebHooks, which we have done but that did not resolve the issue we are having.

**Error Messages**

This error message sometimes occurs when attempting to Capture payment.

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array
in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/PaymentsEndpoint.php on line 179

Call stack:

    WooCommerce\P\A\E\PaymentsEndpoint::capture()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/AuthorizedPaymentsProcessor.php:430
    WooCommerce\P\W\P\AuthorizedPaymentsProcessor::capture_authorization()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/AuthorizedPaymentsProcessor.php:171
    WooCommerce\P\W\P\AuthorizedPaymentsProcessor::process()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/AuthorizedPaymentsProcessor.php:197
    WooCommerce\P\W\P\AuthorizedPaymentsProcessor::capture_authorized_payment()
    wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php:690
    WooCommerce\P\W\WCGatewayModule::WooCommerce\P\W\{closure}()
    wp-includes/class-wp-hook.php:324
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php:173
    WC_Meta_Box_Order_Actions::save()
    wp-includes/class-wp-hook.php:324
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php:263
    WC_Admin_Meta_Boxes::save_meta_boxes()
    wp-includes/class-wp-hook.php:326
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:348
    WP_Hook::do_action()
    wp-includes/plugin.php:517
    do_action()
    wp-includes/post.php:4828
    wp_insert_post()
    wp-includes/post.php:4930
    wp_update_post()
    wp-admin/includes/post.php:453
    edit_post()
    wp-admin/post.php:2270

**Other Issues**

This is a minor additional problem but adding tracking number to the PayPal Shipment Tracking it also gives us an error on some orders but others it goes in without any issues.

**Comment by outpost5441** [comment]
We actually just had a Customer order that came through showing as failed and two minutes later it processed to On Hold.

> Failed to process the payment. Please try again or contact the shop admin. [Error] Unknown error while connecting to PayPal. Status code: 0. CreditCardGateway.php:591 [Error] Unknown error while connecting to PayPal. Status code: 0. OrderEndpoint.php:584 Order status changed from Pending payment to Failed.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/170123982/4b982268-8489-415d-af1e-b7cc911abb34)

**Comment by outpost5441** [comment]
The same customer just did another order and they had no issues.

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/170123982/b0a2f285-0ec4-4af2-9693-f33205125f8c)

**Comment by SydeKrystian** [comment]
Hello @outpost5441 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
