### ISSUE TITLE
Payment received on Paypal but order missing on Woocommerce

### ISSUE THREAD

**Issue by csemplici** [woocommerce/woocommerce-paypal-payments#2253]
Hi,
In the last week we had problems with some orders. We receive the payment from the customer on our Paypal account but there is no order created on Woocommerce, so we can't ship the order because we don't know the order is created.

In attached you can see 2 orders for example. Customers wrote us they made the payment but they didn't receive the confirmation email and of course they don't receive the products.

Let me know how we can check the situation. It's a serious problem because customers thinks this is a fraud.

### Environment

 - WordPress Version 6.5.3
 - WooCommerce Version 8.8.3
 - Plugin Version 2.7.0

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://ayay.it
Site address (URL): https://ayay.it
WC Version: 8.8.3
REST API Version: ✔ 8.8.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 8.1.2-1ubuntu2.17
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.16-MariaDB-0ubuntu0.22.04.1-log
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Il tuo server non ha la classe SoapClient attiva - alcuni plugin gateway che usano SOAP potrebbero non funzionare correttamente.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: wp_
Dimensione totale database: 3097.09MB
Dimensione dati database: 1548.80MB
Dimensione indice database: 1548.29MB
wp_woocommerce_sessions: Dati: 31.05MB + indice: 2.02MB + motore InnoDB
wp_woocommerce_api_keys: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_order_items: Dati: 29.56MB + indice: 32.16MB + motore InnoDB
wp_woocommerce_order_itemmeta: Dati: 337.86MB + indice: 232.61MB + motore InnoDB
wp_woocommerce_tax_rates: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_shipping_zones: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_woocommerce_payment_tokens: Dati: 0.41MB + indice: 0.19MB + motore InnoDB
wp_woocommerce_payment_tokenmeta: Dati: 1.52MB + indice: 0.95MB + motore InnoDB
wp_woocommerce_log: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_actions: Dati: 27.56MB + indice: 28.11MB + motore InnoDB
wp_actionscheduler_claims: Dati: 0.33MB + indice: 0.20MB + motore InnoDB
wp_actionscheduler_groups: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_actionscheduler_logs: Dati: 19.56MB + indice: 15.03MB + motore InnoDB
wp_ac_abandoned_cart_history_lite: Dati: 7.23MB + indice: 0.00MB + motore InnoDB
wp_ac_email_templates_lite: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_ac_guest_abandoned_cart_history_lite: Dati: 3.52MB + indice: 0.00MB + motore InnoDB
wp_ac_sent_history_lite: Dati: 0.30MB + indice: 0.00MB + motore InnoDB
wp_aioseo_posts: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_automatewoo_customers: Dati: 8.52MB + indice: 15.91MB + motore InnoDB
wp_automatewoo_customer_meta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_automatewoo_events: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_automatewoo_guests: Dati: 4.52MB + indice: 7.70MB + motore InnoDB
wp_automatewoo_guest_meta: Dati: 15.52MB + indice: 16.77MB + motore InnoDB
wp_automatewoo_logs: Dati: 4.52MB + indice: 5.55MB + motore InnoDB
wp_automatewoo_log_meta: Dati: 18.55MB + indice: 15.03MB + motore InnoDB
wp_automatewoo_queue: Dati: 0.22MB + indice: 0.30MB + motore InnoDB
wp_automatewoo_queue_meta: Dati: 1.02MB + indice: 0.59MB + motore InnoDB
wp_automatewoo_unsubscribes: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_bwf_actions: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_bwf_action_claim: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_bwf_contact: Dati: 6.52MB + indice: 6.88MB + motore InnoDB
wp_bwf_contact_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_bwf_wc_customers: Dati: 3.52MB + indice: 1.83MB + motore InnoDB
wp_cli_cookie_scan: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cli_cookie_scan_categories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_cli_cookie_scan_cookies: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_cli_cookie_scan_url: Dati: 0.05MB + indice: 0.00MB + motore InnoDB
wp_cli_scripts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_cli_visitor_details: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_commentmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_comments: Dati: 84.63MB + indice: 56.11MB + motore InnoDB
wp_hfcm_scripts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_hurrytimer_evergreen: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_links: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_litespeed_img_optm: Dati: 2.52MB + indice: 0.72MB + motore InnoDB
wp_litespeed_img_optming: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_options: Dati: 24.48MB + indice: 13.27MB + motore InnoDB
wp_pmxi_files: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_hash: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_history: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_images: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_pmxi_imports: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_posts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_pmxi_templates: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_postmeta: Dati: 454.70MB + indice: 845.58MB + motore InnoDB
wp_posts: Dati: 65.23MB + indice: 18.97MB + motore InnoDB
wp_rank_math_404_logs: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_rank_math_analytics_objects: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
wp_rank_math_internal_links: Dati: 0.28MB + indice: 0.11MB + motore InnoDB
wp_rank_math_internal_meta: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_revslider_css: Dati: 0.13MB + indice: 0.03MB + motore InnoDB
wp_revslider_layer_animations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_revslider_navigations: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_revslider_sliders: Dati: 0.20MB + indice: 0.03MB + motore InnoDB
wp_revslider_sliders7: Dati: 0.06MB + indice: 0.02MB + motore InnoDB
wp_revslider_slides: Dati: 0.09MB + indice: 0.03MB + motore InnoDB
wp_revslider_slides7: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wp_revslider_static_slides: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_sbi_feeds: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_sbi_feed_caches: Dati: 0.03MB + indice: 0.02MB + motore InnoDB
wp_sbi_instagram_feeds_posts: Dati: 0.05MB + indice: 0.03MB + motore InnoDB
wp_sbi_instagram_feed_locator: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_sbi_instagram_posts: Dati: 2.02MB + indice: 0.00MB + motore InnoDB
wp_sbi_sources: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_termmeta: Dati: 0.09MB + indice: 0.08MB + motore InnoDB
wp_terms: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_term_relationships: Dati: 0.17MB + indice: 0.11MB + motore InnoDB
wp_term_taxonomy: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_usermeta: Dati: 291.95MB + indice: 155.34MB + motore InnoDB
wp_users: Dati: 10.52MB + indice: 8.55MB + motore InnoDB
wp_wc_admin_notes: Dati: 0.11MB + indice: 0.00MB + motore InnoDB
wp_wc_admin_note_actions: Dati: 0.08MB + indice: 0.02MB + motore InnoDB
wp_wc_category_lookup: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wc_customer_lookup: Dati: 9.52MB + indice: 7.02MB + motore InnoDB
wp_wc_download_log: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_gpf_render_cache: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_order_coupon_lookup: Dati: 1.52MB + indice: 2.67MB + motore InnoDB
wp_wc_order_product_lookup: Dati: 28.56MB + indice: 27.69MB + motore InnoDB
wp_wc_order_stats: Dati: 11.52MB + indice: 9.13MB + motore InnoDB
wp_wc_order_tax_lookup: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wc_product_attributes_lookup: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_download_directories: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_product_meta_lookup: Dati: 0.11MB + indice: 0.13MB + motore InnoDB
wp_wc_rate_limits: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_reserved_stock: Dati: 0.16MB + indice: 0.00MB + motore InnoDB
wp_wc_tax_rate_classes: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wc_webhooks: Dati: 0.02MB + indice: 0.02MB + motore InnoDB
wp_wdr_order_discounts: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wdr_order_item_discounts: Dati: 0.25MB + indice: 0.22MB + motore InnoDB
wp_wdr_rules: Dati: 0.08MB + indice: 0.00MB + motore InnoDB
wp_wfco_report_views: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wfocu_event: Dati: 10.52MB + indice: 13.55MB + motore InnoDB
wp_wfocu_event_meta: Dati: 17.55MB + indice: 0.00MB + motore InnoDB
wp_wfocu_session: Dati: 3.52MB + indice: 4.03MB + motore InnoDB
wp_wlr_earn_campaign: Dati: 0.02MB + indice: 0.09MB + motore InnoDB
wp_wlr_earn_campaign_transaction: Dati: 0.02MB + indice: 0.17MB + motore InnoDB
wp_wlr_levels: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wp_wlr_logs: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_wlr_points_ledger: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wlr_referral: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_wlr_rewards: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_wlr_reward_transactions: Dati: 0.02MB + indice: 0.08MB + motore InnoDB
wp_wlr_users: Dati: 0.08MB + indice: 0.09MB + motore InnoDB
wp_wlr_user_rewards: Dati: 0.02MB + indice: 0.11MB + motore InnoDB
wp_woobe_history: Dati: 0.02MB + indice: 0.05MB + motore InnoDB
wp_woobe_history_bulk: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_bundled_itemmeta: Dati: 0.41MB + indice: 0.47MB + motore InnoDB
wp_woocommerce_bundled_items: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_gc_activity: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_gc_cards: Dati: 0.02MB + indice: 0.06MB + motore InnoDB
wp_woocommerce_gc_cardsmeta: Dati: 0.02MB + indice: 0.03MB + motore InnoDB
wp_woocommerce_gpf_google_taxonomy: Dati: 4.02MB + indice: 0.23MB + motore InnoDB
wp_wow_mwp: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpmailsmtp_debug_events: Dati: 0.06MB + indice: 0.00MB + motore InnoDB
wp_wpmailsmtp_tasks_meta: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_wpmm_subscribers: Dati: 0.02MB + indice: 0.00MB + motore InnoDB
wp_yith_wcwl: Dati: 0.02MB + indice: 0.02MB + motore InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
attachment: 3710
aw_workflow: 3
br_labels: 1
carousels: 1
cfw_order_bumps: 46
cookielawinfo: 59
custom_css: 2
customize_changeset: 53
hurrytimer_countdown: 2
mpc_content_preset: 12
nav_menu_item: 50
oembed_cache: 17
page: 41
portfolio: 12
post: 282
product: 351
product_variation: 210
revision: 1335
shop_coupon: 387
shop_order: 76175
shop_order_refund: 1691
thppopuptemplate: 1
vc_settings_preset: 5
wcpb_product_badge: 14
wcps: 2
wcps_layout: 6
web-story: 4
wfocu_funnel: 47
wfocu_offer: 123
wlwl_email: 75
woo_mb_template: 12
wp_block: 1
wp_global_styles: 1
wpcf7_contact_form: 2
wpclv: 3
wpcode: 2
yith-wcbm-badge: 1
ywdpd_discount: 2
ywrac_cart: 6
ywrac_email: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Advanced Custom Fields: by WP Engine – 6.2.9
AutomateWoo: by WooCommerce – 4.9.5 (aggiornamento alla versione 6.0.24 disponibile)
CheckoutWC: by Objectiv – 7.10.5
Cloudflare: by Cloudflare
Inc. – 4.12.7

Contact Form 7: by Takayuki Miyoshi – 5.9.4
Cost of Goods for WooCommerce Pro: by WPFactory – 3.1.5
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Duplicate Page and Post: by Arjun Thakur – 2.9.4
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
Facebook for WooCommerce: by Facebook – 3.2.2
Goaffpro Affiliate Marketing: by Goaffpro – 2.7.9
Google Tag Manager for WooCommerce PRO: by Tag Concierge – 1.11.4
Header Footer Code Manager: by 99robots – 1.1.37
WooCommerce HookMeUp: by Get Bowtied – 2.5.1
WPCode Lite: by WPCode – 2.1.12
Feed Instagram di Smash Balloon: by Smash Balloon – 6.3.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.8.0
Klaviyo: by Klaviyo
Inc. – 3.3.5

Loco Translate: by Tim Whitlock – 2.6.9
Metrilo for WooCommerce: by Metrilo – 2.0.12
Modal Window: by Wow-Company – 5.3.10
Massive Addons for WPBakery Page Builder: by MassivePixelCreation – 2.4.8
Render shortcodes: by  – 1.0
Scalapay Gateway Easy Installment: by Scalapay – 3.2.0
Rank Math SEO with AI Best SEO Tools: by Rank Math – 1.0.219
Shopkeeper Extender: by Get Bowtied – 3.7
TikTok: by TikTok – 1.2.5
Top Bar: by WP Darko – 3.0.6
Twenty20 Image Before-After: by Zayed Baloch – 1.6.1
Web Stories: by Google – 1.36.0
CTX Feed: by WebAppick – 6.4.30
Converter for Media: by matt plugins – 5.12.5
Discount Rules PRO 2.0: by Flycart – 2.6.3
Discount Rules Core: by Flycart – 2.6.3
Advanced Order Export For WooCommerce: by AlgolPlus – 3.5.1
WooCommerce Satispay: by Satispay – 2.2.2
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.20.0
BEAR – Bulk Editor and Products Manager Professional for WooCommerce: by realmag777 – 2.1.3.1
Table Rate Shipping for WooCommerce: by JEM Plugins – 2.29
WooCommerce Free Gift Coupons: by Kathy Darling – 3.6.0 (aggiornamento alla versione 3.7.0 disponibile)
WooCommerce Stripe Gateway: by WooCommerce – 8.2.0
Woo Gift Cards: by Woo – 1.16.11 (aggiornamento alla versione 1.16.14 disponibile)
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce PayPal Payments: by WooCommerce – 2.7.0
WooCommerce Product Bundles: by SomewhereWarm – 5.13.3 (aggiornamento alla versione 7.1.1 disponibile)
WooCommerce Google Product Feed: by Ademti Software Ltd. – 10.5.3 (aggiornamento alla versione 11.0.7 disponibile)
WooCommerce: by Automattic – 8.8.3 (aggiornamento alla versione 8.9.1 disponibile)
WooCommerce Email Customizer with Drag and Drop Email Builder: by Flycart Technologies LLP – 1.5.16
UpStroke: Multi Product Offers: by WooFunnels – 1.2.0
UpStroke: WooCommerce Reports: by WooFunnels – 1.5.0
WP Mail SMTP: by WP Mail SMTP – 4.0.1
WPC Linked Variation for WooCommerce: by WPClever – 4.2.3
WPC Sticky Add To Cart for WooCommerce: by WPClever – 2.0.5

### Inactive Plugins (15) ###

Cookie-Script.com: by Cookie-Script.com – 1.0.4
Customer Reviews for WooCommerce: by CusRev – 5.48.1
Custom Product Boxes: by CodeIncept – 1.0.8
FunnelKit One Click Upsells: by Funnelkit – 3.5.2
FunnelKit One Click Upsells: by Funnelkit – 3.5.2
HurryTimer: by Nabil Lemsieh – 2.10.0
Product Badges: by 99w – 2.1.4 (aggiornamento alla versione 3.0.1 disponibile)
Slider Revolution: by ThemePunch – 6.7.0
SumoMe: by SumoMe – 1.35
WooCommerce Custom Product Addons Free: by Acowebs – 3.0.8
WooCommerce Dynamic Pricing & Discounts: by پرشین اسکریپت – 2.4.5
WPGraphQL: by WPGraphQL – 1.26.0
WPGraphQL for ACF: by WPGraphQL
Jason Bahl – 2.2.0

WPGraphQL WooCommerce (WooGraphQL): by kidunot89 – 0.19.0
WPLoyalty: by wployalty – 1.2.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wbs_bundle (wbs_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 giorni
Level threshold: –
Log directory size: 2 GB

### WC Pages ###

Shop base: #5 - /shop/
Carrello: #6 - /cart/
Cassa: #2851 - /checkout/
Il mio account: #2852 - /my-account/
Termini e condizioni: #3024 - /termini-e-condizioni/

### Theme ###

Name: Shopkeeper Child
Version: 1.0
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.9.48
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php versione 3.4.0 è obsoleta. La versione attuale è 8.6.0
shopkeeper/woocommerce/checkout/form-coupon.php versione 3.4.4 è obsoleta. La versione attuale è 7.0.1
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper-child/woocommerce/checkout/terms.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper-child/woocommerce/emails/customer-processing-order.php
shopkeeper/woocommerce/global/quantity-input.php versione 4.0.0 è obsoleta. La versione attuale è 7.8.0
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/myaccount/form-login.php versione 4.1.0 è obsoleta. La versione attuale è 7.0.1
shopkeeper/woocommerce/single-product/add-to-cart/simple.php versione 3.4.0 è obsoleta. La versione attuale è 7.0.1
shopkeeper/woocommerce/single-product/product-image.php versione 3.5.1 è obsoleta. La versione attuale è 7.8.0
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Scopri come aggiornare

### WooCommerce Google Product Feed feeds ###

google: Google merchant centre product feed
  Type: google
  Category filter: -
  Categories: -
googleinventory: Google merchant centre product inventory feed (legacy)
  Type: googleinventory
  Category filter: -
  Categories: -

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send "item group ID": Enabled
Expanded schema markup: -
Debug key: 7633392f-1ae8-409d-8dfe-a96ce7c3993b

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Product description: Main product description only (full preferred)
Availability (in stock products): Defaults to "in stock".
Availability (backordered products): Defaults to "in stock".
Availability (out of stock products): Defaults to "out of stock".
Bundle indicator (is_bundle): 
Brand: Defaults to "AYAY".
Manufacturer Part Number (MPN): 
Product Type: Defaults to "Salute e bellezza > Cura della persona > Cosmetici > Bagno e corpo". Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Salute e bellezza > Cura della persona > Cosmetici > Bagno e corpo".
Gender: Defaults to "unisex".
Custom label 0: Pre-populates from product_cat taxonomy.
Custom label 1: Pre-populates from product_cat taxonomy.
Custom label 2: Pre-populates from product_cat taxonomy.

### WooCommerce Google Product Feed DB status ###

Database version: 15
Active database version: 15
wc_gpf_render_cache: Empty
woocommerce_gpf_google_taxonomy (en-US): 5595 items
woocommerce_gpf_google_taxonomy (it-IT): 5595 items

### Gift Cards ###

Database Version: 1.16.11
Loopback Test: ✔
Task Queueing Test: ✔

### Product Bundles ###

Database Version: 5.13.3
Template Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-05-23 10:20:03 +02:00
Options: ✔
Notes: 191
Onboarding: completed

### Action Scheduler ###

Complete: 67.089
Oldest: 2024-04-21 15:07:55 +0200
Newest: 2024-05-22 15:10:45 +0200

Failed: 10.086
Oldest: 2019-11-13 13:15:46 +0100
Newest: 2024-04-08 11:28:20 +0200

Pending: 8
Oldest: 2024-05-22 15:15:50 +0200
Newest: 2024-05-23 14:22:30 +0200

### Status report information ###

Generated at: 2024-05-22 15:11:18 +02:00
`
</details>

**Comment by salmanbukhari1** [comment]
@csemplici I am also facing this issue. how did you resolve?
