### ISSUE TITLE
Problem with Blik payment via PayPal plugin

### ISSUE THREAD

**Issue by zapservice** [woocommerce/woocommerce-paypal-payments#2270]
### Describe the Bug

In half (!) of cases, clients are unable to successfully pay for Blik via PayPal. The money is withdrawn from their account, but the order is not placed. After 1-2 days, their banks (a variety of Polish banks) return the funds. We learn about such orders only because customers write to us, concerned that their money was withdrawn, but they did not receive information about the confirmation/fulfillment of the order.

The other half of clients place orders successfully.
### To Reproduce

Now Blik payment has been removed from the site to avoid problems with orders.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @zapservice 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
