### ISSUE TITLE
Can't disable "Require final confirmation on checkout"

### ISSUE THREAD

**Issue by veptune** [woocommerce/woocommerce-paypal-payments#2276]
Hello there,

The checkbox “Require final confirmation on checkout” does not work. 

Even if I disable it, it acts as it is enabled.

I unchecked the checkbox but it is still the same. The PayPal button is still “Review my order” instead of “Pay” and the user is returned to the checkout page (and needs to click on the Order button.

Here is my setup :

WordPress 6.5.3
WooCommerce 8.9.1
WooCommerce PayPal Payments 2.7.0

Thanks

**Comment by InpsydeNiklas** [comment]
Hi @veptune, in version 2.7.0, the checkout page can only be skipped for payments initiated on the **Block Cart** or the **Block Express Checkout.** 
Support for this skipping the Checkout page with the other express button locations (e.g. single product, Classic Cart, Mini Cart) has been added in the upcoming 2.7.1 update: https://github.com/woocommerce/woocommerce-paypal-payments/releases
This is expected to be released later today.
If any questions or issues remain, I recommend [contacting the support team directly form here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
