### ISSUE TITLE
Unfortunately, your credit card details are not valid.

### ISSUE THREAD

**Issue by prodweb1** [woocommerce/woocommerce-paypal-payments#2280]
Hello,

We updated to 2.7.1 this morning.

Since this morning, I’ve been experiencing a problem on our online store. It’s become impossible to pay with a credit card, the message “Unfortunately, your credit card details are not valid.” is systematically displayed. Of course, we’ve tested this with several cards.

We tried to restore the old version 2.7.0, but the problem persists.

Paypal account payments work normally.

please help us.

**Comment by SydeKrystian** [comment]
Hello @prodweb1 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
