### ISSUE TITLE
Fatal error on non-PayPal orders when a supported shipment tracking plugin is active

### ISSUE THREAD

**Issue by WillowWintersPublishing** [woocommerce/woocommerce-paypal-payments#2285]
### Describe the Bug

When we go to buy a shipping label the payment goes through, but then we get a critical error.

### To Reproduce

1. Go to  buy a shipping label in woocommerce
2. Click on purchase shipping label
3. See error

### Screenshots

![Paypal error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/171205927/47bcd629-f54b-42e8-a32f-b11c17eca55c)

### Expected Behavior

A label print screen should come up

### Environment

 - WordPress Version 6.5.3
 - WooCommerce Version 8.9.1
 - Plugin Version 2.7.1
 - Browser [e.g. Chrome, Safari] and Version All browsers
 - Any other plugins installed
Advanced Custom Fields PRO |   | by WP Engine – 6.3.0.1
AutomateWoo |   | by WooCommerce – 6.0.24
Conditional Fields for Contact Form 7 |   | by Jules Colle – 2.4.12
Cloudflare |   | by Cloudflare, Inc. – 4.12.7
Contact Form 7 |   | by Takayuki Miyoshi – 5.9.5
Debug Log Manager |   | by Bowo – 2.3.3
Facebook for WooCommerce |   | by Facebook – 3.2.3
Flamingo |   | by Takayuki Miyoshi – 2.5
Genesis eNews Extended |   | by Brandon Kraft – 2.2.0
IgniteWoo Updater |   | by IgniteWoo.com – 3.0.4 – Network enabled
Imagify |   | by Imagify – Optimize Images & Convert WebP & Avif – 2.2.2
Solid Security Pro |   | by SolidWP – 8.4.2
Jetpack |   | by Automattic – 13.4.3
Kadence Blocks - PRO Extension |   | by Kadence WP – 2.3.9
Kadence Blocks – Gutenberg Blocks for Page Builder Features |   | by Kadence WP – 3.2.40
Kadence Custom Fonts |   | by Kadence WP – 1.1.5
Kadence Pro - Premium addon for the Kadence Theme |   | by Kadence WP – 1.0.20
Kadence AI Starter Templates |   | by Kadence WP – 2.1.3
Kadence Shop Kit |   | by Kadence WP – 2.1.0
Mailchimp for WooCommerce |   | by Mailchimp – 4.0.2
Microsoft Clarity |   | by Microsoft – 0.9.4
MouseWheel Smooth Scroll |   | by KubiQ – 6.5
Meta pixel for WordPress |   | by Facebook – 3.0.16
Printful Integration for WooCommerce |   | by Printful – 2.2.7
Printify Shipping Method |   | by Printify – 2.8
PW WooCommerce Gift Cards |   | by Pimwick, LLC – 1.254
reCaptcha for WooCommerce |   | by I Thirteen Web Solution – 2.50
Shortcodes Ultimate |   | by Vova Anokhin – 7.1.6
Transients Manager |   | by WPBeginner – 2.0.5
UpdraftPlus - Backup/Restore |   | by UpdraftPlus.Com, DavidAnderson – 1.24.3
User Menus |   | by Code Atlantic – 1.3.2
Widget Importer & Exporter |   | by ChurchThemes.com – 1.6.1
Woo Align Buttons |   | by 320up – 3.7.0
Advanced Order Export For WooCommerce |   | by AlgolPlus – 3.5.2
Woo Store Vacation |   | by MyPreview – 1.9.4
WooCommerce.com Update Manager |   | by Automattic – 1.0.2
WooCommerce Cost of Goods |   | by SkyVerge – 2.13.1
WooCommerce Customer/Order/Coupon Export |   | by SkyVerge – 5.5.1
WooCommerce Stripe Gateway |   | by WooCommerce – 8.3.0
WooCommerce PayPal Payments |   | by WooCommerce – 2.7.1
PDF Invoices & Packing Slips for WooCommerce |   | by WP Overnight – 3.8.2
WooCommerce Points and Rewards |   | by WooCommerce – 1.8.2
WooCommerce Pre-Orders |   | by WooCommerce – 2.1.0
WooCommerce Protected Categories |   | by Barn2 Plugins – 2.7.2
WooCommerce Shipping & Tax |   | by WooCommerce – 2.5.7
WooCommerce USPS Shipping |   | by WooCommerce – 4.8.6
WooCommerce Subscriptions |   | by WooCommerce – 6.3.2
WooCommerce |   | by Automattic – 8.9.1
Yoast SEO Premium |   | by Team Yoast – 22.8
Yoast SEO |   | by Team Yoast – 22.8
WP Mail SMTP |   | by WP Mail SMTP – 4.0.1
WPB Related Products Slider for WooCommerce |   | by wpbean – 1.3.7

</body>
</html>
### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
[Advanced Custom Fields PRO](https://www.advancedcustomfields.com/)	 	by WP Engine – 6.3.0.1
[AutomateWoo](https://automatewoo.com/)	 	by WooCommerce – 6.0.24
[Conditional Fields for Contact Form 7](http://bdwm.be/)	 	by Jules Colle – 2.4.12
[Cloudflare](https://blog.cloudflare.com/new-wordpress-plugin/)	 	by Cloudflare, Inc. – 4.12.7
[Contact Form 7](https://contactform7.com/)	 	by Takayuki Miyoshi – 5.9.5
[Debug Log Manager](https://wordpress.org/plugins/debug-log-manager/)	 	by Bowo – 2.3.3
[Facebook for WooCommerce](https://github.com/woocommerce/facebook-for-woocommerce/)	 	by Facebook – 3.2.3
Flamingo	 	by Takayuki Miyoshi – 2.5
[Genesis eNews Extended](https://kraft.blog/genesis-enews-extended/)	 	by Brandon Kraft – 2.2.0
[IgniteWoo Updater](https://ignitewoo.com/)	 	by IgniteWoo.com – 3.0.4 – Network enabled
[Imagify](https://wordpress.org/plugins/imagify/)	 	by Imagify – Optimize Images & Convert WebP & Avif – 2.2.2
[Solid Security Pro](https://solidwp.com/security)	 	by SolidWP – 8.4.2
[Jetpack](https://jetpack.com/)	 	by Automattic – 13.4.3
[Kadence Blocks - PRO Extension](https://www.kadencewp.com/product/kadence-gutenberg-blocks/)	 	by Kadence WP – 2.3.9
[Kadence Blocks – Gutenberg Blocks for Page Builder Features](https://www.kadencewp.com/product/kadence-gutenberg-blocks/)	 	by Kadence WP – 3.2.40
Kadence Custom Fonts	 	by Kadence WP – 1.1.5
[Kadence Pro - Premium addon for the Kadence Theme](https://www.kadencewp.com/kadence-theme/premium/)	 	by Kadence WP – 1.0.20
Kadence AI Starter Templates	 	by Kadence WP – 2.1.3
[Kadence Shop Kit](https://www.kadencewp.com/product/kadence-woo-extras/)	 	by Kadence WP – 2.1.0
[Mailchimp for WooCommerce](https://mailchimp.com/connect-your-store/)	 	by Mailchimp – 4.0.2
[Microsoft Clarity](https://clarity.microsoft.com/)	 	by Microsoft – 0.9.4
[MouseWheel Smooth Scroll](https://kubiq.sk/)	 	by KubiQ – 6.5
[Meta pixel for WordPress](https://www.facebook.com/business/help/881403525362441)	 	by Facebook – 3.0.16
[Printful Integration for WooCommerce](https://wordpress.org/plugins/printful-shipping-for-woocommerce/)	 	by Printful – 2.2.7
[Printify Shipping Method](https://wordpress.org/plugins/printify-for-woocommerce/)	 	by Printify – 2.8
[PW WooCommerce Gift Cards](https://www.pimwick.com/gift-cards/)	 	by Pimwick, LLC – 1.254
[reCaptcha for WooCommerce](https://wordpress.org/plugins/woo-recpatcha)	 	by I Thirteen Web Solution – 2.50
[Shortcodes Ultimate](https://getshortcodes.com/)	 	by Vova Anokhin – 7.1.6
[Transients Manager](https://wordpress.org/plugins/transients-manager/)	 	by WPBeginner – 2.0.5
[UpdraftPlus - Backup/Restore](https://updraftplus.com/)	 	by UpdraftPlus.Com, DavidAnderson – 1.24.3
[User Menus](https://wordpress.org/plugins/user-menus/)	 	by Code Atlantic – 1.3.2
[Widget Importer & Exporter](https://churchthemes.com/plugins/widget-importer-exporter/)	 	by ChurchThemes.com – 1.6.1
[Woo Align Buttons](https://wordpress.org/plugins/woo-align-buttons)	 	by 320up – 3.7.0
Advanced Order Export For WooCommerce	 	by AlgolPlus – 3.5.2
[Woo Store Vacation](https://mypreview.one/woo-store-vacation)	 	by MyPreview – 1.9.4
WooCommerce.com Update Manager	 	by Automattic – 1.0.2
[WooCommerce Cost of Goods](http://www.woocommerce.com/products/woocommerce-cost-of-goods/)	 	by SkyVerge – 2.13.1
[WooCommerce Customer/Order/Coupon Export](http://www.woocommerce.com/products/ordercustomer-csv-export/)	 	by SkyVerge – 5.5.1
[WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/)	 	by WooCommerce – 8.3.0
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	 	by WooCommerce – 2.7.1
[PDF Invoices & Packing Slips for WooCommerce](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-bundle/)	 	by WP Overnight – 3.8.2
[WooCommerce Points and Rewards](https://woocommerce.com/products/woocommerce-points-and-rewards/)	 	by WooCommerce – 1.8.2
[WooCommerce Pre-Orders](https://woocommerce.com/products/woocommerce-pre-orders/)	 	by WooCommerce – 2.1.0
[WooCommerce Protected Categories](https://barn2.co.uk/wordpress-plugins/woocommerce-protected-categories/)	 	by Barn2 Plugins – 2.7.2
[WooCommerce Shipping & Tax](https://woocommerce.com/)	 	by WooCommerce – 2.5.7
[WooCommerce USPS Shipping](https://woocommerce.com/products/usps-shipping-method/)	 	by WooCommerce – 4.8.6
[WooCommerce Subscriptions](https://www.woocommerce.com/products/woocommerce-subscriptions/)	 	by WooCommerce – 6.3.2
[WooCommerce](https://woocommerce.com/)	 	by Automattic – 8.9.1
[Yoast SEO Premium](https://yoa.st/2jc)	 	by Team Yoast – 22.8
[Yoast SEO](https://yoa.st/1uj)	 	by Team Yoast – 22.8
[WP Mail SMTP](https://wpmailsmtp.com/)	 	by WP Mail SMTP – 4.0.1
[WPB Related Products Slider for WooCommerce](http://wpbean.com/plugins/)	 	by wpbean – 1.3.7

**Comment by InpsydeNiklas** [comment]
Apologies for the trouble with the latest update! A new plugin version with a fix for this error will be available [here in the Release section](https://github.com/woocommerce/woocommerce-paypal-payments/releases) by Monday.
In the meantime, you can [download and install the previous version 2.7.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.7.0) to prevent this error for now.
