### ISSUE TITLE
card payment not working

### ISSUE THREAD

**Issue by Moskagithub** [woocommerce/woocommerce-paypal-payments#2286]
<img width="1310" alt="Screenshot 2024-05-28 at 06 09 23" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/171227837/a68b2760-2886-4598-99a3-d02ebb833b3b">
### Describe the Bug

Cleint can't pay with cards. All the time we have error massage. Please see attachemnt.
I cecked a forums, and I see that this problem has many users. Please help!

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Moskagithub 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
