### ISSUE TITLE
error con uno de tus plugins, WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by fotogorane** [woocommerce/woocommerce-paypal-payments#2291]
### Describe the Bug

WordPress tiene una característica incluida que detecta cuando un plugin o tema provoca un error fatal en tu sitio, y te avisa con este correo electrónico automático.

En este caso, WordPress ha detectado un error con uno de tus plugins, WooCommerce PayPal Payments.

Antes de nada visita tu web (https://www.tximis.es/) y revisa cualquier problema visible. A continuación visita la página donde se capturó el error (https://www.tximis.es/wp-admin/post.php) y revisa cualquier problema visible.

Por favor, ponte en contacto con tu alojamiento para que te ayude a investigar más a fondo este problema.

Si tu sitio se muestra roto y no puedes acceder normalmente a tu escritorio, WordPress tiene un «modo de recuperación» especial. Esto te permite acceder de manera segura a tu escritorio y seguir investigando.

https://www.tximis.es/wp-login.php?action=enter_recovery_mode&amp;rm_token=8ZcXamQ7qbBlgBp3nLDMNb&amp;rm_key=RpCf9A9VgenexD5PaT4Z9i

Para mantener a salvo tu sitio, este enlace caducará en 1 día. No te preocupes por eso, a pesar de esto se te enviará un nuevo enlace por correo electrónico si ocurre de nuevo el error después de que caduque.

A la hora de buscar ayuda con este problema puede que se te pida algo de la siguiente información:
WordPress versión 6.5.3
Tema activo: Astra Child (versión 3.8.2.1654621593)
Plugin actual: WooCommerce PayPal Payments (versión 2.7.1)
PHP versión 8.0.30

Detalles del error
==================
Se ha producido un error del tipo E_ERROR en la línea 38 del archivo /usr/home/tximis.es/web/wp-content/plugins/woocommerce-paypal-payments/api/order-functions.php. Mensaje de error: Uncaught InvalidArgumentException: PayPal order ID not found in meta. in /usr/home/tximis.es/web/wp-content/plugins/woocommerce-paypal-payments/api/order-functions.php:38
Stack trace:
#0 /usr/home/tximis.es/web/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Integration/YithShipmentIntegration.php(83): WooCommerce\PayPalCommerce\Api\ppcp_get_paypal_order('')
#1 /usr/home/tximis.es/web/wp-includes/class-wp-hook.php(326): WooCommerce\PayPalCommerce\OrderTracking\Integration\YithShipmentIntegration->WooCommerce\PayPalCommerce\OrderTracking\Integration\{closure}(6542)
#2 /usr/home/tximis.es/web/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
This issue duplicates https://github.com/woocommerce/woocommerce-paypal-payments/issues/2285, so I will close it.
