### ISSUE TITLE
Show the “Payments Title and discription” texts saved in settings no matter how many times the user check out.

### ISSUE THREAD

**Issue by abdulmanan11** [woocommerce/woocommerce-paypal-payments#2293]
### Describe the Bug

I have changed the title and description of payment methods in the settings and it shows correctly on checkout page, But once the user checkout and tries to order again and goes to checkout page. the default title and description is being displayed. Instead of the saved title and description

### To Reproduce

1. Go to 'Any product and make a order using debit and credit card on the checkout page'
2. Now after successfully making an order try to make another order and when you will go to checkout page 
3. Default title and description of payment methods will show instead of the saved one

### Screenshots

Title and description shows normally here on first time checkout 
Title: Payments
Description: None
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/58119178/b0ff20de-836d-40ee-92d9-31572764273d)

After checking out with debit or credit card if we order again and go to checkout page 
The default title and description is being shown 

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/58119178/57d8ef2b-3a80-4705-8615-86416e5e7b6f)

 - WordPress Version (6.5.3)
 - WooCommerce Version (8.9.0 )
 - Plugin Version (2.7.0)
 - Browser Chrome

**Comment by SydeKrystian** [comment]
Hello @abdulmanan11 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
