### ISSUE TITLE
WooCommerce PayPal Payments version 2.7.1 is broken

### ISSUE THREAD

**Issue by SweetlyDivine** [woocommerce/woocommerce-paypal-payments#2298]
When trying to print the label, the warning pops up, “There has been a critical error on this website” without any information.
I hear that downgrading to a 2.7.0 version will fix the issue, but I am not too savvy and not sure how to do that. So please fix the bug so I can print the labels. My business is at stand still at the moment

**Comment by carolframen** [comment]
There are several reports here: https://wordpress.org/support/topic/failed-to-retrieve-shipping-label-refund-status-2/
And another one here: https://wordpress.org/support/topic/there-has-been-a-critical-error-on-this-website-a-hrefhttps-wordp/

@SweetlyDivine , You can find older versions to download [here](https://wordpress.org/plugins/woocommerce-paypal-payments/advanced/).

If you prefer, you can also use a plugin such as WP Rollback to help you with this process. You can find the plugin [here](https://wordpress.org/plugins/wp-rollback/).

**Comment by m155y** [comment]
Another report of this in 8263645-zen

**Comment by ChrissiePollock** [comment]
Also in 8257814-zen

**Comment by ChrissiePollock** [comment]
#8256183-zen was also affected even though they did not report seeing any error message. They just could not print.

**Comment by InpsydeNiklas** [comment]
Hi folks, thanks for the issue report, and I apologize for the trouble. This error was resolved in #2289. 
It can be worked around either with a temporary downgrade to [version 2.7.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.7.0) or by installing the latest [pre-release  version 2.8.0-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.0-rc1) which is expected to be released officially next week.

If you need additional guidance on how to resolve the error, I recommend contacting our support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
