### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by aleksandrx** [woocommerce/woocommerce-paypal-payments#2300]
### Describe the Bug

Fatal error: Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. in /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:484

### To Reproduce

1. Go to WooCommerce - Orders
2. Trying to open an order
3. See error

### Screenshots

![Screenshot 2024-06-01 124646](https://github.com/woocommerce/woocommerce-paypal-payments/assets/22506564/cd23dfec-6402-40d1-954e-4be6c0a2ed1c)

### Expected Behavior

I was expecting to see an order

### Actual Behavior

Empty page

### Environment

 - WordPress Version 6.5.3
 - WooCommerce Version 8.9.1
 - Plugin Version 2.7.1

**Comment by InpsydeNiklas** [comment]
Hi @aleksandrx 
Thanks for the issue report, and I apologize for the trouble. This error was resolved in #2289. 
It can be worked around either with a temporary downgrade to [version 2.7.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.7.0) or by installing the latest [pre-release  version 2.8.0-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.0-rc1) which is expected to be released officially next week.

If you need additional guidance on how to resolve the error, I recommend contacting our support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!

**Comment by deeminzen** [comment]
Hello!

We're using (used) ver 8.0 (2024-06-11) and got this error.

Thank you for the suggestion to rollback to 7.0 (2024-04-30) which worked :)

Will PayPal correct this error in 8.0 ASAP?

-Thank YOU!

**Comment by premkumarbsetec** [comment]
Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. in /homepages/1/d887141122/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:484 

same issue at WooCommerce PayPal Payments Version 2.8.0

**Comment by tallcoder** [comment]
Same issue in 3.1.0
