### ISSUE TITLE
PayPal Pay Later Messaging Settings - Unable to deactivate on Product Page.

### ISSUE THREAD

**Issue by PracticeSpaceStudio** [woocommerce/woocommerce-paypal-payments#2302]
### Describe the Bug

On the WooCommerce settings page under Pay Later and Pay Later Messaging section, there is a checkbox to uncheck and deactivate Pay Later display on the Product page.  When this is unchecked and saved, it is automatically re-checked again.  There is currently no way to disable it on the Product Page - Feature is broken.  

### To Reproduce

See instructions above

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @PracticeSpaceStudio 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
