### ISSUE TITLE
Not showing PayPal button on the "Customer payment page"

### ISSUE THREAD

**Issue by sanesh-acowebs** [woocommerce/woocommerce-paypal-payments#2303]
### Describe the Bug

PayPal payment button is not showing on the customer payment page.  Please check the screen recording: https://tinyurl.com/23gf5et6

**Comment by InpsydeNiklas** [comment]
Hi @sanesh-acowebs, to see the PayPal payment method on the `Pay for Order` page, you must enable the `Classic Checkout` **Smart Button Location** in the Standard Payments tab:
<img width="873" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/f0f813ae-413f-47e0-b3cb-9c74580544f1">
 
If you need additional guidance with the plugin setup, recommend contacting our support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
