### ISSUE TITLE
Error plugin woocommerce paypal payments

### ISSUE THREAD

**Issue by Patriciacid24** [woocommerce/woocommerce-paypal-payments#2304]
WordPress tiene una característica incluida que detecta cuando un plugin o tema provoca un error fatal en tu sitio, y te avisa con este correo electrónico automático.

En este caso, WordPress ha detectado un error con uno de tus plugins, WooCommerce PayPal Payments.

A la hora de buscar ayuda con este problema puede que se te pida algo de la siguiente información:
WordPress versión 6.5.3
Tema activo: Hello Elementor (versión 2.6.1)
Plugin actual: WooCommerce PayPal Payments (versión 2.7.1)
PHP versión 8.1.27

**Comment by SydeKrystian** [comment]
Hello @Patriciacid24 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
