### ISSUE TITLE
Paypal Bug - Not collecting fees after cart

### ISSUE THREAD

**Issue by ac10mpo** [woocommerce/woocommerce-paypal-payments#2309]
When customers using paypal, its leaving off the shipping and small order fees.

**Comment by SydeKrystian** [comment]
Hello @ac10mpo 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
