### ISSUE TITLE
STYLING ISSUE with PAY LATER section

### ISSUE THREAD

**Issue by 51M0N3-3XC** [woocommerce/woocommerce-paypal-payments#2319]
Any style customization changes are not saved
tests conducted several times always clearing the cache

1. Go to 'Pay Later' tab (in WooCommerce > Payments)
2. Click and change any customization option on the left column
3. Scroll down and 'Save changes'
4. Open the corresponding page to see the results
5. NOTHING CHANGED

I would like it to work
I use a dark theme and it is stuck on the light version

### Environment

 - WordPress Version 6.5.3
 - PHP Version 8.3.7
 - WooCommerce Version 8.9.2
 - Plugin Version 2.7.1
 - Theme FlatSome Version 3.18.7
 - Browser Chrome Version 125.0.6422.142

**Comment by InpsydeNiklas** [comment]
Hi @51M0N3-3XC 
It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!
