### ISSUE TITLE
Uncaught Error: Cannot use object of type WooCommerce\PayPalCommerce\WcGateway\Settings\Settings as array in woocommerce/src/Blocks/Payments/Integrations/AbstractPaymentMethodType.php:34 (3253)

### ISSUE THREAD

**Issue by dennisnissle** [woocommerce/woocommerce-paypal-payments#2334]
### Describe the Bug

Seems like you are overriding the default `settings` attribute from the original, abstract `AbstractPaymentMethodType` with your custom Settings object. This leads to the fatal error:

`Uncaught Error: Cannot use object of type WooCommerce\PayPalCommerce\WcGateway\Settings\Settings as array in woocommerce/src/Blocks/Payments/Integrations/AbstractPaymentMethodType.php:34`

as soon as calling `get_setting()` on the payment object. Please either override the `get_setting()` method too or (better) do not override the settings attribute within your `AdvancedCardPaymentMethod` class.
https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-blocks/src/AdvancedCardPaymentMethod.php#L78

### Environment

Latest WP, Woo and PayPal Payments.

**Comment by dennisnissle** [comment]
@InpsydeNiklas  Any update on this issue? Seems more like a bug than a third party enhancement to me as you are clearly violating the Woo's object model.

**Comment by Dinamiko** [comment]
@dennisnissle sorry for the delay and thanks for letting us know about this issue, it should now not override `settings` property from the base class. This fix will be included in 2.8.3 release.
