### ISSUE TITLE
Order Details in missing in PayPal Order

### ISSUE THREAD

**Issue by dogdoy** [woocommerce/woocommerce-paypal-payments#2339]
### Describe the Bug

The order details in WooCommerce is ok, but when check at Paypal.com the detail is missing. It is working fine on April 14 order.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

![Order_detail_showed](https://github.com/woocommerce/woocommerce-paypal-payments/assets/16892667/f7521c97-6d73-4655-a3de-9cfff5c2cd2a)

![Order_detail_missing](https://github.com/woocommerce/woocommerce-paypal-payments/assets/16892667/5d46da7d-c34e-4f65-8843-9a970e39d2a7)

### Environment

 - WordPress Version 6.5.4
 - WooCommerce Version 8.9.3
 - Plugin Version 2.8.0
 - Browser Chrome Mac Version 125.0.6422.142 
 - Any other plugins installed CheckoutWC Lite 1.1.11, WooCommerce Better Usability 1.0.55, Woocommerce Side Cart Premium 4.0.4, WooCommerce Weight Based Shipping 5.9.1

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @dogdoy 
﻿
Thanks for reaching out to us, we're here to help.

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
