### ISSUE TITLE
No token renewal

### ISSUE THREAD

**Issue by chris013012** [woocommerce/woocommerce-paypal-payments#2344]
Hi,

For weeks, I have problem with the token renewal. The Paypal button is blocked after approx each 8-10Hours. Sometimes, there is the message "Authentication with PayPal failed: Could not create token.
Please verify your API Credentials and try again to connect your PayPal business account"
Then, when I do  "Refresh feature availability status" it works again.

I guess it was because cache plugin but it appears it comes from the module. Today, I've received the message:

https://XYZ.com/wp-login.php?action=enter_recovery_mode&rm_token=LCjnMIICriEkbpoWnzG2AP&rm_key=dsjr8qe5NmkYZJL0Nlv8ic

Pour garder votre site en sécurité, ce lien expirera dans 1 jour. Ne vous inquiétez cependant pas : un nouveau lien vous sera envoyé si l’erreur se présente à nouveau.

Si vous cherchez de l’aide pour ce problème, les informations suivantes pourraient vous être demandées :
WordPress version 6.5.4
Thème actif : Porto Child (version 1.1)
Extension actuelle : WooCommerce PayPal Payments (version 2.8.0)
PHP version 8.3.7

**Comment by SydeKrystian** [comment]
Hello @chris013012 
﻿
Thanks for reaching out to us, we're here to help.

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
