### ISSUE TITLE
paypal pay now button not active

### ISSUE THREAD

**Issue by Il-contabile** [woocommerce/woocommerce-paypal-payments#2347]
hello, when I try to make a payment via paypal, the payment button is visible but is not active.
It is grey and I can't complete the payment. 

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172844352/fc6de724-cd77-4195-9851-a561a3144b76)

Could you please help?
thanks
Luca

**Comment by SydeKrystian** [comment]
Hello @Il-contabile 

It seems that the issue might stem from the setup of your subscription products in PayPal Payments. For subscription products to work seamlessly with PayPal, each subscription must be tied to a properly configured plan.  You can also find a guide and more information in our [documentation](https://woo.com/document/woocommerce-paypal-payments/#paypal-subscriptions). If you've followed these steps and the issue persists please reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
