### ISSUE TITLE
Customer not charged shipping, and shipping details sometimes missing.

### ISSUE THREAD

**Issue by ScionOfDesign** [woocommerce/woocommerce-paypal-payments#2349]
### Describe the Bug

3 of the last 12 orders we have received have been able to go through _without having the user pay for shipping._
In some cases, no shipping details or even contact information was provided even though this is **required** when doing checkout.

### Screenshots

**1. No Shipping Paid and No Shipping Address Provided**
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/8867456/6a3cb054-0aca-4514-bfd0-4c43e0a7b99d)

**2. No Shipping Paid, and No Details Whatsoever**
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/8867456/f277d9f3-8ab9-44cf-8b96-084edb99d7f7)

**3. No SHipping Paid**
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/8867456/4c0747b9-c880-4461-95d4-a4dc2090ef69)

### Expected Behavior

Shipping details must be required, and shipping should be appropriately charged every time.

### Actual Behavior

In some cases, shipping is not charged, and sometimes shipping details are not even required or don't go through.

### Environment

 - WordPress Version **6.5.4**
 - WooCommerce Version **8.9.3**
 - Plugin Version **2.8.0**
 - Any other plugins installed 
   - **PayPal Zettle POS**
   - **WooCommerce Shipping & Tax**

**Comment by SydeKrystian** [comment]
Hello @ScionOfDesign 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
