### ISSUE TITLE
Translation missing from english to portuguese

### ISSUE THREAD

**Issue by modicharm** [woocommerce/woocommerce-paypal-payments#2350]
### Describe the Bug

I changed the Paypal payments plugin language from english to portuguese and not all text was traduced on the checkout page.

### To Reproduce

1. Add a product to basket
2. Click on 'Finalizar compras' button
3. Select Paypal payment method
4. See the translation is missing to portuguese a) "Clicking "Proceed to PayPal" will redirect you to PayPal to complete your purchase."
b)  Credit Card placehosders is also in english. c) Proceed to Checkout button is also not translated.

### Screenshots

![paypal translation missing](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172976568/4aab64f5-61ca-479e-b742-4f218d3ea1ef)
![paypal translation missing-credit card](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172976568/baeeeb74-a300-4ac6-ac98-4e9c11cadcf1)

### Environment

 - WordPress Version - WordPress 6.5.4, com o tema [Astra]
 - WooCommerce Version - Versão 8.9.3
 - Plugin Version - Versão 2.8.0
 - Browser - Chrome Versão 126.0.6478.62 (Compilação oficial) (64 bits)

**Comment by SydeKrystian** [comment]
Hello @modicharm 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by crascher** [comment]
Hi what is the solution for the issue? I am having the same problem. The whole Woocommerce shop is showing german language, but this particular translation is showing in english. But the translation files seem to have correct translations.

**Comment by j0schi** [comment]
As this is one of the first results that comes up here is the solution: In Locotranslate (after changing the 100k limit in the options) You can actually translate this sting under Plugins -> Woocommerce PayPal Payments. It worked fine for me :)
