### ISSUE TITLE
Not have Advanced Card Processing

### ISSUE THREAD

**Issue by monyuan** [woocommerce/woocommerce-paypal-payments#2353]
<img width="787" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/56907515/a5433bfc-a4a5-4ddc-8df1-43ae5b113982">

**Comment by SydeKrystian** [comment]
Hello @monyuan 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
