### ISSUE TITLE
Getting Critical Error Report from my website

### ISSUE THREAD

**Issue by vondegroot** [woocommerce/woocommerce-paypal-payments#2355]
### Describe the Bug

Cannot edit and process orders when WooCommerce PayPal Payments plugin is enabled
PAYPAL PACKAGE TRACKING contents: There has been a critical error on this website. Please check your site admin email inbox for instructions.

### To Reproduce

Disabling WooCommerce PayPal Payments Plugin allows me to edit the order.

WC PP Payments PLUG-IN ENABLED:
![WooCommerce PayPal Payments ENABLED](https://github.com/woocommerce/woocommerce-paypal-payments/assets/62366262/57eff564-88a7-4e6f-aaad-721c838d3c6e)

WC PP Payments PLUG-IN DISABLED:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/62366262/9eb3e79b-5b35-49c7-b402-effa6e200a88)

WooCommerce version: 8.9.3
WooCommerce REST API package:   8.9.3 
WordPress version: 6.5.4

</body>
</html>

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hello @vondegroot, this issue will be addressed in the upcoming plugin update when #2360 is merged. In the meantime, you can downgrade the plugin to the [previous version 2.7.1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.7.1) to work around the error. Beyond this, I recommend reaching out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for additional guidance.
