### ISSUE TITLE
Fatal error: Uncaught Exception: No se pudo recuperar el pedido.

### ISSUE THREAD

**Issue by Datibus** [woocommerce/woocommerce-paypal-payments#2357]
### Describe the Bug

I can't edit an order. A PHP fatal error occurs. If I disable the plugin the error does not occur. The problem only occurs with that order.
### To Reproduce

Edit this order
[[#11229 Emily Thomas]](https://famaraspirit.com/wp-admin/post.php?post=11229&action=edit)

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/6526674/635f1032-3e73-4b30-bca6-b1c27cff56f9)

### Expected Behavior

Edit the order without errors.

### Actual Behavior

The system warns me of a fatal PHP error and prevents me from editing the order.

### Environment

 - WordPress Version 6.5.4
 - WooCommerce Version: 8.9.3
 - Plugin Version 2.8.0
 - Browser [e.g. Chrome, Safari] and Version  Google Chrome 126.0.6478.61
 - Any other plugins installed
 - 
Query Monitor	 	por John Blackbourn
Gravity Forms	 	por Gravity Forms
WPML Multilingual CMS	 	por OnTheGoSystems
WPML SEO	 	por OnTheGoSystems
Akismet Anti-spam: Spam Protection	 	por Automattic - Equipo Anti-spam
All In One WP Security	 	por Equipo de All In One WP Security & Firewall
Autoptimize	 	por Frank Goossens (futtta)
Broken Link Checker	 	por WPMU DEV
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress	 	por Thomas Geiger
Facebook for WooCommerce	 	por Facebook
Avada Builder	 	por ThemeFusion
Avada Core	 	por ThemeFusion
GDPR Cookie Compliance	 	por Moove Agency
Gravity Forms Multilingual	 	por OnTheGoSystems
Extensión de Gravity Forms para Mailchimp	 	por Gravity Forms
LoginPress	 	por LoginPress
Popup Maker	 	por Popup Maker
WooCommerce PDF Facturas, albaranes, notas de entrega y etiquetas de envío	 	por WebToffee
Really Simple SSL	 	por Really Simple Plugins
CTX Feed Pro	 	por WebAppick Author
WooCommerce Stripe Gateway	 	por WooCommerce
WooCommerce Legacy REST API	 	por WooCommerce
WooCommerce Multilingual & Multicurrency	 	por OnTheGoSystems
WooCommerce PayPal Payments	 	por WooCommerce
WooCommerce	 	por Automattic
Yoast SEO	 	por Equipo Yoast
WP Mail SMTP	 	por WP Mail SMTP
WP-Optimize - Clean, Compress, Cache	 	por David Anderson, Ruhani Rabin, Team Updraft
WP Popups Lite	 	por timersys
WP Super Cache	 	por Automattic
WPML Media Translation	 	por OnTheGoSystems
WPML String Translation	 	por OnTheGoSystems
Yoast SEO: WooCommerce	 	por Equipo Yoast
### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Datibus, this issue was resolved in the latest [2.8.1-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.1-rc1) pre-release version. Please give it a try and let us know if any issues persist for you. 
In that case, please contact our support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
