### ISSUE TITLE
no Paying method

### ISSUE THREAD

**Issue by Summerrider69** [woocommerce/woocommerce-paypal-payments#2359]
### Describe the Bug

when doing a buy in our onlineShop Keramikmalspass.com there is an error by paying with paypal.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172901245/35d529b1-c3d5-4a7b-ac4a-1b4a8b03a3b8)

### To Reproduce

1. Go to [Our page](https://keramikmalspass.com/produkt/geschenkgutschein/)
2. Click on 'Wert' and choose 50€ (I think all others work , but this is, what i could reproduce)
3. Click on (Zum Warenkorb hinzufügen) and go to cart after it. 
4. 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172901245/7607925b-08c7-4797-baca-e640751d770b)

5. Click at the paypalbutton to pay
6. after finishing the paypal-Show you´ll land on the error page and see this error:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/172901245/456d4e22-c8b5-4337-b3d8-9124936b1ce6)

i will try now the other payment way by clicking the button under the paypal-button in step 5.

so intresting result:
following the other Link (Weiter zum bezahlen)
the is a paypal express button on top of the page .
The errror will be the same

But:
if you fill our all data and use the paypal-Method  (weiter zu paypal)

it is working like it should!

I don´t change the settings now, but would be happy, if somebody writes me, that i can deactivate the button now.
for now i will create a message for customers.

### Environment

 - WordPress Version
 - Version 4.26023
 - WooCommerce Version
 - 
 - Plugin Version
 - paypal: Version 2.8.0 
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

`
### wp-core ###

version: 6.5.4
site_language: de_DE
user_language: de_DE
timezone: Europe/Berlin
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 194
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress/core/6.5.4
wordpress_size: 67,12 MB (70375929 bytes)
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: 651,55 MB (683200940 bytes)
themes_path: /srv/htdocs/wp-content/themes
themes_size: 20,92 MB (21933248 bytes)
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: 733,76 MB (769403646 bytes)
database_size: 817,95 MB (857686016 bytes)
wpcomsh-disk-space-used: 755,4 MB
wpcomsh-disk-space-quota: 100,0 GB

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Greenshift (greenshift-1)
version: 1.2
author: Wpsoul
author_website: https://greenshiftwp.com/
parent_theme: none
theme_features: woocommerce, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates, custom-line-height, wp-block-styles, editor-style
theme_path: /srv/htdocs/wp-content/themes/greenshift-1
auto_update: Deaktiviert

### wp-themes-inactive (4) ###

Blank Canvas: version: 1.0.11, author: Automattic, Updates werden von WordPress.com verwaltet
Blockbase: version: 3.1.17, author: Automattic, Updates werden von WordPress.com verwaltet
Storefront: version: 4.6.0, author: Automattic, Updates werden von WordPress.com verwaltet
Zoologist: version: 1.0.44, author: Automattic, Updates werden von WordPress.com verwaltet

### wp-mu-plugins (1) ###

wpcomsh-loader.php: author: (undefined), version: (undefined)

### wp-plugins-active (48) ###

Akismet Anti-spam: Spam Protection: version: 5.3.2, author: Automattic - Anti-spam Team, Updates werden von WordPress.com verwaltet
Code Snippets: version: 3.6.5.1, author: Code Snippets Pro, Automatische Aktualisierungen aktiviert
Complianz | GDPR/CCPA Cookie Consent: version: 7.1.0, author: Really Simple Plugins, Automatische Aktualisierungen aktiviert
Crowdsignal Forms: version: 1.7.1, author: Automattic, Updates werden von WordPress.com verwaltet
Crowdsignal Polls & Ratings: version: 3.1.1, author: Automattic, Inc., Updates werden von WordPress.com verwaltet
DHL Shipping Germany for WooCommerce: version: 3.7.0, author: DHL, Automatische Aktualisierungen aktiviert
Folders: version: 3.0.3, author: Premio, Automatische Aktualisierungen aktiviert
Google Analytics for WooCommerce: version: 2.1.2, author: WooCommerce, Updates werden von WordPress.com verwaltet
GreenShift - Animation and Page Builder Blocks: version: 8.9.8, author: Wpsoul, Automatische Aktualisierungen aktiviert
GreenShift Advanced Animation Addon: version: 3.6.3, author: Wpsoul, Automatische Aktualisierungen aktiviert
Greenshift Chart plugin: version: 1.2.2, author: Wpsoul, Automatische Aktualisierungen aktiviert
GreenShift Marketing and SEO Addon: version: 0.9.9.9, author: Wpsoul, Automatische Aktualisierungen aktiviert
Greenshift Query and Meta Addon: version: 4.8.1, author: Wpsoul (latest version: 4.8.2), Automatische Aktualisierungen aktiviert
Greenshift Smart Code AI: version: 0.2, author: Wpsoul, Automatische Aktualisierungen aktiviert
Greenshift Woocommerce Addon: version: 2.1, author: Wpsoul (latest version: 2.2), Automatische Aktualisierungen aktiviert
Jetpack: version: 13.6-a.5, author: Automattic, Updates werden von WordPress.com verwaltet
Jetpack Boost: version: 3.4.4, author: Automattic - Jetpack Site Speed team, Automatische Aktualisierungen aktiviert
LatePoint: version: 4.9.9, author: LatePoint (latest version: 4.9.92), Automatische Aktualisierungen aktiviert
LatePoint Addon - Coupons: version: 1.1.4, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Custom Fields: version: 1.2.7, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Group Bookings: version: 1.1.1, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Locations: version: 1.1.2, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Reminders: version: 1.1.0, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Role Manager: version: 1.0.0, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Service Durations: version: 1.0.6, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Service Extras: version: 1.2.2, author: LatePoint, Automatische Aktualisierungen aktiviert
LatePoint Addon - Taxes: version: 1.1.1, author: LatePoint, Automatische Aktualisierungen aktiviert
Layout Grid: version: 1.8.4, author: Automattic, Updates werden von WordPress.com verwaltet
Loco Translate: version: 2.6.10, author: Tim Whitlock, Automatische Aktualisierungen aktiviert
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: version: 3.1.81, author: Brevo, Automatische Aktualisierungen aktiviert
Order Export & Order Import for WooCommerce: version: 2.5.4, author: WebToffee, Automatische Aktualisierungen aktiviert
Page Optimize: version: 0.5.5, author: Automattic, Updates werden von WordPress.com verwaltet
PDF Invoices & Packing Slips for WooCommerce: version: 3.8.3, author: WP Overnight, Automatische Aktualisierungen aktiviert
PPOM for WooCommerce: version: 32.0.22, author: Themeisle, Automatische Aktualisierungen aktiviert
PW WooCommerce Copy Coupon: version: 1.32, author: Pimwick, LLC, Automatische Aktualisierungen aktiviert
String Locator: version: 2.6.5, author: InstaWP, Automatische Aktualisierungen aktiviert
TP Product Image Flipper for Woocommerce: version: 2.0.2, author: TP Plugins, Automatische Aktualisierungen aktiviert
WooCommerce: version: 9.0.0, author: Automattic, Updates werden von WordPress.com verwaltet
WooCommerce.com Update Manager: version: 1.0.3, author: Automattic, Automatische Aktualisierungen aktiviert
WooCommerce Customer/Order/Coupon CSV Import Suite: version: 3.12.0, author: SkyVerge, Automatische Aktualisierungen aktiviert
WooCommerce Extended Coupon Features FREE: version: 3.3.3, author: Soft79, Automatische Aktualisierungen aktiviert
WooCommerce PayPal Payments: version: 2.8.0, author: WooCommerce, Automatische Aktualisierungen aktiviert
WooCommerce PDF Product Vouchers: version: 3.12.3, author: SkyVerge, Automatische Aktualisierungen aktiviert
WooCommerce Sort By Stock: version: 2.2.0, author: Brandon Yanofsky, Automatische Aktualisierungen aktiviert
WooCommerce Zettle Integration: version: 7.9.2, author: BjornTech AB, Automatische Aktualisierungen aktiviert
Woo Composite Products: version: 9.0.5, author: Woo, Updates werden von WordPress.com verwaltet
WooPayments: version: 7.7.0, author: Automattic, Updates werden von WordPress.com verwaltet
WordPress.com Editing Toolkit: version: 4.26023, author: Automattic, Updates werden von WordPress.com verwaltet

### wp-plugins-inactive (8) ###

Classic Editor: version: 1.6.3, author: WordPress Contributors, Updates werden von WordPress.com verwaltet
Converter for Media: version: 5.12.5, author: matt plugins, Automatische Aktualisierungen aktiviert
Easy Username Updater: version: 1.0.5, author: Yogesh C. Pant, Automatische Aktualisierungen aktiviert
Flexible Shipping: version: 4.25.1, author: Octolize, Automatische Aktualisierungen aktiviert
Gutenberg: version: 18.5.0, author: Gutenberg Team, Updates werden von WordPress.com verwaltet
WooCommerce PDF Invoices, Packing Slips, Delivery Notes and Shipping Labels: version: 4.5.3, author: WebToffee, Automatische Aktualisierungen aktiviert
WooCommerce PDF Invoices, Packing Slips and Credit Notes (Pro): version: 1.0.5, author: Webtoffee, Automatische Aktualisierungen aktiviert
WooCommerce Products Wizard: version: 11.2.0, author: mail@troll-winner.com, Automatische Aktualisierungen aktiviert

### code-snippets (1) ###

snippet-5: name: WooCommerce Gutscheine, scope: global, modified: 2023-12-11 16:45:36

### wp-media ###

image_editor: Photon_Subsizes_WP_Image_Editor_GD
imagick_module_version: Nicht verfügbar
imagemagick_version: Nicht verfügbar
imagick_version: Nicht verfügbar
file_uploads: 1
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.10.0-19-amd64 x86_64
httpd_software: nginx
php_version: 8.1.29 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 512M
max_input_time: 1200
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 8.7.1 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
current: 2024-06-19T15:00:14+00:00
utc-time: Wednesday, 19-Jun-24 15:00:14 UTC
server-time: 2024-06-19T17:00:09+02:00

### wp-database ###

extension: mysqli
server_version: 10.4.26-MariaDB-log
client_version: mysqlnd 8.1.29
max_allowed_packet: 104857600
max_connections: 500

### wp-constants ###

WP_HOME: https://keramikmalspass.com
WP_SITEURL: https://keramikmalspass.com
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Nicht definiert
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: latin1
DB_COLLATE: latin1_swedish_ci

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: 218643800
ssl_cert: No
time_diff: undefined
version_option: 13.6-a.5:1718738515
old_version: 13.6-a.1:1718121384
public: Private
master_user: #213026139 keramikmalspass
is_offline_mode: off
is_offline_mode_constant: off
current_user: #233002264 fight4moree7384c2785
tokens_set: Blog User
blog_token: gV6A22QWwAuzcd)uB!t9NP1ETjTW&zQZ
user_token: SGM*x35910RCldMTGpnd0Ed*Ug3!04i8
version: 13.6-a.5
jp_plugin_dir: /wordpress/plugins/jetpack/13.6-a.5/
plan: business
protect_header: ""
full_sync: {"started":"Sun, 12 May 2024 07:25:37 +0000","finished":"Sun, 12 May 2024 07:25:49 +0000","progress":{"options":{"finished":true},"functions":{"finished":true},"constants":{"finished":true},"users":{"total":"1","sent":1,"finished":true,"last_sent":"233002307"},"network_options":{"finished":true}},"config":{"options":true,"functions":true,"constants":true,"users":[233002307],"network_options":true}}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: 28
full_sync_lag: 57 weeks, 2 days, 7 hours, 50 minutes, 8 seconds
idc_urls: {"home":"https:\/\/keramikmalspass.com","siteurl":"https:\/\/keramikmalspass.com","WP_HOME":"https:\/\/keramikmalspass.com","WP_SITEURL":"https:\/\/keramikmalspass.com"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

`

**Comment by SydeKrystian** [comment]
Hello @Summerrider69 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
