### ISSUE TITLE
Payment processed by bank but no order in WooCommerce

### ISSUE THREAD

**Issue by SonnyGillissen** [woocommerce/woocommerce-paypal-payments#2363]
### Describe the Bug

When a payment is done after the shopping cart an extra tab opens displaying "about:blank", while the main screen is loading PayPal Payments. The payment itself works, but nothing is updated in WooCommerce and no order is created.

### To Reproduce

1. Go the the WooCommerce shop and add the product in your cart
2. Fill in all order details and click one of the PayPal Payment methods.
3. Process payment en try to return back to the shop.

### Expected Behavior

Payment processed and order created in WooCommerce

### Actual Behavior

Payment processed and but no order created in WooCommerce

### Environment

 - WordPress Version: 6.5.4
 - WooCommerce Version: 9.0.1
 - Plugin Version: 2.8.0
 - Browser: all
 - Any other plugins installed:
   - Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro
   - Mailchimp for WooCommerce
   - Pre-Orders for WooCommerce
   - WooCommerce Advanced Free Shipping
   - YITH WooCommerce Product Add-ons & Extra Options

**Comment by SydeKrystian** [comment]
Hello @SonnyGillissen 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
