### ISSUE TITLE
Fatal error #2300

### ISSUE THREAD

**Issue by premkumarbsetec** [woocommerce/woocommerce-paypal-payments#2375]
### Describe the Bug

uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. in /homepages/1/d887141122/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:484 

### To Reproduce

    Go to WooCommerce - Orders
    Trying to open an order
    See error

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/125947139/0756621c-061f-4146-a74c-a3245c546d26)

https://prnt.sc/5nqL_O29dBNW

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 9.0.2
 - WooCommerce PayPal Payments Version 2.8.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @premkumarbsetec 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

This issue should be resolved in version 2.8.1, which we released a few hours ago. You can update the plugin via your WordPress dashboard, or download it directly from: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.1.

Please let us know over support board if the problem continues or if you have any additional questions.

Kind regards,
Krystian
