### ISSUE TITLE
not sure whether manually confirmation in checkout works for express payments

### ISSUE THREAD

**Issue by PSchmalhofer** [woocommerce/woocommerce-paypal-payments#2376]
Hello PayPal-Payments-Dev-Team,
we just got phoned from PayPal and suggested to activate new/best methods for best possible payment UX for our customers.
thats why we activated the option for Apple Pay/Google Pay/Express Checkout provided that the customer will be redirected to the checkout-page to confirm our terms & conditions (age>18, data processing, agb, etc.) and this checkbox is provided at the end of the checkout before pressing "jetzt verbindlich kaufen" (our shop url: https://aproposwein.com)
I found the option: https://prnt.sc/_xIlYPPHa5H- and activated it but I'm not sure whether it fully works at our shop: aproposwein.com 
Could you please help me to identify whether this option https://prnt.sc/_xIlYPPHa5H- works properly for having these payment methods suggested being activated?
thank you very much in advance,
best regards,
PS

**Comment by PSchmalhofer** [comment]
BTW: is it maybe possible to make this topic not public and not visible for anybody? thank you in advance!

**Comment by SydeKrystian** [comment]
Hello @PSchmalhofer 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
