### ISSUE TITLE
Verification email not being sent

### ISSUE THREAD

**Issue by tsg581ba** [woocommerce/woocommerce-paypal-payments#2380]
Everytime that paypal attempts to send me an email for verification, I never receive it. I have even checked my junk/spam folder. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @tsg581ba 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).


﻿Regarding your issue, the plugin does not handle sending emails, so you should ideally contact [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) for assistance.

Kind regards,
Krystian
