### ISSUE TITLE
Payer action required

### ISSUE THREAD

**Issue by premkumarbsetec** [woocommerce/woocommerce-paypal-payments#2389]
### Describe the Bug

Payer action required, possibly overcharge. Payer needs to perform the following action before proceeding with payment. Order status changed from Pending payment to Failed.

### To Reproduce

1. Go to Woo Commerce - Orders
2. Checkout using Paypal

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/125947139/01da5fb4-4541-4697-895c-21626d8aa6f9)

### Expected Behavior

Payment failed in our website but received payment in paypal

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 9.0.1
 - WooCommerce PayPal Payments Version 2.7.0

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @premkumarbsetec 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,  
Krystian

**Comment by scottybo** [comment]
@premkumarbsetec did you ever find a solution to this problem? I'm facing it too
