### ISSUE TITLE
Could Not Validate Nonce Error (204)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#239]
### Describe the bug
Merchants are experiencing this error:
```
021-07-30T21:28:37+00:00 CRITICAL Uncaught WooCommerce\PayPalCommerce\Button\Exception\RuntimeException: Could not validate nonce. in /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/class-requestdata.php:50
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/class-dataclientidendpoint.php(69): WooCommerce\PayPalCommerce\Button\Endpoint\RequestData->read_request('ppc-data-client...')
#1 /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/class-buttonmodule.php(111): WooCommerce\PayPalCommerce\Button\Endpoint\DataClientIdEndpoint->handle_request()
#2 /var/www/html/wp-includes/class-wp-hook.php(303): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}('')
#3 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#4 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#5 /var/www/html/wp-content/plugins/woocommerce/includes/clas in /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Endpoint/class-requestdata.php on line 50
```

### To reproduce

- Visit WooCommerce > Settings > Accounts & Privacy
- Disable the guest user checkout option (first checkbox)
![image](https://user-images.githubusercontent.com/70433191/136582853-71ed4513-260c-40b0-8944-1c6312dbd6c8.png)
- Enable option to register account in checkout
- ~Enable either of the checkboxes to auto-generate account name/password (both also cause the behavior)~
- Visit checkout as logged out user and create an order 
- A user account will be registered automatically (depending on the settings with auto-generated name or password)
- Payment  popup window will result in a loop until the user manually refreshed the site
- After the site refresh, the user is logged into his newly created account and can complete the payment

https://user-images.githubusercontent.com/70433191/134351866-cf126b34-0c0a-4399-b89e-d7035ab19c6c.mp4

Also there is another problem which is present even when the guest checkout is enabled and the “Create account” checkbox is checked.

Sometimes instead of finishing the order the checkout page is reloaded, resulting in bad UX + it is not possible to finish ordering because of duplicated PayPal order.

It seems random, sometimes it finishes fine, sometimes it reloads the checkout page. I think it is reproduced more often when DevTools is opened. So maybe there is a bug related to caching of HTTP requests and/or a race condition.

### Possible cause

We use  createaccount checkbox to determine whether the user needs to created 
https://github.com/woocommerce/woocommerce-paypal-payments/blob/65d05b935e40dbd90d300b31631ec0988306ce46/modules/ppcp-button/src/Endpoint/CreateOrderEndpoint.php#L189
 which is present only if Allow customers to place orders without an account + Allow customers to create an account during checkout are enabled.

### Environment

 - WordPress Version: 5.8, 5.3
 - WooCommerce Version: 5.6, 4.7
 - WooCommerce PayPal Payments Plugin Version: 1.5.1

**Comment by AlexP11223** [comment]
>     * Enable either of the checkboxes to auto-generate account name/password (both also cause the behavior)

I don’t see any effect from enabling the auto-generation options, just **Allow customers to create an account during checkout** is enough to get the error and loop.

**Comment by AlexP11223** [comment]
Looks like there is another bug related to registration (and to the testing of this issue after fixing the loop bug), updated the description.
