### ISSUE TITLE
MISSING_SHIPPING_ADDRESS Error

### ISSUE THREAD

**Issue by AntonioFaloppa** [woocommerce/woocommerce-paypal-payments#2392]
I am using WooCommerce PayPal Payments plugin on Wordpress and I only sell digital products. Since some time to now I am experiencing this error: MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS` when clients try to pay via debit or credit card. I have tried every single recommendation on forums or chats. But nothing works

Note: I haven't tried the use of the native shortcode of Woocommerce Checkout form because I use Elementor Page Builder and doing that is not an option for me.

Can you please let me know of a verified way to avoid the checkout of asking for shipping address?

**Comment by SydeKrystian** [comment]
Hello @AntonioFaloppa 

The issue may be related to the configuration settings within the PayPal Payments Plugin. Specifically, if the “`Require final confirmation on checkout` ” setting in the `Standard Payments` tab is unchecked.

To address this, please check the “Require final confirmation on checkout” setting in your plugin settings. If the issue persists after performing these steps, we suggest you contact us directly for further assistance. We may need to examine your system report or logs to better understand what’s happening. You can open a ticket with our service desk. Here’s how you can request support: [Request Support](https://paypal.inpsyde.com/docs/request-support/). Please make sure to include the URL of this thread in your ticket for reference.

Looking forward to hearing from you.
  
Kind Regards,  
Krystian
