### ISSUE TITLE
Paypal payment is not available whith "classic checkout" 

### ISSUE THREAD

**Issue by Assiba12** [woocommerce/woocommerce-paypal-payments#2395]
### Describe the Bug

Hi, My paypal option on the checkout page of my site does appear ONLY when Smart Button "express checkout" is enable. I don't want to enable PayPal with "express chekout", I juste need to have access to paypal paiment on "classic checkout". But it doesn't work alone (only when I choose "express checkout" + "classic checkout") 

### To Reproduce

1. Go to smart button location
2. Click on "classic checkout" WITHOUT "express checkout"
4. See error... paypal is not available

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/174839025/f74ef736-ddbd-4675-894a-fa30887648a8)

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/174839025/f3142ec8-194f-44db-81c6-28139c84a8b5)

### Environment

 - WordPress Version 6.5.5
 - WooCommerce Version 9.0.2
 - Plugin Version
 - Browser Chrome
 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Assiba12 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
