### ISSUE TITLE
Woocommerce/paypal activation fail

### ISSUE THREAD

**Issue by Jerreme-Josephson** [woocommerce/woocommerce-paypal-payments#2399]
### Describe the Bug

I activate paypal, log into my paypal business and do all the necessary authorization. Everything goes as should be and paypal congratulates me for having been approved. However, when I tap return to WooCommerce, I am taken back to the same page which keeps asking me to activate paypal. 

At first, I thought it was just a matter of being taken back to the same expired page, but when I checked Woocommerce, paypal had not been activated indeed. I went through the process again, this time I chose to be taken to my paypal page instead - just in case my return to woocommerce somehow reversed the activation. On my paypal, it continues to say I have been approved for advanced checkout, yet when I return to woocommerce, I still find that it continues to ask that I activate paypal. By now, I must have carried out the process over 5 times. I have also checked to see if there is any update I need to make with woocommerce and there seems to be none.
 
### To Reproduce

inside the wordpress backend,
1. Go to 'woocommerce then setting'
2. Click on 'woo payments and then all payment methods'
3. Scroll down to paypal and them select finish set-up. enter paypal login details and authorize as necessary'
4. you are taken to confirmation page where it says congratulations with confetti etc...
5. you are given the option to either go to paypal or back to woocommerce, choose go back to woocommerce...
6. See error

### Screenshots

![Screenshot 2024-07-08 at 8 21 07 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/175069483/2e2993e8-19f9-4d40-879a-a6a1a452af80)
![Screenshot 2024-07-08 at 8 24 10 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/175069483/453e386c-3bbc-4b2c-b3e6-52b18814dba3)

### Expected Behavior

I expect that woocommerce would show that my paypal has been activated and like paypal, it would confirm that I have been authorized to accept payments using paypal.

### Environment

 - WordPress Version - 6.5.5
 - WooCommerce Version - 9.0.2
 - Plugin Version - 
 - Browser [e.g. Chrome, Safari] and Version -firefox
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Jerreme-Josephson 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
