### ISSUE TITLE
PayPal button is appearing on all my product pages

### ISSUE THREAD

**Issue by annasaboisky** [woocommerce/woocommerce-paypal-payments#2401]
### PayPal button is on all my product pages as a pay in 4 line. I can not find any way of removing this. It is squished up under the button. Can it be removed? Please see screen shot.

<img width="1323" alt="Screenshot 2024-07-09 at 9 32 53 PM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/175117560/32dbf560-ea2c-46e5-8383-3707903adad4">

### Environment

 - WordPress Version 6.5.5
 - WooCommerce Version 8.8.5
 - WooCommerce PayPal Payments
 - Browser Chrome, Safari
 - Any other plugins installed- multiple

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @annasaboisky 

You can turn off Pay Later Messaging by going to the Pay Later tab in the plugin settings. However, keep in mind that GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
