### ISSUE TITLE
Paypal can't be activated.

### ISSUE THREAD

**Issue by CoHe-MaHe** [woocommerce/woocommerce-paypal-payments#2408]
### Describe the Bug

Paypal kann nichts aktiviert werden. Ich habe es mehrfach versucht und es kommt immer wieder folgender Hinweis: "Wir konnten den Einrichtungsprozess nicht abschließen. Einige Funktionen, wie Karten-Verarbeitung, sind nicht verfügbar. Um das zu korrigieren, versuche es bitte erneut."

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

<img width="865" alt="Ohne Titel 3" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/175315022/86bbe44b-4a16-4593-9e53-67f9d28be0ab">

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @CoHe-MaHe 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
