### ISSUE TITLE
The Plugin change 'sold_individually' value when adding product to cart. (3362)

### ISSUE THREAD

**Issue by mryoubou** [woocommerce/woocommerce-paypal-payments#2410]
### Describe the Bug

The Plugin change **Sold individually** value when adding product to cart.

I have found that you have a  broken logic here that caused this issue when using `woocommerce_add_to_cart_validation` filter to validate subscription product.

Please note that i have no subscription just a simple product.

you can find the function here:
...\woocommerce-paypal-payments\modules\ppcp-paypal-subscriptions\src\PayPalSubscriptionsModule.php

```
$subscriptions_mode = $settings->has( 'subscriptions_mode' ) ? $settings->get( 'subscriptions_mode' ) : '';

if ( 'subscriptions_api' !== $subscriptions_mode ) {
	if ( $product && $product->get_sold_individually() ) {
		$product->set_sold_individually( false );
		$product->save();
	}

	return $passed_validation;
}

```
### To Reproduce

1. Go to product data Inventory tab and set product to be sold individually.
2. Click on add to cart  and the value will be changed. the next time you refresh the page you will find that sold individually was set to false. and you can see quantity input on product page.

### Environment

 - WordPress Version : Latest
 - WooCommerce Version  : Latest
 - Plugin Version : Latest
 - Any other plugins installed :  No, Just WooCommerce, this plugin and storefront theme.

**Comment by flowbecca** [comment]
I can confirm I have the same issue after updating to Version 2.8.1 

All my products set as "sold individually" can be added multiple times to the cart.
Trying and re saving the "sold individually" option on the product inventory doesn't work as it gets set to false again anytime you click on the "add to cart" button.
These are Simple Virtual Downloadable products.

When WooCommerce PayPal Payments is deactivated "Sold individually" works as expected.

**Edited to add :** 

**As I have zero subscription products**, I removed the 'woocommerce_add_to_cart_validation' filter in PayPalSubscriptionsModule.php  
Thanks [mryoubou](https://github.com/mryoubou) for mentioning it ! 

I removed all of the filter and it's working for my simple products now.

**Comment by mryoubou** [comment]
@flowbecca You're welcome, After looking into the code it's a disaster haha, That entire module shouldn't be running in the first place since I don't have **WC_Product_Subscription** installed.

Second, why change the product sold individually value? who gave them the right to do so, even if subscription plugin is installed there's a better way to do it via filters `woocommerce_add_to_cart_sold_individually_quantity` and `woocommerce_add_to_cart_sold_individually_found_in_cart` for example. 

Now, everyone who use the plugin and  has products sold individually need to set it again!
