### ISSUE TITLE
Varible subscription with reduced price

### ISSUE THREAD

**Issue by alexrmrm** [woocommerce/woocommerce-paypal-payments#2412]
When I create a product with variable subscriptions that have a reduced price when I go to the payment option I get the payment for the normal subscription price, not the discount

### To Reproduce
Create a product with variations, of the variable subscription type.
Add a reduced price.
Connect with paypal
Go to pay the subscription and you will see the normal price without the discount.

### Screenshots

![image](https://github.com/user-attachments/assets/df1a61c9-2236-48eb-b478-462a10c812d2)

![image](https://github.com/user-attachments/assets/7783c322-6921-4ac2-9d05-8267e8eeb854)

### Expected Behavior

The reduced price should appear in the payment, not the normal price.

 - WordPress Version: 6.5.5
 - WooCommerce Version: 9.1.1
 - Plugin Version: 2.8.1
 - Browser [e.g. Chrome, Safari] and Version: chrome 126

**Comment by InpsydeNiklas** [comment]
Hello @alexrmrm, the feature for [PayPal Subscriptions](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-subscriptions) does not support price customizations such as sale prices, coupons, or shipping costs. 
This means the price for your subscription product at PayPal is fixed and based on your regular product price when you connect the WooCommerce subscription-type product with the PayPal Subscriptions plan/product.
If you need more flexibility for your subscription processing (e.g. for discounts or shipping options), I recommend [signing up for PayPal Vaulting](https://woocommerce.com/document/woocommerce-paypal-payments/#get-vaulting-approval) as this gives you full flexibility to charge users based on your needs. More details about the differences in subscription capability can be found here: https://woocommerce.com/document/woocommerce-paypal-payments/#subscriptions-faq

For any other questions about subscription processing with PayPal Payments, I recommend reaching out to our support team from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
