### ISSUE TITLE
creditcards by paypal missing after transfer to other hosting

### ISSUE THREAD

**Issue by MSC-lab** [woocommerce/woocommerce-paypal-payments#2426]
### Describe the Bug

After the transfer of our shop to kinsta hosting the creditcard payment was not loading at checkout, only PayPal single. Did cou know if this problems could be from kinsta CDN Caching or anything or see you an other issue at the console? 

Shop URL was https://gewuerz-aschenbrenner.de/

Thanks for your reply!

**Comment by SydeKrystian** [comment]
Hello @MSC-lab 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
