### ISSUE TITLE
Vaulting not working on mini cart (242)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#243]
### Describe the bug
When I want to change payer or a funding source I am not able to do it from a mini cart. Drop down arrow in unresponsive. 

### To reproduce
1. Enable vaulting
2. Add some product to the cart. 
3. Hover over mini cart and click on arrow next to the PayPal button.
4. Observe, clicking on the arrow does not open the drop down list.

**Screenshots**
![image-2021-08-18-10-34-04-902](https://user-images.githubusercontent.com/456223/132230244-08e0c5a9-0b0f-4388-9818-4cea85c7f661.png)

### Expected behavior
Drop down arrow button is responsive

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - WooCommerce PayPal Payments Plugin Version: 1.5.1

**Comment by InpsydeNiklas** [comment]
PayPal fixed the issue by not showing the vaulted menu when the button is less than 250px wide.
