### ISSUE TITLE
mobile number is a required field - error

### ISSUE THREAD

**Issue by rahmatam** [woocommerce/woocommerce-paypal-payments#2442]
Some of our customers encounter an error (mobile number is a required field) after completing the fields and clicking the order button on the checkout page, if they have completed the mobile number field correctly.  Please tell me what is the cause of this error and how to fix this error?  We are very concerned about our customers, some of them may not be able to complete their purchases.

**Comment by SydeKrystian** [comment]
Hello @rahmatam 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
