### ISSUE TITLE
PayPal pay later messaging

### ISSUE THREAD

**Issue by calebj33** [woocommerce/woocommerce-paypal-payments#2444]
Cannot disable the pay later messaging locations for a wordpress/woocommerce site. I disabled the button at the product page, and that went through okay. I uncheck the box for the pay later messaging at the single product page, hit save, and it resets to be checked again. Have also tried going to another tab in the woocommerce settings after unchecking the box and this does not work either.

**Comment by SydeKrystian** [comment]
Hello @calebj33 ,

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it is important to note that the issue you are encountering should not be occurring in the current version (2.8.2) of the plugin. Please ensure that your plugin is updated to this latest version as it may resolve your problem.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
