### ISSUE TITLE
PayPal checkout completion

### ISSUE THREAD

**Issue by calebj33** [woocommerce/woocommerce-paypal-payments#2445]
Orders not completing for wordpress/woocommerce for standard PayPal payments. Customers are able to click on the paypal button, select information in paypal, but when sent back to site it does not complete order. All other payment methods (woo pay, apple pay, google pay, woo credit cards, paypal credit cards) work just fine.

**Comment by SydeKrystian** [comment]
Hello @calebj33 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
