### ISSUE TITLE
Paypal advanced card processing refund option is not working 

### ISSUE THREAD

**Issue by web-centric** [woocommerce/woocommerce-paypal-payments#2446]
I'm not able to refund the customer, the customer has placed an order using Woocommerce Paypal credit card option. The API's are already configured correctly and we are receiving new orders but we are not able to refund, please fix this issue right away, this is not professional.
![unnamed](https://github.com/user-attachments/assets/6f74e9bb-b4d8-4457-8b55-10141001eecf)

**Comment by SydeKrystian** [comment]
Hello @web-centric 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
