### ISSUE TITLE
Payment Applied to a Different Order From a Different Customer (226)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#245]
### Describe the bug
Customer ordered a product but received a receipt from a different, unrelated order. In WooCommerce, the original order is marked as “Cancelled”. The wrong customer’s order gets transitioned from “Completed” → “On Hold” → “Processing”.

### To reproduce
The issue cannot be reproduced locally at the moment, here are the steps reported:
1. Customer attempts to buy product A
2. customer pays for product A using PayPal Payments
3. customer receives a payment receipt about product B with details from customer B

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - WooCommerce PayPal Payments Plugin Version: 1.5.1

**Comment by InpsydeNiklas** [comment]
Has been fixed a while back already.
