### ISSUE TITLE
Dabit & Credit Card button not displaying

### ISSUE THREAD

**Issue by mrigankadas** [woocommerce/woocommerce-paypal-payments#2453]
Hi,

I am facing a new issue on the plugin 'WooCommerce PayPal Payments'.

This is my site https://sportsandmusiclegends.co.uk/. 
I have setup all the settings from backend Woocommerce->Settings->Payments->Paypal (see screenshot). On the product single page I can see the 'PayPal' button but not displaying the 'Dabit & Credit Card' paypal default button (see screenshot) and on the cart page no paypal button is displaying (see screenshot) and also in the checkout page not displaying the 'Dabit & Credit Card' paypal default button. 

![paypal-button](https://github.com/user-attachments/assets/9ebd84db-a7c0-4e1e-a2a2-b797b54dd9d7)

![Football-Memorabilia-Adebayor-Manchester-City-Signed-Football-Memorabilia](https://github.com/user-attachments/assets/fe4ef756-74d3-467b-a4ef-7c5f6c2f0138)

![Cart-Sports-Legends](https://github.com/user-attachments/assets/cfb8f2a3-bfeb-4d5d-a828-f737c3353180)

Please check and confirm me what is the actual issue.

Thanks

**Comment by VerdaderaYT** [comment]
I have the same issue: the dark button to pay with card displays, then disappears a few seconds later when some JavaScript from PayPal's side executes. On the preview it remains. And the exact same thing happens with the "Pay later" button.

These are the versions I have tried:
WordPress: 6.5.5
WooCommerce: 9.0.2
PHP: 7.4.33
WooCommerce PayPal Payments: 2.8.1 and 2.8.2 both have this issue

I was able to trace the issue and find it's related to a GET variable disable-funding passed by the plugin to the PayPal JavaScript request:

![get_variable_disable](https://github.com/user-attachments/assets/28ea554d-c55f-4898-9a78-91ecfb394352)

And same as @mrigankadas, on the settings of the plugin the option field "Disable Alternative Payment Methods" is empty. No matter what I put on that field, the payment methods "card" and "paylater" are always disabled, while they both display perfectly on the preview.

**Comment by SydeKrystian** [comment]
Hello @mrigankadas 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
