### ISSUE TITLE
adds My Account > Payment methods 

### ISSUE THREAD

**Issue by pfoxson** [woocommerce/woocommerce-paypal-payments#2454]
Enabling this plugin enables My Account > Payment methods which is not working.
when adding a payment method, I get Unable to add payment method to your account.
This menu was added with latest update and I don't see how to turn if off!

**Comment by SydeKrystian** [comment]
Hello @pfoxson 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
