### ISSUE TITLE
Issues since update to 2.8.2 version this morning

### ISSUE THREAD

**Issue by zidudad** [woocommerce/woocommerce-paypal-payments#2455]
1. Since the update to 2.8.2 I am using the Botiga theme and all the card payments were automatically rejected for the Shopify like checkout that I was using. The error that I got was:
 _There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again._
 
 I narrowed the error down to Botiga theme and from there I figured out that it was the checkout layout. Since then I have been able to make card payments without issue on the website but today the majority of my orders have come from Paypal.
 
 2. Some Google Pay orders have been declined after the update. I normally have 1 failed order every three days but had 3 in the space of 2 hours today. I used the same card to make payments direct but they did not work with Google Pay. In each case it says the bank has declined the payment.

 - WordPress Version- latest
 - WooCommerce Version-latest
 - Plugin Version-2.8.2
 - Browser [e.g. Chrome, Safari] and Version- Chrome/latest
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @zidudad  

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
