### ISSUE TITLE
Woocommerce Paypal Payments error

### ISSUE THREAD

**Issue by SamK321** [woocommerce/woocommerce-paypal-payments#2456]
### Describe the Bug

On items with variations, I can not select the variation/add it to the basket and paypal details are all greyed out. 
Single items can be added fine, paypal works at checkout fine. 
I disabled all other plugins and it is definitely Woocommerce Paypal Payments that is creating this issue. 
It doesn't seem to be due to reacting to any other plugin, as even with ALL other plugins disabled, this error occurs. 
I have also tried rolling back woocommerce itself to see if it is this plugin and Woocommerce Paypal Payments conflicting, this also does not resolve the issue. 
I have tried rolling back the version of Woocommerce Paypal Payments and this does not resolve the issue. 
The only way to resolve the issue is to disable Woocommerce Paypal Payments, but then i can not take any payments!!

### To Reproduce

1. Go to '[…](https://samanthakgifts.co.uk/shop/steampunk-arrows-set-mega-cogs-pack-also-available-as-separates/)'
2. Click on 'pack, choose an option' - you will not be able to!
3. See error

### Environment

 - WordPress Version 
 - WooCommerce Version Version 9.1.2
 - Plugin Version Version 2.8.2 (other versions also tried!)
 - Browser - Chrome
 - Any other plugins installed, yes, but all deactivated to try and resolve error

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SamK321** [comment]
On items with variations, I can not select the variation/add it to the basket and paypal details are all greyed out. 
Single items can be added fine, paypal works at checkout fine. 
I disabled all other plugins and it is definitely Woocommerce Paypal Payments that is creating this issue. 
It doesn't seem to be due to reacting to any other plugin, as even with ALL other plugins disabled, this error occurs. 
I have also tried rolling back woocommerce itself to see if it is this plugin and Woocommerce Paypal Payments conflicting, this also does not resolve the issue. 
I have tried rolling back the version of Woocommerce Paypal Payments and this does not resolve the issue. 
The only way to resolve the issue is to disable Woocommerce Paypal Payments, but then i can not take any payments!!-->

**Comment by SydeKrystian** [comment]
Hello @SamK321 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
