### ISSUE TITLE
paypal is producing a http error 431 on the redirect pop up window

### ISSUE THREAD

**Issue by jjkanakry** [woocommerce/woocommerce-paypal-payments#2460]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by jjkanakry** [comment]
goto: https://akidandacomic.com/product/single-issue/
click: Paypal Button

**Comment by jjkanakry** [comment]
![Screenshot 2024-07-24 170916](https://github.com/user-attachments/assets/26a4d28e-c85f-43b5-b67a-a04160c1fc13)

**Comment by InpsydeNiklas** [comment]
Hi @jjkanakry, as far as I can tell, the PayPal popup is loading correctly on your site:
![image](https://github.com/user-attachments/assets/8a67da67-3c3e-4c94-94d4-d6ac652e1ee5)
If you're still facing issues, I recommend contacting our support team from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
