### ISSUE TITLE
Name Your Price Reverts to Product Minimum Price on ApplePay

### ISSUE THREAD

**Issue by discsox** [woocommerce/woocommerce-paypal-payments#2466]
### Describe the Bug

Using a "name your price" plugin allows customers to enter a custom price. However the price that is charged is the minimum price that is configured in the name your price plugin in the WooCommerce product instead of the entered price by the customer.
We confirmed this issue with two different "Name your price" plugins
The error goes away when rolling PayPal back to WooCommerce PayPal Payments Version 2.8.1

### To Reproduce
Because we rolled back PayPal to 2.8.1 the error does not show up. As soon as we update to 2.8.2 the error appears as shown below.

1. Got to https://cosentinofamilyfarm.com/product/produce-checkout/
2. enter a custom price >= $5.00
3. Click "PAY NOW"
4. Pay with Apple Pay
5. Complete the payment 
6. Payment confirmation and charge will revert just $5.00 no matter what you enter as payment amount

### Expected Behavior

Apple Pay should charge the entered custom amount and not the Product Minimum amount

### Actual Behavior

Apple Pay charges the product minimum amount instead of the entered custom amount.

### Environment
 - WordPress Version: 6.6.1
 - WooCommerce Version: 9.1.4
 - Plugin Version 2.8.1 (does not work with 2.8.2)
 - any browser that is Apple Pay capable
 - Any other plugins installed: WooCommerce Name Your Price (Yith) also tried WPC Name Your Price for WooCommerce (WPClever)

### Additional Details

<details><summary>System status</summary>

  ```
  <html>
<body>

WordPress Environment
--
Home URL: | https://cosentinofamilyfarm.com
Site URL: | https://cosentinofamilyfarm.com
WP Content URL: | https://cosentinofamilyfarm.com/wp-content
WP Version: | 6.6.1
WP Multisite: | –
Permalink Structure: | /%postname%/
Front Page Display: | page
Front Page: | Cosentino Family Farm (#15)
Posts Page: | Unset
WP Memory Limit: | 256 MB
Database Table Prefix: | Length: 3 - Status: Acceptable
WP Debug Mode: | –
Language: | en_US

  ```

</details>
System Status
WordPress Environment
Home URL:	https://cosentinofamilyfarm.com
Site URL:	https://cosentinofamilyfarm.com
WP Content URL:	https://cosentinofamilyfarm.com/wp-content
WP Version:	6.6.1
WP Multisite:	–
Permalink Structure:	/%postname%/
Front Page Display:	page
Front Page:	Cosentino Family Farm (#15)
Posts Page:	Unset
WP Memory Limit:	256 MB
Database Table Prefix:	Length: 3 - Status: Acceptable
WP Debug Mode:	–
Language:	en_US
Server Environment
Server Info:	Apache
PHP Version:	8.2.21
ABSPATH:	/home/csntnoff/public_html/
PHP Memory Limit:	256 MB
PHP Post Max Size:	64 MB
PHP Time Limit:	300
PHP Max Input Vars:	1000
PHP Display Errors:	–
SUHOSIN Installed:	–
MySQL Version:	10.6.18
Max Upload Size:	64 MB
Default Timezone is UTC:	✔
fsockopen/cURL:	✔
Active Plugins (21)
[ManageWP - Worker](https://managewp.com/)	by [GoDaddy](https://godaddy.com/) – 4.9.20
[Black Studio TinyMCE Widget](https://wordpress.org/plugins/black-studio-tinymce-widget/)	by [Black Studio](https://www.blackstudio.it/) – 2.7.3
[Classic Editor](https://wordpress.org/plugins/classic-editor/)	by [WordPress Contributors](https://github.com/WordPress/classic-editor/) – 1.6.4
[Code Snippets](https://codesnippets.pro/)	by [Code Snippets Pro](https://codesnippets.pro/) – 3.6.5.1
[Yoast Duplicate Post](https://yoast.com/wordpress/plugins/duplicate-post/)	by [Enrico Battocchi & Team Yoast](https://yoast.com/) – 4.5
[Google Analytics for WordPress by MonsterInsights](https://www.monsterinsights.com/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=pluginurl&utm_content=7%2E0%2E0)	by [MonsterInsights](https://www.monsterinsights.com/lite/?utm_source=liteplugin&utm_medium=pluginheader&utm_campaign=authoruri&utm_content=7%2E0%2E0) – 8.28.0
Kadence Slider	by [Kadence WP](http://kadencewp.com/) – 2.3.6
[Metricool](https://metricool.com/)	by [Metricool](http://www.metricool.com/) – 1.22
[Modern Events Calendar Lite](http://webnus.net/modern-events-calendar/)	by [Webnus](https://webnus.net/) – 7.12.1
[Page scroll to id](http://manos.malihu.gr/page-scroll-to-id)	by [malihu](http://manos.malihu.gr/) – 1.7.9
[Page Builder by SiteOrigin](https://siteorigin.com/page-builder/)	by [SiteOrigin](https://siteorigin.com/) – 2.29.19
[SiteOrigin Widgets Bundle](https://siteorigin.com/widgets-bundle/)	by [SiteOrigin](https://siteorigin.com/) – 1.62.3
[TablePress Extension: DataTables Inverted Filter](https://tablepress.org/extensions/datatables-inverted-filter/)	by [Tobias Bäthge](https://tobias.baethge.com/) – 1.1
[TablePress](https://tablepress.org/)	by [Tobias Bäthge](https://tablepress.org/) – 2.4
[UpdraftPlus - Backup/Restore](https://updraftplus.com/)	by [UpdraftPlus.Com, DavidAnderson](https://updraftplus.com/) – 1.24.4
[WooCommerce Name Your Price](http://www.woo.com/products/name-your-price/)	by [Kathy Darling](http://kathyisawesome.com/) – 3.5.13
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	by [WooCommerce](https://woocommerce.com/) – 2.8.1
[WooCommerce](https://woocommerce.com/)	by [Automattic](https://woocommerce.com/) – 9.1.4
[Wordfence Security](https://www.wordfence.com/)	by [Wordfence](https://www.wordfence.com/) – 7.11.6
[WP Rollback](https://wprollback.com/)	by [WP Rollback](https://wprollback.com/) – 2.0.7
[WPForms Lite](https://wpforms.com/)	by [WPForms](https://wpforms.com/) – 1.8.9.6
Theme
Name:	Virtue - Premium
Version:	4.10.15
Author URL:	https://www.kadencewp.com/
Child Theme:	✕

**Comment by SydeKrystian** [comment]
Hello @discsox 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
