### ISSUE TITLE
paypal extended card payment cannot be deactivated

### ISSUE THREAD

**Issue by kittyklein** [woocommerce/woocommerce-paypal-payments#2467]
[fehler paypal.pdf](https://github.com/user-attachments/files/16405353/fehler.paypal.pdf)

woocommerce payments:
paypal > advanced card processing is deactivated!

the button is still visible on the checkout page in the shop.

**Comment by kittyklein** [comment]
found it yourself! 

you actually have to work on a different tab:
standard payments explicitly hide alternative payment methods such as: kedit or debit cards.

it's a real pity that after a plugin update you come across such grey areas. that shouldn't happen automatically. i don't test an order after every plugin update to see if there are any nasty surprises in the payment process. 


[fehler  II paypal.pdf](https://github.com/user-attachments/files/16405408/fehler.II.paypal.pdf)

**Comment by SydeKrystian** [comment]
Hello @kittyklein 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
