### ISSUE TITLE
"Unfortuantely, your credit card details are not valid" but payment proceeds (211)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#247]
### Describe the bug
#193 fixed a bug that could cause the error when starting the credit card payment process.
But we continue to receive isolated reports about the error appearing with update 1.4.0

### To reproduce
We cannot reproduce this error anywhere within the Sandbox and the merchants could also only produce this error with live payments with credit cards that trigger 3D-Secure.

1. Add item to cart
2. Visit checkout
3. Place order via PayPal Card Processing

Error messages will show up and 3D-Secure popup opens to complete the transaction, transaction completes properly despite the displayed errors.

### Expected behavior
No error messages should show up when entering valid credit card information.

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - WooCommerce PayPal Payments Plugin Version: 1.5.1

**Comment by InpsydeNiklas** [comment]
This was resolved a while back.
