### ISSUE TITLE
Wordpress reported a technical error in PayPal plugin but I did not find an error

### ISSUE THREAD

**Issue by nathipugi** [woocommerce/woocommerce-paypal-payments#2483]
I got this email from Wordpress, but I could not find any error in my PayPal plugin. All plugins and my site are updated correctly. 

Hallo!

WordPress hat eine eingebaute Funktion, die erkennt, wenn ein Plugin oder ein Theme einen fatalen Fehler auf deiner Website verursacht, und dich deswegen mit dieser automatisierten E-Mail benachrichtigt.

In diesem Fall hat WordPress einen Fehler in einem deiner Plugins, WooCommerce PayPal Payments, abgefangen.

Besuche zunächst deine Website (https://m3013.ch/) und überprüfe sie auf sichtbare Probleme. Besuche als nächstes die Seite, auf der der Fehler aufgetreten ist (https://m3013.ch/wp-login.php) und prüfe, ob es sichtbare Probleme gibt.

Bitte kontaktiere dein Hosting-Unternehmen, um Unterstützung bei der weiteren Untersuchung dieses Problems zu erhalten.

Wenn deine Website fehlerhaft zu sein scheint und du nicht mehr wie gewohnt auf dein Dashboard zugreifen kannst, hat WordPress jetzt einen speziellen „Wiederherstellungsmodus“. Auf diese Weise kannst du dich sicher in deinem Dashboard anmelden und weitere Untersuchungen durchführen.

https://m3013.ch/wp-login.php?action=enter_recovery_mode&rm_token=shEZGDNzhcjnWvD5BLYk3Z&rm_key=PB48UIYUpCknIwLqepWBaW

Um deine Website zu schützen, läuft dieser Link in 1 Tag ab. Aber keine Sorge: Ein neuer Link wird dir per E-Mail zugeschickt, wenn der Fehler nach Ablauf der Frist erneut auftritt.

Wenn du Hilfe bei diesem Problem suchst, wirst du möglicherweise nach einigen der folgenden Informationen gefragt:
WordPress-Version 6.6.1
Aktives Theme: Blocksy (Version 2.0.55)
Aktuelles Plugin: WooCommerce PayPal Payments (Version 2.8.2)
PHP-Version 8.1.29

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 47 der Datei /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function WooCommerce\PayPalCommerce\Blocks\wc_terms_and_conditions_page_id() in /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-blocks/extensions.php:47
Stack trace:
#0 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(132): WooCommerce\PayPalCommerce\Blocks\BlocksModule->WooCommerce\PayPalCommerce\Blocks\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#1 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#3 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeCachingServiceProvider.php(131): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#4 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(144): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeCachingServiceProvider->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer), Array)
#5 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(74): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeExtension(Object(Closure), Array)
#6 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(318): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#7 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#8 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#9 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/services.php(77): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.setti...')
#10 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(117): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer))
#11 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/DelegatingContainer.php(56): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->invokeFactory(Object(Closure))
#12 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CompositeContainer.php(53): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\DelegatingContainer->get('wcgateway.paypa...')
#13 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(61): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CompositeContainer->get('wcgateway.paypa...')
#14 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(161): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->WooCommerce\PayPalCommerce\Vendor\Dhii\Container\{closure}()
#15 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(128): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->invokeGenerator(Object(Closure))
#16 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/lib/packages/Dhii/Container/CachingContainer.php(62): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->getCached('wcgateway.paypa...', Object(Closure))
#17 /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php(511): WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer->get('wcgateway.paypa...')
#18 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}(Array)
#19 /wordpress/core/6.6.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#20 /wordpress/plugins/woocommerce/9.1.4/includes/class-wc-payment-gateways.php(94): apply_filters('woocommerce_pay...', Array)
#21 /wordpress/plugins/woocommerce/9.1.4/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init()
#22 /wordpress/plugins/woocommerce/9.1.4/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->__construct()
#23 /wordpress/plugins/woocommerce-payments/8.0.0/includes/class-wc-payments-features.php(271): WC_Payment_Gateways::instance()
#24 /wordpress/plugins/woocommerce-payments/8.0.0/includes/class-wc-payments.php(1583): WC_Payments_Features::is_woopay_direct_checkout_enabled()
#25 /wordpress/plugins/woocommerce-payments/8.0.0/includes/class-wc-payments.php(599): WC_Payments::maybe_init_woopay_direct_checkout()
#26 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(324): WC_Payments::{closure}('')
#27 /wordpress/core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#28 /wordpress/core/6.6.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#29 /wordpress/core/6.6.1/wp-settings.php(630): do_action('setup_theme')
#30 /srv/htdocs/wp-config.php(83): require_once('/wordpress/core...')
#31 /wordpress/core/6.6.1/wp-load.php(55): require_once('/srv/htdocs/wp-...')
#32 /wordpress/core/6.6.1/wp-login.php(12): require('/wordpress/core...')
#33 {main}
 thrown

**Comment by 0x0ACB** [comment]
We are also experiencing that issue

Edit: reinstalling the plugin seems to have fixed the issue

**Comment by InpsydeNiklas** [comment]
Hi folks, 
A new WooPayments plugin (8.0.1) was just released: https://github.com/Automattic/woocommerce-payments/releases/tag/8.0.1

> 8.0.1 – 2024-07-31
> Fix – Reverts changes related to Direct Checkout that broke the PayPal extension.

Please see this issue for more details: https://github.com/woocommerce/woocommerce-paypal-payments/issues/2481#issuecomment-2260968694
I will close this as it duplicates #2481.
