### ISSUE TITLE
Payment for a guest user doesn't save the payment method (Vault)

### ISSUE THREAD

**Issue by nicomollet** [woocommerce/woocommerce-paypal-payments#2485]
### Describe the Bug

Since 2.8.1 and this fix https://github.com/woocommerce/woocommerce-paypal-payments/pull/2283 a guest user paying an order has no payment method saved to its account.
PayPal is setup with Vault enabled.
Before 2.8.1, the payment method was saved:
- a PayPal payment token was created in `woocommerce_payment_tokens`
- the PayPal customer ID is added to the user meta

### To Reproduce

1. Configure a website with PayPal and Vault enabled.
2. With anonymous user, add a product to cart
3. On checkout, select PayPal
4. Observe no payment method is saved in the customer account

### Expected Behavior

The payment method used after a successful payment (with Vault enabled) should be saved to the customer account (payment token and `_ppcp_target_customer_id` user meta).

### Actual Behavior

No payment method is saved, just like if Vault was disabled.

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 7.8.0
 - Plugin Version 2.8.1

### Additional Details

To fix the issue, just revert https://github.com/woocommerce/woocommerce-paypal-payments/pull/2283

**Comment by InpsydeNiklas** [comment]
Thanks for the report! This was resolved in #2491 and included in the [2.8.3 update](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.3).
