### ISSUE TITLE
The button won't load in Safari

### ISSUE THREAD

**Issue by gabebarrett101** [woocommerce/woocommerce-paypal-payments#2486]
When I try to check out in Safari, the button won't load until I hit Safari's "X" to stop loading the page. It just looks like the attached image. However, it works fine in Chrome.

![Screenshot 2024-08-03 at 3 56 41 PM](https://github.com/user-attachments/assets/8c8c0b7e-9dcd-47c7-91eb-5de09baa151e)

**Comment by SydeKrystian** [comment]
Hello @gabebarrett101 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
