### ISSUE TITLE
WooCommerce > PayPal Pay Later changes not saving

### ISSUE THREAD

**Issue by tgsmith99** [woocommerce/woocommerce-paypal-payments#2488]
### Describe the Bug

WooCommerce > PayPal Pay Later changes not saving after clicking "Save"

### To Reproduce

1. Go to WooCommerce > Payment Settings > PayPal > Pay Later tab
2. In Customize Your Message section, click on any of the options underneath Product Page, Cart, or Checkout 
3.  Change logo, color, or text size.
4. Save.
5. See confirmation it was Saved but then go back to those options you just changed and see that they did not change.

### Screenshots

Video: https://www.loom.com/share/7cba2336348a491cbe6986102e39d8f8?sid=171ab1a6-cfff-4c61-a843-eab18dee7ca1

### Expected Behavior

Changes should save.

### Actual Behavior

Changes don't save.

### Environment

WP Version: 6.6
Plugins:
  WooCommerce Version: 9.1.2
  WooPayments version: 8.01
  WooCommerce Paypal Payments version: 2.8.2

Browser: Chrome latest version

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @tgsmith99 

We are aware of this problem and our developers are currently working on a fix, which we hope to include in the next update. We will keep you informed and notify you as soon as a fix is available.

In the meantime, there is a workaround you can use. You can disable the new Pay Later messaging configurator and revert to the legacy Pay Later settings configurator using a specific filter. The legacy Pay Later configuration can be restored with this code snippet:

`add_filter( 'woocommerce.feature-flags.woocommerce_paypal_payments.paylater_configurator_enabled', '__return_false' );
`

We apologize for any inconvenience this has caused and appreciate your patience as we work to resolve this issue.

Kind Regards,
Krystian

**Comment by subfighter3** [comment]
> add_filter( 'woocommerce.feature-flags.woocommerce_paypal_payments.paylater_configurator_enabled', '__return_false' );

the snippet does not work with latest versions (wp 6.7.2, wc 9.7.1, wcppp 2.9.6), the pay later configurator keeps showing.
