### ISSUE TITLE
Woocommerce payment

### ISSUE THREAD

**Issue by MohZarad** [woocommerce/woocommerce-paypal-payments#2489]
### Describe the Bug

I have integrated my PayPal account to woocoommerce and it's connected there is an order completed on my website but the money is not in my account 

the referee number 
[2BS03513KT080611U](https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_view-a-trans&id=2BS03513KT080611U)

### Screenshots
![image](https://github.com/user-attachments/assets/78c140c4-4444-4600-a61d-9ad6f8944d3f)

![image](https://github.com/user-attachments/assets/30ae4bde-4f1d-4454-a710-e483474b7f19)

![image](https://github.com/user-attachments/assets/88447918-6d28-45fb-97d3-df90b9cc99b8)

**Comment by SydeKrystian** [comment]
Hello @MohZarad 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
