### ISSUE TITLE
Critical error on advanced credit card processing

### ISSUE THREAD

**Issue by dabesa** [woocommerce/woocommerce-paypal-payments#2497]
### Describe the Bug

When some customers pay via advanced credit card processing, a critical error is generated (no charge is collected):

`Uncaught Error: Call to a member function captures() on null in /home/---/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Processor/PaymentsStatusHandlingTrait.php:38
Stack trace:
#0 /home/---/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Gateway/CreditCardGateway.php(492): WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway->handle_new_order_status()
#1 /home/---/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): WooCommerce\PayPalCommerce\WcGateway\Gateway\CreditCardGateway->process_payment()
#2 /home/---/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment()
#3 /home/---/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(520): WC_Checkout->process_checkout()
#4 /home/---/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::checkout()
#5 /home/---/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/---/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /home/---/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#8 /home/---/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::do_wc_ajax()
#9 /home/---/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#10 /home/---/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /home/---/public_html/wp-includes/template-loader.php(13): do_action()
#12 /home/---/public_html/wp-blog-header.php(19): require_once('/home/---/...')
#13 /home/---/public_html/index.php(17): require('/home/---/...')
#14 {main}
  thrown`

It doesn't happen for all credit cards, but only for some customers. Trying multiple times doesn't help, it looks like something related to the specific card.

### To Reproduce

I don't know how to reproduce because it's specific for some users/cards.
General steps are: complete an order and pay via advanced credit card processing.

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.1.4
 - Plugin Version 2.8.2
 - Browser: Chrome 127.0.6533.72
 - Any other plugins installed: a few but the error is specific from woocommerce-paypal-payments

**Comment by SydeKrystian** [comment]
Hello @dabesa 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
