### ISSUE TITLE
paypal payment plugin update not working

### ISSUE THREAD

**Issue by pennshill** [woocommerce/woocommerce-paypal-payments#2503]
### Describe the Bug
I updated the paypal plugin for woocommerce.  the buttons are not visible on my shop page when I'm on a tablet. I can see them on my desktop. Apple pay doesn't show up.  When I checked the box to add it, the buttons disappeared. When I unchecked it, they came back.  The person that was helping me at paypal said to reach out to Woocommerce to figure out the problem.

![Screenshot 2024-08-09 at 7 05 53 PM](https://github.com/user-attachments/assets/381fd577-817c-4a8c-9124-e6a6ac9a9196)

paypal buttons not showing on tablets or iphones after the plugin upgrade.
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version     6.6.1
 - WooCommerce Version.   9.1.4
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version chrome
 - Any other plugins installed.  woocommerce paypal payments 2.8.2

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @pennshill 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
