### ISSUE TITLE
Advanced Credit Card

### ISSUE THREAD

**Issue by othqsa95** [woocommerce/woocommerce-paypal-payments#2504]
Each order is failed the 1st time, and second try or third try, the order is successful.

When I test with my debit card, I'm charged directly.

When the clients want to finalize their orders, the clients need to SPAM the button Place Order in order to finalize their order.

**Comment by SydeKrystian** [comment]
Hello @othqsa95 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
