### ISSUE TITLE
refund of payment fails

### ISSUE THREAD

**Issue by devrimkaya** [woocommerce/woocommerce-paypal-payments#2507]
when trying refund an order, got an alert on below screenshot

![image](https://github.com/user-attachments/assets/ffdcd144-bc51-4603-b73f-4bdd8eccbdd2)

on ajax response there is nothing more than screen alert. 
![image](https://github.com/user-attachments/assets/183e2262-4669-4b1d-90d9-45ec3698b23b)
 this is the request on ajax
![image](https://github.com/user-attachments/assets/b6ae5faf-2974-4e68-bd77-3807d60b0b3d)
I have tested refund some time ago and it was working ok. this is he first request after a year and not working. 
Is there any log that I can look into?

**Comment by SydeKrystian** [comment]
Hello @devrimkaya 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
