### ISSUE TITLE
PayPal validation give validation error on phone number.

### ISSUE THREAD

**Issue by SleepyCrom** [woocommerce/woocommerce-paypal-payments#2510]
### Describe the Bug

On our checkout page PayPal validation give validation error on phone number. Even if phone number if correct. Everything work if you just rewrite the phone number. By default WooCommerce take phone number for user account. So seams that this have to be marked as dirty before validation works. 

I think issue with this is a javascript issue. We use a Wordpress plugin called "Country Code Selector Pro", Versjon 1.6, by INTOLAP. This plugin helps people put in country code on their phone number. PayPal plugin we use is WooCommerce PayPal Payments, Versjon 2.8.3, by WooCommerce.  

### To Reproduce

1. Go to checkout page. 
2. Try to pay without touching phone number

### Screenshots

![Skjermbilde 2024-08-13 kl  13 00 34](https://github.com/user-attachments/assets/5bfa0055-0e5c-4ba9-8167-1496e05974e8)

### Expected Behavior

Going to next step in the payment process. 

### Actual Behavior

Give a validation error, actual two - but you only need to edit phone number.

### Environment

- Wordpress, version 6.6.1
- WooCommerce versjon 9.1.4
- Country Code Selector Pro", versjon 1.6, by INTOLAP
- WooCommerce PayPal Payments, versjon 2.8.3, by WooCommerce.  

### Additional Details

</details>

**Comment by SydeKrystian** [comment]
Hello @SleepyCrom 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

The issue you're experiencing can likely be resolved with a workaround found in our documentation. Please check it out here: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors#custom-field-not-validated-when-clicking-the-paypal-button

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
