### ISSUE TITLE
I cannot log in or create a new account for a Canadian business - it only shows American States and no place to enter a country.

### ISSUE THREAD

**Issue by gerrybakker-github** [woocommerce/woocommerce-paypal-payments#2512]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by gerrybakker-github** [comment]
new install of woocommerce on a Godaddy woocommerce account.

**Comment by SydeKrystian** [comment]
Hello @gerrybakker-github 

It seems that your GitHub issue is primarily a support request which should be analyzed directly by [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/). 

 In case of doubts for a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

Looking forward to your response.

Kind regards,
Krystian
