### ISSUE TITLE
Paypal and Account Funds for WooCommerce

### ISSUE THREAD

**Issue by OtterBees** [woocommerce/woocommerce-paypal-payments#2518]
### Describe the Bug

When a customer adds funds to their account using the "Account Funds" plugin, and then checks out via Paypal, Paypal deducts the Paypal fee from the **customer's funds**, instead of applying the entire amount of funds to the customer account and deducting the Paypal fee from the business's net. This just started happening in the past month, we think...

### Expected Behavior

The Paypal fee should NOT be deducted from the customer's funds. The Paypal fee should only be deducted from the business's net, while the FULL AMOUNT of funds the customer is choosing to add to their account should be attributed to said account.

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.1.4
 - Plugin "Account Funds for WooCommerce" Version 3.1.0 
 - Browser n/a

**Comment by SydeKrystian** [comment]
Hello @OtterBees 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
