### ISSUE TITLE
No payment with credit card possible

### ISSUE THREAD

**Issue by web4studio** [woocommerce/woocommerce-paypal-payments#2524]
Error Message:
2024-08-20T05:08:56+00:00 Warnung No PayPal order ID found in order #133577 meta.
2024-08-20T05:08:56+00:00 Fehler Payment failed: There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again. OrderProcessor.php:222
2024-08-20T05:14:51+00:00 Warnung No PayPal order ID found in order #133578 meta.
2024-08-20T05:14:51+00:00 Fehler Payment failed: There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again. OrderProcessor.php:222
..

<img width="473" alt="Bildschirmfoto 2024-08-21 um 14 23 07" src="https://github.com/user-attachments/assets/688ceb9b-da1f-4ee1-b7a5-236e0e0a5c01">
<img width="1624" alt="Bildschirmfoto 2024-08-21 um 14 22 49" src="https://github.com/user-attachments/assets/0e93c262-dba5-4116-9299-59b340215dfb">
[woocommerce-paypal-payments-2024-08-20.log](https://github.com/user-attachments/files/16691403/woocommerce-paypal-payments-2024-08-20.log)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @web4studio 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
