### ISSUE TITLE
No funciona pago a 3 meses

### ISSUE THREAD

**Issue by Loroweb** [woocommerce/woocommerce-paypal-payments#2536]
### Describe the Bug

No funciona el pago a 3 meses. Un cliente despues de validar el pago, le vuelve a nuestra web sin mas. 
<img width="1401" alt="Captura de pantalla 2024-08-27 a las 11 04 02" src="https://github.com/user-attachments/assets/727a7838-fd8b-4455-ab2f-b1ea5608f691">

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Expected Behavior

No funciona el pago aplazado a 3 meses

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Loroweb 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
