### ISSUE TITLE
Sandbox mode stuck

### ISSUE THREAD

**Issue by AlfFello** [woocommerce/woocommerce-paypal-payments#2538]
### Describe the Bug

<I cannot get out of sandbox mode, no matter what I click.>

### To Reproduce

1. When I click on Disconnect from PayPal Sandbox
2. Then I scroll down to go to 'Enable Advance Card Payments'
3. It still thinks that I am in test mode.
So the problem is I cannot seem get out of test mode (or sandbox mode). 

### Screenshots

<![image](https://github.com/user-attachments/assets/e7cff478-9f27-492f-8bfa-04de252886ed)>

### Environment

 - WordPress Version newest
 - WooCommerce Version 9.2.3
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed (I am using the Fewer theme).

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @AlfFello 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
