### ISSUE TITLE
Can't Disconnect Account (3621)

### ISSUE THREAD

**Issue by bindashsandeep** [woocommerce/woocommerce-paypal-payments#2539]
![Screenshot (3)](https://github.com/user-attachments/assets/31101628-293d-464d-b2ad-e349eedb67bf)

I tried to disconnect but it's not doing anything after click.

**Comment by InpsydeNiklas** [comment]
Hi @bindashsandeep, thanks for reporting this issue. It seems the `Disconnect Account` button may have stopped working when using WooCommerce 9.2.0 or newer. Downgrading WooCommerce to [version 9.1.4](https://github.com/woocommerce/woocommerce/releases/tag/9.1.4) can temporarily resolve the issue.
Alternatively, clearing the plugin settings from the bottom of the Connection tab would successfully disconnect the account, but it would also reset every other PayPal Payments setting back to the default.
