### ISSUE TITLE
Problem with Google Chrome

### ISSUE THREAD

**Issue by FXR87** [woocommerce/woocommerce-paypal-payments#2540]
After updating the plugin, problems arose related to the type of browser used.

Using Firefox everything is fine and you can see all the payment methods, while with Chrome there are some display problems such as the lack of payment by credit card (as visible in the screenshots)

![Payments - Firefox](https://github.com/user-attachments/assets/63ac11c4-1189-45d5-9826-868005ea19cf)
![payments chrome (phone)](https://github.com/user-attachments/assets/121537d5-9e2e-4fd2-abfb-019f79664364)

Furthermore, the PayPal buttons do not appear when you choose the payment method.

**Comment by SydeKrystian** [comment]
Hello @FXR87 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
