### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'clickUrl')

### ISSUE THREAD

**Issue by madmaxaus** [woocommerce/woocommerce-paypal-payments#2551]
### Describe the Bug

Visit any shopping, product or checkout page on. eg. 

https://myvagina.com/shop

get a bunch of paypal errors in the console:
get this warning first:
{
    "description": "Invalid option value (currency). Expected AUD but received \"USD\"",
    "timestamp": "1725268170259"
}

then errors:

{
    "err": "TypeError: Cannot read properties of undefined (reading 'clickUrl')\n    at https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:379824\n    at Array.map (<anonymous>)\n    at gf (https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:379673)\n    at https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:381894\n    at Array.reduce (<anonymous>)\n    at https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:381853\n    at transport (https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:381937)\n    at https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:120482\n    at e.try (https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:76842)\n    at b (https://www.paypal.com/sdk/js?client-id=BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU&currency=USD&integration-date=2024-08-07&components=messages,buttons&vault=false&commit=false&intent=capture&disable-funding=card,venmo,paylater&enable-funding=venmo:3:120277)",
    "timestamp": "1725268170326",
    "uid": "uid_5bfcddfe20_mdg6nty6mza",
    "env": "production",
    "clientId": "BAAo9oNnBwSY2Z77p7HFnvlj0MppTpbj8NukrtuLkfhDX6QZE1jLadLszKnz4a5D2Cf7ceGhfGdu_IJ_qU",
    "csnwCorrelationId": "f17887289cc00",
    "referrer": "myvagina.com",
    "version": "5.0.457",
    "merchantId": [],
    "sessionId": "uid_5bfcddfe20_mdg6nty6mza",
    "userAction": "continue"
}

### To Reproduce

1. Go to https://myvagina.com/shop/
2. view console
3. See error

### Environment

 - WordPress Version: 6.6.1
 - WooCommerce Version: 9.2.3 
 - Plugin Version: 2.8.3
 - Browser [e.g. Chrome, Safari] and Version: any
 - Any other plugins installed:
 
FunnelKit Automations | Version 3.1.2 by FunnelKit \| Auto-updates disabled
-- | --
FunnelKit Automations Connectors | Version 3.0.1 by FunnelKit \| Auto-updates disabled
FunnelKit Automations Pro | Version 3.1.0 by FunnelKit \| Auto-updates disabled
FunnelKit Cart for WooCommerce | Version 1.7.1 by FunnelKit \| Auto-updates disabled
FunnelKit Funnel Builder | Version 3.5.2 by FunnelKit \| Auto-updates disabled
FunnelKit Funnel Builder Pro | Version 3.5.2 by FunnelKit \| Auto-updates disabled

### Additional Details

we are based in australia and use USD, i suspect this is the problem as switching to AUD fixes it. not an option as all our customer are in USA

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @madmaxaus 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by madmaxaus** [comment]
looks like the latest update fixed it
