### ISSUE TITLE
Vaulting not working

### ISSUE THREAD

**Issue by kudaleganesh** [woocommerce/woocommerce-paypal-payments#256]
### Describe the bug
Vaulting is not working. Do not create the token for subscription products. 
There is no filter through which we can force the vaulting/tokenization for other products.

### To reproduce

1. Place the order.
2. Check the order meta, no token is stored.

**Screenshots**

### Expected behavior
Create the token for checkout orders if products contain subscriptions. The filter ( apply_filters ) enables tokenization for all products.

**Environment (please complete the following information):**
 - WordPress Version :5.8
 - WooCommerce Version:5.6
 - WooCommerce PayPal Payments Plugin Version: Latest
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

### Additional details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by Dinamiko** [comment]
Fixed by #308.
