### ISSUE TITLE
WooCommerce Plugins not updating

### ISSUE THREAD

**Issue by adspecs** [woocommerce/woocommerce-paypal-payments#2560]
### Describe the Bug

Tried running WC updates 

1. Woo Subscriptions

2. WooCommerce PayPal Payments

### To Reproduce

1. Go to '…'
3. Click on '…'
4. Scroll down to …'
5. See error

### Screenshots

![WooC Update Errors](https://github.com/user-attachments/assets/67a4538d-6eda-4df1-8f48-a1d3b1a2aeed)

### Expected Behavior

Plugin to UPDATE

### Actual Behavior

Update failed: Update package not available.

### Environment

 - WordPress Version: [WordPress 6.6.1]
 - WooCommerce Version: Version 9.2.3
 - Plugin Version
 - Browser: Firefox
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @adspecs 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
