### ISSUE TITLE
Duplicated Credit Card Fields (3657)

### ISSUE THREAD

**Issue by balmerp** [woocommerce/woocommerce-paypal-payments#2567]
### Describe the Bug

On website www.waterwayroutes.co.uk

After upgrade from 2.8.3 to 2.9 the Credit Card number, expiry and CVV fields are duplicated and a customer has to enter their information in the second of each field.

Reverting to 2.8.3 solves the problem.  No other changes were made to the website at the time.

### To Reproduce

Add a product to the shopping cart
Go through the checkout process
Choose Card Payment and not PayPal payment
The card fields (Number, Expiry and CVV)  are shown duplicated, one above the other.

### Expected Behavior

The card fields should not be duplicated

### Environment

 - WordPress = 6.6.1 running Hueman theme
 - WooCommerce Version = 9.2.3
 - Plugin Version 2.9 is faulty, version 2.8.3 works fine
 - Browser [e.g. Chrome, Safari] and Version  Chrome
 - Any other plugins installed = WooCommerce Extended Coupon Features FREE and WooCommerce Shipping & Tax

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by harmansingh03** [comment]
Hello there,
I've also had same issue but fixed removing an important from my theme style has fixed the duplicated credit card fields.

**Before**:
#payment input, #payment label {
  display: inline !important;
}

**After**: 
#payment input, #payment label {
  display: inline;
}

You can try this change for your theme style and check the fields.

**Comment by mmalferov** [comment]
In my **Twenty twenty** theme, the fields were broken by the following rule:

```
...
input[type="tel"] {
    ...
    display: block;
    ...
}
```

I changed it to:

```
input[type="tel"]:not(.input-text) {
    display: block;
}
```

...to one did not affect the checkout fields contains `input-text` CSS class for inputs ;-)
