### ISSUE TITLE
Visitors are getting Credit Card errors, stating their information in incorrect, when it is correct.

### ISSUE THREAD

**Issue by ChadAustinMarketing** [woocommerce/woocommerce-paypal-payments#2569]
### Describe the Bug

Visitors are getting Credit Card errors, stating their information is incorrect, when it is correct. It doesn't happen with every visitor, meaning, some credit cards do go through for some visitors. It is not card specific. 

Looking at the error logs, I found that woocommerce-paypal-payments generated the following error:
[woocommerce-paypal-payments-2024-09-04.log](https://github.com/user-attachments/files/16879541/woocommerce-paypal-payments-2024-09-04.log)

### To Reproduce

https://www.hickoryhop.com/checkout/

### Screenshots

n/a
### Expected Behavior

Visitor expects their credit card to go through. 
### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.2.3
 - Plugin Version 2.9.0
 - Browser [e.g. Chrome, Safari] and Version   Chrome 128.0.6613.120 (Official Build) (x86_64)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

Thanks,
Chad

**Comment by SydeKrystian** [comment]
Hello @ChadAustinMarketing 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
