### ISSUE TITLE
WooCommerce PayPal Payments bug, double fields in card payment

### ISSUE THREAD

**Issue by toni-scl** [woocommerce/woocommerce-paypal-payments#2572]
### Describe the Bug

When uploading the plugin WooCommerce PayPal Payments to the version 2.9.0, the fields to enter the card data are duplicated, appear in 2 languages.

### To Reproduce

1. Buy a product
2. Go to payment methods
3. Pay with card

### Screenshots

![paypal_bug](https://github.com/user-attachments/assets/41505bef-61ce-4480-a7e9-4595009925ba)

 - WordPress Version: 6.6.1
 - WooCommerce Version: 9.2.3
 - Plugin Version: 2.9.0
 - Browser: Google Chrome, 128.0.6613.113 (Build oficial) (arm64)

**Comment by harmansingh03** [comment]
Hello there,
I've also had same issue but fixed removing an important from my theme style has fixed the duplicated credit card fields.

Before:
#payment input, #payment label {
display: inline !important;
}

After:
#payment input, #payment label {
display: inline;
}

You can try this change for your theme style and check the fields.

**Comment by SydeKrystian** [comment]
Hello @toni-scl 



We want to provide an update on this issue with double-hosted fields in Advanced Card Processing. We have managed to fix this pre-release version [2.9.1-alpha](https://drive.google.com/uc?export=download&id=1LBtZ-XJIdd7q3DJYJAY9t1MyeDQNkZ2p). Please keep in mind that this is a preview on the next update, which means it hasn't been fully tested, but we appreciate any feedback you might have as you try it.

When introducing new features or making significant changes to your website, it is crucial to test these modifications in a controlled Staging environment before deploying them to your live site. We highly recommend that you initially implement and test any new features on a staging site.

Let us know if that works for you.

Kind regards,
Krystian
