### ISSUE TITLE
Double input field for credit cards

### ISSUE THREAD

**Issue by WebWebBender** [woocommerce/woocommerce-paypal-payments#2576]
### Describe the Bug

In the payment method field, a double input field appears for credit card, expiration date and CVV. With all browsers.

### Screenshots

![Screenshot](https://github.com/user-attachments/assets/fe74628d-3c93-49b3-a7df-ed259b047022)

### Environment

Info del server: 		Apache
Versione PHP: 		8.2.23

WordPress 6.6.1
Versione di WooCommerce: 		9.2.3

[Gravity Forms](https://gravityforms.com/) 	  	di Gravity Forms – 2.8.17
[Bulk Edit Products, Prices & Attributes for Woocommerce](https://elextensions.com/plugin/bulk-edit-products-prices-attributes-for-woocommerce/) 	  	di ELEXtensions – 2.0.1
[Easy WooCommerce Tracking Code Free](https://wordpress.org/plugins/easy-woocommerce-tracking-code-free/) 	  	di webrook – 1.1.0
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/) 	  	di Elementor.com – 3.23.3
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash) 	  	di Elementor.com – 3.23.4
[iubenda | All-in-one Compliance for GDPR / CCPA Cookie Consent + more](https://www.iubenda.com/) 	  	di iubenda – 3.11.0
[Klarna Order Management for WooCommerce](https://krokedil.se/klarna/) 	  	di klarna, krokedil – 1.9.2
[Klarna Payments for WooCommerce](https://krokedil.com/klarna-payments/) 	  	di klarna – 3.6.2
[Loco Translate](https://wordpress.org/plugins/loco-translate/) 	  	di Tim Whitlock – 2.6.11
[PixelYourSite PRO](http://www.pixelyoursite.com/) 	  	di PixelYourSite – 10.4.4
[Product Catalog Feed Pro by PixelYourSite](https://www.pixelyoursite.com/product-catalog-facebook) 	  	di PixelYourSite – 5.4.4.1
[Rey Core](http://www.reytheme.com/) 	  	di ReyTheme – 3.0.0
[Speed Optimizer](https://it.siteground.com/) 	  	di SiteGround – 7.6.4
[Security Optimizer](https://siteground.com/) 	  	di SiteGround – 1.5.3
[TI WooCommerce Wishlist](https://wordpress.org/plugins/ti-woocommerce-wishlist/) 	  	di TemplateInvaders – 2.8.2
[Tidio Chat](http://www.tidio.com/) 	  	di Tidio LLC – 6.0.21
Big File Uploads 	  	di Infinite Uploads – 2.1.3
[WooCommerce Cart Abandonment Recovery](https://cartflows.com/) 	  	di CartFlows Inc – 1.3.0
[WooCommerce Custom Fields](http://www.rightpress.net/woocommerce-custom-fields) 	  	di RightPress – 2.3.4
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) 	  	di WooCommerce – 2.9.0
[WooCommerce](https://woocommerce.com/) 	  	di Automattic – 9.2.3
[Yoast SEO](https://yoa.st/1uj) 	  	di Team Yoast – 23.4
[WP Media folder](http://www.joomunited.com/) 	  	di Joomunited – 5.9.3

**Theme**
Nome: 		Rey Child
Versione: 		1.0.0
URL Autore: 		https://twitter.com/mariushoria
Tema child: 		
Nome del tema genitore: 		Rey
Versione del tema genitore: 		3.0.0
URL autore del Tema Genitore: 		https://twitter.com/mariushoria
Supporto WooCommerce:

**Comment by harmansingh03** [comment]
Ciao WebBender,
Anch'io ho avuto lo stesso problema e sono riuscito a risolvere togliendo un important su display inline

Prima:
#payment input, #payment label {
display: inline !important;
}

Dopo:
#payment input, #payment label {
display: inline;
}

Cerca di vedere nell'ispeziona a quale id/classe hai un important e lo cambi

Fammi sapere se riesci a risolvere così

**Comment by WebWebBender** [comment]
Ciao, grazie @harmansingh03 per la tua risposta.

Nel mio caso viene generato un secondo campo input (oltre a quello standard di paypal > id="ppcp-credit-card-gateway-card-number") con id #zoid-paypal-card-number-field-uid_xxxxxxxx. Questo campo ha css inline {display: inline-block;} che non riesco a sovrascrivere.

![Screenshot 2024-09-10 alle 10 45 23](https://github.com/user-attachments/assets/7864201a-0a99-44f8-a768-f33a64bb64c5)

Temo che questo doppio campo interferisca in fase di acquisto e vorrei capire se esiste il modo per eliminare il campo doppio, tenendo solo quello paypal.

Ho lavorato disattivando i plugin e niente ha funzionato.

**Comment by WebWebBender** [comment]
Ho appena trovato questo articolo: 
https://bluepnume.medium.com/introducing-xcomponent-seamless-cross-domain-web-components-from-paypal-c0144f3e82bf

**Comment by SydeKrystian** [comment]
Hello @WebWebBender 

The issue was resolved with the fixing package provided in the Jira ticket, so I'm closing it.

Kind regards,
Krystian
