### ISSUE TITLE
Double Tax on PayPal Pay Later Orders

### ISSUE THREAD

**Issue by mrl22** [woocommerce/woocommerce-paypal-payments#2583]
### Describe the Bug

We have an e-commerce store with three different payment options.

Credit Card (Opayo)
PayPal
PayPal Pay Later

When placing an order via PayPal Pay Later, the tax is charged twice. 

I have not seen any evidence to suggest that normal PayPal payments are charged twice.

### To Reproduce

1. Create a product with tax
2. Order that item and opt for PayPal Pay Later

I am uncertain if there is any special condition or configuration that is causing this issue.

### Screenshots

Normal Credit Card Payment (Correct)
![image](https://github.com/user-attachments/assets/29bd4006-b936-4eb5-933d-998a647ff9e4)

PayPal Pay Later Order (Tax charged twice)
![image](https://github.com/user-attachments/assets/30f1e342-ff60-4557-a6f5-adacdd9f6acc)

### Expected Behavior

All orders should total their correct amount.

### Actual Behavior

Tax is being charged on each order item and then also on the order sub total.

### Environment
 - PHP Version: 8.2.19
 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.1.4
 - Plugin Version: 2.9.0

**Comment by SydeKrystian** [comment]
Hello @mrl22 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
