### ISSUE TITLE
Woocommerce Order Goes from Processing --> Failed | Paypal Payments

### ISSUE THREAD

**Issue by MMWeb-Dev** [woocommerce/woocommerce-paypal-payments#2593]
### 
Hi, a website that I created currently has some issues with orders going from 'Processing' to 'Failed'. It happens only with PayPal Transactions. However the money is processed and arrives into the Paypal account. 

This error is not recreated when customers pay with other payment methods (Stripe, GooglePay/Apple Pay). 

## To Reproduce Behaviour: 
1. Customer purchases item from store (using Paypal as payment method). 
2. See below image: 
![image](https://github.com/user-attachments/assets/687eb1c5-ca37-4f06-838d-1c838f85672c)

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.1
 - Plugin: Version 2.9.0
 - Browser: Chrome 
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @MMWeb-Dev 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
