### ISSUE TITLE
PayPal checkout requires "Company" field despite it not being set as mandatory in WooCommerce

### ISSUE THREAD

**Issue by haxd21** [woocommerce/woocommerce-paypal-payments#2602]
Describe the Bug:
When using WooCommerce PayPal Payments (v2.9.0), the "Company" field is being marked as required only when the PayPal payment method is selected. This happens despite the field not being set as mandatory in WooCommerce's checkout field settings. The issue only occurs with PayPal and not with other payment methods.

To Reproduce:
Go to WooCommerce checkout page.
Select PayPal as the payment method.
Proceed to checkout without filling the "Company" field.
See error: "Company" field is required.
Expected Behavior:
The "Company" field should not be required unless explicitly set as mandatory in WooCommerce checkout settings.

Actual Behavior:
The "Company" field becomes required whenever PayPal is selected as the payment method, even though it is not set as mandatory in WooCommerce.

**Comment by SydeKrystian** [comment]
Hello @haxd21 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
