### ISSUE TITLE
"Buy Now, pay later" cannot be switched off

### ISSUE THREAD

**Issue by pbruetzk** [woocommerce/woocommerce-paypal-payments#2607]
### Describe the Bug

As of right now, the function within PayPal payments "buy now, pay later" cannot be switched off. I've tried to turn it off, but the button next to my product page does not disappear

**Comment by SydeKrystian** [comment]
Hello @pbruetzk 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
