### ISSUE TITLE
Standard Payments, Changing Smart Button Color, Label, Shape, Layout, etc. - Changes Do Not Apply After Saving, Goes Back To Default.

### ISSUE THREAD

**Issue by conzxo** [woocommerce/woocommerce-paypal-payments#2609]
Hi there,
I’ve set up the Paypal plugin “WooCommerce PayPal Payments”.
I want want to change the colors and shape of the smart buttons.
However when I change options in the Standard Payment settings and save, the settings go back to default, as if I have changed nothing.
Can you help me resolve this ?

To Reproduce
1. Go to Woocommerce / Payments / Payment methods / PayPal
2. Click on "Standard Payments" tab
3. Scroll down to "PayPal Smart Buttons"
4. Change the "Button Layout" or "Color" of the "PayPal Smart Buttons"
5. Save changes

![Issue](https://github.com/user-attachments/assets/611285ce-eab5-4e06-b75a-171d03c31f5b)

Expected Behavior
I want to change the "Button Layout" & "Color" of the Smart Buttons to be displayed on my website.

Actual Behavior
After saving changes, the settings do not apply = They just revert back to default as if I hadn't changed anything. Nothing else on the "Standard Payments" page saves either, Enable/Disable Paypal features for your store doesn't save. nothing saves.

Environment
WordPress Version : 6.6.2
WooCommerce Version : 9.3.1
Plugin Version : 2.9.0
Browser [e.g. Chrome, Safari] and Version : Google Chrome: 128.0.6613.138 (Official Build) (64-bit)

**Comment by SydeKrystian** [comment]
Hello @conzxo 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
