### ISSUE TITLE
PayPal Payment Processing Issue with Currency Switcher on WooCommerce

### ISSUE THREAD

**Issue by ayushman-t** [woocommerce/woocommerce-paypal-payments#2616]
### Describe the Bug

We're experiencing an issue with the PayPal Payments Plugin and a [currency switcher plugin](https://docs.yithemes.com/yith-multi-currency-switcher-for-woocommerce/) on our beta WooCommerce site. When a customer switches a product price from USD to CAD, PayPal continues to charge the customer in USD instead of the selected CAD amount.

### To Reproduce

Set a product price at 1 USD.
Use the currency switcher to change the price to 1.36 CAD.
Proceed to checkout and select PayPal as the payment method.
Observe that PayPal charges 1.36 USD instead of 1.36 CAD.

### Screenshots

![image_2024_09_17T18_32_42_657Z](https://github.com/user-attachments/assets/d7a546d5-4bef-4faf-b7f2-f71c9d54bc33)
![image_2024_09_17T18_30_36_430Z](https://github.com/user-attachments/assets/64b97dcb-768b-48fd-b091-aa7010f772ef)

### Environment

 - WordPress Version: Latest 
 - WooCommerce Version: Latest
 - Plugin Version: Latest
 - Browser [e.g. Chrome, Safari] and Version: Chromium Based Edge
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @Ayushmanwebdeveloper 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
