### ISSUE TITLE
refund using advanced card processing doesn't actually refund the customer 

### ISSUE THREAD

**Issue by tlarsh3** [woocommerce/woocommerce-paypal-payments#2625]
### Describe the Bug
Advanced card processing used to allow refunding the customer through the backend of the website. I have attempted two refunds on two seperate occasions, specifying dollar amount. But come to find out the money never gets refunded or shows the refund status in paypal. So needless to say i had to manually refund the order directly in paypal. 

I have even tried refunding again and it errors out as it should because you should never be able to refund more than they paid. 

### To Reproduce

1, go to an order.
2. click refund button
3.  type refund amount
4. click refund with advanced card processing. 
5.  it will act like it went through successfully, and update the order with refund status.
6.  check paypal account and order will still be in "completed" status not refunded. 

### Expected Behavior

when putting in an amount to refund, click refund with advance card processing it should refund the customer. 

### Actual Behavior

website acts as if it refunded the customer. Paypal does not reflect or actually refund the customer 

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.3.2
 - Plugin Version 2.9.0
 - Browser [e.g. Chrome, Safari] and Version chrome
 - Any other plugins installed 

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by MKB7862024** [comment]
Yes Same thing happeing to me there is any fix it was working before the latest update .

**Comment by SydeKrystian** [comment]
Hello @tlarsh3 & @MKB7862024 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
