### ISSUE TITLE
After filling billing information,  Paypal buttons dispappear

### ISSUE THREAD

**Issue by ericlapier** [woocommerce/woocommerce-paypal-payments#2628]
### Describe the Bug

When our customers try Proceed to checkout and enter the billing details, the paypal buttons disappear

### To Reproduce

1. Goto https://artsvisuelsgatineau.com/en/product/renouvellement/
2. Add to Cart
3. View cart
4. Proceed to checkout  ("Pay with Paypal" button appears at the bottom)
5. Enter Billing details ("Pay with Paypal" button disappear at the buttom)

### Screenshots
![image](https://github.com/user-attachments/assets/ac28e3c4-a350-446f-92b2-c41374ffed66)

### Expected Behavior

Paypal buttons should not disappear when user is ready to click to pay

### Actual Behavior

Paypal buttons  disappear when user is ready to click to pay

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version  9.3.2
 - Plugin Version   Woocommerce PayPal Payments 2.9.0
 -                           
 - Browser :  all
 - Any other plugins installed: Waitlist Woocommerce 2.7.7
                                                TranslatePress - Multilingual 2.8.3

**Comment by SydeKrystian** [comment]
Hello @ericlapier 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
