### ISSUE TITLE
Vaulting activated on Frontend although the option is unchecked in the backend settings

### ISSUE THREAD

**Issue by flowbecca** [woocommerce/woocommerce-paypal-payments#2630]
### Describe the Bug

On payment page, under credit cards "Save to account" is active on the frontend although "Vaulting" is disabled in the backend.  
The "Payment methods / saved methods" tab also appear in the client account page although "Vaulting" is disabled in the backend. 

### To Reproduce

1. Go to advanced card processing settings
2. Uncheck "vaulting"
3. Save
4. See vaulting activated on the frontend

### Screenshots

![Capture d'écran 2024-09-21 075730](https://github.com/user-attachments/assets/e3a48fd1-ee80-422f-b19e-93c364e6f551)

### Expected Behavior

Is Vaulting option is unchecked,  "Save to account" and  the"Payment methods / saved methods" tab should NOT appear on the frontend

### Actual Behavior

When Vaulting option is unchecked,  "Save to account" and  the"Payment methods / saved methods" tab are visible on the frontend

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.2 
 - Plugin Version 2.9.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by PhillBex** [comment]
I am also experiencing this issue, so would be interested in the response
