### ISSUE TITLE
not compatible with hpos, website crashes with 2.9.1

### ISSUE THREAD

**Issue by anzgar01** [woocommerce/woocommerce-paypal-payments#2641]
### Describe the Bug

When I install the latest version of woocommerce paypal payments 2.9.1, my website crashes. When entering recovery mode, there is an error stating that woocommerce paypal payments is not compatible with high performance order storage.
Reverting the plugin to 2.9.0 solves this problem, but can't be a permanent fix.

### To Reproduce

Install 2.9.1, see your website crash

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.3
 - Plugin Version: 2.9.1
 - Browser: Chrome 129.0.6668.70 
 - Any other plugins installed: woocommerce stripe gateway, yith subscriptions, ...

<details><summary>System status</summary>

</details>

**Comment by SydeKrystian** [comment]
Hello @anzgar01 
It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a more detailed investigation, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). When you contact us, please include the following:

- A copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us gather more details about your setup.- 
- The fatal error message that appeared during recovery mode from WordPress. This information will be crucial in diagnosing the crash.

Once we have this information, we’ll be better equipped to assist you and address the compatibility issue with HPOS. We apologize for any inconvenience this has caused and are eager to help resolve it for you.

Thank you for your understanding, and we look forward to hearing from you soon.

Kind Regards,
Krystian
