### ISSUE TITLE
WooPayments PayPal Buttons

### ISSUE THREAD

**Issue by ez-catherineja** [woocommerce/woocommerce-paypal-payments#2655]
### To Reproduce

1. Go to https://kitchenfantasy.com/product/kids-macarons-8-26-2024-330pm-hands-on/
2. Click on Buy Now
3. Scroll down to bottom of Cart
4. See error - Pay Pal buttons are on top, should be below the Woo/Apple/Google Pay options

### Screenshots
<img width="709" alt="Screenshot 2024-09-28 at 10 05 41 AM" src="https://github.com/user-attachments/assets/bb7660a9-6a20-452b-9dbb-c4994d36795e">

### Expected Behavior
<img width="771" alt="Screenshot 2024-09-28 at 10 07 26 AM" src="https://github.com/user-attachments/assets/3941df58-2f70-4c12-931e-7a24c889e258">

PayPal should be at the bottom of choices

### Actual Behavior

PayPal is at bottom on Product and Checkout.  PayPay is on top of Payment options on the Cart page.

### Environment

 - WordPress Version. 6.6.2
 - WooCommerce Version. 9.3.3
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version. Chrome Version 129.0.6668.58 (Official Build) (arm64)
 - Any other plugins installed WooPayments, PayPal Payments

### Additional Details

<details><summary>System status</summary>

  ```
  <!--<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.3
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.23
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.81.0
OpenSSL/3.0.2

SUHOSIN Installed: –
MySQL Version: 8.0.37-29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 851
cpt_courses: 6
cpt_layouts: 5
cpt_services: 9
cpt_team: 6
cpt_testimonials: 5
ctct_forms: 2
ctct_lists: 3
custom_css: 1
event_magic_tickets: 2517
flamingo_contact: 457
flamingo_inbound: 528
mc4wp-form: 1
nav_menu_item: 22
oembed_cache: 3
page: 24
post: 18
product: 126
product_variation: 33
shop_coupon: 51
shop_order: 2127
shop_order_refund: 104
wp_global_styles: 1
wpcf7_contact_form: 1
wpcode: 2
wpcr3_review: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Anti-Spam by CleanTalk: by СleanTalk - Anti-Spam Protection  – 6.41.1
Contact Form 7: by Takayuki Miyoshi – 5.9.8
Creative Mail by Newfold Digital: by Newfold Digital – 1.6.9
Duplicate Page: by mndpsingh287 – 4.5.4
Flamingo: by Takayuki Miyoshi – 2.5
Events Calendar by FooEvents: by FooEvents – 1.7.3
FooEvents for WooCommerce: by FooEvents – 1.19.33
FooEvents Bookings: by FooEvents – 1.7.17
FooEvents Custom Attendee Fields: by FooEvents – 1.7.4
FooEvents PDF Tickets: by FooEvents – 1.10.4
Site Kit by Google: by Google – 1.136.0
Heartbeat Control by WP Rocket: by WP Rocket – 2.0.1
WPCode Lite: by WPCode – 2.2.2
Jetpack: by Automattic – 13.8.1
WPBakery Page Builder: by Michael M - WPBakery.com – 7.9
NitroPack: by NitroPack Inc. – 1.17.0
Really Simple Security Pro: by Really Simple Plugins – 9.0.2
Slider Revolution: by ThemePunch – 6.6.4
Simple History: by Pär Thernström – 5.0.1
Sold Out Badge for WooCommerce: by Charlie Etienne – 4.4.0
ThemeREX Addons: by ThemeREX – 1.71.11.10
ThemeREX Socials: by ThemeREX – 1.4.5
ThemeREX Updater: by ThemeREX – 2.1.4
Checkout Field Editor for WooCommerce: by ThemeHigh – 2.0.3
Discount Rules PRO 2.0: by Flycart – 2.6.5
Discount Rules Core: by Flycart – 2.6.6
WooCommerce Manual Payment: by bfl – 2.8.4
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Stripe Gateway: by WooCommerce – 8.7.0
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WP Menu Cart: by WP Overnight – 2.14.6
WooPayments: by WooCommerce – 8.2.2
WooCommerce PayPal Payments: by WooCommerce – 2.9.1
WooCommerce: by Automattic – 9.3.3
Wordfence Security: by Wordfence – 7.11.7

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.8.0
WP Engine Cache Plugin: by WP Engine – 1.3.1
WP Engine Seamless Login Plugin: by WP Engine – 1.6.1
WP Engine Security Auditor: by wpengine – 1.1.1
WP Engine System: by WP Engine – 5.0.1

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 632 KB

### WC Pages ###

Shop base: #171 - /shop/
Cart: #545 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #547 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #310 - /account/
Terms and conditions: #1711 - /cancelation-policy/

### Theme ###

Name: Basil Child
Version: 1.0
Author URL: https://themeforest.net/user/axiomthemes/portfolio
Child Theme: ✔
Parent Theme Name: Basil
Parent Theme Version: 1.3.11
Parent Theme Author URL: https://themeforest.net/user/axiomthemes/portfolio
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooPayments ###

Version: 8.2.2
Connected to WPCOM: Yes
WPCOM Blog ID: 209817197
Account ID: acct_1LYYXE2ExN5vankI
Payment Gateway: Enabled
Test Mode: Disabled
Enabled APMs: card
WooPay: Enabled (product,cart,checkout)
WooPay Incompatible Extensions: No
Apple Pay / Google Pay: Enabled (product,cart,checkout)
Fraud Protection Level: basic
Multi-currency: Disabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Enabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: ✔
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-29 15:18:17 -07:00
Options: ✔
Notes: 175
Onboarding: completed

### Action Scheduler ###

Canceled: 31
Oldest: 2024-08-31 17:44:15 +0000
Newest: 2024-09-27 17:52:01 +0000

Complete: 616
Oldest: 2024-08-29 05:05:45 +0000
Newest: 2024-09-28 16:34:51 +0000

Pending: 1
Oldest: 2024-09-29 15:53:34 +0000
Newest: 2024-09-29 15:53:34 +0000

### Status report information ###

Generated at: 2024-09-28 10:09:34 -07:00
```
</details> -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @ez-catherineja 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
