### ISSUE TITLE
Choose anotherpayment method ppcp-cancel section BUG

### ISSUE THREAD

**Issue by WINITCOMPS** [woocommerce/woocommerce-paypal-payments#2656]
**### Describe the Bug**

We are using the PayPal Payments plugin on our WooCommerce site. Users must be logged in to make a purchase.

**Issue:**
When a logged-in user goes to checkout for the first time, they are presented with four payment options via PayPal:

Google Pay
Apple Pay
PayPal
Cards via PayPal

If the user chooses to pay with a card, the issue does not occur. However, if they select any of the other options (Google Pay, Apple Pay, or PayPal) and successfully complete the payment, a problem arises on subsequent purchases.

**Reproduction Steps:**
User is logged in and successfully completes a purchase using PayPal, Google Pay, or Apple Pay.
While still logged in, the user attempts to make another purchase.
During the checkout, only two payment options are available: PayPal and the last used payment method. The other two options (Google Pay and Apple Pay or Cards) are missing.

**Error:**
If the user proceeds with the available payment options (without clicking to reveal the other methods), an error occurs when trying to complete the payment:

**Error Message:**
Failed to process the payment. Please try again or contact the shop admin.
[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation.
https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED

**Workaround:**
To bypass the error, the user must click the link below the "Pay Now" button that says "Choose another payment method." Once clicked, the page reloads, and all four payment options (Google Pay, Apple Pay, PayPal, and Cards) are shown again, allowing the user to successfully complete the payment.

**Additional Notes:**
This issue only occurs for PayPal, Google Pay, or Apple Pay payments.
If the user logs out and logs back in, all payment options are shown correctly on the first checkout attempt.
This bug is affecting the user experience, as users are only presented with the correct payment options after manually clicking the "Choose another payment method" link or by logging out and back in.

Expected Behavior
Users should be able to make a second purchase using their previously saved payment method without any issues. All available payment options (Google Pay, Apple Pay, PayPal, and Cards via PayPal) should remain visible and selectable on subsequent checkout attempts without the need for the user to manually click the "Choose another payment method" link. The system should process payments smoothly with any previously saved method, whether it's PayPal, Google Pay, Apple Pay, or a card, without encountering errors or missing payment options.

Actual Behavior
When a logged-in user attempts to make a second purchase using PayPal, Google Pay, or Apple Pay, only two payment options are displayed during checkout: the last used payment method and PayPal. The other available options (Google Pay, Apple Pay, or Cards) are hidden.

If the user proceeds without manually clicking the "Choose another payment method" link, an error occurs when attempting to complete the payment:

Error Message:
Failed to process the payment. Please try again or contact the shop admin.
[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation.
https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED
This forces users to either click the link to reveal all payment options or log out and log back in to restore full payment functionality. The issue does not occur on the first purchase or when using a card as the payment method.

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.3
 - Plugin Version 2.9.1
 - Browser [e.g. Chrome, Safari] and Version tried just about everything mobile, pcs. windows and android, ios
 - Any other plugins installed just woocommerce ones

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 6 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.16
PHP Post Max Size: 6 GB
PHP Time Limit: 480
PHP Max Input Vars: 5000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.11.8-MariaDB-cll-lve
Max Upload Size: 6 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 211
aw_workflow: 4
custom_css: 1
elementor_library: 4
elementor_snippet: 2
jetpack_migration: 2
lty_ins_winner_log: 789
lty_instant_winners: 789
lty_lottery_ticket: 11997
nav_menu_item: 20
page: 30
post: 3
product: 42
product_variation: 12
revision: 454
shop_coupon: 9
shop_order_placehold: 836
wp_font_face: 33
wp_font_family: 12
wp_navigation: 1
wpcode: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.8.0
AutomateWoo: by WooCommerce – 6.1.0
Classic Widgets: by WordPress Contributors – 0.3
CookieYes | GDPR Cookie Consent: by CookieYes – 3.2.6
Duplicate Page: by mndpsingh287 – 4.5.4
Easy WP SMTP: by Easy WP SMTP – 2.6.0
Elementor Pro: by Elementor.com – 3.24.2
Elementor: by Elementor.com – 3.24.4
Facebook for WooCommerce: by Facebook – 3.2.9
Hostinger Tools: by Hostinger – 3.0.11
WPCode Lite: by WPCode – 2.2.2
Jetpack: by Automattic – 13.8.1
LiteSpeed Cache: by LiteSpeed Technologies – 6.5.1
Lottery for WooCommerce: by Flintop – 10.3.0
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: by Brevo – 3.1.86
Social Login Pro for WooCommerce: by WP Plugin Experts – 1.0.13
Storefront Blog Customiser: by WooCommerce – 1.3.0
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Homepage Contact Section: by WooThemes – 1.0.5
Storefront Mega Menus: by WooCommerce – 1.6.2
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.6.3
Storefront Pricing Tables: by WooCommerce – 1.1.0
Storefront Product Hero: by WooThemes – 1.2.13
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Reviews: by WooCommerce – 1.0.6
Import Export WordPress Users and WooCommerce Customers: by WebToffee – 2.5.7
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Additional Variation Images: by WooCommerce – 2.3.2
WooCommerce Brands: by WooCommerce – 1.7.6
WooCommerce PayPal Payments: by WooCommerce – 2.9.1
WooCommerce Points and Rewards: by WooCommerce – 1.8.9
Brevo - WooCommerce Email Marketing: by Brevo – 4.0.28
WooCommerce Subscriptions: by WooCommerce – 6.7.0
WooCommerce: by Automattic – 9.3.3
WPForms Lite: by WPForms – 1.9.1.2

### Inactive Plugins (0) ###


### Dropin Plugins () ###

object-cache.php: LiteSpeed Cache - Object Cache (Drop-in)

### Must Use Plugins (1) ###

Disable Auto Updates: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
lottery (lottery)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 3 MB

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/ -  Contains the woocommerce/cart block
Checkout: #8 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #9 - /my-account/
Terms and conditions: #316 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/customer-completed-order.php
storefront/woocommerce/emails/customer-processing-order.php


### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://winit.store
Subscriptions-core Library Version: 7.5.0
Subscription Statuses: wc-active: 1
wc-pending: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Subscriptions by Payment Gateway ###

Advanced Card Processing: wc-active: 1

### Payment Gateway Support ###

Advanced Card Processing: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

Google Pay (via PayPal): refunds
products

Apple Pay (via PayPal): products
PayPal: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
gateway_scheduled_payments


### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: GB
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: ✔
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: PayPal Subscriptions
PayPal Shipping Callback: –
Apple Pay: ✔
Google Pay: ✔
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-09-30 09:35:40 +01:00
Options: ✔
Notes: 67
Onboarding: skipped

### Action Scheduler ###

Complete: 64,244
Oldest: 2024-08-29 23:03:16 +0100
Newest: 2024-09-29 22:59:49 +0100

Failed: 3
Oldest: 2024-07-23 22:12:54 +0100
Newest: 2024-08-12 10:39:17 +0100

Pending: 25
Oldest: 2024-09-29 23:01:49 +0100
Newest: 2024-10-25 11:27:17 +0100


### Status report information ###

Generated at: 2024-09-29 23:00:01 +01:00
```
</details>

**Comment by SydeKrystian** [comment]
Hello @WINITCOMPS 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
