### ISSUE TITLE
ERROR Paypal - Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-CANNOT_MIX_CURRENCIES

### ISSUE THREAD

**Issue by vitorm119** [woocommerce/woocommerce-paypal-payments#2664]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @vitorm119 

We are aware of this problem. It seems that the recent update may have introduced compatibility issues with certain multi-currency plugins, as you’ve observed. Rest assured, our development team is actively working on a fix, which is scheduled to be included in the next regular update on October 14th.

In the meantime, the best workaround is to revert to the previous version of the PayPal Payments plugin (version 2.9.0). You can download the previous version from the following link: [Download Previous Version](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.0).

Simply download the woocommerce-paypal-payments.zip file and install it like any other plugin.

Kind Regards,

Krystian

**Comment by pimontazami** [comment]
Is there any news on this? Still haven’t seen the October 14 update. Should we expect it soon or is it really best to downgrade?
