### ISSUE TITLE
Problem with Subtotal mismatch behavior after 2.9.1 update

### ISSUE THREAD

**Issue by MDCCCLXXXIVV** [woocommerce/woocommerce-paypal-payments#2666]
### Describe the Bug

After WooCommerce PayPal Payments was updated to version 2.9.1, many clients start having trouble with paying via Paypal due to error with Subtotal mismatch behavior.

Although we have set to Add another line item, the payments fail due to subtotal mismatch, and the orders get cancelled. Switching to Do not send line items to Paypal didn't help either.

We haven't had any problems with any of the payments for several months since we started using WooCommerce PayPal Payments. All this seems to have started after 2.9.1. We use the latest version of every single extension we use.

Is this a known bug? Today there was an update 2.9.2 but such a bug is not mentioned on the changelog, unfortunately.

Does anybody else have this problem?

**Comment by SydeKrystian** [comment]
Hello @MDCCCLXXXIVV 

I noticed that you raised the [same issue](https://wordpress.org/support/topic/problem-with-subtotal-mismatch-behavior-after-2-9-1/) on wp.org. Let’s continue the discussion there, as GitHub is specifically dedicated to reporting developer-related issues, and this doesn't seem to fall under that category.

Looking forward to your response on wp.org.

Kind regards,
Krystian
