### ISSUE TITLE
strange symbols in card number field

### ISSUE THREAD

**Issue by InterlinguaFormazione** [woocommerce/woocommerce-paypal-payments#2670]
### Describe the Bug

When I go to pay by credit card I am seeing the strange symbols as seem in the screen shot and the place holders are not being translated into Italian.

### To Reproduce

1. Go to 'https://interlingua.it/e-learning-online/'
2. Click on 'create order and go to pay'

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.3
 - Plugin Version 2.9.2 
 - Browser [e.g. Chrome, Safari] and Version ALL![Image](https://github.com/user-attachments/assets/b4089b47-0ddc-40a4-84f6-95ada482adbf)

 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
![Image](https://github.com/user-attachments/assets/4c247255-eafc-4332-b81c-cf8aff7f6a9c)

**Comment by SydeKrystian** [comment]
Hello @InterlinguaFormazione 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
