### ISSUE TITLE
Something went wrong. Please try again or choose another payment source.

### ISSUE THREAD

**Issue by justdoitman00** [woocommerce/woocommerce-paypal-payments#2673]
Paypal error: "Something went wrong. Please try again or choose another payment source."

This error continues too appear 10-25 minutes after we think we have fixed it.

### To Reproduce

https://jacohorsetours.com/product/2-hour-jungle-tours/

Click the button to pay with Paypal.

### Screenshots

Attached

### Expected Behavior

Paypal error: "Something went wrong. Please try again or choose another payment source."

### Environment

WordPress address (URL): |   | https://jacohorsetours.com
-- | -- | --
Site address (URL): |   | https://jacohorsetours.com
WooCommerce version: |   | 9.3.3
WooCommerce Legacy REST API package: |   | The Legacy REST API plugin is not installed on this site.
Action Scheduler package: |   | 3.8.1 /var/www/vhosts/jacohorsetours.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable: |   | /var/www/vhosts/jacohorsetours.com/httpdocs/wp-content/uploads/wc-logs/
WordPress version: |   | 6.6.2
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

WordPress address (URL):		https://jacohorsetours.com
Site address (URL):		https://jacohorsetours.com
WooCommerce version:		9.3.3
WooCommerce Legacy REST API package:		 The Legacy REST API plugin is not installed on this site.
Action Scheduler package:		 3.8.1 /var/www/vhosts/jacohorsetours.com/httpdocs/wp-content/plugins/woocommerce/packages/action-scheduler
Log directory writable:		 /var/www/vhosts/jacohorsetours.com/httpdocs/wp-content/uploads/wc-logs/
WordPress version:		6.6.2
WordPress multisite:		–
WordPress memory limit:		256 MB
WordPress debug mode:		–
WordPress cron:		
Language:		en_US
External object cache:		–
Server environment
Server info:		Apache
PHP version:		8.2.24
PHP post max size:		2 GB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.68.0, OpenSSL/1.1.1f
SUHOSIN installed:		–
MySQL version:		10.3.39-MariaDB-0ubuntu0.20.04.2
Max upload size:		2 GB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WooCommerce database version:		9.3.3
Database prefix	 	MG7Lj_
Total Database Size	 	15.77MB
Database Data Size	 	11.90MB
Database Index Size	 	3.87MB
MG7Lj_woocommerce_sessions	 	Data: 0.11MB + Index: 0.02MB + Engine InnoDB
MG7Lj_woocommerce_api_keys	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_woocommerce_attribute_taxonomies	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_woocommerce_downloadable_product_permissions	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_woocommerce_order_items	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_woocommerce_order_itemmeta	 	Data: 0.06MB + Index: 0.03MB + Engine InnoDB
MG7Lj_woocommerce_tax_rates	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_woocommerce_tax_rate_locations	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_woocommerce_shipping_zones	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_woocommerce_shipping_zone_locations	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_woocommerce_shipping_zone_methods	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_woocommerce_payment_tokens	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_woocommerce_payment_tokenmeta	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_woocommerce_log	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_actionscheduler_actions	 	Data: 0.34MB + Index: 0.23MB + Engine InnoDB
MG7Lj_actionscheduler_claims	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_actionscheduler_groups	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_actionscheduler_logs	 	Data: 0.28MB + Index: 0.17MB + Engine InnoDB
MG7Lj_commentmeta	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_comments	 	Data: 0.05MB + Index: 0.09MB + Engine InnoDB
MG7Lj_cpappbk_forms	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_cpappbk_messages	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_e_events	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_e_notes	 	Data: 0.02MB + Index: 0.17MB + Engine InnoDB
MG7Lj_e_notes_users_relations	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_e_submissions	 	Data: 0.02MB + Index: 0.27MB + Engine InnoDB
MG7Lj_e_submissions_actions_log	 	Data: 0.02MB + Index: 0.11MB + Engine InnoDB
MG7Lj_e_submissions_values	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_gla_attribute_mapping_rules	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_gla_budget_recommendations	 	Data: 0.19MB + Index: 0.14MB + Engine InnoDB
MG7Lj_gla_merchant_issues	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_gla_shipping_rates	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_gla_shipping_times	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_imagify_files	 	Data: 0.02MB + Index: 0.08MB + Engine InnoDB
MG7Lj_imagify_folders	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_jetpack_sync_queue	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_links	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_options	 	Data: 7.47MB + Index: 0.09MB + Engine InnoDB
MG7Lj_postmeta	 	Data: 1.52MB + Index: 0.11MB + Engine InnoDB
MG7Lj_posts	 	Data: 0.33MB + Index: 0.06MB + Engine InnoDB
MG7Lj_termmeta	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_terms	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_term_relationships	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_term_taxonomy	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_usermeta	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_users	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_wc_admin_notes	 	Data: 0.06MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wc_admin_note_actions	 	Data: 0.05MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wc_category_lookup	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wc_customer_lookup	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_wc_download_log	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_wc_orders	 	Data: 0.02MB + Index: 0.11MB + Engine InnoDB
MG7Lj_wc_orders_meta	 	Data: 0.06MB + Index: 0.11MB + Engine InnoDB
MG7Lj_wc_order_addresses	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_wc_order_coupon_lookup	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_wc_order_operational_data	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_wc_order_product_lookup	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_wc_order_stats	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_wc_order_tax_lookup	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_wc_product_attributes_lookup	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wc_product_download_directories	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wc_product_meta_lookup	 	Data: 0.02MB + Index: 0.11MB + Engine InnoDB
MG7Lj_wc_rate_limits	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wc_reserved_stock	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wc_tax_rate_classes	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wc_webhooks	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_wpforms_logs	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wpforms_payments	 	Data: 0.02MB + Index: 0.14MB + Engine InnoDB
MG7Lj_wpforms_payment_meta	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_wpforms_tasks_meta	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wpmailsmtp_debug_events	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wpmailsmtp_tasks_meta	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
MG7Lj_wpr_above_the_fold	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_wpr_lazy_render_content	 	Data: 0.02MB + Index: 0.06MB + Engine InnoDB
MG7Lj_wpr_rocket_cache	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_wpr_rucss_used_css	 	Data: 0.02MB + Index: 0.09MB + Engine InnoDB
MG7Lj_yoast_indexable	 	Data: 0.02MB + Index: 0.09MB + Engine InnoDB
MG7Lj_yoast_indexable_hierarchy	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
MG7Lj_yoast_migrations	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
MG7Lj_yoast_primary_term	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
MG7Lj_yoast_seo_links	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
Post Type Counts
attachment	 	57
custom_css	 	1
elementor_library	 	5
elementor-hf	 	2
envato_tk_import	 	2
page	 	9
post	 	2
product	 	9
revision	 	3
shop_order	 	6
shop_order_placehold	 	26
wp_font_face	 	33
wp_font_family	 	12
wp_global_styles	 	1
wp_navigation	 	1
wp_template	 	3
wp_template_part	 	2
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (18)
[Elementor Pro](https://go.elementor.com/wp-dash-wp-plugins-author-uri/)	 	by Elementor.com – 3.24.3
[Elementor](https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash)	 	by Elementor.com – 3.24.5
Envato Elements	 	by Envato – 2.0.14
[Site Kit by Google](https://sitekit.withgoogle.com/)	 	by Google – 1.136.0
[Hide Page And Post Title](https://profiles.wordpress.org/arjunthakur#content-plugins/)	 	by Arjun Thakur – 1.5.8
[Imagify](https://wordpress.org/plugins/imagify/)	 	by Imagify – Optimize Images & Convert WebP & Avif – 2.2.2
[Jeg Elementor Kit](http://jegtheme.com/)	 	by Jegtheme – 2.6.9
JetSticky For Elementor	 	by Crocoblock – 1.0.4
[Post Type Switcher](https://wordpress.org/plugins/post-type-switcher/)	 	by Triple J Software, Inc. – 3.3.1
Template Kit Import	 	by Envato – 1.0.16
WooCommerce.com Update Manager	 	by Automattic – 1.0.3
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/)	 	by WooCommerce – 2.9.2
[WooCommerce](https://woocommerce.com/)	 	by Automattic – 9.3.3
[Yoast SEO](https://yoa.st/1uj)	 	by Team Yoast – 23.5
[WP Consent API](https://wordpress.org/plugins/wp-consent-api)	 	by RogierLankhorst – 1.0.7
[WP Mail SMTP](https://wpmailsmtp.com/)	 	by WP Mail SMTP – 4.1.1
[WP Rocket](https://wp-rocket.me/)	 	by WP Media – 3.17.0.2
[Social Chat](https://quadlayers.com/products/whatsapp-chat/)	 	by QuadLayers – 7.4.6
Inactive plugins (2)
[Elementor Header & Footer Builder](https://github.com/Nikschavan/header-footer-elementor)	 	by Brainstorm Force, Nikhil Chavan – 1.6.42
[Temporary Login](https://elementor.com/)	 	by Elementor.com – 1.2.0
Dropin Plugins ()
advanced-cache.php	 	advanced-cache.php
maintenance.php	 	maintenance.php
Settings
Legacy API enabled:		–
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		
Decimal separator		,
Number of decimals		0
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to WooCommerce.com:		
Enforce Approved Product Download Directories:		
HPOS enabled:		
Order datastore:		Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled:		–
Logging
Enabled		
Handler		Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period		30 days
Level threshold		–
Log directory size		1 MB
WooCommerce pages
[Shop base](https://jacohorsetours.com/wp-admin/post.php?post=129&action=edit):		#129 - /shop/
[Cart](https://jacohorsetours.com/wp-admin/post.php?post=130&action=edit):		 Page contains both the [woocommerce_cart] shortcode and the woocommerce/cart block.
[Checkout](https://jacohorsetours.com/wp-admin/post.php?post=131&action=edit):		#131 - /checkout/ -  Contains the woocommerce/checkout block
[My account](https://jacohorsetours.com/wp-admin/post.php?post=132&action=edit):		#132 - /my-account/
Terms and conditions:		 Page not set
Theme
Name:		Hello Elementor
Version:		3.1.1
Author URL:		https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child theme:		 – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: [How to create a child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/)
WooCommerce support:		
Templates
Overrides:	 	–
WooCommerce PayPal Payments
Onboarded		
Shop country code		CR
WooCommerce currency supported		
Advanced Card Processing available in country		–
Pay Later messaging available in country		–
Webhook status		–
PayPal Vault enabled		–
ACDC Vault enabled		–
Logging enabled		
Reference Transactions		–
Used PayPal Checkout plugin		–
Subscriptions Mode		Disabled
PayPal Shipping Callback		–
Apple Pay		–
Google Pay		–
Fastlane		–
Admin
Enabled Features:		activity-panels, analytics, product-block-editor, coupons, core-profiler, customize-store, customer-effort-score-tracks, import-products-task, experimental-fashion-sample-products, shipping-smart-defaults, shipping-setting-tour, homescreen, marketing, mobile-app-banner, navigation, onboarding, onboarding-tasks, pattern-toolkit-full-composability, product-custom-fields, remote-inbox-notifications, remote-free-extensions, payment-gateway-suggestions, printful, shipping-label-banner, subscriptions, store-alerts, transient-notices, woo-mobile-welcome, wc-pay-promotion, wc-pay-welcome-page, launch-your-store
Disabled Features:		experimental-blocks, minified-js, product-pre-publish-modal, settings, async-product-editor-category-field, product-editor-template-system, blueprint, reactify-classic-payments-settings
Daily Cron:		 Next scheduled: 2024-10-06 18:15:10 +00:00
Options:		
Notes:		82
Onboarding:		completed
Action Scheduler
Version:	3.8.1
Data store:	ActionScheduler_DBStore
Action Status	 	Count	Oldest Scheduled Date	Newest Scheduled Date
Complete	 	73	2024-10-05 23:30:06 +0000	2024-10-06 02:07:37 +0000
Failed	 	653	2024-03-08 22:21:08 +0000	2024-10-05 23:42:39 +0000
Pending	 	4	2024-10-06 23:30:06 +0000	2024-10-12 23:30:06 +0000

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by justdoitman00** [comment]
![Image](https://github.com/user-attachments/assets/ec794e6e-b6fe-41fd-878b-7427fc496e2f)

**Comment by SydeKrystian** [comment]
Hello @justdoitman00 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
