### ISSUE TITLE
Unable to complete payment via ''Debit or Credit Card’.

### ISSUE THREAD

**Issue by rabadam** [woocommerce/woocommerce-paypal-payments#2676]
### Describe the Bug
Customers unable to complete payment via ''Debit or Credit Card’.

![Image](https://github.com/user-attachments/assets/0d5acd0a-9eeb-4545-b974-cbc658af00cd)

### To Reproduce

1. Go to 'checkout'
2. Click on 'Debit or Credit Card'
3. Enter card number, exp, and CSC.
4. The billing address field get presented.
5. Click the pay button

### Expected Behavior

I should be able to complete the payment via ''Debit or Credit Card’ 

### Actual Behavior

After tapping the pay button the address field shows as invalid data even though after several attempts and reentry of the address (which is valid), I'm unable to complete the payment.

The workaround was to do the following:
1.From checkout tap ‘PayPal Checkout’ to get the pop-up.
2.Tap ‘Pay with Debit or Credit Card’
3.I’m not paying with PayPal but do enter my email and click ‘Continue to Payment’
4.Click ‘Continue as guest’ to get the ‘Pay with debit or credit card’ form.
5.Enter credit card info and confirm other fields are correct and click ‘Continue’ to be able to make payment.

### Environment

 - WordPress Version: version: 6.6.2
 - WooCommerce Version:version: 9.3.3
 - WooCommerce PayPal Payments: version: 2.9.2
-  
 - Browser [e.g. Chrome, Safari] and Version: Chrome on Mac Version 125.0.6422.61 (Official Build) (x86_64)
 
 - - Any other plugins installed:
 Akismet Anti-spam: Spam Protection: version: 5.3.3, author: Automattic - Anti-spam Team, Auto-updates enabled
Check Conflicts: version: 1.1.6, author: ioannup, Auto-updates disabled
Jetpack: version: 13.9, author: Automattic, Auto-updates enabled
Mailchimp for WooCommerce: version: 4.4.1, author: Mailchimp, Auto-updates enabled
Order Delivery Date for WooCommerce (Lite version): version: 3.22.0, author: Tyche Softwares, Auto-updates enabled
PDF Invoices & Packing Slips for WooCommerce: version: 3.8.8, author: WP Overnight, Auto-updates enabled
Printful Integration for WooCommerce: version: 2.2.10, author: Printful, Auto-updates enabled
reCAPTCHA for WooCommerce: version: 1.3.3, author: Elliot Sowersby, RelyWP, Auto-updates disabled
Shippo Shipping PRO for WooCommerce: version: 2.1.35, author: OneTeamSoftware, Auto-updates enabled
Smash Balloon Instagram Feed: version: 6.5.1, author: Smash Balloon, Auto-updates enabled
Strong Testimonials: version: 3.1.20, author: WPChill, Auto-updates enabled
TaxJar - Sales Tax Automation for WooCommerce: version: 4.2.3, author: TaxJar, Auto-updates enabled
Termly - GDPR/CCPA Cookie Consent Banner: version: 3.3.0, author: Termly - GDPR/CCPA Cookie Consent Banner, Auto-updates disabled
The MOJO Plugin: version: 3.2.2, author: Bluehost, Auto-updates enabled
WooCommerce: version: 9.3.3, author: Automattic, Auto-updates enabled
WooCommerce.com Update Manager: version: 1.0.3, author: Automattic, Auto-updates disabled
WooCommerce Legacy REST API: version: 1.0.4, author: WooCommerce, Auto-updates disabled
WooCommerce PayPal Payments: version: 2.9.2, author: WooCommerce, Auto-updates disabled
WooCommerce Product Add-Ons: version: 7.1.1, author: Woo, Auto-updates enabled
WooCommerce Shipping & Tax: version: 2.8.2, author: WooCommerce, Auto-updates enabled
WooCommerce Ship to Multiple Addresses: version: 4.0.7, author: WooCommerce, Auto-updates enabled
WooCommerce Smart Coupons: version: 8.6.0, author: StoreApps, Auto-updates enabled
Woo Min/Max Quantities: version: 5.0.1, author: Woo, Auto-updates enabled
WP Mail SMTP: version: 4.1.1, author: WP Mail SMTP, Auto-updates disabled
Yoast SEO: version: 23.6, author: Team Yoast, Auto-updates enabled

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WC Version: 9.3.3
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.18
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 260 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: 284_
Total Database Size: 63.05MB
Database Data Size: 52.53MB
Database Index Size: 10.52MB
284_woocommerce_sessions: Data: 2.85MB + Index: 0.01MB + Engine MyISAM
284_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_order_items: Data: 0.23MB + Index: 0.12MB + Engine MyISAM
284_woocommerce_order_itemmeta: Data: 3.56MB + Index: 1.27MB + Engine MyISAM
284_woocommerce_tax_rates: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
284_woocommerce_tax_rate_locations: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
284_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
284_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_actionscheduler_actions: Data: 0.85MB + Index: 0.42MB + Engine MyISAM
284_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_actionscheduler_logs: Data: 1.51MB + Index: 0.46MB + Engine MyISAM
284_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
284_comments: Data: 0.38MB + Index: 0.19MB + Engine MyISAM
284_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
284_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_mailchimp_carts: Data: 0.41MB + Index: 0.01MB + Engine MyISAM
284_mailchimp_jobs: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
284_nfd_data_event_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
284_nm_personalized: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_options: Data: 17.65MB + Index: 0.50MB + Engine MyISAM
284_postmeta: Data: 17.42MB + Index: 5.02MB + Engine MyISAM
284_posts: Data: 2.14MB + Index: 0.50MB + Engine MyISAM
284_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_sbi_feed_caches: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
284_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_sbi_instagram_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
284_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_strong_views: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
284_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_term_relationships: Data: 0.04MB + Index: 0.10MB + Engine MyISAM
284_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_usermeta: Data: 0.62MB + Index: 0.28MB + Engine MyISAM
284_users: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
284_wcpdf_invoice_number: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
284_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
284_wc_admin_notes: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
284_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
284_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_wc_customer_lookup: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
284_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
284_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
284_wc_order_coupon_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
284_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_wc_order_product_lookup: Data: 0.16MB + Index: 0.15MB + Engine MyISAM
284_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
284_wc_order_tax_lookup: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
284_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_wc_product_meta_lookup: Data: 0.08MB + Index: 0.11MB + Engine MyISAM
284_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
284_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_gc_activity: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_woocommerce_gc_cards: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
284_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
284_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
284_wpmailsmtp_debug_events: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
284_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
284_yoast_indexable: Data: 0.29MB + Index: 0.07MB + Engine MyISAM
284_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.15MB + Engine MyISAM
284_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
284_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
284_yoast_seo_links: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
284_yoast_seo_meta: Data: 0.14MB + Index: 0.14MB + Engine MyISAM

### Post Type Counts ###

attachment: 1677
custom_css: 2
customize_changeset: 5
envira: 1
et_pb_layout: 21
global_product_addon: 7
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mep_events: 1
nav_menu_item: 35
oembed_cache: 3
order_shipment: 84
page: 21
post: 2
product: 336
product_variation: 859
revision: 70
shop_coupon: 96
shop_order: 1009
shop_order_refund: 22
sumo_wcpo_cron_jobs: 27
sumo_wcpo_masterlog: 141
sumo_wcpo_preorders: 26
wcccf: 3
wccpf: 1
wp_global_styles: 1
wp_navigation: 1
wpm-testimonial: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Check Conflicts: by ioannup – 1.1.6
Smash Balloon Instagram Feed: by Smash Balloon – 6.5.1
Jetpack: by Automattic – 13.9
Mailchimp for WooCommerce: by Mailchimp – 4.4.1
The MOJO Plugin: by Bluehost – 3.2.2
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.22.0
Printful Integration for WooCommerce: by Printful – 2.2.10
reCAPTCHA for WooCommerce: by Elliot Sowersby
RelyWP – 1.3.3

Strong Testimonials: by WPChill – 3.1.20
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 4.2.3
Termly - GDPR/CCPA Cookie Consent Banner: by Termly - GDPR/CCPA Cookie Consent Banner – 3.3.0
Shippo Shipping PRO for WooCommerce: by OneTeamSoftware – 2.1.35
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
Woo Min/Max Quantities: by Woo – 5.0.1
WooCommerce PayPal Payments: by WooCommerce – 2.9.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.8.8
WooCommerce Product Add-Ons: by Woo – 7.1.1
WooCommerce Shipping & Tax: by WooCommerce – 2.8.2
WooCommerce Ship to Multiple Addresses: by WooCommerce – 4.0.7
WooCommerce Smart Coupons: by StoreApps – 8.6.0
WooCommerce: by Automattic – 9.3.3
Yoast SEO: by Team Yoast – 23.6
WP Mail SMTP: by WP Mail SMTP – 4.1.1

### Inactive Plugins (1) ###

SUMO Pre-Orders: by Fantastic Plugins – 3.8

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.2.1
SSO: by Garth Mortensen
Mike Hansen – 0.4

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 8 MB

### WC Pages ###

Shop base: #48184 - /shop/
Cart: #5368 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #5369 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #5370 - /my-account/
Terms and conditions: #5392 - /terms-of-use/

### Theme ###

Name: Divi
Version: 4.27.1
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-10-09 05:25:51 -07:00
Options: ✔
Notes: 208
Onboarding: completed

### Action Scheduler ###

Complete: 436
Oldest: 2024-10-03 14:29:34 -0700
Newest: 2024-10-08 14:05:04 -0700

Failed: 318
Oldest: 2019-10-31 14:20:26 -0700
Newest: 2024-10-08 13:44:37 -0700

Pending: 6
Oldest: 2024-10-08 14:25:04 -0700
Newest: 2024-11-06 11:55:49 -0800

### Smart Coupons related settings ###

Number of coupons to show: 5
Number of characters in auto-generated coupon code: 
Valid order status for auto-generating coupon: processing
completed

Include tax in the amount of the generated gift card: 
Deduct credit/gift before doing tax calculations: no
Gift Card discount is inclusive of tax: no
Automatic deletion: no
Coupon emails: yes
Printing coupons: yes
Sell gift cards at less price?: no
Use gift card applied in first subscription order for subsequent renewals until credit reaches zero: yes
Renewal orders should not generate coupons even when they include a product that issues coupons: no
Allow sending of coupons to others: yes
Allow schedule sending of coupons?: 
Combine emails: 
Auto generated coupon email: yes
Combined auto generated coupons email: no
Acknowledgement email: yes
Enable taxes: yes
Prices entered with tax: no
Rounding: no
Display prices in the shop: excl
Display prices during cart and checkout: excl
Display tax totals: single
Enable the use of coupon codes: yes
Calculate coupon discounts sequentially: no
Account endpoints > Coupons: wc-smart-coupons

### Status report information ###

Generated at: 2024-10-08 14:18:22 -07:00
`

</details>

**Comment by rabadam** [comment]
2.9.2 Is problematic. Had to rolllback to 2.9.0 and seems better. Would be nice to know if 2.9.3 will fix this issue.

**Comment by SydeKrystian** [comment]
Hello @rabadam 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
