### ISSUE TITLE
Cant enable "Save PayPal & Venmo payment methods"

### ISSUE THREAD

**Issue by Pierre808** [woocommerce/woocommerce-paypal-payments#2679]
### Describe the Bug
I connected my PayPal account, and it says status: connected. Now I want to enable "Save PayPal & Venmo payment methods", so I click on the enable button, log in to the PayPal, and the PayPal site tells me that everything worked fine. However when I go back to the plugin settings it still says that Status: Not yet enabled  

### To Reproduce

1. Go to 'WooCommerce->Settings->Payments->PayPal->Connection->Enable Saving PayPal & Venmo'
2. Log in to PayPal

### Expected Behavior

The setting should be enabled after connecting.

### Actual Behavior

It still says that Save PayPal & Venmo is not enabled.

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.3
 - Plugin Version: 2.9.2
 - Browser [e.g. Chrome, Safari] and Version: Firefox and Chrome

**Comment by SydeKrystian** [comment]
Hello @Pierre808 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
