### ISSUE TITLE
Not showing "Debit/Credit card" option on checkout

### ISSUE THREAD

**Issue by AlbertoDry** [woocommerce/woocommerce-paypal-payments#2683]
### Describe the Bug

Since 1 October our website is not showing Debit/Credit card option at checkout with PayPal plugin. Everything has been uchanged since we installed it and it worked properly until 1 October when the bug popped up. Our customer don't see "debit/credit card" option at checkout and this cause a loss in sales.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @AlbertoDry 

Please install this version of our plugin on your live site, as it should resolve the problem with Advanced Card Processing:
[https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.3-rc2
](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.3-rc2
)
Let us know if the problem persist. 

Kind regards,
Krystian
