### ISSUE TITLE
Payment options doesn't work unless I active Express Payment

### ISSUE THREAD

**Issue by jesuscruz13** [woocommerce/woocommerce-paypal-payments#2684]
### Describe the Bug

Hi. This plugin doesn't show me any option to pay, unless I active "Express Payment", which I don't wanna activate.

Just show me the message error: "There is no payment method available. This may be our mistake. Please contact us if you need help placing your order."

I need to deliver a new development urgently, where just use Paypal as payment method.

![Image](https://github.com/user-attachments/assets/92564908-c5c7-4e82-a31b-5331f1928bba)
![Image](https://github.com/user-attachments/assets/eda7d055-bf77-4cd1-8e29-f9b8a529ff52)

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.3
 - Plugin Version: 2.9.2
 - Browser [e.g. Chrome, Safari] and Version:  Chrome version 129.0.6668.90 and Edge Versión 129.0.2792.79
 - Any other plugins installed: 
    All-in-One WP Migration 7.86
    All-in-One WP Migration Google Drive Extension 2.90
    Antispam Bee 2.11.6
    Astra Pro  4.8.1
    Autocomplete WooCommerce Orders 3.3.5
    Change WordPress Login Logo  1.3 
    Code Snippets 3.6.5.1
    Easy Updates Manager 9.0.18
    Elemailer Lite 2.3
    Elementor 3.24.4
    Elementor Pro 3.24.2
    Essential Addons for Elementor 6.0.5
    Essential Addons for Elementor - Pro 5.8.5
    Fuentes personalizadas 2.1.6
    Happy Elementor Addons 3.12.3
    Hide Shipping Method For WooCommerce  1.5.0
    JetEngine 3.5.6
    JetSmartFilters 3.5.6
    Safe SVG 2.2.6
    Weglot Translate 4.2.8
    WP Mail SMTP 4.1.1
    Yoast Duplicate Post 4.5

**Comment by SydeKrystian** [comment]
Hello @jesuscruz13 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
