### ISSUE TITLE
I don't know if this issue was already sent in but just in case

### ISSUE THREAD

**Issue by sadeekeM** [woocommerce/woocommerce-paypal-payments#269]
**Screenshots**
![Checkout_ Cash-out through the renozan checkout page - Renozan — Mozilla Firefox 9_15_2021 7_47_30 AM](https://user-images.githubusercontent.com/82333846/133909434-c121465e-4609-4278-a96d-31ccdf51bfb4.png)

My log is saying: "unknown error while connecting to PayPal". I already reached out to PayPal and discussed this, I was then sent to woocommerce and the woocommerce agent I got through to said the developers are already aware of this issue and a new update for PayPal Payments Plugin is coming out soon, then he/she sent me here. I want to make sure you're aware of this specific issue before the update drops because if you're not; who know when it will be fixed. I HOPE YOU SEE THIS!

**Comment by Dinamiko** [comment]
Hello @sadeekeM,

Sorry for the delay in the response, does this issue still persist? if so please let us know here the steps to reproduce it, thanks.

**Comment by InpsydeNiklas** [comment]
For eventual support questions, please file a request from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
