### ISSUE TITLE
Paypal doesnt recognise different currency from currency switcher

### ISSUE THREAD

**Issue by ElecDveEng** [woocommerce/woocommerce-paypal-payments#2694]
### Describe the Bug

Paypal fails if you use a different currency from currency switcher. 
https://wordpress.org/support/topic/cannot-mix-currencies/

YITH Support Team (YITH Support Team) 
Oct 11, 2024, 08:13 GMT+2 
Hello Tully,
thank you for contacting us.
 
Which plugin do you use for Paypal payment? Some of our customers reported that "PayPal for WooCommerce" plugin caused a conflict in the latest release, making a downgrade they fixed the issue.
 
In that case, I invite you open a support request to developers asking for a feedback.
 
If you need additional support by our side, please send in the next reply the url of the site, WordPress and FTP access credentials.
 
Thanks for your time.
 
Best regards,
Alessio Torrisi.
________________________________________
Don't miss the latest updates from YITH. Follow us on [Facebook](https://www.facebook.com/YITHplugins), [Twitter](https://twitter.com/yithemes), and our YouTube channels [EN](https://www.youtube.com/channel/UCnIkaEMbBh1-OFP6Douqxmw) / [ES](https://www.youtube.com/channel/UC4FDGcf086GjP4_xI9CJAlg) / [IT](https://www.youtube.com/channel/UC5VAKhYBDurdAXw7ICb68xA).
Thank you!

 
Tully Woodland 
Oct 10, 2024, 22:46 GMT+2 
I keep getting failed payments using Paypal when they choose an different currency. If I can't resolve this I will need to remove the multicurrency switcher as it does not work right now.

**Comment by SydeKrystian** [comment]
Hello @ElecDveEng 

Thank you for bringing this to our attention. We are aware of this problem, and already patched t. 

You can also download the fixed version of the plugin from this link:
https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.3-rc2

Please give it a try and let us know if you need further assistance.

Kind Regards,
Krystian
