### ISSUE TITLE
Unable to Hide Pay Later Messaging

### ISSUE THREAD

**Issue by s4tnav** [woocommerce/woocommerce-paypal-payments#2695]
The toggle buttons to hide the Pay Later Messaging don't save & revert to default upon clicking on "Save Changes" button.

page : wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-pay-later

**Comment by SydeKrystian** [comment]
Hello @s4tnav 


If the current Pay Later configurator isn’t performing as expected, there is a workaround for this situation. You can restore the legacy Pay Later configurator, and with this option enabled, it should work correctly. You can enable it by using the following filter:

`add_filter('woocommerce_paypal_payments_checkout_messages_renderer_hook', function () {
	return 'ppcp_start_button_wrapper_ppcp_gateway';
});`

To insert this filter, you can use the Code Snippets plugin. Let us know what the outcome is after that. 

If the issue persists after performing these steps, we suggest you contact us directly for further assistance. We may need to examine your system report or logs to better understand what’s happening. You can open a ticket with our service desk. Here’s how you can request support: [Request Support](https://paypal.inpsyde.com/docs/request-support/). Please make sure to include the URL of this thread in your ticket for reference.

Kind Regards,
Krystian
