### ISSUE TITLE
Failed to process the payment - The specified resource does not exist.

### ISSUE THREAD

**Issue by scrumpmeister** [woocommerce/woocommerce-paypal-payments#2706]
Receiving an error when customers try to pay with WooCommerce PayPal plugin.

The following error is shown in the Order:
Failed to process the payment. Please try again or contact the shop admin. [RESOURCE_NOT_FOUND] The specified resource does not exist. https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_RESOURCE_ID PayPalGateway.php:685 INVALID_RESOURCE_ID Specified resource ID does not exist. Please check the resource ID and try again.
OrderEndpoint.php:584 Order status changed from Pending payment to Failed.

Server logs show the following error:
Message
PHP Warning:  Undefined array key "path" in /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-utils.php on line 1279
Timestamp: 2024-10-14T01:31:33.000Z
Kind: plugins
Name :woocommerce-payments
File: /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-utils.php
Line 1279 and 1303

Lasted version (Version 2.9.3 ) of the plugin in use as managed by Wordpress on auto-update.

**Comment by scrumpmeister** [comment]
Unsure if this is  related - https://www.paypal-community.com/t5/Sandbox-Environment/Assistance-Needed-RESOURCE-NOT-FOUND-Error-in-PayPal-Integration/td-p/3126228 but I have no control over it as it's a managed plugin.  I've checked connections as far as the plugins allow and they are working.

**Comment by SydeKrystian** [comment]
Hello @scrumpmeister 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
