### ISSUE TITLE
An error occurred while attempting to create the refund using the payment gateway API.

### ISSUE THREAD

**Issue by nautilus-studio** [woocommerce/woocommerce-paypal-payments#2707]
### Describe the Bug

When attempting to perform a refund with the **Refund with Paypal** button, I get this error: "An error occurred while attempting to create the refund using the payment gateway API."

I have already ensured that my system is correctly receiving and processing webhooks from PayPal by going to the Webhooks Status section within the Connection Tab of your PayPal Payments plugin dashboard, clicking on “Resubscribe” to refresh my subscription to the webhooks, and clicking  “Simulate” to test the correct reception of webhooks by my system. The webhook was received successfully.

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.9.3
 - WooCommerce PayPal Payments Plugin Version: 2.9.3
 - Browser and Version: Google Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by maxlaf** [comment]
I have not tried to reproduce this, but I've started seeing cases in support. It may be worth rolling back to 2.9.2 to see if that resolves it.
8895883-zen

**Comment by SydeKrystian** [comment]
Hello @nautilus-studio 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
