### ISSUE TITLE
Issue with Paypal payment after new update

### ISSUE THREAD

**Issue by rootlabaunz** [woocommerce/woocommerce-paypal-payments#2709]
When customers want to pay via PayPal in checkout, they get redirected to PayPal to sign in. Once they complete the sign-in process and get redirected back to our website, it keeps loading and never confirms the order. During this time, it takes authorisation from PayPal.

When I tried to recreate the issue through my personal PayPal, it worked, so I was unable to replicate this issue. I tried it on Firefox and chrome.

However, 3 customers have notified me about this issue. I can see our sales have dropped in the last 2-3 days. 

The expected behaviour is for customers to be redirected to the merchant website after logging in, taken to the thank you page, and allocated an order number.

All plugins are in their latest version, and customers have this issue on mobile and desktop.

**Comment by SydeKrystian** [comment]
Hello @rootlabaunz 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
