### ISSUE TITLE
Missing support for Apple Pay refunds (3823)

### ISSUE THREAD

**Issue by dawidchyrzynski** [woocommerce/woocommerce-paypal-payments#2715]
### Describe the Bug

When Apple Pay is set up as a separate payment gateway, orders can only be refunded manually. The `process_refund` method appears to be implemented in the `ApplePayGateway` class, but the `supports` property does not include the `refunds` option.

### To Reproduce

1. Install the plugin
2. Enable `Apple Pay (via PayPal)` payment gateway

### Screenshots

![Image](https://github.com/user-attachments/assets/f8ecea65-8745-417f-a25e-ec283c0722bc)
![Image](https://github.com/user-attachments/assets/30a23257-8e1d-44c3-b0d8-d4dc06770b6e)

### Expected Behavior

The `Refund XXX via PayPal` option should be available for orders paid via Apple Pay.

### Actual Behavior

Only manual refund is available.

### Environment

 - WordPress Version: 6.0.3
 - WooCommerce Version: 6.9.4
 - Plugin Version: 2.9.0

**Comment by SydeKrystian** [comment]
Hello @dawidchyrzynski 

Thank you for bringing this to our attention.  

We’re aware of this issue. We’ve created an issue for it and are working on a fix, which will be available soon.  

Kind Regards,  
Krystian
