### ISSUE TITLE
login to paypal payment not completing

### ISSUE THREAD

**Issue by guruvishnu** [woocommerce/woocommerce-paypal-payments#2716]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by guruvishnu** [comment]
![Image](https://github.com/user-attachments/assets/4b2c996f-536f-4c5d-a8ce-01d84650e9fe)

**Comment by SydeKrystian** [comment]
Hello @guruvishnu 

Thank you for your message.

To complete a payment, you need to use a different PayPal account from the one used to onboard the PayPal Payments plugin. The account used for onboarding is meant for the seller, while the buyer needs to use a separate account.

Kind Regards,  
Krystian
