### ISSUE TITLE
payment checkout dosen´t work

### ISSUE THREAD

**Issue by ManufakturFLADE** [woocommerce/woocommerce-paypal-payments#2724]
### To Reproduce

1. Go to 'shopping cart'
2. Click on 'continue to checkout'
3. Choose Paypal
4. Click the button Paypal or credit card
5. I am redirected to PayPal
6. I enter my PayPal details
7. I click on complete purchase
8. sometimes things don't go any further here -
9. sometimes it goes back to the online shop and then it doesn't go any further. I can't do anything because all I see is the waiting queue. The purchase is not completed.

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.3.3
 - Plugin Version 9.3.3
 - Browser [e.g. Chrome, Safari] and Version : safari, Chrome, firefox
 - Any other plugins installed:
B2B Market 2.1.4 , Contact Form 7 4.3.10, Cookiebot Usercentrics 4.3.10, Export Users to CSV 1.11, 
German Market 3.40.1, GTM4WP 1.20.2, Jetpack 13.9.1, Language Fallback 2.0.0, Loco Translate 2.6.11,
Popup Maker 1.20.2, Print Invoice and Delivery Notes 1.2.2, Statify 1.8.4, WooCommer Extendet Coupon Featues Free 3.3.3;
WooCommer Google Product Feed 11.0.14, WooCommerce Lagacy Rest API 1.0.4

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by sgoerger** [comment]
I believe I'm seeing a similar issue - checkout is just hanging.

**Comment by ManufakturFLADE** [comment]
So do you think this is not a problem with the plugin? I don't think so. The problem only exists when paying with Paypal. All orders I receive with payment by bank transfer have no hanging at checkout.

 

Von: sgoerger ***@***.***> 
Gesendet: Dienstag, 22. Oktober 2024 19:04
An: woocommerce/woocommerce-paypal-payments ***@***.***>
Cc: ManufakturFLADE ***@***.***>; Author ***@***.***>
Betreff: Re: [woocommerce/woocommerce-paypal-payments] payment checkout dosen´t work (Issue #2724)

 

I believe I'm seeing a similar issue - checkout is just hanging.

**Comment by SydeKrystian** [comment]
Hello @ManufakturFLADE 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
