### ISSUE TITLE
Plugin causes the "Sold Individually" Checkbox in woo product editor to enable itself on save

### ISSUE THREAD

**Issue by homegrownhrbs** [woocommerce/woocommerce-paypal-payments#2727]
### Describe the Bug

When Woocommerce-paypal-payments plugin is enabled, the "Sold Individually" Checkbox in the product editor automatically checks to the "true" state when saving any product. Disabling the plugin fixes the issue. 
<input type="checkbox" name="_sold_individually" id="_sold_individually" value="yes" class="checkbox">

### To Reproduce

1. Open any woocommerce product in the backend product editor /wp-admin/post.php?post=####&action=edit
2. Change anything  
3. Save
4. Notice that on refresh the Sold Individually Checkbox is now checked.

### Additional Details
This bug has popped up in the past and was fixed, but it seems to be back. 
https://wordpress.org/support/topic/sold-individually-meta-key-reverts-to-no-by-itself/

https://wordpress.org/support/topic/cant-disable-sold-individually/

</details>

**Comment by homegrownhrbs** [comment]
Further review and reading issue [2462](https://github.com/woocommerce/woocommerce-paypal-payments/issues/2462) made me realize that this bug may be caused by a combination of the woocommerce paypal payments plugin alongside "[Woo All Products For Subscriptions](https://woocommerce.com/products/all-products-for-woocommerce-subscriptions/)" 

My theory is that the "Woo All Products For Subscriptions" Plugin which allows all product types to be considered subscriptions and then " Woocommerce Paypal Payments" plugin will force "sold individually" for all product storewide.

**Comment by SydeKrystian** [comment]
Helo @homegrownhrbs 

The issue you're experiencing is not a bug. When a product is linked to a subscription plan, PayPal’s SDK restricts the ability to add multiple items of this product to the cart. This limitation ensures compatibility with the subscription billing process, which typically only allows one subscription product per transaction. As a result, the "Sold Individually" option is automatically selected, and this behavior cannot be changed.

This is a known limitation when using PayPal Subscriptions, as opposed to PayPal Vaulting, which provides more flexibility for handling multiple items. Unfortunately, from a development perspective, there isn't much that can be done to modify this behavior.

If you need further assistance or have additional questions, feel free to reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

Kind Regards,  
Krystian
