### ISSUE TITLE
Error importe cobrado

### ISSUE THREAD

**Issue by Odalysch** [woocommerce/woocommerce-paypal-payments#2729]
### Screenshots

![Image](https://github.com/user-attachments/assets/fbc01743-5d0a-4b53-88b4-4aeb6544b77b)

### Environment

 - WordPress Version  6.6.2
 - WooCommerce Version 9.3.3
 - Plugin Version 2.9.3 WooCommerce PayPal Payments
 - Browser  Chrome

**Comment by SydeKrystian** [comment]
Hello @Odalysch 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
