### ISSUE TITLE
Checkout does not display credit card payment option

### ISSUE THREAD

**Issue by kruppster23** [woocommerce/woocommerce-paypal-payments#2730]
### Describe the Bug

Suddenly Credit Card does not show in the checkout, only pay by paypal.  No changes were made.  The plugin WooCommerce PayPal Payments was updated to version Version 2.9.3

Using standard WooCommerce Checkout

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version: Version 2.9.3
 - WooCommerce Version:  9.3.3
 - Plugin Version 2.9.3
 - Browser [e.g. Chrome, Safari] and Version - Microsoft Edge, Google Chrome and Safari
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @kruppster23 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
