### ISSUE TITLE
Optional Field is Required - very confussing

### ISSUE THREAD

**Issue by classiccopperbracelets** [woocommerce/woocommerce-paypal-payments#2749]
### Describe the Bug

Hi, I'm not technical but

When filling out your address details their is a Field ( Flat No. " it says it is optional but it is required to complete sale - Very confusing, how many sales have I lost

### To Reproduce

1. Go to' Checkout'
2. Uncheck the 'Use same address for billing' box
3. The Field ' Field, suit etc.' says it is optional - but if you don't put information in this field the transaction fails.
4. ' There was a problem with the provided billing address: Flat, suite, unit, etc. is required '

- Don't know how to attach a screenshot

- ![Image](https://github.com/user-attachments/assets/00c4d8b6-6695-467f-9737-721e9939b4bf)

### Environment

 
 - WooCommerce Version
 - Plugin Version

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @classiccopperbracelets 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
