### ISSUE TITLE
Webhooks Issue: Multiple Websites Using Same Merchant Account

### ISSUE THREAD

**Issue by jivemedia** [woocommerce/woocommerce-paypal-payments#2751]
Hello,

I have a client running multiple websites using the same PayPal merchant account.

When I resubscribe webhooks on one site, the URL is updated on that site, but when checking the other site, the webhook URL is that of the other site.

Both sites are running off the same IP address and web server.

Is this normal behaviour? Is there a way to correct this so each site has its own webhook URL set?

Both sites are running WooCommerce 9.3.3 and WooCommerce PayPal Payments 2.9.0.

Thanks.

**Comment by SydeKrystian** [comment]
Hello @jivemedia 

Using the same PayPal merchant account on multiple sites is generally supported and should not cause issues, though each site should ideally have a unique invoice ID setup to avoid any conflicts. However, PayPal only allows a single webhook URL per account, so when you resubscribe webhooks on one site, it overrides the URL for the other site, but that's shouldnt trigger any problems. 

If you encounter any irregularities, please let us know, and we can review the logs. For further assistance, you can also reach out to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Kind Regards,

Krystian
