### ISSUE TITLE
PHP Fatal Error in error log from plugin

### ISSUE THREAD

**Issue by AinsleyJ127** [woocommerce/woocommerce-paypal-payments#2759]
### Describe the Bug

PHP Fatal Error in error log from plugin

### Error Log Results
[04-Nov-2024 17:11:46 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /home/mbraasch81/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-axo/src/AxoModule.php:274
Stack trace:
#0 /home/mbraasch81/public_html/wp-includes/class-wp-hook.php(324): WooCommerce\PayPalCommerce\Axo\AxoModule->WooCommerce\PayPalCommerce\Axo\{closure}()
#1 /home/mbraasch81/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /home/mbraasch81/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /home/mbraasch81/public_html/wp-includes/template-loader.php(13): do_action()
#4 /home/mbraasch81/public_html/wp-blog-header.php(19): require_once('/home/mbraasch8...')
#5 /home/mbraasch81/public_html/index.php(17): require('/home/mbraasch8...')
#6 {main}
  thrown in /home/mbraasch81/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-axo/src/AxoModule.php on line 274

### Environment
version: 6.6.2
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 3013
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/mbraasch81/public_html
wordpress_size: 2.03 GB (2183529501 bytes)
uploads_path: /home/mbraasch81/public_html/wp-content/uploads
uploads_size: 1.70 GB (1828911998 bytes)
themes_path: /home/mbraasch81/public_html/wp-content/themes
themes_size: 27.93 MB (29290698 bytes)
plugins_path: /home/mbraasch81/public_html/wp-content/plugins
plugins_size: 231.41 MB (242646494 bytes)
fonts_path: /home/mbraasch81/public_html/wp-content/uploads/fonts
fonts_size: 1.89 MB (1982368 bytes)
database_size: 103.12 MB (108131657 bytes)
total_size: 4.09 GB (4394492716 bytes)

### wp-active-theme ###

name: Porto Child (porto-child)
version: 1.1
author: P-THEMES
author_website: https://www.portotheme.com/
parent_theme: Porto (porto)
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, title-tag, editor-style, automatic-feed-links, woocommerce, wc-product-gallery-lightbox, menus, post-formats, html5, wp-block-styles, responsive-embeds, align-wide, editor-styles, editor-color-palette, widgets
theme_path: /home/mbraasch81/public_html/wp-content/themes/porto-child

### wp-parent-theme ###

name: Porto (porto)
version: 7.2.8
author: P-THEMES
author_website: https://www.portotheme.com/
theme_path: /home/mbraasch81/public_html/wp-content/themes/porto

### wp-themes-inactive (3) ###

the7dtchild: version: 1.0.0, author: Dream-Theme
The7: version: 11.11.2, author: Dream-Theme
Twenty Twenty-Four: version: 1.2, author: the WordPress team

### wp-mu-plugins (1) ###

WordPress automation by Installatron: author: (undefined), version: (undefined)

### wp-plugins-active (40) ###

Auto Coupons for WooCommerce: version: 3.0.19, author: RLDD
Checkout Field Editor for WooCommerce: version: 2.0.4, author: ThemeHigh
Classic Editor: version: 1.6.5, author: WordPress Contributors
Classic Widgets: version: 0.3, author: WordPress Contributors
Contact Form 7: version: 6.0, author: Takayuki Miyoshi
Duplicate Page: version: 4.5.4, author: mndpsingh287
Duplicator Pro: version: 4.5.19.2, author: Duplicator
Elementor: version: 3.25.4, author: Elementor.com
Email Address Encoder: version: 1.0.24, author: Till Krüss
Facebook for WooCommerce: version: 3.2.10, author: Facebook
Flamingo: version: 2.5, author: Takayuki Miyoshi
Icegram Express - Email Subscribers, Newsletters and Marketing Automation Plugin: version: 5.7.39, author: Icegram
Loco Translate: version: 2.6.11, author: Tim Whitlock
Menu Icons: version: 0.13.15, author: ThemeIsle
PHP Compatibility Checker: version: 1.6.3, author: WP Engine
Porto Theme - Functionality: version: 3.2.8, author: P-Themes
Really Simple CAPTCHA: version: 2.3, author: Takayuki Miyoshi
Site Kit by Google: version: 1.138.0, author: Google
Slider Revolution: version: 6.6.20, author: ThemePunch
Smash Balloon Custom Facebook Feed: version: 4.2.5, author: Smash Balloon
Smash Balloon Instagram Feed: version: 6.6.0, author: Smash Balloon
Smush: version: 3.16.6, author: WPMU DEV
WooCommerce: version: 9.3.3, author: Automattic
WooCommerce.com Update Manager: version: 1.0.3, author: Automattic
WooCommerce Advanced Free Shipping: version: 1.1.7, author: Jeroen Sormani
WooCommerce Advanced Product Labels: version: 1.2.7, author: BeRocket
WooCommerce Advanced Shipping Packages: version: 1.1.5, author: Jeroen Sormani
WooCommerce Category Banner: version: 1.1.2, author: WP BackOffice
WooCommerce FedEx Shipping Plugin with Print Label: version: 7.1.2, author: PluginHive
WooCommerce PayPal Payments: version: 2.9.12-fastlane-limited-release, author: WooCommerce
WooCommerce Product Add-Ons: version: 7.1.2, author: Woo
Wordfence Security: version: 7.11.7, author: Wordfence
WP Mail SMTP: version: 4.1.1, author: WP Mail SMTP
WP Store Locator: version: 2.2.241, author: Tijmen Smit
YITH WooCommerce Ajax Product Filter: version: 5.5.0, author: YITH
YITH WooCommerce Ajax Search: version: 2.8.1, author: YITH
YITH WooCommerce Brands Add-On: version: 2.28.0, author: YITH
YITH WooCommerce Compare: version: 2.43.0, author: YITH
YITH WooCommerce Wishlist: version: 4.0.1, author: YITH
Yoast SEO: version: 23.7, author: Team Yoast

### wp-plugins-inactive (14) ###

Alpus AI Product Review Summary Addon: version: 2.2.0, author: AlpusTheme
Alpus Elementor FlexBox Addon: version: 1.1.0, author: AlpusTheme
Async JavaScript: version: 2.21.08.31, author: Frank Goossens (futtta)
Booster for WooCommerce: version: 7.2.3, author: Pluggabl LLC
DOOFINDER Search and Discovery for WP & WooCommerce: version: 2.5.13, author: Doofinder
Facebook Chat Plugin - Live Chat Plugin for WordPress: version: 2.5, author: Meta
FedEx WooCommerce Extension (BASIC): version: 2.1.2, author: XAdapter
Limit Login Attempts Reloaded: version: 2.26.14, author: Limit Login Attempts Reloaded
VarkTech Pricing Deals for WooCommerce: version: 2.0.2.02, author: Vark
WooCommerce Wholesale Lead Capture: version: 1.11, author: Rymera Web Co
WooCommerce Wholesale Order Form: version: 1.11, author: Rymera Web Co
WooCommerce Wholesale Prices: version: 2.2.1, author: Rymera Web Co
WooCommerce Wholesale Prices Premium: version: 1.17, author: Rymera Web Co
WP Rollback: version: 2.0.7, author: WP Rollback

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 512M
upload_max_filesize: 512M
max_effective_size: 512 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 4.18.0-553.5.1.lve.1.el8.x86_64 x86_64
httpd_software: Apache
php_version: 8.3.11 64bit
php_sapi: litespeed
max_input_variables: 8000
time_limit: 800
memory_limit: 512M
max_input_time: 800
upload_max_filesize: 512M
php_post_max_size: 512M
curl_version: 7.87.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false
current: 2024-11-04T17:15:10+00:00
utc-time: Monday, 04-Nov-24 17:15:10 UTC
server-time: 2024-11-04T12:15:03-05:00

### wp-database ###

extension: mysqli
server_version: 10.6.19-MariaDB-cll-lve
client_version: mysqlnd 8.3.11
max_allowed_packet: 268435456
max_connections: 1000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/mbraasch81/public_html/wp-content
WP_PLUGIN_DIR: /home/mbraasch81/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: writable
mu-plugins: writable

### google-site-kit ###

version: 1.138.0
php_version: 8.3.11
wp_version: 6.6.2
reference_url: https://www.trzmotorsports.com
amp_mode: no
site_status: not-connected
user_status: not authenticated
verification_status: verified-file
connected_user_count: 1
active_modules: site-verification, search-console, analytics-4, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ⭕
	googlesitekit_view_dashboard: ⭕
	googlesitekit_manage_options: ⭕
	googlesitekit_update_plugins: ⭕
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ⭕
	googlesitekit_view_wp_dashboard_widget: ⭕
	googlesitekit_view_admin_bar_menu: ⭕
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ⭕
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ⭕
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ⭕
	googlesitekit_delegate_module_sharing_management::["search-console"]: ⭕
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ⭕
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsPax: ⭕
	audienceSegmentation: ⭕
	conversionReporting: ⭕
	gm3Components: ⭕
	privacySandboxModule: ⭕
	rrmModule: ⭕
	signInWithGoogleModule: ⭕
active_conversion_event_providers: 
	contact-form-7: contact
	woocommerce: add_to_cart, purchase
consent_mode: disabled
consent_api: not-detected
search-console_shared_roles: none
search-console_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: https://www.trzmotorsports.com/
analytics_4_account_id: 1116•••••
analytics_4_property_id: 3761592••
analytics_4_web_data_stream_id: 5213••••••
analytics_4_measurement_id: G-82••••••••
analytics_4_use_snippet: yes
analytics_4_ads_conversion_id: none
analytics_4_available_custom_dimensions: none
analytics_4_ads_linked: false
analytics_4_ads_linked_last_synced_at: 1727147426

### wp_mail_smtp ###

version: 4.1.1
license_key_type: lite
debug: No debug notices found.
lite_install_date: Sep 28, 2023 @ 10:49am

`

**Comment by SydeKrystian** [comment]
Hello @AinsleyJ127 

Please let us know if the problem persists after updating to the latest release candidate version, which you can find [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.4-rc1).

Your feedback is important for us to identify and resolve any issues effectively.

Kind Regards,

Krystian
