### ISSUE TITLE
Problems with Apple Pay via Paypal | Safari Browsers

### ISSUE THREAD

**Issue by Naturmetzger** [woocommerce/woocommerce-paypal-payments#2761]
Hi Woocommerce,

actually it is not possible to place an order with Apple Pay via PayPal on fleischlust.com. The buttons appear, the fingerprint is taken, but the payment does not go through: "Zahlung fehlgeschlagen". We had some paypal technicans investigation on this and this is what they found:

"PayPal does not see REST API Capture call that should come from merchant's shop powered by WooCommerce after the Buyer approved payment via Apple Pay. It seems that merchant's shop powered by WooCommerce is NOT calling REST API Capture call to capture the order after the Buyer approved payment via Apple Pay and this mostly indicates there is certain some issue in merchant's shop powered by WooCommerce."

We followed all the steps shown on https://woocommerce.com/document/woocommerce-paypal-payments/#apple-pay several times. Even under the supervision of PayPal technicians.

We deactivated Apple Pay since it is not working. The issue can only be seen with activated Apple Pay. Please let me know when we should activate it for testing purposes.

Thank you very much!
Martin Schlesinger

### technicals:
Wordpress 6.6.2
WooCommerce 9.3.3
WooCommerce PayPal Payments 2.9.3
Safari 17.6 on MacOS Sonoma 14.6.1
Open PayPal Ticket: WER-IST-SEEFRIED.DE by ptasic@paypal.com

**Comment by SydeKrystian** [comment]
Hello @Naturmetzger 

We’ll likely need to review your staging site and attempt to reproduce this behavior using a sandbox account. However, while we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). 

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
