### ISSUE TITLE
PayPal doesn't catch shipping

### ISSUE THREAD

**Issue by Delickacy** [woocommerce/woocommerce-paypal-payments#2775]
### Describe the Bug

I have all set up and working with WooCommerce payments, but the PayPal button doesn't catch the shipping charges. I am using a flat rate shipping option using "Shipping Zones by Drawing for WooCommerce" which works correctly picking up the charges based on the postal codes. (WooCommerce shipping is NOT available in Canada)

Right now the PayPal button either appears as Express Checkout before the shipping address input area. Below that the Payment option with CC/Debit card OR a smaller PayPal radio button shows up. However since the customer sees the PayPal logo BIGGER than a smaller Radio Button below, they could click on that and pay without entering the address below to add the shipping cost.

When I remove the Express Checkout and leave Standard Check out in the settings, PayPal button disappears completely. Basically customer does not see any PayPal Logo, and only Credit/Debit card option.

### To Reproduce

I would like to have the Customer Details first, followed by the Address which calculates the shipping charges, then the Payment option with either PayPal or CC/Debit options. 

### Screenshots

![Image](https://github.com/user-attachments/assets/782af086-dfa3-4add-b7e5-846d3544eea0)

![Image](https://github.com/user-attachments/assets/02a76924-9d4e-4d6c-a266-50a85bc98a96)

### Expected Behavior

Payment options to be PayPal OR CC/Debit Card

### Actual Behavior

PayPal Express Checkout that bypass the shipping cost or No PayPal option but CC/Debit option which correctly process with the shipping charges added.

### Environment

 - WordPress Version 
 - WooCommerce Version 9.3.3
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version Safari
 - Any other plugins installed 
1.WooCommerce PayPal Payments
2.WooCommerce Shipping
3.WooCommerce Shipping & Tax
4.WooCommerce Stripe Gateway
5.WooCommerce.com Update Manager
6.WooPayments
7.Shipping Zones by Drawing for WooCommerce
8.Google for WooCommerce

### Additional Details

<details><summary>System status</summary>

 `
### WordPress Environment ###

WordPress address (URL): https://delickacy.com
Site address (URL): https://delickacy.com
WC Version: 9.3.3
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.33
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.6.19-MariaDB-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.3.3
WC Database Prefix: ndzt_
Total Database Size: 19.66MB
Database Data Size: 14.40MB
Database Index Size: 5.26MB
ndzt_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_actionscheduler_actions: Data: 1.52MB + Index: 0.94MB + Engine InnoDB
ndzt_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_actionscheduler_logs: Data: 1.23MB + Index: 0.44MB + Engine InnoDB
ndzt_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_blog_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ndzt_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
ndzt_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_automations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_automation_runs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ndzt_mailpoet_automation_run_logs: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_mailpoet_automation_run_subjects: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_automation_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_automation_versions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_newsletters: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ndzt_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
ndzt_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_subscribers: Data: 0.02MB + Index: 0.23MB + Engine InnoDB
ndzt_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_subscriber_tag: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_mailpoet_tags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_options: Data: 5.02MB + Index: 0.14MB + Engine InnoDB
ndzt_postmeta: Data: 1.52MB + Index: 0.41MB + Engine InnoDB
ndzt_posts: Data: 0.31MB + Index: 0.13MB + Engine InnoDB
ndzt_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_sitemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
ndzt_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
ndzt_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
ndzt_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ndzt_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ndzt_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ndzt_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ndzt_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_wc_product_meta_lookup: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
ndzt_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ndzt_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ndzt_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 146
customize_changeset: 4
custom_css: 1
mailpoet_page: 1
nav_menu_item: 5
page: 11
post: 2
product: 102
product_variation: 159
revision: 32
shop_order_placehold: 4
szbdzones: 8
wp_font_face: 33
wp_font_family: 12
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

All-in-One WP Migration: by ServMask – 7.87
Duplicate Page: by mndpsingh287 – 4.5.4
Google for WooCommerce: by WooCommerce – 2.8.6
Jetpack: by Automattic – 13.9.1
Limit Login Attempts Reloaded: by Limit Login Attempts Reloaded – 2.26.16
Pinterest for WooCommerce: by WooCommerce – 1.4.11
Shipping Zones by Drawing for WooCommerce: by Arosoft.se – 3.1.2.4
TikTok: by TikTok – 1.2.10
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Stripe Gateway: by Stripe – 8.8.1
WooPayments: by WooCommerce – 8.4.0
WooCommerce PayPal Payments: by WooCommerce – 2.9.3
WooCommerce Shipping & Tax: by WooCommerce – 2.8.3
WooCommerce Shipping: by WooCommerce – 1.2.2
WooCommerce: by Automattic – 9.3.3

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Flexible Shipping: by Octolize – 5.0.3
Hello Dolly: by Matt Mullenweg – 1.7.2
MailPoet: by MailPoet – 5.3.6

### Must Use Plugins (1) ###

WordPress automation by Installatron: by  –

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 632 KB

### WC Pages ###

Shop base: #43 - /shop/
Cart: #44 - /cart/ -  Contains the woocommerce/cart block
Checkout: #45 - /checkout/ -  Contains the woocommerce/checkout block
My account: #46 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Creamery Pro
Version: pro 1.0
Author URL: https://gracethemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### WooPayments ###

Version: 8.4.0
Connected to WPCOM: Yes
WPCOM Blog ID: 237305740
Account ID: acct_1Q2IoLC8Ft3S9go4
Payment Gateway: Enabled
Test Mode: Enabled
Enabled APMs: card
WooPay: Not eligible
Apple Pay / Google Pay: Disabled
Fraud Protection Level: basic
Multi-currency: Enabled
Auth and Capture: Enabled
Documents: Disabled
Logging: Disabled

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: CA
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: –
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings

Daily Cron: ✔ Next scheduled: 2024-11-06 20:00:19 +00:00
Options: ✔
Notes: 70
Onboarding: completed

### Action Scheduler ###

Complete: 221
Oldest: 2024-10-06 21:48:33 +0000
Newest: 2024-11-06 03:29:34 +0000

Failed: 1
Oldest: 2024-09-29 05:39:35 +0000
Newest: 2024-09-29 05:39:35 +0000

Pending: 3
Oldest: 2024-11-06 06:27:32 +0000
Newest: 2024-11-07 03:29:34 +0000

### Status report information ###

Generated at: 2024-11-06 06:26:47 +00:00
`
  
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Delickacy 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
