### ISSUE TITLE
El pago en 3 plazos de PayPal no funciona, el pago normal con PayPal si que funciona

### ISSUE THREAD

**Issue by AngelicaHub** [woocommerce/woocommerce-paypal-payments#2780]
Mis clientes cuando proceden a pagar mediante la opción de pago en 3 plazos con PayPal les aparece el siguiente error (**Paga en 3 plazos no está disponible para esta compra. Puedes seguir pagando con PayPal de forma rápida y segura.**).

Sin embargo, cuando proceden a pagar de forma normal, le deja pagar sin problema. He revisado la configuración del Plugin de Paypal y todo parece estar activo y correctamente configurado.

### Screenshots

<img src="https://darianails.com/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-09-at-14.17.02.jpeg"/>
### Expected Behavior

Cuando los usuarios introducen su correo y contraseña de PayPal, pulsan sobre iniciar sesión e inician correctamente y cuando continuan con el pago les aparece ese mensaje de la imagen compartida anteriormente.

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.3
 - Plugin Version: WooCommerce PayPal Payments: Versión 2.9.3
 - Browser Chrome and Version: Versión 130.0.6723.92 (Build oficial) (x86_64)
 - Any other plugins installed: 
 
Administrador de archivos WP - Versión 8.0
Advanced Dynamic Pricing for WooCommerce - Versión 4.9.0
All-in-One WP Migration - Versión 7.83
All-in-One WP Migration Unlimited Extension - Versión 2.58
Click to Chat - Versión 4.12
Code Snippets - (sin versión especificada)
Contact Form 7 - Versión 6.0
Cookie Notice & Compliance for GDPR / CCPA - Versión 2.4.18
CTX Feed - Versión 6.5.31
Elementor - Versión 3.25.4
Elementor Pro - Versión 3.24.4
Email Log - Versión 2.4.9
Extras for Elementor - Versión 2.2.51
Flexible Shipping - Versión 5.0.4
Google for WooCommerce - Versión 2.8.6
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress - Versión 1.20.2
Happy Elementor Addons - Versión 3.12.3
Happy Elementor Addons Pro - Versión 2.13.1
Imagify - (sin versión especificada)
Indexado instantáneo - Versión 1.1.21
Ivory Search - Versión 5.5.7
Limit Login Attempts Reloaded - Versión 2.26.16
LoginPress - Versión 3.2.2
MC4WP: Mailchimp for WordPress - Versión 4.9.18
Pasarela Unificada de Redsys para WooCommerce - Versión 1.5.4
Pay for Payment for WooCommerce - Versión 2.1.8
Plugin for Google Reviews - Versión 4.7
Popup by Supsystic - (sin versión especificada)
PowerPack Pro for Elementor - Versión 2.10.19
PublishPress Capabilities - Versión 2.14.0
Rank Math SEO - Versión 1.0.231
Rank Math SEO PRO - Versión 3.0.65
Really Simple Security - Versión 9.1.1.1
reCAPTCHA by BestWebSoft - Versión 1.78
Site Kit by Google - Versión 1.139.0
Smash Balloon Instagram Feed - (sin versión especificada)
Under Construction - (sin versión especificada)
User Registration - Versión 3.3.4.1
WC - APG Campo NIF/CIF/NIE - Versión 3.0.9
Weglot Translate - (sin versión especificada)
WooCommerce - Versión 9.3.3
WooCommerce AJAX Cart - Versión 1.3.25
WooCommerce Login Popup and Shortcodes - Versión 1.0.2
WooCommerce PayPal Payments - Versión 2.9.3
WooPayments - Versión 8.4.0
WP Rocket - Versión 3.8.8
YellowPencil Pro - Versión 7.6.1
YITH WooCommerce Wishlist - Versión 4.0.0

 ¡Muchísimas Gracias de antemano! Espero que puedan encontrar el error y darme una solución lo antes posible por favor, los clientes no pueden comprar. Un saludo y feliz navidad

</details>

**Comment by SydeKrystian** [comment]
Hello @AngelicaHub 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
