### ISSUE TITLE
Refunds not working - receive error

### ISSUE THREAD

**Issue by nerdnestmedia** [woocommerce/woocommerce-paypal-payments#2782]
### To Reproduce

1. Go to '…' - Order 56922, trying to refund 3.00 for purchasing 2 of one download accidentally. 
2. Click on '…' Click on the order, try to refund
3. See error: An error occurred while attempting to create the refund using the payment gateway API.

### Screenshots

![Image](https://github.com/user-attachments/assets/50b5c00b-b93a-43a2-b508-f88a35e53fed)

### Expected Behavior

Expect to give refund of $3 to cusotmer through advanced credit card processing

### Actual Behavior

error in screenshot presents itself, instead of successful refund.

### Environment

 - WordPress Version - Current version: 6.6.2
 - WooCommerce Version - Version 9.3.3
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version - Chrome
 - Any other plugins installed - a lot!

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @nerdnestmedia 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
