### ISSUE TITLE
PayPal Advanced Card Processing Not Working

### ISSUE THREAD

**Issue by designboxuk** [woocommerce/woocommerce-paypal-payments#2787]
### Describe the Bug

Paypal "Credit & Debit Card" solution for PayPals Advanced Card Processing not working / showing correctly. 

### To Reproduce

1. Go to https://postaltubeshop.com/
2. Add product to basket
3. Go to checkout
4. You can see the wrong "

### Screenshots

![Image](https://github.com/user-attachments/assets/023bc43c-97df-4498-957f-736406d23e3e)

### Expected Behavior

The Advanced Card Processing paypal solution should be showing as per screenshot below

![Image](https://github.com/user-attachments/assets/e9a4d534-f4f8-4928-8b50-3f440cb1e7fd)

### Actual Behavior

As described above ^

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 9.3.3
 - Plugin Version: 2.9.4
 - Browser [e.g. Chrome, Safari] and Version: Version 130.0.6723.117 (Official Build) (x86_64)
 - Any other plugins installed: 
 
ActiveCampaign Postmark (Official) | Version 1.20.0 by Andrew Yates & Matt Gibbs \| Auto-updates disabled
Akismet Anti-spam: Spam Protection | Version 5.3.3 by Automattic - Anti-spam Team \| Auto-updates disabled
Better Search Replace | Version 1.4.7 by WP Engine \| Auto-updates disabled
Breeze | Version 2.1.18 by Cloudways \| Auto-updates disabled
Design Box Dashboard | Version 1.4.2 by Design Box Team \| Auto-updates disabled
Disable User Password Reset Admin Notifications | Version 1.9 by Chris Cook \| Auto-updates disabled
Duplicate Page | Version 4.5.4 by mndpsingh287 \| Auto-updates disabled
Google Analytics for WooCommerce | Version 2.1.7 by WooCommerce \| Auto-updates disabled
Google for WooCommerce | Version 2.8.6 by WooCommerce \| Auto-updates disabled
Gravity Forms | Version 2.8.18 by Gravity Forms \| Auto-updates enabled
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress | Version 1.20.2 by Thomas Geiger \| Auto-updates disabled
JetEngine | Version 3.5.7 by Crocoblock \| Auto-updates disabled
JetSmartFilters | Version 3.5.4 by Crocoblock (Latest version: 3.5.7.1) \| Auto-updates disabled
Object Cache Pro | Version 1.21.3 by Rhubarb Group \| Auto-updates disabled
Plugin for Google Reviews | Version 4.7 by RichPlugins <support@richplugins.com> (Latest version: 4.8) \| Auto-updates disabled
Print Invoice & Delivery Notes for WooCommerce | Version 5.2.0 by Tyche Softwares \| Auto-updates disabled
Redirection | Version 5.5.0 by John Godley \| Auto-updates disabled
Schema Pro | Version 2.7.23 by Brainstorm Force \| Auto-updates disabled
SEOPress | Version 8.3.1 by The SEO Guys at SEOPress \| Auto-updates disabled
SEOPress PRO | Version 8.2 by The SEO Guys at SEOPress (Latest version: 8.3) \| Auto-updates disabled
User Switching | Version 1.8.0 by John Blackbourn \| Auto-updates disabled
WooCommerce | Version 9.3.3 by Automattic \| Auto-updates disabled
WooCommerce Legacy REST API | Version 1.0.4 by WooCommerce \| Auto-updates disabled
WooCommerce Locations Pack | Version 1.9.8 by dangoodman \| Auto-updates disabled
WooCommerce PayPal Payments | Version 2.9.4 by WooCommerce \| Auto-updates disabled
WooSidebars | Version 1.4.6 by WooCommerce \| Auto-updates disabled
WP Fusion | Version 3.43.12 by Very Good Plugins (Latest version: 3.44.13) \| Auto-updates disabled
WP Mail Logging | Version 1.13.1 by WP Mail Logging Team \| Auto-updates disabled

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
`
### wp-core ###

version: 6.6.2
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 10007
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html
wordpress_size: loading...
uploads_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/themes
themes_size: loading...
plugins_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/plugins
plugins_size: loading...
fonts_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/uploads/fonts
fonts_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Postal Tube Shop (postal-tubes)
version: 2.0
author: Design Box Media
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, block-templates, post-thumbnails, woocommerce, title-tag, automatic-feed-links, customize-selective-refresh-widgets, sensei, html5, menus, post-formats, wc-product-gallery-lightbox, widgets, editor-style
theme_path: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/themes/postal-tubes
auto_update: Disabled

### wp-themes-inactive (11) ###

Flatsome: version: 3.19.6, author: UX-Themes, Auto-updates disabled
Storefront: version: 4.6.0, author: Automattic, Auto-updates disabled
Twenty Fifteen: version: 3.8, author: the WordPress team, Auto-updates disabled
Twenty Nineteen: version: 2.9, author: WordPress Team, Auto-updates disabled
Twenty Seventeen: version: 3.7, author: the WordPress team, Auto-updates disabled
Twenty Sixteen: version: 3.3, author: The WordPress Team, Auto-updates disabled
Twenty Twenty: version: 2.7, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Four: version: 1.2, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 2.3, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.8, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (28) ###

ActiveCampaign Postmark (Official): version: 1.20.0, author: Andrew Yates & Matt Gibbs, Auto-updates disabled
Akismet Anti-spam: Spam Protection: version: 5.3.3, author: Automattic - Anti-spam Team, Auto-updates disabled
Better Search Replace: version: 1.4.7, author: WP Engine, Auto-updates disabled
Breeze: version: 2.1.18, author: Cloudways, Auto-updates disabled
Design Box Dashboard: version: 1.4.2, author: Design Box Team, Auto-updates disabled
Disable User Password Reset Admin Notifications: version: 1.9, author: Chris Cook, Auto-updates disabled
Duplicate Page: version: 4.5.4, author: mndpsingh287, Auto-updates disabled
Google Analytics for WooCommerce: version: 2.1.7, author: WooCommerce, Auto-updates disabled
Google for WooCommerce: version: 2.8.6, author: WooCommerce, Auto-updates disabled
Gravity Forms: version: 2.8.18, author: Gravity Forms, Auto-updates enabled
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: version: 1.20.2, author: Thomas Geiger, Auto-updates disabled
JetEngine: version: 3.5.7, author: Crocoblock, Auto-updates disabled
JetSmartFilters: version: 3.5.4, author: Crocoblock (latest version: 3.5.7.1), Auto-updates disabled
Object Cache Pro: version: 1.21.3, author: Rhubarb Group, Auto-updates disabled
Plugin for Google Reviews: version: 4.7, author: RichPlugins <support@richplugins.com> (latest version: 4.8), Auto-updates disabled
Print Invoice & Delivery Notes for WooCommerce: version: 5.2.0, author: Tyche Softwares, Auto-updates disabled
Redirection: version: 5.5.0, author: John Godley, Auto-updates disabled
Schema Pro: version: 2.7.23, author: Brainstorm Force, Auto-updates disabled
SEOPress: version: 8.3.1, author: The SEO Guys at SEOPress, Auto-updates disabled
SEOPress PRO: version: 8.2, author: The SEO Guys at SEOPress (latest version: 8.3), Auto-updates disabled
User Switching: version: 1.8.0, author: John Blackbourn, Auto-updates disabled
WooCommerce: version: 9.3.3, author: Automattic, Auto-updates disabled
WooCommerce Legacy REST API: version: 1.0.4, author: WooCommerce, Auto-updates disabled
WooCommerce Locations Pack: version: 1.9.8, author: dangoodman, Auto-updates disabled
WooCommerce PayPal Payments: version: 2.9.4, author: WooCommerce, Auto-updates disabled
WooSidebars: version: 1.4.6, author: WooCommerce, Auto-updates disabled
WP Fusion: version: 3.43.12, author: Very Good Plugins (latest version: 3.44.13), Auto-updates disabled
WP Mail Logging: version: 1.13.1, author: WP Mail Logging Team, Auto-updates disabled

### wp-plugins-inactive (2) ###

JetElements For Elementor: version: 2.7.0, author: Crocoblock, Auto-updates disabled
WooCommerce Worldpay Gateway - Worldpay Online Payments: version: 2.0.0, author: Worldpay, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 500M
upload_max_filesize: 500M
max_effective_size: 500 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 31 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 31 GB
	imagick::RESOURCETYPE_MEMORY: 16 GB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.10.0-31-amd64 x86_64
httpd_software: Apache/2.4.62 (Debian)
php_version: 8.1.30 64bit
php_sapi: fpm-fcgi
max_input_variables: 2500
time_limit: 800
memory_limit: 2040M
max_input_time: 290
upload_max_filesize: 500M
php_post_max_size: 500M
curl_version: 7.74.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-11-12T16:34:09+00:00
utc-time: Tuesday, 12-Nov-24 16:34:09 UTC
server-time: 2024-11-12T16:34:06+00:00

### wp-database ###

extension: mysqli
server_version: 10.6.19-MariaDB-deb11-log
client_version: mysqlnd 8.1.30
max_allowed_packet: 134217728
max_connections: 250

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content
WP_PLUGIN_DIR: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 2040M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: not writable

### objectcache ###

general-status: Connected
general-dropin: Valid
general-license: Valid
general-env: production
general-multisite: No
general-mu: No
general-vcs: No
general-host: cloudways
general-eviction-policy: allkeys-lfu
general-compressions: LZF, LZ4, ZSTD
general-basename: object-cache-pro/object-cache-pro.php
general-client: RedisCachePro\Clients\PhpRedis
versions-php: 8.1.30
versions-igbinary: 3.2.16
versions-phpredis: 6.0.2
versions-relay: Not installed
versions-redis: 7.4.1
versions-plugin: 1.21.3
versions-dropin: 1.21.3
statistics-redis-memory: 44 MB of 2 GB
statistics-redis-keys: 4122
groups-global: [
    "analytics",
    "objectcache",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "blog_meta",
    "global-posts",
    "networks",
    "network-queries",
    "sites",
    "site-details",
    "site-options",
    "site-queries",
    "site-transient",
    "theme_files",
    "translation_files",
    "rss",
    "users",
    "user-queries",
    "user_meta",
    "useremail",
    "userlogins",
    "userslugs"
]
groups-non-persistent: [
    "counts",
    "plugins",
    "theme_json",
    "themes"
]
groups-non-prefetchable: [
    "analytics",
    "objectcache",
    "userlogins",
    "wc_session_id"
]
config-token: ••••••••001c
config-connector: RedisCachePro\Connectors\PhpRedisConnector
config-cache: RedisCachePro\ObjectCaches\PhpRedisObjectCache
config-logger: RedisCachePro\Loggers\ErrorLogLogger
config-log_levels: emergency, alert, critical, error, warning
config-scheme: tcp
config-host: 127.0.0.1
config-port: 6379
config-database: 7159
config-username: null
config-password: null
config-prefix: xjcggpezav
config-maxttl: null
config-timeout: 2.5s
config-read_timeout: 2.5s
config-retry_interval: 25ms
config-retries: 3
config-backoff: smart
config-persistent: false
config-shared: null
config-async_flush: true
config-group_flush: keys
config-network_flush: all
config-cluster: null
config-cluster_failover: error
config-servers: null
config-replication_strategy: distribute
config-sentinels: null
config-service: null
config-tracer: none
config-serializer: igbinary
config-compression: zstd
config-global_groups: null
config-non_persistent_groups: null
config-non_prefetchable_groups: null
config-prefetch: true
config-split_alloptions: true
config-analytics: {
    "enabled": true,
    "persist": true,
    "retention": 7200,
    "sample_rate": 100,
    "footnote": true
}
config-relay: {
    "cache": true,
    "listeners": false,
    "invalidations": true,
    "allowed": null,
    "ignored": [
        "*:analytics:*"
    ]
}
config-tls_options: null
config-updates: true
config-debug: false
config-strict: false
config-save_commands: false
environment-WP_REDIS_DISABLED: 0
environment-OBJECTCACHE_CONFIG: undefined
constants-WP_DEBUG: false
constants-SAVEQUERIES: undefined
constants-WP_REDIS_DIR: undefined
constants-WP_REDIS_DISABLED: false
constants-WP_REDIS_CONFIG: {
    "token": "••••••••001c",
    "host": "127.0.0.1",
    "port": 6379,
    "database": "7159",
    "timeout": 2.5,
    "read_timeout": 2.5,
    "split_alloptions": true,
    "async_flush": true,
    "client": "phpredis",
    "compression": "zstd",
    "serializer": "igbinary",
    "prefetch": true,
    "debug": false,
    "save_commands": false,
    "prefix": "xjcggpezav"
}

### postmark-wordpress ###

status: Yes
version: 1.20.0
directory: /home/1305813.cloudwaysapps.com/xjcggpezav/public_html/wp-content/plugins/postmark-approved-wordpress-plugin
url: https://postaltubeshop.com/wp-content/plugins/postmark-approved-wordpress-plugin
stream: outbound
sender_address: info@postaltubeshop.com
force_from: No
force_html: No
track_opens: No
track_links: Yes
enable_logs: Yes

`

</details>

**Comment by enri90** [comment]
same problem even if I try to configure the credit cards it gives me status: not yet enabled

**Comment by SydeKrystian** [comment]
Hello @designboxuk 


I'm not sure if there's anything specifically wrong in the first screenshot you provided. It would be helpful if you could point out the exact issue you're experiencing. However, I did notice that the second screenshot, where you show the expected outcome, actually depicts a different gateway—it’s not related to Advanced Card Processing but rather the standard card gateways. The '3-button' appearance you're expecting cannot be achieved with Advanced Card Processing.

We appreciate your feedback, but please note that GitHub is primarily used for our development activities. For a faster and more detailed response, we recommend that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When contacting our support team, please include your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This information will help us better understand your setup and resolve your issue more efficiently.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you further.

Thank you for your understanding!

Kind Regards,  
Krystian
