### ISSUE TITLE
Pay Later option doesn't disable

### ISSUE THREAD

**Issue by isaacetor** [woocommerce/woocommerce-paypal-payments#2788]
### Describe the Bug

I tried disabling the pay later option on my website, but after saving the option still remains active and doesn't disable.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version = 6.6.2
 - WooCommerce Version = Version 9.3.3
 - Plugin Version =  2.9.4
 - Browser [e.g. Chrome, Safari] and Version = mozilla firefox
 - Any other plugins installed = woocommerce, elementor

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @isaacetor 

Normally, you should be able to disable the “Pay Later” messaging in the cart and checkout by using the Pay Later configurator.

Here’s a reference screenshot showing how to adjust these settings: [Pay Later Configurator Screenshot](https://drive.google.com/uc?id=1Lg3wILxjH4Cmiw0YXO3i0QPE_poe1LfI).

However, some users have reported that the configurator doesn’t always save settings as expected. If this is the case for you, a workaround would be to enable the legacy Pay Later configurator by adding a filter.

You can add the following code:

```
add_filter('woocommerce_paypal_payments_checkout_messages_renderer_hook', function () {     return 'ppcp_start_button_wrapper_ppcp_gateway'; 
});
```

You can use a plugin like Code Snippets to easily apply this filter.

If you need further assistance we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Best Regards,
Krystian
