### ISSUE TITLE
Add payment methods bugged

### ISSUE THREAD

**Issue by opicron** [woocommerce/woocommerce-paypal-payments#2795]
### Describe the Bug

When using the Add Payment Methods in the Account dashboard I notice some odd behaviour.

Two Payment Methods are in my Account: 
- VISA
- Paypal (default method)

When selecting Add Payment Method, and selecting Paypal this is the result screen:

![Image](https://github.com/user-attachments/assets/12ca0860-2f29-4f04-baec-f14453459564)

When selecting the blue button Add Payment Method the first time following happens:

- Paypal is no longer the default method.

![Image](https://github.com/user-attachments/assets/74eeb312-bd5f-46c9-bb1d-7bb7eaaf0c5a)

When trying for an second time to choose Add Payment Method the following happens:

- VISA payment method is removed*

*I tried to recreate this bug but I am unable to. However it did just happen :/.

Sidebug when setting a default payment method:

![Image](https://github.com/user-attachments/assets/dc8e0abf-c0f4-4f54-95bb-9eecd7d73ac0)

### Expected Behavior

- I expected not to received errors on adding an existing Paypal Payment Method. 
- I not expected to see a golden Pay Now button when adding an Paypal Payment Method. It should be an default Paypal button.
- I expected not to see two notifications when changing the default Payment Method

### Environment

 - WordPress Version 6.6.2
 - WooCommerce Version 9.4.1
 - Plugin Version 2.9.4
 - Any other plugins installed: 
 ACF Slider Block 0.1.2
Advanced Custom Fields PRO 6.3.11
Akismet 5.3.3
Breeze 2.1.19
Code Snippets Pro (Premium) 3.6.5
Debug Log Manager 2.3.3	
Digital License Manager PRO 1.5.0	
GenerateBlocks 1.9.1	
GenerateBlocks Pro 1.7.1	
GP Premium 2.5.0
Gutenberg Block Styles 1.0
I Recommend This 3.10.2
MainWP Child 5.2
MainWP Child Reports 2.2.3
Menu By User Roles 1.0.4
Object Cache Pro 1.21.3
Site Kit by Google 1.139.0
SMTP2GO - Email Made Easy 1.10.0
Two Factor 0.9.1
WooCommerce 9.4.1
WooCommerce PayPal Payments 2.9.4 
WooCommerce Subscriptions 6.9.0
WooCommerce Subscriptions - Custom Price String 1.0.6
WooCommerce.com Update Manager 1.0.3
WooPayments 8.5.0

**Comment by SydeKrystian** [comment]
Hello @opicron 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
