### ISSUE TITLE
php Error

### ISSUE THREAD

**Issue by aaron843** [woocommerce/woocommerce-paypal-payments#2798]
### Describe the Bug

error message from php log:

id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WooCommerce\PayPalCommerce\WcGateway\Gateway\PayPalGateway->process_payment, WooCommerce\PayPalCommerce\WcGateway\Processor\OrderProcessor->process, WooCommerce\PayPalCommerce\WcGateway\Processor\OrderProcessor->handle_new_order_status, WooCommerce\PayPalCommerce\WcGateway\Processor\OrderProcessor->handle_capture_status, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array('woocommerce_order_status_pending_to_processing_notification'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_New_Order->trigger, WC_Email->get_subject, apply_filters('woocommerce_email_subject_new_order'), WP_Hook->apply_filters, custom_email_subject, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.

### To Reproduce

1. Purchase with PayPal

### Expected Behavior

No error messages

### Actual Behavior

Error message

### Environment

 - WordPress Version 6.7
 - WooCommerce Version 9.3.3 
 - Plugin Version 2.9.3 
 - Browser [e.g. Chrome, Safari] and Version NA
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @aaron843 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by aaron843** [comment]
Okay. You may want to update your support link, which is what directed me to github.
