### ISSUE TITLE
Smart buttons not translated on iOS devices (294)

### ISSUE THREAD

**Issue by isabellainpsyde** [woocommerce/woocommerce-paypal-payments#280]
**The problem**
The text on the smart button does not get translated to German when using IOS device. For Windows and Android devices this does not occur.
There seems to be a difference between “Pay with PayPal” and “Pay Later” button; on my testing env. I use German Merchant account and VPN, but only the Pay Later button got translated to German.

**Steps to reproduce**

- Setup a store for Germany with Euros and a German Merchant account.
- Activate the pay later button on Checkout.
- Make a purchase on an iOS device like an iPhone or iPad
→ The smart buttons will be translated to German with an Android & Windows devices, but not with an iOS device. 
The Pay Later button for German merchants is always called “ Später Bezahlen”, because every region has a specific Pay Later button. (E.g. for Australia “Pay in 4”)

![image](https://user-images.githubusercontent.com/70694460/134904404-9d16b05d-c74a-403b-9375-eb031f108cb6.png)

**Expected behaviour**
All buttons should be translated automatically to German when the user fits the criteria from PayPal.
A feature as proposed feature request: override language used to display PayPal buttonsBACKLOG may help resolve this issue for when the merchant only wants the buttons to be displayed in one language anyway.

**Possible cause**
Expecting PayPal to return variable values from gathered details (system, browser & country) when it should only check the country selection. It should also be the same for both buttons (as now it seems to have a separate process for the two)

**Comment by InpsydeNiklas** [comment]
This should not be a problem anymore.
Additionally, https://github.com/woocommerce/woocommerce-paypal-payments/pull/1098 implements a setting to set a fixed the language.
