### ISSUE TITLE
Woocommerce order failed via PayPal Payment Gateway.

### ISSUE THREAD

**Issue by POPCLINGS** [woocommerce/woocommerce-paypal-payments#2802]
So I have recently update the PayPal Payment Plugin to Version 2.9.4.

There are orders failed with the following notification. I have been using a currency switcher. Can this be solved?

[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/api/rest/reference/orders/v2/errors/#CANNOT_MIX_CURRENCIES ********************* CANNOT_MIX_CURRENCIES CANNOT_MIX_CURRENCIES

**Comment by SydeKrystian** [comment]
Hello @POPCLINGS 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
