### ISSUE TITLE
Advanced Card Processing always failing

### ISSUE THREAD

**Issue by joekewe** [woocommerce/woocommerce-paypal-payments#2806]
### Describe the Bug

After several years of successful credit card web store orders, Advanced Card Processing is now always failing.  Customers all receive "There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again."  Orders fail.  
Log shows:
2024-11-18T18:13:46+00:00 Warning No PayPal order ID found in order #30621 meta.
2024-11-18T18:13:46+00:00 Error Payment failed: There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again. OrderProcessor.php:222

### To Reproduce

Attempt to checkout using a credit card (not PayPal) from our web store.

### Expected Behavior

Transaction should work

### Actual Behavior

Customers all receive "There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again."  Orders fail.  
Log shows:
**2024-11-18T18:13:46+00:00 Warning No PayPal order ID found in order #30621 meta.**
2024-11-18T18:13:46+00:00 Error Payment failed: There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again. OrderProcessor.php:222

### Environment

 - WordPress 6.7
 - WooCommerce Version  9.4.1
 - Plugin Version   2.9.4
 - Browser Safari 18.1 and Version
 - Any other plugins installed:
 
Business Bloomer WooCommerce Add To: Cc: Bcc: Email Recipients	 	by Business Bloomer – 2.3.20240214
Booster Plus for WooCommerce	 	by Pluggabl LLC – 7.2.4
Broken Link Checker	 	by WPMU DEV – 2.4.1
CM Curated List Manager Pro	 	by CreativeMindsSolutions – 1.5.3
Contact Form 7	 	by Takayuki Miyoshi – 6.0
Disable XML-RPC	 	by Philip Erb – 1.0.1
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress	 	by Thomas Geiger – 1.20.2
ELEX WooCommerce DHL Express Shipping - Basic	 	by ELEXtensions – 3.0.5
Enable Media Replace	 	by ShortPixel – 4.1.5
Enhanced Media Library	 	by wpUXsolutions – 2.9.4
Avada Builder	 	by ThemeFusion – 3.11.11
Avada Core	 	by ThemeFusion – 5.11.11
Google for WooCommerce	 	by WooCommerce – 2.8.7
GTranslate	 	by Translate AI Multilingual Solutions – 3.0.7
Custom Login Page Customizer	 	by Hardeep Asrani – 2.4.0
Search By SKU - for Woocommerce	 	by Unroll Digital – 0.8.0
Speed Up - Menu Cache	 	by Simone Nigro – 1.0.18
UpdraftPlus - Backup/Restore	 	by TeamUpdraft, DavidAnderson – 1.24.11
WooCommerce UPS Shipping Plugin with Print Label	 	by PluginHive – 6.1.8
W3 Total Cache	 	by BoldGrid – 2.8.0
WebRotate 360 Product Viewer for WordPress	 	by WebRotate 360 LLC – 3.2.0
WooCommerce.com Update Manager	 	by Automattic – 1.0.3
WooCommerce Purchase Order Payment Gateway	 	by WooCommerce – 1.4.8
WooCommerce PayPal Payments	 	by WooCommerce – 2.9.4
WooCommerce	 	by Automattic – 9.4.1
Yoast SEO	 	by Team Yoast – 23.8

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://www.autom8.com
Site address (URL): https://www.autom8.com
WC Version: 9.4.1
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.25.5
PHP Version: 8.2.25
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.11.5-MariaDB-1:10.11.5+maria~ubu2004
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.1
WC Database Prefix: _RVL_
Total Database Size: 250.91MB
Database Data Size: 210.93MB
Database Index Size: 39.98MB
_RVL_woocommerce_sessions: Data: 9.02MB + Index: 0.20MB + Engine InnoDB
_RVL_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_RVL_woocommerce_order_items: Data: 0.28MB + Index: 0.09MB + Engine InnoDB
_RVL_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.97MB + Engine InnoDB
_RVL_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_RVL_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_RVL_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_RVL_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_actionscheduler_actions: Data: 1.19MB + Index: 0.53MB + Engine InnoDB
_RVL_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_actionscheduler_logs: Data: 2.22MB + Index: 0.27MB + Engine InnoDB
_RVL_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_awb_critical_css: Data: 34.02MB + Index: 0.02MB + Engine InnoDB
_RVL_aws_index: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
_RVL_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_blc_instances: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
_RVL_blc_links: Data: 6.52MB + Index: 0.63MB + Engine InnoDB
_RVL_blc_synch: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
_RVL_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_comments: Data: 1.52MB + Index: 0.72MB + Engine InnoDB
_RVL_cptch_blacklist_ip: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_cptch_track_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_fusion_forms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_fusion_form_entries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_fusion_form_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_fusion_form_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
_RVL_gla_merchant_issues: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
_RVL_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_RVL_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_mclean_scan: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_options: Data: 13.30MB + Index: 0.44MB + Engine InnoDB
_RVL_ph_ups_api_key_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_ph_ups_wc_orders_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
_RVL_postmeta: Data: 49.58MB + Index: 23.03MB + Engine InnoDB
_RVL_posts: Data: 61.31MB + Index: 1.39MB + Engine InnoDB
_RVL_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_termmeta: Data: 1.52MB + Index: 0.66MB + Engine InnoDB
_RVL_terms: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
_RVL_term_relationships: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
_RVL_term_taxonomy: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
_RVL_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_usermeta: Data: 2.52MB + Index: 2.98MB + Engine InnoDB
_RVL_users: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
_RVL_wc_admin_notes: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
_RVL_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
_RVL_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_wc_customer_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
_RVL_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
_RVL_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
_RVL_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_wc_order_product_lookup: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
_RVL_wc_order_stats: Data: 0.23MB + Index: 0.16MB + Engine InnoDB
_RVL_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_wc_product_attributes_lookup: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
_RVL_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_wc_product_meta_lookup: Data: 0.19MB + Index: 0.42MB + Engine InnoDB
_RVL_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_RVL_yoast_indexable: Data: 4.52MB + Index: 0.84MB + Engine InnoDB
_RVL_yoast_indexable_hierarchy: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
_RVL_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
_RVL_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
_RVL_yoast_seo_links: Data: 2.45MB + Index: 2.55MB + Engine InnoDB
_RVL_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2292
custom_css: 1
fusion_element: 29
jetpack_migration: 2
nav_menu_item: 511
oembed_cache: 7
page: 264
post: 2
product: 1496
product_variation: 128
revision: 2092
shop_coupon: 1
shop_order: 1395
shop_order_refund: 39
wpcf7_contact_form: 10

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Business Bloomer WooCommerce Add To: Cc: Bcc: Email Recipients: by Business Bloomer – 2.3.20240214
Booster Plus for WooCommerce: by Pluggabl LLC – 7.2.4
Broken Link Checker: by WPMU DEV – 2.4.1
CM Curated List Manager Pro: by CreativeMindsSolutions – 1.5.3
Contact Form 7: by Takayuki Miyoshi – 6.0
Disable XML-RPC: by Philip Erb – 1.0.1
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.20.2
ELEX WooCommerce DHL Express Shipping - Basic: by ELEXtensions – 3.0.5
Enable Media Replace: by ShortPixel – 4.1.5
Enhanced Media Library: by wpUXsolutions – 2.9.4
Avada Builder: by ThemeFusion – 3.11.11
Avada Core: by ThemeFusion – 5.11.11
Google for WooCommerce: by WooCommerce – 2.8.7
GTranslate: by Translate AI Multilingual Solutions – 3.0.7
Custom Login Page Customizer: by Hardeep Asrani – 2.4.0
Search By SKU - for Woocommerce: by Unroll Digital – 0.8.0
Speed Up - Menu Cache: by Simone Nigro – 1.0.18
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 1.24.11

WooCommerce UPS Shipping Plugin with Print Label: by PluginHive – 6.1.8
W3 Total Cache: by BoldGrid – 2.8.0
WebRotate 360 Product Viewer for WordPress: by WebRotate 360 LLC – 3.2.0
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.4.8
WooCommerce PayPal Payments: by WooCommerce – 2.9.4
WooCommerce: by Automattic – 9.4.1
Yoast SEO: by Team Yoast – 23.8

### Inactive Plugins (6) ###

Delete Expired Transients: by WebAware – 2.0.7
DHL Express Commerce: by DHL Express – 3.0.0
ELEX Easypost WooCommerce Extension (BASIC): by ELEXtensions – 2.1.0
Kadence WooCommerce Email Designer: by Kadence WP – 1.5.13
Media Deduper Pro: by Cornershop Creative – 1.3.1
MOJO Marketplace: by Mike Hansen – 1.5.8

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php
maintenance.php: maintenance.php
object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Kinsta Must-use Plugins: by Kinsta Team – 3.1.1
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

Legacy API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 716 KB

### WC Pages ###

Shop base: #1428 - /shop/
Cart: #1429 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #1430 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #1431 - /my-account/
Terms and conditions: #45 - /terms/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.11.11
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada-Child-Theme/woocommerce/emails/customer-refunded-order.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: ✔
Reference Transactions: ✔
Used PayPal Checkout plugin: ✔
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-19 01:30:15 -08:00
Options: ✔
Notes: 194
Onboarding: completed

### Action Scheduler ###

Complete: 385
Oldest: 2024-10-18 19:18:13 +0000
Newest: 2024-11-18 18:34:04 +0000

Failed: 886
Oldest: 2021-09-07 19:25:57 +0000
Newest: 2023-09-27 22:31:20 +0000

Pending: 3
Oldest: 2024-11-19 03:00:00 +0000
Newest: 2024-11-19 12:05:35 +0000

### Status report information ###

Generated at: 2024-11-18 10:34:08 -08:00
`

</details>

**Comment by SydeKrystian** [comment]
Hello @joekewe 

Recently we have identified that when JavaScript is not enabled on the checkout page, ACDC payments can be affected. This is unintended behavior, as ACDC should work independently of the smart buttons.

As a temporary workaround, we recommend enabling Smart Button Locations (under the Standard Payments tab) on the Classic Checkout or Express Checkout page, depending on your current setup. This should resolve the issue until we implement a more permanent fix.

If this workaround does not resolve the problem, please let us know. There is a possibility that, despite enabling the buttons, they might not appear due to conflicts with a third-party plugin or theme.

In that case, we will work with you to investigate the issue further.

Kind Regards,
Krystian

**Comment by joekewe** [comment]
Dear Krystian,

I have temporarily disabled Advanced Card Processing on our web store, and I am relying on the “PayPal” module for accepting credit cards.  Please tell me if you need me to test your JavaScript theory, otherwise I will continue to wait for your updated plugin.

Thanks,

Joe Kewe
