### ISSUE TITLE
Ratepay (PayPal) refund does not work

### ISSUE THREAD

**Issue by manustaufi** [woocommerce/woocommerce-paypal-payments#2808]
### Describe the Bug

We tried to refund a PayPal order which was paid with Ratepay. This looked successful in WooCommerce but in PayPal backend nothing happened.

It shows the following message:
Status der Bestellung auf zurückerstattet gesetzt. Um Geld an den Kunden zurückzuzahlen, musst du eine Rückerstattung über deinen Zahlungsweg erteilen. (English translation: Status of the order set to refunded. To refund money to the customer, you must issue a refund via your payment method.)

### To Reproduce

1. Go to Woocommerce backend
2. Go to any Ratepay order
3. Click on refund and process the refund

### Expected Behavior

The refund should have taken place through PayPal

### Actual Behavior

The message shows: Status der Bestellung auf zurückerstattet gesetzt. Um Geld an den Kunden zurückzuzahlen, musst du eine Rückerstattung über deinen Zahlungsweg erteilen. (English translation: Status of the order set to refunded. To refund money to the customer, you must issue a refund via your payment method.)

### Environment

 - WordPress Version: 6.6.2
 - WooCommerce Version: 7.7.0
 - Plugin Version: 2.9.4
 - Browser [e.g. Chrome, Safari] and Version: Latest Edge
 
### Additional Details

Normal PayPal refunds work as expected.

<details><summary>System status</summary>

### WordPress Environment ###

WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: ❌ 6.6.2 - Es ist eine neuere Version von WordPress verfügbar (6.7)
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 8.2.25
PHP Post Max Size: 1 GB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0+deb10u2
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.7.0
WC Database Prefix: pdi_
Datenbank-Gesamtgröße: 2572.91MB
Datenbank-Datengröße: 1348.29MB
Datenbank-Indexgröße: 1224.62MB
pdi_woocommerce_sessions: Daten: 2.02MB + Index: 0.02MB + Engine InnoDB
pdi_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_woocommerce_order_items: Daten: 10.52MB + Index: 3.52MB + Engine InnoDB
pdi_woocommerce_order_itemmeta: Daten: 369.86MB + Index: 111.23MB + Engine InnoDB
pdi_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
hb_config: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
hb_documents: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
hb_login: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
hb_trash: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
pdi_actionscheduler_actions: Daten: 9.02MB + Index: 13.14MB + Engine InnoDB
pdi_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_actionscheduler_logs: Daten: 7.02MB + Index: 4.03MB + Engine InnoDB
pdi_berocket_termmeta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_commentmeta: Daten: 0.11MB + Index: 0.13MB + Engine InnoDB
pdi_comments: Daten: 44.56MB + Index: 29.09MB + Engine InnoDB
pdi_fbv: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_fbv_attachment_folder: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_feedmanager_channel: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_feedmanager_country: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_feedmanager_feed_status: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_feedmanager_field_categories: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_feedmanager_product_feed: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_feedmanager_product_feedmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_feedmanager_source: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_groups_capability: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_groups_group: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_groups_group_capability: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_groups_user_capability: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_groups_user_group: Daten: 1.52MB + Index: 0.39MB + Engine InnoDB
pdi_ig_actions: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
pdi_ig_blocked_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_campaigns: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_ig_contactmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_ig_contacts: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_ig_contacts_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_ig_contact_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_ig_custom_fields: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_ig_lists: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_lists_contacts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_ig_mailing_queue: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_ig_queue: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
pdi_ig_sending_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_temp_import: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_unsubscribe_feedback: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_wc_cart: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
pdi_ig_wc_guests: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_ig_workflows: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_ig_workflows_queue: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_dynamic_segment_filters: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_feature_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_mailpoet_log: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_newsletter_templates: Daten: 2.52MB + Index: 0.00MB + Engine InnoDB
pdi_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_segments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_statistics_bounces: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
pdi_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_mailpoet_statistics_woocommerce_purchases: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_mailpoet_stats_notifications: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_subscribers: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
pdi_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_mailpoet_user_agents: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_mailpoet_user_flags: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_newsletter: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_newsletter_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_newsletter_sent: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_newsletter_stats: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_newsletter_user_logs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_options: Daten: 9.25MB + Index: 2.03MB + Engine InnoDB
pdi_pmxi_files: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_hash: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_history: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_images: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_imports: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_posts: Daten: 0.06MB + Index: 0.00MB + Engine InnoDB
pdi_pmxi_templates: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_postmeta: Daten: 469.98MB + Index: 573.16MB + Engine InnoDB
pdi_posts: Daten: 58.19MB + Index: 22.84MB + Engine InnoDB
pdi_rank_math_analytics_adsense: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_rank_math_analytics_ga: Daten: 2.52MB + Index: 2.44MB + Engine InnoDB
pdi_rank_math_analytics_gsc: Daten: 72.11MB + Index: 82.52MB + Engine InnoDB
pdi_rank_math_analytics_inspections: Daten: 1.38MB + Index: 0.11MB + Engine InnoDB
pdi_rank_math_analytics_keyword_manager: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_rank_math_analytics_objects: Daten: 0.06MB + Index: 0.02MB + Engine InnoDB
pdi_rank_math_internal_links: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
pdi_rank_math_internal_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_redirection_404: Daten: 4.02MB + Index: 6.05MB + Engine InnoDB
pdi_redirection_groups: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_redirection_items: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
pdi_redirection_logs: Daten: 0.19MB + Index: 0.05MB + Engine InnoDB
pdi_storeabill_documentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_storeabill_documents: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
pdi_storeabill_document_attachmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_storeabill_document_attachments: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_storeabill_document_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_storeabill_document_items: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
pdi_storeabill_document_noticemeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_storeabill_document_notices: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_storeabill_journals: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_termmeta: Daten: 0.09MB + Index: 0.14MB + Engine InnoDB
pdi_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
pdi_term_relationships: Daten: 0.08MB + Index: 0.05MB + Engine InnoDB
pdi_term_taxonomy: Daten: 0.06MB + Index: 0.06MB + Engine InnoDB
pdi_usermeta: Daten: 43.56MB + Index: 28.09MB + Engine InnoDB
pdi_users: Daten: 3.52MB + Index: 2.45MB + Engine InnoDB
pdi_wc_admin_notes: Daten: 0.08MB + Index: 0.00MB + Engine InnoDB
pdi_wc_admin_note_actions: Daten: 0.08MB + Index: 0.02MB + Engine InnoDB
pdi_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_wc_customer_lookup: Daten: 4.52MB + Index: 3.98MB + Engine InnoDB
pdi_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_wc_orders: Daten: 32.56MB + Index: 25.45MB + Engine InnoDB
pdi_wc_orders_meta: Daten: 110.66MB + Index: 246.00MB + Engine InnoDB
pdi_wc_order_addresses: Daten: 12.52MB + Index: 15.06MB + Engine InnoDB
pdi_wc_order_coupon_lookup: Daten: 1.52MB + Index: 0.94MB + Engine InnoDB
pdi_wc_order_operational_data: Daten: 12.55MB + Index: 7.03MB + Engine InnoDB
pdi_wc_order_product_lookup: Daten: 9.52MB + Index: 9.06MB + Engine InnoDB
pdi_wc_order_stats: Daten: 10.52MB + Index: 6.55MB + Engine InnoDB
pdi_wc_order_tax_lookup: Daten: 2.52MB + Index: 2.02MB + Engine InnoDB
pdi_wc_product_attributes_lookup: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_wc_product_download_directories: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
pdi_wc_rate_limits: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_wc_reserved_stock: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
pdi_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_wdr_order_discounts: Daten: 0.50MB + Index: 0.00MB + Engine InnoDB
pdi_wdr_order_item_discounts: Daten: 2.52MB + Index: 0.77MB + Engine InnoDB
pdi_wdr_rules: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_woocommerce_amazon_buyer_index: Daten: 0.05MB + Index: 0.05MB + Engine InnoDB
pdi_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_gzd_shipmentmeta: Daten: 12.52MB + Index: 7.03MB + Engine InnoDB
pdi_woocommerce_gzd_shipments: Daten: 2.52MB + Index: 0.61MB + Engine InnoDB
pdi_woocommerce_gzd_shipment_itemmeta: Daten: 12.52MB + Index: 11.03MB + Engine InnoDB
pdi_woocommerce_gzd_shipment_items: Daten: 2.52MB + Index: 3.39MB + Engine InnoDB
pdi_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
pdi_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
pdi_woocommerce_gzd_shipping_providermeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
pdi_wpr_above_the_fold: Daten: 2.52MB + Index: 0.27MB + Engine InnoDB
pdi_wpr_rocket_cache: Daten: 0.09MB + Index: 0.11MB + Engine InnoDB
pdi_wpr_rucss_used_css: Daten: 0.41MB + Index: 0.41MB + Engine InnoDB
pdi_wt_iew_action_history: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
pdi_wt_iew_mapping_template: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acoplw_badges: 1
acoplw_prod_list: 1
attachment: 1125
br_labels: 2
custom_css: 5
custom-css-js: 1
customize_changeset: 17
dipl-team-member: 1
dipl-testimonial: 1
divi-file-uploads: 171
document_template: 6
et_body_layout: 10
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 16
et_template: 48
et_theme_builder: 9
fme_qifw_woocomerce: 1
mailpoet_page: 1
nav_menu_item: 66
oembed_cache: 1
page: 46
pdi_global_styles: 2
post: 73
private: 2471
product: 129
product_variation: 9
revision: 758
rm_content_editor: 1
shop_coupon: 25138
shop_order: 72518
shop_order_refund: 422
sp_wcslider: 4
sp_wps_shortcodes: 3
testimonials: 1
ucfml_coupons: 1
wbcr-snippets: 12
wc_order_status: 9
wcpcsu-custom-post: 2
wcps: 2
wcps_layout: 2
wp_global_styles: 2
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Query Monitor: von John Blackbourn – 3.16.4
Adcell Tracking und Remarketing: von Firstlead GmbH – 1.0.21
Better Search Replace: von WP Engine – 1.4.7
Code Profiler Pro: von Jerome Bruandet ~ NinTechNet Ltd. – 1.6.1
Divi Carousel: von DiviGear – 2.0.26
Divi Product Carousel: von DiviGear – 2.0.2
Divi Instagram Feed: von DiviPeople – 1.0.3
Divi MadMenu: von Ivan Chiurcci – 1.9.3
Divi Plus: von Elicus – 1.9.8
Divi Form Attachments: von FR Plugins – 1.0.1
Divi Social Plus: von DiviPeople – 1.0.8
Yoast Duplicate Post: von Enrico Battocchi & Team Yoast – 4.5
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: von Thomas Geiger – 1.20.2
Facebook for WooCommerce: von Facebook – 3.3.0
FileBird Lite: von Ninja Team – 6.4.2
Groups: von itthinx – 3.2.1
Woody code snippets (PHP snippets | Insert PHP): von Creative Motion
Will Bontrager Software
LLC  – 2.5.1

Maintenance Mode: von Lukas Juhas – 2.4.4
Manage Notification E-mails: von Virgial Berveling – 1.8.6
Object Cache Pro: von Rhubarb Group – 1.21.3
Redirection: von John Godley – 5.5.0
Rank Math SEO PRO: von Rank Math SEO – 3.0.75
Rank Math SEO: von Rank Math SEO – 1.0.232
SVG Support: von Benbodhi – 2.5.8
TP Product Image Flipper for Woocommerce: von TP Plugins – 1.0.7
Trusted Shops Easy Integration for WooCommerce: von vendidero – 2.0.3
Urgency Coupons for Mailing Lists PRO: von Dusty Sun – 2.9.5
User Role Editor: von Vladimir Garagulya – 4.64.2
Quantity Plus Minus Button for WooCommerce by CodeAstrology: von CodeAstrology Team – 1.1.7
Ajax add to cart for WooCommerce: von QuadLayers – 2.4.1
Category Slider for WooCommerce: von ShapedPlugin LLC – 1.4.20
Discount Rules PRO 2.0: von Flycart – 2.6.4
Discount Rules Core: von Flycart – 2.6.6
Payment Plugins for Stripe WooCommerce: von Payment Plugins
support@paymentplugins.com – 3.3.77

WooCommerce Advanced Product Labels: von BeRocket – 3.2.6.5
WooCommerce AJAX Cart: von Moises Heberle – 1.3.25
WooCommerce Conversion Tracking: von weDevs – 2.0.12
WooCommerce Amazon Pay: von Amazon Pay – 2.5.3
Germanized für WooCommerce Pro: von vendidero – 4.1.3
Germanized für WooCommerce: von vendidero – 3.18.4
WooCommerce Google Analytics Pro: von SkyVerge – 1.12.0
WooCommerce Order Status Manager: von SkyVerge – 1.15.2
WooCommerce PayPal Payments: von WooCommerce – 2.9.4
WooCommerce Smart Coupons: von StoreApps – 5.4.0
WooCommerce: von Automattic – 7.7.0 (Update auf Version 9.4.1 ist verfügbar)
WordPress Importer: von wordpressdotorg – 0.8.3
WP Product Feed Manager: von WP Marketing Robot – 2.11.1
WP Rocket | No .htaccess: von WP Rocket Support Team –
WP Rocket: von WP Media – 3.16.2.1
WP Sitemaps Config: von Kybernetik Services – 2.2.2
Sequential Order Numbers for WooCommerce: von WebToffee – 1.6.6

### Inactive Plugins (8) ###

Google Analytics for WooCommerce: von WooCommerce – 2.1.8
PayPal PLUS for WooCommerce: von Inpsyde GmbH – 2.2.1
Pinterest for WooCommerce: von WooCommerce – 1.4.12
vendidero Helper: von vendidero – 2.1.6
WP All Import - User Import Add-On Pro: von Soflyy – 1.1.8
WP All Import - WooCommerce Import Add-On Pro: von Soflyy – 4.0.0
WP All Import Pro: von Soflyy – 4.7.8
WP Downgrade | Specific Core Version: von Reisetiger – 1.2.6

### Dropin Plugins (4) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class (Drop-in)
maintenance.php: maintenance.php
object-cache.php: Object Cache Pro (Drop-in)

### Must Use Plugins (1) ###

Code Profiler (mu-plugin): von Jerome Bruandet – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: ✔

### WC Pages ###

Shop-Basis: #6 - /shop/
Warenkorb: ❌ Die Seite enthält nicht den [woocommerce_cart]-Shortcode oder woocommerce/cart-Block.
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/
Allgemeine Geschäftsbedingungen: #177 - /agb/

### Theme ###

Name: Divi
Version: 4.27.3
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: DE
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2024-11-19 14:48:58 +02:00
Options: ✔
Notes: 180
Onboarding: completed

### Action Scheduler ###

Canceled: 71
Oldest: 2024-10-24 23:27:36 +0000
Newest: 2024-11-08 22:59:05 +0000

Complete: 7.938
Oldest: 2024-10-21 22:45:40 +0000
Newest: 2024-11-19 08:31:16 +0000

Failed: 1.394
Oldest: 2023-03-28 08:55:32 +0000
Newest: 2024-10-30 14:28:44 +0000

Pending: 7
Oldest: 2024-11-20 02:49:40 +0000
Newest: 2024-11-20 22:50:14 +0000

### Status report information ###

Generated at: 2024-11-19 10:35:11 +02:00

</details>

**Comment by SydeKrystian** [comment]
Hello @manustaufi 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
