### ISSUE TITLE
Bug Report: PayPal Transmission Error Resulting in €0.01 Payment Requirement

### ISSUE THREAD

**Issue by Z003Y89** [woocommerce/woocommerce-paypal-payments#2814]
Bug Report: PayPal Transmission Error Resulting in €0.01 Payment Requirement
Description
Customers using PayPal to pay via WooCommerce are encountering an issue where they are required to pay €0.01 before proceeding with the actual transaction amount. This behavior confuses or deters customers from completing their purchases.

PayPal has indicated this is a transmission error originating from our side:

“Are you using a shop provider? If so, please contact them, as this seems to be a transmission error. Everything is fine on PayPal’s side; we only process the data that is transmitted to us.”

To Reproduce

Go to the WooCommerce store.
Add a product to the cart and proceed to checkout.
Select PayPal as the payment method.
Observe the prompt for an additional €0.01 payment.
Expected Behavior
The customer should be able to complete their transaction seamlessly by paying only the total purchase amount.

Actual Behavior
Before processing the intended payment, the customer is required to pay €0.01, which leads to confusion and failed transactions.

Screenshots
(Attach relevant screenshots that show the issue, such as checkout pages or error messages.)

Environment
WordPress Version: [e.g., 6.7]
WooCommerce Version: [e.g., 9.4.2]
PayPal Plugin Version: [e.g., WooCommerce PayPal Payments 2.9.4]
Browser: [e.g., Chrome Version 118.0, Safari Version 16]
Other Active Plugins:
Germanized for WooCommerce (Version 3.18.4)
WooCommerce Shipping & Tax (Version 2.8.3)
LiteSpeed Cache (Version 6.5.2)
WP Statistics (Version 14.11.3) (and others — complete list available upon request)
Debug Logs
Enable PayPal debug logs in WooCommerce, attempt to replicate the issue, and attach the logs here:

Go to WooCommerce > Settings > Payments > PayPal > Advanced.
Enable logging and attempt to complete a purchase.
Copy the relevant portion of the log related to the €0.01 issue.
Additional Context
The issue persists across multiple transactions.
PayPal confirmed no issues on their end.
No recent code modifications were made to checkout-related functionality.
The WooCommerce system report flagged outdated template files for the active theme (Bricks Child). Could this affect transmission?
System Status Report
(Paste the WooCommerce system status report here, redacting any sensitive information.)

Steps Taken to Debug
Verified API credentials and plugin configurations in WooCommerce PayPal settings.
Tested the issue with a default theme (e.g., Storefront) to rule out theme conflicts.
Temporarily disabled other plugins to check for conflicts.
Checked rounding, tax, and currency settings.
Ensured all plugins and WordPress core are updated.
Request for Assistance
Please advise if this issue is caused by a bug in the PayPal plugin or WooCommerce and suggest potential solutions. Let us know if additional details or tests are required.

**Comment by SydeKrystian** [comment]
Hello @Z003Y89 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
