### ISSUE TITLE
TRANSACTION FAILED error recieved when using PayPal express checkout with GPAY

### ISSUE THREAD

**Issue by eulands** [woocommerce/woocommerce-paypal-payments#2825]
When somebody try to pay with GPay , he recieving "TRANSACTION FAILED". 
This problem doesn't  occour when the client chooising ApplePAY. 
We tryed with a lot of type of cards.

**Comment by SydeKrystian** [comment]
Hello @eulands 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
