### ISSUE TITLE
Missing "PayPal buy-button" on check-out page when "Classic Cart button" is added to cart

### ISSUE THREAD

**Issue by sandraplant** [woocommerce/woocommerce-paypal-payments#2827]
### Describe the Bug
Currently I am using the classic checkout button for my shop solution. I would prefer to offer both solutions to my customers - the classic cart and the classic checkout button. I can not offer the classic cart button to my customers because on the check out page the "buy-button" is missing or not displayed. Instead a message is shown which states "You are currently paying with PayPal. Choose another payment method". In the past this was possible and the buy-button has been displayed properly.

### To Reproduce
1. For setting "Smart Button Locations" choose both options (Classic Checkout AND Classic Cart)
2. Save settings
3. Delete all caches
4. Visit the shop
5. Chose product and add it to the cart
6. Go to cart![Image](https://github.com/user-attachments/assets/50bb1cd5-8bc5-428c-a0fb-dd0eaf27d9fb)

7. Click on the Classic Cart button which lead to the PayPal login page
8. Authenticate at PayPal
9. Chose preferred payment method and go back to shop with relevant button
10. Scroll to the end of the cart page
11. Instead of the expected buy-button you will find the message which I described in the bug description

### Expected Behavior
Display buy-button in cart once you are redirected from PayPal instead of misleading message.

### Actual Behavior
Misleading message is displayed and customer can not proceed purchasing process

### Environment
 - WordPress Version 6.7.1 (Bug also existed in previous versions)
 - WooCommerce Version 9.4.2 (Bug also existed in previous versions)
 - Plugin Version 2.9.4 (Bug also existed in previous versions)
 - Browser Safari Desktop Version 17.4.1 and Safari iOS 17.6.1
 - Any other plugins installed:
Checkout Field Editor for WooCommerce
Elementor
Elementor Pro
Full Screen Menu for Elementor
Germanized für WooCommerce
Germanized für WooCommerce Pro
Germanized für WooCommerce: One Stop Shop
Google for WooCommerce
Limit Login Attempts Reloaded
Meta Tag Manager
OMGF
Site Kit by Google
Smart Slider 3 Pro
SVG Support
WooCommerce
WooCommerce PayPal Payments
WP Statistics
WP Statistics - Data Plus
WP-Optimize - Clean, Compress, Cache
Yoast SEO
Yoast SEO Premium

**Comment by SydeKrystian** [comment]
Hello @sandraplant 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
