### ISSUE TITLE
Pay Later messaging only displayed when smart button is active on the same page (199)

### ISSUE THREAD

**Issue by isabellainpsyde** [woocommerce/woocommerce-paypal-payments#283]
**The problem**
The Pay Later messaging is only displayed on the product page/cart/checkout when the PayPal buttons are activated for the same page. When no button is loaded for the site, then the messaging is hidden.
Example: Button for single product page is disabled, the messaging won’t load. But when the button from the mini cart is active, it would cause the messaging to load.

**Steps to reproduce**

- enable Pay Later messaging on the single product page
- disable PayPal button on single product page
- 
- disable PayPal button on the mini cart
- → the Pay Later banner will not be displayed on the single product page
- enable PayPal button on the mini cart
- → the Pay Later banner will be displayed on the single product page

**Expected behaviour**
The Pay Later banner should be loaded independent of whether or not the buttons are enabled on the same page.

**Workaround**
To view the messaging on the product page without the buttons enabled for the product page/mini cart, the button for the single product page could be activated in the plugin settings and then hidden with CSS:

.product #ppc-button {
display:none
}
Alternatively, enabling the button for the mini cart helps even when the theme does not provide a mini cart.

**Comment by benedict-w** [comment]
+1
