### ISSUE TITLE
PAYPAL ACTIVITIES ON PRODUCT AND MINI CART EMPTY YOUR CART

### ISSUE THREAD

**Issue by DPinotti-Upen** [woocommerce/woocommerce-paypal-payments#2830]
### Describe the Bug
With the activation of the PayPal buttons on the product cards and mini-carts this problem occurs:

- I add products to the cart
- I continue with the purchases
- in random navigation phases the cart is emptied.

By trying to disable PayPal on the single product and mini-cart, leaving it active only on checkout, the cart and purchase flow remains correct without emptying the cart.

 - WordPress Version 6.7.1
 - WooCommerce Version 9.4.2
 - Plugin Version 
 - all Browser

**Comment by SydeKrystian** [comment]
Hello @DPinotti-Upen 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
