### ISSUE TITLE
Google pay Error :  [googlepay | checkout] TRANSACTION FAILED

### ISSUE THREAD

**Issue by leccyril** [woocommerce/woocommerce-paypal-payments#2835]
### Describe the Bug

Google pay transaction failed

### To Reproduce

1 add a product 
2 fill form
3 try to pay with google pay

### Screenshots

![Image](https://github.com/user-attachments/assets/1cb76054-5c04-4c0e-bc22-175b68ee686c)

### Expected Behavior

Payment successful

### Actual Behavior

Payment failed

### Environment

 - WordPress Version : 6.7.1
 - WooCommerce Version : 9.4.2
 - Plugin Version : 2.9.4
 - Browser [e.g. Chrome, Safari] and Version : google desktop, google on mobile
 - Any other plugins installed

### Additional Details

Systrem report

`
### WordPress Environment ###

WordPress address (URL): https://blackedition-gold.com
Site address (URL): https://blackedition-gold.com
WC Version: 9.4.2
Legacy REST API Package Version: L’extension Legacy REST API n’est pas installée sur ce site.
Action Scheduler Version: ✔ 3.8.2
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 4 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.30
PHP Post Max Size: 512 Mo
PHP Time Limit: 360
PHP Max Input Vars: 2000000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.20-MariaDB
Max Upload Size: 512 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.4.2
WC Database Prefix: wp0s_
Taille totale de la base de données: 29.17MB
Taille de la base de données: 24.40MB
Taille de l’index: 4.77MB
wp0s_woocommerce_sessions: Données : 0.11MB + Index : 0.02MB + Moteur InnoDB
wp0s_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp0s_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp0s_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_actionscheduler_actions: Données : 0.06MB + Index : 0.11MB + Moteur InnoDB
wp0s_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_actionscheduler_logs: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp0s_bw_pricing_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp0s_e_events: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_mwai_filemeta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_mwai_files: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_options: Données : 5.06MB + Index : 0.14MB + Moteur InnoDB
wp0s_postmeta: Données : 11.45MB + Index : 2.30MB + Moteur InnoDB
wp0s_posts: Données : 5.38MB + Index : 0.13MB + Moteur InnoDB
wp0s_revslider_css: Données : 0.13MB + Index : 0.02MB + Moteur InnoDB
wp0s_revslider_layer_animations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_revslider_navigations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_revslider_sliders: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp0s_revslider_sliders7: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_revslider_slides: Données : 0.14MB + Index : 0.02MB + Moteur InnoDB
wp0s_revslider_slides7: Données : 0.17MB + Index : 0.02MB + Moteur InnoDB
wp0s_revslider_static_slides: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_sbi_feeds: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_sbi_feed_caches: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_sbi_instagram_feeds_posts: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_sbi_instagram_feed_locator: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_sbi_instagram_posts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_sbi_sources: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_term_relationships: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp0s_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_tinvwl_analytics: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_tinvwl_items: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_tinvwl_lists: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_usermeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
wp0s_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp0s_wc_admin_notes: Données : 0.06MB + Index : 0.00MB + Moteur InnoDB
wp0s_wc_admin_note_actions: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp0s_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_orders: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp0s_wc_orders_meta: Données : 0.06MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_order_addresses: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp0s_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_order_operational_data: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp0s_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp0s_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_wc_product_attributes_lookup: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_wc_product_download_directories: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_wc_product_meta_lookup: Données : 0.08MB + Index : 0.11MB + Moteur InnoDB
wp0s_wc_rate_limits: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp0s_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_yoast_indexable: Données : 0.13MB + Index : 0.09MB + Moteur InnoDB
wp0s_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp0s_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp0s_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp0s_yoast_seo_links: Données : 0.16MB + Index : 0.11MB + Moteur InnoDB

### Post Type Counts ###

adp-popup: 6
attachment: 281
cpt_layouts: 20
cpt_portfolio: 4
cpt_services: 6
cpt_testimonials: 4
custom_css: 1
customize_changeset: 9
elementor_library: 2
gift_card: 1
mc4wp-form: 1
nav_menu_item: 12
oembed_cache: 7
page: 23
points_image: 2
post: 47
product: 15
revision: 174
shop_coupon: 7
shop_order_placehold: 6
tribe_events: 15
tribe_organizer: 1
tribe_venue: 1
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Advanced Popups: par Code Supply Co. – 1.2.1
AI Engine: par Jordy Meow – 2.6.8
All-in-One WP Migration: par ServMask – 7.87
Boxtal Connect: par Boxtal – 1.3.0
Certishopping Social Reviews for Woocommerce: par Certishopping   – 4.2.9
Contact Form 7: par Takayuki Miyoshi – 6.0
Image Hotspot by DevVN: par Le Van Toan – 1.2.8
Elementor: par Elementor.com – 3.25.9
Smash Balloon Instagram Feed: par Smash Balloon – 6.6.1
Loco Translate: par Tim Whitlock – 2.6.14
MC4WP : Mailchimp pour WordPress: par ibericode – 4.9.19
Maintenance: par WebFactory Ltd – 4.15
Slider Revolution: par ThemePunch – 6.7.21
Stop User Enumeration: par Fullworks – 1.6.3
ThemeREX Addons: par ThemeREX – 2.31.2
ThemeREX Updater: par ThemeREX – 2.1.4
Premmerce Permalink Manager for WooCommerce: par Premmerce – 2.3.11
WooCommerce PayPal Payments: par WooCommerce – 2.9.4
WooCommerce: par Automattic – 9.4.2
Yoast SEO: par L’équipe Yoast – 23.9
WP Fastest Cache: par Emre Vona – 1.3.2
WPS Hide Login: par WPServeur
NicolasKulka
wpformation – 1.9.17.1

### Inactive Plugins (4) ###

Akismet Anti-spam: Spam Protection: par Automattic - Anti-spam Team – 5.3.5
TI WooCommerce Wishlist: par TemplateInvaders – 2.9.1
WooCommerce Stripe Gateway: par Stripe – 8.9.0
YITH WooCommerce Gift Cards: par YITH – 4.17.0

### Settings ###

Legacy API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 jours
Level threshold: –
Log directory size: 153 Ko

### WC Pages ###

Base de la boutique: #2331 - /boutique/
Panier: #2332 - /panier/ -  Contient le code court [woocommerce_cart]
Commander: #2333 - /validation/ -  Contient le code court [woocommerce_checkout]
Mon compte: #2334 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Frank Jewelry Store Child Theme
Version: 1.0
Author URL: https://themerex.net/
Child Theme: ✔
Parent Theme Name: Frank Jewelry Store
Parent Theme Version: 2.14.0
Parent Theme Author URL: http://themerex.net/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: FR
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: ✔
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: ✔
Google Pay: ✔
Fastlane: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store

Disabled Features: product-data-views
experimental-blocks
minified-js
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
blueprint
reactify-classic-payments-settings
use-wp-horizon

Daily Cron: ✔ Next scheduled: 2024-11-26 03:59:56 +00:00
Options: ✔
Notes: 64
Onboarding: completed

### Action Scheduler ###

Terminé: 101
Oldest: 2024-10-26 05:39:56 +0000
Newest: 2024-11-24 20:05:21 +0000

En attente: 3
Oldest: 2024-11-25 06:26:31 +0000
Newest: 2024-11-25 20:05:21 +0000

Échoué: 2
Oldest: 2024-10-22 04:26:00 +0000
Newest: 2024-11-20 16:29:03 +0000

### Status report information ###

Generated at: 2024-11-25 06:27:15 +00:00

Error console logs : 

  | error | @ | ConsoleLogger.js:63
-- | -- | -- | --
  | error | @ | PaymentButton.js:686
  | n | @ | GooglepayButton.js:660
  | (anonymous) | @ | GooglepayButton.js:725
  | f | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | rt | @ | GooglepayButton.js:2
  | a | @ | GooglepayButton.js:2
  | Promise.then |   |  
  | rt | @ | GooglepayButton.js:2
  | a | @ | GooglepayButton.js:2
  | Promise.then |   |  
  | rt | @ | GooglepayButton.js:2
  | a | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:717
  | (anonymous) | @ | GooglepayButton.js:748
  | f | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | rt | @ | GooglepayButton.js:2
  | a | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:754
  | (anonymous) | @ | GooglepayButton.js:745
  | f | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | rt | @ | GooglepayButton.js:2
  | a | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:2
  | (anonymous) | @ | GooglepayButton.js:654
  | value | @ | GooglepayButton.js:651
  | cd | @ | pay.js:309
  | b.onpaymentmethodchange | @ | pay.js:316

</span></div>

</details>

**Comment by SydeKrystian** [comment]
Hello @leccyril 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by kieron** [comment]
@leccyril did you figure this out?

**Comment by SydeKrystian** [comment]
Hello @kieron 

We are not aware of any widespread issues of this kind. If you encounter a similar problem, please don’t hesitate to contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), and we’ll be happy to investigate it for you.

Kind regards,
Krystian

**Comment by leccyril** [comment]
@kieron  i never had answer and it is still not working 
Some said if we hide shipping price until checkout it causes issue but i tried to uncheck same issue

**Comment by AlexPeasey** [comment]
@leccyril did you get this fixed or find a workaround since December? We've just encountered this issue and can't figure out any way to solve it.

**Comment by kieron** [comment]
> [@leccyril](https://github.com/leccyril) did you get this fixed or find a workaround since December? We've just encountered this issue and can't figure out any way to solve it.

Sadly not, both PayPal and woocommerce have been UTTERLY useless in their support too, passing the blame repeatedly, dragging tickets out for weeks, and just seemingly having no clue.

The most I got out of them is that it's due to a 'PAYER_ACTION_REQUIRED' issue, but again, were no more helpful than that.

**Comment by femiyb** [comment]
Hello @AlexPeasey 
Could you please reach out to us on our [dedicated support channel](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), so we can better assist you and look into what could be causing this issue?

Edit: Note that we are aware of this issue and a fix package is in works

Thanks.

**Comment by AlexPeasey** [comment]
@leccyril thanks for the quick response, kieron. That's incredibly frustrating! 

@femiyb thank you, I submitted a request a few minutes ago.
