### ISSUE TITLE
Google Kit & Paypal payments not compatible

### ISSUE THREAD

**Issue by dakisman** [woocommerce/woocommerce-paypal-payments#2839]
### To Reproduce

1. Go to 'Dashboard'
2. Click on 'Installed plugings'
3. Scroll down to Paypal Payments'

 - WordPress Version 6.7.1
 - WooCommerce Version 9.4.2
 - Plugin Version 2.9.4
 - Browser [e.g. Chrome, Safari] and Version Chrome Version 131.0.6778.86
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @dakisman 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
