### ISSUE TITLE
WooCommerce PayPal Payments plugin fails to update

### ISSUE THREAD

**Issue by pro-sport1** [woocommerce/woocommerce-paypal-payments#2842]
### Describe the Bug

WooCommerce PayPal Payments plugin fails to update. This seems to occur every time an update is attempted for this plugin.

### To Reproduce

Selecting 'update now' link on yellow information bar.

### Screenshots

![Image](https://github.com/user-attachments/assets/79854de5-4392-4774-961e-633015f0d3f9)

### Expected Behavior

Update to complete

### Actual Behavior

'updating' appears with red circling arrows indicating update in progress, but this has remained as the status for over 90 minutes this morning. Other updates have completed within seconds.

### Environment

 - WordPress Version 6.7.1
 - WooCommerce Version 9.4.2
 - Plugin Version 2.9.3
 - Browser Chrome
 - Any other plugins installed: Multiple

![Image](https://github.com/user-attachments/assets/4e314879-682c-4aea-a151-fc5d8d63b088)

**Comment by SydeKrystian** [comment]
Hello @pro-sport1 


We are not aware of any widespread issues with updating the WooCommerce PayPal Payments plugin. I recommend performing a full conflict test to rule out any potential issues with your theme or other plugins. Here's what you can do:

Temporarily activate the default Storefront theme.
Disable all other plugins except for WooCommerce and PayPal Payments.
Test the checkout process to see if the issue persists.
If the problem goes away, re-enable the plugins one by one to identify which one is causing the conflict.

Alternatively, you can manually download the latest update from [this link](https://github.com/woocommerce/woocommerce-paypal-payments/releases).

If the issue continues, for a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Kind Regards,

Krystian
