### ISSUE TITLE
Plugin sends negative sums to PayPal

### ISSUE THREAD

**Issue by dellachiaranew** [woocommerce/woocommerce-paypal-payments#2844]
### Describe the Bug

Using the WooCommerce Smart Coupons plugin, we added a voucher code for 50% discount and a free item. In the itemmeta the cost for the free item is correctly memorized as 0. When paying with paypal, the payment is processed and, at the end of the processing, the customer has the following error:
[CANNOT_BE_NEGATIVE](https://developer.paypal.com/api/rest/reference/orders/v2/errors/#CANNOT_BE_NEGATIVE)
: Must be greater than or equal to zero. If the currency supports decimals, only two decimal places are supported.

### To Reproduce

We can reproduce this only with the WooCommerce Smart Coupons plugins (a pro plugin). We are available to have a developer access to a staging copy of our site, if necessary.

### Screenshots
[`](https://sdmakeup.com/screenshot.jpg)

### Expected Behavior

Payment is submitted

### Actual Behavior

Payment is not submitted with the error: [CANNOT_BE_NEGATIVE](https://developer.paypal.com/api/rest/reference/orders/v2/errors/#CANNOT_BE_NEGATIVE)

### Environment

 - WordPress Version 6.7.1
 - WooCommerce Version 9.3.3
 - Plugin Version 2.9.4
 - Browser [e.g. Chrome, Safari] and Version any
 - WooCommerce Smart Coupons by StoreApp version 9.18.0

### Additional Details

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://sdmakeup.com
Site address (URL): https://sdmakeup.com
WC Version: 9.3.3
Legacy REST API Package Version: ✔ 1.0.4
Action Scheduler Version: ✔ 3.8.1
Log Directory Writable: ✔
WP Version: 6.7.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 80
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0+deb10u2
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (69) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.6.13
WPML SEO: by OnTheGoSystems – 2.1.0.1
Affiliate For WooCommerce: by StoreApps – 8.10.0 (aggiornamento alla versione 8.12.0 disponibile)
Free Shipping Bar: Amount Left for Free Shipping for WooCommerce: by WPFactory – 2.4.6
Better User Search: by Dale Higgs – 1.1.1
Nexi XPay: by Nexi SpA – 7.3.4
Click to Chat: by HoliThemes – 4.12
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 7.1.4
Contact Form 7 Multilingual: by OnTheGoSystems – 1.3.1
Contact Form 7: by Takayuki Miyoshi – 5.9.8
Disable payment method / COD fees for Order for WooCommerce: by PI Websolution – 1.1.7.64
Duplicate Page: by mndpsingh287 – 4.5.4
Emailchef for WooCommerce: by dueclic – 5.1
Emailchef: by dueclic – 2.9
Envato Market: by Envato – 2.0.12
Facebook for WooCommerce: by Facebook – 3.2.10
Flamingo: by Takayuki Miyoshi – 2.5
Force Regenerate Thumbnails: by Exactly WWW – 2.2.0
Google for WooCommerce: by WooCommerce – 2.8.6
OMGF: by Daan from Daan.dev – 5.9.1
Instagram Feed Pro Personal: by Smash Balloon – 6.3.2
Jetpack: by Automattic – 13.9.1
Salient WPBakery Page Builder: by Michael M - WPBakery.com | Modified by ThemeNectar – 7.8.1
OMGF Additional Fonts (Add-on): by Daan from Daan.dev – 1.2.11
Repeat Order for Woocommerce: by polyres – 1.3.3
reSmush.it Image Optimizer: by reSmush.it – 1.0.4
Safe SVG: by 10up – 2.2.6
Salient Core: by ThemeNectar – 3.0.1
Salient Home Slider: by ThemeNectar – 1.4.1
Salient Nectar Slider: by ThemeNectar – 1.7.7
Salient Portfolio: by ThemeNectar – 1.8
Salient Shortcodes: by ThemeNectar – 1.5.4
TikTok: by TikTok – 1.2.4
Toolset Types: by OnTheGoSystems – 3.5.2
Export & Import WPBakery Page Builder: by Tomiup – 1.0.2
W42 Custom order status: by Web42 Srl – 1.0
W42 Mobile category image: by Web42 Srl – 1.0
W42 Offer Price Cart: by Web42 Srl – 1.0
W42 Custom product tabs: by Web42 Srl – 1.0
W42 Profile data: by Web42 Srl – 1.0
W42 Review Images Popup: by Web42 Srl – 1.0
WC Exporter for Danea - Premium: by ilGhera – 1.6.4
WC Importer for Danea - Premium: by ilGhera – 1.6.2
WooCommerce Accordions: by Magnigenie – 1.2.3
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.2.13
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce Stripe Gateway: by Stripe – 8.8.2
Google Analytics for WooCommerce: by WooCommerce – 2.1.7
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce Multilingual & Multicurrency: by OnTheGoSystems – 5.3.8
WooCommerce PayPal Payments: by WooCommerce – 2.9.4
WooCommerce Product Reviews Pro: by SkyVerge – 1.19.2
WooCommerce Regions Pack: by TinyGiantStudios – 1.5
WooCommerce Smart Coupons: by StoreApps – 9.18.0
WooCommerce WishLists: by Element Stark – 2.3.3 (aggiornamento alla versione 2.3.4 disponibile)
WooCommerce: by Automattic – 9.3.3 (aggiornamento alla versione 9.4.2 disponibile)
Wordfence Security: by Wordfence – 8.0.1
Yoast SEO Premium: by Team Yoast – 21.6
Yoast SEO: by Team Yoast – 23.7
WP All Export Pro: by Soflyy – 1.9.1
WP Bulk Delete: by Xylus Themes – 1.3.2
WP Fastest Cache: by Emre Vona – 1.3.1
WP Mail Logging: by WP Mail Logging Team – 1.13.1
WP Mail SMTP: by WP Mail SMTP – 4.1.1
WP Migrate Lite: by WP Engine – 2.6.9
Widget per recensioni di Google: by Trustindex.io  – 12.1.2
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.9
WPML String Translation: by OnTheGoSystems – 3.2.14
Yoast SEO: WooCommerce: by Team Yoast – 15.9

### Settings ###

Legacy API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: IT
WooCommerce currency supported: ✔
Advanced Card Processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: ✔
PayPal Vault enabled: –
ACDC Vault enabled: –
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: –
Subscriptions Mode: Disabled
PayPal Shipping Callback: –
Apple Pay: –
Google Pay: –
Fastlane: –

### Impostazioni Smart Coupons ###

⠀* Numero di coupon da mostrare: 5
⠀* Numero di caratteri nel codice del coupon auto-generato: 7
⠀* Stato di ordine valido per la generazione automatica di coupon: Processing | Completed
⠀* Cancellazione automatica: ❌ No
⠀* Email coupon: ✔ Yes
⠀* Stampa coupon: ✔ Yes
⠀* Vendi carte regalo a prezzo inferiore?: ❌ No
⠀* Usa la carta regalo applicata all'ordine della prima iscrizione per avere rinnovi successivi finché il credito non si azzera: ✔ Yes
⠀* Gli ordini di rinnovo non dovrebbero generare coupon anche se includono un prodotto che ne genera: ❌ No
⠀* Permetti l'invio di coupon ad altri: ✔ Yes
⠀* Permetti l'invio dilazionato dei coupon?: ✔ Yes
⠀* Combina email: ❌ No
⠀* Email coupon autogenerati: ✔ Yes
⠀* Email coupon combinati autogenerati: ❌ No
⠀* Email di avviso: ✔ Yes
⠀* Include le tasse nell'importo della carta regalo generata: ✔ Yes
⠀* Sottrai il credito o il regalo prima di calcolare le tasse: ❌ No
⠀* Lo sconto della carta regalo è tasse incluse: ✔ Yes
⠀* Abilita le imposte: ✔ Yes
⠀* Prezzi inseriti con imposte incluse: ✔ Yes
⠀* Mostra i prezzi nel negozio: ✔ Incl
⠀* Visualizza i prezzi nel carrello e nel riepilogo dell'ordine: ✔ Incl
⠀* Arrotondamento: ✔ Yes
⠀* Mostra il totale delle imposte: Single
⠀* Abilita l'uso di codici promozionali: ✔ Yes
⠀* Calcola sconti codici sequenzialmente: ❌ No
⠀* Endpoint account > Coupon: wc-smart-coupons
⠀* WooCommerce Account Connected: ✔ Yes

### Status report information ###

Generated at: 2024-11-26 19:17:59 +01:00
`
</details>

**Comment by SydeKrystian** [comment]
Hello @dellachiaranew 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
