### ISSUE TITLE
Warnings after install

### ISSUE THREAD

**Issue by millerf** [woocommerce/woocommerce-paypal-payments#2847]
![Image](https://github.com/user-attachments/assets/e5f2c649-d03b-4f20-9c6c-4aebe0151743)
### To Reproduce

1. Launch a wp-env 
2. Activate WooCommerce
3. Install plugin
4. Notice the warning everywhere in the admin
5. I believe it actually prevents activating the plugin because the header prevents a redirection to happen. 

Warning reads:
```
Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6114 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-admin/includes/misc.php on line 1438 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-includes/functions.php on line 7137 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-admin/admin-header.php on line 9 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-includes/option.php on line 1715 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-includes/option.php on line 1716
``` 

### Screenshots

![Image](https://github.com/user-attachments/assets/1f2d7cf3-2c52-4280-b0c6-db5fb39b6d81)

![Image](https://github.com/user-attachments/assets/fc47e378-8c14-4c65-aecd-0d206e5fb346)

### Expected Behavior

No warnings
### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @millerf 

The fix for this issue is already available for testing. You can download it from the following link: [Download Fix](https://drive.google.com/uc?id=1cn4NR-aG1AJi4zyEYCbVAM_V4QX26UnQ)

Alternatively, if you prefer to wait until officially released you can disable debugging or even better use [this code snippet](https://developer.woocommerce.com/2024/11/11/developer-advisory-translation-loading-changes-in-wordpress-6-7/) to suppress the notice:

`add_filter( 'doing_it_wrong_trigger_error', '__return_false' );`

Currently, the fix is undergoing acceptance testing and should be officially released soon.

Kind Regards,
Krystian
