### ISSUE TITLE
I can't save my changes

### ISSUE THREAD

**Issue by koby57** [woocommerce/woocommerce-paypal-payments#2851]
Hello,

I can't save my changes ! I want to retire the case "BOUTIQUE" and when i wanna save it didn't work ! 
please help me![Image](https://github.com/user-attachments/assets/ab75d25e-8e60-46e2-87f8-c323f9949855)

**Comment by SydeKrystian** [comment]
Hello @koby57 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
