### ISSUE TITLE
Making billing_company required dynamically using woocommerce_checkout_fields not working

### ISSUE THREAD

**Issue by bogdanJoca** [woocommerce/woocommerce-paypal-payments#2853]
### Describe the Bug

I use this code to make billing_company required if there are dangerous products in cart, otherwise its optional, and its working for every Payment method except PayPal

`add_filter('woocommerce_checkout_fields', 'modify_billing_company_field_based_on_dangerous');

function modify_billing_company_field_based_on_dangerous($fields) {
    $make_required = false;

    foreach (WC()->cart->get_cart() as $cart_item) {
        $product_id = $cart_item['product_id'];

        $custom_field_value = get_post_meta( $product_id, 'dangerous', true );

        if ( $custom_field_value) {
            $make_required = true;
            break;
        }
    }

    if ($make_required) {
        $fields['billing']['billing_company']['required'] = true;
    }

    return $fields;
}`
### To Reproduce

1. Put my code in functions.php, change $custom_field_value to true
2. Go to checkout and select PayPal
3. Leave billing_company empty
3. Purchase with PayPal

### Expected Behavior

I should be stopped from buying with PayPal if the billing field is empty, and be shown a notification Company Name is required.
### Actual Behavior

The PayPal Popup opens when the billing_company is empty.

### Environment

 - WordPress Version 6.3.5
 - WooCommerce Version 8.2.3
 - Plugin Version 1.0.48
 - Any Browser

**Comment by SydeKrystian** [comment]
Hello @bogdanJoca 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
