### ISSUE TITLE
All item's SKUs stuffed in first item SKU

### ISSUE THREAD

**Issue by buddy-kilo** [woocommerce/woocommerce-paypal-payments#2857]
### Describe the Bug

First item in table (in paypal order details) contains all the next item SKUs... Please see screenshot.

 - WordPress Version (6.7.1)
 - WooCommerce Version (9.4.2)
 - Plugin Version (2.9.4)

![Image](https://github.com/user-attachments/assets/2d798a2b-a82d-4e35-bd87-7a30bc76a9af)

**Comment by SydeKrystian** [comment]
Hello @buddy-kilo 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
