### ISSUE TITLE
Notice:: Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by lordspace** [woocommerce/woocommerce-paypal-payments#2862]
### NOTICE

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /var/www/vhosts/example.com/htdocs/wp-includes/functions.php on line 6114

### To Reproduce

Just activate the plugin.

WP v6.7.1
woocommerce v9.4.2 
woocommerce-paypal-payments v2.9.4

**Comment by SydeKrystian** [comment]
Hello @lordspace 

We have made updates to address this, as noted in the PR here: https://github.com/woocommerce/woocommerce-paypal-payments/pull/2816

Please test the following version and let us know if the problem persists: [2.9.5-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.5-rc1).

If the issue continues, for a prompt and detailed response, we kindly ask that you create a new issue on our [GitHub repository](https://github.com/woocommerce/woocommerce-paypal-payments/issues). When creating the issue, please include the relevant details, including a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us investigate and resolve the issue more quickly.

Kind Regards,
Krystian
