### ISSUE TITLE
Function _load_textdomain_just_in_time loading at wrong time

### ISSUE THREAD

**Issue by compusolver** [woocommerce/woocommerce-paypal-payments#2864]
### Describe the Bug

Customers can't buy from my woocommerce site.  I get this error in debug log:   PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-paypal-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /home/customer/www/hanks-guitar-shop.com/public_html/wp-includes/functions.php on line 6114

### To Reproduce

Try to put any product into the cart and you get "There has been a critical error on this website."

### Environment

 - WordPress Version  6.7.1
 - WooCommerce Version 9.4.2
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version - all browsers.
 - Any other plugins installed - same results with new site with only woocommerce and necessary plugins.

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @compusolver 


We have made updates to address this, as noted in the PR here: https://github.com/woocommerce/woocommerce-paypal-payments/pull/2816

Please test the following version and let us know if the problem persists: [2.9.5-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.5-rc1).

If the issue continues, for a prompt and detailed response, we kindly ask that you create a new issue on our [GitHub repository](https://github.com/woocommerce/woocommerce-paypal-payments/issues). When creating the issue, please include the relevant details, including a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us investigate and resolve the issue more quickly.

Kind Regards,
Krystian
