### ISSUE TITLE
Translation loading trigger too early -- woocommerce_before_calculate_totals

### ISSUE THREAD

**Issue by DBziggy** [woocommerce/woocommerce-paypal-payments#2865]
I defined 2 constants in wp-config.php
API_CUSTOMER_NAME
API_PASSORD

In my functions.php file I added the following:

add_action( 'woocommerce_before_calculate_totals', 'bis_recalc_price' );
function bis_recalc_price( $cart_object ) {
    $customerArray=api_authCustomer(API_CUSTOMER_NAME,API_PASSORD);  <<< This fails with  PHP Fatal error:  Uncaught Error: Undefined constant "API_CUSTOMER_NAME" 
...
}

The description says "Translation loading for the <code>wf-address-autocomplete-validation</code> domain was triggered too early"

I use the same sequence in most of my other functions and have had no problem.  It only happens in this function and not on every page load.

**Comment by BlutVampir** [comment]
Please fix this asap.

translations should be loaded with the init action, not with the load of the plugin!

like that:

add_action( 'init', 'wpdocs_load_textdomain' );
function wpdocs_load_textdomain() {
	load_plugin_textdomain( 'wpdocs_textdomain', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' ); 
}

**Comment by DBziggy** [comment]
is the problem that I am executing:

add_action( 'woocommerce_before_calculate_totals', 'bis_recalc_price' );
function bis_recalc_price( $cart_object ) {
...
}
within my functions.php or that some plugin is prematurely executing the woocommerce_before_calculate_totals hook.

If it is me then where do I put it?

To be clear:  I do not get a notice.  It is a hard fail and it is not in a plugin, it is in the functions.php.

**Comment by InpsydeNiklas** [comment]
Hi folks, please give it a try with the new [2.9.5-rc1 pre-release](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.5-rc1) version and let us know if that resolves the notice for you. Thank you!
Note, there could potentially still be other plugins with this notice. You can find more details and other potential workarounds in [this blog post](https://developer.woocommerce.com/2024/11/11/developer-advisory-translation-loading-changes-in-wordpress-6-7/).
