### ISSUE TITLE
Advanced Card Processing Not Showing When Using Woocommerce Blocks

### ISSUE THREAD

**Issue by mwnets** [woocommerce/woocommerce-paypal-payments#2873]
The Advanced Card Processing payment option does not show when using the Checkout block in Woocommerce Blocks. It shows when a user is logged in, but does not show for guests. 

### To Reproduce

Just add the Advanced Card Processing option when using  Checkout block in Woocommerce Blocks

### Environment

 - WordPress Version: WordPress 6.7.1
 - WooCommerce Version: Version 9.4.3
 - Plugin Version: Version 2.9.4
 - Browser [e.g. Chrome, Safari] and Version: Happens on all browsers
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @mwnets 

We have made updates to address such issues. Please test the following version and let us know if the problem persists: [2.9.5-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.5-rc1).

If the issue still occurs, for a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). When you contact them, please include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us resolve the issue more quickly.

Kind Regards,
Krystian
