### ISSUE TITLE
Smart button & Pay Later messaging disappear on the cart page after changing shipping method (163)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#288]
**The problem**
When changing the shipping method on the cart page, the PayPal button disappears until a site refresh or AJAX reload.
Any AJAX reload in the cart page will lead to the Pay Latter banner disappearing until the site was refreshed.

**Steps to reproduce**
- set up a webshop with at least 2 shipping methods and at least 1 product
- set up PayPal Payments as a payment method & enable button on the cart page
- add a product to the cart and visit the cart page
- change shipping in the cart from one to the other option --> paypal button disappears until site reload
- change the item total and hit “update cart” to make the Pay Later messaging disappear

![gif_recording2](https://user-images.githubusercontent.com/78153894/135078911-3cc7239b-b9fd-455a-b340-9be9bb58cfef.gif)

**Expected behaviour**
When changing the shipping method, the button should stay hooked.
Also, any AJAX update on the site should cause the Lay Later messaging to be updated.

**Possible cause**
interestingly, applying the button to a different hook may cause it to not disappear upon changing shipping methods:
hook the cart page buttons after the cart to prevent it from disappearing upon changing shipping options (might require additional CSS for placement) 
The button seemingly only disappears when hooked into woocommerce_proceed_to_checkout or woocommerce_after_cart_totals or some others, but woocommerce_after_cart causes the button to not disappear.

**Workaround**
interestingly, applying the button to a different hook may cause it to not disappear upon changing shipping methods:
hook the cart page buttons after the cart to prevent it from disappearing upon changing shipping options (might require additional CSS for placement) 
The button seemingly only disappears when hooked into woocommerce_proceed_to_checkout or woocommerce_after_cart_totals or some others, but woocommerce_after_cart causes the button to not disappear.

**Comment by nicdwilson** [comment]
4959278-zen
