### ISSUE TITLE
PayPal Button don't load on Safari

### ISSUE THREAD

**Issue by stigazzi** [woocommerce/woocommerce-paypal-payments#2880]
### To Reproduce

1. Go to checkout using Safari on MacOS or iOS
2. Browser Console shows: 

Fetch API cannot load https://www.paypal.com/sdk/js?client-id=AVoBuSKYXe_hdC8073U3OQIXCHWoER4VQf4s7Nrt1P38KCiQAIqOCrwrEXsR_G1KgOk-1xrdFMs9dzGM&currency=EUR&integration-date=2024-11-05&components=buttons,funding-eligibility,buttons,fastlane&vault=false&commit=true&intent=capture&disable-funding=bancontact,blik,eps,ideal,mybank,p24,venmo,trustly,paylater&enable-funding=venmo&locale=de_DE due to access control checks.

### Expected Behavior

Buttons should load

### Actual Behavior

Buttons don't load

### Environment

 - WordPress Version 6.7.1
 - WooCommerce Version 9.4.3
 - Plugin Version 2.9.4
 - Safari Version 18.1.1 (20619.2.8.11.12)

**Comment by SydeKrystian** [comment]
Hello @stigazzi 

It seems that the issue may be related to Apple Private Relay blocking certain scripts. I recommend disabling Private Relay in your settings and testing again to see if that resolves the issue.

If the problem persists, for a more detailed and prompt response, please reach out to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). When you contact our support team, kindly include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of the issue more quickly.

We’ll be closing this GitHub issue for now. However, once you reach out to our support team, they will be ready to assist you further.

Kind Regards,
Krystian
