### ISSUE TITLE
Subscription plan issue

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#2887]
We found that the problem lies between the WooCommerce Subscriptions plugin and the WooCommerce PayPal plugin. Issue Description:

The PayPal checkbox works as expected when selecting the "Subscription Review" option for a 1-year subscription. Please refer screenshot:- https://capture.dropbox.com/zuzz0rbJMK9Y58vY
However, when selecting 2 or 3 years, the subscription is not being created on PayPal, indicating a conflict between the two plugins.
We have also checked the log.

 Please refer screenshot:- https://capture.dropbox.com/SJ0hBFe2Swi0QZGn As per the screenshot WooCommerce Subscriptions plugin is sending a request but due to a parameter mismatch of the year PayPal have rejected the request. 

Can you please help us on this?

**Comment by SydeKrystian** [comment]
Hello @Dhavalbe2m 

Thank you for bringing this to our attention and providing the details.

We’re aware of this and plan to address it in an upcoming update. While it may not be fixed in the very next update, it will likely be resolved in the update after that.

Kind Regards,  

Krystian
