### ISSUE TITLE
Order lines doubled (268)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#289]
The problem
Some users experience an issue that causes the order lines to appear twice after the payment.
The order total is correct, but the subtotal does not match.

Examples:
![image](https://user-images.githubusercontent.com/78153894/135079631-df67e022-7850-495c-ae8c-03bcdedbb417.png)
![image](https://user-images.githubusercontent.com/78153894/135079720-f43c69b2-bd2f-4d99-83fb-2a605f4d977e.png)

Possible cause
Version 1.5.1 changed the default behaviour for subtotal mismatch: PCP-195 (Plugin conflict blocking line item details). This may now be causing the behaviour of doubled order lines. Adding a setting as described in PCP-255 (add toggle for Subtotal Mismatch Behavior) may help prevent issues, depending on what behaviour is desired.

**Comment by InpsydeNiklas** [comment]
This issue has already been resolved a while back.
