### ISSUE TITLE
Payment decline on 2.9.5

### ISSUE THREAD

**Issue by GML-yo** [woocommerce/woocommerce-paypal-payments#2903]
### Describe the Bug

Customer can't pay due to paypal reject

{"name":"UNPROCESSABLE_ENTITY","details":[{"issue":"INSTRUMENT_DECLINED","description":"The instrument presented  was either declined by the processor or bank, or it can't be used for this payment."}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"9858b622cdb32","links":[{"href":"https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INSTRUMENT_DECLINED","rel":"information_link","method":"GET"},{"href":"https://www.paypal.com/checkoutnow?token=3GF06109C1556890M","rel":"redirect","method":"GET"}]}","response":{"code":422,"message":"Unprocessable Entity"}

All payment bug despite 2.9.5 upgrade. Allways with same error message.

No problem with old versions (about 1300 orders since 2024/07)

### Environment

 - WordPress Version : 6.7.1
 - WooCommerce Version : 9.4.3
 - Plugin Version : 2.9.5
 - Browser [e.g. Chrome, Safari] and Version : all
 - Any other plugins installed

**Comment by SydeKrystian** [comment]
Hello @GML-yo 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
