### ISSUE TITLE
not_enabled_to_vault_payment_source

### ISSUE THREAD

**Issue by Badger2024** [woocommerce/woocommerce-paypal-payments#2918]
### To Reproduce

1. Go to CHECKOUT after adding a product to CART
2. Click on PAYPAL button
3. Screen resets itself to top of page and displays above error.
4. Displayed error: NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance.
5. See Error: ![Image](https://github.com/user-attachments/assets/12907146-8a34-4422-a315-d23a04b21392)

### Expected Behavior

PAYPAL payment request to be processed.

### Actual Behavior

Transaction is declined due to NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @Badger2024 

Please follow the step-by-step instructions below:  
  
1. Navigate to the PayPal Payments plugin settings.  
2. Go to the Connection tab, which is the main card in the plugin settings.  
3. Scroll to the bottom of this tab, where you will find a "Clear Now" button.  
4. Clicking this button will clear the plugin settings from your database.  
5. Attempt to onboard your plugin again.  
  
Please let us know the outcome of these troubleshooting steps. If the issue persist after this, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
