### ISSUE TITLE
Advertising checkboxes for paypal pay later won't uncheck. I don't want pay later on my site and I definitely don't want free advertising for it there. Tried clearing cache, turning off hack guardian, etc. Storefront theme

### ISSUE THREAD

**Issue by wgailey** [woocommerce/woocommerce-paypal-payments#2923]

**Comment by SydeKrystian** [comment]
Hello @wgailey 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by wgailey** [comment]
Its not a support request I already fixed the problem on my end, its a bug submission but I understand if you aren't up to coding...

**Comment by SydeKrystian** [comment]
Hello @wgailey 

We handle these kinds of issues primarily through support rather than as bug submissions. If you'd like, you can explore this board to see examples of how bug reports are typically structured, as there are plenty of references [available](https://github.com/woocommerce/woocommerce-paypal-payments/issues).

If anything similar arises in the future, please don’t hesitate to reach out to us via support. Thank you for your understanding!

Kind Regards,
Krystian

**Comment by wgailey** [comment]
Its not a support request I already fixed the problem on my end, its a bug submission but I understand if you are up to coding...

**Comment by wgailey** [comment]
> Hello @wgailey 
> 
> We handle these kinds of issues primarily through support rather than as bug submissions. If you'd like, you can explore this board to see examples of how bug reports are typically structured, as there are plenty of references [available](https://github.com/woocommerce/woocommerce-paypal-payments/issues).
> 
> If anything similar arises in the future, please don’t hesitate to reach out to us via support. Thank you for your understanding!
> 
> Kind Regards,
> Krystian

Look its not that I dont understand you purposely put this bug in to scam people into advertising for a crap service for free. Its just that I wanted to put a name to who was running the scam, thanks again!
