### ISSUE TITLE
Unable to save edits to Title and Description in Standard Payments tab

### ISSUE THREAD

**Issue by DrByte234** [woocommerce/woocommerce-paypal-payments#2929]
### Describe the Bug

Goal: Edit Title and/or Description in Standard Payments Tab

### To Reproduce

1. Go to'Settings/Standard Payments'
2. Click on 'Title'
3. Scroll down to …'Save Changes'
4. See error: Hangs after clicking 'Save Changes'

### Expected Behavior
After changing Title and Description and clicking 'Save changes'. I expect the save process to complete and the Title and Description to be updated to reflect the changes made.

### Actual Behavior
After changing Title and Description and clicking 'Save changes', the "save" process does not complete and the Title and Description is not updated to reflect the changes made.

### Environment

 - WordPress Version 6.7.1
 - WooCommerce Version 9.4.3
 - Plugin Version 2.9.5
 - Browser [e.g. Chrome, Safari] and Version : Edge: 131.0.2903.99 
 - Any other plugins installed: Tested using only woocommerce and elementor pro all other plugins disabled.

### Additional Details
Only using Standard Payments, only displayed on Checkout. No advanced features are used. The plugin is set to have PayPal and Venmo links available at checkout only. I must be able to edit the Standard Payments Title and Description fields or I will be forced to use a different plugin.

I have tested in staging site, removing all plugins other than woocommerce and elementor pro. I have cleared all associated cache's, worked with Kinsta (our host) to verify that server resources are correct and no issues are showing on the server logs of any related problems.

I also tested by removing woocommerce paypal payments and installing Payment Plugins for PayPal WooCommerce and was able to edit the Title and Description of the Standard Payments Tab with no problem saving. I then disabled Payment Plugins for PayPal WooCommerce and enabled woocommerce paypal payments and the problem returned, indicating that the problem is specific to woocommerce paypal payments.

I will be forced to remove woocommerce paypal payments if I cannot change the Title and Description. Please advise if this issue has been encountered before and if so, what can be done to resolve it.

Thank you

</details>

**Comment by SydeKrystian** [comment]
Hello @DrByte234 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
