### ISSUE TITLE
Transactions cannot be voided

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#293]
### Problem
When the transaction is an authorization, there is "Order Action" to capture. There is also option to "Refund". Selecting Refund will cause an API error as you are unable to refund an authorization via PayPal.

If a transaction is an authorization, then it cannot be refunded. It can only be captured or voided.

### Proposed Solution

When transaction is an authorization, replace "Refund" option with "Void" option. Documentation to void an authorization can be found here: https://developer.paypal.com/docs/api/payments/v2/#authorizations_void

**Comment by Dinamiko** [comment]
Fixed in #299.
