### ISSUE TITLE
Payment not possible in pay for order form because of terms checkbox missing (371)

### ISSUE THREAD

**Issue by snandos** [woocommerce/woocommerce-paypal-payments#294]
### Problem
The PayPal payment cannot be startet in the pay for order form because this plugin checks for the _terms_ checkbox which might not be shown in combination with third party plugins.

### To reproduce
1. Use Plugin like "WooCommerce Germanized" and "WooCommerce Germanized Pro" which has a checkbox management where _terms_ checkbox is disabled or not shown on the pay for order form.
2. Try to pay an order via pay for order form.
3. Error "Please read and accept the terms and conditions to proceed with your order." occurs without having seend any _terms_ checkbox.

### Expected behavior
Validation of terms checkbox should only be triggered if checkbox was shown - like in the WooCommerce core.

**Environment**
 - WordPress 5.7.3
 - WooCommerce 5.5.1
 - WooCommerce PayPal Payments Plugin Version 1.6.0
 - WooCommerce Germanized and WooCommerce Germanized Pro

**Comment by Dinamiko** [comment]
Hi @snandos,

Just to let you know that we finally merged your PR change (I created a new one becasue the other was a bit outdated) so this is going to be included in the upcoming release, thanks and sorry for the delay.
