### ISSUE TITLE
weird issue with paypal plugin on checkout

### ISSUE THREAD

**Issue by anzgar01** [woocommerce/woocommerce-paypal-payments#2946]
### Describe the Bug

Paypal buttons are not displayed, instead there is an error message.

### To Reproduce

1. Go to https://wp-spezialist24.de/produkt/wordpress-wartung-premium/
2. Check the checkbox and fill some text in the textfield.
3. Click on add to cart ("In den Warenkorb")
4. Click on "Weiter zum Bezahlen"
5. See error. Alternatively if there is no error shown, go to chrome developer console, there are several paypal javascript errors

### Expected Behavior

Paypal buttons showing up for both Express Checkout and standard checkout.

### Actual Behavior

No paypal buttons visible.

### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.5.1
 - Plugin Version: 2.9.5
 - Browser [e.g. Chrome, Safari] and Version: Chrome latest version
 - yith subscriptions

<details><summary>System status</summary>

</details>

**Comment by SydeKrystian** [comment]
Hello @anzgar01 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
