### ISSUE TITLE
"Function _load_textdomain_just_in_time was called incorrectly" in version 2.9.5

### ISSUE THREAD

**Issue by justdave** [woocommerce/woocommerce-paypal-payments#2947]
### Describe the Bug

The following error message is appearing in the error logs every time the site is accessed:

```
Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>woocommerce-paypal-payments</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in wp-includes/functions.php on line 6114
```

Note that I currently have version 2.9.5 installed, which supposedly fixed this issue according to #2816, and my logs show that it updated to this version on December 10, however I am still seeing it on December 21st. I have uninstalled and reinstalled it just to make sure I didn't get a partial update somehow.

### To Reproduce

1. Access the website or run any WPCLI command
2. Look at the debug.log if it's enabled, or the webserver's error log if not. (or the console output if you ran WPCLI)
3. See error

### Expected Behavior

There should not be an error logged.

### Actual Behavior

The error is logged.

### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.5.1
 - Plugin Version: 2.9.5
 - Browser [e.g. Chrome, Safari] and Version: n/a because it's a server-side issue
 - Any other plugins installed
   - Contact Form 7
   - Contact Form CFDB7
   - Easy Updates Manager
   - Events Tickets Plus
   - The Events Calendar
   - WordFence Security

**Comment by SydeKrystian** [comment]
Hello @justdave 

As the problem persists with 2.9.5, we recommend reaching out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). When contacting them, please include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will allow us to investigate and resolve the issue more efficiently.

Thank you for your patience and understanding. Our team will be ready to assist you further.

Kind Regards,
Krystian
