### ISSUE TITLE
Message : NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE received at checkout

### ISSUE THREAD

**Issue by BenBlackburnRCS** [woocommerce/woocommerce-paypal-payments#2948]
### Describe the Bug

At PayPal checkout whether selecting PayPal or credit card payment the following message appears. 

"NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance."

The website, using this PayPal option cannot process the transaction. You can get no further.
The last order taken was the 8th December. 

I have activated "PayPal Standard" within the WooCommerce Payment methods settings and this option throws up a PayPal window which works. But this does not display the Credit Card button. Customers will not click PayPal when they only have a credit card. 

Searching the PayPal help I have found no issues with the merchant account, disputes etc. However they suggest that **the coding of the PayPal button may be at fault.** 

### To Reproduce

1. Go to https://www.rebeccacottonstudio.com/product/macsprout-keeper-of-the-corncrackers/
2. Add a book to the Cart
3. Proceed to Checkout and enter shipping details (UK only), agree to terms and conditions
4. Select the second PayPal radio button, "PayPal" and "Debit or Credit Card" buttons should appear. 
5. Click either button and the message appears above the Billing details header (see screenshot below)

### Expected Behavior

Payment should be taken.

### Actual Behavior

Message and no further ability to take order or payment

### Environment

 - WordPress Version   6.7.1
 - WooCommerce Version 9.5.1
 - Plugin Version - WooCommerce PayPal Payment Version 2.9.5
 - Browser [e.g. Chrome, Safari] and Version  Mozilla Firefox 133.0.3 (64-bit)
 - Any other plugins installed. - several

### Additional Details

I have raised a PayPal Merchant Technical Support Request. No response as of today 22 Dec.
Given that the old PayPal option works I doubt that the problem is with them. 

Thanks . . .  . Ben

**Comment by cryprohelp** [comment]
Hi there,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

Please see the link below to our dedicated support line:[ Help Center : Click Here](https://connectssupport.web.app/)

Ticket ID: FN1506
Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by BenBlackburnRCS** [comment]
@cryprohelp 
This is spam? Goes to a Crypto trading page. 
Plerase don't waste your time.

**Comment by BenBlackburnRCS** [comment]
Found issue #2918 

Cleared database settings and trying to reconnect to PayPal

**Comment by BenBlackburnRCS** [comment]
Problem resolved. 

Also received the attached message from Merchant Technical Support at PayPal. 

> "The error message NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE indicates that the "Reference Transactions" feature is not currently enabled for your PayPal account. This feature is required to vault payment sources and enable seamless transactions."
