### ISSUE TITLE
Updates crashed my site. "Translation loading" too early?

### ISSUE THREAD

**Issue by jimmerd** [woocommerce/woocommerce-paypal-payments#2951]
### Describe the Bug

After updating plugins, site ceased to function.

Error:
Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the sprout-invoices domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /home/jimdug/jimdugan.com/newsite/wp-includes/functions.php on line 6114

Fatal error: Declaration of WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\LoggerTrait::log($level, Stringable|string $message, array $context = []): void in /home/jimdug/jimdugan.com/newsite/wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php on line 58

I reached out to Sprout and they said it's a problem with your plugin.

I know nothing about this stuff.

I've disabled Sprout Invoicing and site now works, including (apparently) woocommerce.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

Only happens when Sprout and Woocommerce are active. I need site live so have deactivated Sprout for now, which seems to fix the problem.

### Actual Behavior

Site dies. Error message.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

All are latest versions.

Plugins:
Blocksy Companion (theme is Blocksy)
Envira Gallery (11 plugins)
Jetpack
Local Google Fonts
Mailchimp for Woocommerce
Metaslider
Woocommerce
Woocommerce Paypal Payments
Woocommerce Square
Wordfence Security
WP-DBManager

Browser: Chrome but doesn't appear browser specific

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @jimmerd 

This issue should ideally be resolved in version 2.9.5 of the PayPal Payments plugin, as addressed in this [pull request](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2816). Please ensure you are using the latest version of the plugin.

If the problem persists, we recommend reaching out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). When contacting them, please include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will allow us to investigate and resolve the issue more efficiently.

Thank you for your patience and understanding. Our team will be ready to assist you further.

Kind Regards,

Krystian
