### ISSUE TITLE
subscriptions vaulting - There has been a critical error on this website.

### ISSUE THREAD

**Issue by taxtec** [woocommerce/woocommerce-paypal-payments#298]
Hi, we try use woocommerce subscriptions. We checked the box 
-  Enable saved cards and subscription features on your store. To use vaulting features, you must enable vaulting on your account. 

we are in Germany. 
Wordpress 5.8.1
WooCommerce PayPal Payments 1.6.0
WooCommerce Subscriptions 3.1.5

After checking the Box, the website shows: There has been a critical error on this website.

unchecking the box, will not solve the problem. Only restore of backup. 

we are in Germany. 
Wordpress 5.8.1
WooCommerce PayPal Payments 1.6.0
WooCommerce Subscriptions 3.1.5
Any ideas? 

Best regards, 

Tax Tec

**Comment by InpsydeNiklas** [comment]
Hi @taxtec,

This issue should be fixed with the latest update 1.6.1: Fix - Fatal error: get_3ds_contingency() #310
If any issues persist, then please reach out to our support directly: https://paypal.inpsyde.com/docs/request-support/
Thanks!

Kind regards,
Niklas
