### ISSUE TITLE
Handle failed authorizations when capturing order

### ISSUE THREAD

**Issue by isabellainpsyde** [woocommerce/woocommerce-paypal-payments#304]
**The problem**
Capturing failed authorizations via order actions shown as successful captures.

**Steps to reproduce**
1. Make an order with DENIED authorization status. Currently in 1.6.0 can be done as described in https://github.com/woocommerce/woocommerce-paypal-payments/issues/301
2. Capture it via order actions in WC.
3. Got a note that it is successfully captured, but actually there are no captures.

**Expected behaviour**
The merchant should get a message about failed capture and authorization status.

**Possible cause**
Here  we look only for capturable authorizations ignoring others:
https://github.com/woocommerce/woocommerce-paypal-payments/blob/d38f24ef2bd7bfce1243806f16e2d0109c190abf/modules/ppcp-wc-gateway/src/Processor/class-authorizedpaymentsprocessor.php#L88

**Suggested solution**
IF capturing an authorization
AND status = COMPLETED
THEN mark order as Processing

IF capturing an authorization
AND status = DECLINED
THEN mark order as Failed

IF capturing an authorization
AND status = PENDING
THEN mark order as On Hold
AND Add details to order page from status.details

IF capturing an authorization
AND status = FAILED
THEN keep order as On Hold

**Comment by AlexP11223** [comment]
oops, already created that :) #303

**Comment by isabellainpsyde** [comment]
Close due to dublicte
