### ISSUE TITLE
PayPal payments successfully captured, but Woo status remains unpaid, moves to cancelled (323)

### ISSUE THREAD

**Issue by isabellainpsyde** [woocommerce/woocommerce-paypal-payments#311]
**Problem:** 
Merchants experiencing an issue where PayPal payment is successfully captured, but payment status never updates. This results in orders marked as unpaid.

We got the system report and logs from PP. The log is showing the capture and the webhook received and processed. The order notes never acknowledge the capture.

WC order status looks afterwards like this:
![image](https://user-images.githubusercontent.com/70694460/136230699-a2dab65b-0491-4a63-857c-8d4de74b6ef1.png)

**Comment by shaunkuschel** [comment]
Received another report of this on 4537545-zen (internal link).

**Comment by khalilladha** [comment]
I had couple of cases came across this issue and happy to share more details. Few of my Merchants also facing the same issue where they reported that payment is happening successfully on PayPal end but order showing in Cancelled/Failed status in their WooCommerce admin. Customer also got the wrong notification as payment didn't go through but the payment went through.

**Comment by InpsydeNiklas** [comment]
This could potentially occur when there is custom order status logic. But please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you have any further questions. Thanks!
