### ISSUE TITLE
Plugin does not meet the legal requirements in Germany

### ISSUE THREAD

**Issue by benloeffel** [woocommerce/woocommerce-paypal-payments#317]
### Describe the bug
This plugin places several buttons on the checkout page and doesn't allow for any custom text to be added to the button.
In Germany, it's required by law that the checkout button displays one of the following labels:

1. Kostenpflichtig bestellen
2. Zahlungspflichtig bestellen
3. Zahlungspflichtigen Vertrag schließen
4. Jetzt kaufen[1]

More information can be found here: 
- [Bürgerliches Gesetzbuch (BGB) § 312j Besondere Pflichten im elektronischen Geschäftsverkehr gegenüber Verbrauchern](https://www.gesetze-im-internet.de/bgb/__312j.html)
- [Wikipedia Button-Lösung](https://de.wikipedia.org/wiki/Button-L%C3%B6sung)

### To reproduce
1. Install the plugin
2. Connect the plugin to a sandbox environment
3. Add item to the cart
4. Proceed to the checkout page

**Screenshots**
![2021-10-11 14_15_07-Window](https://user-images.githubusercontent.com/15696921/136788527-0e88dbcb-e47c-43d7-a420-656c07375a07.jpg)

### Expected behavior
A single checkout button with a custom label is displayed.

**Environment (please complete the following information):**
 - WordPress Version: 5.8.1
 - WooCommerce Version: 5.7.1
 - WooCommerce PayPal Payments Plugin Version: 1.6.0

### Additional details
As a temporary workaround, store owners in Germany could potentially do the following to be compliant:
1. Disable all funding options except for the main PayPal checkout button
2. Set the button label to be "Pay with PayPal"
3. Create custom translation for string "Pay with"
4. Hide the PayPal logo

**Comment by InpsydeNiklas** [comment]
Hi @benjaminloeffel,

The plugin provides a setting to adjust the button labels. Choose "PayPal Buy Now" to receive the  "Jetzt kaufen" label on the buttons:
![image](https://user-images.githubusercontent.com/70433191/136793731-ef8d786a-002d-45b1-8bdd-e1c76ac68e67.png)

![image](https://user-images.githubusercontent.com/70433191/136793534-00bf8fcd-865b-4d0d-b228-1dc2e1f5d25c.png)

The suggested workaround does not work because the button strings cannot be modified as the buttons are coming directly from PayPal.
For further questions I suggest reaching out to our support from here:
https://paypal.inpsyde.com/docs/request-support/
Thanks!

Kind regards,
Niklas

**Comment by benjaminloeffel** [comment]
@InpsydeNiklas, thanks for the feedback. I've seen this label and started using it, but the text appears in English despite my WordPress installation being set to German.

**Comment by gcPhil** [comment]
@InpsydeNiklas I noticed the same issue as @benjaminloeffel, and your suggested settings don't work for me. The buttons need 5-10 seconds to load(!) and then the texts does not meet the legal requirements in Germany. I attache a screenshot.

(By the way, event in YOUR screenshot the "Debit- oder Kreditkarte" Text is not correct, no legally valid purchase contract is concluded if people are using that button in Germany).

You write that the texts can't be translated in wordpress, so do you know any other way to change them?

![wc-paypal](https://user-images.githubusercontent.com/2893036/140751078-3a9c60c6-bb03-47bc-a1fa-15470f3a79ff.png)

**Comment by InpsydeNiklas** [comment]
Hi @gcPhil, 

The buttons are currently automatically translated by PayPal. You can only influence the language with your device language setting or your location. But we aim to add a language override feature at some point that allows you to force the WordPress language.
As mentioned above, for further questions please reach out to our support from here:
https://paypal.inpsyde.com/docs/request-support/
Thanks!

Kind regards,
Niklas
