### ISSUE TITLE
Billing address not Chrome but is in Firefox?

### ISSUE THREAD

**Issue by zlobec** [woocommerce/woocommerce-paypal-payments#325]
Hi,

I'm getting the Billing address fields when I test the plugin with Firefox but not with Chrome. This is strange behavior. How can I remove the option to enter the Billing address at all, since the customer already enters it in the cart customer data?

In Firefox:
https://i.imgur.com/DVj0GBu.png
In Chrome:
https://i.imgur.com/mhjZqdw.png

**Comment by InpsydeNiklas** [comment]
Hi @zlobec,

When paying with credit cards through the default credit card smart button, PayPal decides on the basis of several factors which payment flow is initiated for the customer after clicking the button.
Included in these factors could be: The user location, user language, eventual PayPal cookies stored on the computer/browser, and many more. The browser can already make a difference.
Some users may be presented with the inline smart fields with our without additional details requested, while some others may be presented with the checkout flow through the popup with a forced PayPal account login/registration.
You can find more information about the standard card fields in the PayPal documentation.
https://developer.paypal.com/docs/checkout/integration-features/standard-card-fields/
What payment flow is initiated through the default credit card button cannot be influenced in the plugin.

The best thing you can do to prevent users from having to enter additional details for credit card payments is to activate the PayPal Card Processing:
https://docs.woocommerce.com/document/woocommerce-paypal-payments/#section-8
The PayPal Card Processing is an on-site credit card checkout that works with a hosted field integration:

Activating it removes the black default button for credit cards in the iframe and instead creates a second payment gateway exclusively for credit card payments.
So all of your customers only need to enter their credit card information without the need for a PayPal account or additional details.
 
Please reach out to our plugin support directly if you have any further questions:
https://paypal.inpsyde.com/docs/request-support/

Thanks!

Kind regards,
Niklas
