### ISSUE TITLE
Critical error when activating on multisite from the PayPal Checkout Gateway plugin

### ISSUE THREAD

**Issue by xpurichan** [woocommerce/woocommerce-paypal-payments#326]
### Describe the bug
We are able to activate the plugin without issue on a single site, but when network activating the plugin on a multisite it can lead to a 500/critical error with the following PHP error in the logs:

`Fatal error: Uncaught Error: Call to a member function get_active_api_credentials() on null in /srv/htdocs/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/PPEC/class-ppechelper.php:47`

It seems like this only happens as part of an upgrade flow, when we follow the WooCommerce message's notice to upgrade from WooCommerce PayPal Checkout Gateway to WooCommerce PayPal Payments. The behavior was reproducible twice, but I can't reproduce it a third time using the same steps.

### To reproduce
This was my experience that led to finding the issue:
1. Site had `woocommerce-gateway-paypal-express-checkout` installed and we received a notice to Upgrade to PayPal Payments (and then later to Activate PayPal Payments) as seen here:
![Screen Shot 2021-10-13 at 5 55 08 PM](https://user-images.githubusercontent.com/33190975/137217953-114a391a-b461-4e66-b534-4758774e12f7.jpg)
2. On an individual website we were able to Upgrade and then Activate the PayPal Payments plugin without any issue.
3. Next we went to `/wp-admin/network/` to manage the network for the multisite.
4. On the the plugins page we found the same notice as we did in step 1 above, but when we completed the activation step (or, other times, when we completed this and then deactivated the WooCommerce PayPal Checkout Gateway plugin) the website crashed with a critical error and the above-mentioned PHP error was found in the logs.

**Environment (please complete the following information):**
 - WordPress Version: 5.8.1
 - WooCommerce Version: 5.8.0
 - WooCommerce PayPal Payments Plugin Version: 1.6.1
 - Browser [e.g. chrome, safari] and Version: n/a
 - Any other plugins installed: n/a, issue occurs even when WooCommerce and WooCommerce PayPal Checkout Gateway are the only plugins active

### Additional details
Originally found on a WP Special Projects partner site.

**Comment by leonardola** [comment]
I could not reproduce this bug. It seems like it was fixed by #364. Can you still reproduce this?

**Comment by xpurichan** [comment]
Great find @leonardola ! I just tested the dev and production site for the partner who originally reported the error, and upgrades went well on both! I'll close this now.
