### ISSUE TITLE
Different Credit Card form styles cross-browser

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-paypal-payments#33]
## Chrome

Updated screenshot to latest issues*

Old screenshot: https://d.pr/i/hi7W43

![](https://d.pr/i/8ysjgH+)

Issues:
 - [ ] Card icon position is off
 - [ ] No placeholders for credit card number field or the CVV field
 - [ ] the placeholder for the expiry date says "MM/YYYY" but the label says "MM/YY"

## Firefox

![](https://d.pr/i/ByPeH6+)

Issues:
 - [ ] No placeholders for credit card number field or the CVV field
 - [ ] the placeholder for the expiry date says "MM/YYYY" but the label says "MM/YY"

## Safari

![](https://d.pr/i/znjjww+)
 
Issues:
 - [ ] Can't see any of the fields
 - [ ] No placeholders for card number or CVV
 - [ ] Similarly to above, the expiry date place order, and label aren't consistent

## Internet Explorer

Are we supporting IE with v1.0?

![](https://d.pr/i/h89wBd+)

- [ ] Card form doesn't load on IE (No errors in console from what I could see 🤔 )

**Comment by royalfoxie** [comment]
Hi! Is there any chance to change the placeholders? It has a different styles (no website styles) and it's only inside one input.

**Comment by InpsydeNiklas** [comment]
For now, the card fields are correctly displayed in all [officially supported browsers](https://developer.paypal.com/reference/guidelines/browser-support/), though not up to the oldest version supported by the base JSSDK.
