### ISSUE TITLE
Can't checkout to certain countries with optional postcode (319)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#330]
### Description
Same issue as #224: can't checkout to certain countries with optional postcode, that was not fixed on 1.6.0. Countries that have no postal code encounter an issue during checkout, since it still required a postal code to be included.

Error:
```
[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-MISSING_SHIPPING_ADDRESS
```
### Steps to reproduce
- Create a shipping zone that includes countries like UAE or Ireland
- On checkout set address to United Arab Emirates or Ireland
- Use PayPal to pay

Error appears: `MISSING_SHIPPING_ADDRESS`

### Expected behaviour
As with the PayPal Checkout plugin, the checkout should work for countries with optional postcodes.

### Environment
 - WordPress Version: 5.8
 - WooCommerce Version: 5.8
 - WooCommerce PayPal Payments Version 1.6.1

**Comment by chrism245** [comment]
Similar case 4375363-zd

**Comment by sadeekeM** [comment]
I finally found my people! I am from Jamaica and is experiencing the exact same issue. Any insight on when the next update will be available?

**Comment by InpsydeNiklas** [comment]
@sadeekeM The update should be released on Monday if all goes according to plan, but a preview version with a fix can be downloaded from here already https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/1.6.2-test1

**Comment by mvauclare** [comment]
Hi everyone,
I meet this issue now on my website.
I use last version of Woocommerce and Paypal payments plugin.
When I complete the checkout form and click on Pay with Paypal button : Paypal pop up open ... and close ... and there is this error displaying on my checkout page : 

MISSING_SHIPPING_ADDRESS The shipping address is required when `shipping_preference=SET_PROVIDED_ADDRESS`.


I don't have this issue if I use woocommerce checkout shortcode to build my page ...

Demo here : https://www.loom.com/share/22967ee028bd4a60a362f72082fba0fb
