### ISSUE TITLE
Orders with a fee item that has a negative value throw errors

### ISSUE THREAD

**Issue by tobyaherbert** [woocommerce/woocommerce-paypal-payments#349]
### Describe the bug

We're using a discount plugin that works by applying fee items to an order with a negative value. When using this plugin on an order that has a fee item with a negative value, an error is returned by the PayPal API indicating that Money objects contained in the breakdown cannot have a negative value.

### To reproduce

Create a WooCommerce Order that has a fee item with a negative value and the PayPal Payment will throw an error.

### Expected behavior

The PayPal order should be created.

### Environment

WordPress Version: 5.8.1
WooCommerce Version: 5.8.0
WooCommerce PayPal Payments Plugin Version: 1.6.1
Browser: Google Chrome 95.0.4638.69 (Official Build) (x86_64)

### Additional details

I've created a must-use plugin which uses the `woocommerce_paypal_payments_purchase_unit_from_wc_order` hook to strip out these items as a patch. Source is available [here](https://gist.github.com/tobyaherbert/8de353d39f991906c98daf66fbb5bb1c)

**Comment by InpsydeNiklas** [comment]
This was fixed a while back. Thanks for the report.
