### ISSUE TITLE
Compatibility with One Page Checkout Extension (250)

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-paypal-payments#356]
### Describe the bug

When using PayPal payments with the [One Page Checkout extension](https://github.com/woocommerce/woocommerce-one-page-checkout), the payment buttons on product pages appear in the wrong location when using the one page checkout. The original issue has a video and instructions to reproduce.

Essentially you need to:

- Enable both One Page Checkout and PayPal
- Enable One Page Checkout for a simple product
- View the simple product, scroll down to the One Page Checkout Form, select PayPal payment method
- You'll notice payment buttons do not appear within the checkout, they appear in the product description above

This issue was first reported here: 455-gh-woocommerce/woocommerce-one-page-checkout, however the integration code is within PayPal. I found a fix by changing:

https://github.com/woocommerce/woocommerce-paypal-payments/blob/5de222c19c3dc71f83aa5866b3f3757e0a38c1ad/modules/ppcp-button/src/Assets/SmartButton.php#L332-L335

to:

```php
if (
     ( is_product() || wc_post_content_has_shortcode( 'product_page' ) )
     && ! $not_enabled_on_product_page
     && ! is_checkout()
) {
```

and:

https://github.com/woocommerce/woocommerce-paypal-payments/blob/5de222c19c3dc71f83aa5866b3f3757e0a38c1ad/modules/ppcp-button/src/Assets/SmartButton.php#L269-L272

to:

```php
if (
     ( is_product() || wc_post_content_has_shortcode( 'product_page' ) )
     && ! $not_enabled_on_product_page
     && ! is_checkout()
) {
```

One Page Checkout ensures `is_checkout()` is true on pages containing the one page checkout form. I've not raised a PR in case there is a better way, or something that can be changed on the One Page Checkout side.

**Comment by senff** [comment]
Also reported in #35197991-HC

**Comment by maxlaf** [comment]
Another report in 5334020-zen
