### ISSUE TITLE
Onboarding Error Message

### ISSUE THREAD

**Issue by jnf664** [woocommerce/woocommerce-paypal-payments#357]
### Describe the bug
After installing the Woocommerce PayPal Payments plugin, version 1.6.1, during the Connect to PayPal function in Woocommerce - Settings - Payments - PayPal-PayPal Express Checkout - Manage - we click on Connect to PayPal and see a message during PayPal login that reports:

This email is already being used by a PayPal business account. Login or use a different email address to signup.

We continue through the PayPal connect process and see our PayPal account created an App named:

Application_App - with credentials.

We get the following error message in our Woocommerce Admin page for PayPal Payments after Connecting to PayPal using the Woocommerce PayPal Payments plugin version 1.6.1;

We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again.

When we browse to PayPal Card Processing in our Woocommerce Admin page for PayPal payments, we see error message:

You need to complete your onboarding, before you can use the PayPal Card Processing option. Click here to complete your onboarding.

When we click the link provided to complete onboarding, we're sent back to the Woocommerce PayPal Checkout page and again see button named "Connect to PayPal" but that didn't work the first time; so, we clicked link named "Toggle to manual credential input".

After logging in to our PayPal account to find My Apps and Credentials - Live - we see a new app named:
MyApp_WooCommerce_Developers - with credentials.

Using the Client ID and Secret from the above new app in our PayPal account, we input the credentials into the fields provided by the "Toggle to manual credential input" but then get error message in the PayPal Card Processing tab in our Woocommerce Settings - Payments page:

Credit Card processing for your account has not yet been activated by PayPal. If your account is new, this can take some days. Otherwise, please get in contact with PayPal. 

We've been processing PayPal payments with PayPal Standard for over 20 years, which means the error messages are anomalies.

We contacted PayPal and they referred us to woocommerce-support@inpsyde.com and they responded by pointing us to github.

We see in our PayPal account PayPal API credentials that match the above "Application_App"; however, after completing the "Connect to PayPal" process, we see PayPal created another app named:

MyApp_WooCommerce_Developers with credentials.

We see in our PayPal account the "Application_App" and the "MyApp_WooCommerce_Developers" app. We are aware of all the error messages shown above and perceive the new Woocommerce PayPal Payments app has a bug that confuses which set of credentials to apply for PayPal payments. 

So, in an effort to troubleshoot the anomalies, we used "Sandbox" credentials from PayPal and manually input those credentials in the Woocommerce Admin page for PayPal Payments and see no error messages at all in any of the Woocommerce PayPal payments tabs or pages. We processed a test transaction and all activities completed as expected.

After trying the Sandbox credentials, we returned to Live credentials, but the error messages persist.

We logged into our PayPal account and deleted the Activation_App and the MyApp Woocommerce Developers app to start the Connect to PayPal process again. We then deactivated and deleted the PayPal Payments plugin in our Wordpress, logged out then logged in again.

We installed version 1.6.1 Woocommerce PayPal Payments plugin using the "Get Started" link provided by Woocommerce and again, all the error messages repeated themselves.

We have confirmed that using Live API credentials provided by our PayPal account and manually inputting credentials from the MyApp Woocommerce Developers app result in error messages. We are unsure if our Customers are able to checkout using Live credentials but know the sandbox credentials work to throw no error messages.

We are using the latest Wordpress 5.8.2 and Woocommerce 5.9.0 and PayPal Payments 1.6.1
Linux 3.12.18 x86_64
PHP 7.4.25
Wordfence 7.5.6 (free version)
Site Health: Good

Over the next few days, we'll again delete all the apps in our PayPal account to start over and this time we'll also disable Wordfence during the "Connect to PayPal" process in our Woocommerce Admin page for PayPal Payments - then report on our progress.

**Comment by Dinamiko** [comment]
Hello @jnf664,

Did you manage to connect your PayPal account correctly? if not please let us know here the steps for reproducing it, thanks.

**Comment by jnf664** [comment]
Hello,
 
Positively have not been able to connect to PayPal. No hope, no joy.
 
Forced to return to PayPal Standard because Woocommerce will not connect to PayPal.
 
Chat with you again soon,

Jennifer and Frank At-PQC(tm)
719-649-4242
www.qualitycontrolplan.com
www.jnfspecialties.com

**Comment by jnf664** [comment]
Hello,
 
So very sorry about the difficulty with the new PayPal payments plugin on our website.
 
Please advise if we need to disable setting in Woocommerce - Advanced - Legacy API that is named:
 
Enable the legacy REST API
 
There is a check mark to enable use of the legacy REST API in this tab.
 
Wonder if this setting is interfering with the Woocommerce PayPal Payments plugin? Please advise...
 
Other settings in the "Advanced" tab in our current Woocommerce settings include:
 
Page setup - all the fields in this tab are provided by default
REST API - there is no "key" in this tab
WEBHOOKS - there is no "webhook" in this tab
Woocommerce.com - marketplace suggestions is enabled in this tab
Features - woocommerce analytics is enabled in this tab
 
Multiple visits with tech-support at PayPal reveals there are no problems...hmm...
 
We are successfully using PayPal Standard in Woocommerce - Payments with plugin named WooCommerce PayPal Checkout Gateway, which will be disabled March 2022. Of course, the plugin is no longer being updated, but we have to disable PayPal or use the old plugin until we can successfully use the new plugin with no error messages.
 
Jennifer and Frank - 11-30-2021

**Comment by jnf664** [comment]
Please advise if we should turn off the "Legacy REST API" in Woocommerce Settings to enable successful use of the Woocommerce PayPal Payments plugin. We provided a very lengthy description of the problem but have not heard from you. We have also installed the latest version of the update but it too does not allow a connection to PayPal and it reports the same errors.

**Comment by InpsydeNiklas** [comment]
Hi @jnf664,

This legacy setting should not interfere with the plugin onboarding. But maybe something else on your site is blocking the connection to PayPal.
Could you please send us a copy of your WooCommerce system report as advised here?: https://paypal.inpsyde.com/docs/request-support/
Please include a link to this GitHub issue and we will look into it further is as soon as possible.
Thanks!

**Comment by jnf664** [comment]
Hello,
 
Please advise how to send this sensitive information.
 
Chat with you again soon,

Jennifer and Frank

**Comment by isabellainpsyde** [comment]
Hello Jennifer and Frank, 

did you get the chance to send us a copy of your WooCommerce system report? If it was not clear on how to do it, you can open a support ticket here: https://paypal.inpsyde.com/docs/request-support/
Thanks!

**Comment by jnf664** [comment]
Hello,
 
Please be aware this issue is not resolved and should remain open until resolved.
 
We asked but did not get an answer about how to submit the Woocommerce report.
 
Please advise...

Jennifer and Frank

**Comment by jnf664** [comment]
Hello,
 
Please be aware this issue is not resolved and we think this is a very sneaky way of getting out of having to answer for the difficulties we are having and how many untold thousands of voices that are having the same difficulty.
 
Chat with you again soon,

Jennifer and Frank

**Comment by jnf664** [comment]
We are providing report but you waited until today to ask again but did not answer our question about how to submit until today. We created the following report on 12-8-2021, immediately upon your request but you did not tell us how to submit sensitive information:

### WordPress Environment ###

WordPress address (URL): https://www.quality-control-plan.com
Site address (URL): https://www.quality-control-plan.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.26
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1l-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_zsvi_
Total Database Size: 25.36MB
Database Data Size: 21.60MB
Database Index Size: 3.76MB
wp_zsvi_woocommerce_sessions: Data: 0.26MB + Index: 0.02MB + Engine MyISAM
wp_zsvi_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
wp_zsvi_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_woocommerce_order_itemmeta: Data: 0.15MB + Index: 0.12MB + Engine MyISAM
wp_zsvi_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_actionscheduler_actions: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_zsvi_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_actionscheduler_logs: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_zsvi_aws_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_aws_index: Data: 0.41MB + Index: 0.21MB + Engine MyISAM
wp_zsvi_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_comments: Data: 0.13MB + Index: 0.07MB + Engine MyISAM
wp_zsvi_cptch_blacklist_ip: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zsvi_cptch_track_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_cptch_track_visitor: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_imagify_files: Data: 0.26MB + Index: 0.19MB + Engine MyISAM
wp_zsvi_imagify_folders: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_options: Data: 1.58MB + Index: 0.07MB + Engine MyISAM
wp_zsvi_postmeta: Data: 2.02MB + Index: 0.80MB + Engine MyISAM
wp_zsvi_posts: Data: 2.37MB + Index: 0.09MB + Engine MyISAM
wp_zsvi_redirection_404: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_redirection_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_redirection_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_relevanssi: Data: 0.78MB + Index: 0.77MB + Engine MyISAM
wp_zsvi_relevanssi_log: Data: 0.12MB + Index: 0.10MB + Engine MyISAM
wp_zsvi_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_rsssl_csp_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_usermeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_zsvi_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wc_customer_lookup: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_zsvi_wc_download_log: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_zsvi_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wc_order_product_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_zsvi_wc_order_stats: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_zsvi_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfConfig: Data: 0.44MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfFileMods: Data: 2.29MB + Index: 0.33MB + Engine MyISAM
wp_zsvi_wfHits: Data: 3.18MB + Index: 0.10MB + Engine MyISAM
wp_zsvi_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfIssues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wfKnownFileList: Data: 1.22MB + Index: 0.14MB + Engine MyISAM
wp_zsvi_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfLogins: Data: 0.29MB + Index: 0.07MB + Engine MyISAM
wp_zsvi_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_zsvi_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wfNotifications: Data: 0.09MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wfStatus: Data: 0.09MB + Index: 0.04MB + Engine MyISAM
wp_zsvi_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wpfm_backup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_wplc_chat_msgs: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_zsvi_wpr_rucss_resources: Data: 1.64MB + Index: 0.02MB + Engine MyISAM
wp_zsvi_wpr_rucss_used_css: Data: 1.79MB + Index: 0.02MB + Engine MyISAM
wp_zsvi_yoast_indexable: Data: 0.17MB + Index: 0.04MB + Engine MyISAM
wp_zsvi_yoast_indexable_hierarchy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_zsvi_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_zsvi_yoast_prominent_words: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_zsvi_yoast_seo_links: Data: 0.10MB + Index: 0.03MB + Engine MyISAM
wp_zsvi_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 112
custom_css: 1
nav_menu_item: 41
oembed_cache: 12
page: 50
post: 10
product: 48
revision: 174
shop_order: 380
shop_order_refund: 19
tablepress_table: 4
user_request: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Advanced noCaptcha & invisible Captcha: by WP White Security – 6.1.7
Advanced Woo Search: by ILLID – 2.42
Classic Editor: by WordPress Contributors – 1.6.2
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.2
CAOS: by Daan from FFW.Press – 4.1.9
Imagify: by WP Media – 1.10
Last Modified Timestamp: by Evan Mattson – 1.0.5
MyThemeShop Theme & Plugin Updater: by MyThemeShop – 3.0.7
Relevanssi: by Mikko Saari – 4.14.4
SiteGround Optimizer: by SiteGround – 6.0.5
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.6.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.3
WooCommerce Stripe Gateway: by WooCommerce – 5.8.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6
WooCommerce: by Automattic – 5.9.0
Yoast SEO Premium: by Team Yoast – 17.7
Yoast SEO: by Team Yoast – 17.7.1
WP File Manager: by mndpsingh287 – 7.1.2
WP Rocket: by WP Media – 3.10.4
WP Rollback: by Impress.org – 1.7.1
Yoast SEO: WooCommerce: by Team Yoast – 14.4

### Inactive Plugins (4) ###

Autoptimize: by Frank Goossens (futtta) – 2.9.3
Classic Widgets: by WordPress Contributors – 0.2
Redirection: by John Godley – 5.1.3
Wordfence Security: by Wordfence – 7.5.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #761 - /shop/
Cart: #762 - /cart/
Checkout: #763 - /checkout/
My account: #764 - /my-account/
Terms and conditions: #859 - /terms-and-conditions/

### Theme ###

Name: Schema by MyThemeShop
Version: 3.9.23
Author URL: https://mythemeshop.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: mts_schema/woocommerce/archive-product.php
mts_schema/woocommerce/single-product.php


### Action Scheduler ###

Complete: 110
Oldest: 2021-11-19 15:53:22 -0700
Newest: 2021-12-07 09:30:44 -0700

Pending: 1
Oldest: 2021-12-08 13:05:08 -0700
Newest: 2021-12-08 13:05:08 -0700


### Status report information ###

Generated at: 2021-12-08 13:05:48 -07:00

**Comment by jnf664** [comment]
This problem is not "CLOSED" until we successfully install and operate PayPal Payments on our website. We have successfully been using PayPal for 20 years and have not had any trouble until your new software, which we perceive is broken and should not be released to unsuspecting Users.

**Comment by isabellainpsyde** [comment]
Hello Frank and Jennifer, 

my apologies. Of course, we want to help you and solve this issue. My colleague asked you to send us a copy of your WooCommerce system report as advised here: https://paypal.inpsyde.com/docs/request-support/ 
As this may was not clear enough I sent you the link again. I closed the ticket on Github so we can provide you with further support via our support platform to handle your sensitive data carefully. 
We will take a look at the information and will get back to you. 
Sorry for the inconvenience.

**Comment by sofiobanzale** [comment]
I have the same problem on my website with woocommerce paypal payment. It's about the plugin itself. try to reach woocommerce support service.
https://woocommerce.com/my-account/create-a-ticket/

**Comment by Sirvijver** [comment]
Hello all,

this issue should be possible to resolve, but does not seem to be a developer's issue, so we would suggest opening a support ticket with us direct via [these instructions](https://paypal.inpsyde.com/docs/request-support/) or via the [WooCommerce support forum](https://woocommerce.com/my-account/create-a-ticket/).

Via these engagements, we can most likely guide you through the process. I will close this thread, as this type of situation should be handled via the support process.

Kind regards, 
Joost
