### ISSUE TITLE
Cannot pay using saved card in My Account -> Orders (418)

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#360]
Not possible to pay with a saved card in My Account -> Orders ("Pay Now"?).

## Steps to reproduce

1. Create an order in WC admin UI.
2. Go to My Account -> Orders, press Pay on the order.
3. Pay with a saved card.
4. See "Unfortunately, we do not support your credit card" error.

## Possible cause

[PayNowBootstrap.js](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-button/resources/js/modules/ContextBootstrap/PayNowBootstrap.js) does not handle saved cards.

## Suggested solution

Handle saved cards like in [CheckoutBootstap.js](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-button/resources/js/modules/ContextBootstrap/CheckoutBootstap.js).

**Comment by Dinamiko** [comment]
Fixed by #361.
