### ISSUE TITLE
[RC] "Save your Credit Card" shouldn't be optional when paying for a subscription (425)

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#368]
### Describe the bug

When using DCC to pay for a subscription, the "Save your Credit Card" checkbox should be checked off by default and user shouldn't be allowed to uncheck it.
Even if this doesn't change the underlying behavior (which I'm not sure yet), this is incorrect in UI terms.

### To reproduce

1. Add a subscription product to the cart.
1. Go to the Checkout page.
1. Confirm that "Save your Credit Card" is unchecked by default and you can toggle it as desired.

**Screenshots**

<img width="421" alt="Screen Shot 2021-11-16 at 15 37 44" src="https://user-images.githubusercontent.com/184724/142083548-a92c7b37-6921-49af-8cc3-4fb47dff97ad.png">

### Expected behavior

Vaulting should be enforced somehow for subscription products.

**Comment by Dinamiko** [comment]
Hi @jorgeatorres,

I just want to mention that we are enforcing vaulting for subscription products here: https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js#L187-L189

So as soon as there is a subscription product in the cart we are going to send vault true independently of which value comes from the save card checkbox.

This is already merged into trunk and is going to be included in the upcoming release.

Regarding this issue I think the easiest way to implement it is by not rendering the checkbox element when there is a subscription product as in #374.
