### ISSUE TITLE
[RC] Refunding via PayPal does not change order status to "Refunded" (426)

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#369]
### Describe the bug
This is part of the 1.6.2 changelog and was originally reported as #241, but I can't find a PR that actually fixed this.
During our testing, it didn't seem to work (even in a publicly accessible website), but maybe we're missing something. Is there a way to debug this further?

### To reproduce

1. Purchase anything via PayPal.
1. Confirm order status is "Processing".
1. Refund order on PayPal dashboard.
1. Even after waiting for a while for webhooks (I presume) to fire, order doesn't change status.

**Screenshots**
See [screencast](https://d.pr/i/N0Ivch).

### Expected behavior

Order changes status as described in #241.

**Comment by AlexP11223** [comment]
> I can't find a PR that actually fixed this.

It was fixed before 1.6.2 actually. The problem was that there were some general problems with webhook registration, not specific to refunds.

Do webhooks work on the webhooks status page in the plugin settings?

**Comment by jorgeatorres** [comment]
Hi @AlexP11223!

Thanks for your answer. After setting up a new site, we were unable to replicate, so we're not sure what could've gone wrong initially. I'm closing this issue now.

cc @isabellainpsyde.
