### ISSUE TITLE
All payments fail for virtual goods with custom order

### ISSUE THREAD

**Issue by elwiderman** [woocommerce/woocommerce-paypal-payments#370]
### Describe the bug
I have a WooCommerce store that sells virtual goods. Instead of the standard WooCommerce checkout flow I have a custom checkout where I am creating a custom order programatically using the following piece of code:

`
global $woocommerce;
$billing_address = array(
	…
	has all the billing fields
	…
);
$order = wc_create_order();
$order->add_product(wc_get_product({product_id_goes_here}), 1);
$order->set_address($billing_address, 'billing');
$order->calculate_totals();
$order->save();

$payment_url = $order->get_checkout_payment_url();

// redirecting to the payment page like a custom order from the wp-admin
wp_safe_redirect($payment_url);
`

In the payment page I have the list of payment gateways including Paypal through the new Woocommerce PayPal plugin. Please note that all my checkouts are guest checkouts. So when the I am trying to make the payments logged out of WordPress – all payments fail. Whereas when I try to make the payments being logged into to WordPress the payments go through. Please note that in the sandbox mode all payments are successful. My live PayPal account has the exact same settings as the Sandbox.
In order to debug, I have created a separate WordPress + Woocommerce installation with the exact same configuration but with the standard Woocommerce Cart -> Checkout -> Payment flow. In this case the payment is successful for both cases when I am logged into WordPress and when not.

### To reproduce
1. Turn on guest checkout.
2. Create a custom order from **Woocommerce > Orders > Add new**
3. Use the ** Customer payment page →** link to make the payment in another window(without being logged in to wordpress)

### Expected behavior
It is expected that the payment must process at Paypal when i am logged into wordpress

**Environment (please complete the following information):**
 - WordPress Version - 5.8.2
 - WooCommerce Version - 5.9.0
 - WooCommerce PayPal Payments Plugin Version - 1.6.1
 - Browser [e.g. chrome, safari] and Version - all browsers

**Comment by InpsydeNiklas** [comment]
Please[ get in touch with the support team](https://woocommerce.com/wp-admin/post.php?post=8738362&action=edit#get-help) if any issues persist for you with the latest version of the integration. Thanks!
