### ISSUE TITLE
Internet Explorer 11 Support

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-paypal-payments#38]
I'm not sure if IE11 support is on the table for 1.0 but I've created this issue to discuss/track it.

## PayPal Checkout

- [ ] PayPal Smart Buttons don't load

![](https://d.pr/i/0yJ3Wg+)

## PayPal Card Processing

- [ ] No Credit Cards payment fields or payment method option are loading

(the double place order buttons should be fixed once #26 is merged) 

![](https://d.pr/i/a283v2+)

**Comment by InpsydeNiklas** [comment]
[IE11 support will be dropped ](https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/)by WordPress 5.8+ and will also not see any official PayPal Payments support.
