### ISSUE TITLE
Paypal payments automatically disabled for new subscribers

### ISSUE THREAD

**Issue by steffans** [woocommerce/woocommerce-paypal-payments#389]
### Describe the bug
Paypal payments is disabled when purchasing subscriptions if a customer is not logged in. See DisableGateways.php line 113

```php
if ( $this->subscription_helper->cart_contains_subscription() && ! is_user_logged_in() ) {
    return true;
}
```

### Expected behavior
New customers should be able to checkout using Paypal, because the account is automatically created during the checkout. By using the following account creation settings (Accounts & Privacy):

[x] Allow customers to create an account during checkout
[x] When creating an account, automatically generate an account username for the customer based on their name, surname or email
[x] When creating an account, automatically generate an account password

**Environment:**
 - WordPress Version 5.9.0
 - WooCommerce Version 5.8.2
 - WooCommerce Subscriptions 3.1.6
 - WooCommerce PayPal Payments Plugin Version 1.6.2

**Comment by InpsydeNiklas** [comment]
Hi @steffans,
The gateway has been intentionally disabled for guest users when subscription products are in the cart with the recent update 1.6.2. It could cause problems with renewals when the user was not logged in during the subscription creation.
We are working to bring back this functionality with the next feature update. But for the time being, only logged-in users can purchase subscription products.

**Comment by developcrk** [comment]
Hi @InpsydeNiklas,

I was checking the update logs Is this Fix - Guest users must checkout twice for subscriptions, no smart buttons loaded #342 the fix for this?

Is it possible now to buy with PayPal as a guest?

Regards.

**Comment by Pikamander2** [comment]
We're also having trouble with guests purchasing subscriptions via PayPal. Is that functionality enabled in 1.6.3 or is it still disabled? The error messages aren't very clear.

**Comment by InpsydeNiklas** [comment]
#342 was not fully resolved in time for the 1.6.2/1.6.3 update as it is unfortunately not a trivial problem to fix and requires more code refactoring. 
The changelog entry may be a bit misleading as it does not fully reflect the change that was implemented instead. 
We will make sure these are more clear for the future.
Anyway, it is one of the highest priorities and we aim to re-enable guest subscription checkouts for the next update, which is set to arrive in early January.

**Comment by Pikamander2** [comment]
@InpsydeNiklas - Thanks for the info. Just to clarify, is there currently any way at all for unregistered users to checkout with a subscription using PayPal, or do they absolutely need to create an account before visiting the checkout page?

**Comment by steffans** [comment]
Just tested a new subscription signup with 1.6.5-test2 (not logged in), the Paypal option shows up but the "Sign up button" remains and does not get switch for the "Paypal" smart button. 

_Edit:_

This issue seems to be related to the "Invoice prefix" setting, using a prefix with 6 chars the smart button works fine. However longer prefix lengths cause issues, a prefix like "vqezbtgwikxayvi-" (15 chars). See error log:   

```
Response Body: {
"name":"INVALID_REQUEST","details":[{"field":"/customer_id","value":"vqezbtgwikxayvi-61f5157ab430e","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long"}],"message":"Request is not well-formed, syntactically incorrect, or violates schema.","links":[{"href":"https://developer.paypal.com/docs/api/identity/v1/#error-INVALID_STRING_LENGTH","rel":"information_link"}],"debug_id":"b6d93d0ca599"
}
```

Maybe validate the "Invoice prefix" string length?

**Comment by InpsydeNiklas** [comment]
This issue should be resolved by now. For the time being, guests can only buy subscription products from the Checkout page as the buttons will be disabled on the non-Checkout pages.
When we found a method to handle non-Checkout pages more reliably, the buttons on these pages will be restored for guests.
If any issues or questions persist, please reach out to our support from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
