### ISSUE TITLE
[RC] Redirect after updating settings for DCC sends you to PPCP settings screen (478)

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#392]
### Describe the bug

After (possibly) making changes to the settings on the "PayPal Card Processing" screen, you're redirected to the "PayPal" settings screen instead.

### To reproduce

1. Go to WC > Settings > Payments > PayPal Card Processing.
1. Make sure to enable vaulting if it was disabled.
1. Click "Save changes".
1. Confirm you're now on the "PayPal" settings tab instead.

### Expected behavior

The currently selected tab (PayPal vs PayPal Card Processing) should be honored after saving changes.

**Comment by jorgeatorres** [comment]
This section of code seems to be related to the issue:

https://github.com/woocommerce/woocommerce-paypal-payments/blob/8cdcbcf4bbcb9c570827bdbfad044176f0f7575b/modules/ppcp-wc-gateway/src/Settings/SettingsListener.php#L206-L207

**Comment by Dinamiko** [comment]
Reverted as it introduced issue in PayPal gateway.
