### ISSUE TITLE
Updating from v1.6.1 to v1.6.2 causes all credit/debit payments to fail on the website

### ISSUE THREAD

**Issue by TorlockC** [woocommerce/woocommerce-paypal-payments#406]
### Describe the Bug

Updating from v1.6.1 to v1.6.2 causes all credit/debit payments to fail on the website. On the surface that sounds kind of dramatic and I'm sure not all users are getting the same issue (otherwise 1.6.2 wouldn't be released) but this is the case on our site and from looking through the WP forum some others too.

After filling in their personal details and card details, customers are confronted with the following error: “Error processing checkout. Please try again.” with no further information. The error is very generic so I proceed to the log but unfortunately, nothing substantial is there either (see second screenshot below).

After this, I've checked through the network tab in FF and I can see a response from `?wc-ajax=checkout` with the following JSON:

`{“result”:”failure”,”messages”:””,”refresh”:false,”reload”:false}`

It seems that no attempt is made to PayPal via the API and instead the order is made, failed and the payment stage is no reached.

### To Reproduce

1. Update 1.6.1 to 1.6.2
2. Add item to cart
3. Proceed to checkout and fill in personal details
4. Select the credit/debit option and fill in card details
5. Click to complete payment and get the error: 'Error processing checkout. Please try again.'
6. Check network tab `?wc-ajax=checkout` JSON response for `{“result”:”failure”,”messages”:””,”refresh”:false,”reload”:false}`

### Screenshots

Error frontent: https://i.imgur.com/pHF6tHc.png
Error log after this: https://i.imgur.com/aFQ4SgX.png
Network tab for `?wc-ajax=checkout` after error: https://i.imgur.com/3SibufT.png

### Expected Behavior

The user should be able to enter their personal/card details and if everything is okay the payment should be taken and the order moved to the processing state.

### Actual Behavior

Payment is not taken (nor does it seem attempted) an error is thrown and the state is stuck on failed.

### Environment

 - WordPress Version: 5.6
 - WooCommerce Version: 5.8.0
 - Plugin Version: Reverted back to 1.6.2
 - Browser [e.g. Chrome, Safari] and Version: Issue occurs in all major browser (tested in latest FF/Chrome/Safari)
 - Any other plugins installed: Yes (see below)

Elementor / Elementor Pro
W3TC
Advanced Shipment Tracking for WooCommerce
Ajax Search Pro
Purchase Orders for WooCommerce
Query Monitor
S3 Uploads
WooCommerce EU VAT Assistant
WooCommerce PDF Invoices & Packing Slips
WooCommerce Split Orders
WordFence
WP Offload SES Lite

**Comment by InpsydeNiklas** [comment]
This issue should be resolved by now. If any problems or questions persist, please reach out to our support from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
