### ISSUE TITLE
Subscriptions+PayPal not working

### ISSUE THREAD

**Issue by FeelPeak** [woocommerce/woocommerce-paypal-payments#409]
### Bug description

Hi there. We're working on launching a subscription-based service on our website, but we're having trouble getting PayPal payments to work.

We did some testing a month ago with this plugin (version 1.6.1) and it worked, although some parts of it were very buggy and offered poor feedback to the user when something went wrong, so we decided to put it on the backburner for a bit.

Now that two significant updates have been released, we're trying it out again (version 1.6.3). Unfortunately, we can't even successfully make a payment now.

When selecting the United States as the user's country, the checkout page displays this error message: <strong>"Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements."</strong>

Despite the error message, it still shows the three PayPal/Venmo buttons (we only want one; how do we turn those other two off?), so the PayPal (sandbox) popup window can still successfully be opened. However, after paying for the order, WooCommerce displays this error message at the top of the screen: "Invalid payment method."

In the console, we get these two error messages:

CreditCardRenderer.js?387a:43

`Uncaught TypeError: Cannot read properties of null (reading 'style')
    at CreditCardRenderer.render (webpack-internal:///964:935)
    at Renderer.render (webpack-internal:///964:836)
    at CheckoutBootstap.render (webpack-internal:///964:738)
    at CheckoutBootstap.init (webpack-internal:///964:700)
    at bootstrap (webpack-internal:///964:1284)
    at HTMLScriptElement.eval (webpack-internal:///964:1305)`

b.sbox.stats.paypal.com/v2/counter.cgi?p=uid_fc8184cebc_mte6mde6mty&s=SMART_PAYMENT_BUTTONS:1

`Failed to load resource: net::ERR_CONNECTION_TIMED_OUT`

Any idea what might be causing that error? We told it to allow payments from all countries, so I'm not sure what the issue could be, and the error message doesn't offer much help in the way of what we need to adjust.

### Reproduction steps
1. Go to https://redesign.feelpeak.com/shop
2. Under "Online Personal Training 1 Month", click "Sign up now"
3. You will be redirected to https://redesign.feelpeak.com/checkout/
4. Enter a name, country, and email address
5. Click the PayPal button and "pay" for the order using a PayPal sandbox account
6. The PayPal popup will close and "Invalid payment method." will appear at the top of the checkout page.

### Screenshots

![image](https://user-images.githubusercontent.com/96179247/146179014-0e33b8f3-1422-4914-8718-a67ea3fec222.png)

### Environment
 - **WordPress version:** 5.8.2
 - **WooCommerce Version:** 5.9.0
 - **WooCommerce PayPal Payments**: 1.6.3
 - **WooCommerce Subscriptions**: 3.1.6
 - **Theme version**: Astra 3.7.5
 - **Browser**: Tested in the latest version of Chrome and Firefox

**Comment by FeelPeak** [comment]
Here's the payload and response data from the call to https://redesign.feelpeak.com/?wc-ajax=checkout

```
billing_first_name: Test
billing_last_name: Test
billing_country: US
billing_email: Test@feelpeak.com
woocommerce-process-checkout-nonce: 1f17fe613b
_wp_http_referer: /?wc-ajax=update_order_review
ppcp-resume-order: undefined
```

```
{"result":"failure","messages":"<ul class=\"woocommerce-error\" role=\"alert\">\n\t\t\t<li>\n\t\t\tInvalid payment method.\t\t<\/li>\n\t<\/ul>\n","refresh":false,"reload":false}
```

**Comment by steffans** [comment]
You can use the `Disable funding sources` option in your Paypal payments settings to disable Venmo and the other buttons.

**Comment by brianyu28** [comment]
There's some discussion of a similar issue at https://github.com/woocommerce/woocommerce-paypal-payments/issues/389, which looks like it might match what you're describing here?

**Comment by InpsydeNiklas** [comment]
Additional funding sources are only displayed when Vaulting is not enabled. Vaulting is required to use the subscription functionality though, so please make sure that's enabled.
Anyway, this particular behavior of the smart button rendering on the checkout page for a guest user is a bug. Instead, it should say "There are no available payment methods" and not display any start buttons when there are no other payment methods active and the user is not logged in.
We have seen this behavior on a few sites (this is the second report afaik) after the gateway has been disabled for guest users in 1.6.2 as mentioned in #389.
Despite the smart button still rendering, the PayPal gateway is not active which leads to the error "invalid payment method" when trying to use it.
It's not quite clear why this is happening, but we are working to resolve the guest checkout entirely for an update in January that comes after the upcoming [version 1.6.4](https://github.com/woocommerce/woocommerce-paypal-payments/milestone/6?closed=1), as disabling the gateway was meant to be a temporary measure anyway.

**Comment by InpsydeNiklas** [comment]
This should be resolved already. If any issues persist, please [get in touch with the support team](https://woocommerce.com/wp-admin/post.php?post=8738362&action=edit#get-help). Thanks!
