### ISSUE TITLE
PayPal Checkout Legacy Notice should contain more helpful copy for store owners.

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-paypal-payments#415]
### Describe the Bug

When PayPal Payments is activated, PayPal Checkout (and presumably other legacy PayPal plugins) has a notice in **WP Admin → Plugins** which prompts the user to update to PayPal Payments. It has a link to the PayPal Payments product page on WooCommerce.com, and a "Learn More" link which links to the actual upgrade instructions.

This notice makes it sound like installing PayPal Payments is the sufficient step to complete the upgrade, when in actuality it is necessary but not sufficient to properly upgrade - according to the upgrade instructions, PayPal Payments should be tested, then PayPal checkout should also be uninstalled.

Note that there are good arguments that ['Learn More' is an uncertain, unhelpful button label](https://www.nngroup.com/articles/learn-more-links/).

### To Reproduce

1. Install and Activate both PayPal Checkout and PayPal Payments
2. Go to **WP Admin → Plugins** and observe the notice on the PayPal Checkout row

### Screenshots
![Screenshot](https://d.pr/i/2YiFI9+.png)  
*If you do not see the image, please [click here](https://d.pr/i/2YiFI9).*

### Expected Behavior
I expect very clear call to action that helps non-technical store owners know the exact steps they need to take to properly upgrade.

### Actual Behavior
The notice says to install PayPal Payments with a soft "Learn More" call to action for the full instructions. 

### Recommendation
One or both of the following will help:
- Include all the basic upgrade steps (install the new plugin, setup & test, then remove legacy plugin after) 
- Change the label of the 'Learn More' button to a stronger call to action. I recommend "Complete Upgrade Instructions", which lets the user know that the blurb is *not* comprehensive for updating.

Additionally, including a notice for users of Subscriptions that PayPal Payments will correctly pick up their renewals from PayPal Checkout would be a nice confidence builder that might assist adoption.

### Additional Details
4614714-zen

**Comment by InpsydeNiklas** [comment]
Hi @melek,
We agree the instructions in this notice could be better, but it is coming from the PayPal Checkout plugin and not from PayPal Payments. We are working on an improved onboarding flow and better overall setup documentation, but all of these things we're working on would still come after the user saw the notice from the Checkout plugin anyway.
Improvements to the actual upgrade notice would fit better in the PayPal Checkout plugin repo: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues
But we will also bring this up internally to see how we can get this improved together. Thanks!

**Comment by InpsydeNiklas** [comment]
The migration notice is created by the [PayPal Checkout plugin](https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/), which is no longer maintained and likely won't see any more updates to change the notice.
All that PayPal Payments is doing in this regard is to suppress the notice when it is active. So I will close this issue as there is nothing that can be done from the PayPal Payments perspective.
