### ISSUE TITLE
[Enhancement] Add filters for allowed_country_currency_matrix and country_card_matrix (495)

### ISSUE THREAD

**Issue by davoraltman** [woocommerce/woocommerce-paypal-payments#437]
Hi folks,

We're trying to enable [ACDC](https://developer.paypal.com/docs/checkout/advanced/) for stores in Hong Kong. To enable this option, we first need to modify the plugin's file (attached is the guide we received from PayPal, referring to SG instead of HK but the drill is the same).

[Enabling_ACDC_in_WooCommerce.pdf](https://github.com/woocommerce/woocommerce-paypal-payments/files/7837167/Enabling_ACDC_in_WooCommerce.pdf)

We modified woocommerce-paypal-payments/modules/ppcp-api-client/services.php (not DccApplies.php from the guide as it didn't work) but the problem with this approach is that we would need to modify the plugin's core file each time the plugin is updated. As a potential solution, we are suggesting that two filters be added to the plugin - allowed_country_currency_matrix and country_card_matrix so that we can modify the array outside of the core plugin. Thank you!

P.S. If there's another way for us to work around this issue, please do let me know. Thanks!

**Comment by InpsydeNiklas** [comment]
The only alternative to modifying the code would be to set the WooCommerce store location in the General settings tab to a supported country/currency:
https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/

**Comment by Dinamiko** [comment]
Fixed in #485.

**Comment by Dinamiko** [comment]
Filter documentation added to repo wiki: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#add-advanced-credit-and-debit-card-acdc-countries
