### ISSUE TITLE
improve onboarding flow, allow no card processing (370)

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#443]
Some users may not want to provide the PayPal Card Processing. In that case, they are not interested in applying for the feature during the initial onboarding.

## Suggested solution

![image](https://user-images.githubusercontent.com/5680466/149939450-bbb0e9af-24fd-4c22-84a0-2a28cefc3265.png)

- Defaults are as above.
- The Advanced and Basic checkboxes should be radio (only one can be selected)
- If Advanced is selected, pass `product` in `v2.customer.partner-referrals` as `PPCP`
- If Basic is selected, or Securely accept all major credit & debit cards is unchecked, pass `product` as `EXPRESS_CHECKOUT`
- Advanced should only be presented to the configured countries (currently US, CA, UK, AU, FR, IT, ES)

**Comment by Dinamiko** [comment]
Fixed in #445.
