### ISSUE TITLE
Investigate if `assert` is really needed outside of tests

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#450]
We currently have some PHP assertions in code outside of tests, which sometimes can get flagged by security-related software (such as Security by CleanTalk) as potential vulnerabilities.
Those in our code are definitely not vulnerabilities in any way, but I thought we could still go through the current instances of `assert()` in our code and if they are not really needed, maybe just remove them.

Files with assertions as of right now:

- [modules/ppcp-status-report/src/StatusReportModule.php](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-status-report/src/StatusReportModule.php)
- [modules/ppcp-vaulting/src/VaultingModule.php](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-vaulting/src/VaultingModule.php)
- [modules/ppcp-wc-gateway/src/WCGatewayModule.php](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-wc-gateway/src/WCGatewayModule.php)
- [modules/ppcp-webhooks/services.php](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-webhooks/services.php)
- [modules/ppcp-webhooks/src/WebhookModule.php](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-webhooks/src/WebhookModule.php)

**Comment by AlexP11223** [comment]
It's for type-hinting.

**Comment by InpsydeNiklas** [comment]
We've been in contact with certain plugin developers like CleanTalk to verify with them that the assertions in the plugin are not an issue and won't end up getting flagged.
So I will close this issue.
