### ISSUE TITLE
WooCommerce as mu-plugin is not detected as active (524)

### ISSUE THREAD

**Issue by areklam** [woocommerce/woocommerce-paypal-payments#461]
### Describe the Bug

The detection of WooCommerce using `is_plugin_active()` [does not take into account mu-plugins](https://developer.wordpress.org/reference/functions/is_plugin_active//#description). 

### To Reproduce

1. Install WooCommerce as mu-plugin
2. Install and activate WooCommerce PayPal Payments plugin
3. See error about WooCommerce is not installed (screenshot)

### Screenshots

![Screenshot 2022-02-01 at 16 29 51](https://user-images.githubusercontent.com/77097516/151998229-de398d55-5251-47c3-9c97-6d06b8733b0d.png)

### Expected Behavior

WooCommerce to be detected as installed and the plugin to prompt for further setup (connecting to PayPal)

### Actual Behavior

Setup is blocked as WooCommerce is not detected.

**Comment by blydewright** [comment]
I'm experiencing the same issue - hopefully someone will get around to approve this fix. Thanks @areklam! :)

**Comment by Dinamiko** [comment]
Fixed in #498
