### ISSUE TITLE
Improve onboarding notice (496)

### ISSUE THREAD

**Issue by Narek13** [woocommerce/woocommerce-paypal-payments#465]
### Describe the Bug

After installing PayPal Payments, some users are confused by the wording:
> PayPal Checkout is almost ready.

When the PayPal Checkout Gateway plugin is already configured and active.

### To Reproduce

1. Instal the plugin.
2. See the text message.

### Screenshots

<img width="917" alt="Screen Shot 2022-02-03 at 16 12 06" src="https://user-images.githubusercontent.com/11319597/152340702-d0d86f75-e4eb-40f6-8cee-cbe7cdedc1d1.png">

### Expected Behavior

The notice text should be:
> PayPal Payments is almost ready.

### Actual Behavior

> PayPal Checkout is almost ready.

**Comment by Dinamiko** [comment]
Merged into trunk.
