### ISSUE TITLE
PayPal Payments doesn't set transaction fee metadata (307)

### ISSUE THREAD

**Issue by danielbreves** [woocommerce/woocommerce-paypal-payments#467]
### Describe the Bug

PayPal Checkout used to set the transaction fee as an order metadata [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/85a478de146459418b23854cca4a60f073344dbf/includes/functions.php#L111), PayPal Payments doesn't.

### Expected Behavior

There should be some mechanism for plugins to read PayPal transaction fees.

### Environment

 - WordPress Version 5.9
 - WooCommerce Version 6.1.1

**Comment by Dinamiko** [comment]
Implemented in #490.
