### ISSUE TITLE
No translation on a multilingual site for "Pay with" on PayPal button (577)

### ISSUE THREAD

**Issue by BaltasarParreira** [woocommerce/woocommerce-paypal-payments#468]
### Describe the Bug

No translation on a multilingual site for "Pay with" on payPal button when choose button Label = "Pay with PayPal".
Text always in english.

### To Reproduce

Choose the option as described before.

### Screenshots

![image](https://user-images.githubusercontent.com/1650425/152417050-ffa5d4c1-5b36-491b-a602-8b0cdb6423f2.png)

### Expected Behavior

Previous discontinued plugin "PayPal Checkout" works without problems.

### Environment

 - WordPress Version: 5.9
 - WooCommerce Version: 6.1.1
 - Plugin Version: 1.6.5
 - Browser:  Chrome and Firefox latest versions
 - Any other plugins installed: None for payments or PayPal

**Comment by InpsydeNiklas** [comment]
@BaltasarParreira With PayPal Payments, the button locale is independent of your site locale and automatically decided by PayPal. So it doesn't matter if you switch the site language as the buttons will always be displayed in a language relevant to the user. This works differently than the previous PayPal Checkout plugin which used the WordPress locale for the buttons.

**Comment by InpsydeNiklas** [comment]
Interest in a feature to manually override the language can be expressed here: #600
