### ISSUE TITLE
Clicking on PayPal button does not check if the "I have read and agree to the website terms and conditions *" checkbox is on (448)

### ISSUE THREAD

**Issue by BaltasarParreira** [woocommerce/woocommerce-paypal-payments#469]
### Describe the Bug

Clicking on PayPal button does check if the "I have read and agree to the website terms and conditions *" checkbox is on and instead giving the error and auto close the popup PayPal window accepts and moves forward.

### To Reproduce

Simulate making a payment and this behavior is seen.

### Screenshots

![image](https://user-images.githubusercontent.com/1650425/152418925-c3d6fbeb-49cc-4f55-aae2-3aebce5b1590.png)

### Expected Behavior

Previous discontinued plugin "PayPal Checkout" works without problems and auto closes the window if terms are note accepted.

### Environment

 - WordPress Version: 5.9
 - WooCommerce Version: 6.1.1
 - Plugin Version: 1.6.5
 - Browser:  Chrome and Firefox latest versions
 - Any other plugins installed: None for payments or PayPal

**Comment by InpsydeNiklas** [comment]
@BaltasarParreira This is intentional behavior and will be changed in the future. For the moment, the checkout field validation happens after creating the PayPal order, so when the popup window is closed. No payment will be captured unless the user provides all required fields though.

**Comment by InpsydeNiklas** [comment]
This will be handled in #513, so I will close this one for now.

**Comment by InpsydeNiklas** [comment]
This will be handled in #513, so I will close this one for now.
