### ISSUE TITLE
Replace PAYPAL.FUNDING.CREDIT with PAYPAL.FUNDING.PAYLATER

### ISSUE THREAD

**Issue by Chaithi** [woocommerce/woocommerce-paypal-payments#47]
The new Pay in 4 feature is to be rolled out October 1.

In most cases, this is done automatically. However, in cases where you're using Standalone function (such as on checkout page), replace PAYPAL.FUNDING.CREDIT with PAYPAL.FUNDING.PAYLATER

**Comment by Dinamiko** [comment]
Hello @Chaithi,

Can we close this issue? seems Pay in 4 is already included in recent versions of the plugin.

**Comment by InpsydeNiklas** [comment]
This was already changed, so I'll close the issue.
