### ISSUE TITLE
Add transaction ID to WC order and order note when refund is received (537)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#473]
As part of #456 we added transaction ID into the order note, we need to add it again when a refund is received because the transaction ID is not the same as the previous one.

### Acceptance criteria
Create a refund on PayPal and then check that order and order note displays the correct transaction ID. Note that it can take some minutes until the webhook is received.

**Comment by AlexP11223** [comment]
Maybe we should also set the transaction ID of the order? (using `TransactionIdHandlingTrait`)
