### ISSUE TITLE
Improve "Disable funding sources" setting label & description (218)

### ISSUE THREAD

**Issue by Narek13** [woocommerce/woocommerce-paypal-payments#475]
### Describe the Bug

Too many customers are asking how to disable [Alternative Payment Methods](https://developer.paypal.com/docs/checkout/integration-features/alternative-payment-methods/#availability) because they oversee the Disable funding sources setting.
In other PayPal integrations, this feature is usually called Hide Funding Source(s) instead. This makes it clear that the setting is too difficult to see/understand because of inconsistent working compacted to PayPal Checkout.

### To Reproduce

1. Install and activate the plugin.
2. Complete the onboarding.
3. In the settings find the one called "Disable funding sources"

### Screenshots

<img width="895" alt="Screen Shot 2022-02-07 at 15 49 27" src="https://user-images.githubusercontent.com/11319597/152782910-61c56af6-7f4e-4cc2-8965-c7ccb5a5dc41.png">

### Expected Behavior

The label of the setting should be
> Hide Funding Source(s)

The description should go under the field instead of the tooltip and should include the following text

> By default, all possible funding sources will be shown. This setting can disable funding sources such as Credit Cards, Pay Later, Venmo, or other [Alternative Payment Methods](https://developer.paypal.com/docs/checkout/integration-features/alternative-payment-methods/#availability).

### Actual Behavior

The label of the setting is
> Disable funding sources

The description is in the tooltip

**Comment by Dinamiko** [comment]
Fixed in #477.
