### ISSUE TITLE
Allow partial capture

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#483]
We have had some merchants request the ability to do a partial capture.

Use Case: Merchant prices the items on the website at their maximum price and when they actually weigh the cuts of meat that they order, the weights usually come in lower thus the price the customer actually pays comes in lower than what they authorized.

When they go to capture the order, the only option is to capture the full authorized amount.

### Suggested solution

Documentation: https://developer.paypal.com/docs/api/payments/v2/#authorizations_capture 

Pass the current order total as `amount`.

Also maybe we should pass `final_capture=true` (if it is not the default behavior), since we never capture more than once, and I guess it can affect whether the remaining money stay locked for some time when capturing lower amount (if the capture considered not final).

**Comment by Dinamiko** [comment]
Implemented in #484.
