### ISSUE TITLE
emoji in product description causing INVALID_STRING_LENGTH error (347)

### ISSUE THREAD

**Issue by InpsydeNiklas** [woocommerce/woocommerce-paypal-payments#491]
### The problem
Depending on how it's counted, emojis may count as more than one character. 
When the product description contains text and an emoji like this 🤔 in the first 127 characters,  then the API responds with `INVALID_STRING_LENGTH` as the emoji causes the string to exceed the maximum length.

### To Reproduce
1. create a product with an emoji in the description (has to be within the first 127 characters)
2. visit the single product page and click the PayPal button
3. alternatively, add the product to the cart and click the PayPal button from the cart or checkout page
3. payment fails: `[INVALID_REQUEST] Request is not well-formed, syntactically incorrect, or violates schema. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH `

### Expected behavior
No error when checking out with a product with an emoji in the description.

### Actual Behavior
An error occurs when clicking the PayPal button and no PayPal order will be created.

### Workaround
Remove emoji from the first 127 characters of the product description. Emoji can be placed in later parts as only the first 127 characters are sent to PayPal.

### System information
PayPal Payments 1.7.0
WooCommerce 6.2.0
WordPress 5.9

**Comment by metricwebdesign** [comment]
haayy do we have an update?

**Comment by InpsydeNiklas** [comment]
The PR linked above will eventually include a fix for the issue. This will likely not yet be included in the upcoming 1.7.1 update but we expect it for the following one.
You can give it a try with the [currently proposed change](https://github.com/woocommerce/woocommerce-paypal-payments/pull/540/commits/6ba367efbd846fffeacacaf5b2cf06dcb9bb251b) as it only involves removing three characters to take effect. But while it may prevent the reported error, there will probably be further tweaks so it should be tested thoroughly before actually using it.

**Comment by metricwebdesign** [comment]
so i make the green edit to my file?

**Comment by InpsydeNiklas** [comment]
Yes, remove the red, add the green. In this case, just remove the `mbr_`, save the file, and that's it. It may not be the perfect solution quite yet but should at least prevent the error.

**Comment by soundatech** [comment]
Hello,

Unfortunately, again same problem with the product which includes emoji inside first 127 characters inside long description...

Please find this log problem, for example (I have all-new version of plugin):

`2022-05-09T15:07:34+00:00 DEBUG PATCH https://api.paypal.com/v2/checkout/orders/1M609789VC830874V
Request Body: [{"op":"replace","value":{"reference_id":"default","amount":{"currency_code":"EUR","value":"1846.20","breakdown":{"item_total":{"currency_code":"EUR","value":"1674.00"},"shipping":{"currency_code":"EUR","value":"172.20"},"tax_total":{"currency_code":"EUR","value":"0.00"}}},"description":"","items":[{"name":"C12 DIY Microphone Kit - Assembled Kit (+149\u20ac)","unit_amount":{"currency_code":"EUR","value":"748.00"},"quantity":2,"description":"","sku":"achat-c12-kit","category":"PHYSICAL_GOODS","tax":{"currency_code":"EUR","value":"0.00"}},{"name":"Premium Shockmount C12","unit_amount":{"currency_code":"EUR","value":"89.00"},"quantity":2,"description":"\ud83d\udc49Premium Shockmount C12 :Made of high quality brass, the C12 shockmount will be ideal to stabilize your microphone and allow yo","sku":"achat-c12-premium-shockmount","category":"PHYSICAL_GOODS","tax":{"currency_code":"EUR","value":"0.00"}}],"payee":{"merchant_id":"6VQZGB4FJ6GW4"},"shipping":{"name":{"full_name":"mohammad hasbullah hassan osman"},"address":{"country_code":"MY","address_line_1":"no 6, lorong bunga china, taman P.Ramlee","admin_area_1":"KUL","admin_area_2":"kuala Lumpur","postal_code":"53000"}},"custom_id":"19424","invoice_id":"WC-19424"},"path":"\/purchase_units\/@reference_id=='default'"}]
Response Debug ID: 985fd88e8ff42
Response: Array
(
    [code] => 400
    [message] => Bad Request
)

Response Body: {"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"985fd88e8ff42","details":[{"field":"/items/1/description","value":"\uD83D\uDC49Premium Shockmount C12 :Made of high quality brass, the C12 shockmount will be ideal to stabilize your microphone and allow yo","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long."}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH","rel":"information_link","encType":"application/json"}]}

2022-05-09T15:07:34+00:00 WARNING [INVALID_REQUEST] Request is not well-formed, syntactically incorrect, or violates schema. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH
2022-05-09T15:34:01+00:00 DEBUG POST https://api.paypal.com/v2/checkout/orders
Request Body: {"intent":"CAPTURE","purchase_units":[{"reference_id":"default","amount":{"currency_code":"EUR","value":"1846.20","breakdown":{"item_total":{"currency_code":"EUR","value":"1674.00"},"shipping":{"currency_code":"EUR","value":"172.20"},"tax_total":{"currency_code":"EUR","value":"0.00"}}},"description":"","items":[{"name":"C12 DIY Microphone Kit - Assembled Kit (+149\u20ac)","unit_amount":{"currency_code":"EUR","value":"748.00"},"quantity":2,"description":"","sku":"achat-c12-kit","category":"PHYSICAL_GOODS","tax":{"currency_code":"EUR","value":"0.00"}},{"name":"Premium Shockmount C12","unit_amount":{"currency_code":"EUR","value":"89.00"},"quantity":2,"description":"\ud83d\udc49Premium Shockmount C12 :Made of high quality brass, the C12 shockmount will be ideal to stabilize your microphone and allow","sku":"achat-c12-premium-shockmount","category":"PHYSICAL_GOODS","tax":{"currency_code":"EUR","value":"0.00"}}],"payee":{"merchant_id":"6VQZGB4FJ6GW4"},"shipping":{"name":{"full_name":"mohammad hasbullah hassan osman"},"address":{"country_code":"MY","address_line_1":"no 6, lorong bunga china, taman P.Ramlee","admin_area_1":"KUL","admin_area_2":"kuala Lumpur","postal_code":"53000"}}}],"application_context":{"user_action":"CONTINUE","shipping_preference":"SET_PROVIDED_ADDRESS","landing_page":"LOGIN","locale":"en-US","brand_name":"Mic & Mod","return_url":"https:\/\/www.micandmod.com\/?wc-ajax=ppc-return-url","cancel_url":"https:\/\/www.micandmod.com\/order\/"},"payer":{"name":{"given_name":"mohammad hasbullah hassan","surname":"osman"},"email_address":"mhhohq@gmail.com","address":{"country_code":"MY","address_line_1":"no 6, lorong bunga china, taman P.Ramlee","admin_area_1":"KUL","admin_area_2":"kuala Lumpur","postal_code":"53000"},"phone":{"phone_type":"HOME","phone_number":{"national_number":"601137506848"}}},"payment_method":{"payee_preferred":"IMMEDIATE_PAYMENT_REQUIRED","payer_selected":"PAYPAL"}}
Response Debug ID: b88ee6a5dfaf7
Response: Array`

**Comment by tritos-design** [comment]
Unfortunately, I have to second this. The bug is still there.

**Comment by InpsydeNiklas** [comment]
Thanks for pointing it out, it seems the testing scope for this issue was too limited.
The linked PR should be included in the next release and a test package can be [downloaded here.](https://drive.google.com/uc?export=download&id=1I2SxujQw32Jw0Qukq65Khe8pAOHIoo_y)

**Comment by dademaru** [comment]
Hi,

we had customers experiencing a similar issue and seems due to **special characters** in product description.

Example:

> This is a product description with “double quotes” and line breaks.
> Special characters are converted to longer Unicode Characters…

In latest version of `prepare_description` method you are stripping shortcodes and other HTML tags from product description and then truncating it to 127 characters:

> This is a product description with “double quotes” and line breaks.
Special characters are converted to longer Unicode Cha

But when passing it to PayPal it is JSON encoded so in the request it becomes:

> This is a product description with \u201cdouble quotes\u201d and line breaks.\r\nSpecial characters are converted to longer Unicode Cha

135 characters.

The solution could be to **truncate to 127 characters after JSON encoding** to prevent failed orders for INVALID_REQUEST > INVALID_STRING_LENGTH.

(Should I open a new issue or it's ok to comment here, since it's related?)

Thanks
