### ISSUE TITLE
Hide smart buttons for free products and zero-sum carts (500)

### ISSUE THREAD

**Issue by Narek13** [woocommerce/woocommerce-paypal-payments#499]
### Describe the Bug

Paypal doesn't not support zero-sum payments(when they are $0) so the buttons should be hidden in the cart/checkout when user adds a **$0** item to their order

### To Reproduce

1. create product with $0 price
2. smart button on single product page & cart will load
3. checkout will not work as PayPal does not support zero-sum payments

### Screenshots

![1d241ae9-b114-4a58-b278-058ab687d450](https://user-images.githubusercontent.com/11319597/154488180-f4350c4f-7d82-486b-b1e8-6f934a129c2d.png)

### Expected Behavior

Buttons should not load when the order total is $0.

### Actual Behavior

Buttons are loaded

**Comment by Dinamiko** [comment]
Fixed in #500.
