### ISSUE TITLE
Subscriptions Support Testing

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-paypal-payments#50]
I've enabled subscriptions support by defining `PPCP_FLAG_SUBSCRIPTION` and enabled the vault setting in settings but noticing a few issues with Subscriptions:

**General Issues**
- [ ] "Vaulting - Enable Vaulting". This setting isn't clear that it's needed for Subscriptions support. I do see the setting tool tip mentions it but I wonder if we need to be more clear or use a different term instead of Vaulting. Some common phrases used in other gateways is "Tokenization" or "Save Profiles". Thoughts?
- [ ] When the "vaulting" setting is enabled the credit card form looks off: https://d.pr/i/UIoRi4 :x:
- [ ] Deprecated subscription function is being used :x:

```
[30-Sep-2020 03:43:04 UTC] PHP Deprecated:  WC_Subscriptions_Manager::process_subscription_payment_failure_on_order is <strong>deprecated</strong> since version 2.6.0 with no alternative available. in /Users/matt/local/store/wp-includes/functions.php on line 4801
```

**PayPal Checkout & PayPal Card Processing**

- [x] Subscription and parent order both look good ✅ 
- [ ] Processing a renewal order results in on-hold subscription and pending payment order :x:

**Comment by jorgeatorres** [comment]
Fixed in 1.3.0 & 1.3.2.
