### ISSUE TITLE
Partial refunds via PayPal are created twice/double in WooCommerce order (583)

### ISSUE THREAD

**Issue by snandos** [woocommerce/woocommerce-paypal-payments#522]
### Describe the Bug

PayPal partial refunds via WooCommerce backend result in two refund entries in the order details view of WooCommerce

### To Reproduce

1. Create a partial refund in the backend of WooCommerce and use "Refund via PayPal" button.
2. The refund entry is successfully created in the backend 
3. PayPal correctly refunds the amount to the customers bank account / debig card / credit card etc.
4. PayPal sends back a webhook about the successful refund
5. PayPal Payments plugin creates a new refund entry to the order instead of updating the existing one.
6. You now have two refunds in the order details of WooCommerce

### Screenshots

![grafik](https://user-images.githubusercontent.com/42617635/156157836-5ee92fdf-d09c-4a29-a37e-01462392cca0.png)

### Expected Behavior

Don't create a second refund entry if it already exists

### Actual Behavior

Creates the refund a second time.

### Environment

 - WordPress 5.9.1
 - WooCommerce 6.2.1
 - Plugin Version 1.7.0 (but happens to previous versions also, problem is therefore not new)
 - WooCommerce Germanized 3.8.3
 - WooCommerce Germanized Pro 3.4.1
 - Firefox

**Comment by InpsydeNiklas** [comment]
@snandos Can you reproduce the behavior in the PayPal Sandbox as well or only in live mode? So far, we haven't been able to reproduce it internally.

**Comment by ragian** [comment]
I have the same issue and I'm able to reproduce it in Paypal Sandbox
wordpress Version  Version 5.9.2 
woocommerce Version 6.3.1
woocommece paypal Version 1.7.0

**Comment by delitestudio** [comment]
Same issue here...

**Comment by InpsydeNiklas** [comment]
If you can reproduce the behavior in the sandbox, then please [send us a message from here](https://paypal.inpsyde.com/docs/request-support/) with a reference to this issue.

While there are some isolated reports about this behavior, we haven't yet had the chance to look into it further, so if you could for example provide a staging environment where the behavior can be reproduced, it would help us a lot in addressing it. In some cases, resubscribing to the webhooks did eventually resolve the behavior but seemingly not for everyone. It's worth trying if you haven't already though.
Thanks!

**Comment by delitestudio** [comment]
Ok, thanks for the reply, we tried resubscribe the webhooks. However, it would not be important to put a check in your plugin to avoid that if there is already a refund, it does not do it a second time?

**Comment by snandos** [comment]
Sorry for my late response.
I have now created a sandbox system with WordPress + WooCommerce + PayPal Payments Plugin and basic settings. I can confirm this bug also happens in the PayPal Sandbox mode.
@InpsydeNiklas I'll create a ticket and will send over the details and credentials of the sandbox shop. Thanks!

**Comment by Tonimerc** [comment]
Also having this issue and not been able to resolve it so would be interested if a solution is found.

**Comment by MadMaxInfinity** [comment]
Same issue on my side. I hope thanks to @snandos you'll be able to find a solution.
At least, finding this a known bug, our accountant stopped pumping his head on a wall searching for ghost refunds... 😃

**Comment by snandos** [comment]
Since this problem isn't fixed yet and led to problems with our invoicing plugin, I've looked for a workaround which fixes the issue in the meantime.

It's quite simple: Turn off webhook events regarding refunds in the PayPal Developer dashboard.

In the PayPal Developer dashboard you need to get to your "app" (e.g. "WooCommerce Shop"). There you can find all registered webhooks (which should be just one). You can click on the pencil icon to get to the edit screen of this webhook. Then uncheck all refund types, like "Payment capture refunded".

Of course the shop staff is not allowed to refund items in the paypal dashboard anymore, since this would lead to inconsistencies. Also this won't work if you have another app of some kind, which interacts with the PayPal API directly and you need to get those refunds from PayPal into your WooCommerce shop.

**Comment by t-bo** [comment]
I don't understand how they prioritize the issues for their plugin. 
This one should have been fixed long time ago. 

Still ongoing with 1.8.0 test 1 version.

**Comment by Turner-Mike** [comment]
I'm very disappointed that this hasn't been sorted, yet. I raised it almost five months ago - see https://wordpress.org/support/topic/partial-refunds-duplicated/ .

One thing worth adding is that it only shows up if the refund is less than half of the total. If it is more than half, the refund second refund is rejected.

I have actually had one occasion, on my sandboxed testing system where I have had three refunds, if the initial refund was less than a third of the total.

**Comment by bastiancgn** [comment]
We are also waiting for an update and are facing the problem since 4 month now…

We do a part refund of one item, paypal sends the money back but there are two refunds in woocommerce…

Thanks and kind regards,
Bastian

![image](https://user-images.githubusercontent.com/56078309/164003588-05bbd31c-0a64-4973-8d27-16dace4978f0.png)

**Comment by AlexP11223** [comment]
We had difficulties reproducing it, but now we are working on it :) 

> I have had three refunds

That's strange, do you have WC logs with this?

**Comment by Turner-Mike** [comment]
Logs sent by email.

**Comment by kbalicki** [comment]
We have exactly the same problem (and that is why I googled this ticket). Woo and other plugins are up to date. Have anybody found some temp workaround?

**Comment by InpsydeNiklas** [comment]
The issue has been resolved for the upcoming 1.8.1 update and can be tested with [a pre-release version from here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/1.8.1-test1).
Big thanks to everyone for providing feedback.

**Comment by bbdetail** [comment]
Hello. I am seeing this exact bug again in Version 2.0.3. Following the exact steps in the original post. Should I file a new bug report?

Below you can see the first refund initiated by the shop manager, and then 3 minutes later, another refund made by the system.

![woo-double-refund-bug](https://user-images.githubusercontent.com/11225433/228317726-c9e0e009-b0d4-4132-9776-18b3e4fc6d7d.jpg)

**Comment by WillPresley** [comment]
Following intently, as I have a client who would be furious if this bug has regressed!

**Comment by 4n0n1mo** [comment]
No fix yet?

**Comment by d-den** [comment]
I'm seeing the same issue here. When refunding via the button that refunds via the payment provider it registers a partial refund with two different users. The first user is the user logged in. The second user is an old administrator but is has a client role. Can this be reopened or should I create a new ticket for this?
