### ISSUE TITLE
Manual orders return an error for guest users when paying with PayPal Card Processing (580)

### ISSUE THREAD

**Issue by InpsydeNiklas** [woocommerce/woocommerce-paypal-payments#530]
### Describe the Bug

When a manual order is created and the payment link is sent to the customer, there may be an error when attempting to complete the purchase with the PayPal Card Processing while the customer is not logged-in:
`Cardholder's first and last name are required, please fill the checkout form required fields.`
![image](https://user-images.githubusercontent.com/70433191/157862591-3a5ec0ed-ba5c-4a5b-abfd-4cf19cd2702f.png)

### To Reproduce

1. From the WooCommerce Orders page, manually add a new order
2. Fill in the details for the new order: Add a product, customer email address (mandatory), etc.
3. Save the order 
4. Open the payment link with the "pay for order" page as a guest (while not logged in as a user)
5. From the pay for order page, confirm you are not logged in and pay with Credit Card (PayPal Card Processing).
6. Error occurs.

### Expected Behavior

Credit card payment is successful when all required details are provided in the order and the customer is not logged in.

### Actual Behavior

Error about missing `Cardholder's first and last name` despite the information being present in the WooCommerce order when confirming purchase while not logged in.

### Workaround

The credit card payment will be successful when the customer is logged into a WordPress account.

### Environment

 - WordPress Version 5.9.1
 - WooCommerce Version 6.2.2
 - PayPal Payments 1.7.0

**Comment by t-bo** [comment]
Please mark this as critical. No manual payment can currently be done.

**Comment by panilo** [comment]
HEllo, any update on this?

**Comment by propanehunter** [comment]
Issue still exists.  Anyone working on a solution?

**Comment by Dinamiko** [comment]
Fixed in #641, will be included in 1.9.0 release.
