### ISSUE TITLE
Checkout page invalid input not captured until after proceeding to "Pay Now" with a PayPal payment option

### ISSUE THREAD

**Issue by user-1138** [woocommerce/woocommerce-paypal-payments#531]
### Describe the Bug

Invalid input on the WooCoomerce Checkout page is not captured until after the customer has clicked through to their choice of PayPal payment method and clicked the final "Pay Now" button. Only then is the invalid input captured and the customer is returned to the Checkout page, which then (per usual) auto-scrolls up to the Error Notice advising them of what fields they botched (e.g. missing address field, unchecked T&C's checkbox, etc...).

Once the invalid input is corrected, the customer must then redo the entire PayPal process - particularly annoying for those choosing a "Buy now, pay later" option like Pay in 4 (which have a few hoops to jump through than standard PayPal).

So obviously and ideally, checkout fields would be validated before proceeding to the PayPal pop-up (like other payment methods do, including the old PayPal Standard).

### To Reproduce

1. Add product/s to Cart
2. Go to the Checkout page
3. Leave checkout field/s in an invalid state (e.g. missing address field, unchecked T&C's checkbox, etc...)
4. Proceed with a PayPal payment option.
5. In the PayPal pop-up window, click through to the "Pay Now" button.
6. Checkout fields are now finally validated, the PayPal pop-up window closes, and the WooCoomerce Error Notice is displayed at the top of the checkout page.

### Expected Behavior

Ideally, checkout fields would be validated before proceeding to the PayPal pop-up (like other payment methods do, including the old PayPal Standard).

### Environment

 - WordPress Version 5.9.2
 - WooCommerce Version 6.3.1
 - Plugin Version 1.7.0
 - Browser [e.g. Chrome, Safari] and Version - Firefox 91.7.0esr (64-bit)
 - Any other plugins installed - POLi Payments for WooCommerce 4.3, WooCommerce Stripe Gateway 6.3.0, Wordfence Security 7.5.8.
 
### Additional Details

Other payment options enabled during testing included Stripe Credit Cards, POLi Payments, and Direct bank transfer.

**Comment by InpsydeNiklas** [comment]
More information can be found in #513 where it will also be handled so I'm closing this issue.
