### ISSUE TITLE
Naff "WooCommerce Developers" wording when connecting a PayPal account. (701)

### ISSUE THREAD

**Issue by user-1138** [woocommerce/woocommerce-paypal-payments#532]
### Describe the Bug

After installing the plugin and proceeding to the pop-up window to connect a PayPal account, three times (once at the very start and twice at the very end of that process) the term "**WooCommerce Developers**" is used. This is weird wording and might frighten off the less technically inclined.

### To Reproduce

1. Install the plugin
2. Initiate the process to connect a PayPal account.
3. "WooCommerce Developers" is mentioned three times, per attached screenshots.

### Screenshots

![Connect-Account-First-Screen](https://user-images.githubusercontent.com/21233532/158004475-f5dbdaa8-0de0-42fd-812d-ef177fe06494.png)
![Connect-Account-Last-Screen](https://user-images.githubusercontent.com/21233532/158004480-724095b9-c1a0-4620-8718-cf4e9f1b7015.png)

### Expected Behavior

Just "WooCommerce" would suffice in my books.

### Actual Behavior

Per description.

### Environment

NA

### Additional Details

NA

**Comment by InpsydeNiklas** [comment]
This was recently changed and now it should only say "Back to WooCommerce".
