### ISSUE TITLE
Pay for order (guest) failing when no email address available (564)

### ISSUE THREAD

**Issue by Narek13** [woocommerce/woocommerce-paypal-payments#535]
### Describe the Bug

When manually creating orders in WooCommerce backend and sending the link to the buyer, the payment with PayPal Payments will fail unless there is an email entered in the billing address email field.

![c7d8a054-f75c-4952-a97e-713107cba7b5](https://user-images.githubusercontent.com/11319597/158362247-579b455e-81f6-47f1-8074-a3c1191b9a97.png)

### To Reproduce

1. With "Add order" in WC backend , create guest order with **no email address**.
2. Visit payment link, attempt to pay with PayPal Payments.
3. Payment will fail.
4. Add an email address to order from the backend:
![9b2889c9-659d-4288-b205-80aed8c14de1](https://user-images.githubusercontent.com/11319597/158362604-f795b9b0-28f4-4e08-9dc9-ed6f016124e6.png)
→ PayPal popup window opens without error and payment will succeed.

### Screenshots

![c7d8a054-f75c-4952-a97e-713107cba7b5](https://user-images.githubusercontent.com/11319597/158362247-579b455e-81f6-47f1-8074-a3c1191b9a97.png)

### Expected Behavior

Guest orders can be paid for without entering an email address.

### Actual Behavior

Guest order payment is failing.

**Comment by Dinamiko** [comment]
Fixed in #536.
