### ISSUE TITLE
Incorrect TAX details on PayPal order overview (590)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#541]
### Describe the Bug

The tax amounts that are shown in the PayPal order overview are incorrect. 
The tax amounts from the shipping are added to the shipping costs in the PayPal dashboard and not to the tax.

### To Reproduce

1. enable taxes 
2. create tax rates (one or more)
3. create shipping zone and Shipping methods which are Taxable
4. buy product with taxes and shipping costs

### Expected Behavior

The taxes from the shipping costs should be sent as part of the tax instead of part of the shipping amount.

### Actual Behavior

The taxes that were added for the shipping costs will be displayed under “shipping amount” instead of “Sales tax” in the PayPal dashboard

### Environment

 - WordPress Version: 5.9
 - WooCommerce Version: 6.3
 - Plugin Version: 1.7.0

**Comment by Dinamiko** [comment]
It needs to handle more cases:
- When item quantity is greater than 1.

**Comment by EricaKuschel** [comment]
Hallo @Dinamiko! On April 4 it looks like this was supposed to be added to the [next version](https://github.com/woocommerce/woocommerce-paypal-payments/milestone/9) after `1.7.1`. Being that we are on `1.8.1`, was this added? I don't see mention of #541 in the changelog notes. 

Thanks!

**Comment by Dinamiko** [comment]
Hello @EricaKuschel, 

Unfortunately it was not included as it was causing issues in other parts of the code, we are still working on this issue hoping we'll finish it soon.
