### ISSUE TITLE
Confusion between Pay Later messaging settings vs "Pay Later" as a funding source 

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#543]
### Describe the Bug

Some users are having trouble with the difference between Pay Later as a funding source and the Pay Later messaging settings. [For example](https://developer.woocommerce.com/2022/03/10/woocommerce-3-5-10-6-3-1-security-releases/#comment-9597):

> Currently trying to make the switch to the PayPal Payments plugin but despite “Pay Later on Checkout” being unselected, clicking “Enable buttons on Checkout” enables both the PayPal and PayPal Later buttons. Am I missing something?

Personally, I'd suggest that we:

1. Disable all Pay Later messaging sections when "Pay Later" is hidden as a funding source in *PayPal Checkout Settings > Hide Funding Source(s)*. Makes little sense to allow users to customize messaging settings that won't really be of use.
2. When Pay Later messaging is disabled in a specific context (say, Checkout, as in the example above) the "Pay Later" button should also be hidden in that context.

One could argue that some users might want to hide the messages but keep the button. I can't say if this would be a majority of users, but maybe the trade-off described above is reasonable given the most those users could gain is not seeing a line of text, while users trying to accomplish the opposite actually get a payment method they don't want.

In any case, the settings are a bit confusing as it's not clear how to disable the Pay Later button in a context (not really possible atm). Maybe we could add a "Pay Later" parent setting per context (e.g.: "Enable Pay Later on Checkout") and make the messaging toggle a child of that setting (allowing users to hide/display the button _and_ the messaging per context) or make sure the help text makes it clear that the button might still appear.

### To Reproduce

1. Go to WC > Settings > PayPal.
2. Scroll down to "Pay Later on Checkout" and make sure the toggle is not checked off.
3. On the frontend, add some items to the cart and go to the Checkout screen.
4. If eligible, the Pay Later button still appears despite the messaging being turned off.

**Comment by InpsydeNiklas** [comment]
This was improved in version 2.0.0 with the introduction of the [Pay Later tab](https://woocommerce.com/document/woocommerce-paypal-payments/#pay-later-tab).
