### ISSUE TITLE
AJAX urls call home_url twice

### ISSUE THREAD

**Issue by abonnell** [woocommerce/woocommerce-paypal-payments#546]
### Describe the Bug

When the PayPal plugin constructs it's AJAX urls it requests the WC_AJAX endpoint but wraps it in home_url() when, by default, the WC_AJAX endpoint is already constructed using home_url(). This results in PayPal ajax calls being nested an extra path deep

WooCommerce Standard AJAX path: `/home-url?wc-ajax={XXX}`
WooCommerce Paypal Payments AJAX path: `/home-url/home-url?wc-ajax=ppc-create-order`

### To Reproduce

1. Set up the PayPal plugin for your storefront
2. Go to the checkout page and opt to use PayPal
3. Note the URL for the `wc-ajax=ppc-create-order` AJAX request in comparison to the URLs for `wc-ajax=update_order_review`

### Expected Behavior

The PayPal plugin should use the same AJAX path as default WooCommerce installations

### Actual Behavior

The PayPal plugin nests its WC-AJAX endpoints one home_url deeper than default WooCommerce does

### Environment

 - WordPress Version: 5.9.2
 - WooCommerce Version: 5.6.1
 - Plugin Version: 1.7.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome 99.0.4844.74
 - Any other plugins installed: None relevant

**Comment by InpsydeNiklas** [comment]
Thanks for the report.
This issue has already been resolved for the next plugin version in https://github.com/woocommerce/woocommerce-paypal-payments/pull/529.

**Comment by abonnell** [comment]
Oh awesome, didn't see another issue for this. Thanks! Do you guys have an eta?

**Comment by InpsydeNiklas** [comment]
A new pre-release version is expected later this week here on the GitHub release section.
Everyone is welcome to provide early feedback on these versions as our own testing usually takes roughly a week before it will be released officially.

**Comment by abonnell** [comment]
Thanks much!
