### ISSUE TITLE
Wrong ajax endpoint in js var PayPalCommerceGateway when WordPress installed in subfolder

### ISSUE THREAD

**Issue by ivankuraev** [woocommerce/woocommerce-paypal-payments#547]
### Describe the Bug

When WordPress installed in subfolder, wp_localize_script for PayPalCommerceGateway generate wrong endpoint url, because in SmartButton.php uses this code to generate url

home_url( \WC_AJAX::get_endpoint( CreateOrderEndpoint::ENDPOINT ) );

but \WC_AJAX::get_endpoint() already return value with subfolder, and home_url() include full path in url.

### Environment

 - WordPress Version 5.9.2
 - WooCommerce Version 6.3.1
 - Plugin Version 1.7.0

**Comment by InpsydeNiklas** [comment]
Thanks for the report. Though this issue has already been resolved for the next plugin version in #528 & https://github.com/woocommerce/woocommerce-paypal-payments/pull/529.
