### ISSUE TITLE
PayPal Buttons not visible anywhere after activation

### ISSUE THREAD

**Issue by ateufel** [woocommerce/woocommerce-paypal-payments#564]
I have tried with different Themes, and activated PayPal on single product page, checkout and cart. Paypal is connected successfully and simulating the Webhook status works too. Is there anything I need to do in addition to connecting the Paypal account, activating the payment option and activating the Paypal button for different pages in the plugin options?

* WordPress 5.9.2
* Theme: Current Storefront, Current Atomion
* WooCommerce 6.3.1
* WooCommerce PayPal Payments 1.7.0

I have used the "WooCommerce PayPal Checkout Gateway" Plugin and it worked fine with that one, but it is deprecated.

**Comment by InpsydeNiklas** [comment]
Hi @ateufel,  
Please open a support ticket with a copy of your system report from here and we'll look into this with you: https://paypal.inpsyde.com/docs/request-support/
Thanks!
