### ISSUE TITLE
[RC] Console errors in the Checkout page (619)

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-paypal-payments#568]
### Describe the Bug

There are errors in the browser console when visiting the Checkout page.

This doesn't seem to be affecting the payment flow as I can still check out correctly, but we shouldn't have errors in the console.

### To Reproduce

1. Add a product to the cart
2. Go to the Checkout page
3. Notice the errors in the console. [Here's a video](https://d.pr/v/38BAVD) with the behavior, also displaying the settings I have in case it's relevant 
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/41606954/161591207-edf31d1d-cc9b-443a-90c9-0a574d142a11.png">

### Expected Behavior

No errors should show up in the console.

### Actual Behavior

Some errors show up in the console.

### Environment

 - WordPress Version: 5.9.2
 - WooCommerce Version: 6.3.1
 - Plugin Version: 1.7.1-test2
 - Browser and Version: Chrome 99.0.4844.84
 - Any other plugins installed: None

**Comment by InpsydeNiklas** [comment]
It seems this only happens when either the Pay Later messaging or the Pay Later button is loaded on the page. Disabling Pay Later via `Hide Funding Source(s)` appears to prevent the error.

**Comment by InpsydeNiklas** [comment]
This error was resolved a while back.
