### ISSUE TITLE
[RC] Can't complete an order with a card that requires 3DS

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-paypal-payments#570]
### Describe the Bug

Can't complete an order when paying with a card that requires 3DS.

### To Reproduce

1. Make sure Card Processing is enabled'
2. On the Card Processing settings page, make sure that "Contingency for 3D Secure" is set to "Always trigger 3D Secure"
3. Go to the store, add a product to your cart, and proceed to checkout
4. Select "Credit cards" as the payment method
5. Fill in the credit card details
6. Notice that the modal window for 3DS shows up, but then gets closed and an error message shows up saying `Something went wrong. Please try again or choose another payment source`. There are also some errors in the console. [Here's a video](https://d.pr/v/o1XJXF) with the behavior and with the Card Processing settings in case they're relevant

### Expected Behavior

The customer must be able to complete an order when using 3DS. I'm using the same cards that used to work in previous pre-release package tests. Glad to learn if I'm missing something.

### Actual Behavior

The payment processing fails with an error message.

### Environment

WordPress Version: 5.9.2
WooCommerce Version: 6.3.1
Plugin Version: 1.7.1-test2
Browser and Version: Chrome 99.0.4844.84
Any other plugins installed: None

**Comment by InpsydeNiklas** [comment]
Hi @a-danae, the card used in the video is a 3DS v1 card which will no longer work with PayPal Card Processing ever since PayPal fully ramped 3DS v2.
To test 3DS v2, please use the cards mentioned in the documentation here: https://woocommerce.com/document/woocommerce-paypal-payments/#testing-acdc-feautres-sandbox

**Comment by a-danae** [comment]
Hey @InpsydeNiklas ! That was it. I've updated the testing instructions and I'm closing this issue. Thanks! 🙌
