### ISSUE TITLE
Cannot use emojis in product description

### ISSUE THREAD

**Issue by tritos-design** [woocommerce/woocommerce-paypal-payments#576]
### Describe the Bug

When using emojis in the product description, the PayPal payment gets rejected with the following error message:

`{"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"dad8177f358e8","details":[{"field":"/purchase_units/@reference_id=='default'/items/1/description","value":"\uD83D\uDE0DJuuuuhuuuu - Unser supergeniales Produkt ist zur Abwechslung mal salzig!!!\uD83E\uDDC2\r\nUnd ein bisschen spicy noch dazu\uD83C\uDF36️\uD83D\uDC83\r\n\r\nPURELY - P","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long."}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH","rel":"information_link","encType":"application/json"}]}`

### To Reproduce

Add emojis (maybe in general special Unicode characters) to a product description, place an order and try to pay via PayPal.

### Expected Behavior

The payment works. (Maybe invalid characters are escaped.)

### Actual Behavior

The payment fails with the error message as shown above.

### Environment

 - WordPress Version: 5.9.2
 - WooCommerce Version: 6.3.1
 - Plugin Version: 1.7.1
 - Browser [e.g. Chrome, Safari] and Version: any
 - Any other plugins installed: Germanized for WooCommerce 3.8.4 & Germanized for WooCommerce Pro 3.4.3

**Comment by InpsydeNiklas** [comment]
Hi @tritos-design, You can find a linked pull request with a proposed fix in #491, so I will close this. It's a simple change and should be easy to apply if you'd like to give it a try.
 I can't say if it will stay like this, but it is one way to work around the error and a final fix will likely be included in the next update 1.8.0.
