### ISSUE TITLE
Allow free trial subscriptions (PCP-475)

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#580]
Currently it´s not possible to purchase a free subscriptions because it´s not possible to place an order with zero amount in PayPal. To provide a solution for this problem we could use the “one dollar auth and void afterwards” approach for cards and vaulting without payment for PayPal.

https://developer.paypal.com/limited-release/vault-payment-methods/vault-api/

**Comment by Dinamiko** [comment]
Implemented in #581.
