### ISSUE TITLE
feature request: option/filter to disable smart buttons (189)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#588]
Some merchants were asking for a way to disable the smart buttons (PayPal, Credit Card & other funding sources) and instead only display the default WooCommerce "Place order" button.

The PayPal Checkout Gateway plugin has a filter/setting, that allows disabling the smart buttons:
[https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/trunk/includes/class-wc-gateway-ppec-settings.php#L145](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/trunk/includes/class-wc-gateway-ppec-settings.php#L145)

This filter can disable the smart buttons from the [PayPal Checkout](https://docs.woocommerce.com/document/paypal-express-checkout/#section-27) plugin:
`add_filter( 'woocommerce_paypal_express_checkout_disable_smart_payment_buttons', '__return_true' );`

I built a plugin file with the filter for easier testing:

disable-smart-buttons.zip (available with SD ticket)
[PayPal Checkout ](https://docs.woocommerce.com/document/paypal-express-checkout/#section-27)

Would it be feasible to develop a feature that disables the smart button and forces PayPal payments through the regular “Place order” button without the Javascript workflow?

Especially considering the fact that PayPal Standard is no longer available and PayPal Checkout will be sunset soon, we need to have a way for merchants to provide a PayPal payment method for customers that do not use a supported browser for the JSSDK.
As we need to clarify the browser support for the JSSDK in [PCP-224: clarify browser support for PayPal JSSDKBACKLOG](https://inpsyde.atlassian.net/browse/PCP-224) we need to bring this up with PayPal as well.

**Comment by Squeezemind** [comment]
Please add this feature on next release

**Comment by InpsydeNiklas** [comment]
PayPal decided against adding functionality for this.
So for the time being, PayPal Payments only implements the PayPal smart buttons.
