### ISSUE TITLE
Feature request: Option to disable PayPal for subscriptions (546)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#593]
Some users are looking for an option to disable PayPal Payments for subscription products entirely.

The PayPal Standard integration did not show up in the checkout when its subscription functionality was disabled even when the WooCommerce Subscriptions plugin has manual renewals enabled.

When Vaulting is disabled in PayPal Payments, the gateway will still show up when manual renewals are accepted.

This could be considered a PayPal Standard parity feature. But is only interesting for a niche group of users.

**Comment by HuthDev** [comment]
With pay later enabled you cannot have vaulting enabled. This causes subscriptions through paypal to fail because we cannot save their email. Please advise on how we can disable pay later/paypal on subscriptions.

**Comment by InpsydeNiklas** [comment]
This is part of update 2.3.0.
