### ISSUE TITLE
add custom args in order to modify the PayPal invoice with custom data (337)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#596]
A user would like to modify the PayPal invoice with custom data.

They are using this filter:
```
add_filter('woocommerce_paypal_args', 'th_custom_field_to_paypal', 10, 2);
function th_custom_field_to_paypal($paypal_args, $order){
 
	foreach ( $order->get_items() as $item_id => $item ) {
		$colors = wc_get_order_item_meta( $item_id, '_WCPA_order_meta_data');
		if($colors != ''){
			$paypal_args['item_name_1'] = 'Chosen colors - '. $colors[0]['value'];	
			break;
		}
	}
	return $paypal_args;
}
```
This code does not work with PayPal Payments though.

The PayPal Checkout plugin provides filters to modify line items:
[Add hooks to change name/description of line items sent to PayPal by jorgeatorres · Pull Request #869 · woocommerce/woocommerce-gateway-paypal-express-checkout](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/869)

**Comment by omarmhd** [comment]
I have the same problem

**Comment by InpsydeNiklas** [comment]
This has been addressed in https://github.com/woocommerce/woocommerce-paypal-payments/pull/538. 
[This filter](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#modify-the-order-creation-request-body-data) can be used to modify the order creation request body data
