### ISSUE TITLE
Smart buttons not translated on iOS devices (294)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#597]
**The problem**
The text on the smart button does not get translated to German when using IOS device. For Windows and Android devices this does not occur.

**Steps to reproduce**
- Setup a store for Germany with Euros and a German Merchant account.
- Activate the pay later button on Checkout.
- Make a purchase on an iOS device like an iPhone or iPad
- → The smart buttons will be translated to German with Android & Windows devices, but not with an iOS device. 
The Pay Later button for German merchants is always called “ Später Bezahlen”, because every region has a specific Pay Later button. (E.g. for Australia “Pay in 4”)
![image](https://user-images.githubusercontent.com/78153894/163176584-66a02143-7a32-43a0-845c-2be235e7103f.png)

**Expected behaviour**
All buttons should be translated automatically to German when the user fits the criteria from PayPal.
A feature as proposed in [PCP-190: feature request: override language used to display PayPal buttonsBACKLOG](https://inpsyde.atlassian.net/browse/PCP-190) may help resolve this issue when the merchants only want the buttons to be displayed in one language anyway.

**Possible cause**
We are expecting PayPal to return variable values from gathered details (system, browser & country) when it should only check the country selection. It should also be the same for both buttons (as now it seems to have a separate process for the two)

**Comment by InpsydeNiklas** [comment]
Not an issue anymore.
