### ISSUE TITLE
upgrade subscription end up with original subscription (281)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#598]
The problem
****When you upgrade your current variable subscription to a more expensive one, everything seems to be flowing ok, except that when you get the confirmation you end up still having the cheaper subscription.

**Steps to reproduce**
- Enable allow switching in Subscription settings: 
![image](https://user-images.githubusercontent.com/78153894/163177719-88302e0e-5c06-4a2b-afe1-4f251e644ded.png)
- Backend: Create variable subscriptions with cheap and expensive options. I set up the upgrade of the subscription in the way that for the upgrade you only have to pay the difference of the price already paid for the cheap version.
- Frontend: buy a cheap option.
- Backend: Activate the cheap subscription.
- Frontend: go to: My Account > subscriptions > Press “Upgrade or Downgrade" > Chose the expensive subscription and follow the checkout process.

Now when you check the email received for this purchase you still see that the cheap subscription has been purchased.
Also the subscription under “My Account” will still show the cheap subscription.

On the Related orders page, you will see that the expensive order was purchased, but it will not reflect anywhere else.
Probably related is that I also do not see the expensive purchase in the backend subscription list.

A side issue is that once the payment has been captured, the order stays on “processing”.

**Expected behaviour**
After the upgrade has been paid for it should:
- send an email with a purchase confirmation of the expensive subscription
- reflect the expensive subscription in “My Account” > subscriptions

**Suggested solution**
merchant informed that this does work correctly with Stripe…

**Comment by InpsydeNiklas** [comment]
It appears to work as expected.
