### ISSUE TITLE
add toggle for Subtotal Mismatch Behavior (255)

### ISSUE THREAD

**Issue by Sirvijver** [woocommerce/woocommerce-paypal-payments#599]
Internally, WC calculates line item prices and taxes out to four decimal places; however, PayPal can only handle amounts out to two decimal places (or, depending on the currency, no decimal places at all). Occasionally, this can cause discrepancies between the way WooCommerce calculates prices versus the way PayPal calculates them. If a mismatch occurs, this option controls how the order is dealt with so payment can still be taken.

I propose adding a setting called Subtotal Mismatch Behavior with these two options:
-add another line item
-do not send line items to PayPal

During development, somehow PayPal decided to make “do not send line items to PayPal” the default upon subtotal mismatch.

**Comment by InpsydeNiklas** [comment]
This setting was added in 2.3.0 in the Connection tab, so I'm closing this issue.
