### ISSUE TITLE
Empty payer data may cause CITY_REQUIRED error for certain checkout countries (615)

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#632]
Checkout via product/cart buttons may not work for logged-out users when the country is set to specific locations like Vietnam.

### To Reproduce

1. set WooCommerce store location country to Vietnam
2. set Default customer location is to Store country/region
3. alternatively, just set Vietnam as a checkout country when testing
4. log out and navigate to a single product page
5. make sure Vietnam would be the selected country
6. click PayPal smart button on single product page while not logged in
7. API error occurs: `[UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-CITY_REQUIRED`

### Possible cause

It happens because it is a country without postal code and this check for removing shipping fails.
https://github.com/woocommerce/woocommerce-paypal-payments/blob/d18df34e9bafd21c2a63e73a36ec37cbb1c46ec8/modules/ppcp-api-client/src/Factory/PurchaseUnitFactory.php#L164

It seems like this check is actually supposed to be “is this shipping address valid”, not just country + postal code. Because I doubt that it is enough for a valid address, it probably just happens so that the postal code is usually filled when the rest of the fields are filled too.

For example it also fails for logged in users with some address fields deleted in the account.

**Comment by raywick** [comment]
Hi! 

This issue is still happening with Ecuador. I have the last version of the plugin, but I still receive the same error. Should I create a new issue?
