### ISSUE TITLE
no plugin extendability found

### ISSUE THREAD

**Issue by shashank-cedcoss** [woocommerce/woocommerce-paypal-payments#636]
there is no hook or filter to support custom subscription type product and use the paypal transaction token for recurring payments.
how to use this plugin to extend for other subscription plugin ?

**Comment by InpsydeNiklas** [comment]
The plugin can be extended with a custom module from here https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#adding-modules-and-accessing-the-plugin-container
I hope that helps!

**Comment by shashank-cedcoss** [comment]
Thanks @InpsydeNiklas for quick response, mainly I am working on a subscription plugin and I want to use paypal transaction token for recurring payments but I haven't found any way to use that.
Can you please tell me specifically from where I can find the transaction token in your plugin, or how can I fetch that token and use it in our plugin.
Thanks

**Comment by AlexP11223** [comment]
> paypal transaction token for recurring payments

If you mean [vaulting](https://developer.paypal.com/limited-release/vault-payment-methods/), then it can be retrieved using the API mentioned in the docs, [`GET /v2/vault/payment-tokens`](https://developer.paypal.com/api/limited-release/payment-tokens/v2/#payment-tokens_tokens).

It's unclear how do you want to use our plugin for that. There is [`PaymentTokenEndpoint`](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-api-client/src/Endpoint/PaymentTokenEndpoint.php) class implementing this request. If using the module approach mentioned above, it is the [`'api.endpoint.payment-token'`](https://github.com/woocommerce/woocommerce-paypal-payments/blob/c3887bec7aa2c868a461c859758dd5bae5537dc3/modules/ppcp-api-client/services.php#L112) service in the container.

**Comment by InpsydeNiklas** [comment]
If any questions remain, please [get in touch with the support team](https://woocommerce.com/wp-admin/post.php?post=8738362&action=edit#get-help). Thanks!
