### ISSUE TITLE
Cant' refund : "ERROR Refund failed: No country given for address." for orders created with 1.71 after updating from 1.71 to 1.8 (681)

### ISSUE THREAD

**Issue by eddr** [woocommerce/woocommerce-paypal-payments#639]
### Describe the Bug

- latest WC and WP
- Plugin version 1.71 : works well
- Updated to 1.8 and can't refund via PayPal, getting general error message. Logs say
"ERROR Refund failed: No country given for address."

### To Reproduce

- Create an Order paid with PP with plugin version 1.71 with country "Israel"
- Update plugin to 1.8
- Try to refund

### Expected Behavior

Refund accepted

### Actual Behavior

error message, refund was not completed on WC side nor PP side

### Environment

latest WC, WP
Plesk + NGINX on Nublue VPS

 - WordPress Version : 5.9.3
 - WooCommerce Version : 6.4.1
 - Plugin Version : 1.7.1, 1.8
 - Browser [e.g. Chrome, Safari] and Version : Firefox, Chrome, latest
 - Any other plugins installed : Many, but tested with WC only

**Comment by InpsydeNiklas** [comment]
@eddr We are seeing some reports about this but can't reproduce the behavior with the provided steps. The reports are also coming across multiple plugin versions so we are not seeing a direct relation to the latest update.
Can you reproduce this only in live mode or also with Sandbox orders?
When going back to 1.7.1, does the refund work for you?
Thanks!

**Comment by pschroeder89** [comment]
@InpsydeNiklas I just downgraded to 1.7.1 and it still occurs for my refunds. 
This is with live mode, I haven't tried with sandbox orders. Should I? Any other suggestions to try out?

**Comment by ifnull** [comment]
@InpsydeNiklas We are experiencing this issue now as well. We are on 1.7.0 and have not attempted to update. This seems like a change with the Paypal service itself.
