### ISSUE TITLE
Checkout error when PayPal onboarding is in progressive state

### ISSUE THREAD

**Issue by chickenn00dle** [woocommerce/woocommerce-paypal-payments#65]
When onboarding is in the progressive state (only email and merchant ID present), checkout results in the following error:

```
Error processing checkout. Please try again.
```

Here is a screencast of this happening in the progressive state: https://d.pr/i/3QfxQi

And of checkout working as expected when onboarding is complete (with the same PP sandbox account(s)): https://d.pr/i/ZTsUzI

Steps to reproduce:

1. Connect via the onboarding connect button
2. Optional: If connection was successful, remove API Client ID and Secret Keys then save settings
3. Attempt to checkout an item using PayPal and see the above error

**Comment by InpsydeNiklas** [comment]
Following version 1.7.0, the plugin prevents progressive onboarding states by requiring all API credential fields to be filled before saving. If the credentials are incorrect, the gateway can still be enabled but no PayPal smart buttons will render.
