### ISSUE TITLE
[HELP WANTED] Use vault from wc-ajax=ppc-create-order endpoint

### ISSUE THREAD

**Issue by RodrigoTomeES** [woocommerce/woocommerce-paypal-payments#653]
### Describe the Bug

Hi,

We are trying to use the Vault functionality through "wc-ajax=ppc-create-order" endpoint (we are using a headless approach). We are sending this data to the endpoint:

```js
{
  nonce: 'xxxx',     
  payer: {
    email_address: 'xxxx@personal.example.com',
    name: {
      surname: 'Doe',
      given_name: 'John',
    },
    address: {
      country_code: 'ES',
      address_line_1: 'Direccion 1',
      address_line_2: 'linea 2',
      admin_area_1: 'xx',
      admin_area_2: 'xxxx',
      postal_code: '30001',
    },
    phone: {
      phone_type: 'HOME',
      phone_number: {
        national_number: '941505050',
      },
    },
  },
  bn_code: 'Woo_PPCP',
  context: 'checkout',
  order_id: '0',
  payment_method: 'ppcp-gateway',
  funding_source: 'paypal',
  form: 'billing_first_name=&billing_last_name=&billing_company=&billing_country=ES&billing_address_1=&billing_address_2=&billing_postcode=&billing_city=&billing_state=C&billing_phone=&billing_email=&billing_agente_navegador=Mozilla%2F5.0%20(X11%3B%20Linux%20x86_64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F97.0.4692.71%20Safari%2F537.36&billing_idioma_navegador=es-ES&billing_altura_pantalla=1080&billing_anchura_pantalla=1920&billing_profundidad_color=24&billing_diferencia_horaria=-120&shipping_first_name=&shipping_last_name=&shipping_company=&shipping_country=ES&shipping_address_1=&shipping_address_2=&shipping_postcode=&shipping_city=&shipping_state=C&order_comments=&shipping_method%5B0%5D=flat_rate%3A1&shipping_method%5B2022_06_20_every_4th_week_0%5D=flat_rate%3A1&payment_method=ppcp-gateway&woocommerce-process-checkout-nonce=xxxxx&_wp_http_referer=%2F%3Fwc-ajax%3Dupdate_order_review&ppcp-funding-source=paypal',
  createaccount: false,
}
```

The payment is process correctly but without Vault feature.

### Environment

 - WordPress Version: 5.8.3 
 - WooCommerce Version: 6.5.1
 - Plugin Version: 1.8.0

Thanks!

**Comment by AlexP11223** [comment]
What do you mean by "headless"? If you need to interact with the plugin programmatically, it probably would be easier to do it directly via the service container [like in the description here](https://github.com/woocommerce/woocommerce-paypal-payments/pull/203#issue-953109067).

What do you need to do with vaulting?
Vaulting of the payment methods is usually done on the PayPal side without sending any data to the merchant server. I think we do not control it for PayPal buttons. For cards we only pass [vault parameter in JS](https://github.com/woocommerce/woocommerce-paypal-payments/blob/d4c7dc6b6ba6ae33741c9bdb9e2682352958fea1/modules/ppcp-button/resources/js/modules/Renderer/CreditCardRenderer.js#L198-L200). The only exception is vaulting for free trial subscriptions, which we initiate ourselves and redirect to the sign in/confirmation page. https://github.com/woocommerce/woocommerce-paypal-payments/blob/d4c7dc6b6ba6ae33741c9bdb9e2682352958fea1/modules/ppcp-api-client/src/Endpoint/PaymentTokenEndpoint.php#L211-L222

**Comment by RodrigoTomeES** [comment]
Hi,

We contact with PayPal and the data-client-token was missing in the PayPal script import

**Comment by RodrigoTomeES** [comment]
@AlexP11223  We are connecting to the plugin endpoint from the front with Next
