### ISSUE TITLE
PayPal Button is not loading for WooCommerce Subscriptions when amount is 0 (zero) or free trial (708)

### ISSUE THREAD

**Issue by tomrobak** [woocommerce/woocommerce-paypal-payments#659]
### Describe the Bug

Using WooCommerce PayPal Payments 1.8.0 - PayPal button not appearing in checkout when trying to purchase WooCommerce Subscription (free_trial) where amount is 0 (zero).

### To Reproduce

Screen recording showing all steps and paypal button trying to load infinitely [https://d.pr/v/j4rVST](https://d.pr/v/j4rVST)

### Screenshots

![Screenshot 2022-05-28 at 13 43 47](https://user-images.githubusercontent.com/48855143/170824396-cf75c102-e0f5-4f68-bdc0-3e0e05cac913.jpg)

### Expected Behavior

Working button for subscription with free trial / first payment 0

### Actual Behavior

PayPal button not loading - spinning arrows

### Environment

 - WordPress Version 6.0
 - WooCommerce Version 6.5.1
 - Plugin Version 1.8.0
 - Browser Chrome, Safari, Firefox (latest versions) 
 - Other plugins installed: WooCommerce Subscriptions 4.3.0, WooCommerce Memberships 1.23.0, WooCommerce Stripe Gateway 6.4.0, WooCommerce Order Status Control 1.14.0

**Comment by InpsydeNiklas** [comment]
One potential workaround for this issue would be enabling the [PayPal Card Processing](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing-acdc). If you are operating from a region that does not support this feature, the workaround could be applied by enabling PayPal Card Processing while a sandbox account is connected.
The behavior is under investigation though and when there's a proposed fix, it will be linked to this issue.

**Comment by tomrobak** [comment]
> One potential workaround for this issue would be enabling the [PayPal Card Processing](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing-acdc). If you are operating from a region that does not support this feature, the workaround could be applied by enabling PayPal Card Processing while a sandbox account is connected. The behavior is under investigation though and when there's a proposed fix, it will be linked to this issue.

Enabling PayPal Card Processing didn't change behaviour.

**Comment by InpsydeNiklas** [comment]
Can you please give it a try with [this version](https://drive.google.com/uc?export=download&id=1JpdzGvGq8R8vFzzCL8kAm_b4osshel3C)? If any issues persist, please open [a support ticket from here](https://paypal.inpsyde.com/docs/request-support/).
A PR with the proposed fix is linked in #661, so I will close this one.
Thanks!
