### ISSUE TITLE
best hooks to customize and support other currencies. 

### ISSUE THREAD

**Issue by ignitebhdeveloper** [woocommerce/woocommerce-paypal-payments#660]
Dear Team,

Apologies if this is not the right platform to ask this. but, if you could nudge me in the right direction to achieve the mentioned below.
So, on our e-commerce website, we're using a multi-currency (aelia.co) plugin that allows us to give users the flexibility to see the prices in their desired currency. is there any way we can programmatically convert the prices to USD or other PayPal-supported currencies if the user clicks on the place order button? 

Thanks!

**Comment by InpsydeNiklas** [comment]
Hi @ignitebhdeveloper, The integration does not provide any hooks to modify the currency but I'm not sure I understand what exactly you're looking for. Can you provide a specific example? 
Is your store using a currency that's not supported by PayPal but you want to display the buttons regardless and automatically convert the Checkout to a supported currency?
I don't think there's any way to achieve this.
Which currency is used for the checkout would be up to the multi-currency plugin to decide and PayPal should generally be disabled for unsupported currencies.

**Comment by InpsydeNiklas** [comment]
Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if any questions remain. Thanks!
