### ISSUE TITLE
Could not process order. Could not retrieve order.

### ISSUE THREAD

**Issue by MarshallGostoso** [woocommerce/woocommerce-paypal-payments#666]
### Describe the Bug

Hello everybody. First I'm sorry for the bad English, I'm using a translator.
When trying to make a purchase as a GUEST previously, the error returned: "No PayPal order found in the current WooCommerce session"
After this new update to version 1.8.1, it returned the following error: Could not process order. Could not retrieve order.
I emphasize here that if the customer uses the paypal buttons available on the product page and in the cart, he can pay normally.

### To Reproduce

1. Go to shop page as guest
2. Click on any product
3. Pay with paypal

### Screenshots

![image](https://user-images.githubusercontent.com/94805837/171321530-445cf0fe-108f-400d-998b-8bfd17a1976b.png)

![image](https://user-images.githubusercontent.com/94805837/171321566-1f232b84-41aa-4e37-97cd-c70d11b4f901.png)

### Expected Behavior

Customer must be able to make their purchase via paypal as a guest.

### Actual Behavior

Customer is unable to pay by paypal.

### Environment

 - WordPress Version : 6.0 
 - WooCommerce Version 6.5.1
 - Plugin Version 1.8.1
 - Browser any

**Comment by InpsydeNiklas** [comment]
Can you please give it a try with the [1.8.2-test1](https://github.com/woocommerce/woocommerce-paypal-payments/releases) version? 
If the problem persists for you, I suggest reaching out to the support [from here](https://paypal.inpsyde.com/docs/request-support/).
Please include a link to this issue then.
Thanks!

**Comment by tdw02d** [comment]
Did the 1.8.2-test1 version work? I am having the same issues.

**Comment by Hube2** [comment]
I am having the same issue, but this is old. The site with the issue I'm having is running version 1.9.0 of this plugin. Is the test to correct this issue included in 1.9.0? If not can I safely downgrade to 1.8.2-test1 to see what happens?

**Comment by garzettone** [comment]
I have the same error "Could not retrieve order" with Woocommerce 6.7.0 and WooCommerce PayPal Payments 1.9.1.
I can't go online with a new website for this error.

**Comment by lucapardo** [comment]
i have the same issues with higher versions : paypal payments 1.9.2 and woocommerce 6.8.0
is there any solution to the problem ?

**Comment by drewskix86** [comment]
Same issue since updating to WC 6.8.0

**Comment by InpsydeNiklas** [comment]
Please contact the support [from here](https://paypal.inpsyde.com/docs/request-support/) if you need assistance.
Thanks!
