### ISSUE TITLE
Webhook status page is crashing

### ISSUE THREAD

**Issue by millerf** [woocommerce/woocommerce-paypal-payments#679]
Seeing

```
Fatal error: Uncaught Error: Class 'WooCommerce\PayPalCommerce\Webhooks\Status\Assets\WebhooksStatusPageAssets'  not found in [...]
```
When accessing the Webhook status page (`/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-webhooks-status-page`).

It is happening with version `1.8.1` on WPCOM.

**Comment by InpsydeNiklas** [comment]
Not aware of any other reports and I'm not sure there is a wpcom test env but we'll have a look.
Does this error persist in the minimum configuration with only WooCommerce and PayPal Payments?

**Comment by eoigal** [comment]
This is resolved. There were some files missing from the plugin on WPCOM which caused this error. I suspect they were removed by mistake trying to resolve lint errors.
