### ISSUE TITLE
Critical Error 500 once click on "Customer payment page" link from an order

### ISSUE THREAD

**Issue by kxeilakos** [woocommerce/woocommerce-paypal-payments#700]
### Describe the Bug

The payment link e.g. https://mydomaincom/checkout-2/order-pay/6028/?pay_for_order=true&key=wc_order_123456xxxxxx
responds 500 once I activate the WC Paypal Payment plugin!
### To Reproduce

This error can be either reproduced from customer's side or from admin's side.
1) Customer:
The customer has made an order and has created an account and then logs into the dashboard to Pay for the order from there
![image](https://user-images.githubusercontent.com/35487400/175666449-f682e68e-51d7-47aa-8ff5-bf367d575553.png)

Once the "Pay" button is clicked the server responds with 500
![image](https://user-images.githubusercontent.com/35487400/175666517-16b0426b-2a46-4147-b74a-a2e1c6d59c02.png)

2)Admin:
Log into WP backend, navigate to WC > orders and click on the "Customer payment page"
![image](https://user-images.githubusercontent.com/35487400/175666720-8a302430-b559-4208-9511-4bb7fe0baf73.png)

3) Send Invoice email to the client. The Pay link is there
![image](https://user-images.githubusercontent.com/35487400/175666836-0cf49bcd-f7d3-4286-9664-6e39d0380d30.png)

But the same issue comes up.

Any ideas? It is very important to debug here.

### Expected Behavior

Once I de-activate the plugin 
![image](https://user-images.githubusercontent.com/35487400/175667226-bd548207-89a3-4d87-99a2-99b9d122a0bb.png)

the Checkout page loads as expected displaying the rest of the payment methods  >>
![image](https://user-images.githubusercontent.com/35487400/175667367-0c1cdd17-ab52-48db-9fc9-922640a73854.png)

The same should happen once the Plugin is activated

### Actual Behavior

But once the plugin is activated, it responds with 500
### Environment

 - WordPress Version: 6.0
 - WooCommerce Version:6.6.1
 - Plugin Version: 1.8.1
 - Browser [e.g. Chrome, Safari] and Version: Chrome latest
 - Any other plugins installed
My basic plugin here is: Car Rental Booking System for WordPress  from Quantical Labs
https://codecanyon.net/item/car-rental-booking-system-for-wordpress/21663173?irgwc=1&clickid=xn43HrVD9xyOTEOwUx0Mo3EHUkDzcYUilxzASg0&iradid=275988&irpid=296919&iradtype=ONLINE_TRACKING_LINK&irmptype=mediapartner&mp_value1=&utm_campaign=af_impact_radius_296919&utm_medium=affiliate&utm_source=impact_radius 
I am also using WPML to translate the site.

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @kxeilakos,

There have been similar reports about conflicting behavior with other plugins from Quantical Labs. 
The latest pre-release version should prevent this error from happening: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/1.9.0-test6
Could you please give it a try and let us know if this resolves the error for you as well? Thanks!

**Comment by kxeilakos** [comment]
Hi @InpsydeNiklas 
Thank you for your response.
Unfortunately, the issue persists even with the 1.9.0 version. :( 
I had more problems in the past, like the issue with the guest users who could not complete orders unless they logged in.

**Comment by InpsydeNiklas** [comment]
There have been some issues on the "Pay for order" page in the past, like the payment not completing for guest users but these have mostly been addressed.
We can't reproduce the reported error though, so could you please perform a [conflict test](https://woocommerce.com/document/how-to-test-for-conflicts/) to isolate which other plugin is causing this conflict? Given the history, the Car Rental Booking would be the primary suspect.

To look into this issue deeper with you please reach out to the plugin support from here: https://paypal.inpsyde.com/docs/request-support/
And please include a link to this issue.
Thanks!
