### ISSUE TITLE
extra options provided by "WooCommerce Extra Product Options " not provided in the PayPal receipt (881)

### ISSUE THREAD

**Issue by Bebuk85** [woocommerce/woocommerce-paypal-payments#732]
Hi, Your new plugin doesn't show the extra options provided by "WooCommerce Extra Product Options" in the PayPal receipt as WooCommerce PayPal Checkout Gateway used to do it.

Now your plugin only shows the name of the product and that's all

I'll show you 2019 vs 2022 receipts

**2022**
![after](https://user-images.githubusercontent.com/72046610/179325796-42986342-d400-40e6-9607-deee06a2e6c0.png)

**2019**
![before](https://user-images.githubusercontent.com/72046610/179325798-d0aab84b-5d6b-414d-b68e-5b2dc7db7b91.png)
![before1](https://user-images.githubusercontent.com/72046610/179325799-7345a291-b2d2-48ce-92a8-e86dfb806157.png)
.

**Comment by Dinamiko** [comment]
Closing as #1601 adds a filter that can be used to customize the name of the item on PayPal.
