### ISSUE TITLE
Does not support WooCommerce Subscriptions that start with a free trial period (710)

### ISSUE THREAD

**Issue by binaryduke** [woocommerce/woocommerce-paypal-payments#745]
When trying to complete checkout for a subscription product that starts with a free trial:

- the user receives an error message stating: "Something went wrong. Please try again or choose another payment source."

- logs show:
2022-07-24T16:33:54+00:00 ERROR Failed to start PayPal vaulting: [FORBIDDEN] No permission for the requested operation https://developer.paypal.com/docs/api/vault/v2/#error-UNKNOWN_BUSINESS_ERROR
2022-07-24T16:33:59+00:00 DEBUG POST https://api.paypal.com/v2/vault/payment-tokens
Request Body: {"customer_id":"WC-a8dd17f37dd26","source":{"paypal":{"usage_type":"MERCHANT"}},"application_context":{"return_url":"https:\/\/www.emojitrading.com\/checkout\/","cancel_url":"https:\/\/www.emojitrading.com\/checkout\/?ppcp_vault=cancel"}}
Response Debug ID: 27a59c7550047
Response: Array
(
    [code] => 403
    [message] => Forbidden
)

Response Body: {"name":"FORBIDDEN","message":"No permission for the requested operation","debug_id":"27a59c7550047","details":[{"issue":"UNKNOWN_BUSINESS_ERROR","description":"There was an issue while processing your request."}],"links":[{"href":"https://developer.paypal.com/docs/api/vault/v2/#error-UNKNOWN_BUSINESS_ERROR","rel":"information_link","method":"GET"}]}

2022-07-24T16:33:59+00:00 ERROR Failed to start PayPal vaulting: [FORBIDDEN] No permission for the requested operation https://developer.paypal.com/docs/api/vault/v2/#error-UNKNOWN_BUSINESS_ERROR
2022-07-24T16:45:12+00:00 DEBUG POST https://api.paypal.com/v1/identity/generate-token
Request Body: {"customer_id":"WC-a8dd17f37dd26"}
Response Debug ID: f8762215d661
Response: Array
(
    [code] => 200
    [message] => OK
)

No problems whatsoever with subscription products that don't have a free trial.

**Comment by InpsydeNiklas** [comment]
Hi @binaryduke! The support for free trial subscriptions is still in development: https://woocommerce.com/document/woocommerce-paypal-payments/#free-trials
It was meant to be released to everyone already, but for the time being, it can only be used in Sandbox mode and may not yet work for live payments. We hope this changes soon!

**Comment by binaryduke** [comment]
So Paypal/Subscriptions with free trials is effectively unusable.

**Comment by InpsydeNiklas** [comment]
The integration can be used with free-trial subscriptions, but Reference Transactions must be enabled for the merchant account to save the PayPal account in the Vault without a payment: https://woocommerce.com/document/woocommerce-paypal-payments/#free-trials
Without Reference Transactions, saving a payment method (PayPal account) is only possible with an actual transaction, e.g. by including a sign-up fee.
