### ISSUE TITLE
When checking out I'm getting an error 'Someting went wrong please choose a different payment method'

### ISSUE THREAD

**Issue by dekock** [woocommerce/woocommerce-paypal-payments#747]
The website is using Woocomerce, Event Ticket Plugin and Discounts plugin. 
When adding an event to the cart I click on checkout. 
On the checkout page, I complete billing details and I click on the pay in 4 for example. 
I can see the PayPal window open then it closed and scrolls to the top showing me the error. 

I tries this again and clicked on the PayPal button only and a similar thing happened. 

I tried this with the latest test pre-release version. 

TAMOUNT_MISMATCH Should equal item_total + tax_total + shipping + handling + insurance - shipping_discount - discount.eh version before I got an error 'AMOUNT_MISMATCH Should equal item_total + tax_total + shipping + handling + insurance - shipping_discount - discount.'

**Comment by InpsydeNiklas** [comment]
Can you please give it a try with the latest version, 1.9.1 or the [most recent pre-release from here](https://github.com/woocommerce/woocommerce-paypal-payments/releases)?
If the problem persists for you, please get in touch with the support from here and include a link to this issue: https://paypal.inpsyde.com/docs/request-support/
Thanks!

**Comment by InpsydeNiklas** [comment]
Please refer to the support from the link above if any issues persist with the latest version.
Thanks!
