### ISSUE TITLE
"Pay with a Card" option always availabe on PayPal landing page (846)

### ISSUE THREAD

**Issue by user-1138** [woocommerce/woocommerce-paypal-payments#748]
### Describe the Bug

The PayPal landing page (pop-up) always presents the "Pay with a Card" button/option - even with settings one might expect would prevent any kind of Credit Card payment option being shown (besides customers choosing a saved Credit Card instead of their PayPal balance, once logged in to their PayPal account).

This allows a customer to proceed with Credit Card payment as a guest through PayPal, when a store may be using another Credit Card payment processor/plugin. Such an alternative/duplicate channel for Card payments may not be desirable for some stores.

### To Reproduce

1. Add products to cart.
2. Go to checkout and enter details.
3. Select PayPal payment option and click on the primary PayPal payment button.
4. The PayPal landing page (pop-up) always presents the "Pay with a Card" button/option

**Settings I expected would remove the "Pay with a Card" option:**
_WP Dashboard > WooCommerce > Settings > Payments > PayPal Checkout >_ 
_Landing Page:_ Login (PayPal account login)
_Hide Funding Source(s):_ Credit or debit cards

_WP Dashboard > WooCommerce > Settings > Payments > PayPal Card Processing >_ 
_Vaulting:_ Not Ticked
_Onboarding:_ Not completed, quote: "_Credit Card processing for your account has not yet been activated by PayPal. If your account is new, this can take some days. Otherwise, please get in contact with PayPal._"

### Expected Behavior

In short, there should be a way to limit this plugin to PayPal (account) payments only (i.e. no Card payment options, including the "Pay with a Card" option). E.g. like how the plugins own Pay in 4 landing page, and eBay's PayPal landing pages are presented, with only Login or Signup options.

![Pay-in-4-Popup-WooCommerce](https://user-images.githubusercontent.com/21233532/180980853-281a0ea4-da95-4d28-9aa7-335950c88f05.png)

![PayPal-Popup-eBay](https://user-images.githubusercontent.com/21233532/180980906-4ed03f45-ddfa-4159-b3c7-3c979199c1bf.png)

### Actual Behavior

Irrespective of the plugins settings, the "Pay with a Card" option is always displayed on the PayPal landing page.

![PayPal-Popup-WooCommerce](https://user-images.githubusercontent.com/21233532/180980996-128e8702-7df4-4242-a99c-64eefc96ff87.png)

### Environment

 - WordPress Version 6.0.1
 - WooCommerce Version 6.7.0
 - WooCommerce PayPal Payments Version 1.9.1
 - Firefox 91.11.0esr (64-bit)
 - WooCommerce Stripe Gateway Version 6.4.3

**Comment by InpsydeNiklas** [comment]
This depends on your PayPal account configuration.
If you want to entirely disable guest checkouts via PayPal, the configuration in your PayPal account under [Website payment preferences](https://www.paypal.com/businessmanage/preferences/website) must be updated as seen here:
![image](https://user-images.githubusercontent.com/70433191/209993526-9ff74a33-befa-43c2-8719-f8f908967508.png)

**Comment by user-1138** [comment]
Thanks @InpsydeNiklas - works a treat!

FYI for others. The full steps to finding this setting in PayPal is:

1. Log in to PayPal, hover over your Profile Name (top right), click on "Account Settings"
2. Then in the left navigation pane, under the "SOLUTIONS & SERVICES" section, click on "Website payments"
3. Click "Update" on the "Website preferences" section, and set "PayPal account optional" to "Off" (as depicted above)

For those with Dev/Staging sites, don't forget you'll need to update this setting under your separate PayPal Sandbox - Merchant account.
