### ISSUE TITLE
[1.9.1] PayPal scripts loading on on pages without active smart buttons or Pay Later messaging (819)

### ISSUE THREAD

**Issue by InpsydeNiklas** [woocommerce/woocommerce-paypal-payments#750]
### Describe the Bug

With version 1.9.1, PayPal scripts are loaded on all pages even if all smart buttons and Pay Later messaging are disabled.

### To Reproduce

1. install version 1.9.1
2. open browser network activity
3. load any page without an active PayPal button or Pay Later messaging
4. observe PayPal scripts loading anyway

### Expected Behavior

The PayPal scripts only load when smart buttons or the Pay Later messaging are enabled on a page.

### Actual Behavior

The PayPal scripts load when smart buttons or the Pay Later messaging are not enabled on a page.

### Environment

 - WordPress Version 6.0.1
 - WooCommerce Version 67.0
 - Plugin Version 1.9.1

### Possible cause

Behavior introduced with this commit: Fix messaging display when the buttons are disabled #692 

### Potential workaround
Downgrade to a previous version like 1.9.0 or 1.8.1 (available in [the Releases section](https://github.com/woocommerce/woocommerce-paypal-payments/releases)) or try it with [this package](https://drive.google.com/uc?export=download&id=1TP2LWrlJT2jZvPW7FH0ASrbpPHUdsTdg) which rolls back #692.

**Comment by snandos** [comment]
We have this or a similar issue with the order received page with version 1.9.2!
PayPal scripts and tracking is loaded and fired even if the order has been payed with BACS.
This is not by design or is it?

**Comment by InpsydeNiklas** [comment]
@snandos The `Order received` page is part of the [Checkout endpoints](https://woocommerce.com/document/woocommerce-endpoints-2-1/#section-1). Right now, all Checkout endpoints will load the scripts when any PayPal gateway is enabled on the Checkout page. So the behavior is expected.
The scripts from the Checkout gateway are probably not needed on the `/checkout/order-received/` endpoint, so we'll look into whether or not an exemption for this specific endpoint would be viable.
