### ISSUE TITLE
NEW: DSGVO GDPR External connection problem

### ISSUE THREAD

**Issue by BigBenSolutions** [woocommerce/woocommerce-paypal-payments#758]
Hi,

the Plugin do external connections to, thats in GDPR not allowed:
- https://www.paypal.com/sdk/js?client-id=...
- https://www.paypal.com/tagmanager/pptm.js
- https://t.paypal.com/ts/
- https://www.paypal.com/xoplatform/logger/api/logger
- https://www.paypal.com/credit-presentment/log

how can i deactive these connections?

**Comment by InpsydeNiklas** [comment]
Hi @BigBenSolutions, This only affects version 1.9.1 and was resolved in #750 for the next update which is scheduled for this week. The linked issue includes a workaround package with a temporary fix.

**Comment by thealkly** [comment]
Hi, somehow it seems that the external connections are still apperaring with the current plugin version even on pages witouth any paypal button. 
Is there some other way to fix this GDPR complient?  
Thanks!!
