### ISSUE TITLE
V 1.9.2 - Sticky checkout (869)

### ISSUE THREAD

**Issue by Bebuk85** [woocommerce/woocommerce-paypal-payments#781]
**Hello, the new update has a bug when you click on the yellow PayPal button without filling in any fields, it becomes a bit sticky, you can't go up or down.**

https://user-images.githubusercontent.com/72046610/183769950-d5cb170e-acab-43ac-8210-4daf9550546d.mp4

**Comment by InpsydeNiklas** [comment]
The scrolling animation was queued for every error message. So the more fields failed the validation, the more scroll actions were queued up and prevented the user from scrolling down. This will be resolved in the next update. Thanks for bringing it up!
