### ISSUE TITLE
Plugin settings not saved on version 1.9.2 (882)

### ISSUE THREAD

**Issue by dabesa** [woocommerce/woocommerce-paypal-payments#809]
### Describe the Bug

When I change the plugin settings and save the page, the new settings are not displayed in the plugin page - even if they are applied.

### To Reproduce

Check this:
https://www.loom.com/share/13d03c57895a4c0fb392d7a77726319f

Niklas told me that it was an old incompatibility with the plugin Checkout Fields Editor, but the bug it's still happening in 1.9.2 so I filed this report.

**Comment by vittoriofattore** [comment]
I have the same issue with the 1.9.3. version. Did you manage to fix it?

**Comment by dabesa** [comment]
@vittoriofattore No, I open this bug to have the attention of the developers.

**Comment by InpsydeNiklas** [comment]
The compatibility issue with the `Checkout Fields Editor` plugin hasn't been addressed yet (in 1.9.3). I think it would need to be addressed in the other plugin but haven't yet received developer feedback, so I can't say for sure.
But I hope to get someone to look into it soon and if possible, resolve it for the next update in late September.
Until then, the best bet would be to reach out to the other plugin support, as they should be able to provide a solution, at least if I am not mistaken in my assumption.

**Comment by dabesa** [comment]
@InpsydeNiklas @vittoriofattore and all, here is the answer from the Checkout Field Editor support:

> Please note that this is a known issue. The issue can be fixed by adding a few changes to our plugin file. As a temporary fix, you can install the fixed plugin file attached along with this update. We will be including this fix in the upcoming version of our plugin.
>  
> The below code is added in ‘woo-checkout-field-editor-pro → public → class-thwcfd-public-checkout.php’(line 565, function → ‘woo_form_field’) for the temporary fix.
>  
> if(!is_checkout()){
>     return $field;
> }
 
I confirm that that it works.
