### ISSUE TITLE
Display Checkout Field Validation Message for other type of errors too (not only required fields) (947)

### ISSUE THREAD

**Issue by dademaru** [woocommerce/woocommerce-paypal-payments#813]
### Describe the Bug

Thanks for the improvements to **Checkout Field Validation Message** (#740 - #513), but it still remains limited to 'required' fields notice.

**All other types of errors** (e.g. 'phone', 'post code', 'email', … validations) **aren't displayed**.

So if fields are populated but with invalid data, user will know the real errors only after proceeding with PayPal checkout, filling in PayPal credentials and clicking the pay button.

### To Reproduce

Fill in phone or post code fields with invalid data (e.g. 'test').

### Expected Behavior

WooCommerce displays fields validation message:

- _Billing Postcode / ZIP is not a valid postcode / ZIP._
- _Billing Phone is not a valid phone number._

Other custom validation error messages can be added by developers or plugins - e.g. via one of these hooks:
- 'woocommerce_process_checkout_field_*'
- 'woocommerce_checkout_process',
- 'woocommerce_after_checkout_validation'

and are correctly displayed among the other errors.

### Actual Behavior

Only required field messages are displayed.
All the other error messages are displayed only after PayPal checkout processing.

### Possible solutions

If it's not possible to output the WooCommerce error notices as it happens for all the other payment gateways, could it be possible for you to add a hook to let developers adding filters for other validations?

Thanks

**Comment by InpsydeNiklas** [comment]
Hi @dademaru, the basic validation before clicking the button, as the name suggests, only performs a basic validation task by ensuring that **required** form fields are not left empty before clicking any smart button. 
The email address field is validated to contain a valid email format, though.
But the zip code field is more complicated because every country has special requirements for the zip code format. 
This would be possible to improve further, but it's not currently on the roadmap.

In any case, improvements are coming towards the behavior when the buyer returns to the Checkout with an error message. The smart buttons should be automatically hidden at this stage since the payment was already pre-authorized. This would make it more obvious to the buyer how to complete the payment after encountering an error.

**Comment by dademaru** [comment]
@InpsydeNiklas sorry, having been somehow 'forced' to switch to _WC PayPal Payments_ from [_WC PayPal Checkout_](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout) and being used to seeing validation errors before being redirected and prompted to fill in PayPal login details and then redirected back to WC checkout, I thought it was possible and the normal way to proceed.
 
In general I think it's more proper and better in terms of user experience to be able to process the checkout only if all the fields are valid(ated), without intermediate redirects/other forms (e.g. PayPal login, payment fund/method selection) to be filled in and then being redirected again to the checkout page with errors shown. 

There may also be fields that, if properly filled in (and correctly) validated, could change the total (e.g. VAT ID with VAT exemption).
So pre-authorizing a total that might differ if the invalid field is later corrected does not seem to me to be the best solution.

If a user is unwilling/unable to provide valid information to complete an order, why does he/she have to enter PayPal information, choose what funds to use, and pre-authorize a payment that he/she will not be able to complete?

– I am not criticizing, I am just sharing my considerations, hoping you can take them into account.

**Comment by dademaru** [comment]
@InpsydeNiklas I try to demonstrate additional problems caused by this 'basic' checkout error validation.

1. If I try to click the PayPal button with invalid Post Code, Phone and Email, it only marks Phone and Email as errors but only reporting that they are required, not that they are invalid:

<img width="980" alt="Schermata 2022-09-09 alle 11 35 34" src="https://user-images.githubusercontent.com/1826139/189321767-5e0f2e60-12b5-4bee-9e97-7ea0096ca35a.png">

---

2. Fixing the email field, it reports the error only for the phone field (still not for the post code field):

<img width="978" alt="Schermata 2022-09-09 alle 11 33 56" src="https://user-images.githubusercontent.com/1826139/189322676-972d8fde-518f-4a0a-8286-6173a01ec93a.png">

---

3. Fixing the phone field as well, clicking the PayPal button redirects/open the PayPal log in page (while on the checkout page, the error notice for the phone remains displayed):

<img width="972" alt="Schermata 2022-09-09 alle 11 36 30" src="https://user-images.githubusercontent.com/1826139/189322722-8a5c4c49-5a6b-45cf-9815-4943c8743750.png">

---

4. Once redirected to checkout page it eventually displays the post code field error notice:

<img width="969" alt="Schermata 2022-09-09 alle 11 36 53" src="https://user-images.githubusercontent.com/1826139/189322815-cfd41b39-36a8-4103-8324-56a61e2046b3.png">

Please also note two UX issues: 
- now the **error notice is displayed below** the coupon notice while before it was displayed above
- the **invalid field** (post code) is **not highlighted** (red border)

---

5. Then happens the worst bug: if the user fills in other invalid data (e.g. wrong phone, email, or other custom field) it now prevents you checkout while still only showing you the post code error:

<img width="972" alt="Schermata 2022-09-09 alle 11 37 15" src="https://user-images.githubusercontent.com/1826139/189324118-4d7242f8-8afd-46bd-8420-9d86bee2ae46.png">

---

6. Even if you fix the post code field (but have other invalid fields, e.g. phone) it still displays only the previous error notice (post code):

<img width="971" alt="Schermata 2022-09-09 alle 11 37 51" src="https://user-images.githubusercontent.com/1826139/189324356-90c2a7af-05d6-4066-bb66-d7e154914530.png">

So the user can't easily understand which is the error to fix and can't checkout.

One of our customers received several calls from users complaining that they could not complete the order even though they had corrected the reported error but it kept reporting it.

---

### Possible solution
Instead of trying to validate each type of field through JS, clicking the PayPal button should perform the [WC()->checkout()->process_checkout()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L1135) to allow 
[WC()->checkout()->validate_checkout()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L849) & [WC()->checkout()->validate_posted_data()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L745).
Only if no error is returned then you should initialize the order with PayPal (prompt to login).

Hope this helps.
Thanks.

**Comment by InpsydeNiklas** [comment]
Thanks for the details!
The team is looking at further improving the basic validation, while other options to improve the timing of the WC validation behavior are still under investigation. For compatibility reasons, the real WC validation currently has to happen after creating the PayPal order.
Performing the WC validation on button click would lead to compatibility problems that are worse compared to what you reported.

> now the error notice is displayed below the coupon notice while before it was displayed above

The basic validation displays the errors above the coupon notice while the regular WooCommerce errors are displayed below. This should be aligned in a future update.

> the invalid field (post code) is not highlighted (red border)

We have a list of possible improvements for the whole validation flow and this will be checked as well.

I can't reproduce the behavior under 5 & 6, but there are some upcoming improvements that should make a scenario where the user is "stuck" essentially impossible.

**Comment by dademaru** [comment]
@InpsydeNiklas thanks for returning to this issue.

Concerning points 5 & 6 I only used WC, Storefront theme and your plugin so it should be easily reproducible.
Anyway (point 5), once a field validation error (not the required field error) is displayed, so for example the post code error, if other invalid data is subsequently entered in other fields, these errors are not detected and only the first error is always shown:
<img width="1083" alt="Schermata 2022-10-20 alle 15 47 03" src="https://user-images.githubusercontent.com/1826139/196967319-15e71798-bdc5-44fc-a71c-f01aa9701cfb.png">

Then (point 6), even if you fix the invalid field concerned by error message (but have other invalid fields, e.g. phone) it still displays only the previous error notice (post code):

<img width="1093" alt="Schermata 2022-10-20 alle 15 47 32" src="https://user-images.githubusercontent.com/1826139/196967249-1860246c-4ccd-493e-8438-16568e088c2a.png">

I've reproduced it with WC 7.0, Storefront 4.1.3, PayPal Payments 1.9.4 and still the same errors.

> For compatibility reasons, the real WC validation currently has to happen after creating the PayPal order.
What do you mean? 
WC PayPal Checkout plugin seems to work with WC validation before redirecting to PayPal login/process.

I look forward to the upcoming improvements. Thanks

**Comment by AlexP11223** [comment]
> clicking the PayPal button should perform the [WC()->checkout()->process_checkout()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L1135) to allow
> [WC()->checkout()->validate_checkout()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L849) & [WC()->checkout()->validate_posted_data()](https://github.com/woocommerce/woocommerce/blob/6.8.2/plugins/woocommerce/includes/class-wc-checkout.php#L745).

We were doing this before, but it was causing some issues because it supposed to be done at the end of checkout.

#942 now attempts to `validate` without `process`.

**Comment by dademaru** [comment]
@AlexP11223 thank you, I'll give it a try as soon as released.

**Comment by AlexP11223** [comment]
It probably will not be included in the next release (next week), you can try this package if you want.

[pcp-817-woocommerce-paypal-payments.zip](https://github.com/woocommerce/woocommerce-paypal-payments/files/9880267/pcp-817-woocommerce-paypal-payments.zip)

**Comment by InpsydeNiklas** [comment]
The validation behavior was improved over the course of the last few updates. Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if any validation issues persist for you with the latest update 2.0.1.
Thanks!
