### ISSUE TITLE
Plugin settings not saving on version 1.9.3.

### ISSUE THREAD

**Issue by vittoriofattore** [woocommerce/woocommerce-paypal-payments#814]
### Describe the Bug

When I check the "Checkout" box and click Save, it remains unchecked.

### To Reproduce

1 Check the "Checkout" box
2 Click "Save"
3 Watch the settings not refresing

### Environment

 - WordPress Version
 - WooCommerce Version 6.8.2.
 - Plugin Version 1.9.3.
 - Browser Edge
 - Any other plugins installed wprocket, cartflows, klaviyo, woocommerce stripe, woocommerce cod, woocommerce email template customizer, notifier for phone, checkout field editor, loco translate, pixel your site, imagify, elementor

**Comment by InpsydeNiklas** [comment]
Hi @vittoriofattore, this is most likely caused by the `Checkout Field Editor` plugin and the problem as reported in #809.
So I'll close this duplicate issue.
