### ISSUE TITLE
woocommerce sandbox

### ISSUE THREAD

**Issue by endfates** [woocommerce/woocommerce-paypal-payments#815]
### Describe the Bug

Setting up sandbox API/mode instead repeats creating a new PayPal account rather than retrieving preset API info from PayPal since PayPal already has all the API info ready.  Also, Trying to line up API lingo do not always match with what Woocommerce labels it vs PayPal's version so manual setup is ???

### To Reproduce

1. Go to WooCommerce -> Settings -> Payment -> Manage Paypal 
2. Click on Sandbox checkbox then click 'test payments with PayPal sandbox'
3. follow steps and you will see that it is recreating a new account as it asks you for your address, etc after logging in rather than actually connecting to PayPal to get the sandbox info.  Pretty sure that's not supposed to happen.

### Expected Behavior

NOT expecting to create a new PayPal account if it asks that much info.  

### Environment

 - WordPress Version  6.0.2
 - WooCommerce Version 6.8.2
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version  Firefox 104.0.1 and Chrome 105.0.5195.54
 - Any other plugins installed

<html><body>

Akismet Anti-Spam |   | by Automattic – 5.0
-- | -- | --
Black Studio TinyMCE Widget |   | by Black Studio – 2.7.2
Classic Editor |   | by WordPress Contributors – 1.6.2
Classic Widgets |   | by WordPress Contributors – 0.3
Contact Form 7 |   | by Takayuki Miyoshi – 5.6.3
Yoast Duplicate Post |   | by Enrico Battocchi & Team Yoast – 4.5
Jetpack |   | by Automattic – 11.2
Link Library |   | by Yannick Lefebvre – 7.3.21
QSM - Reporting & Analysis |   | by QSM Team – 1.4.6
Quiz And Survey Master |   | by ExpressTech – 8.0.3
Really Simple CAPTCHA |   | by Takayuki Miyoshi – 2.1
Sucuri Security - Auditing, Malware Scanner and Hardening |   | by Sucuri Inc. – 1.8.33
TablePress |   | by Tobias Bäthge – 1.14
Advanced Editor Tools (previously TinyMCE Advanced) |   | by Automattic – 5.6.0
Social Media and Share Icons (Ultimate Social Media) |   | by UltimatelySocial – 2.7.5
UpdraftPlus - Backup/Restore |   | by UpdraftPlus.Com, DavidAnderson – 1.22.19
WooCommerce PayPal Payments |   | by WooCommerce – 1.9.3
WooCommerce |   | by Automattic – 6.8.2
WP Mail SMTP |   | by WPForms – 3.5.2
NextGEN Gallery |   | by Imagely – 3.28

</body>
</html>[Akismet Anti-Spam](https://akismet.com/) 	  	by Automattic – 5.0
[Black Studio TinyMCE Widget](https://wordpress.org/plugins/black-studio-tinymce-widget/) 	  	by Black Studio – 2.7.2
[Classic Editor](https://wordpress.org/plugins/classic-editor/) 	  	by WordPress Contributors – 1.6.2
[Classic Widgets](https://wordpress.org/plugins/classic-widgets/) 	  	by WordPress Contributors – 0.3
[Contact Form 7](https://contactform7.com/) 	  	by Takayuki Miyoshi – 5.6.3
[Yoast Duplicate Post](https://yoast.com/wordpress/plugins/duplicate-post/) 	  	by Enrico Battocchi & Team Yoast – 4.5
[Jetpack](https://jetpack.com/) 	  	by Automattic – 11.2
[Link Library](http://wordpress.org/extend/plugins/link-library/) 	  	by Yannick Lefebvre – 7.3.21
[QSM - Reporting & Analysis](https://quizandsurveymaster.com/) 	  	by QSM Team – 1.4.6
[Quiz And Survey Master](https://expresstech.io/) 	  	by ExpressTech – 8.0.3
[Really Simple CAPTCHA](https://contactform7.com/captcha/) 	  	by Takayuki Miyoshi – 2.1
[Sucuri Security - Auditing, Malware Scanner and Hardening](https://wordpress.sucuri.net/) 	  	by Sucuri Inc. – 1.8.33
[TablePress](https://tablepress.org/) 	  	by Tobias Bäthge – 1.14
[Advanced Editor Tools (previously TinyMCE Advanced)](https://wordpress.org/plugins/tinymce-advanced/) 	  	by Automattic – 5.6.0
[Social Media and Share Icons (Ultimate Social Media)](http://ultimatelysocial.com/) 	  	by UltimatelySocial – 2.7.5
[UpdraftPlus - Backup/Restore](https://updraftplus.com/) 	  	by UpdraftPlus.Com, DavidAnderson – 1.22.19
[WooCommerce PayPal Payments](https://woocommerce.com/products/woocommerce-paypal-payments/) 	  	by [WooCommerce](https://woocommerce.com/) – 1.9.3
WooCommerce 	  	by Automattic – 6.8.2
[WP Mail SMTP](https://wpmailsmtp.com/) 	  	by WPForms – 3.5.2
[NextGEN Gallery](https://www.imagely.com/wordpress-gallery-plugin/nextgen-gallery/) 	  	by Imagely – 3.28

### Additional Details

Sometimes the webhook tests fails, other times - it works.  Seems more glitchy lately hence why I am trying to do sandbox mode.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @endfates, 
[Additional vetting by PayPal](https://woocommerce.com/document/woocommerce-paypal-payments/#sign-up-for-advanced-card-payments) is required and prompted automatically during the onboarding when connecting the account with `Advanced Card Processing` selected. 
Advanced features (PayPal Card Processing) cannot be used unless the account was enabled for it. This applies to Live **and** Sandbox accounts.

For questions regarding the setup, please contact the support as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
