### ISSUE TITLE
Anomaly with Paypal extension "Enable on checkout"

### ISSUE THREAD

**Issue by Skywaven** [woocommerce/woocommerce-paypal-payments#817]
### Describe the Bug

Impossible to activate the checkbox "Enable on checkout"
When I activate the button and I click on "Save Changes" at the bottom, the page reloads but the ckeckbox "Enable on checkout" is still deactivated.

### To Reproduce

1. Go to "Woocommerce" > Settings > Payments > All payments methods > Paypal > Paypal Checkout
2. Click on "Enable on checkout" then "Save Changes"
4. Page reloads and "Enable on checkout" is deactivated

### Screenshots

![image](https://user-images.githubusercontent.com/112756847/188266724-30f6a40e-5c20-4851-beee-077bef82cf1e.png)

### Expected Behavior

Activation of the option "Enable on checkout"

### Actual Behavior

The option is not enabled when I click on "Save Changes"

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 6.8.2
 - Any other plugins installed  Astra Pro Theme 

### Additional Details

  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Skywaven, sounds like it could be related to this compatibility issue with the `Checkout Field Editor` plugin https://github.com/woocommerce/woocommerce-paypal-payments/issues/809#issuecomment-1235081259.
If the problem persists with all plugins except for WooCommerce and PayPal Payments disabled, please reach out to the support as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
