### ISSUE TITLE
Paypal buttons on top of page

### ISSUE THREAD

**Issue by mikel27a** [woocommerce/woocommerce-paypal-payments#818]
### Describe the Bug

The buttons used to appear only before add to cart. now they show up immediately in the single product page at the top as well as the checkout. looks weird. 

### To Reproduce

1. Go to https://papacito.love/shop/apparel/papacitoloveshirt/
2. Click on add to cart and then checkout
3. Scroll down to Appears below heder and 

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @mikel27a, 
The Divi Theme Builder does not support the `woocommerce_single_product_summary hook`, which causes the buttons to render on the top of the page. I suggest asking the theme developer to add support for this (default) hook as there are currently no plans to change the default in PayPal Payments.
But to work around this site builder limitation, you can change the button position with a filter [as explained in the documentation here](https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-smart-buttons-not-loading).
For questions, please contact the support as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
