### ISSUE TITLE
Paypal 4x activated

### ISSUE THREAD

**Issue by naturomarket** [woocommerce/woocommerce-paypal-payments#820]
Hello,

I'm using the Paypal Checkout plugin which doesn't state the Paypal 4x payment. However a customer just called me to say that the paypal 4x payment is visible on my website at the stage of payment and that she tried to pay with it. It worked but she didn't received the order confirmation. I checked on my end and the paypel 4x payment is activated on my website and visible at the stage of payment eventhough I never activated this. In your plugin settings, there is nowhere I can toggle it off. Could you help me on this? I don't want to have this feature activated on my website.

Attached the settings on my woocommerce backoffice and the screenshots of the customer.

Thanks,

Maud
![WhatsApp Image 2022-09-05 at 09 53 03](https://user-images.githubusercontent.com/112859617/188413582-1fde099d-0c9f-4ab2-a5a1-5b8574672bbb.jpeg)

![WhatsApp Image 2022-09-05 at 09 56 08](https://user-images.githubusercontent.com/112859617/188413469-9c5316a4-f92f-4cd2-b891-ddd9dec8a52b.jpeg)

<img width="625" alt="Capture d’écran 2022-09-05 à 10 07 29" src="https://user-images.githubusercontent.com/112859617/188412543-39c68470-6221-4df8-8ef4-fbd16f48b016.png">
![WhatsApp Image 2022-09-05 at 09 56 08 (1)](https://user-images.githubusercontent.com/112859617/188413182-0e651fad-49c9-4526-a317-ffbd89d88198.j
![WhatsApp I
![WhatsApp Image 2022-09-05 at 09 57 20](https://user-images.githubusercontent.com/112859617/188413217-71cd9cb5-0097-471b-af2c-ec462c50ab9b.jpeg)
mage 2022-09-05 at 09 56 08](https://user-images.githubusercontent.com/112859617/188413199-a41b9ce5-e617-4bf9-99bd-bf9200566c16.jpeg)
peg)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @naturomarket, for questions, please reach out to the support as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!

The Pay Later button can be disabled via the `Hide Funding Source(s)` setting as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#disable-pay-later
