### ISSUE TITLE
Paypal payment button doesn't appear on checkout page (nor anywhere)

### ISSUE THREAD

**Issue by thibautfitoussi** [woocommerce/woocommerce-paypal-payments#822]
### Describe the Bug

=> The paypal button doesn't appear on the checkout page (PayPal Gateway Enabled, and buttons enabled on checkout)

1. Go to https://alternativemedicals.com/fr/baume-de-soin-rajeunissant-au-getto-pour-le-corps/
2. Click on 'commander'
3. Scroll down to "votre commande"
4. Paypal payment option/button doesn't appear

### Screenshots

![image](https://user-images.githubusercontent.com/17620194/188446048-3e02dd84-727c-48c7-a767-0df8e794cb38.png)

### Expected Behavior

=> I am expected to see the paypal payment option to appear on the checkout page.

### Actual Behavior

Just doesn't appear

### Environment

 - WordPress Version : 6.0.2
 - WooCommerce Version : 6.8.2
 - Plugin Version : 1.9.3
 - Browser [e.g. Chrome, Safari] and Version : chrome 105.0.5195.102
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @thibautfitoussi, this is most likely a conflict with a different plugin because we can't reproduce this.
Have you tried the recommended [troubleshooting steps](https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting) by disabling all other plugins except for WooCommerce and PayPal Payments?

**Comment by thibautfitoussi** [comment]
Hi Niklas,

Did you have a chance to look at my previous email ?

Cordialement,

Thibaut


[image: photo]
*Thibaut Fitoussi*
CEO, FST Therapeutes
0626151207 | ***@***.*** | therapeutes.com
<https://www.therapeutes.com/> | therapeutesmagazine.com
<https://streaklinks.com/BMjW0G2g4Gpo-VewNwsKiN-J/http%3A%2F%2Fwww.facebook.com%2FtherapeutesCom>
<https://streaklinks.com/BMjW0Guurj8tqu-36wi4OZkA/http%3A%2F%2Ftwitter.com%2Ftherapeutescom>
<https://streaklinks.com/BMjW0GiamtJJC63H2gjNH_3k/http%3A%2F%2Fplus.google.com%2F%2BTherapeutesCOM%2F>

ᐧ

**Comment by thibautfitoussi** [comment]
Hi Niklas,

Thank you very much for your answer.

Yes, I disabled all plugins and still the paypal button does not appear.

I am wondering if I didn't set it up correctly ?

Is there anything you could do to help me solve it ?

Thanks


Thibaut


[image: photo]
*Thibaut Fitoussi*
CEO, FST Therapeutes
0626151207 | ***@***.*** | therapeutes.com
<https://www.therapeutes.com/> | therapeutesmagazine.com
<https://streaklinks.com/BMTkaa-CwlNWylMvyAZ20ICA/http%3A%2F%2Fwww.facebook.com%2FtherapeutesCom>
<https://streaklinks.com/BMTkaa6goJvn2WgGOgUXPOy6/http%3A%2F%2Ftwitter.com%2Ftherapeutescom>
<https://streaklinks.com/BMTkaauwcC7I8Fk_BQgbypij/http%3A%2F%2Fplus.google.com%2F%2BTherapeutesCOM%2F>

ᐧ

Le mar. 6 sept. 2022 à 12:09, Niklas Gutberlet ***@***.***> a
écrit :

**Comment by femiyb** [comment]
@thibautfitoussi 
We will need to look into this issue further.
For further assistance and help setting up the PayPal Payments plugin, please [get in touch with the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
