### ISSUE TITLE
Enable Blik and Przelewy24 payments for all countries

### ISSUE THREAD

**Issue by Berciu** [woocommerce/woocommerce-paypal-payments#823]
Is it possible to enable Blik and Przelewy24 payments for all countries? People staying in a country other than Poland and having a Polish bank account do not see the Blik or Przelewy24 option

**Comment by InpsydeNiklas** [comment]
Hi @Berciu, This is currently not possible as PayPal determines the available APMs based on the buyer's geolocation. So the buyer would need a Polish IP address to be served the Blik or Przelewy24 buttons.
