### ISSUE TITLE
when click on wordpress logo near dashboard,, then auto opne paypal payment windows,,

### ISSUE THREAD

**Issue by gurvindergpk** [woocommerce/woocommerce-paypal-payments#824]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @gurvindergpk, Please reach out to the plugin support as described here if you need assistance: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
