### ISSUE TITLE
stripe express checkout shipping issue

### ISSUE THREAD

**Issue by marcoolalla** [woocommerce/woocommerce-paypal-payments#829]
### Describe the Bug

when processing a payment with the Gpay express checkout i select a delivery adress and complete the payment, from the user side there are no issues nor errors.

when opening the order received from woocommerce and from stripe i see that the delivey address is not correct and is containing the Gpay account address instead of the selected delivery address that i got when doing the payment.

### To Reproduce

add a product on the cart, use the express checkout in the cart page 

### Expected Behavior

the addess passed to stripe and to woocommerce should be the one selected by the user

### Actual Behavior

the address passed is the Gpay account address

### Environment

 - WordPress Version 6
 - WooCommerce Version 6.6.0
 - Plugin Version  6.7.0
 - Browser [e.g. Chrome, Safari] and Version mobile chrome

**Comment by InpsydeNiklas** [comment]
Hi @marcoolalla, This repo is only for issues regarding [PayPal Payments](https://docs.woocommerce.com/document/woocommerce-paypal-payments/). 
For questions or issues regarding Stripe, please reach out to the Stripe support: https://wordpress.org/support/plugin/woocommerce-gateway-stripe/#new-topic-0
Thanks!
