### ISSUE TITLE
My woocommerce store Paypal Credit card processing not active for buyers

### ISSUE THREAD

**Issue by homenids** [woocommerce/woocommerce-paypal-payments#830]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @homenids, if you have questions or need assistance with the setup, please reach out to the support as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
