### ISSUE TITLE
Having huge and urgent problem after last updates

### ISSUE THREAD

**Issue by smgm25** [woocommerce/woocommerce-paypal-payments#835]
### Describe the Bug

When someone who is registered as memeber try to purchase throug Paypal with this plugin activated website shows an error "Something went wrong. Please try again or choose another payment source."
If I deactivate this plugin, WooCommerce Stripe Plugin works well.
But I also need Paypal.

This bug happens only when some user is already subscribed

### To Reproduce

Login as user to website
Add something to cart
Go to checkout
Try to buy with Paypal or Stripe
See error "Something went wrong. Please try again or choose another payment source."

What works:
Deactivate Paypal plugin
or
Unlog user and create a new one

This bug happens only when some user is already subscribed

### Screenshots

https://i.ibb.co/ncQPsC9/Schermata-2022-09-08-alle-11-29-51.png

### Expected Behavior

Like before Subscriber user must buy and pay normal with Paypal or Stripe

### Actual Behavior

Already subscriber cannot pay if Paypal plugin is activated

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 6.8.2
 - Plugin Version 1.9.3
 - Browser [e.g. Chrome, Safari] and Version Any browser any device
 -  [WooCommerce Stripe Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) - 6.7.0
 - [WooCommerce Subscriptions](https://www.woocommerce.com/products/woocommerce-subscriptions/) - 4.5.1
 - [CartFlows Pro](https://cartflows.com/) - 1.10.2

</details>

**Comment by smgm25** [comment]
Please help

**Comment by InpsydeNiklas** [comment]
Hi @smgm25, Please reach out to the support team with a copy of your system report as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
The team will get back to you as fast as possible. Thanks!
