### ISSUE TITLE
Paypal Buttons in a place where they should not be.

### ISSUE THREAD

**Issue by ShokNored** [woocommerce/woocommerce-paypal-payments#836]
Dear Sir or Madam,
I need your help with a problem.

Today I made some changes to my store header and I noticed that in a preview window (Opera Next) in the upper left corner three Paypal buttons are displayed, which are not displayed in the normal view.

How can this be?

On my smartphone I have partly the problem that when I tap on the top left of the menu or the store name, which is then called in a new tab the Paypal payment page.

In the following two images I have uploaded the relevant states as a screenshot:
https://i.ibb.co/Xx6Cdpf/WebShop.png
https://i.ibb.co/chvTdjG/Web-Shop-in-Vorschauansicht.png

Is this a bug from you or what can cause this?

Please help me, because so I can not let my webshop go online.

With friendly

 - WordPress Version
 - 6.0.2
 - WooCommerce Version
 - 6.8.2
 - Plugin Version
 - 1.9.3
 - Browser [e.g. Chrome, Safari] and Version
 - Opera GX on Desktop and different Mobile browsers.
 - Any other plugins installed
 - BEAR – Bulk Editor and Products Manager Professional for WooCommerce
 - Contact Form 7
 - Envato Market
 - FileBird
 - Flexible Shipping
 - GDPR Cookie Compliance
 - Germanized für WooCommerce
 - Germanized für WooCommerce: One Stop Shop (Deactivated)
 - Limit Login Attempts Reloaded
 - Post Views Counter
 - Slider Revolution
 - Statify
 - Statify - Extebded Evaluation
 - TablePress
 - UpSolution Core
 - Wordfence Security
 - WP Super Cache
 - WP Telegram Widget
 - WPBakery Page Builder
 - YITH WooCommerce Gift Cards

### Additional Details

I´ve installed and activated the theme "Impreza".
It´s the premium version and from UpSolution.

**Comment by InpsydeNiklas** [comment]
This appears more like a problem with the theme than with PayPal Payments.
But the support will get back to you through the helpdesk as soon as possible.
