### ISSUE TITLE
"PayPal Payment" in dashboard not localized

### ISSUE THREAD

**Issue by stkjj** [woocommerce/woocommerce-paypal-payments#840]
/woocommerce-paypal-payments/modules/ppcp-vaulting/src/VaultingModule.php line 55 reads

`				+ array( 'ppcp-paypal-payment-tokens' => 'PayPal payments' )`

but should 

`				+ array( 'ppcp-paypal-payment-tokens' =>  __('PayPal payments', 'woocommerce-paypal-payments') )`

to be properly translateable

Alternatively: 

`				+ array( 'ppcp-paypal-payment-tokens' =>  __('PayPal Payments', 'woocommerce') )`

to rely on existing WooCommerce translation

**Comment by InpsydeNiklas** [comment]
Thanks for the feedback! This was requested in #613 but, so far, it didn't make it into an official release.
In any case, this endpoint will be replaced in favor of the default endpoint for saved payment methods in one of the next couple of updates.
