### ISSUE TITLE
Paypal button disapears at checkout level if Elementor Pro is activated

### ISSUE THREAD

**Issue by joelkerth** [woocommerce/woocommerce-paypal-payments#841]
### Describe the Bug
Paypal button disapears at checkout level if Elementor Pro is activated.. When Elementor Pro is disabled then it works fine.
I tryed many different combinations of activated/deactivated plugins and the only evidence is Elementor Pro is tampering the plugni.
Essentially, when Elementor Pro is activated, then the Paypal gateway just does not display the blue (or gold) "PayPal" button to place the order. 

![image](https://user-images.githubusercontent.com/16841890/189510986-177c6925-6d77-4fc8-a26b-cee4e54a59fd.png)

 - WordPress Version 6.0.2
 - WooCommerce Version 6.8.2 
 - Plugin Version 1.9.3
 - Browser Chrome, Mozilla (last version)

<details><summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): https://wpmagnum.com
Site address (URL): https://wpmagnum.com
WC Version: 6.8.2
REST API Version: ✔ 6.8.2
WC Blocks Version: ✔ 8.0.0
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.23
PHP Post Max Size: 5 GB
PHP Time Limit: 5000
PHP Max Input Vars: 5000
cURL Version: 7.85.0
OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 5.7.39
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient activada - puede que algunos plugins de pasarela de pago que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.8.2
WC Database Prefix: tZV_
Tamaño total de la base de datos: 974.02MB
Tamaño de los datos de la base de datos: 725.82MB
Tamaño del índice de la base de datos: 248.20MB
tZV_woocommerce_sessions: Datos: 3.99MB + Índice: 0.12MB + Motor MyISAM
tZV_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_downloadable_product_permissions: Datos: 217.56MB + Índice: 156.21MB + Motor MyISAM
tZV_woocommerce_order_items: Datos: 0.39MB + Índice: 0.23MB + Motor MyISAM
tZV_woocommerce_order_itemmeta: Datos: 4.13MB + Índice: 2.02MB + Motor MyISAM
tZV_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_actionscheduler_actions: Datos: 3.51MB + Índice: 1.24MB + Motor MyISAM
tZV_actionscheduler_claims: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_actionscheduler_groups: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
tZV_actionscheduler_logs: Datos: 2.33MB + Índice: 1.64MB + Motor MyISAM
tZV_aepc_custom_audiences: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_aepc_logs: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
tZV_affiliate_wp_affiliatemeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_affiliates: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_campaigns: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_coupons: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_creatives: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_customermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_customers: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_payouts: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_referralmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_affiliate_wp_referrals: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_rest_consumers: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_sales: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_affiliate_wp_visits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_cartflows_ca_cart_abandonment: Datos: 1.52MB + Índice: 0.06MB + Motor InnoDB
tZV_cartflows_ca_email_history: Datos: 0.23MB + Índice: 0.22MB + Motor InnoDB
tZV_cartflows_ca_email_templates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_cartflows_ca_email_templates_meta: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_cartflows_visits: Datos: 5.47MB + Índice: 3.43MB + Motor MyISAM
tZV_cartflows_visits_meta: Datos: 21.15MB + Índice: 5.26MB + Motor MyISAM
tZV_commentmeta: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
tZV_comments: Datos: 2.10MB + Índice: 0.86MB + Motor MyISAM
tZV_dgwt_wcas_index: Datos: 1.52MB + Índice: 0.05MB + Motor InnoDB
tZV_dgwt_wcas_invindex_cache: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_dgwt_wcas_invindex_doclist: Datos: 2.52MB + Índice: 3.03MB + Motor InnoDB
tZV_dgwt_wcas_invindex_info: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_dgwt_wcas_invindex_wordlist: Datos: 0.39MB + Índice: 0.19MB + Motor InnoDB
tZV_dgwt_wcas_stats: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
tZV_duplicator_pro_entities: Datos: 0.01MB + Índice: 0.00MB + Motor MyISAM
tZV_duplicator_pro_packages: Datos: 0.89MB + Índice: 0.00MB + Motor MyISAM
tZV_e_events: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_e_notes: Datos: 0.02MB + Índice: 0.17MB + Motor InnoDB
tZV_e_notes_users_relations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tZV_e_submissions: Datos: 0.02MB + Índice: 0.27MB + Motor InnoDB
tZV_e_submissions_actions_log: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
tZV_e_submissions_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_fs_activities: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_attachments: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_conversations: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_data_metrix: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_mail_boxes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_persons: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_products: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_saved_replies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_taggables: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_tag_pivot: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_tickets: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_workflows: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_fs_workflow_actions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_gf_addon_feed: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_gf_draft_submissions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_gf_entry: Datos: 0.14MB + Índice: 0.03MB + Motor InnoDB
tZV_gf_entry_meta: Datos: 0.39MB + Índice: 0.41MB + Motor InnoDB
tZV_gf_entry_notes: Datos: 0.13MB + Índice: 0.03MB + Motor InnoDB
tZV_gf_form: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_gf_form_meta: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
tZV_gf_form_revisions: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_gf_form_view: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
tZV_gf_rest_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_gla_budget_recommendations: Datos: 0.20MB + Índice: 0.11MB + Motor InnoDB
tZV_gla_merchant_issues: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_gla_shipping_rates: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_gla_shipping_times: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_itsec_bans: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_itsec_dashboard_events: Datos: 0.08MB + Índice: 0.06MB + Motor InnoDB
tZV_itsec_distributed_storage: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_itsec_fingerprints: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_itsec_geolocation_cache: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_itsec_lockouts: Datos: 1.52MB + Índice: 0.25MB + Motor InnoDB
tZV_itsec_logs: Datos: 324.69MB + Índice: 20.61MB + Motor InnoDB
tZV_itsec_mutexes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_itsec_opaque_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_itsec_temp: Datos: 1.52MB + Índice: 0.77MB + Motor InnoDB
tZV_itsec_user_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_category: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_form: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_learndash_pro_quiz_lock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_master: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_prerequisite: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_question: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_learndash_pro_quiz_statistic: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_statistic_ref: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_learndash_pro_quiz_template: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_pro_quiz_toplist: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_learndash_user_activity: Datos: 1.52MB + Índice: 1.59MB + Motor InnoDB
tZV_learndash_user_activity_meta: Datos: 1.52MB + Índice: 0.53MB + Motor InnoDB
tZV_links: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_options: Datos: 5.62MB + Índice: 0.31MB + Motor MyISAM
tZV_postmeta: Datos: 30.31MB + Índice: 12.18MB + Motor MyISAM
tZV_posts: Datos: 4.32MB + Índice: 0.94MB + Motor MyISAM
tZV_rank_math_analytics_gsc: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tZV_rank_math_analytics_inspections: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
tZV_rank_math_analytics_objects: Datos: 0.23MB + Índice: 0.08MB + Motor InnoDB
tZV_rank_math_internal_links: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
tZV_rank_math_internal_meta: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
tZV_sib_model_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_sib_model_users: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_sm_sessions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_termmeta: Datos: 0.02MB + Índice: 0.02MB + Motor MyISAM
tZV_terms: Datos: 0.03MB + Índice: 0.05MB + Motor MyISAM
tZV_term_relationships: Datos: 0.11MB + Índice: 0.20MB + Motor MyISAM
tZV_term_taxonomy: Datos: 0.03MB + Índice: 0.04MB + Motor MyISAM
tZV_tm_taskmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_tm_tasks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_usermeta: Datos: 15.22MB + Índice: 8.27MB + Motor MyISAM
tZV_users: Datos: 0.89MB + Índice: 0.99MB + Motor MyISAM
tZV_wc_admin_notes: Datos: 0.04MB + Índice: 0.00MB + Motor MyISAM
tZV_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.01MB + Motor MyISAM
tZV_wc_category_lookup: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
tZV_wc_customer_lookup: Datos: 0.50MB + Índice: 0.38MB + Motor MyISAM
tZV_wc_download_log: Datos: 28.21MB + Índice: 21.65MB + Motor MyISAM
tZV_wc_order_coupon_lookup: Datos: 0.03MB + Índice: 0.06MB + Motor MyISAM
tZV_wc_order_product_lookup: Datos: 0.66MB + Índice: 0.61MB + Motor MyISAM
tZV_wc_order_stats: Datos: 0.39MB + Índice: 0.28MB + Motor MyISAM
tZV_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wc_product_meta_lookup: Datos: 0.06MB + Índice: 0.08MB + Motor MyISAM
tZV_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wc_reserved_stock: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
tZV_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
tZV_wfblockediplog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wfblocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tZV_wfconfig: Datos: 0.47MB + Índice: 0.00MB + Motor InnoDB
tZV_wfcrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wffilechanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wffilemods: Datos: 7.52MB + Índice: 0.00MB + Motor InnoDB
tZV_wfhits: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tZV_wfhoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wfissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tZV_wfknownfilelist: Datos: 4.52MB + Índice: 0.00MB + Motor InnoDB
tZV_wflivetraffichuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wflocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wflogins: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wfnotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wfpendingissues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
tZV_wfreversecache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wfsnipcache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
tZV_wfstatus: Datos: 0.11MB + Índice: 0.03MB + Motor InnoDB
tZV_wftrafficrates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_woos_search_cache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_woos_search_trends: Datos: 0.09MB + Índice: 0.06MB + Motor InnoDB
tZV_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_wpmailsmtp_tasks_meta: Datos: 0.03MB + Índice: 0.01MB + Motor MyISAM
tZV_yith_wapo_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wapo_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_affiliates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_clicks: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_commissions: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_commission_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_payments: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_payment_commission: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcaf_payment_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
tZV_yith_wcmbs_downloads_log: Datos: 22.55MB + Índice: 0.00MB + Motor InnoDB
tZV_yoast_indexable: Datos: 1.52MB + Índice: 0.47MB + Motor InnoDB
tZV_yoast_indexable_hierarchy: Datos: 0.11MB + Índice: 0.16MB + Motor InnoDB
tZV_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
tZV_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
tZV_yoast_seo_links: Datos: 0.28MB + Índice: 0.16MB + Motor InnoDB

### Post Type Counts ###

acf_fw_form: 1
acf-field: 11
acf-field-group: 1
attachment: 1130
cartflows_flow: 8
cartflows_step: 20
custom_css: 3
elementor_library: 41
elementor_snippet: 2
itsec-dash-card: 4
itsec-dashboard: 1
jet-smart-filters: 1
nav_menu_item: 96
newsletter: 3
oembed_cache: 82
page: 31
polylang_mo: 3
post: 2
product: 971
sfwd-certificates: 1
sfwd-courses: 2
sfwd-lessons: 22
sfwd-quiz: 1
sfwd-topic: 31
sfwd-transactions: 3
shop_coupon: 11
shop_order: 6133
shop_order_refund: 40
ticket: 2
ticket_history: 3
ticket_reply: 2
ufaq: 6
wp_global_styles: 1
yith-wcmbs-plan: 4
ywcmbs-membership: 3504
ywrac_cart: 317
ywrac_email: 1
ywtm_tab: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Gravity Forms: por Gravity Forms – 2.6.6
Advanced Custom Fields PRO: por Cerebros deliciosos – 5.12.2
AffiliateWP: por AffiliateWP – 2.9.3
FiboSearch - AJAX Search for WooCommerce: por Equipo de FiboSearch – 1.19.0
Clever Addons for Elementor: por CleverSoft – 2.1.6
Clever Addons Pro for Elementor: por CleverSoft – 1.2.12
CartFlows Pro: por CartFlows Inc – 1.9.0
CartFlows: por CartFlows Inc – 1.9.0
Cloudflare: por Cloudflare
Inc. – 4.11.0

Easy Theme and Plugin Upgrades: por Chris Jean – 2.0.2
Ele Custom Skin: por Dudaster.com – 3.1.7
Elementor Pro: por Elementor.com – 3.7.5
Elementor: por Elementor.com – 3.7.4
LearnDash LMS - WooCommerce Integration: por LearnDash – 1.9.4.1
Loco Translate: por Tim Whitlock – 2.6.2
Login and Logout Redirect: por Swapnil V. Patil – 2.0.2
Login as User: por Web357 – 1.4.4
Newsletter, SMTP, Email marketing and Subscribe forms by Sendinblue: por Sendinblue – 3.1.48
Manage Notification E-mails: por Virgial Berveling – 1.8.2
Facebook for WordPress: por Facebook – 3.0.7
Really Simple SSL: por Really Simple Plugins – 5.3.4
Rank Math SEO: por Rank Math – 1.0.96
LearnDash LMS: por LearnDash – 4.2.0.1
WooCommerce Cart Abandonment Recovery: por CartFlows Inc – 1.2.19
WooCommerce Email Customizer: por cxThemes – 3.33
WooCommerce PayPal Payments: por WooCommerce – 1.9.3
WooCommerce: por Automattic – 6.8.2
Asset CleanUp Pro: Page Speed Booster: por Gabriel Livan – 1.1.7.9
Email Login: por Beau Lebens – 4.6.4
Hide Dashboard Notifications: por WPRepublic – 1.2.1
WP Mail SMTP: por WPForms – 3.5.2
WP-Optimize Premium - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.2.8

YITH WooCommerce Membership Premium: por YITH – 1.11.0
YITH WooCommerce Tab Manager Premium: por YITH – 1.2.31

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (4) ###

Asset CleanUp Pro: Plugin Filtering: por Gabriel Livan – 1.0
Endurance Page Cache: por Mike Hansen – 2.2
LearnDash LMS Multisite: por LearnDash – 1.0.0
SSO: por Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la tienda: #28 - /tienda/
Carrito: #29 - /carrito/
Finalizar compra: #16678 - /finalizar/
Mi cuenta: #31 - /mi-cuenta/
Términos y condiciones: #15 - /terminos-y-condiciones/

### Theme ###

Name: Hello Elementor
Version: 2.6.1
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: La  version 3.7.0 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-cancelled-order.php está obsoleta. La versión del núcleo es la 4.1.0
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-failed-order.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-new-order.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-completed-order.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-invoice.php
La  version 3.7.0 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-new-account.php está obsoleta. La versión del núcleo es la 6.0.0
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-note.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-on-hold-order.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-processing-order.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-refunded-order.php
La  version 3.7.0 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-reset-password.php está obsoleta. La versión del núcleo es la 4.0.0
La  version 3.5.4 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-addresses.php está obsoleta. La versión del núcleo es la 5.6.0
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-customer-details.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-downloads.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-footer.php
La  version 2.4.0 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-header.php está obsoleta. La versión del núcleo es la 4.0.0
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-details.php
/home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-items.php
La  version 3.3.0 de /home/vectorespremium/public_html/wpmagnum/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-styles.php está obsoleta. La versión del núcleo es la 4.0.0

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: AR
WooCommerce currency supported: ✔
PayPal card processing available in country: –
Pay Later messaging available in country: –
Webhook status: ✔
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page
wc-pay-subscriptions-page

Disabled Features: minified-js
settings

Daily Cron: ✔ Next scheduled: 2022-09-11 23:57:10 -03:00
Options: ✔
Notes: 93
Onboarding: completed

### Action Scheduler ###

Complete: 12.391
Oldest: 2022-08-31 21:45:59 +0000
Newest: 2022-09-11 03:10:08 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 5
Oldest: 2022-09-11 04:10:53 +0000
Newest: 2022-09-14 20:59:51 +0000

### Status report information ###

Generated at: 2022-09-11 00:23:20 -03:00
`

</details>

**Comment by lahoucine010** [comment]
upgrade the php version on cpanel

**Comment by Sirvijver** [comment]
Hello @joelkerth 

the PayPal button is replacing the WooCommerce button when the PayPal payment method is selected. It seems the Elementor plugin is blocking our ajax-script from doing this action, so this is something that needs to be adjusted on Elementor side. 

If the previous comment (upgrade the php version on cpanel) resolved the issue, we can leave it at that. If you need additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We will close this thread, since we don't provide plugin support via GitHub.

Kind regards, 
Joost

**Comment by InpsydeNiklas** [comment]
Elementor Pro does not support all default WooCommerce hooks, including the ones used by PayPal Payments. We are looking into eventually providing better compatibility, but in the meantime these filters should help resolve the behavior on the single product and Checkout pages:

```php
add_filter('woocommerce_paypal_payments_single_product_renderer_hook', function() {
    return 'woocommerce_after_add_to_cart_form';
});

add_filter('woocommerce_paypal_payments_checkout_button_renderer_hook', function() {
    return 'woocommerce_review_order_after_submit';
});
```
