### ISSUE TITLE
Handle unsupported browsers better

### ISSUE THREAD

**Issue by AlexP11223** [woocommerce/woocommerce-paypal-payments#843]
Unsupported browsers like IE11, old Safari (11), Chrome/Firefox (40-50) cause order failures because PayPal Payments would fail to replace the “Place order” button with the PayPal smart buttons.

The best thing would be if the “Place order” button from the PayPal Payments gateway behaves the same way as the PayPal Standard integration by simply forwarding the buyer to the PayPal website instead of initiating the JS checkout flow.

We still hide and exchange the button with our smart buttons. But if the button replacement fails, buyers would still be able to complete PayPal payment via this fallback behavior instead of failing the order and preventing the checkout.

Alternatively, we must find a way to hide the “Place order” button even if our JavaScript replacement fails.

**Comment by Sonhui-genekeys** [comment]
I couldn't agree more with this comment.

> The best thing would be if the “Place order” button from the PayPal Payments gateway behaves the same way as the PayPal Standard integration by simply forwarding the buyer to the PayPal website instead of initiating the JS checkout flow.
