### ISSUE TITLE
Woocomerce paypal button

### ISSUE THREAD

**Issue by miggon1** [woocommerce/woocommerce-paypal-payments#854]
hello i have been using woocommerce for paypal on my site miggon.com for more then 4 months. i have a static visitors in between 1k to 1.3k on my site. sometimes i am getting more then 5 orders and sometimes even zero for few days.. I am sure there is a bug with the plugin. please help me to solve the issue

**Comment by InpsydeNiklas** [comment]
I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) to take a deeper look into this if you are still encountering any problems. Thanks!
