### ISSUE TITLE
Unable to open, track number to paypal

### ISSUE THREAD

**Issue by chickmy** [woocommerce/woocommerce-paypal-payments#855]
Version number: 1.9.3
![image](https://user-images.githubusercontent.com/42132304/190874707-a84f9b64-34ef-4938-9aa1-252e6c4687c6.png)

**Comment by InpsydeNiklas** [comment]
Tracking will be automatically enabled for your PayPal account when you disconnect your account and then connect it again using the onboarding wizard: https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account
If you still encounter any issues with this on the latest version, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
