### ISSUE TITLE
Lots of unsuccessful orders without order confirmation.

### ISSUE THREAD

**Issue by Berciu** [woocommerce/woocommerce-paypal-payments#856]
Hello. I've been using the plugin for about 2 weeks. I have about 70-50 orders a day, of which about 15 are unsuccessful daily, such that the customer does not receive any order confirmation from the store and the funds are debited from his account and returned to 24 hours. I used a different plugin before and there were no problems. I still have to explain to my clients and tell them that the funds will return themselves within 24 hours. My clients are from Poland and most pay with BLIK or Przelewy24.

**Comment by Sirvijver** [comment]
Hello @Berciu 

Sorry that we have not responded to you earlier, but we don't use GitHub for plugin support purposes. I would have to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you raised is most likely related to and older issue that should already be resolved in the current version.
Alternative payment methods such as iDEAL are push payments, so it will debit the customer's bank account as soon as they have authorized/approved the payment.
If the merchant doesn't capture this payment, it will be refunded automatically after 3 hours. Depending on the bank, the buyer should see the refund in a few days, as SEPA transactions take a day to process.
When no order has been created in WooCommerce, then PayPal Payments will also not have captured the payment and so no funds will be added to the merchant account.
The only scenarios in which I could see this happen are either when the webhooks are not registered, or the buyer did not correctly complete the checkout process as described in this issue: https://github.com/woocommerce/woocommerce-paypal-payments/issues/513

But again: this issue should have been resolved in the previous release, so please check if you now still encounter this and open a new thread with our support team if you need additional support.

Kind regards, 
Joost
