### ISSUE TITLE
Not Adding Product Variation Costs

### ISSUE THREAD

**Issue by jabrieske** [woocommerce/woocommerce-paypal-payments#857]
### Describe the Bug

In just the past few days, I've noticed that if a custom builds a product with variations, that the extra variations costs are not added to the product if they use the PayPal button on the single product page. If they go to the cart or checkout and use PayPal, the extra cost is added. 

### To Reproduce

1. Go to https://lowboybeaters.com/product/beater-builder-flat/?start_customizing=yes
2. Add variations that will add extra cost to the product
3. Do not add to cart. Rather, click the PayPal button.
4. NOTE: I have disabled the button, but can enable it for testing. 

### Expected Behavior

The cost of the variations should be added

### Actual Behavior

The cost of the variations are not added

### Environment

`
### WordPress Environment ###

WordPress address (URL): https://lowboybeaters.com
Site address (URL): https://lowboybeaters.com
WC Version: 6.9.2
REST API Version: ✔ 6.9.2
WC Blocks Version: ✔ 8.3.2
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.30
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.1.1q-fips

SUHOSIN Installed: –
MySQL Version: 5.7.39-42-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.9.2
WC Database Prefix: rsz5t8f57r_
Total Database Size: 456.82MB
Database Data Size: 403.31MB
Database Index Size: 53.51MB
rsz5t8f57r_woocommerce_sessions: Data: 60.07MB + Index: 0.75MB + Engine MyISAM
rsz5t8f57r_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_order_items: Data: 0.91MB + Index: 0.36MB + Engine MyISAM
rsz5t8f57r_woocommerce_order_itemmeta: Data: 111.41MB + Index: 3.83MB + Engine MyISAM
rsz5t8f57r_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_payment_tokens: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
rsz5t8f57r_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_actionscheduler_actions: Data: 0.25MB + Index: 0.14MB + Engine MyISAM
rsz5t8f57r_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_actionscheduler_logs: Data: 3.45MB + Index: 2.36MB + Engine MyISAM
rsz5t8f57r_aioseo_cache: Data: 0.41MB + Index: 0.03MB + Engine InnoDB
rsz5t8f57r_aioseo_notifications: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_aioseo_posts: Data: 0.90MB + Index: 0.11MB + Engine MyISAM
rsz5t8f57r_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rsz5t8f57r_commentmeta: Data: 0.13MB + Index: 0.14MB + Engine InnoDB
rsz5t8f57r_comments: Data: 4.52MB + Index: 2.38MB + Engine InnoDB
rsz5t8f57r_css_js_manager: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_eg_grids: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_eg_item_elements: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_eg_item_skins: Data: 0.63MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_eg_navigation_skins: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_email_log: Data: 42.12MB + Index: 0.06MB + Engine MyISAM
rsz5t8f57r_et_bloom_stats: Data: 25.70MB + Index: 4.19MB + Engine MyISAM
rsz5t8f57r_fpd_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_fpd_category_products_rel: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_fpd_designs: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_fpd_products: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_fpd_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_fpd_views: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_gf_entry: Data: 0.98MB + Index: 0.10MB + Engine MyISAM
rsz5t8f57r_gf_entry_meta: Data: 3.16MB + Index: 1.91MB + Engine MyISAM
rsz5t8f57r_gf_entry_notes: Data: 0.13MB + Index: 0.04MB + Engine MyISAM
rsz5t8f57r_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_gf_form_meta: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_gf_form_revisions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_gf_form_view: Data: 0.12MB + Index: 0.06MB + Engine MyISAM
rsz5t8f57r_gf_rest_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_mailchimp_carts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
rsz5t8f57r_mailchimp_jobs: Data: 0.16MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_nf_objectmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_nf_objects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_nf_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_ninja_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_ninja_forms_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_options: Data: 14.45MB + Index: 3.27MB + Engine InnoDB
rsz5t8f57r_postmeta: Data: 39.56MB + Index: 24.06MB + Engine InnoDB
rsz5t8f57r_posts: Data: 63.52MB + Index: 1.09MB + Engine InnoDB
rsz5t8f57r_redirection_404: Data: 0.31MB + Index: 0.12MB + Engine MyISAM
rsz5t8f57r_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_redirection_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_redirection_logs: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
rsz5t8f57r_redirects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_rg_form_meta: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_rg_form_view: Data: 0.43MB + Index: 0.24MB + Engine MyISAM
rsz5t8f57r_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_rg_lead: Data: 2.50MB + Index: 0.22MB + Engine MyISAM
rsz5t8f57r_rg_lead_detail: Data: 0.77MB + Index: 0.94MB + Engine MyISAM
rsz5t8f57r_rg_lead_detail_long: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_rg_lead_meta: Data: 0.19MB + Index: 0.07MB + Engine MyISAM
rsz5t8f57r_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_sbi_feeds: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_sbi_feed_caches: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_sbi_instagram_feed_locator: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_sbi_instagram_posts: Data: 0.93MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_sbi_sources: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rsz5t8f57r_sgpb_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rsz5t8f57r_sgpb_subscription_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rsz5t8f57r_stock_log: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
rsz5t8f57r_termmeta: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
rsz5t8f57r_terms: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
rsz5t8f57r_term_relationships: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
rsz5t8f57r_term_taxonomy: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
rsz5t8f57r_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rsz5t8f57r_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_usermeta: Data: 9.52MB + Index: 4.03MB + Engine InnoDB
rsz5t8f57r_users: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
rsz5t8f57r_vxg_zendesk: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_vxg_zendesk_accounts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_vxg_zendesk_log: Data: 9.06MB + Index: 0.08MB + Engine MyISAM
rsz5t8f57r_wc_admin_notes: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_wc_admin_note_actions: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_wc_customer_lookup: Data: 0.11MB + Index: 0.10MB + Engine MyISAM
rsz5t8f57r_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_wc_order_product_lookup: Data: 0.19MB + Index: 0.17MB + Engine MyISAM
rsz5t8f57r_wc_order_stats: Data: 0.10MB + Index: 0.08MB + Engine MyISAM
rsz5t8f57r_wc_order_tax_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_wc_product_attributes_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
rsz5t8f57r_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
rsz5t8f57r_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rsz5t8f57r_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rsz5t8f57r_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rsz5t8f57r_woocommerce_square_customers: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
rsz5t8f57r_woojetpack_country_ip: Data: 2.39MB + Index: 1.44MB + Engine MyISAM
rsz5t8f57r_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rsz5t8f57r_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rsz5t8f57r_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 1992
custom_css: 2
et_pb_layout: 64
jetpack_migration: 2
nav_menu_item: 19
oembed_cache: 6
page: 41
popupbuilder: 1
post: 21
product: 79
product_variation: 456
project: 55
revision: 1467
secondline_psb_post: 1
shop_coupon: 98
shop_order: 5585
shop_order_refund: 46
tablepress_table: 1
user_request: 2
wc_product_tab: 16
wpsl_stores: 53

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

Akismet Anti-Spam: by Automattic – 5.0
All in One SEO: by All in One SEO Team – 4.2.5.1
Bloom: by Elegant Themes – 1.3.12
Envato Market: by Envato – 2.0.7
301 Redirects: by WebFactory Ltd – 2.72
Essential Grid: by ThemePunch – 3.0.16
Facebook for WooCommerce: by Facebook – 2.6.23
Fancy Product Designer: by fancyproductdesigner.com – 4.7.9
FooTable: by Brad Vincent – 0.3.1
WP Gravity Forms Zendesk: by CRM Perks. – 1.1.0
Gravity Forms: by Gravity Forms – 2.6.6
Smash Balloon Instagram Feed: by Smash Balloon – 6.0.7
Jetpack: by Automattic – 11.3.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Login Logo: by Mark Jaquith – 0.10.2
Mailchimp for WooCommerce: by Mailchimp – 2.7.5
Multistep Product Configurator for WooCommerce: by radykal.me – 1.2.5
Open Graph: by Will Norris – 1.11.0
Podcast Subscribe Buttons: by SecondLine Themes – 1.4.5
Blubrry PowerPress: by Blubrry – 9.4
Really Simple SSL: by Really Simple Plugins – 5.3.4
SendGrid: by SendGrid – 1.11.8
SiteGround Optimizer: by SiteGround – 7.2.1
TablePress: by Tobias Bäthge – 1.14
Use Any Font: by Dnesscarkey – 6.2.95
WooCommerce Availability Notifications: by ThemePlugger – 1.4.2
WooCommerce Colors: by WooThemes – 1.0.7
WooCommerce Gravity Forms Product Add-Ons: by Element Stark – 3.3.26
Booster for WooCommerce: by Pluggabl LLC – 5.6.5
WooCommerce Menu Cart: by WP Overnight – 2.12.0
WooCommerce PayPal Payments: by WooCommerce – 1.9.3
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Shipping & Tax: by WooCommerce – 1.26.3
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26 (update to version 1.8.0 is available)
WooCommerce Smart Coupons: by WooCommerce – 3.3.8 (update to version 6.1.1 is available)
WooCommerce Square: by WooCommerce – 3.2.0
Stock Manager for WooCommerce: by StoreApps – 2.8.3
WooCommerce Tab Manager: by SkyVerge – 1.14.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.41
WooCommerce: by Automattic – 6.9.2
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.7

WP Store Locator: by Tijmen Smit – 2.2.235
Zendesk Support for WordPress: by Zendesk – 1.8.4

### Inactive Plugins (21) ###

Advanced Order Export For WooCommerce: by AlgolPlus – 3.3.2
Email Log: by Sudar – 2.4.8
Find Slow Functions & Actions & Filters & Hooks: by Puvox.software – 1.41
Fusebox Player: by Fusebox – 2.9.4
Health Check & Troubleshooting: by The WordPress.org community – 1.5.0
Lightweight Social Icons: by Thomas Usborne – 1.1
Popup Builder: by Sygnoos – 4.1.13
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.5
Product Sales Report for WooCommerce: by Aspen Grove Studios – 1.5.1
Query Monitor: by John Blackbourn – 3.10.1
Redirection: by John Godley – 5.3.4
Schema - All In One Schema Rich Snippets: by Brainstorm Force – 1.6.5
Theme Check: by Theme Review Team – 20211203
WooCommerce Export Customer Email: by MH Mithu – 1.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce URL Coupons: by WooThemes / SkyVerge – 2.4.1
WordPress Database Backup: by Austin Matzko – 2.3.3
WP Crontrol: by John Blackbourn & crontributors – 1.14.0
WP Mail SMTP: by WPForms – 3.5.2
WP Maintenance Mode & Coming Soon: by Themeisle – 2.5.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Shop base: #23 - /shop/
Cart: #24 - /cart/
Checkout: #25 - /checkout/
My account: #26 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi Child Theme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.18.0
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce PayPal Payments ###

Onboarded: ✔
Shop country code: US
WooCommerce currency supported: ✔
PayPal card processing available in country: ✔
Pay Later messaging available in country: ✔
Webhook status: –
Vault enabled: ✔
Logging enabled: –
Reference Transactions: –
Used PayPal Checkout plugin: ✔
Tracking enabled: ✔

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
experimental-product-tour
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2021-10-01 06:30:00 -06:00
Options: ✔
Notes: 77
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2022-09-19 02:56:05 -0600
Newest: 2022-09-19 02:56:05 -0600

Complete: 463
Oldest: 2022-08-19 09:49:28 -0600
Newest: 2022-09-19 08:40:00 -0600

Failed: 17
Oldest: 2019-12-30 13:33:42 -0700
Newest: 2022-09-12 18:43:59 -0600

Pending: 7
Oldest: 2022-09-19 08:55:00 -0600
Newest: 2022-09-23 13:32:38 -0600

### Status report information ###

Generated at: 2022-09-19 08:40:12 -06:00
`

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
@jabrieske These don't appear to be regular product variations, but instead more like third-party "Product Add-ons".
Custom product pricing on the single product page through third-party extensions may not be supported for now.
But the amount the user is charged would still be correct in any case, regardless of what it says in the PayPal popup window. 
The correct amount would be taken from the WooCommerce order and is then patched into the PayPal order before the payment is captured.

Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this issue and more details about how these "variations" are created. Thanks!
