### ISSUE TITLE
Unable to check out with WooCommerce PayPal Payments

### ISSUE THREAD

**Issue by vtbookworm** [woocommerce/woocommerce-paypal-payments#858]
### Describe the Bug

Sometimes a user who is logged in to our website plowpartsplus.com cannot pay using PayPal or Venmo. The error message they see is "Something went wrong. Please try again or choose another payment choice." I'm not sure whether your plugin on this website is displaying that error message. It isn't always consistent, and possibly has to do with whether PayPal recognizes the user or needs the user to log in to PayPal. But that's just a guess. This is an intermittent problem, and we have applied the latest fixes.

### To Reproduce

1. Go to our staging site: https://g9f.908.myftpupload.com
2. Click on Shop
3. Click on My Account
4. Register as a new user; follow the registration procedure.
5. Go back to My Account and log in as the new user
6. Add items to the cart.
7. View the cart.
8. Click on either the PayPal or Venmo button, You should see the error message.

If you don't see the error message, but instead get to the PayPal screen, cancel and go back to the staging site. DO NOT place an order; I haven't been able to get the sandbox to work on the staging site, so you WILL BE CHARGED if you place an order.

### Expected Behavior
I expected to be taken to either the PayPal login screen, the PayPal screen where you can choose payment methods, or the Venmo screen, depending on which button was pressed to check out.

### Actual Behavior
An error message is shown: "Something went wrong. Please try again or use another payment choice."

There are no other payment choices, and trying again produces the same result.

Note that if the user is not logged in to our website, the checkout process works.

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 6.9.3
 - WooCommerce PayPal Payments 1.9.3
 - Browser Chrome or Firefox, latest versions, Chrome is 105.0.5195.127 (Official Build) (64-bit)
 - Any other plugins installed
![image](https://user-images.githubusercontent.com/11725704/191528935-b18ae8b4-c701-4930-a4e8-e512ce9d4936.png)

### Additional Details
Ticket number 545782
 
This is an intermittent problem. Occasionally, a logged-in user can check out. I've tried flushing the cache, clearing cookies, and rebooting the machine. Nothing works consistently.

With WP_DEBUG on, we see the following two problems:
![image](https://user-images.githubusercontent.com/11725704/191535137-63de1a38-001d-4b46-9f45-5c04de72bb50.png)

I don't know what's going on with the dates. I'm using a plugin, WP DEBUG LOG - config tool, to turn on WP_DEBUG and display the log.
 -->
<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
@vtbookworm If you still require assistance with this, please [get in touch with the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
