### ISSUE TITLE
Account doesn't connect, token issue

### ISSUE THREAD

**Issue by LidiaCrochetTricot** [woocommerce/woocommerce-paypal-payments#859]
### Describe the Bug

I have updated all the plugins and woocommerce and I encounter an issue with the plugin. I try to connect the account with the plugin and it's working, but 1 minute after I get a token issue in woocommerce with the plugin, and it's not working. I try to repeat the processus but I arrive at the same stage.

![1](https://user-images.githubusercontent.com/39492735/191710697-a65afb8e-cca5-456a-9e5e-b066aeef1f94.jpg)

**Comment by femiyb** [comment]
@LidiaCrochetTricot If you still require assistance with this, please [get in touch with the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
