### ISSUE TITLE
Paypal isnt letting me connect

### ISSUE THREAD

**Issue by austynbuchanan** [woocommerce/woocommerce-paypal-payments#860]
### Describe the Bug

I go to activate my paypal account. At first it let me connect my credentials, but then the small pop up window just goes white. I  tried deleting the plugin and then redownloading it. when i try to activate it then, it pops up the window with a challenge, i complete it and then it just keeps doing more challenges. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by outrank-james** [comment]
Same here on two different websites.
<img width="885" alt="Screenshot 2022-09-29 at 10 00 45 am" src="https://user-images.githubusercontent.com/47569353/192989066-ffb7240e-a0e6-41ec-8abb-d1f0663a719a.png">

**Comment by InpsydeNiklas** [comment]
If the onboarding wizard fails, for example when the connection to PayPal is blocked, the API credentials could also be connected manually: https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input
Should this problem persist for you with the latest version and/or after manual credential input, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). 
Thanks!
