### ISSUE TITLE
PHP 8.1 warning:  Constant FILTER_SANITIZE_STRING is deprecated (937)

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-paypal-payments#867]
After upgrading from php 7.3 to 8.1 I see lots of PHP Deprecated warnings like `PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-vaulting/src/CustomerApprovalListener.php on line 56` 

In fact, there is quite some usage of `FILTER_SANITIZE_STRING` in this plugin. See https://github.com/woocommerce/woocommerce-paypal-payments/search?p=1&q=FILTER_SANITIZE_STRING

During development of my child theme I follow the WordPress best practices 
```
/**
* For developers: WordPress debugging mode.
*
* Change this to true to enable the display of notices during development.
* It is strongly recommended that plugin and theme developers use WP_DEBUG
* in their development environments.
*/
define('WP_DEBUG', true);
``` 

However, now my logs are full of these Deprecated messages. Would be nice if these could be fixed in a future release.

**Comment by InpsydeNiklas** [comment]
PayPal Payments supports PHP 7.1 up to PHP 8.
PHP 8.1 is not yet officially supported, so we can't rule out eventual warnings for now.

**Comment by gerdneuman** [comment]
Ok, I did not know this. Had I known I would not have upgrade my site from php 7.3 to 8.1 (I got a warning from the WooCommerce plugin on my site, that a minimum of 7.4 would be required). I find it strange, that WooCommerce PayPal Payments supports other PHP versions than WooCommerce. Both WooCommerce and WordPress support 8.1 officially.

Also on https://wordpress.org/plugins/woocommerce-paypal-payments/ it says:
> PHP Version: 7.1 or higher

and https://woocommerce.com/document/woocommerce-paypal-payments/ also says so:
> Requirements:
>   ...
>   PHP Version 7.1 or newer

**Comment by InpsydeNiklas** [comment]
@gerdneuman The latest update 2.0 improved the compatibility with PHP 8.1. The minimum required PHP version has also been increased to 7.2 with this release. 
But please be aware that different plugins can have different requirements, and requiring a minimum of PHP 7.2 does not automatically mean that it works with the latest PHP versions.
For example, WordPress does not yet officially support PHP 8.2, and we haven't yet tested it with PayPal Payments.
By now, it has been tested on PHP 8.1 though, and we haven't found any major problems in that regard (WordPress does not yet fully support PHP 8.1 though and can still produce notices).
