### ISSUE TITLE
Provide option for Credit Card to appear above PayPal in checkout

### ISSUE THREAD

**Issue by Chaithi** [woocommerce/woocommerce-paypal-payments#87]
### Describe the bug
Since the module is not broken into two methods, the user doesn't have control over which payment method (between PayPal and Credit Card) appears first in checkout. 

### Additional details
Provide toggle in the Credit Card Processing section to allow merchant to set Credit Cards first in checkout.

**Comment by ethanclevenger91** [comment]
For some reason (likely user experience related), the plugin authors elected to toss out the default payment gateway configuration settings screens that come with a payment gateway, and instead tagged the credit card gateway within the main PayPal gateway.

If you toss out the screen check [here](https://github.com/woocommerce/woocommerce-paypal-payments/blob/1.5.1/modules/ppcp-wc-gateway/src/class-wcgatewaymodule.php#L218), the credit card payment gateway appears as expected in the list of gateways and can be re-ordered as expected, but the action button in the right-hand column goes to an unused screen.

A naive PR would do just that, but would need, at a minimum, a redirect set up from the default action URL that WooCommerce generates to the custom setting screen this plugin creates.

**Comment by ethanclevenger91** [comment]
Same details essentially rehashed [here](https://wordpress.org/support/topic/checkout-page-payment-options-order/) on the WP.org support forums.

**Comment by jorgeatorres** [comment]
Fixed in #236.
