### ISSUE TITLE
PayPal card type icône bug

### ISSUE THREAD

**Issue by ChoosenMatch** [woocommerce/woocommerce-paypal-payments#871]
### Describe the Bug

My PayPal on woocommerce is having issues because the credit card or débit card icone card types is not showing, it appears ans disappears everytime.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
If you still encounter any issues with the latest version, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
