### ISSUE TITLE
There is no title for the payment method next to the radio button 

### ISSUE THREAD

**Issue by Loreye820** [woocommerce/woocommerce-paypal-payments#872]
### To Reproduce

1. Go to plugins and activate Woocommerce Paypal Payments
2. Refresh checkout page
3. Scroll down to payment methods
4. See there is no title next to the radio button, it is blank

### Environment

 - WordPress Version 6.0.2 
 - WooCommerce Version 6.9.4
 - Plugin Version 1.9.3 WooCommerce PayPal Payments
 - Browser Chrome, Version 105.0.5195.125 (Official Build) (x86_64)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
The gateway title displays correctly for us.
If you still encounter this issue with the latest version, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
