### ISSUE TITLE
Title for Card Processing is not Adjacent to the Radio Button

### ISSUE THREAD

**Issue by dsgjohnnie** [woocommerce/woocommerce-paypal-payments#874]
### Describe the Bug

On Checkout page, the title for PayPal Card Processing is below the radio button instead of next to it, which is causing customer confusion.

### To Reproduce

1. Enable PayPal Card Processing
2. Add item to cart
3. Go to Checkout page

### Screenshots

![PayPal CC Payments 09 22 2022](https://user-images.githubusercontent.com/114694374/193133489-10d7f9e6-e50d-4e75-9480-aa9cbe6d0908.png)

### Expected Behavior

I expected the title to be adjacent to the radio button, on the right side, similar to the PayPal and Amazon Pay options in the screenshot

### Actual Behavior

Title is one line below the radio button and aligned to the left

### Environment

WordPress Version 6.0.2
WooCommerce Version 6.9.4
Plugin Version 1.9.3
Browser: Edge Version 105.0.1343.53 (64-bit)
               Chrome Version 105.0.5195.127 (64-bit)
Other Plugins Installed:
+----------------------------------------------+----------+--------+----------+
| name                                         | status   | update | version  |
+----------------------------------------------+----------+--------+----------+
| woo-order-export-lite                        | inactive | none   | 3.3.2    |
| autoptimize                                  | inactive | none   | 3.1.2    |
| back-in-stock-notifier-for-woocommerce       | active   | none   | 3.0      |
| bing-webmaster-tools                         | active   | none   | 1.0.13   |
| chargeback-for-woocommerce                   | inactive | none   | 0.1.8    |
| conversion-tracking-bing-woocommerce         | active   | none   | 1.0.7.2  |
| dark-mode-for-wp-dashboard                   | inactive | none   | 1.1.3    |
| duplicate-page                               | active   | none   | 4.4.9    |
| elementor                                    | active   | none   | 3.7.7    |
| emails-verification-for-woocommerce          | active   | none   | 2.4.3    |
| envato-market                                | active   | none   | 2.0.7    |
| head-footer-code                             | active   | none   | 1.3.0    |
| woo-quickbooks-crm-perks-pro                 | active   | none   | 1.2.3    |
| jetpack                                      | active   | none   | 11.3.2   |
| official-mailerlite-sign-up-forms            | active   | none   | 1.6.0    |
| microsoft-clarity                            | active   | none   | 0.7.5    |
| woo-product-feed-pro                         | active   | none   | 11.8.7   |
| profile-builder                              | active   | none   | 3.8.0    |
| redirection                                  | active   | none   | 5.3.4    |
| google-site-kit                              | active   | none   | 1.84.0   |
| trustpilot-reviews                           | active   | none   | 2.5.914  |
| updraftplus                                  | active   | none   | 1.22.23  |
| woocommerce                                  | active   | none   | 6.9.4    |
| woocommerce-gateway-amazon-payments-advanced | active   | none   | 2.2.4    |
| woo-cart-abandonment-recovery                | active   | none   | 1.2.19   |
| woocommerce-google-analytics-integration     | active   | none   | 1.5.14   |
| nmi-payment-woocommerce                      | active   | none   | 5.2.0    |
| woocommerce-paypal-payments                  | active   | none   | 1.9.3    |
| wc-serial-numbers                            | active   | none   | 1.2.10   |
| wc-serial-numbers-pro                        | active   | none   | 1.1.7    |
| wp-cerber                                    | active   | none   | 9.2.2    |
| wp-crontrol                                  | active   | none   | 1.14.0   |
| wp-mail-smtp-pro                             | active   | none   | 3.5.2    |
| wp-rocket                                    | active   | none   | 3.12.1.1 |
| wpscan                                       | active   | none   | 1.15.6   |
| et-core-plugin                               | active   | none   | 4.3.4    |
| wordpress-seo                                | active   | none   | 19.7.1   |
| aaa-wp-cerber                                | must-use | none   | 1.0      |
| advanced-cache.php                           | dropin   | none   |          |
+----------------------------------------------+----------+--------+----------+

### Additional Details

I have been successfully using the existing plugin for many months for PayPal transactions only, but I just enabled Card Processing as a payment method for the first time, so I don't know if this bug existed on other versions of the plugin or Woocommerce.

**Comment by InpsydeNiklas** [comment]
With this long title and the gateway icons, I'm not sure if this fits in one line. 
Beyond the length of the title, this extra break is may be caused by additional styling from the theme. 
I suggest giving it a try with the Storefront theme or any default WordPress theme to see if the behavior persists for you: https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting
If it does not, then your theme developer is usually in a better position to help out.

But if the issue persists with a default theme, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
