### ISSUE TITLE
Still see "pay in 3" button not translated in the wordpress language but uses the merchant language

### ISSUE THREAD

**Issue by badpenguin** [woocommerce/woocommerce-paypal-payments#875]
### Describe the Bug

We're based in spain but with websites in different EU languages.

The paypal "pay in 3" button always appear in spanish language instead of italians or other languages.

### Environment

 - WordPress 6.0.2
 - WooCommerce 6.9.2
 - Plugin Version 1.9.3
 - Browser: any
 - Any other plugins installed
- - WooCommerce PDF Invoices & Packing Slips 1.9.3
- - WooCommerce Stripe Gateway 6.7.0

**Comment by InpsydeNiklas** [comment]
> We're based in spain but with websites in different EU languages.

Languages provided by the website are not relevant from the plugin perspective. PayPal automatically determines the button and interface language for every individual user.
Beyond this, every supported country has a different Pay Later button: https://developer.paypal.com/docs/checkout/pay-later/es/
So this button will never be "translated". Instead, the buyer gets presented the button that is relevant for them.

For questions regarding the setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
