### ISSUE TITLE
Payment buttons not working for some customers

### ISSUE THREAD

**Issue by kllawhite** [woocommerce/woocommerce-paypal-payments#878]
### Describe the Bug

On https://backwateroutfitting.com/checkout/, for some customers, the payment buttons for Paypal, Venmo, and Pay Later are not showing up on the checkout page, and the Debit or Credit Card button is not functioning. This is a new development within the last 2 weeks +/-. Speaking with one customer, he was able to change to a newer computer and the problem went away. Another customer encountered the problem on a mobile phone. I don't know what computer systems, phone or software was used in any case.

### To Reproduce

I have not been able to reproduce the problem.

### Screenshots
![2022-09-30 17 39 28](https://user-images.githubusercontent.com/114783258/193368352-9a5ab762-2927-422c-884a-14500ef60c37.jpg)

### Expected Behavior-

These screen shots are from my desktop and iPhone. These are functioning as expected.
![image](https://user-images.githubusercontent.com/114783258/193368723-3c0c93a9-bdc7-4ffb-99f5-f02c9275f99b.png)
![2022-09-30 18 27 31](https://user-images.githubusercontent.com/114783258/193369032-17e206a6-0da0-4b7c-88bf-15e704285f61.png)

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 6.9.4
 - Plugin Version 1.9.3
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
The compatibility with older browsers like outdated (mobile) Safari versions was imporved with the latest update 1.9.4. So please update the plugin and [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if any issues persist. Thanks!
