### ISSUE TITLE
Bug Paypal sdk mobile 

### ISSUE THREAD

**Issue by alexrider123** [woocommerce/woocommerce-paypal-payments#879]
### Describe the Bug

Hello,
Whenever I activate the WooCommerce PayPal Payments plugin, my Lighthouse treemap shows that 16% of the homepage load (411KB) comes from the following:
https://www.paypal.com/sdk/js?client-id=AUslsH0Dt98Xu_BVSBJVSonhTqyeSrVMztNplHXg7C0jd79xQTz7mOaEKCgC0F5GCTtq5hw0sroPCBKo&currency=EUR&integration-date=2022-04-13&components=buttons,funding-eligibility,messages&vault=false&commit=false&intent=capture&disable-funding=card&enable-funding=venmo,paylater

This, while Paypal is shown only on my e-shop page, and not on any other page on the website. 
There is a noticeable change in the time it takes each page of the website to load - a major issue. 

### To Reproduce

1. Go to https://ateliersurcours.com

### Screenshots

![Capture](https://user-images.githubusercontent.com/23637728/193457157-2fc760b6-e69e-4dd3-81df-71119876a839.JPG)

### Expected Behavior

The homepage should not load that much data and load quicker. 

### Actual Behavior

The homepage loads a heavy Paypal SDK of about 411KB, slowing down the loading time.

### Environment

 - WordPress Version 6.0.2
 - WooCommerce Version 6.9.4
 - Plugin WooCommerce PayPal Payments Version 1.9.3
 - Browser and Version Chrome 106.0.5249.91 (Official Build)
 - Any other plugins installed: AR Model Viewer, 	
Elementor Pro, WooCommerce Payments, WP Rocket, Yoast SEO. -

**Comment by InpsydeNiklas** [comment]
> This, while Paypal is shown only on my e-shop page, and not on any other page on the website.

The [Mini Cart button](https://woocommerce.com/document/woocommerce-paypal-payments/#button-on-mini-cart) is enabled in the PayPal Payments settings. This means the PayPal scripts will load on every page of your site. The Mini Cart is a global feature, and the scripts will load regardless of whether your theme actually provides a Mini Cart.
https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-scripts-on-every-page
So the best first step to reduce the load is by disabling the button on the Mini Cart.

But for questions regarding the setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
