### ISSUE TITLE
Failed transactions after disabling credit card option

### ISSUE THREAD

**Issue by theyoungercato** [woocommerce/woocommerce-paypal-payments#880]
### Describe the Bug

Customer orders are failing after enabling the credit card feature, then disabling it. The error in the logs is:

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. <a href="https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED " target="_blank">https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED </a>********************* [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. <a href="https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED " target="_blank">https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED </a>********************* Order status changed from Pending payment to Failed

### To Reproduce

1. Go to reusablesandmore.com
2. Click on any product, add to cart, then checkout 
3. Scroll down to payment method, pay via PayPal

### Expected Behavior

Payment is successful 

### Actual Behavior

An error shows, and the order is failed

### Environment

 - WordPress Version: 6.0.2
 - WooCommerce Version: 6.9.4
 - Plugin Version: 1.9.3
 - Browser [e.g. Chrome, Safari] and Version: All
 - Any other plugins installed: Many, but still occurs when others are disabled 

### Additional Details

Doesn't seem to happen for all customers 

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
@stacimail 

At this time, we will require a bit more information to look into and assist with this issue.

Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for assistance with this issue.
Please ignore this if you have already reached out to the support team.

Thanks.
