### ISSUE TITLE
tengo ahora mismo desconectado el pago por tarjeta de credito por paypal porque me estaba dando fallo, por que será?

### ISSUE THREAD

**Issue by alipau** [woocommerce/woocommerce-paypal-payments#885]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
For setup questions, please reach out to the support team as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Or directly from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
Kind regards,
Niklas
