### ISSUE TITLE
Place order Disappears at checkout page when choosing Credit/debit card payment method

### ISSUE THREAD

**Issue by MLotfy88** [woocommerce/woocommerce-paypal-payments#890]
when im using the plugin to accept payments in checkout page using paypal and credit card process, if checkout page on paypal option by default and changed it to credit card the place order button disappear
I tried so many other checkout page builders and providers but i found the same, 
Only Eccential addons for elemento pro worked just fine but with place orber button duplicated. 
The final bulder i tried now is woofunnels and the same problem, paypal smart button is good option in these case but card field is empty and has poor design. 
I had to use braintree plugin now and it's perfect. 

I'm just start testing and designing my ecommerce and i hope that you can provide something like braintree design in payment methods section at the checkout page

I'm using PHP 8.0.13
And the latest version of WordPress and woocommerce and paypal payments plugin

**Comment by InpsydeNiklas** [comment]
@MLotfy88 For setup questions please reach out to the support team as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Or directly from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
Kind regards,
Niklas
