### ISSUE TITLE
External cURL Request to PayPal on every page requests is slow down the whole website (backend & frontend)

### ISSUE THREAD

**Issue by chris-schreyer** [woocommerce/woocommerce-paypal-payments#891]
### Describe the Bug
On every request, regardless if frontend or backend, a curl request (php) is sent to paypal. The request is calling **https://api.paypal.com/v1/customer/partners/xxx/merchant-integrations/xxx**
The whole website pagespeed is now based on the response time of paypal. This slows down the whole website and should be fixed.

### To Reproduce

1. Install the Plugin Query Monitor and watch the "HTTP-API-Call" tab.
2. Browse to your WordPress Site (Frontend or Backend)
3. You'll see a Requests everytime.

### Screenshots
<img width="1736" alt="2" src="https://user-images.githubusercontent.com/27851529/194511873-cb68d00f-7966-4677-ab68-1eec0f6991a7.png">
<img width="1368" alt="3" src="https://user-images.githubusercontent.com/27851529/194511881-2c35c8c8-9eb8-4b4b-9115-138b3da7be46.png">

### Expected Behavior
The request should be called only when really needed. If we really need to fetch it on every request we should cache it.

### Environment

 - Latest WordPress Version
 - Latest WooCommerce Version
 - Latest Plugin Version
 - All Browsers because it's serverside (PHP)
 - I deinstalled all plugins and only tested it with (WooCommerce, woocommerce-paypal-payments and Query Monitor. A basic storefront theme is installed with no modifications).

**Comment by E-VANCE** [comment]
I second this...! 🥈

Have been debugging our website and these API calls occur on **every page load** (!) and massively impact the load time – we see the same behaviour when using the sandbox `https://api.sandbox.paypal.com/v1/customer/partners/xxx/merchant-integrations/xxx`

![CleanShot 2022-10-11 at 13 17 06](https://user-images.githubusercontent.com/4123541/195077847-b6089914-9747-4362-a683-7ac393530db2.png)

The penalties range between 500 and 1000ms which corresponds to a whopping ~ **20%**. Ouch.

Please fix this asap...

**Comment by zuim** [comment]
From what I found this should be fixed by commit 2938b15bc216b07acb67d5d5d02b489f8f10cf8e. So it should be fixed in the next release. 

If you don't use pay upon invoice you can just put `return false;` in the first line of pui_is_active() (https://github.com/woocommerce/woocommerce-paypal-payments/blob/521ba0e24aa58d2d5e45be03b1472dad1e5bf0fc/modules/ppcp-wc-gateway/src/Helper/PayUponInvoiceProductStatus.php#L61), to disable pui until the update is released.

**Comment by chris-schreyer** [comment]
Version 1.9.4 is out now and this version will fix this problem.
