### ISSUE TITLE
Trust Padges

### ISSUE THREAD

**Issue by MLotfy88** [woocommerce/woocommerce-paypal-payments#894]
At the standard smart button in credit/debit card form field there is no data or even no trust padges like logos fo visa, mastercard, American express, others. 

Can you add a little bit of customization like choosing trust padges to appear and add a description or any text??!

[Untitled999.png](https://user-images.githubusercontent.com/113838543/194576380-7d1e629e-cfb4-4d2b-9ce6-2dd6e5f0b68a.png)

**Comment by InpsydeNiklas** [comment]
What exactly are you looking for? A gateway icon? 
For the time being, only the PayPal Card Processing comes with included gateway icons: https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing-acdc
But custom icons could also be added with a filter like this: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#adding-a-gateway-icon
There is also a feature that allows you to split the black card button into a separate payment gateway, so it will not be rendered inside the regular PayPal gateway. For now, this can only be enabled with a small extra plugin, and the [support team would be happy to assist from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!

Kind regards,
Niklas
