### ISSUE TITLE
Credit Card processing for your account has not yet been activated by PayPal

### ISSUE THREAD

**Issue by IlPizza79** [woocommerce/woocommerce-paypal-payments#898]
### Describe the Bug

Like some other users, I have the "Credit Card processing for your account has not yet been activated by PayPal. If your account is new, this can take some days. Otherwise, please get in contact with PayPal.". But **my account is NOT new**, it exists at least since 2/3 years... 

So, what should I do? How can I "get in contact with PayPal" or fix the issue?

### To Reproduce
I've upgraded form the old PayPal payment to the new  "WooCommerce PayPal Payments". I've followed the steps and connected my PayPal account with no errors.

### Screenshots
![Impostazioni-WooCommerce](https://user-images.githubusercontent.com/48421419/194848158-8176e04d-4141-4ee2-9e6e-675c516670cd.jpg)

### Expected Behavior
Well, I was expecting to have no isuue or at least a clear explanation on how to fix my issue.

### Actual Behavior
Like I said, I got the error "Credit Card processing for your account has not yet been activated by PayPal. If your account is new, this can take some days. Otherwise, please get in contact with PayPal."

### Environment
Everything in my website is updated to the latest version available.

### Additional Details
My website right now is in maintenace mode. Is that related to my issue?

**Comment by InpsydeNiklas** [comment]
@IlPizza79 The PayPal account must be enabled for advanced card payments, otherwise you will see this message. 
You can [sign up for this feature](https://woocommerce.com/document/woocommerce-paypal-payments/#sign-up-for-advanced-card-payments) during the onboarding process when selecting `Advanced Card Processing`.
For any questions regarding the onboarding, please get in touch with the [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!

**Comment by IlPizza79** [comment]
Thank you for your reply, I've enabled for my account and now it works.
But let me say it would be nice to add some more info in the error message, like the link you provided.
Thanks again :-)

**Comment by InpsydeNiklas** [comment]
The current error messaging is not optimal, I agree. But the entire settings UI is being reworked, so in the next update 1.9.4 the `PayPal Card Processing` tab will be hidden when your account is not enabled for advanced card payments. 
Instead, there is a new `Connection` tab from where the sign-up can be initiated: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/1.9.4-rc1

**Comment by IlPizza79** [comment]
Hi, that's really nice! I think it would be much easier for the average user to understand how to get it done :-)
Thanks again, and keep up the good work :-)
