### ISSUE TITLE
Payments get blocked one account is made

### ISSUE THREAD

**Issue by alanoitaliano** [woocommerce/woocommerce-paypal-payments#902]
### Describe the Bug

On my site, I have disabled billing address, country code, town etc.
Enabled guest buying.
I'm just selling VIP subscriptions for my server so I only need: First name, e-mail, Discord ID (Custom Field), Steam ID (Custom Field).

When someone goes straight into buying a VIP package without making an account everything goes thru.
When someone enters my site, makes an account first, then tries to buy Paypal throws generic error "Something went wrong....." and in console I see "TypeError: Cannot read properties of undefined (reading 'country_code')"
Then if they go to My account > input their addresses again everything works.

To solve this for now, I enabled all billing fields but left optional. Then even if You input only first name, e-mail. steam id, discord id the payments goes thru.

But I would love to keep my shop clean and disable completely those fields. 

### To Reproduce

Install Checkout Field Editor by ThemeHigh.
Disable billing information (Probably any?)
Allow users to buy without account
Make an order without account - should pass.
Make an account first then head to shop and buy - should output error.

### Expected Behavior

Let people buy when making an account with billing information disabled.

### Actual Behavior

Paypal throws error "TypeError: Cannot read properties of undefined (reading 'country_code')" in console, paypal window appears for a fraction of second and dissapears.

### Environment

 - WordPress Version: 6.0.2
 - WooCommerce Version: 6.9.4
 - Plugin Version: 1.9.3
 - Browser [e.g. Chrome, Safari] and Version: Doesn't matter in this situation
 - Checkout Field Editor by ThemeHigh

**Comment by InpsydeNiklas** [comment]
@DJAlo This behavior is expected when the `Default customer location` setting is set to `No location by default`.
The default WooCommerce payment gateways will throw a similar error when the billing fields are hidden, and no billing country is set for the buyer.
If you unset the billing country field in the checkout, the WooCommerce General settings `Default customer location` must be configured with `Shop country/region` (or Geolocate). Then the customer should automatically have the shop country assigned.
So this is not directly a plugin issue, but WooCommerce requiring a billing country for the customer to process orders for existing customers.
For questions regarding the setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
