### ISSUE TITLE
paypal not working 

### ISSUE THREAD

**Issue by philippe-ostral** [woocommerce/woocommerce-paypal-payments#907]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by bashgeek** [comment]
I have to say, this must be the best bug report I've ever seen.

**Comment by InpsydeNiklas** [comment]
@philippe-ostral For questions regarding the setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
