### ISSUE TITLE
Could not retrieve order. OrderEndpoint.php:466 Order status changed from Awaiting Payment to Failed.

### ISSUE THREAD

**Issue by cdric0701** [woocommerce/woocommerce-paypal-payments#911]
### Describe the Bug

Could not retrieve order. OrderEndpoint.php:466 Order status changed from Awaiting Payment to Failed.

### To Reproduce

1. Choose the product (or products)
2. Add to Cart
3. Pay for the order

### Screenshots

![image](https://user-images.githubusercontent.com/6715950/195513394-c61fed42-a657-4477-99d1-3514db9de718.png)
![image](https://user-images.githubusercontent.com/6715950/195513538-05147bb9-f993-4fc2-a43e-0aa6c30ba881.png)

### Expected Behavior

Create an order manually and proceed to payment.

### Actual Behavior

Could not retrieve order. OrderEndpoint.php:466 Order status changed from Awaiting Payment to Failed.
The $order_gateway->process_payment($order->get_id()); result is result : failure and order status : Could not retrieve order

### Environment

 - WordPress : 6.0.2
 - WooCommerce : 7.0.0
 - Plugin Version : 1.9.4
 - Browser Firefox and Chrome

### Additional Details

Use of function on button submit : $order_gateway->process_payment($order->get_id());
The order gateway used is : ppcp-gateway
With prior creation of the order in woocommerce with function wc_create_order (in WooCommerce Core Functions).

It worked well with : WooCommerce PayPal Checkout Gateway but not with WooCommerce PayPal Payments.
<details><summary>System status</summary>

</details>

**Comment by arnauvp** [comment]
We are also impacted by it.

**Comment by femiyb** [comment]
Hello @arnauvp @cdric0701  

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with more information regarding this issue for assistance. Thanks!
