### ISSUE TITLE
PAYEE_ACCOUNT_RESTRICTED The merchant account is restricted.

### ISSUE THREAD

**Issue by octavaclero** [woocommerce/woocommerce-paypal-payments#912]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
This error means there is a restriction on your PayPal account. 
To resolve this, you must reach out to the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/).
