### ISSUE TITLE
WooCommerce PayPal Payments is not working well

### ISSUE THREAD

**Issue by Fanaticracks** [woocommerce/woocommerce-paypal-payments#914]
### Describe the Bug

Hi,

I set the configuration successfully in 'WooCommerce PayPal Payments', but now is not allowing me to save changes in the 'manage' section of it. For example, I cannot activate the buttons at checkout, although I do click on the 'checkbox' for 'activate buttons at checkout' the saving changes are having no effect.

I'll appreciate any help on the matter, please, thank you!

### To Reproduce

I do click on the 'checkbox' for 'activate buttons at checkout' but the saving changes are having no effect.

### Expected Behavior

When I do click on the 'checkbox' for 'activate buttons at checkout', I'd expect to save changes successfully.

### Actual Behavior

When I do click on the 'checkbox' for 'activate buttons at checkout', save changes are having no effect.

### Environment

 - WordPress Version - 6.0.2
 - WooCommerce Version - 
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Fanaticracks, This sounds like a potential conflict with another plugin. 
Please ensure third-party plugins (like Checkout Field Editor) are updated to the latest version.
If the problem persists after [troubleshooting](https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting), please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thanks!
