### ISSUE TITLE
Activation failure

### ISSUE THREAD

**Issue by mmrvistagrande** [woocommerce/woocommerce-paypal-payments#915]
### Describe the Bug

activation goes to a page which has a revoked certificate.  Instead of going to https://www.paypal.com/ it goes to https://paypal.com/ which is not okay.

### To Reproduce

Click Activate PayPal button  ,popup with login appears,  entered email and clicked next, another screen flashes on the popup and quickly changes to another saying

   Secure Connection Failed

   An error occurred during a connection to paypal.com. Peer’s Certificate has been revoked.

   Error code: SEC_ERROR_REVOKED_CERTIFICATE

**Comment by prunly** [comment]
@mmrvistagrande - I had this same issue yesterday and was able to get around it by using Chrome to authenticate instead of Firefox. Not sure if it was dumb luck or if this will solve your problem. In any case, not a smooth process!

**Comment by Sirvijver** [comment]
Hello @mmrvistagrande 

If you are still encountering this issue, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We don't provide merchant support via GitHub, so I will close this thread.

Kind regards, 
Joost
