### ISSUE TITLE
Critical Error when plugin enabled.

### ISSUE THREAD

**Issue by bizactuator** [woocommerce/woocommerce-paypal-payments#919]
### Describe the Bug
Critical error when enabled. (Plugin is active, and no error if I don't have the payment method turned on. if I turn the payment method on, I get this error. If I turn paypal OFF so it does not use it, but keep the plugin active, the error goes away.)

Here is the error when debug is turned on:

"Fatal error: Uncaught TypeError: WooCommerce\PayPalCommerce\ApiClient\Entity\Address::__construct(): Argument #1 ($country_code) must be of type string, bool given, called in /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/AddressFactory.php on line 41 and defined in /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Entity/Address.php:69 Stack trace: #0 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/AddressFactory.php(41): WooCommerce\PayPalCommerce\ApiClient\Entity\Address->__construct(false, '', '', '', '', '') #1 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/PayerFactory.php(111): WooCommerce\PayPalCommerce\ApiClient\Factory\AddressFactory->from_wc_customer(Object(WC_Customer), 'billing') #2 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(936): WooCommerce\PayPalCommerce\ApiClient\Factory\PayerFactory->from_customer(Object(WC_Customer)) #3 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(829): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->payerData() #4 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php(545): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->localize_script() #5 /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/ButtonModule.php(70): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->enqueue() #6 /home/aird/public_html/wp-includes/class-wp-hook.php(307): WooCommerce\PayPalCommerce\Button\ButtonModule::WooCommerce\PayPalCommerce\Button\{closure}('') #7 /home/aird/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #8 /home/aird/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #9 /home/aird/public_html/wp-includes/script-loader.php(2156): do_action('wp_enqueue_scri...') #10 /home/aird/public_html/wp-includes/class-wp-hook.php(307): wp_enqueue_scripts('') #11 /home/aird/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #12 /home/aird/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #13 /home/aird/public_html/wp-includes/general-template.php(3042): do_action('wp_head') #14 /home/aird/public_html/wp-content/themes/flexia/header.php(19): wp_head() #15 /home/aird/public_html/wp-includes/template.php(770): require_once('/home/aird/publ...') #16 /home/aird/public_html/wp-includes/template.php(716): load_template('/home/aird/publ...', true, Array) #17 /home/aird/public_html/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #18 /home/aird/public_html/wp-content/plugins/elementor/modules/page-templates/templates/header-footer.php(9): get_header() #19 /home/aird/public_html/wp-includes/template-loader.php(106): include('/home/aird/publ...') #20 /home/aird/public_html/wp-blog-header.php(19): require_once('/home/aird/publ...') #21 /home/aird/public_html/index.php(17): require('/home/aird/publ...') #22 {main} thrown in /home/aird/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Entity/Address.php on line 69"

### To Reproduce

1. Go to https://airdefensebadge.com
2. Click on '…' (Just go to website... on Desktop I get critical error)
3. See error

### Screenshots
https://www.screencast.com/t/YZS4AuVAuSd

### Expected Behavior
Page should load sales page (home page). 
it works fine if I have the paypal plugin disabled.

### Actual Behavior
when enabled, the home page has error.

### Environment

 - WordPress Version Most current today.
 - WooCommerce Version most current today.
 - Plugin Version most current, today.
 - Browser [e.g. Chrome, Safari] and Version, all browsers I have, Chrome, Firefox, Edge, opera
 - 
 - Any other plugins installed (lots but error only happens when this one is enabled.)

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by bizactuator** [comment]
actually, it is ONLY when I'm logged in as admin the error happens. when I sign out, no error.

So how do I fix that?

**Comment by femiyb** [comment]
Hello @bizactuator 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
