### ISSUE TITLE
Paypal Button Not showing in checkout page

### ISSUE THREAD

**Issue by iconbaaz** [woocommerce/woocommerce-paypal-payments#931]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
Hello @iconbaaz 

For assistance with support-related issues, [please reach out to the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).
Thanks.
