### ISSUE TITLE
Issue with pay in 3 text on single product page woocommerce

### ISSUE THREAD

**Issue by designboxuk** [woocommerce/woocommerce-paypal-payments#932]
When you are on the single product pages, below the "add to basket buttons" you can see the pay in 3 text bugging in and out of display on the screen continuously. The console is flagging an error with Venmo pay in 3 but I am not sure how this can be fixed.

1. Go to https://postaltubeshop.com/product/nutcracker-soldier-cardboard-tube-set/
2. View the checkout section

**I would add screenshots but not applicable**

I need this PayPal section to be functional and not flicker in and out of display.

Plugin details are as follows:

 - WordPress Version 6.0.3
 - WooCommerce Version 7.0.0
 - PayPal Payments Plugin Version 1.9.4
 - Browser: Chrome

**Comment by Sirvijver** [comment]
Hello @designboxuk 

I took a look at the product, cart and checkout page and for me the Pay Later text showed up correctly and as expected.
If you are still encountering this issue, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We do not provide merchant support via GitHub, so I will close this thread.

Kind regards, 
Joost
