### ISSUE TITLE
How to translate the text associated to the button Paypal

### ISSUE THREAD

**Issue by colourinvasion** [woocommerce/woocommerce-paypal-payments#935]
![Imagem1](https://user-images.githubusercontent.com/90452946/197589294-4067d62e-139b-471a-928e-50889ca97408.png)

**Comment by InpsydeNiklas** [comment]
The tagline cannot be translated from the plugin perspective. PayPal automatically provides an appropriate language version of the buttons and tagline for every individual website visitor: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-translating-paypal-payments
The language can only be actively impacted when clearing all PayPal cookies and setting a different browser language.

For any questions regarding the plugin setup, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
