### ISSUE TITLE
i need help please +359 878685719

### ISSUE THREAD

**Issue by xioazuki** [woocommerce/woocommerce-paypal-payments#939]
i tried to connect my paypal to my site and the button doesnt wok. I click the ''paypal'' button and nothing happens

**Comment by Sirvijver** [comment]
Hello @xioazuki 

We do not provide support for our plugin via GitHub, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.
When you do: please also provide the system report and more details when possible.

Kind regards, 
Joost
