### ISSUE TITLE
Failed to process the payment (ORDER_NOT_APPROVED) but payment received successfully on Paypal

### ISSUE THREAD

**Issue by Murgator** [woocommerce/woocommerce-paypal-payments#940]
### Describe the Bug

A customer pay with Paypal (I received the payment on Paypal) but the order status became FAILED on woocommerce here is the error obtained below. It happened to one of my customer on Monday October 16, 2022.

### To Reproduce

Choose the product (or products)
Add to Cart
Pay for the order
See error

### Screenshots

![93391f446d8ccfb81b579c7146751f21](https://user-images.githubusercontent.com/38978895/197964737-ee64b528-e645-42ee-ad06-74d8518781d7.png)

### Expected Behavior

Create an order and proceed to payment.

### Actual Behavior

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED PayPalGateway.php:500 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_NOT_APPROVED OrderEndpoint.php:313 État de la commande modifié de Attente paiement à Échouée.

### Environment

 - WordPress: 6.0.3
 - WooCommerce: 7.0.0
 - Plugin: 1.9.4
 - Browser: Chrome

### Additional Details

I use WooCommerce PayPal Payments and enable Paypal 4x

**Comment by Sirvijver** [comment]
Hello @Murgator 

We have not seen this issue before, so from the information you provided, we cannot tell you what could be the case here. However, we do not provide plugin support via GitHub and would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you still need support on this matter.

If you do open a support request, please make sure you include your system report. This ticket will be closed.

Kind regards, 
Joost
