### ISSUE TITLE
paypal disappeared

### ISSUE THREAD

**Issue by mondoinformaticastore** [woocommerce/woocommerce-paypal-payments#944]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
Hello @mondoinformaticastore 

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with more information about this issue for assistance. Thanks!
