### ISSUE TITLE
Error processing checkout. Please try again. 

### ISSUE THREAD

**Issue by steve-agl** [woocommerce/woocommerce-paypal-payments#945]
I hav a recurring problem, if i do buy as a logged in user all is ok when i try as anonymous, asking all data the payment is processed, i see it on paypal and woocommerce show it too, but user don't go to than you page but still at checkout page with this error:

Error processing checkout. Please try again. (well in italian but this is the original string) 

This force us to go on maintenance, before we use this pluign (to support Pay later option, all was ok vit the standard paypal plugin

**Comment by femiyb** [comment]
Hello @steve-agl 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. 
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
