### ISSUE TITLE
can't make payment

### ISSUE THREAD

**Issue by PirateXGG** [woocommerce/woocommerce-paypal-payments#948]
Hello
i install the plugin and setup all settings and use the sandbox and it successful connected
but in checkout page when i try to chose tha paypal it's loading for ever and nothing happens
![Capture](https://user-images.githubusercontent.com/84042172/198859055-a3afd612-1075-4c26-a38b-e8a70eb7caa9.PNG)

**Comment by femiyb** [comment]
Hello @PirateXGG 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
