### ISSUE TITLE
Can't login to my Paypal account from my webstore!

### ISSUE THREAD

**Issue by alhakeem2001** [woocommerce/woocommerce-paypal-payments#949]
I can't access my Paypal account to test my payment process, I have checked everything on my payment setting on my admin side, and all it seems ok, what should I do now?

Thanks, 

OM

**Comment by Sirvijver** [comment]
Hello @alhakeem2001,

Thank you for reaching out. The issue you describe sounds to me like an account issue, or are you having issues onboarding your account to your website?

In any case, the GitHub site is only used by us for development activities. We support the merchants via other site, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I will close this ticket.

Kind regards, 
Joost
