### ISSUE TITLE
DCC Form hidden when PPC is include in Hide Funding Methods

### ISSUE THREAD

**Issue by cmpktwrkshp** [woocommerce/woocommerce-paypal-payments#95]
### Describe the bug
If Disable Funding Sources contains 'Credit or Debit Cards', then the ACDC/DCC option is hidden as a payment option in the listed payment methods on the cart page even if ADCD/DCC is enabled.

### To reproduce

1. Add Credit or Debit Cards to Disable Funding Sources
2. View checkout page with default wordpress theme.

### Expected behavior
The payment methods available to the buyer should contain PayPal AND the ACDC/DCC payment option from PayPal.

**Environment (please complete the following information):**
 - WordPress Version : 5.6
 - WooCommerce Version : 4.8.0
 - WooCommerce PayPal Payments Plugin Version : 1.0.3
 - Browser [e.g. chrome, safari] and Version : Chome 87.0.4280.88
 - Any other plugins installed - yes, many; however, only WooCommerce, WooCommerce PayPal Payments, and Server Info plugins are activated at time of testing.

**Comment by james-allan** [comment]
Hi, there @Bruuuuuce. 

Could you elaborate on what you mean by _ADCD/DCC_? Screenshots might also help us understand and replicate. 

Thanks :)

**Comment by jorgeatorres** [comment]
Hi @Bruuuuuce!

Thanks for the report! I wasn't able to reproduce this in the latest version and so I'm going to close the issue for now. Feel free to re-open if you're still having trouble or if you feel I've missed something. Thanks again!
