### ISSUE TITLE
PayPal Payments Not Working With New WooCommerce Checkout Blox

### ISSUE THREAD

**Issue by daviddobric** [woocommerce/woocommerce-paypal-payments#951]
The PayPal Payments developed by WooCommerce/Automatic is not working on the new WooCommerce Checkout page which is generated by the WP Blocks. I had everything working on my site but when I changed to the new Checkout Blocks everything works fine ecept PayPal which is not showing on the page at all.. I have created several new websites and installed again WooCommerce new checkout blocks and also PayPal payments but again, everything works fine except PayPal.

Pls.. your respond on this issue as soon as possible.

**Comment by openmindculture** [comment]
This seems the exact problem in our block theme. While PayPal express checkout can be displayed on product details pages, there is no PayPal payment option showing in the regular WooCommerce checkout. We already tried various combinations with or without other payments like credit card or invoice, both works, but PayPal doesn't.

Our checkout page is not customized as a full-site-editing template, but we use the [WooCommerce Blocks](https://de.wordpress.org/plugins/woo-gutenberg-products-block/) plugin, as we customized other parts of the shop. We also use [WooCommerce Payments](https://de.wordpress.org/plugins/woocommerce-payments/) to be able to provide alternative payment methods.

In the checkout page source code, we can see that WooCommerce is using block templates, according to the wrapper class names: `div class="wc-block-components-main wc-block-checkout__main wp-block-woocommerce-checkout-fields-block"`.

PayPal is set to use a live account, but it did not work in the sandbox mode either.

PayPal support also checked our installation and concluded that we need to contact WooCommerce plugin support:

> Please keep in mind that PayPal does not author the plugins that WooCommerce allows to be installed on their websites (even though those plugins send transaction requests to PayPal.) Merchants will need to contact WooCommerce Support or the plugin author/developers for their recommendation as to how they can integrate PayPal Payouts

**Comment by openmindculture** [comment]
Could it probably help to disable the [WooCommerce Blocks (woo-gutenberg-products-block) plugin](https://wordpress.org/plugins/woo-gutenberg-products-block/)? as its documentation states that we do not need the blocks plugin unless we want to use new, non-standard WooCommerce blocks.

I will try to [switch the WooCommerce checkout back to classic (without blocks)](https://wordpress.org/support/topic/use-classic-woocommerce-checkout-but-still-use-blocks-otherwise/#post-16153168), hopefully without losing the option to use block syntax and block themes for products, shop archives, and other custom pages elsewhere, as suggested in the WordPress WooCommerce plugin support forum.

But as we want to use block themes with full-site editing options wherever possible, and as WooCommerce seems to default to a block checkout at least in our configuration, it would still be good to see full plugin support using block syntax.

**Comment by openmindculture** [comment]
Possibly the PayPal Payment plugin relies on a hook that is only used in the classic PHP version of the checkout? We had a similar issue with another plugin that worked with the server-side shortocde / PHP version, but not with the new block alternative which used client side JavaScript to fetch the WordPress API, thus bypassing the expected PHP hooks.

**Comment by daviddobric** [comment]
We've tried everything possible even disabling the whole guttenberg edditor and the woocommerce blocks but non of them respond. I think it`s a bug related to .php it simply doesnt call the paypal .php files. What we also found is, it works on some settinging enabled on single product checkout but not in cart and checkout pages. Very strange issue, even our developers can't solve it. Please someones reposnd asap.

**Comment by daviddobric** [comment]
On the checkout page, none of the payment options offerd by paypal are showing-up. Even not the PayPal buttons! Eve zou know the solution, please share it with me. Thank you!

**Comment by openmindculture** [comment]
This is what WooCommerce support wrote to me:

> You can replace the Checkout block with the Classic (aka Shortcode) version in your checkout page.
> To do that, you need to:
> - edit the Checkout page (in Admin > Pages)
> - remove the Checkout block
> - add a Shortcode block, and enter [woocommerce_checkout] in the text field.

Source: https://wordpress.org/support/topic/use-classic-woocommerce-checkout-but-still-use-blocks-otherwise/#post-16153168

**Comment by daviddobric** [comment]
This does not solve the problem. I did this to restore the older CheckOut layout so that PayPal works the way it should. But we want the new checkout layout, we just want the PayPal buttons to appear :)

**Comment by daviddobric** [comment]
We've reverted the checkout pages back to the older look, but the newer block version is much better and looks nicer.

**Comment by openmindculture** [comment]
Thanks @daviddobric for sharing your experience! I have submitted a feature request to WooCommerce as well. I will update this post when our request gets accepted and published.

**Comment by InpsydeNiklas** [comment]
The new Cart and Checkout are [not yet supported](https://woocommerce.com/document/cart-checkout-blocks-support-status/#section-9) by PayPal Payments: https://woocommerce.com/document/woocommerce-paypal-payments/#faq-does-paypal-payments-support-blocks
So the plugin only works with the shortcode Cart and Checkout pages.
Block support is one of the top priority items on the roadmap and is expected to be available in the coming months. 
The progress for this will be tracked in #211, so I am closing this issue.
For any questions regarding the plugin setup, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

**Comment by openmindculture** [comment]
We changed
- the checkout back to classic (shortcode `[woocommerce_checkout]`
- the cart back to classic (shortcode `[woocommerce_cart]`
but still struggling with
- the mini cart (provided by the [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) which does not display any PayPal button despite the option to display one is activated in the WP-Admin backend,
and getting erratic error messages in the classic checkout (more details below).

When the payment section loads, there are WooCommerce payments (like credit card), and, alternatively, PayPal below. Clicking on "PayPal" opens another section that temporarily shows the PayPal logo, then getting replaced by a text that simply says "PayPal". Error messages and warnings are only in the developer console.

If a customer presses a checkout button _before_ proceeding to the checkout, they will be guided to PayPal login etc in a new window. When they come to the checkout and select "PayPal", they can complete their order successfully.

But customers who go to checkout via the mini cart, which does not display any PayPal button, cannot complete their checkout when selecting PayPal as a payment.

We identified three different error message scenarios, all in the developer tools only, no error or warning displayed to the customers.

1. unhandled_error {err: 'TypeError: Cannot read properties of null...
  - `{err: 'TypeError: Cannot read properties of null (reading 'nodeType')\n    at https://www.paypal.com/sdk/js?client-id=...`
  
```
{msg: 'Script error. - : 0'}
error	@	putHtmlCodeToDom.tsx:27
f.win.onerror	@	6af62a6……7c1381ac7101e5d8b:2
error (async)
```
  
2. Error: Detected container element removed from DOM
  - 
```
  unhandled_error {err: 'Error: Detected container element removed from DOM
  at js?client-id=...
  at HTMLDivElement.<anonymous> (jquery.min.js?ver=3.6.1:2:50996)
    at He (jquery.min.js?ver=3.6.1:2:48094)
    at S.fn.init.replaceWith (jquery.min.js?ver=3.6.1:2:50895)
    at String.<anonymous> (checkout.min.js?ver=7.3.0:1:8408)
    at String.<anonymous> (hijackJQueryEach.tsx:41:21)
    at Function.each (jquery.min.js?ver=3.6.1:2:3053)
    at t.each (hijackJQueryEach.tsx:34:50)
p | @ | 6af62a6……7c1381ac7101e5d8b:2
-- | -- | --
  | _ | @ | 6af62a6……7c1381ac7101e5d8b:2
  | h | @ | 6af62a6……7c1381ac7101e5d8b:2
  | (anonymous) | @ | putHtmlCodeToDom.tsx:21
  | c | @ | putHtmlCodeToDom.tsx:19
  | (anonymous) | @ | optIn.tsx:40
  | iterateServices | @ | getServiceSelection.tsx:50
  | await in iterateServices (async) |   |  
  | (anonymous) | @ | optIn.tsx:23
  | v | @ | apply.tsx:50
  | await in v (async) |   |  
  | t | @ | gateway.tsx:22
  | (anonymous) | @ | gateway.tsx:35
  | await in (anonymous) (async) |   |  
  | (anonymous) | @ | useBannerPreDecisionGateway.tsx:36
  | S | @ | 6af62a6……7c1381ac7101e5d8b:2
  | (anonymous) | @ | 6af62a6……7c1381ac7101e5d8b:2
  | w | @ | 6af62a6……7c1381ac7101e5d8b:2
  | setTimeout (async) |   |  
  | n | @ | 6af62a6……7c1381ac7101e5d8b:2
  | requestAnimationFrame (async) |   |  
  | (anonymous) | @ | 6af62a6……7c1381ac7101e5d8b:2
  | a.YM.diffed | @ | 6af62a6……7c1381ac7101e5d8b:2
  | M | @ | 6af62a6……7c1381ac7101e5d8b:2
  | w | @ | 6af62a6……7c1381ac7101e5d8b:2
  | M | @ | 6af62a6……7c1381ac7101e5d8b:2
  | w | @ | 6af62a6……7c1381ac7101e5d8b:2
  | M | @ | 6af62a6……7c1381ac7101e5d8b:2
  | w | @ | 6af62a6……7c1381ac7101e5d8b:2
  | M | @ | 6af62a6……7c1381ac7101e5d8b:2
  | Y | @ | 6af62a6……7c1381ac7101e5d8b:2
  | q | @ | 6af62a6……7c1381ac7101e5d8b:2
  | (anonymous) | @ | banner.tsx:36
  | a | @ | ready.tsx:68
  | (anonymous) | @ | ready.tsx:76
  | a | @ | ready.tsx:55
  | 1307 | @ | banner.tsx:22
  | o | @ | bootstrap:19
  | (anonymous) | @ | startup:4
  | o.O | @ | chunk loaded:23
  | (anonymous) | @ | startup:5
  | (anonymous) | @ | 0ce7e83……79e12e03623ffb364:1
```
3. `"PayPal Message has been hidden. Message must be visible and requires minimum dimensions of 318px x 24px. Current container is 968.015625px x 24.015625px."`

The third one is quite osbcure, as I would love to unhide a message in our theme, if only there was a message in the DOM. Maybe related to the second one. Who removed which DOM element, when, for what reason, and if this should be prevented, how to do so?
