### ISSUE TITLE
AMOUNT_MISMATCH error for Pay upon Invoice with inserted coupon (Germany)

### ISSUE THREAD

**Issue by AndrijaSobak** [woocommerce/woocommerce-paypal-payments#952]
Some orders fail to complete because they get "AMOUNT_MISMATCH /purchase_units/@reference_id=='default'/amount/value Should be equal item_total + tax_total + shipping + handling + insurance - shipping_discount - discount" error. From observed it happens on random as I compared two orders with Pay upon Invoice gateway which both have 1 product and same coupon, one has a product worth 41,97€ without taxes and payment succeeds other has product worth 50,38€ without taxes and it fails.

First order that succeeded:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/117084710/199003106-c9db6afc-4390-4559-a0e1-fcb1a8099b46.png)

Second order that failed:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/117084710/199003190-c3f82820-6dd7-41d7-a1a5-6acc0e011967.png)

 - WordPress Version 6.0.3
 - WooCommerce Version 7.0.0
 - Plugin Version 1.9.4

This was already reported before with version 1.9.0 but a fix was pulled with version 1.9.1, 1 week and 5 days ago another guy reported same issue from Germany. ([Reported here](https://wordpress.org/support/topic/item_total_mismatch-error-message-3/))

Could you please advise me what can I do so that it may be helpful in pin pointing the error so fix is rolled out as fast as possible?

**Comment by MarcJandt** [comment]
We're experiencing the same issue. Once we've activated detailed logging, we were able to see the issue (seemingly) being a problem with rounding (we're using prices including VAT in our product's setup).

`Request Body: {"intent":"CAPTURE","processing_instruction":"ORDER_COMPLETE_ON_PAYMENT_APPROVAL","purchase_units":[{"reference_id":"default","amount":{"currency_code":"EUR","value":"27.78","breakdown":{"item_total":{"currency_code":"EUR","value":"24.29"},"shipping":{"currency_code":"EUR","value":"2.70"},"tax_total":{"currency_code":"EUR","value":"4.44"},"discount":{"currency_code":"EUR","value":"3.64"}}}`

You can see that 24.29 + 2.70 + 4.44 - 3.64 equals to 27.79 instead of 27.78.

The item's price is 28.90 including 19 % VAT.
15 % discount and 3.21 shipping including VAT.

28.90 * 0.85 + 3.21 equals 27.78
without VAT and adding it later on:
(24.29 * 0.85 + 2.70) * 1.19 equals 27.78 as well
using absolute values:
(24.29 - 3.64 + 2.70) * 1.19 equals 27.79

@AndrijaSobak Same happens on your second order, where 50.38 - 5.03 + 8.62 equals 53.97 instead of the shown 53.96.

**Comment by AndrijaSobak** [comment]
@MarcJandt Nice find! Thank you for pointing it out, I'm not sure how I missed that in my calculation.

So this may be problem with WooCommerce itself and how it calculates.

I have found function ditch_items_when_mismatch which is causing this error and description is "All money values send to PayPal can only have 2 decimal points. WooCommerce internally does not have this restriction. Therefore the totals of the cart in WooCommerce and the totals of the rounded money values of the items, we send to PayPal, can differ. In those cases, we can not send the line items." and I believe the problem lies here with rounding.

It calculates $total - (float) $item->unit_amount()->value_str() * (float) $item->quantity() then it rounds it to two decimal points, maybe using flag PHP_ROUND_HALF_UP or PHP_ROUND_HALF_DOWN here would fix the problem. Rounding is done for taxes as well, so maybe same thing here.

**Comment by wolkenkrieger** [comment]
A quickfix for this is to set the number of decimals to 4 (settings -> general) and format the price via a filter

```
function kb_decimals_price_args($args): mixed {
	$args['decimals'] = 2;
	return $args;
}
add_filter('wc_price_args', 'kb_decimals_price_args', 10, 1);
```

BUT!!! the email-text for the ratepay payment-info builds his price NOT via wc_price() so the price will shown with 4 decimals :/

**Comment by AndrijaSobak** [comment]
@wolkenkrieger Did you maybe found out where does ratepay payment-info get the price? So we can also filter the price there to show 2 decimals instead of 4.

**Comment by wolkenkrieger** [comment]
Yes in PayUponInvoice.php

`echo wp_kses_post( "<p>Bitte überweisen Sie den Betrag in Höhe von {$order->get_currency()}{$order->get_total()} bis zum {$order_date_30d} auf das unten angegebene Konto. Wichtig: Bitte geben Sie unbedingt als Verwendungszweck {$payment_reference} an, sonst kann die Zahlung nicht zugeordnet werden.</p>" );`

also see: https://github.com/woocommerce/woocommerce-paypal-payments/issues/986

**Comment by AndrijaSobak** [comment]
Would something like this work there:
{number_format($order->get_total(), 2, '.', ',')}

**Comment by wolkenkrieger** [comment]
my own implementation:

```
$price = wc_price($order->get_total(), $order->get_currency());
$order_date_30d = gmdate( 'd.m.Y', $thirty_days_date );
[...]

$content .= wp_kses_post( "<p>Bitte überweisen Sie den Betrag in Höhe von {$price} bis zum {$order_date_30d} auf das unten angegebene Konto. Wichtig: Bitte geben Sie unbedingt als Verwendungszweck {$payment_reference} an, sonst kann die Zahlung nicht zugeordnet werden.</p>" );

```

i cloned the email-order-detail.php and implemented my own hook to inject a well formed ratypay-text

**Comment by AndrijaSobak** [comment]
@wolkenkrieger Thank you so much, I'll go and test it out.

**Comment by wolkenkrieger** [comment]
email-order-details.php:

```
use WooCommerce\PayPalCommerce\WcGateway\Gateway\PayUponInvoice\PayUponInvoiceGateway;

defined( 'ABSPATH' ) || exit;

$text_align = is_rtl() ? 'right' : 'left';

if(PayUponInvoiceGateway::ID === $order->get_payment_method()) {
	do_action('itsw_email_before_order_table', $order, $sent_to_admin);
} else {
	do_action( 'woocommerce_email_before_order_table', $order, $sent_to_admin, $plain_text, $email );
}
 ?>

[...]
```

functions.php

```
/**
 * @param \WC_Order $order
 * @return string|null
 */
function itsw_pui_instructions(WC_Order $order): ?string {
	$instructions = $order->get_meta('ppcp_ratepay_payment_instructions_payment_reference');
	$gateway_settings = get_option( 'woocommerce_ppcp-pay-upon-invoice-gateway_settings' );
	$merchant_name    = $gateway_settings['brand_name'] ?? '';
	$order_date = $order->get_date_created();
	$price = wc_price($order->get_total(), $order->get_currency());
	
	if ( NULL === $order_date ) {
		return NULL;
	}
	
	$order_purchase_date = $order_date->date( 'd.m.Y' );
	//$order_time          = $order_date->date( 'H:i:s' );
	$order_date          = $order_date->date( 'd-m-Y H:i:s' );
	
	
	$thirty_days_date = strtotime( $order_date . ' +30 days' );
	
	if ( false === $thirty_days_date ) {
		return NULL;
	}
	
	$order_date_30d = gmdate( 'd.m.Y', $thirty_days_date );
	
	$payment_reference   = $instructions[0] ?? '';
	$bic                 = $instructions[1]->bic ?? '';
	$bank_name           = $instructions[1]->bank_name ?? '';
	$iban                = $instructions[1]->iban ?? '';
	$account_holder_name = $instructions[1]->account_holder_name ?? '';
	
	if (!$payment_reference || !$bic || !$bank_name || !$iban || !$account_holder_name) {
		return NULL;
	}
	
	$content = wp_kses_post("<p>Für Ihre Bestellung {$order->get_id()} vom {$order_purchase_date} bei {$merchant_name} haben Sie die Zahlung mittels “Rechnungskauf mit Ratepay“ gewählt.");
	//$content .= '<br>Bitte benutzen Sie die folgenden Informationen für Ihre Überweisung:</br>';
	$content .= wp_kses_post( "<p>Bitte überweisen Sie den Betrag in Höhe von {$price} bis zum {$order_date_30d} auf das unten angegebene Konto. Wichtig: Bitte geben Sie unbedingt als Verwendungszweck {$payment_reference} an, sonst kann die Zahlung nicht zugeordnet werden.</p>" );
	$content .= wp_kses_post( "<p>Empfänger: {$account_holder_name}" );
	$content .= wp_kses_post( "<br>IBAN: {$iban}" );
	$content .= wp_kses_post( "<br>BIC: {$bic}" );
	$content .= wp_kses_post( "<br>Name der Bank: {$bank_name}" );
	$content .= wp_kses_post( "<br>Verwendungszweck: {$payment_reference}</p>" );
	$content .= wp_kses_post( "<p>{$merchant_name} hat die Forderung gegen Sie an die PayPal (Europe) S.à r.l. et Cie, S.C.A. abgetreten, die wiederum die Forderung an Ratepay GmbH abgetreten hat. Zahlungen mit schuldbefreiender Wirkung können nur an die Ratepay GmbH geleistet werden.</p>" );
	
	return $content;
}

/**
 * @param \WC_Order $order
 * @param           $sent_to_admin
 * @return void
 */
function itsw_email_before_order_table(WC_Order $order, $sent_to_admin): void {
	if ( ! $sent_to_admin && PayUponInvoiceGateway::ID === $order->get_payment_method() && $order->has_status( 'processing' ) ) {
		echo itsw_pui_instructions($order);
	}
}

add_action('itsw_email_before_order_table', 'itsw_email_before_order_table', 10, 2);

```
not the golden way but it works so far^^

**Comment by Dinamiko** [comment]
Hi @AndrijaSobak,

Regarding `ditch_items_when_mismatch` method it was added to prevent `AMOUNT_MISMATCH` issues, it does not send line items to PayPal when there is a mismatch and therefore transaction is processed, that works for most PayPal payments, unfortunatelly it does not work for PUI as it's not possible to create an order without line items.

The rounding issues we are facing are usually because PayPal only accepts two decimals but WC allows managing more than two.

I'll give a try at @wolkenkrieger solution to see if we can provide at least a workaround till we found a better solution: https://github.com/woocommerce/woocommerce-paypal-payments/issues/952#issuecomment-1314920010

**Comment by AndrijaSobak** [comment]
> A quickfix for this is to set the number of decimals to 4 (settings -> general) and format the price via a filter
> 
> ```
> function kb_decimals_price_args($args): mixed {
> 	$args['decimals'] = 2;
> 	return $args;
> }
> add_filter('wc_price_args', 'kb_decimals_price_args', 10, 1);
> ```
> 
> BUT!!! the email-text for the ratepay payment-info builds his price NOT via wc_price() so the price will shown with 4 decimals :/

This function for whatever reason returns critical error.
"CRITICAL Uncaught TypeError: Return value of kb_decimals_price_args() must be an instance of mixed, array returned in..."

**Comment by wolkenkrieger** [comment]
mixed is for PHP version 8.x !!

set to array, if you use a 7.x

**Comment by AndrijaSobak** [comment]
Works now like a charm, thank you
