### ISSUE TITLE
Paypal button

### ISSUE THREAD

**Issue by haf1230** [woocommerce/woocommerce-paypal-payments#955]
### Describe the Bug
 the paypal button once appears and once disappears in desktop and on mobile it never shows!  i dont know where is the issue! you can check the error by visiting the site https://kjmoda.com/shop/men/hombre/zapatilla-rhyton-gucci-23/?wmc-currency=EUR 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
Hello @haf1230 

I checked the link you shared and I could see the PayPal button after a size option has been selected.
If the issue persists for you, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
