### ISSUE TITLE
WooCommerce PayPal Payments plugin does not work for payment processing. When it is seclected at checkout as the payment method, you get the error message "Something went wrong. Please try again or choose another payment source.". I have the gateway disabled at this time so you won't be able to test it unless you reach out and I enable it again. I am very concerned that having it live on the site will be concerning for customers.

### ISSUE THREAD

**Issue by paintedfoxhome** [woocommerce/woocommerce-paypal-payments#957]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by AndrijaSobak** [comment]
Dear @paintedfoxhome, I would suggest checking if option "Enable logging" is checked in Connection tab. I had the same problem and I fixed it by unchecking it.

**Comment by femiyb** [comment]
Hello @AndrijaSobak 

Please [reach out to the support team here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for assistance with this issue. Thanks!
