### ISSUE TITLE
Incompatibility with WooCommerce causes critical error

### ISSUE THREAD

**Issue by sympatrick** [woocommerce/woocommerce-paypal-payments#958]
Ever since WooCommerce released Version 7.0.0, I´ve been having the issue that whenever I update WooCommerce to 7.0.0 and have WooCommerce PayPal Payments enabled, it causes a Technical Error which crashes my site. I then have to restore a backup of the site.
In the "Your site is experiencing a technical issue" email I get from WordPress, it says: "Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WooCommerce PayPal Payments."

And it also says:
"When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.0.2
Active theme: BuddyBoss Child (version 1.0.0)
Current plugin: WooCommerce PayPal Payments (version 1.9.4)
PHP version 8.0.23

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 50 of the file /home/sympla5/[members.symplact.org/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/ProxyContainer.php](http://members.symplact.org/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/containers/src/ProxyContainer.php). Error message: Declaration of DhiiContainerProxyContainer::has($key) must be compatible with PsrContainerContainerInterface::has(string $id): bool"

I´ve already ruled out third-party plugin and theme incompatibilities. I´ve also tried re-installing PayPal Payments, but the issue persits. There seems to be a conflict between the code of WooCommerce PayPal Payments and WooCommerce itself, as stated in the Error Details above. For whatever reason, that conflict causes a critical error for me, and seemingly also a handful of other people, but not for everyone using these two plugins together.

**Comment by sympatrick** [comment]
It´s a three-way plugin conflict between WC, WC Paypal Payments, and "Bulgarisation for WooCommerce". Here´s a link to another user´s description of the problem: https://wordpress.org/support/topic/incompatible-with-woocommerce-paypal-payments/ .
The developers of the Bulgarisation plugin reply claiming that the problem lies with WooCommerce Paypal Payments.

**Comment by femiyb** [comment]
Hello @sympatrick 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
