### ISSUE TITLE
when doing add_action( 'woocommerce_email_before_order_table' ), 4th parameter should not be typrized or nullable

### ISSUE THREAD

**Issue by larsenlarsson** [woocommerce/woocommerce-paypal-payments#959]
see:
https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-wc-gateway/src/Gateway/PayUponInvoice/PayUponInvoice.php#L286

plugin and theme developers may call do_action( 'woocommerce_email_before_order_table' in other context than emails.

therefore the fourth parameter should be nullable if necessary or the typing should be omitted:

```
		add_action(
			'woocommerce_email_before_order_table',
			function( WC_Order $order, bool $sent_to_admin, bool $plain_text, ?WC_Email $email ) {
```

**Comment by InpsydeNiklas** [comment]
This was fixed already with the last update.
