### ISSUE TITLE
Paypal Button not working

### ISSUE THREAD

**Issue by Jeremynicholas** [woocommerce/woocommerce-paypal-payments#963]
When the paypal button is clicked at checkout it simply scrolls to the top of the page and nothing happens - no login popup. The settings are all correct and the account is linked.

**Comment by InpsydeNiklas** [comment]
The first best thing you can do if any issues arise is following [troubleshooting steps](https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting).
If you need further assistance with the plugin setup, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) as there is no support provided here on GitHub. Thanks!
