### ISSUE TITLE
WooCommerce PayPal Payments 1.9.5 Pay Upon Invoice - Stock correction on failed orders (967)

### ISSUE THREAD

**Issue by vonzurgathen** [woocommerce/woocommerce-paypal-payments#964]
With the Pay upon Invoice function, the stock level is also adjusted downward for failed orders. The query of the stock level correction therefore comes too early and would be unnecessary here.

**Comment by vonzurgathen** [comment]
nothing happens here?

**Comment by InpsydeNiklas** [comment]
Thanks for the report, this is being looked into.
