### ISSUE TITLE
PayPal activate not working

### ISSUE THREAD

**Issue by kan02** [woocommerce/woocommerce-paypal-payments#967]
### Describe the Bug

When I try to connect my paypal account it says that it is connected and I can go back to woocommerce, but when I do so; I am automatically logged out, I try to log back in; paypal not connected.

### Environment

 - WordPress Version 6.1
 - WooCommerce Version 7.0.1
 - Plugin Version 1.9.5
 - Chrome Version 107.0.5304.88

**Comment by femiyb** [comment]
Hello @kan02 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
