### ISSUE TITLE
No consideration of the quantity discount in the Paypal popup

### ISSUE THREAD

**Issue by issjut** [woocommerce/woocommerce-paypal-payments#968]
### Describe the Bug

We offer our customers a quantity discount and use the plugin "Conditional Discounts for WooCommerce by ORION" for this purpose. For example, the customer gets 1 USD discount on the single price if he buys more than 6 items. However, this seems to be just a display error, as the correct amount including the discount is charged at the end. Unfortunately, not all customers get that far and cancel the purchase beforehand. 

### To Reproduce

1. Go to 'https://babysbestfood.com/en/holle-organic-formula-pre/'
2. Add at least 6 products to the shopping cart
3. Click 'Checkout' in Mini Shopping Cart
4. Enter your billing information
5. Choose Paypal as payment method
6. Log in to your Paypal account
7. You see a different price in the popup compared to the total in the checkout

### Screenshots
https://paste.pics/37f2058bd9a63c81fc9bb19cc18bdd5b
https://paste.pics/a8d06cf33d6b90e0814f55208f0603b7

### Environment

 - WordPress Version 6.1
 - WooCommerce Version 7.0.1
 - Plugin Version 1.9.5
 - All Browser 
 - Conditional Discounts for WooCommerce by ORION 2.28.2
 - Theme: Minimog Version: 1.10.1 

### Additional Details

The theme author was also informed about the bug, but could not help so far.

**Comment by InpsydeNiklas** [comment]
This appears to be a remaining limitation from #642. But I can't reproduce the behavior with the free plugin version, so I suggest reaching out to the [support from the discount plugin](https://help.orionorigin.com/submit-ticket/).

It all depends on how exactly the discount is applied, and I'm not sure what else could be done here from the PayPal Payments perspective when the cart is not aware of the discount. Before the capture call is made, the plugin gets the updated totals from the WooCommerce order, which includes the discount. But what's displayed in the PayPal popup window depends on the cart content.

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if more guidance is needed. Thanks!
