### ISSUE TITLE
plugin was working fine for 6months I just upgraded the plugin and now I get this fatal error

### ISSUE THREAD

**Issue by nzhome** [woocommerce/woocommerce-paypal-payments#980]
Error Details
=============
An error of type E_ERROR was caused in line 115 of the file /nas/content/live/evoscan/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/WebhookModule.php. Error message: Uncaught Error: Class 'WooCommerce\PayPalCommerce\Webhooks\Status\WebhooksStatusPage' not found in /nas/content/live/evoscan/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/WebhookModule.php:115
Stack trace:
#0 /nas/content/live/evoscan/wp-content/plugins/woocommerce-paypal-payments/bootstrap.php(54): WooCommerce\PayPalCommerce\Webhooks\WebhookModule->run(Object(Dhii\Container\CachingContainer))
#1 /nas/content/live/evoscan/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(73): {closure}('/nas/content/li...')
#2 /nas/content/live/evoscan/wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(86): WooCommerce\PayPalCommerce\init()
#3 /nas/content/live/evoscan/wp-includes/class-wp-hook.php(307): WooCommerce\PayPalCommerce\{closure}('')
#4 /nas/content/live/evoscan/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#5 /nas/content/live/evoscan/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#6 /nas/content/l

**Comment by nzhome** [comment]
I am a php developer, but I just can't see why updating the plugin from the plugin page would cause a class to go missing from the plugins folder. unless the update stuffed up the files that were supposed to be included?

**Comment by nzhome** [comment]
I also see a mention in the stack trace of a Dhii\Container\CachingContainer   which I have no idea what that is. something called PayPalCommerce   is that your guys?  maybe the update was supposed to reset or clear something that it forgot to do?

**Comment by InpsydeNiklas** [comment]
@nzhome Can you please try deleting the plugin and then install it again?
The plugin settings are currently going through a rework and some pages (like the webhook status page) were moved.
If any issues persist after reinstalling the plugin, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your WooCommerce system report. Thanks!

**Comment by nzhome** [comment]
wait.  so you purposefully broke the paypal plugin update mechanism. so you expect the entire world to pay for your mistakes by reinstalling it from scratch. you gotta be kidding.  i am gonna use Stripe from now on, and delete paypal from my site. this paypal thing is nothing but issues.
