### ISSUE TITLE
Backend Storage for the PayPalRequestIdRepository does not scale (558)

### ISSUE THREAD

**Issue by prettyboymp** [woocommerce/woocommerce-paypal-payments#983]
# Describe the Issue

Storing the `PayPal-Request-Id`'s in blog options doesn't scale well. During a higher transaction volume, the number of Id's being stored in the `ppcp-request-ids` option quickly grow in size.  Because object cache stores, like memcached, usually have their cache bucket threshold pretty low, this growth in options will lead to a point where it causes object caching of `alloptions` to fail, taking down higher traffic sites.

Specifically, the options for us had grown to over half a MB while storing nearly 4300 Request ID mappings.

An alternative storage mechanism outside of the options table needs to be developed for these, if storage is needed at all.

Storage may not actually be needed.  The idempotency key, e.g. `PayPal-Request-Id`, should be generated in the context of when a changing event is triggered as only that context would know whether any attempts to make a change are new commands or retries of previously failed commands.

As an example, it would be better if the caller to [`WooCommerce\PayPalCommerce\ApiClient\Endpoint\OrderEndpoint::capture()`](https://github.com/woocommerce/woocommerce-paypal-payments/blob/7ffbb5e159da5e126a1c6243b51ad115de7583d1/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php#L275) passed in an idempotency key rather than using one previously stored for the order.  That would allow the idempotency key to be based on the original nonce of the user submitting the order to be processed and captured, or by the action if it's being triggered by the action scheduler.  That would allow both of these outside, higher up, contexts to control whether to retry on a failure - where idempotency comes into play.

**Comment by ingenuitor** [comment]
I would agree 100%, when you have over 100,000+ orders it's a real issue with data management, less is always more. The options table is always a bad idea, it seems many plugins use this and no simple way to remove. Worse yet in some cases it's a serialized data mess. 

I feel by default there should always be a separated database for any plugin that needs to store data IMO and have a solid removal system. This will allow for better caching, scaling and just overall data / site management in general. 

Hence why they pushed the High-Performance order storage (COT) REF: https://developer.woocommerce.com/2022/09/16/high-performance-order-storage-call-for-testing-vol-2/

**Comment by darienjoseph** [comment]
Yes I'm finding my largest clients growing very quickly, needs to be sorted. Being an autoload = yes as well is also an issue
