### ISSUE TITLE
Non hookable price-format in PUI Gateway class

### ISSUE THREAD

**Issue by wolkenkrieger** [woocommerce/woocommerce-paypal-payments#986]
In PayUponInvoice add_action('woocommerce_email_before_order_table' ...

the price is build by 

`{$order->get_currency()}{$order->get_total()}`

but should be build by

`wc_price($order->get_total(), $order->get_currency())`

to be hookable via `wc_price_args()`

**Comment by Dinamiko** [comment]
Good catch @wolkenkrieger, thank you for letting us know :)
