### ISSUE TITLE
Impossible to apply changes and save

### ISSUE THREAD

**Issue by adroma** [woocommerce/woocommerce-paypal-payments#990]
### Describe the Bug

The plugin doesn't save changes, so it can't be shown in payment method into checkout page. As you can see in the attachment, the configuration is correct and connection between paypal and woocommerce is done!

### To Reproduce

1. Go to ' woocommerce/settings/payments'
2. Click on 'paypal'
3. Select 'Connection, standard payements',  …'
4. Click on SAVE

### Screenshots

In the attachment

 - WordPress Version 6.1
 - WooCommerce Version 7.1.0
 - Plugin Version 1.9.5
 - Browser Chrome latest version
 **- Any other plugins installed:**
mailchimp-for-wpadvanced-nocaptcha-recaptcha
allow-html-in-category-descriptions
appmysite
burst-statistics
checkout-field-editor-and-manager-for-woocommerce
classic-editor
codistoconnect
complianz-gdpr
cookie-notice
custom-post-type-ui
disable-cart-fragments
disable-comments
duplicate-page
duplicate-post
duracelltomi-google-tag-manager
electro-extensions
elex-woocommerce-role-based-pricing-plugin-basic
email-log
envato-market
extra-product-options-for-woocommerce
facebook-for-woocommerce
favicon-by-realfavicongenerator
finale-woocommerce-sales-countdown-timer-discount
fish-and-ships
flexible-refund-and-return-order-for-woocommerce
foobox-image-lightbox
google-site-kit
insert-headers-and-footers
jetpack
js_composer
klarna-order-management-for-woocommerce
klarna-payments-for-woocommerce
loco-translate
mas-static-content
mas-woocommerce-brands
meta-tags-for-seo
my-wp-login-logo
mykraft-responsive-video-shortcode
password-protected
pdf-poster
PDFEmbedder-premium
product-enquiry-for-woocommerce
raneri-danea
really-simple-ssl
redirection
redux-framework
revslider
robin-image-optimizer
role-and-customer-based-pricing-for-woocommerce
sitemap-by-click5
taxonomy-discounts-woocommerce
trackship-for-woocommerce
trustpilot-reviews
user-role-editor
vies-validator
w3-total-cache
webappick-product-feed-for-woocommerce
woo-advanced-shipment-tracking
woo-min-max-quantity-step-control-single
woo-product-bundle-premium
woo-product-filter
woo-smart-quick-view
woocommerce
woocommerce-abandoned-cart
woocommerce-google-adwords-conversion-tracking-tag
woocommerce-mailchimp
woocommerce-menu-bar-cart
woocommerce-pay-for-payment
woocommerce-payments
woocommerce-paypal-payments
wordfence
wordpress-importer
wordpress-seo
wp-all-export
wp-all-import-pro
wp-clone-by-wp-academy
wpae-woocommerce-add-on
wpai-woocommerce-add-on
wpsso
wpsso-google-merchant-feed
wpsso-wc-metadata
wt-woocommerce-related-products
yikes-inc-easy-custom-woocommerce-product-tabs
yith-woocommerce-compare
yith-woocommerce-wishlist

![Immagine 2022-11-15 102337](https://user-images.githubusercontent.com/44196060/201884772-60fb4709-db76-474e-8de9-e15628c174f5.png)

**Comment by InpsydeNiklas** [comment]
Hi @adroma,

Most likely, the [checkout-field-editor-and-manager-for-woocommerce](https://wordpress.org/plugins/checkout-field-editor-and-manager-for-woocommerce/) plugin is breaking the PayPal Payments settings page. 
When this plugin is disabled, the settings should save correctly. I suggest reaching out to their plugin support to have the conflict resolved. PayPal Payments uses non-standard fields in the settings, which may not be anticipated by this plugin.
If the problem persists for you with this plugin disabled, please consider [reaching out to the PayPal Payments support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!

Kind regards,
Niklas
