### ISSUE TITLE
"No se pudo recuperar pedido" in check out

### ISSUE THREAD

**Issue by PabloCabelloo** [woocommerce/woocommerce-paypal-payments#994]
Buyers can't pay with paypal. 
Error apperared is "no se pudo recuperar pedido"

**Comment by Sirvijver** [comment]
Hello @PabloCabelloo 

We do not support our plugin via GitHub, so we would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

When you do, please provide the system report, the plugin logs (if available), the error you are seeing and any screenshot that could help us link this to any known issue.

I will mark this thread as closed and wait to let the support team help you once you open the support request with them.

Kind regards, 
Joost
