### ISSUE TITLE
PAYEE_ACCOUNT_RESTRICTED The merchant account is restricted.

### ISSUE THREAD

**Issue by hasanqrq** [woocommerce/woocommerce-paypal-payments#995]
I have a problem with payments gateways in WordPress PayPal, the following error appears when trying to pay by plugin 👍 PAYEE_ACCOUNT_RESTRICTED The merchant account is restricted.

**Comment by InpsydeNiklas** [comment]
Hi @hasanqrq,

This errors means there is a restriction on your merchant account. This is not a technical problem and must be resolved by contacting the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/).
For any other questions, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!

Kind regards,
Niklas
