### ISSUE TITLE
Support for woocommerce-product-bundles

### ISSUE THREAD

**Issue by DalbertHab** [woocommerce/woocommerce-paypal-payments#998]
### Describe the Bug

Add support for woocommerce-product-bundles so the Smart button works on the product single pages.
At the current state the bundled products are not transfered. You can pay at Paypal but afterwards you get an error that your cart is not configured properly as configured bundle options are not transmitted to the woocommerce backend.

### To Reproduce

1. Install Paypal Payments
2. Install Woocommerce Product Bundles
3. Configure a Bundle with a selection
4. Try to buy the product at the single page with the paypal button without selecting a bundle option

### Environment

- https://woocommerce.com/products/product-bundles/ - 6.17.3
- woocommerce-paypal-payments - 1.9.5

### Additional Details

In the SingleProductActionHandler.js#L48 there should be a check if the product is a bundled product (form.bundle_form) and if so submit the selected products

**Comment by InpsydeNiklas** [comment]
Last time I checked, there was only a problem when the bundle contained a variable product, but not when it's made of simple products. Is this what you mean by "Configure a Bundle with a selection"?

In any case, if you encounter any problems with the buttons on the single product page for certain product types, you can disable the buttons for with a filter: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-smart-buttons-on-the-single-product-page-for-specific-products
Supporting bundles or product add-ons from the single product page is not always trivial, but the team is looking into adding broader support for the buttons on the single product page.

**Comment by DalbertHab** [comment]
We have several bundles t containing 2 fixed products and the customer has to choose an additional one out of a aselection of 4. The customer has to choose one product to complete the bundle in order to add it to the cart. If no selection is made, the "Add to cart" button from Woocommerce is disabled. The Paypal Smart button from the woocommerce-gateway-paypal-express-checkout plugin is disabled, too. Your button is the only one that's enabled even if the customer makes no choice.

Best regards
David

**Comment by sam-messina** [comment]
I am also experiencing this issue with the PayPal button not working on these bundles. Any update on a fix?

**Comment by InpsydeNiklas** [comment]
This was resolved a while back and appears to work with variable product bundles as of 2.4.0.
As soon as the "Add to Cart" button is inactive (e.g. due to a variable product selection not being made), the PayPal buttonsare as well.
If you continue to encounter any problems with product bundle setups, I recommend contacting our [support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!
